### ISSUE TITLE
User merging: UserActions has records for each merged identity

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1009]
I'm not sure if this is desired behavior, or if the frontend should be deduplicating apps/packages, but the current state of things is that merging users will get you duplicate app buttons.

To reproduce:

1. Create demo user.
2. Install Filedrop
3. Sign in as any free user.
4. Sign out.
5. Create second demo user.
6. Install Filedrop (again)
7. Sign in as same user from step 3.
8. View two copies of FileDrop in the apps page.

![screenshot-3](https://cloud.githubusercontent.com/assets/307325/10441071/a53d8faa-70f9-11e5-80e2-bfbc4bb99e1e.png)

**Comment by zarvox** [comment]
As discussed on IRC: the approach we'd like to go with to solve this and preserve information for unmerging is: 

On merge, don't transfer UserActions, but copy any actions to the target if the target account doesn't already have actions for that app.

**Comment by dwrensha** [comment]
Closing, as we no longer support account merging.
