### ISSUE TITLE
Admin stats page: API token section could use some explanation

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1010]
This is at the bottom of the stats page:

![screenshot-3](https://cloud.githubusercontent.com/assets/307325/10441834/0260a08e-7102-11e5-8c87-207f06ad323f.png)

It's not clear what this is, or what that link is going to point to.

Perhaps a checkbox labeled "Enable machine-readable stats link" and a brief paragraph explaining what this is/does:

If you want to use this data with a separate viewing program, you can allow retrieving these stats as a JSON object by enabling this checkbox and fetching the randomly-generated link below.

Or something like that.

**Comment by ocdtrekkie** [comment]
This is already done, currently it looks like this:

![image](https://user-images.githubusercontent.com/4399499/74382827-b175e600-4db3-11ea-82d6-d3506df04c93.png)
