### ISSUE TITLE
Using two Sandstorm tabs at once can cause a "(unknown grain)" forever state

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1018]
Steps to reproduce:
1. Prepare two user accounts on the same Sandstorm; call them user1 and user2.
2. (Seemingly) Make sure they're not in each other's contacts
3. As user1, create two grains (call them grain1 and grain2). Create sharing links for each (call them sharelink1 and sharelink2)
4. As user2, log into Sandstorm, then open sharelink1 and sharelink2 in different browser tabs.
5. With the browser tab for sharelink1 open, notice a question about if you want to reveal your identity, Click "Reveal my identity".
6. Visit the browser tab for sharelink2.

Expected behavior:
- Browser tab for sharelink2 shows the grain2.

Actual behavior:
- Browser tab for sharelink2 is in some half-loaded state forever and will never truly load until you click "Refresh" in your browser.

![spin-forever](https://cloud.githubusercontent.com/assets/25457/10466640/180633ec-71aa-11e5-93f4-6860358ec3c4.png)

**Comment by dwrensha** [comment]
Heh, nice. Looks like you found a race condition in my code.

**Comment by paulproteus** [comment]
: D

**Comment by dwrensha** [comment]
I cannot reproduce this currently, I think because we now always ask the user which identity to reveal, regardless of what the contacts situation is.

**Comment by paulproteus** [comment]
I've been meaning to file a bug about that behavior! But since the current
code can't repro this, feel free to close.

**Comment by paulproteus** [comment]
I'm closing this since I filed it and haven't seen it in a year :)
