### ISSUE TITLE
More Info on Sign-in Page for First-time Users: Why Use Sandstorm?

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1020]
Based on user tests:
- they were not sure what to expect after log-in
- they were confused as to why Sandstorm is a much better option than alternatively using equivalent apps (not through Sandstorm)

Since we have the real estate maybe it would make sense to provide some additional context here.

**Comment by paulproteus** [comment]
I understand this is nearly done?

**Comment by neynah** [comment]
Yes. Resolved by @kentonv. Will close it for now unless the next user tests say otherwise. :)

**Comment by paulproteus** [comment]
Oh my goodness it looks so good.
