### ISSUE TITLE
icon not showing when running app with spk dev

### ISSUE THREAD

**Issue by chandnipatelTW** [sandstorm-io/sandstorm#1038]
When running spk dev, the grain icon set in sandstorm-pkgdef.capnp does not show, instead it shows the autogenerated icon.  

Once you package the app with spk dev and upload it to sandstorm the grain icon set in the metadata shows.  

The appGrid icon shows correctly in both cases.

**Comment by paulproteus** [comment]
Thanks for filing this!

I seem to recall @zarvox ran into this, too.

**Comment by zarvox** [comment]
Yep, I think that lookup path completely fails to check dev packages.  sandstorm-io/vagrant-spk#72 appears to duplicate this report.

I'll see if I can get to this soon.
