### ISSUE TITLE
Improve install app confirmation page.

### ISSUE THREAD

**Issue by nhducit** [sandstorm-io/sandstorm#1043]
I think we should provide user more information about application will be installed rather than just display this simple prompt.

![install this app](https://cloud.githubusercontent.com/assets/4246176/10562676/4b441d78-7592-11e5-8a13-9c5aa1475916.png)

**Comment by ocdtrekkie** [comment]
I believe this is already in progress, as part of including the Keybase verification during the install process. It's also a duplicate of #15.

**Comment by neynah** [comment]
I agree. (We're working on it!) :D

**Comment by paulproteus** [comment]
FWIW #1058 is where we're working on it.

**Comment by zarvox** [comment]
Strictly, that PR doesn't change the install page.  But it is a good base to build on when reworking that flow!

**Comment by paulproteus** [comment]
Mm, right.​
