### ISSUE TITLE
Solid emial server implementation for Sandstorm?

### ISSUE THREAD

**Issue by taoeffect** [sandstorm-io/sandstorm#1045]
I notice that Sandstorm [has Roundcube](https://apps.sandstorm.io/app/0qhha1v9ne1p42s5jw7r6qq6rt5tcx80zpg1f5ptsg7ryr4hws1h), but it seems to be a webmail client, not a real email server.

Myself and a friend forked Alex Payne’s Sovereign project to improve it and distill it down to its core email part. We called it [Empress Mail](https://github.com/taoeffect/empress/), and even implemented an email-migration feature to help people leave the clutches of centralized services like Gmail (which have been [abusing](https://lobste.rs/s/ckfyqd/the_hostile_email_landscape) their users).

However, it’s still not quite production ready and could use a little more work to get there.

Does Sandstorm have interest / need-for in a solid standalone email server app?

**Comment by paulproteus** [comment]
Hi @taoeffect ! I would love to make inbound and outbound email work well for people, within Sandstorm.

I see on GitHub that it says you're in the Bay Area. Is that right? If so, maybe we can catch up in person sometime. Tue Oct 20 evening/afternoon perhaps?

I'll also try to braindump to this ticket the current state of email in Sandstorm, so that we're both on the same page.

**Comment by taoeffect** [comment]
Yep, I'm in the Bay Area. Not sure I can meet up tomorrow in person but definitely via a video chat. See the left sidebar [here for my contact info](https://fixingtao.com/) (visible on a wide screen) and send me an email. :)

> I'll also try to braindump to this ticket the current state of email in Sandstorm, so that we're both on the same page.

Sounds good. :+1:

**Comment by paulproteus** [comment]
Thanks for the email pings & github issue pings. I started that thread on sandstorm-dev -- https://groups.google.com/forum/#!topic/sandstorm-dev/67XicD9oFLc -- and let's move this there, I figure.

Once we have specific next steps, we can turn those into GitHub issues etc.
