### ISSUE TITLE
cannot log in: getaddrinfo ESRCH

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#1047]
After applying #1030, I am unable to log in with Github or Email authentication. I see the following error in /opt/sandstorm/var/log/sandstorm.log:

```
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Github. getaddrinfo ESRCH
    at getAccessToken (packages/github/github_server.js:46:1)
    at Object.userAgent [as handleOauthRequest] (packages/github/github_server.js:5:1)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
    at middleware (packages/oauth/oauth_server.js:173:1)
    at packages/oauth/oauth_server.js:146:1
```

**Comment by zarvox** [comment]
Hmm, that's no good.  This is on Arch Linux, right?  A few questions to aid debugging:

* Are any of `/etc/hosts`, `/etc/resolv.conf`, `/etc/gai.conf`, or `/etc/nsswitch.conf` symlinks to things not under `/etc`?
* What do the uncommented lines of your `/etc/nsswitch.conf` and `/etc/gai.conf` look like?
* What files are needed for name resolution to work on your machine?  (You could try `strace`-ing the `tmp/dnstest` as we do in `make-bundle.sh` to see what files are accessed.  If there are things under `/etc` that aren't in the bundle's `etc.list`, feel free to add them to the whitelist in `make-bundle.sh`.)

**Comment by dwrensha** [comment]
This is on Ubuntu 15.04. My Arch box does not appear to have any trouble with the change.

**Comment by dwrensha** [comment]
Maybe relevant: this VM used NAT,  with a static IP configured in /etc/network/interfaces like this:

```
auto eth1
iface eth1 inet static
address 192.168.56.50
netmask 255.255.255.0
network 192.168.56.0
broadcast 192.168.56.255
```

**Comment by dwrensha** [comment]
I accidentally borked the machine where I originally saw this issue. I'm now working with a Ubuntu 14.04 machine. In that case, the error that I see is `getaddrinfo ENOTFOUND`.

> Are any of /etc/hosts, /etc/resolv.conf, /etc/gai.conf, or /etc/nsswitch.conf symlinks to things not under /etc?

Why, yes:
```
$ ls -l /etc/resolv.conf
lrwxrwxrwx 1 root root 29 Apr 19  2014 /etc/resolv.conf -> ../run/resolvconf/resolv.conf
```

> What do the uncommented lines of your /etc/nsswitch.conf and /etc/gai.conf look like?

/etc/gai.conf is completely commented out.

```
$ cat /etc/nsswitch.conf 
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat

hosts:          files mdns4_minimal [NOTFOUND=return] dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by dwrensha** [comment]
Hitting `getaddrinfo ESRCH` on Ubuntu 15.10 too.

**Comment by paulproteus** [comment]
Yeah -- I think if we add /run/resolvconf to etc.list that would work. I
don't know if that is unconscionably gross (pretending /run is part of
/etc), though.

**Comment by zarvox** [comment]
Yeah, the symlink that points out of /etc is definitely the problem here.  I guess we could do the same dance with binding `/run` to `/run.host` and symlinking /run/resolvconf, but that's not pretty.  Adding /run/resolvconf to etc.list without modifying the C++ will cause things to break - the code asserts that the target dir is under `/etc`.  Maybe we should rename it to "host-files-to-link.list" or something?

A workaround in the meantime would be to not use `resolvconf` (`sudo apt-get remove resolvconf`).  I'm not sure what things on Ubuntu depend on it, but NetworkManager is reasonably smart these days without it.

**Comment by dwrensha** [comment]
Yay, it works after `sudo apt-get remove resolvconf` and a reboot.

```
The following packages will be REMOVED:
  resolvconf ubuntu-minimal
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 313 kB disk space will be freed.
```
