### ISSUE TITLE
sandstorm-http-bridge buffering uploads?

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1054]
A user reports that during a large upload (actually, a git push in his case) sandstorm-http-bridge consumes increasing amounts of memory until finally being killed (presumably by the kernel OOM killer).

I thought that we supported streaming uploads, but this sounds like buffering. Need to investigate.

**Comment by eyedarts** [comment]
Thanks @kentonv! 

When I was watching the memory to see what was happening, I was actually doing a 'git pull' and downloading. The repo is about 200 MB. I'm not sure if those details make a difference or not. I was able to upload (git push) to both GitWeb and Gogs, but not GitLab. 'git pull' and 'git clone' fail with all of them.

**Comment by kentonv** [comment]
I guess if pulls fail that suggests that we're buffering downloads as well.

**Comment by dwrensha** [comment]
I am able to reproduce this behavior. Very interesting! Thanks for catching it, @eyedarts!

**Comment by dwrensha** [comment]
I suspect we are running into the issues predicted by [this comment](https://github.com/sandstorm-io/sandstorm/blob/8084ce42d6b5d06d67e5f818999cb8ac8e68fc38/src/sandstorm/sandstorm-http-bridge.c%2B%2B#L586-L591).

**Comment by kentonv** [comment]
@dwrensha Indeed! Of course downloads are buffering! We don't have any flow control. :/
