### ISSUE TITLE
UX: Send an invite

### ISSUE THREAD

**Issue by wtogami** [sandstorm-io/sandstorm#1057]
* + Share access
* Send an invite
* Type someone's e-mail address and send.

UX Bug: Form allows you to edit the address and personal message field, but you can't submit it again until you click "+ Send more invites", which wipes those fields.  Perhaps the fields shouldn't allow editing after they are sent, or the UI should allow sending again after it has been edited?

**Comment by zarvox** [comment]
Looks like this is approximately the same usability issue as #961

**Comment by wtogami** [comment]
yes, closing as duplicate of #961
