### ISSUE TITLE
more helpful [403] error text

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#1063]
Instead of "Unauthorized [403]" we can have this text: 

"Unauthorized [403]: Please ask the grain owner to click the Share Access button to send you an invite if you'd like to access the grain."

What do you think, @kentonv @paulproteus ? We could make it "grain owner or someone else with access" but I think brevity is nice.

**Comment by neynah** [comment]
Today it says: "You do not have permission to access this grain. Please sign in to request access."

Is this satisfactory @jadeqwang?
![5](https://cloud.githubusercontent.com/assets/855341/14055087/fb2d8e64-f29b-11e5-81a5-c9177dc8a9f3.jpg)

**Comment by kentonv** [comment]
I'm not Jade but I believe this is fixed. :)
