### ISSUE TITLE
Allow a single user to keep a grain open from multiple sessions?

### ISSUE THREAD

**Issue by ar-jan** [sandstorm-io/sandstorm#1066]
I quite often work from 2 computers at the same time (well, switching between them), and would like to be able to keep a single grain open on both computers. Currently, one of the grains will be disconnected:

`You have been disconnected. The connection to the server was lost. Force reconnect`

Admittedly working from 2 computers is itself suboptimal (I need/want to use both Linux and Windows). But, would this be possible?

**Comment by dwrensha** [comment]
Hi!

I suspect you are running into a known bug with the Etherpad app. See https://github.com/kentonv/etherpad-lite/issues/2.

Do you see the problem on apps others than Etherpad?

**Comment by ar-jan** [comment]
Ah, you're right. I've only seen this with Etherpad since that's what I use most. Just tested that this doesn't happen with e.g. ShareLaTeX.

Thanks, I'll comment on the Etherpad issue.
