### ISSUE TITLE
Incorrect ARIA markup on email signin form

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/sandstorm#1072]
Just noticed the following:

```
<form class="email" role="menuitem">
```

This is incorrect. The email form isn't a menu item. A menu item would be the actual item you click to bring up the email login screen (I.e. the button, link, etc.)

With this role in place, presentation is a bit odd but functional on my laptop. Unfortunately, it doesn't work at all on my Android devices running Firefox.

Thanks.

**Comment by paulproteus** [comment]
If you happen to know the right role, I'd be happy to submit a trivial patch for this!

Otherwise probably I'll wait until Drew is back (early next week) to sanity-check with him, since I'm not as aware of ARIA technical details as he is.

**Comment by ndarilek** [comment]
I'd just remove the role entirely for now. Roles are only really 
important if you aren't using semantic markup, which you're all tending 
toward in more recent versions, or if you're using something like tabs 
for which there is no equivalent HTML. It might be a good idea to add a 
role around there somewhere, but at this point the role breaks things 
more than it contributes. :)

Sorry, would just cut it myself, only I'm doing a few other things at 
the moment and trying to head out for the weekend. :) No rush either, I 
was able to log in by emailing a link to my phone from the laptop.

**Comment by paulproteus** [comment]
np, happy to submit a patch to remove a useless string!
