### ISSUE TITLE
Cannot launch any app

### ISSUE THREAD

**Issue by lafaye** [sandstorm-io/sandstorm#1074]
Hi, 

The installation is OK. I can log into sandstorm, and install any app (for example etherpad), 
but when I launch any app, I get a wheel turning forever.

In the debug window, I only see this:
** SANDSTORM SUPERVISOR: Starting up grain.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.

I installed sandstorm on my own server (Debian Jessie) with:
apt-get install curl
curl https://install.sandstorm.io | bash
I can the access to it using:
http://my.ownserver.fr:6080
(I changed my real server name to my.ownserver.fr).

Here is the content my /opt/sandstorm/sandstorm.conf file:
ERVER_USER=sandstorm                                                                                                                                       
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://myownserver.fr:6080
WILDCARD_HOST=*.myownserver.fr
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false

The two ports are open:
root@inuk:/opt/sandstorm/var/log# nmap localhost -p 6080

Starting Nmap 6.47 ( http://nmap.org ) at 2015-10-24 16:05 CEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000034s latency).
Other addresses for localhost (not scanned): 127.0.0.1
PORT     STATE SERVICE
6080/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 1.21 seconds
root@inuk:/opt/sandstorm/var/log# nmap localhost -p 6081

Starting Nmap 6.47 ( http://nmap.org ) at 2015-10-24 16:05 CEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000038s latency).
Other addresses for localhost (not scanned): 127.0.0.1
PORT     STATE SERVICE
6081/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.64 seconds

Please, help me. I do not know what to do to correct this problem.

Pierre

**Comment by dwrensha** [comment]
Looks like you need to set the port number on your wildcard host:

```
WILDCARD_HOST=*.myownserver.fr:6080
```

**Comment by lafaye** [comment]
I tried that also, but with no success.

**Comment by dwrensha** [comment]
It sounds like your wildcard DNS might not be resolving correctly. Does the following command return your server's IP address in its Answer Section?

```
dig -t a anything.myownserver.fr
```

**Comment by lafaye** [comment]
The IP address of my server is not in the output below (it is: ***.***.86.51).
Any advice on what I should do?

Thanks

root@inuk:~# dig -t a anything.myownserver.fr

; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> -t a anything.myownserver.fr
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 6390
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;anything.myownserver.fr.                IN      A                                                                                                            
                                                                                                                                                             
;; AUTHORITY SECTION:                                                                                                                                        
server.fr.               3600    IN      SOA     sma-10.domserver.ecole. hostmaster.domserver.ecole. 112 900 600 86400 3600                                     
                                                                                                                                                             
;; Query time: 1 msec                                                                                                                                        
;; SERVER: 10.165.120.10#53(10.165.120.10)                                                                                                                   
;; WHEN: Sat Oct 24 18:19:05 CEST 2015                                                                                                                       
;; MSG SIZE  rcvd: 127

**Comment by dwrensha** [comment]
These docs may help: https://docs.sandstorm.io/en/latest/administering/wildcard/

At some point you must have configured a DNS server to resolve `myownserver.fr` to your server's IP address. You'll need to also configure that DNS server to resolve `*.myownser.fr` to your server's IP address.

**Comment by lafaye** [comment]
Thanks a lot. I will ask the admin of DNS and I will get back to you if this does not solve the problem.

**Comment by lafaye** [comment]
This solved the problem. Thank you very much.
