### ISSUE TITLE
Fails silently to install new apps

### ISSUE THREAD

**Issue by icarito** [sandstorm-io/sandstorm#1089]
By examining logs I've found the following traceback:

```
Exception in queued task: TypeError: Cannot call method 'close' of undefined
    at Object.Sessions.find.observe.removed (app/server/proxy.js:402:13)
    at [object Object].observeChangesCallbacks.removed (packages/minimongo/observe.js:169:1)
    at self.applyChange.removed (packages/minimongo/observe.js:71:1)
    at packages/mongo/observe_multiplex.js:183:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at Object.task (packages/mongo/observe_multiplex.js:177:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
```

My sandstorm.conf file is as follows:
```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://beacon.example.org:6080
WILDCARD_HOST=*.beacon.example.org
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
```

I have successful DNS wildcard from *.beacon.example.org to this host.

**Comment by icarito** [comment]
![image](https://cloud.githubusercontent.com/assets/199755/10798562/391fda92-7d76-11e5-81c0-213c837031f7.png)

This is what it looks like to try to start a grain. The animation does not stop.

**Comment by jparyani** [comment]
Hey @icarito, it looks like your WILDCARD_HOST is missing a port (it should be `WILDCARD_HOST=*.beacon.example.org:6080`). The exception you're seeing *should* be unrelated noise.

**Comment by kentonv** [comment]
(#1090 fixes the exception)

**Comment by icarito** [comment]
This is very strange. I actually removed the port from the WILDCARD_HOST because I was getting getaddrinfo ENOTFOUND when attempting to install apps.

**Comment by icarito** [comment]
Anyhow it worked now for me, thanks!
