### ISSUE TITLE
"Session was never opened. [500]" on grain

### ISSUE THREAD

**Issue by rchrd2** [sandstorm-io/sandstorm#1103]
![screen shot 2015-10-28 at 11 53 46 am](https://cloud.githubusercontent.com/assets/182479/10861281/70d3308e-7f37-11e5-8473-58f1c5abfcb6.png)

I've had this error a few times. I think this is how to reproduce:
- open a grain
- leave it open in a tab all day
- put computer to sleep for a long time (like over night)
- wake computer
- grain is dead, and only way to restore is to refresh the window. The page has a error: "Session was never opened. [500]"

Refreshing the window is not ideal, especially when multiple tabs are open. Intuitively, I'd expect Sandstorm to detect that the grain has shut down, and start it back up again.

**Comment by kentonv** [comment]
Hmm, this was supposed to be fixed last week. @jparyani, thoughts?

**Comment by rchrd2** [comment]
It could very well be fixed. I took that screenshot on "2015-10-28 at 11.53.46 AM". I'll keep an eye on it and let you if the issue happens again.

**Comment by rchrd2** [comment]
This is confirmed. I left a grain open last night, put my computer to sleep, and checked it this morning. It was dead with the same 500 error message. The version my server is running is "Version: 0.128".

**Comment by dwrensha** [comment]
Did the server go to sleep too, or was it just the client?

**Comment by rchrd2** [comment]
As far as I know, the server did not go to sleep. It's installed on a Digital Ocean server that is running 24/7 so the machine definitely stayed up all night. Not sure if Sandstorm itself goes to sleep ever.

**Comment by rchrd2** [comment]
Here's another screenshot. Not sure if this helps. I'm starting to think it has something to do with the Meteor Socket losing it's connection. 

![screen shot 2015-11-01 at 11 40 47 pm](https://cloud.githubusercontent.com/assets/182479/10876921/2054003c-80f6-11e5-86b5-5f4f3e0addb9.png)
