### ISSUE TITLE
Sandcats SSL Expiring

### ISSUE THREAD

**Issue by maurer** [sandstorm-io/sandstorm#1109]
My sandstorm instance is serving an expired SSL certificate (expired about 12 hours ago). The sandstorm log's last line is:

```
Since Sun Nov 01 2015 18:25:26 GMT+0000 (UTC) is more than three days away from Sun Nov 08 2015 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
```

It's currently Nov 1, so a Nov 8 cert would be just fine, but this is not what the server is using.

**Comment by maurer** [comment]
Restarting the sandstorm service (`systemctl restart sandstorm`) caused sandstorm to begin using the correct certificates.

**Comment by zarvox** [comment]
@paulproteus I can confirm that I observed this issue before the restart with both curl and firefox.  Perhaps there's an issue in the SNI callback hotpatch logic?

**Comment by kentonv** [comment]
Randomly sampling some sandcats servers, I observe that there are a few hosts with certs that expired last night still using those certs, but among hosts that had certs expiring yesterday or the day before I haven't found any still using the expired certs. This could mean that (a) there is a problem specifically related to certs expiring last night (DST-related? n-days-after-update?), (b) servers tend to figure things out within a day, or (c) I don't have enough data points.

**Comment by paulproteus** [comment]
Thanks all for these reports. This is really interesting and I will work on
getting to the bottom of it. Sorry for the bad experience Matthew Maurer.
​

**Comment by ocdtrekkie** [comment]
I'll close this as I imagine if it happened more often or wasn't fixed we'd have seen it more in the last four years.
