### ISSUE TITLE
docs: Add information on how to move a Sandstorm install from one machine to another

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1129]
Notes to self/ things to keep in mind

* `/usr/local/bin/sandstorm` symlink

* systemd/rc.d service

* sandstorm user ID might change on new machine

This came about because @glyph asked me these questions.

**Comment by glyph** [comment]
Thanks @paulproteus !

**Comment by paulproteus** [comment]
You are welcome!
