### ISSUE TITLE
builid broken with latest libsodium

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#1137]
Recent Jenkins builds have been failing. E.g. https://build.sandstorm.io/job/Sandstorm%20PRs/1175/.

https://github.com/jedisct1/libsodium/commit/f56647ce4e8b9334128a7d972cc111e560337040 removed `crypto_scalarmult/curve25519/donna_c64/api.h` and dropped `crypto_scalarmult/curve25519/donna_c64/base_curve25519_donna_c64.c` from the autotools build, but kept the latter file checked in, even though it `#include`s the former.

Ekam tries to build every C file that it finds, so when it finds this file, it tries and fails.

**Comment by kentonv** [comment]
Looks fixed by https://github.com/jedisct1/libsodium/commit/c574ad86e52e89e23a624e5504e38c599e614473. Thanks @jedisct1.

**Comment by jedisct1** [comment]
I still would recommend using release tags instead of tracking the master branch, as that one can be broken, insecure, and kill kittens without any prior notice.

**Comment by kentonv** [comment]
@jedisct1 Yes, probably a good idea. I think at the time I set this up, I was using a not-yet-released interface for chunked hashing or something like that.

On the other hand, if a security bug is found in libsodium, I would like it to be hard for us to forget to update. Any chance you could add a branch called "release" which always points to the most recent release tag? That way the next Sandstorm release (which we do one or more times a week) will include the fix even if we missed the advisory.

**Comment by jedisct1** [comment]
How about a `stable` branch that includes code from the latest release, plus possibly important (not necessarily security-related) fixes that will be part of the next release?

**Comment by kentonv** [comment]
@jedisct1 That sounds perfect.

**Comment by jedisct1** [comment]
Done (minus updating the documentation).
You can now track the `stable` branch.

**Comment by kentonv** [comment]
Done: https://github.com/sandstorm-io/sandstorm/commit/0c4b4d106cf64ebb60ab73dd95137d54f9629bb5
