### ISSUE TITLE
docs: Regenerate against IE11-fixed version of readthedocs theme

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1151]
@zarvox filed https://github.com/mkdocs/mkdocs/pull/749

When it's fixed, we should rebuild the docs.

**Comment by paulproteus** [comment]
Self-assigning although there's no action to take until upstream merges that, unless we decide this is urgent enough to do ourselves.

**Comment by zarvox** [comment]
Upstream merged my fix.  Dunno if they've done a release since then.  Maybe this is fixed?  Check it when you have time?

**Comment by paulproteus** [comment]
Done now! Rebuild docs against mkdocs 0.15.
