### ISSUE TITLE
Menu cut off/does not scroll in landscape on Firefox Mobile 

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#1153]
When I'm have a grain open in landscape on my phone, four options on the hamburger menu are cut off, and the menu can not scroll or be dragged at all. I have Firefox on Android.

**Comment by spollard** [comment]
I can confirm this is still happening. I may take  a look myself since it seems like a small change...

**Comment by ocdtrekkie** [comment]
That'd be great! Note that I no longer have an Android, so I can't test this.

**Comment by spollard** [comment]
I just made a PR. Can somebody test it? #3354
I determined the changes by fiddling with the css in Firefox. I didn't want to setup a whole sandstorm dev env for just this tiny change....

I tested this at mobile width without any changes to other css. 

I tested this at desktop width also by forcing the grain items to be tall: 
body > .topbar > .navbar li.navitem-grain {   height: 320px;  }
