### ISSUE TITLE
Installation fails with your server never started listening

### ISSUE THREAD

**Issue by ovizii** [sandstorm-io/sandstorm#1156]
I am completely lost. I am trying to install on a server I own (a virtual one) which has its own dedicated IP and hostname say sandstorm.mydomain.tld 

now I started installing curl https://install.sandstorm.io | bash 
during the installation I chose myname.sandcats.io - the installation failed with: the server never started or some such.

I then thought I might have to change my servers hostname to myname.sandcats.io and gave that a try but nothign helped.

Can someone explain how this works? 
I can have my own wildcards DNS of course but I'd like to use sandcats.io for this since I heard it offers HTTPS too. 

Now in the FAQs I see: 
https://docs.sandstorm.io/en/latest/administering/faq/#why-cant-i-access-sandstorm-from-the-internet-even-though-the-server-is-running

WILDCARD_HOST=*.yourname.sandcats.io:6080

But my config file looks completely different: 
    SERVER_USER=sandstorm
    PORT=80
    MONGO_PORT=6081
    BIND_IP=0.0.0.0
    BASE_URL=http://myname.mydomain:80
    WILDCARD_HOST=*.myname.sandcats.io:80
    UPDATE_CHANNEL=dev
    ALLOW_DEV_ACCOUNTS=false

If I access myname.sandcats.io I get redirected to htts and I see 
    Error looking up DNS TXT records for host 'myname.sandstorm.io': queryTxt ENODATA
    This Sandstorm server's main interface is at: https://alpha.sandstorm.io
.....

**Comment by paulproteus** [comment]
Hi @ovizii ,

Thanks for filing this bug report. It looks like you're hitting some kind of serious issue, and I'd love to help you debug it.

I aim to get back to you tomorrow, around this time. If someone else is able to help you before then, I'd be grateful.

**Comment by ovizii** [comment]
there's no rush, I simply had some spare capacity so I created a new container with LXC based on a Debian 8 minimal template. I updated the sources and upgraded before attempting to install sandstorm.

I just need some clarification why my config file looks different and if I need to change my hostname or if my server keeps its FQDN and the sandcats story runs parallel?

**Comment by ovizii** [comment]
So, I tried again, and obviously I was overworked that evening I tired first as I just realized of course I keep my hostname, myname.sandcats.io is simply used as a wild card domain for the web server on my server. 

Still, no luck. 

Here is my config:
    root@bailey:~# cat /opt/sandstorm/sandstorm.conf
    SERVER_USER=sandstorm
    PORT=6080
    MONGO_PORT=6081
    BIND_IP=0.0.0.0
    BASE_URL=http://bailey.ict-consult.co.za:6080
    WILDCARD_HOST=*.ovizii.sandcats.io:6080
    UPDATE_CHANNEL=dev
    ALLOW_DEV_ACCOUNTS=false

trying to start it:
    root@bailey:~# sandstorm status
    Sandstorm is not running.
    root@bailey:~# sandstorm start
    Sandstorm started. PID = 1399
    root@bailey:~# sandstorm status
    Sandstorm is not running.

The log says:
    ** Server monitor died. Aborting.
    ** Starting Sandstorm at: Sat Nov 14 14:15:13 2015
    *** Uncaught exception ***
    sandstorm/run-bundle.c++:1090: failed: mount("none", "/", nullptr, MS_REC | MS_PRIVATE, nullptr): Permission denied
    stack: 0x4dd6f3 0x4dcb1f 0x4fb520 0x4fa6d9 0x4fa6ca 0x43ca41 0x43d6c5
    ** Server monitor died. Aborting.

This might be an issue because I am trying to set it up inside an LXC container? I then checked my host system and found apparmor is blocking sandstorm:
    Nov 14 15:21:10 james kernel: [109570.531049] audit: type=1400 audit(1447510870.554:10705): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-container-default" name="/" pid=21731 comm="sandstorm" flags="rw, rprivate"

How do I fix this, anyone tried sandstorm with apparmor?

**Comment by ovizii** [comment]
I tried assigning another apparmor profile to it: /etc/apparmor.d/lxc/lxc-default-with-mounting 

which contains:
# Do not load this file.  Rather, load /etc/apparmor.d/lxc-containers, which
# will source all profiles under /etc/apparmor.d/lxc

profile lxc-container-default-with-mounting flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/lxc/container-base>

# allow standard blockdevtypes.
# The concern here is in-kernel superblock parsers bringing down the
# host with bad data.  However, we continue to disallow proc, sys, securityfs,
# etc to nonstandard locations.
  mount fstype=ext*,
  mount fstype=xfs,
  mount fstype=btrfs,
}

but still no-luck.

**Comment by paulproteus** [comment]
Hi @ovizii ,

It seems like the LXC container is working fine, but apparmor is preventing you from using Sandstorm.

I know very little about apparmor. Is it important to you to keep apparmor? Note that Sandstorm containerizes itself and then containerizes all the apps, so it's not clear to me apparmor is helping you security-wise.

Can you set apparmor into complain mode, in order to figure out what rules you need, and then turn it back on?

Having said that, I think @jacksingleton was looking into either AppArmor or SELinux around Sanstorm; maybe he has some suggestions.

**Comment by paulproteus** [comment]
Having said all that, you will eventually run into a problem with this configuration. These two lines are not compatible:

```
BASE_URL=http://bailey.mydomain.tld:6080
WILDCARD_HOST=*.myname.sandcats.io:6080
# ... your other config options
```

because (due to the way web browsers work) BASE_URL and WILDCARD_HOST have to be on the same domain name.

So you'll probably be happiest if you configure it this way:

```
BASE_URL=http://myname.sandcats.io:6080
WILDCARD_HOST=*.myname.sandcats.io:6080
# ... your other config options
```

**Comment by paulproteus** [comment]
If you can adjust your config in the above way, and you can get past these apparmor troubles, I think you will enjoy your Sandstorm install!

I did some more searching and I read a few things.

In particular https://gist.github.com/gionn/7585324 - this documents how to permit Sandstorm to do a "bind mount", which should get you moving. That _should_ be able to get you moving, but you might have to fiddle with the permitted mount options until it does start.

**Comment by jacksingleton** [comment]
My impression was that running an AppArmor profile for Sandstorm isn't useful because AppArmor is path based and allowing bind mount allows all path based restrictions to be bypassed.

I'm also not experienced with AppArmor though, this was based on a first pass of research so could be wrong.

**Comment by ovizii** [comment]
hm, I think I managed to work around apparmor (by assigning it the unconfined profile) but when starting sandstorm I now see this in my logs instead of the above apparmor issues, does this ring any bells? 


sandstorm/run-bundle.c++:1090: failed: mount("none", "/", nullptr, MS_REC | MS_PRIVATE, nullptr): Permission denied
stack: 0x4dd6f3 0x4dcb1f 0x4fb520 0x4fa6d9 0x4fa6ca 0x43ca41 0x43d6c5
** Server monitor died. Aborting.
** Starting Sandstorm at: Sat Nov 21 11:27:26 2015
*** Uncaught exception ***
sandstorm/run-bundle.c++:1122: failed: mount("/dev/fuse", "dev/fuse", nullptr, MS_BIND, nullptr): No such file or directory
stack: 0x4dd6f3 0x4dcb1f 0x4fb520 0x4fa6d9 0x4fa6ca 0x43ca41 0x43d6c5
** Server monitor died. Aborting.
** Starting Sandstorm at: Sat Nov 21 11:33:53 2015
*** Uncaught exception ***

**Comment by paulproteus** [comment]
Sorry about that, semi-known bug:

To work around this for now, you can do:

```
modprobe fuse
```

Either we should `modprobe fuse` ourselves, or we should remove FUSE support when unavailable/unnecessary.

**Comment by ovizii** [comment]
That seems way over my head:
```
modprobe fuse
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.2.3-2-pve/modules.dep.bin'
```

All I could find via Google is that the reason might be that I am not using a generic kernel but one provided by my hypervisor: proxmox 
I'll keep digging :-)

**Comment by ovizii** [comment]
Got some instructions on the proxmox forum (see here http://forum.proxmox.com/threads/24773-I-would-like-to-see-an-appliance-for-sandstorm-io ) and got it to work. Thanks for your pointers. Now I can start playing :-)

So this thread "could" be closed except this sandstorm instance seems to work on HTTP not HTTPS. I tried the suggestions from here: https://docs.sandstorm.io/en/latest/administering/sandcats/#how-the-https-service-works but its still not running on HTTPS.

Any further pointers?

**Comment by ovizii** [comment]
Found the solution here: https://docs.sandstorm.io/en/latest/administering/ssl/

**Comment by paulproteus** [comment]
Great!
