### ISSUE TITLE
Installer: Port 80 question happens even if I said "no"

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1158]
If I answer "no" for "OK to continue?", the installer script still does the port 80 openness check and asks me if it's OK to use port 6080. My answer to that question doesn't matter, since the next thing the installer does is fail out due to my having answered "no" earlier.

**Comment by paulproteus** [comment]
This is pretty hilarious (also a sad bug). Thanks for the bug report.

**Comment by paulproteus** [comment]
I've just pushed a branch containing a patch for this. I'll verify this within 0-2 weeks.

**Comment by paulproteus** [comment]
It should be "easy" to fix this in the next 2 weeks, so I'll leave it assigned to me and attempt to do so.

**Comment by ocdtrekkie** [comment]
So this one appears to already have a fix on a branch, which just hasn't been verified? Should we open a PR from that branch? GitHub still believe it's able to merge, so presumably all we need is for someone to check the work here.
