### ISSUE TITLE
Rocket.chat - files uploaded to chat point to 127.0.0.1 - not unavailable

### ISSUE THREAD

**Issue by thomasfrivold** [sandstorm-io/sandstorm#1163]
When I upload a file in a rocket.chat session, the URL looks like this:

File Uploaded: *hnkCbBd.jpg*
http://127.0.0.1:8000/ufs/rocketchat_uploads/tPD532LniP3ScEiqh.jpg

Dave, that doesn't work

**Comment by ocdtrekkie** [comment]
Tagging @Sing-Li but you may want to file the report on https://github.com/RocketChat/Rocket.Chat specifying it refers to the Sandstorm package.

**Comment by zarvox** [comment]
See https://github.com/RocketChat/Rocket.Chat/issues/910

**Comment by Sing-Li** [comment]
Fixed in v0.9.0.  Please close.

**Comment by zarvox** [comment]
Thanks @Sing-Li !
