### ISSUE TITLE
Opening a shared link without being logged in to Sandstorm causes the black Sandstorm bar to overlap with the app

### ISSUE THREAD

**Issue by simonv3** [sandstorm-io/sandstorm#1164]
I shared this app instance with someone who isn't logged in, and testing it myself, I can't see the top half of the grey bar. (there should be an Ideas and a Boards). 

Link:

https://oasis.sandstorm.io/shared/9CThct6PeQJt-wF1MJnRAC4XczoukXD5MkcpZOlj_v4

This probably has something to do with a `position: fixed` value on the css. Does the body have to be pushed down x amount of pixels?

**Comment by kentonv** [comment]
AFAICT the app is not placing any content in the gray bar. It's not hidden: if you open the iframe in a new window, the gray bar looks exactly the same. The DOM inspector also shows no content in the gray bar.

It looks to me like the app is not filling in the gray bar when the user is not logged in.

**Comment by simonv3** [comment]
@kentonv you're right, I had a similar experience recently which made me realize it was a bug in the app. I haven't pinpointed it yet, but it's a bug in Idea Otter, not here. Should have come and closed it.
