### ISSUE TITLE
Grains fail to load when SockJS falls back to long polling

### ISSUE THREAD

**Issue by jacksingleton** [sandstorm-io/sandstorm#1186]
Meteor apps use SockJS which falls back to long polling when websocket connections fail.

However when running in Sandstorm on a server without websocket support (or being proxied through a webserver without support) grains get stuck in a reload loop.

But Sandstorm Shell does work, successfully falling back to long polling.

This is quite easily reproducible by setting up nginx as a reverse_proxy to Sandstorm using the config here: https://github.com/iflowfor8hours/sandcastle/blob/master/templates/reverse_proxy.conf.j2 but ripping out the websocket configuration.

I've attached tcpdump captures from the shell and wekan without websocket forwarding configured that I was looking at to attempt to debug this.

[shell.txt](https://github.com/sandstorm-io/sandstorm/files/40717/shell.txt)
[wekan.txt](https://github.com/sandstorm-io/sandstorm/files/40718/wekan.txt)

**Comment by jacksingleton** [comment]
Some more research:

I tried an app directly using SockJS (without Meteor) and found that it worked fine, so this might just be a thing with Meteor apps.

The error that repeats a couple times in wekan.txt originates from the meteor function `defaultResumeLoginHandler` here: https://github.com/meteor/meteor/blob/master/packages/accounts-base/accounts_server.js#L990

This function ends up getting called when loginWithToken is called by meteor-accounts-sandstorm. I checked the response from `GET /.sandstorm-credentials` and it is generating and returning the token successfully. I then (after stopping the app) checked the users collection for the grains mongo db, where Meteor stores a hash of the token. I found the correct hashes for the tokens I could see were being returned.

So then I tried disabling meteor-accounts-sandstorm... and still refresh loop. So I think the login error is a side effect of the problem not the cause.

**Comment by paulproteus** [comment]
The new refresh loop without meteor-accounts-sandstorm -- does this still
have the 403 from defaultResumeLoginHandler?​ Just curious.

**Comment by kentonv** [comment]
I wonder if Meteor's reload-safetybelt could be involved.

**Comment by jacksingleton** [comment]
@paulproteus yeah I can double check that may get a chance tonight

@kentonv interesting, first time I've heard of that package. I can probably find a way to disable it to test the theory
