### ISSUE TITLE
Configure advice for Google auth slightly wrong

### ISSUE THREAD

**Issue by pdehaye** [sandstorm-io/sandstorm#1188]
One of the URLs suggested when setting up Google login is slightly wrong. 

For step 5:

Set Authorized Javascript Origins to: https://my-awesome-subdomain.sandcats.io/

Google complains about this, it should not include the trailing "/"

**Comment by frigginglorious** [comment]
Thought it would be an easy tackle, but I was grepping around in files for that dialogue and couldn't find anything. I asked in IRC and this is what I got:

> kentonv: the instructions you're trying to update are in Meteor
> kentonv: the Meteor `google` or `accounts-google` package.

**Comment by dwrensha** [comment]
Fixed by #1835.
