### ISSUE TITLE
multi-identity lets you unlink your last identity from your account

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1191]
![account](https://cloud.githubusercontent.com/assets/307325/11352073/0ea5331a-91ef-11e5-87b0-1135dc5decb7.png)

This leaves your account in a rather-awkward state:

![account1](https://cloud.githubusercontent.com/assets/307325/11352102/3b4607e6-91ef-11e5-97a2-29d518fbb779.png)

You can still install apps, but when you try to create instances of grains, that fails with 

`TypeError: identity is undefined` in `shell.js`

We should at least not show the UI for unlinking your last identity.  Perhaps even stricter checks should be enforced (can't unlink last login identity?  something else?)

**Comment by dwrensha** [comment]
Fixed in #1226.
