### ISSUE TITLE
"Login enabled" button: lets me disable only login identity, is unstyled, is confusing to screenreader

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1192]
![account1](https://cloud.githubusercontent.com/assets/307325/11352273/53298a1c-91f0-11e5-8989-f0ca35549648.png)

We should probably not let you disable your last login identity.

We should definitely style the control in some way.

If the control is a `<button>`, it should describe an action which will trigger when activated.  If it is some other control that usually indicates state (nouns) rather than actions (verbs), then that's fine, but we should switch the control.  As it is now, it's going to be rather confusing for screenreader users.

**Comment by dwrensha** [comment]
Fixed in #1226.
