### ISSUE TITLE
Can't verify email addresses for service-related notifications without admin configuring email

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1193]
Maybe we should disable the UI and add a note if the server admin has not configured email, if that's knowable without having to do a Meteor method call.

We do show the text "Email identity service is disabled." when the user tries to add an email to be verified, but the admin hasn't configured email yet, but maybe we should hint this failure earlier, or give the affected user something actionable like "Contact your server administrator to fix this."

**Comment by zarvox** [comment]
As a bonus, I also get the same error message in my account dropdown, even though I didn't interact with that dropdown at all and it seems out of place:

![account1](https://cloud.githubusercontent.com/assets/307325/11353078/f94a5a6c-91f4-11e5-8bbe-6bc6b29f9391.png)

**Comment by dwrensha** [comment]
Fixed in #1226.
