### ISSUE TITLE
Switching primary email address is confusing

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1195]
The radio button switches, but there's no indication that an RPC took place and that the state got immediately saved server-side.

It would be more usable (and indeed, more testable too!) if the UI had several states:

* Initial state on page load
* Triggered (RPC is away, but unconfirmed yet)
* Completed (RPC completed, new state set)
* Failed (revert to previous state, show failure message)

An additional UI trouble: if I'm using a screenreader, it's not even *possible* for me to read through the list of confirmed emails without changing my primary service email, and I'm very likely to unintentionally change that setting without noticing, since there's no feedback that switching the radio button is causing a server-side change.

**Comment by neynah** [comment]
Yeah that sounds pretty bad. We can adjust it and add a button like github's.

![image](https://cloud.githubusercontent.com/assets/855341/11355057/934ce362-9206-11e5-9b77-7b7ed359f235.png)

**Comment by paulproteus** [comment]
Yay doing what other people do! Honestly quite serious.​

**Comment by neynah** [comment]
@paulproteus but in a purple way.

**Comment by dwrensha** [comment]
Fixed in #1226.
