### ISSUE TITLE
Support PATCH method outside of API

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/sandstorm#1218]
Loomio is transitioning from a single app to an API back-end with an HTML/JS front-end. At this time, however, I don't think they've decoupled the two. They're using PATCH in some places, and these requests are failing because the HTTP server for grain instances doesn't appear to implement PATCH. I'd rather not change their underlying API by switching methods, nor do I want to route everything through the API host to get PATCH support.

Any chance that the grain HTTP implementation can be made to support PATCH requests?

**Comment by kentonv** [comment]
I agree Sandstorm should be made to support PATCH. @mnutt I don't suppose you'd be interested in working on this, since you know exactly where it goes? :)

**Comment by ndarilek** [comment]
I actually don't know where it goes, it was someone else on the list and 
I haven't touched C++ since college. :( Sorry.

**Comment by ndarilek** [comment]
Er, never mind, just saw that the last sentence wasn't addressed to me. :)

Still very interested in this though. I may be able to hack around it 
temporarily--I think Rails used to have a hack that makes the method 
whatever value was passed as some query parameter or other but I don't 
recall the specifics.

**Comment by rdbartlett** [comment]
Rich from Loomio here :)

We're getting an increasing volume of requests for a secure version of Loomio, especially from activists working in really dangerous parts of the world. Sandstorm seems like the perfect solution. 

If there's anything we can do to support someone to resolve this PATCH issue, please let me know. It would really make a big impact for people doing amazing work in the world.

:heart:

**Comment by paulproteus** [comment]
Wow, that's great! Thanks for chiming in, @rdbartlett . I'll see what we can do.

**Comment by rdbartlett** [comment]
Thanks for the prompt injection of enthusiasm @paulproteus :dancer: 

Just cross-referencing here to the relevant conversation happening in Loomio: https://www.loomio.org/d/yw0D8Sc6/help-porting-loomio-to-sandstorm

**Comment by paulproteus** [comment]
Given that #1465 is resolved, I'm going to mark this as closed. Thanks to all who requested it, worked on it, reviewed it, nudged us, and more.
