### ISSUE TITLE
Infinite loading grain

### ISSUE THREAD

**Issue by BackIsBachus** [sandstorm-io/sandstorm#1232]
Hi everyone,

I recently installed Sandstorm (with the default conf) installed an app to see if everything was fine, but when I created a grain I just have the spinning animation telling me that it is loading and it never seems to end. I see the grain I created in the list of grains I own and the only log line I have after startup is:
```
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
```
I tried this with several apps (Etherpad, LaTeX, Rocket.Chat and a few others), tried restarting sandstorm and the server but this issue seems to persist.

Could it be a configuration problem on my side or an interference with another software (and therefore not a problem from Sandstorm)?

Config and other software running :
* Dedicated Server
* Debian Jessie
* 4GB RAM
* Apache2
* MySQL
* fail2ban

**Comment by zarvox** [comment]
This sounds like what happens when DNS for the main Sandstorm hostname is pointing at Sandstorm correctly, but the wildcard subdomains are not pointing at Sandstorm.  Some more docs here: https://docs.sandstorm.io/en/latest/administering/wildcard/

**Comment by BackIsBachus** [comment]
Indeed it was a problem with the wildcard, I reinstalled it clean and it works, thanks and sorry for the trouble!

**Comment by memento** [comment]
Hello, I have the same problem.
I run Deian Jessie on a dedicated server.
I installed sandstorm on a fresh install (just after installing curl) by typing this command :
```
curl https://install.sandstorm.io | bash
```
All went well.
my sandstorm domain ___thing.sandcats.io___ (I changed the subdomain) is accessible (ports allowed on router) and I can get to ___https://thing.sandcats.io/apps___, no problem (except I don't have the apps thumbnails).
![OK](http://oi68.tinypic.com/jagbpz.jpg)

The installation of any app goes well, but when i try to "open" a grain, it's spinning forever.
![problem](http://oi67.tinypic.com/1r9reu.jpg)

**Comment by memento** [comment]
Grain loading log : 
```
Debug log: Untitled GitLab repository

...e; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Starting up grain.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.


```

**Comment by memento** [comment]
Anyone ?

**Comment by ocdtrekkie** [comment]
As the above said, it's very likely to be an issue with your DNS not being setup for the wildcard.

https://docs.sandstorm.io/en/latest/administering/wildcard/

**Comment by memento** [comment]
Actually, I re-routed the ports 80 and 443 directly on the debian server (with sandstorm on it) and it works, so I don't think it has anything to do with the DNS. By the way, when you say DNS, as I don't have a DNS server on my server, what did you suggest I should do ? I don't owe the domain ___thing.sandcats.io___. So, no DNS registar acount configuration.

**Comment by ocdtrekkie** [comment]
I'm not a Linux guy, you're going to probably need to wait for one of the Sandstorm team folks to help you with this. Generally, for Sandcats.io setups, most of the DNS stuff is handled for you, and usually the default configuration for that all works.

But every time someone has talked about all the apps 'infinitely loading', it's been an issue with the wildcard DNS. The grains are technically up, but it's not able to reach them.

**Comment by memento** [comment]
I think I doing it wrong with the forwarding configuration of NginX (on the Raspberry Pi). Thanks for trying, I appreciate :)

**Comment by kentonv** [comment]
@memento Are you accessing your Sandstorm server over HTTP or HTTPS?

I don't understand how your nginx config can work for HTTPS, since nginx would need to have an SSL certificate for the host. Did you configure this somehow?

**Comment by memento** [comment]
Hi !
I access my sandstorm server over HTTPS thanks to the automated script that generated the certificates itself.

**Comment by kentonv** [comment]
@memento OK, but the problem is that you can't put nginx in front of an HTTPS server unless you configure nginx with the right certificates and private key. It's not good enough if just the server _behind_ nginx has the key, because nginx itself also needs the key in order to look at the requests and find out what host they're going to. But Sandcats changes its keys all the time, so you probably don't want to try to copy those keys over to nginx, since you'd need to be updating it constantly.

So I'm confused how you could be accessing your server at all over HTTPS. I don't think it should be working at all.

The easiest thing for you to do is redirect your port 443 from your router directly to your Sandstorm server, skipping nginx on the Raspberry Pi. If you aren't serving any other HTTPS sites on your nginx then this should work fine -- you cans till send regular HTTP requests through nginx to be routed as you see fit.

If you are serving other HTTPS sites at the same IP, then you probably can't use Sandcats HTTPS and will instead need to obtain your own wildcard certificate for your own domain. (Or, you'll need to write scripts that update nginx's certificates from your Sandcats server whenever they change, but this will be complicated.)

Does that help?

**Comment by memento** [comment]
Yes, it's a mistery.
Thank you for your answer, you rock
And thank you for your work, in general !

**Comment by paulproteus** [comment]
Hi @memento,

Did you manage to get this issue fixed? I'd love to know either way, yes or no.

Thanks!

**Comment by memento** [comment]
Hi @paulproteus , it works now the server hosting sandstorm is right behind the router, with ___no___ Raspberry Pi forwarding the http(s) requests anymore.

Yes, now, it works like a charm.
Have a good night !

**Comment by paulproteus** [comment]
Great! Super happy to hear that.

**Comment by nagendra-prasad** [comment]
@memento  even am facing excat issue any help would be greatly appreciated..
