### ISSUE TITLE
sessions are not automatically refreshed when permissions change

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#1241]
1. Alice shares a Groove Basin grain with Bob.
 2. Bob opens a session to the grain.
 3. Alice adjusts the permissions on the share token.
 4. Bob should immediately get a new session with the new permissions. Currently he needs to manually refresh the page to get this to happen.

This is broken not just on master but on the currently live release. I suspect it broke with the changes in #867 and #1071.

**Comment by jparyani** [comment]
The intent was that open websockets would be closed, and upon any new request, apps would get the correct headers. In practice, a lot of apps are not sophisticated enough to detect permissions changing in this manner, and probably would like a refresh. 

#1242 fixes a bug in that websockets were not always being closed correctly on permission changes.

**Comment by dwrensha** [comment]
Thanks! Looks fixed to me now.
