### ISSUE TITLE
When trying to log in as non-login identity, clicking on cards should initiate login as that identity

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1243]
When I log in as a non-login identity, I'm presented with a list of the identities which cat log into accounts connected to my identity. Currently the list is not clickable, so the only thing I can do is "go back". Instead, Clicking on an identity in this list should initiate login with the corresponding provider.

Of course, for OAuth login, if the user happens to be logged into that OAuth service under *some other* identity than the one they clicked on, they'll end up logged in as that other identity instead. This is unfortunate, but should be unusual, as most people don't maintain multiple Google/Github accounts, or at least won't have logged into Sandstorm previously with a different Google/Github account.

**Comment by dwrensha** [comment]
Fixed in https://github.com/sandstorm-io/sandstorm/pull/1837.
