### ISSUE TITLE
I have a sandcats instance that won't start...

### ISSUE THREAD

**Issue by noci2012** [sandstorm-io/sandstorm#1253]
Mongo log shows:  
{ "ts" : Timestamp(1448966371, 19), "h" : NumberLong("-8529971332018509463"), "v" : 2, "op" : "i", "ns" : "meteor.misc", "o" : { "_id" : "BASE_URL", "value" : "http://xxxx.sandcats.io:7443:6080" } }

While the external address should be: 

https://xxxx.sandcats.io:7443
and the internal address:
http://xxxx.sandcats.io:7080

what went wrong.

**Comment by noci2012** [comment]
How can a databases be cleared and an instance restarted from scratch.

**Comment by paulproteus** [comment]
Hi there!

If you want to uninstall Sandstorm and start fresh, you can do:

sudo service sandstorm stop
sudo rm -rf /opt/sandstorm

that will leave a systemd unit file (or rc.d service file) around, and
leave symlinks in /usr/local/bin/sandstorm and /usr/local/bin/spk but since
you're re-installing, that should be OK. Thanks for asking & it'd be good
if we documented this better.

**Comment by noci2012** [comment]
Trying the database:
# ./sandstorm mongo
MongoDB shell version: 2.6.7
connecting to: 127i0.0.1:7081/meteor
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
2015-12-08T21:06:09.072+0000 In File::open(), ::open for '' failed with errno:2 No such file or directory
> db.auth('sandstorm','qddhUROWOGtD8A-x5n9BbLipWe5')
Error: 18 { ok: 0.0, errmsg: "auth failed", code: 18 }
0
> use admin
switched to db admin
> db.auth('sandstorm','qddhUROWOGtD8A-x5n9BbLipWe5')
1
> show collections
2015-12-08T21:06:43.183+0000 error: { "$err" : "not master and slaveOk=false", "code" : 13435 } at src/mongo/shell/query.js:131
> 


So somehow this database is now a replica set?

**Comment by noci2012** [comment]
actualy i want to be able to install in a selectable /opt directory, and it should ask for port numbers as well. As i need multiple instances of sandstorm... one behind my current setup (for current usage) and one with a valid sandcat certificate...

**Comment by noci2012** [comment]
Ok the OVERIDE* options might be shown somewhere else then in code.
also missing is the override for 6081.... (which probably nuked the previous instance.)

I now shutdown everything, created a new instance (even took down webservice just to allow the check for 443 to succeed..., why not accept an override for 7443??

after that carefully move /opt/sandstorm to an other location, edit the sandstorm.conf to use ports 7080, 7081 & 7443 resp. and start... and now the instance seems to workwith port forward.... fro 7443 front end to back and...


Oh and btw, i am not using systemd.... it breaks too many things and actualy slows things down in startup in my experience.
