### ISSUE TITLE
when I try to link an identity and fail, it closes all my open grains

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#1265]
I tried to link my existing identity (Github login), and tried to link a new identity (Google account), which had unfortunately logged in previously when I was doing testing.

Got 403 error, as expected, but then it also closed all of my open grains, due to refreshing. :(

**Comment by dwrensha** [comment]
Fixed by https://github.com/sandstorm-io/sandstorm/pull/1646 and https://github.com/sandstorm-io/sandstorm/pull/1658.
