### ISSUE TITLE
Sidebar arrow highlight on hover

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1266]
This is a solution to @zarvox's suggestion that users may mistakenly click on the close grain button. 

- whole row highlights on hover (indicates action)
- row height increases to match grain height (harder to miss)
- highlight is somewhat subtle
![newsidebar-hover](https://cloud.githubusercontent.com/assets/855341/11680509/956423b4-9e0d-11e5-9627-01b1cde7b502.png)

**Comment by neynah** [comment]
@jparyani I'm assuming our default colours haven't changed but I've referenced them on the left anyway.
New highlight colours are:
dark: #343334
light: #636363
![image](https://cloud.githubusercontent.com/assets/855341/13193123/63d66fc4-d728-11e5-9c2d-6c8b25f7349b.png)

**Comment by jparyani** [comment]
Unfortunately, the colors of the sidebar didn't match your design. I went with eyeballed values that looked decent to me for now. We should standardize/fix all of our topbar and sidebar colors at some point.

**Comment by neynah** [comment]
@jparyani That's fine. I appreciate it! I agree, there is work to be done.
