### ISSUE TITLE
Change Page Title on Referral Page

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1273]
@paulproteus, top bar title should say "Referral Program" rather than "About Sandstorm"?

![image](https://cloud.githubusercontent.com/assets/855341/11726937/d360b398-9f35-11e5-96b5-230b1425d03c.png)

**Comment by neynah** [comment]
Also makes me wonder if there should be a link/sub navigation tab to move between "About Sandstorm" and "Referral Program"

**Comment by zarvox** [comment]
Ahhh, yes.  Each route needs a `setDocumentTitle` helper and should call it in the template.

Also, this doesn't strike me as something that belongs within "About Sandstorm" at all, but rather under Account, if anything.  I suspect "About Sandstorm" was just the last route that you were viewing.

**Comment by neynah** [comment]
Oops! Yes, you're right. I meant Account, not About Sandstorm. :)

**Comment by paulproteus** [comment]
Self-assigning; will investigate after the weekend unless someone pings me and says I should do otherwise; if someone else beats me to it, then by all means re-assign to yourself!

**Comment by neynah** [comment]
Fixed by @paulproteus
