### ISSUE TITLE
Referral Program - Proposed Design

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1276]
@paulproteus suggested I add some design touches to the new [Referral Program](https://oasis.sandstorm.io/referrals) page. It's pretty basic but here's the first draft. I'd love if someone would take this on and even do the basic implementation (I can style-tweak afterwards). I just won't be able to get to this until I'm done the front-page redesign. :)

I'll export the graphics now.
![referral-ui-draft1](https://cloud.githubusercontent.com/assets/855341/11758362/e1673c52-a01e-11e5-858b-d0204fdf835c.png)

**Comment by kentonv** [comment]
Your designs keep getting better. How long until we hit the design singularity?

**Comment by neynah** [comment]
Thanks @kentonv! I guess we'll know it when we see it. :D

This redesign has been implemented by @paulproteus's #1301.
