### ISSUE TITLE
Sandstorm install support more instances with more top level directories.

### ISSUE THREAD

**Issue by noci2012** [sandstorm-io/sandstorm#1280]
From #1210
While installing is would be nice to be able to set an alternative directory for an instance.
At the same time there need to be multiple startup scripts possible.
Separate mongo ports need to be specified as well, to prevent one instance with an unusable database.

like:

bash sandstorm --to-directory /data/instance1  --init=sandstorm1 --mongo-port=6081
bash sandstorm --to-directory /data/instance2  --init=sandstorm2 --mongo-port=6082

**Comment by kentonv** [comment]
Out of curiosity, why do you feel the need to install multiple Sandstorm instances on the same machine? Sandstorm is designed to be multi-user so normally this isn't necessary.

**Comment by noci2012** [comment]
I have different domains to supply sandstorm on...
One is an internal one another is external (no sandcats) with ssl stripped in the proxy, another is a sandcats one for public access. And i don't have 10's of machines. or want to dedicate VM's to them.

**Comment by noci2012** [comment]
closing old stuff
