### ISSUE TITLE
Sandstorm/Sandcats installer need better check for ports.

### ISSUE THREAD

**Issue by noci2012** [sandstorm-io/sandstorm#1281]
During installation of a sandcats instance it is needed that different ports from 80/443 are checked and specified.  I have a use case where a system already is running a web server on port 80/443, and this needs to be on another port.

sandstorm --listen=7080 --listen-ssl=7443 --sandcats=xxxx.sandcats.io

The sandcats instance will be accessed through a SNI capable SSL blind proxy

From #1210

**Comment by paulproteus** [comment]
Hi @noci2012 ,

Thanks for filing this. I'll dig into it in the next 1-2 weeks.

**Comment by paulproteus** [comment]
Hi @noci2012 ,

Here's some proposed logic.

- Check if port 80 is available. If not, hope that 6080 is available and use that for HTTP.

- Check if port 443 is available. If not, hope that 6443 is available and use that for HTTPS, if the user has a sandcats hostname.

The primary change is that by default, then, on a system with sandcats but port 443 already bound, after this change, the system would default to using a sandcats domain name *with HTTPS enabled* and on port 6443.

+1/-1 ?

**Comment by noci2012** [comment]
That should work..., and the implicit choice is ok, if documented, and notified.
The capability to specifiy is also ok.
(documented so one can prepare a proxy for it, notify to confirm the usage).

**Comment by paulproteus** [comment]
Thanks! I'll work on implementing this soon, then.

**Comment by paulproteus** [comment]
De-assigning from me because I haven't resolved in the past two weeks and I don't think I'll be able to in the next two.

**Comment by noci2012** [comment]
closing old stuff.
