### ISSUE TITLE
a grain can show up twice in the grains list

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#1284]
If I own a grain and also share it with an identity that's linked to my account, the grain shows up twice in my grains list, which is confusing.

**Comment by zarvox** [comment]
Which of the following do you think makes the most sense?

* show only the row that acts as the owning account
* show only the row that acts as the most-recently-redeemed apiToken (I'm assuming here that the identity is sticky and that you won't just always open the grain as the owner every time, but I'm not actually sure what we do today)
* show both links, but for every item in the grain table, also show something indicating which identity opening the grain will act as
* show only one row in the table, but show all the icons for all your identities who have access to that grain.  Maybe also show icons for other contacts who have access to that grain.

I suspect that we only want the grain to show up once in the table, but it's not clear to me which identity I should be acting as when I open it, or how to communicate that you have multiple identities that can act on this grain.

**Comment by neynah** [comment]
I wasn't able to reproduce this issue... but if this is still an issue I think we should decide on a solultion. I think in general I agree that seeing a grain twice on your list is confusing since it's the same grain.

**Comment by paulproteus** [comment]
I can repro this, fwiw!

![duplicate-grain](https://cloud.githubusercontent.com/assets/25457/13022362/cbb0f9cc-d195-11e5-8a48-a014185d89ed.png)

**Comment by paulproteus** [comment]
Steps to reproduce:

- Open a grain

- Create a sharing link

- View the sharing link in a different browser _tab_ but same browser _instance_

- Make sure your acct has multiple identities on it (add an email address for an easy way to get another identity)

- Choose an unusual identity as the one that you want to view the grain as

**Comment by mrdomino** [comment]
Would it make sense or be reasonable to imagine upgrading all the linked identities to the "highest" role available? I suppose not since roles aren't necessarily ordered.

How hard is it to give all the linked identities the union of all the permissions they have? Is that a sane thing to do?

**Comment by paulproteus** [comment]
"union of all the permissions they have" is what I expected, fwiw.

**Comment by mrdomino** [comment]
Hmmmm along similar lines, if you've visited a grain with multiple capability links with the same identity, what permissions do you in fact have today, and what should you have?

I suppose "union of all of them" is the more specific articulation of my existing idea about how it should work, which I'd previously stated as "highest role". It seems as though "union of all of them" or similar is what's currently happening, but I'm not exactly looking at the code.

**Comment by paulproteus** [comment]
BTW, along these lines - when I open a capability link to a grain I have access to by one of my grains, what I want to happen is to enhance that existing identity's access to the grain.

I think I'm OK with an interstitial, so long as the "View with the existing identity that has access to this grain" UI element is enormous, and the other options require me clicking tiny links to opt out of a default behavior.

In general I like the:

```
We're going to do something.

         +----------------------------+
             ( big button to do it )
         +----------------------------+

    small text link to do something else
````

pattern

**Comment by zarvox** [comment]
Just to explain the current behavior (not saying it's necessarily the right behavior):

* The grain list shows (identity, grain) pairs.
* Apps do not know anything about humans having/acting with multiple identities.
* Apps get handed an identity, and the permissions that that identity has.
* Identities which have opened multiple sharing links with different permissions get the union of those permissions.
* Accounts which have multiple identities choose one when opening a grain, and receive that grain's permissions.
* using the "Switch identity" option in the account dropdown while you have the grain open will trigger sharing access from your identity that has access to the identity you're switching to, if the identity you're switching to doesn't yet have access to this grain.

The high-level reason why there's a harder isolation boundary between identities is that you may want to keep multiple identities for the same account separated from each other.  If you have your secret-email-address identity and your public-facing-github identity on the same account, then we don't want to accidentally cause you to reveal your secret-email-address identity to someone who shared a grain with your public-facing-github identity.  Automatically merging identities at the app level could wind up leaking information about "which accounts actually own these identities?"

**Comment by paulproteus** [comment]
> using the "Switch identity" option in the account dropdown while you have the grain open will trigger sharing access from your identity that has access to the identity you're switching to, if the identity you're switching to doesn't yet have access to this grain.

This is surprising to me, though I can see how it makes sense! I expected that clicking "Switch identity" would not create any new permissions, but let me perceive how the other identity views it, up to a 403. But I guess that's not very useful, so it makes enough sense for "Switch Identity" to share; I was attempting to "Switch identity" for debugging, not for sharing, in my case.

In general, big +1 to your message.

**Comment by dwrensha** [comment]
> The grain list shows (identity, grain) pairs.

Not exactly. If I have a grain shared with me through multiple of my identities, it still only shows up once in the list. It can only show up twice if I am also the grain owner.
