### ISSUE TITLE
Multiple identities: Does it use the last one I used with a grain?

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#1291]
I did link a second identity to my account on Alpha, and set it as my login identity, but I found it really odd when I was suddenly no longer able to vote on the Sandstorm App Committee page, until I realized it was using my Github identity instead of my Google one, and there was a dropdown to change it on the top right.

I'm confused why it used my Github identity, since I only had interacted with that grain via my Google identity prior.

**Comment by kentonv** [comment]
Hmm, indeed, I observed this to: I visited sandstorm.io/vote and found that it defaulted to a different identity than I have ever used with that grain before.

@dwrensha it's supposed to prefer an identity I've used in the past, right?

**Comment by dwrensha** [comment]
I suspect the weirdness comes from this being a "public" grain on the old sharing model. There are likely some corner cases that can arise there that I haven't considered yet.

**Comment by kentonv** [comment]
Oh right... I forgot about the old sharing model.

**Comment by dwrensha** [comment]
The answer to "Does it use the last one I used with a grain?" is "yes", and that's working as intended for non-legacy grains.

For legacy grains, after #1965 we will use the current identity for opening, which I think is the best we can do.
