### ISSUE TITLE
Sharing visibility

### ISSUE THREAD

**Issue by noci2012** [sandstorm-io/sandstorm#1298]
It would be nice to see the Whom shared with button on the top IF a document has been shared.
Now first the "+ Share access" drop down has to be open to be able to open it. (If it is opened it shows a button on the topbar, but removes the button if the shared with view is closed).

**Comment by kentonv** [comment]
I believe @zarvox proposed something like this. Powerbox connections should be shown there too.

**Comment by noci2012** [comment]
Closing old stuff
