### ISSUE TITLE
dead link in tests/apps/ip-networking.js

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#1302]
The IP networking test [links to](https://github.com/sandstorm-io/sandstorm/blob/b2c12bb74b5ceb3e03363061e92bac007129ec7c/tests/apps/ip-networking.js#L17) https://github.com/jparyani/sandstorm-test-app/tree/ip-network , but that link yields a 404.

**Comment by jparyani** [comment]
Fixed
