### ISSUE TITLE
Install script fails to create group sandstorm for some configurations

### ISSUE THREAD

**Issue by medic15** [sandstorm-io/sandstorm#1306]
On a fresh install of openSUSE Tumbleweed (rolling release) the install script fails with the message:
`...chown: invalid group: ‘sandstorm:sandstorm’`

After the failure, the user sandstorm exists but the group sandstorm does not.  The failure to create the group is linked the a setting in /etc/login.defs containing the variable USERGROUPS_ENAB which has a default setting of "no" in openSUSE.  Changing the value to "yes" allows the install script to succeed.

The install script should verify the group exists prior to creating the user and assign the user to that group when executing the useradd command.

Props to dwrensha on the IRC for identifying the source of the problem.

**Comment by paulproteus** [comment]
Thanks @medic15 for filing this bug. I'll address it in the next round of installer fixes.

**Comment by jbigte** [comment]
Install script fails with same chown error on Suse Linux Enterprise Server SLES 12.

Not wanting to change the USERGROUPS_ENAB default setting, I created the sandstorm group and assigned the sandstorm user (already created, as noted, by the install script before it fails) using Yast.

The install script then succeeds.

+1 for fixing this in the next round of installer fixes...

**Comment by paulproteus** [comment]
Thanks for filing, all. I'll implement this soon.
