### ISSUE TITLE
Reinstall + Sandcats.io Recovery "Not Authorized" Error

### ISSUE THREAD

**Issue by dgoodwin** [sandstorm-io/sandstorm#1312]
Trying to re-install on a clean server and recover my sandcats.io domain, with https. Host system is CentOS 7.

 Hit the following error:

(root@hobbes /opt) $ curl https://install.sandstorm.io | bash                                                                                     [34/5182]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 67977  100 67977    0     0   236k      0 --:--:-- --:--:-- --:--:--  237k
Sandstorm makes it easy to run web apps on your own server. You can have:

1. A full server with automatic setup (press enter to accept this default)
2. A development server, for writing apps.

How are you going to use this Sandstorm install? [1] 
We're going to:

* Install Sandstorm in /opt/sandstorm
* Automatically keep Sandstorm up-to-date
* Configure auto-renewing HTTPS if you use a subdomain of sandcats.io
* Create a service user (sandstorm) that owns Sandstorm's files
* Configure Sandstorm to start on System boot (with systemd)

Rest assured that Sandstorm itself won't run as root.
OK to continue? [yes] 
As a Sandstorm user, you are invited to use a free Internet hostname as a subdomain of sandcats.io,
a service operated by the Sandstorm development team.
...
Sandcats.io protects your privacy and is subject to terms of use. By using it,
you agree to the terms of service & privacy policy available here:
https://sandcats.io/terms https://sandcats.io/privacy

Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).
Type the word none to skip this step, or help for help.
What *.sandcats.io subdomain would you like? [] rmrf            
We need your email on file so we can help you recover your domain if you lose access. No spam.
Enter your email address: [] MYEMAIL
Registering your domain.
This hostname is already in use. Type help if you need to recover access, or 
pick a new one.
Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).
Type the word none to skip this step, or help for help.
What *.sandcats.io subdomain would you like? [] help
Sandcats.io is a free dynamic DNS service run by the Sandstorm development team.

You can:

* Read more about it at:
  https://github.com/sandstorm-io/sandstorm/wiki/Sandcats-dynamic-DNS

* Recover access to a domain you once registered with sandcats

* Just press enter to go to the previous question.
What Sandcats domain do you want to recover? [none] rmrf
OK. We will send a recovery token to the email address on file. Type no to abort.
OK to continue? [yes] 
OK! Sent a recovery token to your email.
Please enter the token that we sent to you by email. [] REDACTED
OK! You have recovered your domain. Next we will update your IP address.
Update successful.
Congratulations! You're all configured to use rmrf.sandcats.io.
Your credentials to use it are in /opt/sandstorm/var/sandcats; consider making a backup.
Now we're going to auto-configure HTTPS for your server.

* This will take about 30 seconds, and needs no input from you.
* Thanks to GlobalSign for their help making this happen.

Generating certificate request...
Requesting certificate (BE PATIENT)...
Some part of HTTPS autoconfiguration failed. Log data available in 
var/sandcats/https/rmrf.sandcats.io/0.response-json

Config written to /opt/sandstorm/sandstorm.conf.
Finding latest build for dev channel...
Downloading: https://dl.sandstorm.io/sandstorm-138.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.9M  100 22.9M    0     0  42.4M      0 --:--:-- --:--:-- --:--:-- 42.4M
gpg: WARNING: unsafe permissions on homedir `/tmp/sandstorm-installer.wujNFfdHoO/.gnupg'
GPG signature is valid.

Your server is now online! Visit this link to configure it:

  http://rmrf.sandcats.io:6080/admin/settings/[REDACTED]

NOTE: This URL expires in 15 minutes. You can generate a new setup URL by running
'sudo sandstorm admin-token' from the command line.

To learn how to control the server, run:
  sandstorm help

(root@hobbes /opt/sandstorm) $ cat var/sandcats/https/rmrf.sandcats.io/0.response-json
{"error":"Not authorized."}#        

sandstorm.log looks clean, as do all the sandcats *-log files.

Didn't seem to be an issue on a previous build of this box, I recovered the domain there as well without issue, but on a fresh install having this problem.

**Comment by paulproteus** [comment]
Hi there!

I think I know what the problem is. You have more active HTTPS certificates
than we support at the moment, as an anti-abuse tactic.

I should be able to bump the number of max certs up now so you can get one.
I can attempt to make that log message more helpful.

**Comment by dgoodwin** [comment]
My apologies I've probably failed a lot of installs and tried to re-issue each time. Feel free to kill anything pre-existing if that's possible.

**Comment by paulproteus** [comment]
No worries. if you have an old /opt/sandstorm/var/sandcats/https from an
old install, you should be able to drop that into place.

I can't cancel the other certs but it's not a big deal to change the
constant # of certs people are allowed to have, which I can do within 24
hours sometime, hopefully soonish.

**Comment by dgoodwin** [comment]
Trying again this morning, still wasn't able to grab a new one yet but I was able to restore the sandcats dir from backup and I appear to be up and running. Thanks!

**Comment by dgoodwin** [comment]
Hey @paulproteus I fear this issue may have resurfaced somehow on Jan 1st and taken out my sandstorm instance.

Certificate we want to use: /var/sandcats/https/rmrf.sandcats.io/1450602947708 valid starting Sun Dec 20 2015 09:16:06 GMT+0000 (UTC) until Wed Dec 30 2015 07:59:59 GMT+0000 (UTC)
We have only the one key that we know about. We'll need to renew soon.
Migrations already applied: 17/17
renewHttpsCertificateIfNeeded: Happily choosing to renew certificate.
generateKeyAndCsr created new key & certificate request for *.rmrf.sandcats.io
storeNewKeyAndCsr successfully saved key and certificate request to /var/sandcats/https/rmrf.sandcats.io/[redacted] and /var/sandcats/https/rmrf.sandcats.io/[redacted].csr respectively of length 1706 and 918
Submitting certificate request for host rmrf where the request has length 918
Received HTTP error while renewing certificate (will keep retrying) 403
Error response contained information {"error":"Not authorized."}

I haven't done anything manually at this point it's just the normal cert renewal mechanism, feels like it may have hit the limit again?

Wondering if I should just try to grab a new sandcats.io sub-domain instead. (I'm not tied to rmrf at this point it's really just for my personal use so far) Thanks for any help you can provide!

**Comment by paulproteus** [comment]
Goodness. I suspect there's a deeper problem with the sandcats code causing
it to crash and count certificates that are only partially issued. I'll
look into that shortly.

What I'll do this very moment is permit 6 certificates, and then I'll look
into fixing the underlying bug this week.

**Comment by dgoodwin** [comment]
Thank you! I'll keep restarting it periodically and see if it can get itself a cert. Cheers.

**Comment by paulproteus** [comment]
Hi @dgoodwin , did you manage to resolve this? I think so, but thought I'd double-check.

If so, please mark it as closed, so we can know for sure. Or let us know it's not resolved so we can finish helping you.

Thanks!

And BTW we'd love to have you on the Sandstorm development discussion group: https://groups.google.com/forum/#!forum/sandstorm-dev

Cheers!

**Comment by dgoodwin** [comment]
I am up and running yes, thanks! Joining the google group now.

**Comment by joncamfield** [comment]
I think I may have also hit up against this in trying to recover from a failed backup-and-move.
