### ISSUE TITLE
Deleting grains should have an undo button

### ISSUE THREAD

**Issue by fkautz** [sandstorm-io/sandstorm#1313]
The user should have the ability to undo a delete. This will protect users from data loss where the user mistakenly deletes the grain through either bad UI design from the guest app or accidental clicking.

**Comment by paulproteus** [comment]
My take on this is we should move toward a model of "Archive this grain",
and move full "Delete" into a different menu.

Just a random personal opinion; curious what others think.

**Comment by fkautz** [comment]
Agreed, I was thinking archive but didn't want to bias the design. Another possible feature on top of this would set a policy where deleted grains with a given type expire after a configurable amount of time. e.g. retain all etherpads for two years and meme generators for 1 week.

**Comment by paulproteus** [comment]
Another possible design is that delete could trigger a download of a grain
backup.

(Just brainstorming; not sure I love that idea for now.)

**Comment by ocdtrekkie** [comment]
I do not want to ever get into the thing where the Delete button is hidden from users as a way to encourage people to Archive. Google has flirted with that repeatedly, and been shamed by the masses for it every time.

Deleting should possibly/probably go into a Recycle Bin/Trash of some sort though? People could go in and restore them if they wanted, or permanently delete them, and they'd auto-delete after a period of time.

**Comment by JamborJan** [comment]
I agree with @ocdtrekkie about removing the delete button. As a user I want to have the possibility that something is really gone and destroyed.

With todays solution it's very easy to delete something accidentally. It just happened to me that I deleted a ethercalc spread sheed I wanted to keep because I mixed up the name. A recycle bin type of thing would have been nice now.

**Comment by dwrensha** [comment]
Grains now go into the "trash" before being delete forever: https://github.com/sandstorm-io/sandstorm/pull/1950. Closing.
