### ISSUE TITLE
Edge case when setting blank title or path

### ISSUE THREAD

**Issue by mquandalle** [sandstorm-io/sandstorm#1318]
With the new `postMessage` API grains can expose meta-data to the Sandstorm shell. I encounter the following edge case:

```js
window.parent.postMessage({setTitle: ''}, '*');
```

Instead of setting a blank tittle, this output the following message in the console:

    postMessage from app not understood: [object Object]

(Setting a blank title isn’t the best idea in the world, but that just happen to me in Wekan due to a load order problem, ie the `DocHead.getTitle()` is called for the first time before the title is set and then re-called again a few milliseconds later due to its reactivity). Anyway I think this edge case should be handled correctly.

This bug is due to JS automatic type conversion [here](https://github.com/sandstorm-io/sandstorm/blob/39c898e30f5f836429c68b7476609beb39f8dbcf/shell/shared/grain.js#L1251). Similar calls wouldn't work either:

```js
window.parent.postMessage({setPath: ''}, '*');
```

**Comment by paulproteus** [comment]
Hi @mquandalle ! Seems like we should check that the type is string, rather
than checking its truthiness. Is that what you'd suggest too? If so, feel
very free to submit a pull request and/or reply saying yes here and I will
submit the pull request.


Another thing we could do is ask users to provide a JS object instead, like:

window.parent.postMessage({setTitle: {value: ""}}, '*');

But that seems overly complicated and also a breaking API change.

**Comment by mquandalle** [comment]
Yes, I will let you do the simple change.

**Comment by paulproteus** [comment]
Great!​
