### ISSUE TITLE
Non-ascii characters in URLs handled incorrectly

### ISSUE THREAD

**Issue by pamalyshev** [sandstorm-io/sandstorm#1323]
I've tested that with DokuWiki and MediaWiki apps, so I'm not sure if that is a bug in Sandstorm or in apps.
## MediaWIki ##
1. Install MediaWiki, create new wiki.
2. Go to wiki's Main Page (Url: https://oasis.sandstorm.io/grain/R4.....h/Main_Page)
3. Manually change Url to https://oasis.sandstorm.io/grain/R4.....h/Test, press enter.
4. Everything works fine, you can edit page Test.
5. Manually change Url to https://oasis.sandstorm.io/grain/R4....h/%D0%A2%D0%B5%D1%81%D1%82 (encoded "Тест" in Russian)
6. You'll be redirected to https://oasis.sandstorm.io/grain/R4....h/%225AB and page title will be **"5AB**, not **Тест**.

In some cases you'll get **Bad title** i.e in https://oasis.sandstorm.io/grain/R4....h/%D0%9A%D0%B0%D1%81%D1%82%D1%80%D1%8E%D0%BB%D0%B8 (encoded "Кастрюли") you'll be redirected to https://oasis.sandstorm.io/grain/R4....h/%1A0AB@N;8 and title saying **Bad Title**

But if you'll open a link in a new window, i.e https://5...b.oasis.sandstorm.io/Main_Page and then change link to https://5...b.oasis.sandstorm.io/%D0%A2%D0%B5%D1%81%D1%82 (encoded "Тест") 
everything will be fine, page title will be "Тест", and you can edit that page.

So I think the problem is that Sandstorm UI's url is incorrectly transformed into iframe's url.

**Comment by paulproteus** [comment]
Thanks for filing this, @pamalyshev ! I think you're right that this is a bug and we'll look into it.

**Comment by kentonv** [comment]
This will be fixed in the next release (v0.142, probably some time next week). Sorry it took a while!
