### ISSUE TITLE
Sidebar request: Tooltip with grain title

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#1325]
Along with my prior notion that ideally I shouldn't need the wider sidebar to close grains, I also shouldn't need the larger sidebar to skim grain titles. Can we have tooltips on the grain icons with the full grain titles? Even when expanded, this might remain useful, side the sidebar does truncate longer grain titles. Pretty much all web browsers will return such a tooltip when mousing over a tab.

**Comment by paulproteus** [comment]
My personal feeling on this is:

+1 to tooltip
​

**Comment by zarvox** [comment]
This idea is great and super-easy to implement.  Thanks @ocdtrekkie!
