### ISSUE TITLE
"SANDSTORM SUPERVISOR: Grain still in use; staying up for now." & turning wheel

### ISSUE THREAD

**Issue by neo-luddite** [sandstorm-io/sandstorm#1326]
Hello,

I also got the "turning wheel of death" instead of grains problem (ubuntu 14.04). 
Debug console says (with freshly created grain):

>...** SANDSTORM SUPERVISOR: Starting up grain.
>** SANDSTORM SUPERVISOR: Starting up grain.
>** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
>** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
>** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
>** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
>** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
>*** lost connection to grain (probably because it shut down) ***

sandstorm.conf:
>SERVER_USER=sandstorm
>PORT=6080
>MONGO_PORT=6081
>BIND_IP=127.0.0.1
>BASE_URL=https://abc.example.net
>WILDCARD_HOST=*.abc.example.net
>UPDATE_CHANNEL=dev
>ALLOW_DEV_ACCOUNTS=false

/etc/nginx/sites-enabled/default (analog to your given example):
> [...]
> listen 443;
> server_name abc.example.net ~^abc-[^.]*\.example\.net$;
> [...]
> location / {
> proxy_pass http://127.0.0.1:6080;

dns-wildcards seem to function. `$ dig whatever.abc.example.net` results in the correct IP adress (1.2.3.4 in this example):
> whatever.abc.example.net. 299	IN	CNAME	abc.example.net.
> abc.example.net.	7199	IN	A	1.2.3.4

- no errors in sandstorm and nginx logs. 
- no messages in firewall logs (port 80 and 443 opened)
- I can see my avatar picture in sandstorm account settings.
- I tried using sandstorm without nginx as reverse proxie, same same. 
- I can install and delete apps
- I can create and delete grains (I tried ethercalc and etherpad)
- I tried using chromium and firefox, disabled all extensions and enabled third party cookies. 
- https://oasis.sandstorm.io/apps is working with my firefox and chromium
- no icons/pictures of ethercalc and etherpad under "Most used" ins "Apps" (only text, links to apps are working)

I'm running out of ideas. Any help would be much appreciated!

**Comment by ocdtrekkie** [comment]
I don't know ANYTHING about Nginx, but I have an idea.

On this line `server_name abc.example.net ~^abc-[^.]*.example.net$;` you have that abc- in there, like alpha- in the nginx example. However, that's there for if you use a prefix in your wildcard host. Like abc-*.abc.example.net because the Alpha server and Oasis share a subdomain, hence they have that prefix.

**Comment by paulproteus** [comment]
Hi @neo-luddite ,

This line:

```
server_name abc.example.net ~^abc-[^.]*.example.net$;
```

should probably be

```
server_name abc.example.net *.abc.example.net;
```

based on what I have in my personal Sandstorm configuration.

Let me know if that takes care of things for you!

**Comment by ocdtrekkie** [comment]
So I was right-ish, @paulproteus?

**Comment by paulproteus** [comment]
Yes @ocdtrekkie I think your analysis was right!

FWIW, I also found the last sentence of your explanation a little
confusing, since it didn't say exactly what @neo-luddite should do
specifically.

**Comment by ocdtrekkie** [comment]
I meant to suggest that he could add a prefix to his wildcard host, like Sandstorm Alpha (and the nginx config example file) are set up.

I didn't know if just a * would work there. 

The nginx config example should probably not be set up with a prefix if we don't have people use such a prefix normally. Or at least should document in comments the alternative option.

**Comment by neo-luddite** [comment]
hey there, tnx for the replies!

the `~^abc-[^.]*.example.net$;` is in the example nginx conf file linked in the reverse proxy guide
(https://github.com/sandstorm-io/sandstorm/blob/master/nginx-example.conf).
in the text of the guide `*.abc.example.net` is written. I tried both and both don't work. 
also, as written above, I tried sandstorm without nginx and direct access via port 6080 with the same result/problem, so it seems not to be a nginx problem.

**Comment by neo-luddite** [comment]
btw regarding the Reverse Proxy Guide

> Copy nginx-example.conf to /etc/nginx/sites-enabled/

on debian based systems best practise is having the (vhost)config files in /etc/(nginx|apache2)/sites-available/ and linking the active configurations to /etc/(nginx|apache2)/sites-enabled/

**Comment by Esamimbias** [comment]
Hi,

just solved the same issue hosting sandstorm on my domain. By reading page content I found that images's URL was something like : static.mydomain.net/* ...  that was unresolved

resolution : 
created a subdomain sandstorm.mydomain.net pointing on the same IP
configured sandstorm.conf :  
BASE_URL=http://sandstorm.mydomain.net:6080
WILDCARD_HOST=*.sandstorm.mydomain.net:6080

no nginx particular setup, even if my nginx is using ports 80 and 443.

Etherpad now work, but Wekan endlessly loops... another issue to solve ;)

**Comment by neo-luddite** [comment]
@Esamimbias 

I already got a widcard domain configured, (static|whatsoever).abc.example.net get resolved.

**Comment by Esamimbias** [comment]
OK sorry I skipped this line.

It's the fact I couldn't see the apps pictures/icons that helped me solve my issue. Maybe you should use your browser to inspect those missing elements and check if everything OK. Can't tell if the two facts are related, but as soon as I fixed the icons URL, the endless loop issue got fixed too, as if sandstorm finally managed to download something it needed and could proceed.

**Comment by neo-luddite** [comment]
good idea! 
unfortunately inspecting the element and c&p the app-icon link to a new tab I see the etherpad icon. 
link looks like:

https://static.abc.example.net/2jQKJajoRpRjQgDHm

**Comment by neo-luddite** [comment]
I think I figured it out. Seems as if I made a mistake creating the custom ssl certificate. the CN is abc.example.net (missing the wildcard *.abc.exmaple.net) and therefore the browser is not opening the content of the iframe but instead tries to show the import certificate page, which is not show under the "wheel of death".

no time to test this today, but will have a closer look tomorrow.

**Comment by neo-luddite** [comment]
well, I missed the "Import the Certificate Authority (CA) Certificate (rootCA.pem) into the browser's that will be using Sandstorm." part of the tutorial. 

 "Some browsers may load grains without this step and ask users to add a security excpetion in order to fully load grains." is true for firefox, but the dialog is not shown in the iframe and hidden under the turning wheel.

tnx for helping!

**Comment by Esamimbias** [comment]
Great ! and your comments helped me solve my issue : some grains were constantly reloading. Trying to connect using HTTPS on port 443 the browser indicated an SSL error (invalid certificate).
 My error : the SSL certificate in nginx was for the top domain instead of the sandstorm sub-domain. I created and install a specific certificate for the sub domain. Now it works fine.
Thanks too !
