### ISSUE TITLE
Backup generation is not atomic on single-machine Sandstorm

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1329]
Since we're just running zip concurrently with the application, our backup-generating reads could interleave with application writes in a potentially data-corrupting order.

One way to solve this would be to "stun" the grain's process tree while the snapshot is being generated, using the kernel's [cgroups freezer subsystem](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/cgroups/freezer-subsystem.txt).

On most systems, this would require either writing to cgroups directly (which may or may not still work) or integrating with systemd's cgroups controller API: http://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/

**Comment by paulproteus** [comment]
+1 to cgroups freezer; thanks to link to their docs

(fwiw, I would personally like to see this as an alternative to actually
killing grains)

**Comment by zarvox** [comment]
I think the primary reason for killing grains-not-in-use is memory usage, which the freezer doesn't help with.

**Comment by paulproteus** [comment]
(I am happy to enable 100GB of swap, fwiw, if doing so allowed me to ​have
faster grain startup times. But I realize this is off topic.)

**Comment by kentonv** [comment]
@paulproteus Ehh, paging out the whole process and paging it in later may very well be much slower than killing it and starting it again later.

**Comment by paulproteus** [comment]
I'm sure it depends on the app, but yeah, it would be slower sometimes for
sure.

**Comment by ocdtrekkie** [comment]
#3398 will do this, presumably? Should we close this in favor of #3186?

**Comment by zenhack** [comment]
Yeah, it looks like This and #3186 are the same issue; didn't realize this existed when I opened it.
