### ISSUE TITLE
Strange error shows up when accessing a grain that previously was usable...

### ISSUE THREAD

**Issue by noci2012** [sandstorm-io/sandstorm#1332]
Using sandstorm-138... i get

Error: Error: remote exception: Peer disconnected.
C++ location:(javascript):??
type: disconnected

Logging shows nothing effectively pointing to a clue.
Restarting the sandcats instance didn't work either.

It happens for existing grains and also when attempting to create a grain.

**Comment by paulproteus** [comment]
Is there anything suspicious/interesting in
/opt/sandstorm/var/sandstorm/sandstorm.log ?

**Comment by noci2012** [comment]
We have only the one key that we know about. We'll need to renew soon.
Migrations already applied: 17/17
Since Tue Jan 05 2016 17:05:17 GMT+0000 (UTC) is more than three days away from Fri Jan 15 2016 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
Since Tue Jan 05 2016 18:25:03 GMT+0000 (UTC) is more than three days away from Fri Jan 15 2016 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
Since Tue Jan 05 2016 19:44:49 GMT+0000 (UTC) is more than three days away from Fri Jan 15 2016 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
Since Tue Jan 05 2016 21:04:35 GMT+0000 (UTC) is more than three days away from Fri Jan 15 2016 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
Since Tue Jan 05 2016 22:24:21 GMT+0000 (UTC) is more than three days away from Fri Jan 15 2016 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
Since Tue Jan 05 2016 23:44:07 GMT+0000 (UTC) is more than three days away from Fri Jan 15 2016 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
Downloading app: https://app-index.sandstorm.io/packages/46d02089a7f4775da8917baad2310d85
App ready: 46d02089a7f4775da8917baad2310d85
fetching keybase 5C5580353165D42FD89E1371A9FF0AD7DEE40258
Since Wed Jan 06 2016 01:03:53 GMT+0000 (UTC) is more than three days away from Fri Jan 15 2016 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.

**Comment by noci2012** [comment]
like i said nothing really special..

**Comment by noci2012** [comment]
Can there be interactions with dockers ( to be more precise, iptables / nat rules )?
The service was not running (started it for a bit, but no difference).
After removing the rules & modules for these the grains worked again..?

**Comment by paulproteus** [comment]
Hi nici2012,

I'm glad you were able to get your issue resolved! And I'd like to do what
we we can to avoid this problem for the future.

I don't know much about Docker's iptables/NAT rules. If you can help me
understand how we could integrate better, then the answer is maybe!

Specific questions for you:

- Which Docker component seemed to be causing weird interactions with
Sandstorm? This will help me find the documentation for it.

- How do you stop & start Sandstorm? If via Docker, are you running
Sandstorm via a Dockerfile that you created?

- What commands did you run, or what files did you edit, to remove the
rules and modules you mentioned?

Thanks so much.

**Comment by noci2012** [comment]
Modules before:

core / # lsmod | head
Module                  Size  Used by
cpufreq_userspace       1317  4
8021q                  15912  0
garp                    4844  1 8021q
mrp                     6231  1 8021q
msr                     2224  0
bridge                 79191  0
stp                     1429  2 garp,bridge
llc                     3121  3 stp,garp,bridge
bonding                87357  0


Iptables before:
core / # iptables -L -nv
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
core / # iptables -L -nv -t nat
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

==========================================================
service docker start
 =======================================================
After:
core / # lsmod | head -n20
Module                  Size  Used by
xt_conntrack            2689  1
ipt_MASQUERADE          1013  1
nf_nat_masquerade_ipv4     1665  1 ipt_MASQUERADE
xt_addrtype             2437  2
br_netfilter            9017  0
iptable_nat             1631  1
nf_nat_ipv4             4243  1 iptable_nat
nf_nat                 10450  2 nf_nat_ipv4,nf_nat_masquerade_ipv4
iptable_filter          1328  1
ip_tables              13698  2 iptable_filter,iptable_nat
x_tables               13793  5 ip_tables,ipt_MASQUERADE,xt_conntrack,iptable_filter,xt_addrtype
cpufreq_userspace       1317  4
8021q                  15912  0
garp                    4844  1 8021q
mrp                     6231  1 8021q
msr                     2224  0
bridge                 79191  1 br_netfilter
stp                     1429  2 garp,bridge
llc                     3121  3 stp,garp,bridge

core / # iptables -L -nv
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
core / # iptables -L -nv -t nat
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

==== Now i need to wait for connection tracking to forget previous sessions....

**Comment by noci2012** [comment]
It doesn't die immediately...., but after the connection tracking entries die down 
the effects are visible.
Stopping the docker service makes no difference.

**Comment by noci2012** [comment]
after all iptables modules have been unloaded the service works again.
sand storm is normal running on the host.
(Not in docker, docker was started for something else, it was the docker setting for the graphite performance grapher, just loading the docker service is sufficient to break sandstorm, no need to start the guest.).

**Comment by noci2012** [comment]
To answer your Q:
Which Docker component seemed to be causing weird interactions with
Sandstorm? This will help me find the documentation for it.

service docker start    # causes the trouble
service docker stop    # does NOT solve it.
I think the ip tables stuff is the cause.

- How do you stop & start Sandstorm? If via Docker, are you running
Sandstorm via a Dockerfile that you created?

Sandstorm runs on the host as a native application
service sandstorm start   # local instance
service sandstorm stop
service sandcats start   # instance using xxxx.sandcats.io (https ) behind an SNI proxy
service sandcats stop


- What commands did you run, or what files did you edit, to remove the
rules and modules you mentioned?

iptables -F FORWARD
iptables -F OUTPUT
iptables -X DOCKER
iptables -t nat -F PREROUTING
iptables -t nat -F POSTROUTING
iptables -t nat -X DOCKER
rmmod xt_conntrack ipt_MASQUERADE nf_nat_masquerade_ipv4 xt_addrtype br_netfilter
rmmod iptable_nat nf_nat_ipv4 nf_nat iptable_filter ip_tables x_tables

**Comment by noci2012** [comment]
I have been looking a bit further: in a grain is a log file as well...
which contains:

** SANDSTORM SUPERVISOR: Starting up grain.
*** Uncaught exception ***
sandstorm/supervisor.c++:1218: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x546ef5 0x53f29f 0x53ec6e 0x567fb9 0x567faa 0x4dcf5f
** SANDSTORM SUPERVISOR: App exited with status code: 1

and that seems to fit: 
Error: Error: remote exception: Peer disconnected.
C++ location:(javascript):??
type: disconnected
....

**Comment by noci2012** [comment]
According to:
https://github.com/docker/docker/issues/9452

the dummy.ko driver is needed. Now the big Q: Why does it sometimes need the dummy.ko driver and other times not.

**Comment by noci2012** [comment]
Now the dummy driver is available...., the iptables are NOT modified by docker.
And starting docker has no effect on grains... 

So the actual problem was the availability of the dummy.ko IP driver.

**Comment by noci2012** [comment]
Suggestion: Check for the availability of the dummy kernel module during installation.
btw. Kernel is 4.1.12 .

**Comment by noci2012** [comment]
I will let it stay open, please close if you cannot act on it.

**Comment by paulproteus** [comment]
Thanks! I will look into this shortly.

**Comment by noci2012** [comment]
Closing old stuff, the landscape changed a lot so i will reissue if thins start acting up again.
