### ISSUE TITLE
Periodically I get a 504 Gateway Time-out on Oasis for a grain

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1335]
Sometimes when my computer resumes from sleep, I see this instead of my todo list:

![sandstorm-504](https://cloud.githubusercontent.com/assets/25457/12149949/7b633144-b45b-11e5-9be0-4d97571d0a80.png)

I imagine a number of our users see this as well, since I don't think I did anything weird to trigger this.

Some problems with this error message.

- If I were less technical, I would think that Oasis/Sandstorm is entirely broken.

- It's not clear to me if the error is coming from Sandstorm, or from the app, even as a technical person. Since I created this app, I know that nginx isn't part of the app, but that's just because I'm the app author. Some apps do contain nginx after all.

- It contains no information on how I (as the person using the grain) can work around the problem. It happens to be true that I can right-click, then do "Reload frame", and my grain will work.

**Comment by paulproteus** [comment]
@jparyani implemented a fix for this that went live in an Oasis frontend push last night.

If 0 people experience this over the next week, then I'm adequately convinced it's closed.

**Comment by paulproteus** [comment]
https://oasis.sandstorm.io/about claims we're running 0.137 on oasis, but 0.137 was released in 2015.

But I haven't seen this issue crop up in the last week. I'm going to close it for now since I said I would, but am a little confused.

**Comment by paulproteus** [comment]
![504](https://cloud.githubusercontent.com/assets/25457/12441349/f09213c8-bf13-11e5-8124-fd17307edb00.png)

Got a fresh 504 today!

**Comment by neynah** [comment]
I just got one too. :(

**Comment by kentonv** [comment]
Note that /about lies after hot-pushes.

**Comment by paulproteus** [comment]
Got another one.

![504](https://cloud.githubusercontent.com/assets/25457/12591728/10bfb56a-c41e-11e5-9790-93f7bfd1d1c6.png)
