### ISSUE TITLE
Apps does not have icon after installing

### ISSUE THREAD

**Issue by NhanHo** [sandstorm-io/sandstorm#1345]
Using sandstorm-138, certain apps does not have an icon both in the apps page and the grain page. Looking through http requests, there are a few static.domain.com urls that returned 404. Specifically, the 3 apps that I found missing icons are: Wekan, Gitlab and Gitweb. Several other apps (FileDrop, Ghost, Etherpad) have normal icon.

Here is the sandstorm.conf file:

> SERVER_USER=sandstorm
> PORT=6080
> MONGO_PORT=6081
>BIND_IP=0.0.0.0
> BASE_URL=http://foo.bar.com:6080
> WILDCARD_HOST=*.foo.bar.com:6080
> UPDATE_CHANNEL=dev
> ALLOW_DEV_ACCOUNTS=false

![sandstorm-missing-icon](https://cloud.githubusercontent.com/assets/2504203/12193115/f10521a2-b599-11e5-868a-649155a32a79.png)

**Comment by dwrensha** [comment]
It sounds like you might be running into #1012. Does running `sudo sandstorm restart` fix things?

**Comment by NhanHo** [comment]
`sudo sandstorm restart` did fix the issue!

**Comment by paulproteus** [comment]
Yippee.​ Thanks all for helping track this down.
