### ISSUE TITLE
Docs: Security practices overview appears in two places

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1356]
Somehow it appears both under /using and /developing, and these two copies have diverged. :(

**Comment by kentonv** [comment]
Is it possible to cause mkdocs to leave HTML redirects so that we can redirect one location to the other? I'd have to break any existing links.

**Comment by paulproteus** [comment]
Fixed in https://github.com/sandstorm-io/sandstorm/pull/1369

**Comment by paulproteus** [comment]
To verify:

- https://google.com/search?q=sandstorm+security+practices
- https://docs.sandstorm.io/en/latest/developing/security-practices/
- https://docs.sandstorm.io/en/latest/using/security-practices/
