### ISSUE TITLE
A «not coder question» about Dokuwiki and Worpress

### ISSUE THREAD

**Issue by tierce** [sandstorm-io/sandstorm#1359]
Hello,

Why do I have this message with a Dokuwiki grain ;

*The plugin repository could not be contacted. Make sure your server is allowed to contact www.dokuwiki.org and check your proxy settings. [Retry]*

Or can not «directly» install a plugin for Worpress from the Wordpress Plugin Catalogue?

Sorry if you consider this as a noob question.

**Comment by dwrensha** [comment]
Hi!

The first problem is that Sandstorm apps [don't get network access by default](https://sandstorm.io/news/2015-06-10-network-access-permission-android-vs-sandstorm). We're currently working on the Powerbox UI, which will make it easier for apps to request external resources.

The second problem is that Sandstorm does not yet have good support for apps with plugin architectures. For apps like Etherpad and ShareLaTeX, our strategy has been to just bundle common additions that should cover what most people want. For WordPress we allow arbitrary plugins to be installed, but they go into per-grain storage and need to be manually updated. #507 has some more discussion about this issue. Eventually we want to have a Sandstorm-native notion of an app "add-on".

**Comment by tierce** [comment]
Thank you so much for your quick answer! The links you provided helps to understand without spending too much time searching for answers!
