### ISSUE TITLE
install.sh: Use sysctl.d

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1360]
A story from Jason: 

> random annoyance I ran into today. some debian package updated /etc/sysctl.conf, and there was a conflict with what sandstorm had added (kernel.unprivileged_userns_clone = 1). I wish the sandstorm installer would've made the change under its own file in /etc/sysctl.d/

Notes about this:

- I have mixed feelings about priority. If someone else wants to chase this down, awesome.

- At least Debian and CentOS seem to support this directory. Presumably the right test is to find out if `/etc/sysctl.d` exists, and if it does exist, use that.

**Comment by zarvox** [comment]
Utterly untested, but maybe a useful place to start: https://github.com/zarvox/sandstorm/commit/b4563a1d300a610847688366bb4df6835f66fdca

**Comment by paulproteus** [comment]
Neat!

If you ever feel like testing this, you can do

`make installer-test`

I can also own this pull request and handle testing it, which I assume I'll
do unless you comment otherwise.

**Comment by zarvox** [comment]
Good to know!

> I can also own this pull request and handle testing it, which I assume I'll do unless you comment otherwise.

Please do, thanks. :)

**Comment by paulproteus** [comment]
Tasks before this is completed:

- [ ] Merge this into a dev branch on e.g. my laptop
- [ ] Run installer-tests
- [ ] Update docs etc to explain that one might have to remove a sysctl.d file, rather than remove a sysctl.conf line, on uninstall (?)

I should do this in the next 0-2 weeks because I don't like how long it's been sitting here.
