### ISSUE TITLE
Users experience "Unauthorized (403)" when logging in with the wrong user/identity on a share-by-identity email

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1366]
Steps to reproduce:

- Alice opens a grain
- Alice uses share-by-identity to add Bob to the grain
- Bob receives an email
- Bob clicks on link in email

Expected behavior:

- Bob sees the grain

Actual behavior:

- Since Bob is using a different identity/account than the one tagged in share-by-identity, Bob (well Jade in this case) sees a message like this.

![jade-403-unauthorized](https://cloud.githubusercontent.com/assets/25457/12273406/8c62adee-b91a-11e5-9b47-d14501a5f60b.png)

I'm not fully sure exactly how accounts/identities interact with this, but it has affected more than one user and so I thought I should at least file a bug.

**Comment by kentonv** [comment]
I believe David is fixing this together with implementing the "request access" button.

**Comment by paulproteus** [comment]
Super rad.

**Comment by dwrensha** [comment]
Fixed by #1385.
