### ISSUE TITLE
Run a specific command to start a grain on demo mode

### ISSUE THREAD

**Issue by mquandalle** [sandstorm-io/sandstorm#1378]
I think it is confusing for new users that use the _demo_ feature of Sandstorm to arrive to a blank board without much clue about what to do next. Instead a better experience would be to have a “Welcome board” with some instructions in the cards and maybe even having a step by step feature introduction using [intro.js](http://usablica.github.io/intro.js/).

IIRC this discussion also happened with Etherpad and they decided to display the “Welcome to Etherpad!” message in all cases, which arguably isn’t needed for experienced users that just want to create yet another document.

Maybe there is already a way for a grain to detect than it is in “demo” mode and I’m just not aware of it. Otherwise it would be great to have either a distinct command at launch or just a meta-data exposed by the `http-bridge` to expose this information.

I think it would also be useful to extend the grain demo mode not only to unauthenticated Sandstorm users, but also to authenticated users that installed a new app and are are creating a new grain of it for the first time so that they can discover the application features.

**Comment by paulproteus** [comment]
It is possible technically, for what it's worth, to determine if a user is
a demo user. I think it involves doing Cap'n Proto RPC at the moment,
though.

I can look into this more starting Monday or so. @dwrensha and @jparyani
know more off the top of their heads.

**Comment by kentonv** [comment]
Dang, I thought I responded to this but my reply is not here.

I definitely agree it would be nice to trigger demo behavior for demo users. I also think non-demo users may want a way to get demo behavior, e.g. after installing a new app. So I think we should make sure Sandstorm has an explicit way to trigger this which we can play with later.

I think sandstorm-pkgdef.capnp should have a way to specify a different command to use for demo mode, like a special kind of action. Typically you'd probably set an extra environment var in that command.

**Comment by kentonv** [comment]
I think initial implementation of this (just for demo users) should be pretty easy so I'm labeling it byte-sized!

We'll need to think more about how to expose it to non-demo users without cluttering the UI.
