### ISSUE TITLE
run-bundle.c++: Bind to SMTP_LISTEN_PORT at Sandstorm start, so it can be on a privileged port

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1386]
Goal:

- Sandstorm can listen on SMTP port 25 by itself, without the help of nginx, to simplify https://docs.sandstorm.io/en/latest/administering/email/

Details:

- This would look very similar to how `HTTPS_PORT` works - some changes to `run_bundle.c++` and some changes to `pre-meteor.js` or `meteor-bundle-main.js`

- Then Sandstorm+Sandcats can terminate inbound SMTP.

Request for comment:

- Please comment saying `+1` if you want this!

Other notes:

- Originally this bug contained mention of doing STARTTLS using the sandcats keys, which would be nice. I'm going to declare that out-of-scope for now, but if I find it's easy, I might add it. Not sure yet.

**Comment by paulproteus** [comment]
@awans and @mrdomino might want to say +1 or not; don't know if you find this interesting/useful.

FWIW one thing that would motivate me to work on this is if someone says, "I will write a tutorial for some website about 'How I run my self-hosted email using Sandstorm'" with this. I will freely admit to being publicity-driven.

Note that I/someone/etc should probably document how to set up an email service that works with sandcats (perhaps Mandrill, since it doesn't require DNS stuff), and/or using e.g. gandi.net's SMTP service.

**Comment by paulproteus** [comment]
(also naturally if someone _else_ wants to work on this, I can write those docs/tutorial/etc!)

**Comment by jparyani** [comment]
This actually already works. The config var is SMTP_LISTEN_PORT, and it's currently used as part of the testing script (https://github.com/sandstorm-io/sandstorm/blob/8d922ed33cfeeda9b56c252dabc61e9d69db34ad/tests/run-local.sh#L118). Sorry for not documenting it.

**Comment by jparyani** [comment]
Sorry, I didn't completely read the issue, this doesn't support STARTTLS. Also, I'm not sure low numbered ports will actually work, since the Sandstorm front-end isn't run as root. We can probably do something similar to what we do with the web server ports, and hand them off as an fd.

**Comment by kentonv** [comment]
+1

**Comment by noci2012** [comment]
please also leave room for existing mail servers. like the https issue i had with existing web servers during its setup.

**Comment by xet7** [comment]
For binding to lower port, for example Caddy uses setcap.
From https://caddyserver.com/docs/faq page:
"On Linux, you can use setcap to give Caddy permission to bind to low ports. Something like
```setcap cap_net_bind_service=+ep ./caddy```
should work. Consult the man pages of your OS to be certain. You could also use iptables to forward to higher ports."

Could somebody test does this work?

**Comment by paulproteus** [comment]
A difficulty is that we don't want to run all of Sandstorm with
cap_net_bind_service I *think*, unless we think doing so is safe. I will
revisit this again shortly though; thank you for the link!

**Comment by mrdomino** [comment]
+1

**Comment by paulproteus** [comment]
Current plan:

- Right now, we assume fd 3 is Sandstorm's main HTTP(S) listener, and fd 4 and higher are secondary HTTP listeners.

- I propose we do the SMTP fd _before_ those, which would require re-numbering the use of fd 3 and fd 4.

As a side note about STARTTLS:

- Per `lib/server.js` within simplesmtp, it seems that it does support inbound STARTTLS.
- However, it doesn't seem to have a SNI-esque thing that we can piggy-back on top of so that we can cycle the credentials. So we'd probably want to stop & start the SMTP service on sandcats key change... or just do that once a day.
