### ISSUE TITLE
I “can't” find the documentation.

### ISSUE THREAD

**Issue by kpreid** [sandstorm-io/sandstorm#1389]
I'm shaking the dust off my Sandstorm install, so I wanted to have the docs handy while I did it. I went to the Sandstorm home page https://sandstorm.io/ and I couldn't find any link to the docs!

* I looked in the top bar. Nope, just new-user-ish stuff.
* I looked at the obvious action buttons. Nope, just demo/install/oasis.
* I looked at the bottom of the page. Nope, there's a link labeled “For Self-hosters”, but that just gets me to the download page.

I get that the documentation is linked from several places like “after you've downloaded...”, but perhaps it should be a little easier to navigate to directly?

**Comment by kentonv** [comment]
Good point!

Fixed!

**Comment by paulproteus** [comment]
For history/discussion/etc:

Fixed in https://github.com/sandstorm-io/sandstorm-website/commit/9299ef86536e7273573f15e0d9bababe4f60e32b
