### ISSUE TITLE
Allow Sandstorm to bind to IPv6 addresses

### ISSUE THREAD

**Issue by kpreid** [sandstorm-io/sandstorm#1393]
Sandstorm appears to accept an IPv6 address in its `BIND_IP` configuration, but fails to actually bind, presumably due to some bug. I get this error:

    sandstorm/util.c++:845: fatal: *exception = sandstorm/run-bundle.c++:1846: failed: bind(sockFd, reinterpret_cast<sockaddr *>(&sa), sizeof sa): Cannot assign requested address
    stack: 0x4b48a2 0x4b485a 0x5944fe
    ** Front-end died immediately after starting.

I have verified that the address can be bound by non-Sandstorm software.

My socket programming is exceedingly rusty, but it looks like it might be a simple bug in [`run-bundle.c++`](https://github.com/sandstorm-io/sandstorm/blob/c4cf509c31b3bacee5e401a01e7460f11ba6612b/src/sandstorm/run-bundle.c%2B%2B#L1835):

    sockaddr_in sa;
    memset(&sa, 0, sizeof sa);
    sa.sin_family = AF_INET;
    sa.sin_port = htons(port);
    int rc = inet_pton(AF_INET, config.bindIp.cStr(), &(sa.sin_addr));
    // If ipv4 address parsing fails, try ipv6
    if (rc == 0) {
      rc = inet_pton(AF_INET6, config.bindIp.cStr(), &(sa.sin_addr));
      KJ_REQUIRE(rc == 1, "Bind IP is an invalid IP address:", config.bindIp);
    }

Shouldn't the IPv6 case set `sa.sin_family` to `AF_INET6`?

**Comment by paulproteus** [comment]
It seems to me from a quick skim of http://long.ccaba.upc.edu/long/045Guidelines/eva/ipv6.html that maybe we need to use `sockaddr_in6` or rather `sockaddr_storage` to be agnostic about IPv6 vs IPv4.
