### ISSUE TITLE
Add reference documentation for config file

### ISSUE THREAD

**Issue by kpreid** [sandstorm-io/sandstorm#1395]
I had an ancient Sandstorm installation which I wanted to bring up to current standards. I couldn't find any docs that would help me update my config file (to include such things as HTTPS and Sandcats configuration), so I ended up rerunning the installer.

While a specific tutorial on “getting from version X to version Y” would be obsolete quickly, what would have helped that I didn't find is _reference_ documentation on the contents of the Sandstorm config file. From that I could have drawn my own conclusions about what needs revising.

There should be documentation which describes each element that can be in the config file.

**Comment by paulproteus** [comment]
+1

I'll assign this to me for now, but if someone else decides they want to own it, that's cool with me.

**Comment by kentonv** [comment]
Ideally we want to make it so no one ever has to edit the config file.

Admittedly this has not happened in practice, so we should at least document it.

**Comment by paulproteus** [comment]
I agree this is important. I'll aim to get to it in the next 0-2 weeks.
