### ISSUE TITLE
App install confirmation page should not show "Restore grain backup..." button

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1403]
Since you don't have the app installed yet, you won't be able to restore a grain using that package, and install time is not the right time to encourage a user to do this anyway.

![pixels1](https://cloud.githubusercontent.com/assets/307325/12495381/3d333ff0-c044-11e5-8392-b2eb716770c0.png)

@paulproteus can I assign this one to you, since you were the one who added this button?

**Comment by paulproteus** [comment]
+1 to assign to me
