### ISSUE TITLE
[Docs] Navigation back to website is inefficient

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1405]
For the past 4 user tests I've conducted on our old and new website there is a persisting annoyance for users navigating from Docs back to sandstorm.io. Currently, the only way to navigate back to the website would be to hit the back button (or type in the URL). This seems fine at first but if you start clicking on navigation within docs, then you have to click the back button multiple times to get back to the website.

I have 2 options in mind with a preference for option A.

A. Add a navigation button/link on docs to go to sandstorm.io

B. Have docs open in a new tab

**Comment by paulproteus** [comment]
I'm +1 on (B)

For (A), if you tell me where to place it Nena, I will place it there. I'm
+0.9 on (A) because I don't want to have to think about where to put the
link, but if you insist, I will try to think hard about that. But it'd be
easier if you can think about it for me, I admit.

**Comment by neynah** [comment]
I'm less thrilled about B because @zarvox @kentonv convinced me that having things open in new tabs is an unexpected/unnecessary behaviour(correct me if I'm wrong).

**Comment by paulproteus** [comment]
I'm cool with doing just A and not doing B, fwiw!

**Comment by neynah** [comment]
Here's my suggestion: 
![image](https://cloud.githubusercontent.com/assets/855341/12496663/f42d9dc0-c04b-11e5-9ff5-649401d24a07.png)

**Comment by paulproteus** [comment]
That looks good to me. To implement it I'll probably have to fork the theme that the docs use. @neynah maybe we can take some time tomorrow when we're both in-office and see if there are other theme choices that would make this easier for me to achieve.

Another question: is it important to you that this be equally easy to find on narrow screens, e.g. "mobile"?

**Comment by neynah** [comment]
Sounds great. I'll be there.

Yes, my suggestion for mobile (with the existing theme):
- also the hamburger menu is at the very top left corner in the current UI, I just centered it vertically with the other elements
- you can either center it vertically or just make the top bar shorter in height altogether
![docs-mobile](https://cloud.githubusercontent.com/assets/855341/12500089/b1932b60-c064-11e5-9097-7d004be744a9.png)

**Comment by paulproteus** [comment]
+1

**Comment by paulproteus** [comment]
Tentative decision:

- Make the section heading titles solid white.

- Keep to the readthedocs theme.

- Asheesh can try to add the paragraph deep links to the theme, which is not a show-stopper for this issue.

**Comment by paulproteus** [comment]
Props to @zarvox for helping me with the flexbox questions I had about a week ago.

**Comment by paulproteus** [comment]
Thanks to @neynah for helping me decide how to address this in a time-efficient manner!
