### ISSUE TITLE
install.sh: If unprivileged userns works, but /proc/sys is mounted read-only, it's OK to proceed

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1420]
See: https://groups.google.com/forum/#!topic/sandstorm-dev/Ek7sg7g2gUM

There is a hack in that thread, but presumably this change should come with a test too.

**Comment by kentonv** [comment]
I'm confused.

* If unprivileged userns works, and /proc/sys/kernel/unprivileged_userns_clone exists, then it must be "1", and so we won't attempt to write it, so it's fine if it's read-only.
* If /proc/sys/kernel/unprivileged_userns_clone is "0", then unprivileged userns surely doesn't work, and so we need to  bail out.

Is the problem just that the error message is bad in the latter case? Or are you seeing some contradiction in which /proc/sys/kernel/unprivileged_userns_clone is "0" but unprivileged userns actually does work?

**Comment by paulproteus** [comment]
It's a matter of the order of the checks, as I recall. I'll provide a test
that I think explains it well.

**Comment by paulproteus** [comment]
The `full-server-install-on-jessie-with-proc-readonly-but-sysctl-already-set.t` installer-tests file checks for this, so closing it now.
