### ISSUE TITLE
Self-Hosted - Installation failed - Your kernel does not appear to be compiled with support for unprivileged user  namespaces

### ISSUE THREAD

**Issue by blutux** [sandstorm-io/sandstorm#1430]
Hi Everyone,

i've tried to install with the curl install (curl https://install.sandstorm.io) on a dedicated server from ovh.com (a kimsufi server). And the installation failed.

Here the complete error message : 
"Your kernel does not appear to be compiled with support for unprivileged user 
namespaces (CONFIG_USER_NS=y), or something else is preventing creation of user 
namespaces. This feature is critical for sandboxing. Arch Linux is known to 
ship with a kernel that disables this feature; if you are using Arch, you will 
unfortunately need to compile your own kernel (see 
https://bugs.archlinux.org/task/36969). If you are not using Arch, and don't 
know why your system wouldn't have user namespaces, please file a bug against 
Sandstorm so we can figure out what happened."

The os is a Jessy Debian 64 bits.

i've read some previous post, so you will find some command result below:  

 * uname -a
Linux "hotsname.tld" 3.14.32-xxxx-grs-ipv6-64 #6 SMP Wed Jan 20 17:52:44 CET 2016 x86_64 GNU/Linux

* cat /proc/self/mounts | grep /tmp  
nothing

* cat /proc/sys/kernel/unprivileged_userns_clone
No such file or directory

* unshare --user id
uid=65534(nobody) gid=65534(nogroup) groupes=65534(nogroup)

Could you help me ?

Thanks in advance

Blutux

**Comment by kentonv** [comment]
Hi @blutux,

Are you able to execute `unshare --user id` as a non-root user, or only as root?

It looks like your kernel is not an official Debian kernel build. My theory is that the kernel is provided by your host and that they've disabled unprivileged user namespaces.

**Comment by blutux** [comment]
when I execute unshare --user id with an non root user  - i have : permission denied :/

**Comment by kentonv** [comment]
It sounds like your kernel is configured to disallow unprivileged userns, then. :( I recommend contacting your host and asking about it.

**Comment by blutux** [comment]
After some research i have found an option when i install, and i can use original kernel. And now the install works \o/

Thanks for the help

**Comment by paulproteus** [comment]
Yippee! @blutux if you're willing to post a blog post somewhere about which provider you have, and what steps you had to do to make Sandstorm work properly, that might save other people some time too!

Or you can just say it here and then at least Google will index this and people will know what to do.

Glad this got resolved.

**Comment by blutux** [comment]
My provider is a OVH, I have a kimsufi dedicated server and I install Jessy Debian version in 64 bits (like that i have the right kernel). To install the unmodify os, i've check the checkbox "use the distribution kernel" in the personalized installation mode

**Comment by samuel-finistere** [comment]
Hi! I posted a comment on similar issue here: https://github.com/sandstorm-io/sandstorm/issues/671
But I discovered that we have exactly the same pbl (I use a Kimsufi @ OVH)

@blutux do you know if it's possible to get the original kernel without reinstalling my server ? (I don't want to wipe 300GB of data)

**Comment by samuel-finistere** [comment]
ok forget the question,
In the meantime, I was fed up with Atom processors, I purchased a stronger server (core i3 / 16GB ram). During setup I chose the right kernel option :)

For the record, I got from a colleague the answer to my question  (thanks a bunch @jderrien ^_^).

So, to switch an OVH dedicated server from netboot with OVH's home made kernels to an original Debian kernel, without loosing any data (hopefully):

* Install kernel from Debian
```
   aptitude install linux-base linux-headers-amd64 linux-image-amd64 firmware-linux-free firmware-linux-nonfree firmware-netxen firmware-realtek
        update-initramfs -k all -u -t
```

* Update grub config (depending on the options chosen during server install)
```
        mv /etc/grub.d/06_OVHkernel /etc/grub.d/15_OVHkernel
        update-grub2
```
* Disable netboot on OVH manager (Select `hdd`), then reboot the server
