### ISSUE TITLE
If-None-Match: * should be accepted (rather than turn the request into a 400)

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1437]
@synchrone noticed on #sandstorm earlier today that we crash in `proxy.js` if a request comes in with `if-none-match: *`.

@dwrensha noticed we do handle `if-match: *` but don't yet handle `if-none-match: *`.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html indicates that `*` is an acceptable value.

**Comment by paulproteus** [comment]
Stack trace: http://pastebin.com/aSjdxbKK

**Comment by dwrensha** [comment]
From the newer RFC: http://tools.ietf.org/html/rfc7232#section-3.2

**Comment by paulproteus** [comment]
@mnutt expressed an interest in look into this; I'll let him comment further in a bit.
