### ISSUE TITLE
403 after long idle in Paperwork

### ISSUE THREAD

**Issue by funwhilelost** [sandstorm-io/sandstorm#1458]
I've got my Sandstorm open on a pinned tab in Chrome.  When I come back each morning with a Paperwork grain open it can't seem to save my notes.  The failures have these errors in the JS console:

```
openSession error
r {error: 403, reason: "Unauthorized", details: "User is not authorized to open this grain.", message: "Unauthorized [403]", errorType: "Meteor.Error"}
```
and
```
POST grain-id.sandstorm/api/v1/notebooks/id/notes 404 (Not Found)
```

After a hard refresh everything works fine.

**Comment by jparyani** [comment]
Thanks for the bug report! This actually explains what's going on in #1335. On meteor reconnecting, openSession will be called before the client has had a chance to go through Meteor's automatic login mechanisms. We need to check for `Meteor.loggingIn()` before calling openSession.

**Comment by funwhilelost** [comment]
Glad to give you another angle on this.  :+1:
