### ISSUE TITLE
grain not loading when using local sandstorm server

### ISSUE THREAD

**Issue by vanceaadi** [sandstorm-io/sandstorm#1469]
I've installed sandstorm on a Ubuntu 15.10 machine using 
curl https://install.sandstorm.io | bash

I've setup the server and logged in.
Then I've installed Etherpad and created a new grain.
It starts loading and gets stuck on the spinning circle. After 10 minutes, still nothing.
Debug log: Untitled Etherpad pad

...** SANDSTORM SUPERVISOR: Starting up grain.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.

I've tested other apps, and all present the same issue, grain does not load.

Am I missing something?

**Comment by paulproteus** [comment]
Hi there! What is the contents of your sandstorm.conf? Specifically:

BASE_URL=...
WILDCARD_HOST=...

What you're describing is often caused by a DNS configuration that doesn't
support wildcard hosts. See
https://docs.sandstorm.io/en/latest/administering/faq/#why-do-i-see-an-error-when-i-try-to-launch-an-app-even-when-the-sandstorm-interface-works-fine
for more.

If you don't want to reveal those publicly here on GitHub, you can email
support@sandstorm.io and we can try to take care of you there. Thanks for
asking and for trying Sandstorm!

**Comment by vanceaadi** [comment]
> cat /opt/sandstorm/sandstorm.conf 
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://vanadr-ubulat64:6080
WILDCARD_HOST=*.vanadr-ubulat64:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false

**Comment by paulproteus** [comment]
Got it.​ I think that you'll find that vanadr-ubulat64 does not have
wildcard DNS, which will result in the problem described in the FAQ page
about wildcard DNS.

You can test this by doing:

ping example.vanadr-ubulat64

**Comment by vanceaadi** [comment]
Thanks for the prompt response.

**Comment by paulproteus** [comment]
You're welcome!

You can try using http://xip.io/ to get wildcard DNS for an internal IP address, and you can try using https://sandcats.io for getting wildcard DNS for a public IP address!

I hope this doesn't stop you from using Sandstorm entirely. xip.io is widely-liked.

**Comment by Apidcloud** [comment]
I'm facing the same issue. I have installed Sharelatex but can't load a document (a grain).

My conf is as follows:
`SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://192.168.121.128:6080
WILDCARD_HOST=*.192.168.121.128.sandstorm.io:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
`
I just want to use it locally, so the base url and wildcard use the virtual machine IP address. Is it wrong?

Thanks!

**Comment by paulproteus** [comment]
Hi @Apidcloud ,

There's an error in your `WILDCARD_HOST` - `sandstorm.io` doesn't provide wildcard DNS for IP address, but xip.io does. See this link:

https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-use-sandstorm-with-an-internal-ip-address

Let me know if that helps you out!

**Comment by Apidcloud** [comment]
@paulproteus Thanks for your prompt response! It worked :+1:

**Comment by AndrewSav** [comment]
Similar issue here. Config:

```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://shkaf:6080
WILDCARD_HOST=*.shkaf:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
```
Browser console:

```
shell-client.js:722 App authors: To understand the grain-frame in Sandstorm and how to find logs and perform troubleshooting, see: - https://docs.sandstorm.io/en/latest/developing/path/ - https://docs.sandstorm.io/en/latest/using/top-bar/ - https://docs.sandstorm.io/en/latest/developing/troubleshooting/ When debugging, make sure you execute Javascript in the context of the 'grain-frame' IFRAME. References: - https://stackoverflow.com/questions/3275816/debugging-iframes-with-chrome-developer-tools - https://developer.mozilla.org/en-US/docs/Tools/Working_with_iframes We can also provide personal assistance! Get in touch: https://sandstorm.io/community
ui-4e4c8030ca9aad3f9da7bfa01f06d5a6.shkaf/:1 
        
        
       Failed to load resource: the server responded with a status of 403 (Unauthorized)
ui-67ddfbdbc3e6c071abb1d56268837d97.shkaf/:1 
        
        
       Failed to load resource: the server responded with a status of 403 (Unauthorized)
ui-9f0226a9deccd1b1736ef9e95b6beebd.shkaf/:1 
        
        
       Failed to load resource: the server responded with a status of 403 (Unauthorized)
ui-9cacfd2369fe8fdbecb7caec4bdd106d.shkaf/:1 
        
        
       Failed to load resource: the server responded with a status of 403 (Unauthorized)
ui-eb5088f3cc7c8d0e6151af719d132907.shkaf/:1 
        
        
       Failed to load resource: the server responded with a status of 403 (Unauthorized)
 uBOL: Generic cosmetic filtering stopped because no more DOM changes
```

Ping is working:

```
 ping ui-67ddfbdbc3e6c071abb1d56268837d97.shkaf

Pinging ui-67ddfbdbc3e6c071abb1d56268837d97.shkaf [192.168.88.53] with 32 bytes of data:
Reply from 192.168.88.53: bytes=32 time<1ms TTL=64
Reply from 192.168.88.53: bytes=32 time<1ms TTL=64

Ping statistics for 192.168.88.53:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

What could be wrong?

**Comment by ocdtrekkie** [comment]
@AndrewSav This probably should be a new issue, but does this occur any time you try to open an app, or for a specific app only? Do you have cookies blocked with your browser, perhaps? (Sandstorm uses a cookie to convey permission for a given browser session to access a grain.)

**Comment by AndrewSav** [comment]
> @AndrewSav This probably should be a new issue, but does this occur any time you try to open an app, or for a specific app only? 
For all of them - in the log you see 5 errors one per each of the default apps.

>Do you have cookies blocked with your browser, perhaps? (Sandstorm uses a cookie to convey permission for a given browser session to access a grain.)
No. Not many people do nowadays, or internet would break ;)

Anyway, I found a solution. If instead of:

```
BASE_URL=http://shkaf:6080
WILDCARD_HOST=*.shkaf:6080
```

you do:

```
BASE_URL=http://shkaf.domain.tld:6080
WILDCARD_HOST=*.shkaf.domain.tld:6080
```

then it works. Probably should be documented in the installation notes / troubleshooting (or better yet fixed - it could well be that the way cookies are set up for wild card domains by sandstorm could be incorrect)

**Comment by ocdtrekkie** [comment]
Interesting, I didn't notice the single-name resolution earlier but that doesn't surprise me too much. I know Chromium browsers didn't want to work right with *.localhost, which is why local.sandstorm.io exists. Would probably indeed be good to add an installation note in the docs.

**Comment by AndrewSav** [comment]
> Would probably indeed be good to add an installation note in the docs.

Another thing to consider is the installer prompt. It defaulted for me to `http://shkaf:6080` and the help text in the installer did not give any indication that this might not work.
