### ISSUE TITLE
Can't revoke access to grains if a user is added directly

### ISSUE THREAD

**Issue by zombiezen** [sandstorm-io/sandstorm#1477]
Context: https://groups.google.com/d/topic/sandstorm-dev/QBCmzrKVMD8/discussion

My original problem description:

> On my self-hosted instance, I've noticed that there's no longer a UI to revoke shared permissions of a grain I own and have shared with someone else.  Is this an intentional change that I missed?  If so, what's the rationale?
> 
> (For reference, I'm on 0.141.  I'm going to "Share access" > "See who has access" and I have a name of a user on the system.)

Quoting Kenton:

> It used to be that to share with someone you would always send them a sharing link. To revoke them, then, you'd revoke the link. The user list didn't let you revoke directly because the user could always revisit the link again and regain access.
> 
> However, it's now possible to add users directly. But, when that was added, we apparently forgot to make sure you could revoke those users directly. :(

**Comment by dwrensha** [comment]
This was fixed in #1468.
