### ISSUE TITLE
"Install this app" doesn't say which app

### ISSUE THREAD

**Issue by mkj** [sandstorm-io/sandstorm#15]
I visit https://alpha.sandstorm.io/install/4e1da8cec67250de8fa80371bc21f4eb?url=http://sandstorm.io/apps/ipython-notebook.spk and it says

Install this app?
Do you want to install this app?

[button]Install[/button]

But the only indication of the App's name is in the URL.

**Comment by rds13** [comment]
Having just install my first application I do find it surprising to not see any application name on that step. I was about to fill a bug report for that too.
I've read all the comments and still I think there should be an application name displayed. It could simply be shown between quotes with an unverified badge as long as we cannot provide a workflow for trusted applications.

**Comment by glamrock** [comment]
I was just noticing this as well. The intermediate fix could be as simple as a `&app=` flag in the referring url.

**Comment by kentonv** [comment]
We do actually have metadata for this in the package now. I suppose we should go ahead and display the name from there, and once the app store is up we can start doing actual verification of names.
