### ISSUE TITLE
Implement some sort of "local developer account" login

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#150]
For the purpose of a localhost Sandstorm server that is only accessible to one person anyway and is intended only for development, it would make sense to implement some way to create test users and log in as them. This way, people don't have to hook Google or Github authentication just for their silly testing.

The feature should NOT use passwords or anything else that could be mistaken for security. The developer should be able to create as many users as they want and arbitrarily log in as any of them by just choosing the account from a list.

We can implement this pretty easily using the same approach as the "demo user" code.

**Comment by timmolter** [comment]
Just to leave a note about the Google login setup, it failed for me, whereas the GitHub one worked.

It said `Invalid redirect URL` for a split second, and that was it. The redirectURL Sandstorm told me to use was: `http://1.2.3.4:6080/_oauth/github` (not the real IP address, but it was a raw one).

**Comment by kentonv** [comment]
> The redirectURL Sandstorm told me to use was: `http://1.2.3.4:6080/_oauth/github` (not the real IP address, but it was a raw one).

Hmm, the redirect URL said "github" when you were trying to use google? Is it possible you copy/pasted the wrong thing somewhere? This is Meteor's login code which is pretty well-tested.
