### ISSUE TITLE
Run Standstorm on Local LAN

### ISSUE THREAD

**Issue by elgenmfg** [sandstorm-io/sandstorm#1500]
Hello,

I am trying to configure Sandstorm to run locally on our intranet. 
So far Sandstorm loads, but none of the apps able to start. I am seeing this message:

** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
Here is the admin log:

** Starting Sandstorm at: Wed Feb 10 07:21:17 2016
** Starting back-end...
** Starting MongoDB...
Found a stale mongod lock file. Removing it.
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
Migrations already applied: 20/20
SANDCATS_BASE_DOMAIN is configured but your HOSTNAME doesn't appear to contain it: sandcats.io 10.10.10.200

Here is the contents of the config file:

SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND IP=10.10.10.200
BASAE_URL=http://10.10.10.200:6080
WILDCART_HOST=*.local.sandstorm.io:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNT=false
SANDCAST_BASE_DOMAIN=sandcast.io

Is there any way to set this up to access the  app at 10.10.10.200:6080 without having a subdomain?

**Comment by dwrensha** [comment]
Maybe http://xip.io/?

**Comment by paulproteus** [comment]
Hi @elgenmfg ,

Thanks for asking this question.

I just wrote some new documentation to hopefully answer your question, as well as help others in the future: https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-use-sandstorm-with-an-internal-ip-address

Does that help answer it? Let me know!

**Comment by ocdtrekkie** [comment]
I am kinda sad there aren't better solutions built into Windows and such for this. Wildcard support in my HOSTS file would be nice.

I hadn't heard of xip.io before, and it seems like a nifty thing.

**Comment by paulproteus** [comment]
There are crazier options for Windows, such as
http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome ... but
yeah, xip.io is a bajillion times easier.

**Comment by ocdtrekkie** [comment]
Is it wrong that I kinda want to try that though?

**Comment by paulproteus** [comment]
Dude I once stepped someone through using it, in almost a day's worth of
time spent in Twitter direct messages.

The DNS proxy has security upsides - specifically, xip.io could decide to
change what IP address your thing binds to, and serve you a phishing site.
I guess they'd have difficulty man-in-the-middle-ing you though since it's
to an internal IP address, so that's nice actually!

**Comment by elgenmfg** [comment]
Hi @paulproteus,

Thanks for the detailed instruction, but unfortunately  after installing Wekan the board still not loading. I am getting these messages:

...** SANDSTORM SUPERVISOR: Starting up grain.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.

and in the admin log:

** Starting Sandstorm at: Fri Feb 12 05:57:20 2016
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
Migrations already applied: 20/20
fetching keybase AD1E0DD65E86C787D602EDF15D34826FE06DA95D
fetching keybase AD1E0DD65E86C787D602EDF15D34826FE06DA95D
fetching keybase AD1E0DD65E86C787D602EDF15D34826FE06DA95D
fetching keybase AD1E0DD65E86C787D602EDF15D34826FE06DA95D
keybase lookup error: Error: ETIMEDOUT
    at [object Object]._onTimeout (/programs/server/npm/http/node_modules/request/request.js:909:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
keybase lookup error: Error: ETIMEDOUT
    at [object Object]._onTimeout (/programs/server/npm/http/node_modules/request/request.js:909:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
keybase lookup error: Error: ETIMEDOUT
    at [object Object]._onTimeout (/programs/server/npm/http/node_modules/request/request.js:909:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
keybase lookup error: Error: ETIMEDOUT
    at [object Object]._onTimeout (/programs/server/npm/http/node_modules/request/request.js:909:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
fetching keybase AD1E0DD65E86C787D602EDF15D34826FE06DA95D
keybase lookup error: Error: ETIMEDOUT
    at [object Object]._onTimeout (/programs/server/npm/http/node_modules/request/request.js:909:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

Here is the contents of the config file:

SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND IP=10.10.10.200
BASAE_URL=http://10.10.10.200.xip.io:6080
WILDCART_HOST=*.l10.10.10.200.zipo:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNT=false
#SANDCAST_BASE_DOMAIN=xip.io

**Comment by elgenmfg** [comment]
@paulproteus thanks very much for the detailed article! Sandstorm is now working with an internal IP!

Cheers!

**Comment by paulproteus** [comment]
Hi there! I'm so glad you got it working!​

**Comment by icf20** [comment]
this config is not longer working
