### ISSUE TITLE
Problems with running install.sh twice

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1503]
This issue lists a bunch of problems that can occur when you run `install.sh` twice, just to make sure I have them all in once place. I'll be editing it over time.

## sandcats key is "already in use"

```
What *.sandcats-dev.sandstorm.io subdomain would you like? [] hee3rang
We need your email on file so we can help you recover your domain if you lose access. No spam.
Enter your email address: [] hee3rang@asheesh.org
Registering your domain.
There is already a domain registered with this sandcats key. If you are 
re-installing, you can skip the Sandcats configuration process.
```

Note that then when you type `none` in, it defaults to using localhost as the base domain, which is useless.

It also then offers these mismatched variables:

`URL users will enter in browser: [http://localhost:6080] `
`Wildcard host: [*.local.sandstorm.io:6080] `

both of which do end up in `sandstorm.conf`

```
BASE_URL=http://localhost:6080
WILDCARD_HOST=*.local.sandstorm.io:6080
```

**Comment by paulproteus** [comment]
Sandstorm *does* appear to start properly, however, so that's good.

**Comment by paulproteus** [comment]
And doing *another* reinstall on top of that is also OK.

**Comment by paulproteus** [comment]
## Other uses-cases for the installer

If there is a system-wide sandstorm, but you want one in `$HOME`, we should make sure that remains a possibility.

**Comment by dwrensha** [comment]
See also https://github.com/sandstorm-io/sandstorm/issues/660.

**Comment by paulproteus** [comment]
I declare this issue fixed by https://github.com/sandstorm-io/sandstorm/commit/c639db73ad5d7b1a9632811363955c705be1e6e1 . If we want some smarter handling, that can be designed in #660 if someone wants.
