### ISSUE TITLE
Add search cancel/clear button

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1504]
Recent user test indicates that our search UX is not great. User had problems cancelling the search as we currently have no mechanism to do that except to clear the text.

Something as simple as the x icon we use for closing grains would suffice.

![image](https://cloud.githubusercontent.com/assets/855341/12960891/8d74db1e-cff2-11e5-8db2-abe263d79794.png)

**Comment by zarvox** [comment]
That would work.  A text button "Clear" conjoined with the input box might be even clearer, and more accessible to boot.

Google Docs search's X button produces a giant tooltip when you hover over it explaining what it does, so I'm inclined to think that having a text label is worthwhile.  Interestingly, Google search itself has no clear button.

**Comment by neynah** [comment]
@zarvox Good point. Yes, I think a "Clear" button conjoined would be clearer than the x.

Hmm I guess this poses the question then if having "no results" text + a clear button is worse than just having "no results" text.

**Comment by zarvox** [comment]
I would say that the urgency of a quick way to clear the search is indeed lower, but that it is still a potentially nice affordance to have, especially on mobile, where clearing an input box can be more burdensome.

The fact that the search box clears when you navigate away from the /apps page also makes this less urgent.

**Comment by neynah** [comment]
I think with our "no results" search fix, enabling a search clear button is less impactful & perhaps not necessary. Going to close this for now. :)
