### ISSUE TITLE
Hover titles missing for some top nav items

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1505]
Discovered to be inconvenient in user testing. I propose to be consistent and add hover text to the following top bar items (that are missing hover titles):
- share access
- webkey
- notifications

![uifix-hovertext](https://cloud.githubusercontent.com/assets/855341/12961385/0fe35d3a-cff5-11e5-9fd2-000c2ae3410c.png)

**Comment by zarvox** [comment]
Notes to self: this is made awkward by the fact that when you provide sandstorm-ui-topbar a popup template, it owns the button (and the callback to show the template), but if you don't, then you render the button yourself.

A better approach might be pushing the DOM for the button down into the component's template itself, which would allow the component to specify the button hovertext there with the button itself.

**Comment by zarvox** [comment]
This will want to wait until my powerbox changes are in, since they'll conflict for the Powerbox button templates.  But I'll take care of this soon thereafter.
