### ISSUE TITLE
Sidebar collapse button is too small

### ISSUE THREAD

**Issue by rlafuente** [sandstorm-io/sandstorm#1513]
Currently, the sidebar collapse button is exceedingly discreet and easy to miss (I did for a couple of weeks).

I went to the [original issue](https://github.com/sandstorm-io/sandstorm/issues/872) where the button was suggested, and it looks great on the screenshots with the custom "<", better than the arrow actually. But on the actual front-end it's just the character `<`, which doesn't look half as good as the larger glyph.

Replacing the plaintext `<` character with an SVG icon that looks closer to the original design intent would solve this.

**Comment by neynah** [comment]
Thanks for filing this @rlafuente, we were unaware that anyone was having issues with the current sidebar collapse button. I'll queue this for things we should fix soon. :)

**Comment by paulproteus** [comment]
Since this got reverted in https://github.com/sandstorm-io/sandstorm/pull/1561 , re-opening for now.

**Comment by paulproteus** [comment]
@jparyani any chance you'd be interested in revising this, this week, to be mergeable? @neynah and I would love it if so.

**Comment by jparyani** [comment]
Ya, I'd be happy to. @neynah, can you make icons for the left/right arrow?

**Comment by neynah** [comment]
Sure thing, I'll do that today. :)

**Comment by paulproteus** [comment]
Resolved: fixed!
