### ISSUE TITLE
Make hiding of vertical left-column panel (with grains list) sticky

### ISSUE THREAD

**Issue by gwillen** [sandstorm-io/sandstorm#1525]
It's awesome that the left-column panel with the grains list can be hidden with the left-arrow icon.

It would be awesomer if, once hidden, it stayed hidden across all apps until unhidden OR there was some other way to make it default to hidden.

I bring this up because I have a friend who uses his monitor in a 'portrait' configuration, and the left bar is causing him to feel grief about the amount of valuable horizontal screen real estate it's wasting.

I know the usecase is uncommon, but it seems like a fix wouldn't be too hard!

Thanks!

**Comment by paulproteus** [comment]
I am gently +1 on this, fwiw.

**Comment by simonv3** [comment]
+1. I have a smaller screen and I much prefer the real estate to be freed up. Every time I open a Sandstorm grain I collapse the sidebar.

**Comment by kentonv** [comment]
Is it sufficient for this to be implemented using localStorage or does it need to be stored against the user in the database?

**Comment by gwillen** [comment]
As far as I'm concerned, localStorage is totally fine. My friend with the portrait monitor would have no issue with that. (I'm assuming it would still be configured to stick around all new Sandstorm windows on that machine, not just for one grain, say.)

**Comment by ocdtrekkie** [comment]
I feel like the inability to close a grain from the minimal menu is the biggest problem with being able to keep it that way. I'd love to keep it minimized, but we need a way to close crud from it. Three clicks to close a grain is kinda painful. (Open tray, click X, close tray.)

**Comment by simonv3** [comment]
I would be fine with it being stored in localStorage. Even a cookie! 

This might be peculiar to me - but I don't think I've ever closed a grain. I also don't manage my own sandstorm instance, so I'm not very conscious of the open grains, so that's not a usecase that had occurred to me. @ocdtrekkie do you close them en masse or one by one when you're closing grains? What if there was a toggle at the top that goes into "close grain" mode. Similar to how you can close running apps on Android or iOS? 

Toggle -> Icons turn into 'x's -> close relevant grains.

**Comment by ocdtrekkie** [comment]
@simonv3 If we turned the icons into X's it'd be very hard to tell what you're closing. I suggested the tkp bar idea myself, actually.

**Comment by gwillen** [comment]
I have also never closed a grain, and I have to be honest, I'm not sure what closing a grain actually _does_. The grain is still alive on the backend, right? I'm just closing my local session to it? I tend to manage those sessions the same way I manage Android apps, and to some degree browser tabs -- I just let them sit there forever and ignore them.

**Comment by simonv3** [comment]
@ocdtrekkie, I was imagining the icon would still be visible but with a red x. I'll see if I can find an example screenshot from iOS. but yeah, I'm not sure it's the best solution.

**Comment by ocdtrekkie** [comment]
@gwillen Open grains consume RAM. Closed grains are shutdown, AFAIK. So if you leave your Sandstorm window open all day, closing grains saves you GBrh if you're on Oasis (once they count it).

**Comment by kentonv** [comment]
FWIW, we plan to make it so that even grains that are "open" as tabs will have their server-side shut down if you don't look at that tab for a long time (and started back up as soon as you go back to that tab).

But yeah, currently leaving the tab open forces the grain to stay running on the server.

**Comment by simonv3** [comment]
This is what it looks like in iOS when you're in app "delete" mode: 

![delete apps](http://innov8tiv.com/wp-content/uploads/2014/01/cydia-app-delete-app-iOs-7.png)

**Comment by paulproteus** [comment]
FWIW that's basically how the app uninstall mode works within Sandstorm;
curious if you've tried it and what you think of it.

**Comment by simonv3** [comment]
Hah! I thought I had seen it on Sandstorm. I think it's a pretty good pattern, though pretty hard to discover on iOS. Not so on Sandstorm.

**Comment by paulproteus** [comment]
One fun fact on Sandstorm is that the meaning of uninstalling an app is
pretty unclear, IMHO. It doesn't remove your data that was created with
those apps, aka your grains of the app. Presumably it shouldn't remove
those grains. but maybe we should indicate that to people so they aren't
scared. I for one assumed it would.

**Comment by simonv3** [comment]
Oh hm. not to carry off on a tangent too much - but likewise on OS X it's not very clear what uninstalling software does. Usually I feel like it leaves the customizations the user had for the app in place (in their usr/ folder or wherever). Uninstalling an app on OS X just means uninstalling the launcher and interface (just throwing them in the trash). The files that it creates stay there for a lot of apps (unless they were contained within the app's bundle). 

I'm a bit more confused about what "installing" an app means in Sandstorm.

**Comment by paulproteus** [comment]
"installing" an app means, "You have the ability to create grains with this
app."​

Hopefully that helps explain things? If not, let me know what to clarify,
because I do think it'd be useful to write this up somewhere.

**Comment by gwillen** [comment]
@paulproteus I think a general "app/grain lifecycle" post would not be out of order at all. I could have guessed either way as to whether removing an app would remove associated grains. I don't really understand, on a given server, who has permission to install apps / create grains, and whether installed apps are scoped to a server or a user. (Or whether this is different for e.g. alpha/oasis, which are multitenant systems so obviously users have to be able to install apps, versus e.g. private sandstorm servers like personal or corporate ones.)

And I also had no idea that closing a grain from the grain list in the left sidebar would terminate it on the server. In fact, I feel like I find that strongly counterintuitive, since that list appears to be a list of grains I've opened in this window, not a list of grains that are running on the server... I guess the new mental model I'm developing, integrating all this, is that the left-bar entry is a "handle" to a grain on the backend, and when all "handles" are close, either by X'ing them _or_ by closing the window they're in, then the grain can be GC'ed?

I would pretty much not have had a chance of guessing that model, if that's the true model, before this conversation. :-) (And if it's not, I'm at a loss as to what the true model is... and I'm a fairly informed user who has had multiple conversations with the Sandstorm developers, as you know.) So yeah, I think a grain lifecycle document would be excellent.

**Comment by gwillen** [comment]
Yay! Thanks! :D
