### ISSUE TITLE
Fix typo / improve message for error: identity already linked

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1526]
So I attempted to link an identity I already had linked:
- initially, the error made me think something failed & I could not achieve linking the identity
- I feel that maybe it's acceptable just to have a message that says something like "This identity is already linked." instead of producing an error.
- The error message is also pretty wordy/repetitive and "alread" should be "already"

![image](https://cloud.githubusercontent.com/assets/855341/13021817/082b67d8-d192-11e5-82c8-b1dd4f9e7645.png)

**Comment by paulproteus** [comment]
@neynah what is the expected behavior here? Perhaps a message at the bottom saying:

>Success: Identity was already linked to this account!

in the same place as the "error" message is now?

**Comment by neynah** [comment]
Wow your suggestion is great. Let's go with that. :)

**Comment by paulproteus** [comment]
OK, great. I can probably tackle this during this week. Self-assigning for that reason.
