### ISSUE TITLE
Proposal for top bar design adjustment

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1558]
Some users during our usability testing have experienced confusion and did not expect actions in the top bar to affect the grains. Main change I'm proposing that I suspect may help:
- matching the sandstorm sidebar section with the rest of the sidebar (similar to previous design: https://github.com/sandstorm-io/sandstorm/issues/872)

If that's not enough, we can also:
- slightly lighten the background colour of grain actions in the topbar

![image](https://cloud.githubusercontent.com/assets/855341/13200304/0e5c2c8a-d7f7-11e5-96ed-07459b48ab8c.png)

Current:
![image](https://cloud.githubusercontent.com/assets/855341/13200314/5121a20c-d7f7-11e5-9357-3043550800e6.png)

**Comment by zarvox** [comment]
I'm curious what this would look like with the sidebar collapsed.

**Comment by neynah** [comment]
Similar to https://github.com/sandstorm-io/sandstorm/issues/872 but without the arrow beneath the Sandstorm logo:
![image](https://cloud.githubusercontent.com/assets/855341/13587194/470a0602-e47b-11e5-8c76-e49b0dbb4393.png)

**Comment by zarvox** [comment]
That makes the topbar 48px tall, whereas right now it sits 32px tall.

**Comment by neynah** [comment]
It's an old mock-up so it's not 100% accurate with our current UI. The only change I'm proposing in this issue is for the width of the Sandstorm logo section, not the height of the topbar. We'll maintain it at 32px tall. I just thought you'd want a quick glance not something 100% pixel perfect. :)

**Comment by zarvox** [comment]
Yeah, I'm definitely in support of this idea in principle; just trying to tease out the little details needed to actually implement this.

The "Apps" and "Grains" buttons will look a bit large next to the topbar and grains, if we leave them at their current size.  The text for "Sandstorm" would wind up being smaller than the other things in the "list", despite the structure of the list hinting that these are in fact the same kind of thing.  Not sure if it'd be better to expand the topbar, shrink the "Apps" and "Grains" links, or something else entirely.

I guess we'd probably want the Sandstorm icon to line up with the other navbar icons.  When the sidebar collapses, I'd expect the other items in the topbar (like grain title or current route) would shift left as the Sandstorm button shrinks as well.

**Comment by neynah** [comment]
Yes, we'd have to make adjustments to the Sandstorm icon & text to align it with the other navigation items. This is what it would look like to change the Sandstorm logo to match:

![image](https://cloud.githubusercontent.com/assets/855341/13588433/7c779dc8-e484-11e5-870b-77a97bafb601.png)

The other option (to keep all items consistent) would be to scale down "Apps" and "Grains" sections (including icon + text) and then styling them/increasing the contrast to differentiate them from grains. I can mock that up if that's the direction we want to pursue but until then I think we should stick with the above as the first fix.

**Comment by ocdtrekkie** [comment]
I'd like to avoid making the top bar larger than necessary for purely cosmetic reasons. /opinion

**Comment by kentonv** [comment]
FWIW, I think @neynah's last image looks pretty good.
