### ISSUE TITLE
Resulting sandstorm admin-token URL  http://local.sandstorm.io:6080/admin/settings/<foo> doesn't work

### ISSUE THREAD

**Issue by jeremiah** [sandstorm-io/sandstorm#1559]
Nor can I reach http://yaalr.sandcats.io:6080/admin/settings/<foo> when I go through the internet server config set-up.

**Comment by jeremiah** [comment]
I'm getting "Connection Refused" when I try and access a sandstorm generated link.

**Comment by jeremiah** [comment]
Here's my config:

SERVER_USER=sandstorm                                                                                                                                                                                                            
PORT=6080                                                                                                                                                                                                                        
MONGO_PORT=6081                                                                                                                                                                                                                  
BIND_IP=0.0.0.0                                                                                                                                                                                                                  
BASE_URL=http://yaalr.sandcats.io:6080                                                                                                                                                                                           
WILDCARD_HOST=*.yaalr.sandcats.io:6080                                                                                                                                                                                           
UPDATE_CHANNEL=dev                                                                                                                                                                                                               
ALLOW_DEV_ACCOUNTS=yes                                                                                                                                                                                                           
SANDCATS_BASE_DOMAIN=sandcats.io

**Comment by ocdtrekkie** [comment]
Is there a reason you are not on https with Sandcats? I don't know if that's a problem, but it seems odd to me.

**Comment by jeremiah** [comment]
Firewall. :-)

I had the ports 6080 and 30025 blocked. I already have some hosts running on 443 and 80 so sandstorm could use those. I punched a hole in my firewall and now I can reach sandcats.io

I wonder if there might be an option to allow that? That is to say, if sandstorm finds that there already is a web server running, would it be able to configure itself by re-using the running web server?

**Comment by kentonv** [comment]
@jeremiah We could in theory implement auto-configuration for common reverse proxies, but it would be tricky since there is such a wide array of things to support here: nginx, apache, HAProxy, every distro-specific flavor thereof, etc. We have talked about doing it but haven't yet.

**Comment by jeremiah** [comment]
I think that your solution is the right way to go, it preserves the security chosen by the admin of the node. What I think may help is further documentation around the required hole in the firewall. 

During set up I read that there were non-standard ports used, but it would have helped me to have a bit more documentation on why and perhaps encourage admins to think about their firewall in relation to Sandstorm. 

In the end this issue was due mostly to my haste than to the docs or the software. :-)
