### ISSUE TITLE
Minor Style: Down arrow displays wrong in Edge

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#1560]
I don't remember what particular quirk of formatting causes this, but it was fixed on most of the other SVGs in Sandstorm. This probably affects IE11 too, but I didn't check.

![image](https://cloud.githubusercontent.com/assets/4399499/13206099/3f8db12c-d8bd-11e5-963d-01bd37f8ed5c.png)

**Comment by neynah** [comment]
:(

**Comment by kentonv** [comment]
IE for some reason has different opinions from the rest of the world on how SVGs should be positioned. Probably we need an `xMidYMin` or something attribute.

**Comment by kentonv** [comment]
(That is, we need to open the SVG in a text editor and add the correct attribute like that. You'll see the attribute or something similar in some of the other SVGs, for example. "xMidYMin" means "center in the X direction, push to 'min' in the Y direction (top)".)

**Comment by kentonv** [comment]
Fixing it in #1574 by moving to fonticons instead of svg.

**Comment by kentonv** [comment]
Incidentally, this particular issue seems to be Edge-only, _not_ IE, which is unusual! I don't have Edge to test on, but since fonticons are way more consistent between IE and Chrome I bet they'll work better on Edge too.

**Comment by zarvox** [comment]
FWIW, you can download VMs of all the various IE + Edge versions at https://dev.windows.com/en-us/microsoft-edge/tools/vms/linux/
