### ISSUE TITLE
docs: icon size info could be clearer, in app market publishing guide

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1564]
@phildini had a problem where had received only one icon from @neynah and wasn't sure about the following things:

- Relative to what directory does the `embed` occur? (Answer: `.sandstorm/`)

- Will it follow symlinks? (Answer: Yes, I guess?)

- Which icons truly _need_ to be filled out? Does he need to specify image sizes for an SVG? (Answers: Just the first one. No.)

Also @neynah I think we have four image formats because we have different notions of how they should be styled, like different border-radius or similar. If that's true, we should write it down somewhere! Or maybe we already do write it down somewhere and I should link to it from the app market publishing docs?

**Comment by neynah** [comment]
@phildini asked me for an SVG without noticing that I already created a PR with the appropriate sizes: https://github.com/phildini/logtacts/pull/50

(I also sent him the SVG without realizing he didn't notice my PR and that's been corrected since.)

FWIW, we require 4 sizes for bitmap and 3 sizes for vector. I can update the docs accordingly.

**Comment by neynah** [comment]
Via: https://docs.sandstorm.io/en/latest/developing/publishing-apps/#icons

"The appGrid icon represents your app on the "New" screen on Sandstorm. It should be 128 x 128 pixels, and no larger than 64 KB.
The grain icon represents individual grains on both the navbar and the grain list. It should be 24 x 24 pixels, and no larger than 4 KB. If you omit this, the appGrid icon will be used.
The market icon is used in the app market. It should be 150 x 150 pixels, and no larger than 256 KB. If you omit this, the appGrid icon will be used.
The marketBig icon is used on an app's specific page on the app market. It should be 300 x 300 pixels, and no larger than 256 KB. If you omit this, the market icon will be used (raster images may look bad)."

Is this sufficient or is there still some confusion?

**Comment by phildini** [comment]
I think this is mostly user error on me. Many thanks to @neynah for everything she did. The one thing that might be useful is showcasing, in the docs or in a link to elsehwhere, what your vision is for what should be different about the images. (Which you can totally use Contact Otter for, btw, if you wish)

**Comment by neynah** [comment]
Something like this @phildini?
![appicon-guide](https://cloud.githubusercontent.com/assets/855341/13233879/c9957668-d96a-11e5-8894-23e704619274.png)

**Comment by phildini** [comment]
Yeah, that's brilliant. :heart_eyes: 

Relatedly, I'm sure this is already in your head, but it seems like we're getting close to time for a "design guide" for sandstorm like there's a dev guide. When I see the above, I think "Where's the design guide this could go in?"

**Comment by ocdtrekkie** [comment]
@phildini I am super hesitant/scared of "design guides", because it inspires a certain monoculture of app design. See how Android has now gone to usability crud, and any developer who you complain to tells you to take a hike, because they're following Google's guidelines.

It makes sense to suggest ideal configuration for interacting with Sandstorm, but I vastly prefer apps go their own way on design, and do the right thing for their app.

**Comment by neynah** [comment]
Some authors would appreciate some design guidance/tips. But, I agree that we don't want to confine apps to fit a design standard that we see fit. Perhaps for now it's best for folks to poke myself/other designers individually if they'd like design suggestions.

I do, however, on the smaller scale of things think it's useful to show app authors how their icons will be displayed so they can design & prepare their files accordingly. @phildini other than app icons, are there other general guidelines that would be helpful to you?

**Comment by phildini** [comment]
That's probably a good place to leave it for now.

**Comment by paulproteus** [comment]
FWIW, my request here would be that @neynah and I work together to have the image she screenshot'd above show up in the app market docs.

**Comment by neynah** [comment]
I was planning on doing a PR to docs this weekend with the image and some notes. I assume there's not too much to do there?
