### ISSUE TITLE
Guided tour overlay does not always go away when clicking "new grain" on IE

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1573]
Tested on IE11

Steps:
1. Make sure you're logged in with an empty account.
2. Refresh to make sure you have a clean state.
3. Install an app that isn't already installed.
4. At the app details page you'll see the call-out of the "new grain" row. Click on the row to create a new grain.

Expected result: Callout overlay goes away when clicking "new grain".

Actual result:

![screenshot from 2016-02-22 18-02-59](https://cloud.githubusercontent.com/assets/4001805/13239369/8a4028ea-d98e-11e5-98f2-94df0e2753f2.png)

Note that clicking anywhere at this point causes the overlay to go away.

**Comment by kentonv** [comment]
Note that the problem only appears with a freshly-installed app. It's possible to get the callout to appear again by deleting the grain, refreshing, and returning to the app details page -- but if the app is not freshly-installed this time, the problem does not occur.

**Comment by paulproteus** [comment]
That is sad. I can test that; thanks for noticing it.

**Comment by zarvox** [comment]
I'd guess this has something to do with event bubbling/dispatch in IE.

Would be interesting to see if this affects introjs on IE11 more generally, or just in Sandstorm.
