### ISSUE TITLE
misleading error message if no cookies allowed in browser

### ISSUE THREAD

**Issue by LeSpocky** [sandstorm-io/sandstorm#1578]
Cookies are not allowed in my browser by default (Firefow with Cookie Monster Add-On). When opening a sandstorm instance (e.g. https://oasis.sandstorm.io/ ) I get the following misleading message:

> Oops, looks like there's no route on the client or the server for url: "https://oasis.sandstorm.io/." 

Maybe it should just say I have to allow cookies. (If I allow cookies, everything works fine.)

**Comment by kentonv** [comment]
Do you see this on Sandstorm instances other than Oasis? For instance, do you see it on https://alpha.sandstorm.io ? I do not think we use cookies on the main host; I would expect that you wouldn't have trouble until opening an app. We do use localStorage, but only when you log in. But oasis.sandstorm.io specifically uses CloudFlare and it does use cookies, so possibly it is the problem (and if so I'm not entirely sure if we can do anything about it).

**Comment by LeSpocky** [comment]
The message on https://alpha.sandstorm.io/ when forbidding cookies with Cookie Monster is:

> Oops, looks like there's no route on the client or the server for url: "https://alpha.sandstorm.io/." 

When allowing cookies, I see a login form.

**Comment by dwrensha** [comment]
> We do use localStorage, but only when you log in.

After #1551, we now read always read from `localStorage`.

If I select "Block sites from setting any data" in Chrome, `sessionStorage` is also blocked. Trying to read from `localStorage` or `sessionStorage` throws an exception.

**Comment by kentonv** [comment]
We should detect this and not fail. Maybe we can fall back to storing in a global variable, which will reset when people browse away, but at least they'll be able to use Sandstorm as long as they don't do that?

One problem is that OAuth redirect-based login won't work. Maybe we should switch back to popup-based login.

**Comment by zarvox** [comment]
On the other hand, popup-based login is often a lousy user experience on mobile, where the popup is often just blocked.  We probably only want to do popup-based login if we've detected that cookies/localStorage/sessionStorage are blocked.

(Do any other Meteor things break when `localStorage`/`sessionStorage` are unavailable?  I'm pretty sure Reload will have a bad time...)

**Comment by kentonv** [comment]
Right, there are situations where popup login is bad, and we shouldn't use it everywhere.

But note that on desktop popup login does have the significant advantage that it does not force reloading Sandstorm, which makes it faster. This may outweigh the disadvantage of popups being kind of ugly.

**Comment by dwrensha** [comment]
The "Oops, looks like there's no route on the client or the server for url" error seems to be fixed by
https://github.com/sandstorm-io/sandstorm/commit/8235b99b60b6bc240b3d32471843cc9431237013.

**Comment by dwrensha** [comment]
Some IRC discussion here: http://logbot.g0v.tw/channel/sandstorm/2016-03-20#112
