### ISSUE TITLE
Alternative for /proc/self/exe

### ISSUE THREAD

**Issue by pgrm** [sandstorm-io/sandstorm#1582]
I'm trying to create a stack for .net core and it was really easy. I based it on their docker image and everything went fine until I tried starting the app. I got the following error:

    dnx: src/dnx/pal.linux.cpp:14: std::string GetNativeBootstrapperDirectory(): Assertion `ret != -1' failed.
    /opt/app/.sandstorm/launcher.sh: line 32:     3 Aborted                 /opt/DNX_BRANCH/runtimes/default/bin/dnx -p project.json web

turns out the code failing is 

    ssize_t ret = readlink("/proc/self/exe", buffer, PATH_MAX);

from [aspnet/dnx/src/dnx/pal.linux.cpp](https://github.com/aspnet/dnx/blob/7ac7929aa575e17b3c271e4a7a0c164418de0395/src/dnx/pal.linux.cpp). AFAIK one of the differences between sandstorm and docker containers is the missing /proc in sandstorm. Also, I couldn't find an alternative to `/proc/self/exe`

unfortunately my C++ skills are limited at best so I'm stuck here a bit. I also know that MS is working on replacing dnx with dotnet cli, but that doesn't help since it also will want to use the same functionality: https://github.com/dotnet/cli/search?utf8=%E2%9C%93&q=get_own_executable_path

Any suggestions how I could get ASP.Net Core 1.0 running in sandstorm?

PS here are my changes: https://github.com/pgrm/vagrant-spk/commit/ec5625d131eefe4e00107e234c5f4cbd9a163222

**Comment by kentonv** [comment]
I would call this a bug in .NET: good Linux apps have a fallback if /proc isn't available, and generally the right way to find the executable path is based on argv[0] in any case.

That said, that doesn't help you!

Perhaps as a hack you could map a "fake" /proc into your app. In sandstorm-pkgdef.capnp you can define a mapping from /proc to some alternate directory in which you set up self/exe to be a symlink to your executable. As long as your app only has one .NET executable then it'll work?

**Comment by pgrm** [comment]
@kentonv thx - that sounds like an easy solution, unfortunately it isn't. I've tried to create the link like this:

	mkdir -p /proc/self/
	ln -s /opt/DNX_BRANCH/runtimes/default/bin/dnx /proc/self/exe

When I do it in `setup.sh` and `build.sh` I get the error that `/proc/self/exe` already exists. That might be the reason, `dnu` and all the other commands work. When I do it in `launcher.sh` I get the error that `/proc` is readonly and I can't write to it. I'll mention this also the the .Net guys and link this issue later today.

**Comment by kentonv** [comment]
@pgrm Since `proc` already exists in the VM, you'll need to name the directory something other than `proc`, but then inside your `sandstorm-pkgdef.capnp` remap it to proc. Specifically under `sourceMap` > `searchPath` you'll want to add an entry like:

    ( packagePath = "proc", sourcePath = "/fake-proc" ),

Then create your fake proc under `/fake-proc`.

**Comment by pgrm** [comment]
thx, that worked - now I have more dnx errors. I'll try to get the new dotnet cli running, as dnx will be deprecated in few weeks latest.

**Comment by pgrm** [comment]
Oh actually - one more thing - currently I need to modify the `sandstorm-pkgdef.capnp` file by hand. Is there any way I can define a template or specify inside vagrant-spk that I'd like to have that entry there?

**Comment by paulproteus** [comment]
_Oh_ @pgrm , you need this for all packages you create with that stack. Fascinating.

There isn't a way to do that yet. We'll have to add support for that into `vagrant-spk`. https://github.com/sandstorm-io/vagrant-spk/issues/144 tracks that.

Given that, I'm going to close this issue in favor of that issue, if that is OK!

**Comment by pgrm** [comment]
I've created a follow up issue https://github.com/dotnet/cli/issues/4111 since dotnet core has been released already but it still doesn't really want to work. Maybe some of you guys can provide there some insights into sandstorm if needed? thx
