### ISSUE TITLE
admin/users page should have a column for intrinsicName

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#1586]
... it could probably even replace the "handle" column.

This would help, for example, if an admin sees a bunch of new accounts and want to figure who they belong to.

**Comment by neynah** [comment]
Update: As a part of our new Admin redesign we're planning to have multiple identities grouped & visible together. Admin's will be able to manage multiple accounts together. (Design is pretty rough & not finalized yet)

![useraccounts3](https://cloud.githubusercontent.com/assets/855341/14055705/2e3f0c7e-f2a1-11e5-84c1-46a79f9028b1.png)
![useraccounts3 5](https://cloud.githubusercontent.com/assets/855341/14055825/4791c436-f2a2-11e5-9af4-f68d316fdebe.png)

**Comment by dwrensha** [comment]
The new admin design has shipped, and it solves this problem!
