### ISSUE TITLE
sandstorm-146 bug: API key says host is "undefined"

### ISSUE THREAD

**Issue by elimisteve** [sandstorm-io/sandstorm#1592]
I ran into this locally when testing my own app, locally after installing an app, and even on Oasis after installing Etherpad.

This appears to be a 146-wide issue independent of where the server is (locally or on Oasis) and independent of the app (which makes sense).

**To recreate**, just go to any grain, click the key icon, give it a name, press Enter, and you'll see `undefined#abc123restofauthtokenapikeyhere...`.

**Comment by zarvox** [comment]
This is actually fixed in git master by https://github.com/sandstorm-io/sandstorm/commit/40fff588d13870d70fb142f91a9e03ebdf92bda2 but we haven't deployed the fix.

**Comment by kentonv** [comment]
FWIW in the meantime you can manually substitute in the API hostname, e.g. https://api.oasis.sandstorm.io . Very few people use this interface so I decided the fix was non-urgent, but it will roll out this weekend.

**Comment by elimisteve** [comment]
Great, thanks guys!

**Comment by zarvox** [comment]
This is fixed and the fix is deployed now, so I'm going to go ahead and close the issue. :)
