### ISSUE TITLE
issue importing `/sandstorm/package.capnp` - not on default search path

### ISSUE THREAD

**Issue by timbertson** [sandstorm-io/sandstorm#1611]
I've built (some of) sandstorm locally, and am trying to package an app using the `spk` binary. Note that I *haven't* run `make install`, because I can't quite get that far. When I try to use the `spk` binary from my workspace, I get:

```
$ /home/tim/dev/scratch/sandstorm/sandstorm/bin/spk pack passe.spk 
*** Uncaught exception ***
sandstorm-pkgdef.capnp:2: failed: Import failed: /sandstorm/package.capnp
```

I can get it to work using:

```
/home/tim/dev/scratch/sandstorm/sandstorm/bin/spk -I /home/tim/dev/scratch/sandstorm/sandstorm/src/ pack passe.spk
```

..so it's just a matter of wrapping up (or configuring) `spk` so that it knows to include this as a default search path. I've had a look at obvious ways of doing this, but had no luck:

 - there doesn't seem to be a `configure` phase to sandstorm, so it doesn't seem like `spk` can hard-code its own installation prefix as a default search path
 - I couldn't find any environment variables (e.g. $CAPNP_SEARCH_PATH) which would allow me to add this in a wrapper script
 - I noticed when running under `strace` that `spk` does know where it lives:
```
readlink("/proc/self/exe", "/home/tim/dev/scratch/sandstorm/"..., 4097) = 49
```

... but it doesn't seem to be using that to form a default search path, since it still only tries to load package.capnp from `/usr/local/include/sandstorm` and `/usr/include/sandstorm/` after that.

It's possibly the case that a fully built and installed version of sandstorm would fix this issue, but I'm interesting in packaging just `spk` for `nixpkgs`, which requires me to understand the problem and its fix anyway. (I don't think it's worth trying to package _all_ of sandstorm just yet but I'm hoping that having `spk` available will mean I can at least build my app for sandstorm as part of my existing `nix`-based build system)

---

If you're curious why I couldn't build a full sandstorm locally, I got stuck on the meteor / npm deps:

```
( ... )
==== meteor frontend ====
sandstorm-db: updating npm dependencies -- content-type...                         
bignum: updating npm dependencies -- bignum...
connect: updating npm dependencies -- connect...
meteor-node-forge: updating npm dependencies -- node-forge...
npm-request: updating npm dependencies -- request...
sandstorm-email: updating npm dependencies -- mailcomposer, simplesmtp, stream-buffers...
simplesmtp: updating npm dependencies -- simplesmtp, mailparser, mimelib, mailcomposer...
=> Errors while initializing project:         
                                              
While building package bignum:
error: couldn't install npm packages from npm-shrinkwrap: Command failed: npm WARN package.json packages-for-meteor-bignum@0.0.0 No description
npm WARN package.json packages-for-meteor-bignum@0.0.0 No repository field.
npm WARN package.json packages-for-meteor-bignum@0.0.0 No README data
clang-3.7: error: unknown argument: '-fno-tree-sink'
clang-3.7: warning: optimization flag '-fno-tree-vrp' is not supported
make[1]: *** [Release/obj.target/bignum/bignum.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/home/tim/.meteor/packages/meteor-tool/.1.1.10.110di49++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.3.5-300.fc23.x86_64
gyp ERR! command "node" "/home/tim/.meteor/packages/meteor-tool/.1.1.10.110di49++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"configure" "build"
gyp ERR! cwd /home/tim/dev/scratch/sandstorm/sandstorm/shell/packages/bignum/.npm/package-new-1n2wj2x/node_modules/bignum
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! bignum@0.9.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.9.0 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.3.5-300.fc23.x86_64
npm ERR! command "/home/tim/.meteor/packages/meteor-tool/.1.1.10.110di49++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/tim/.meteor/packages/meteor-tool/.1.1.10.110di49++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
npm ERR! cwd /home/tim/dev/scratch/sandstorm/sandstorm/shell/packages/bignum/.npm/package-new-1n2wj2x
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
npm WARN package.json packages-for-meteor-bignum@0.0.0 No description
npm WARN package.json packages-for-meteor-bignum@0.0.0 No repository field.
npm WARN package.json packages-for-meteor-bignum@0.0.0 No README data
clang-3.7: error: unknown argument: '-fno-tree-sink'
clang-3.7: warning: optimization flag '-fno-tree-vrp' is not supported
make[1]: *** [Release/obj.target/bignum/bignum.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/home/tim/.meteor/packages/meteor-tool/.1.1.10.110di49++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.3.5-300.fc23.x86_64
gyp ERR! command "node" "/home/tim/.meteor/packages/meteor-tool/.1.1.10.110di49++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"configure" "build"
gyp ERR! cwd /home/tim/dev/scratch/sandstorm/sandstorm/shell/packages/bignum/.npm/package-new-1n2wj2x/node_modules/bignum
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! bignum@0.9.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.9.0 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.3.5-300.fc23.x86_64
npm ERR! command "/home/tim/.meteor/packages/meteor-tool/.1.1.10.110di49++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/tim/.meteor/packages/meteor-tool/.1.1.10.110di49++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
npm ERR! cwd /home/tim/dev/scratch/sandstorm/sandstorm/shell/packages/bignum/.npm/package-new-1n2wj2x
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0


Makefile:332: recipe for target 'shell-build' failed
make: *** [shell-build] Error 1
```

I don't care too much about this (I suspect it's a distro thing, I'm on fedora 23), but include it in case you're interested. For _running_ my app I'm happy to just use vagrant or a real server somewhere, I just don't want to have to bring in such a huge dependency in order to _build_ an app package.

**Comment by kentonv** [comment]
Hi @timbertson,

When properly installed, `spk` knows how to find the `.capnp` files at their install location, but if it detects it is not in the usual final install location, this logic is skipped. It does try /usr/include and /usr/local/include as fallbacks. The code is not designed to support an arbitrary prefix since as you know Sandstorm isn't normally installed into the traditional FHS tree. I would be willing to accept a PR fixing this if it doesn't break the way we do things currently. The code to edit is around line 286.

However, I think you may encounter another problem. The `spk dev` step builds a list of all of your app's dependencies, including libraries installed on the system, and the `spk pack` step then packs those files into an output package. If you do development inside a Vagrant box, you probably need to run `spk pack` inside the same Vagrant box. (Though, if your app is a statically-linked binary, or built using meteor-spk which has its own dependency bundle, you may be able to avoid this... maybe.)

**Comment by zarvox** [comment]
#1055 mentions a workaround for the node-gyp issue - try setting CC/CXX to gcc/g++ during the npm step?

**Comment by timbertson** [comment]
Thanks @kentonv, good to know I wasn't just overlooking the mechanism. I've now had a look at the code, and I'm a little confused at how `installHome` is set currently - it looks like we're expecting to always be run as `sandstorm` in spk-main.cc, which is surprising because I've seen instructions telling me to run `spk` - is that actually a wrapper around the `sandstorm` binary rather than the `spk` binary which gets built into `bin/` in a dev workspace?

But whatever the details of how `sandstorm` and `spk` binaries are built, I believe my PR (#1612) should be unobtrusive - it simply sets `installHome` appropriately if we're being run _either_ as `$PREFIX/sandstorm` or `$PREFIX/bin/spk`. This means I need to copy / link the relevant files from $SRC/src/sandstorm into $PREFIX/usr/include/sandstorm as part of installation, but that's reasonable.

As for the files that go into a package, I have run one of the demo apps and saw how sandstorm-files.list gets populated (quite clever!). In my case I'm packaging [passe](https://github.com/timbertson/passe), which is very simple - one mostly-static ocaml executable plus a handful of resources - since I'm also the author I can fairly easily generate this, I expect the only akward part will be parsing `ldd` output.

(And thanks @zarvox - if this is a known issue then that's fine, I was just mentioning it in case it was the first time it's come up)

**Comment by kentonv** [comment]
Sandstorm ships a single statically-linked executable that covers all the tools, so `spk` ends up being a symlink to the executable `sandstorm`, hence the logic. Note that symlinks are expanded before inspecting the suffix, so in your case you will need `$PREFIX/bin/spk` to be the actual file, not a symlink.

Hey, Passé looks neat. I actually have a home-grown tool I use that works similarly, but is written as a shell script which is pretty inconvenient when I'm e.g. on a phone, so I might have to consider switching.

**Comment by timbertson** [comment]
Thanks for explaining, that all makes sense :)

I've been using Passé for more than a year now I think, it's been pretty solid so far - hopefully it'll be on sandstorm soon, which seems like a nice fit for such a personal app!

**Comment by paulproteus** [comment]
Yes! FWIW, I want to say I find the name Passé very hard to Google for,
even the search [Passé app] doesn't seem to find this app. It seems super
cool, though, and I do look forward to trying it on Sandstorm!
