### ISSUE TITLE
You can appear to be using a grain anonymously, even if it doesn't allow anonymous access, if you sign out in another tab

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/sandstorm#1625]
Steps to repro: go to https://r.wholezero.org (signed in). Stop streaming. Open a new tab or window. Go to https://mrdomino.sandcats.io. Sign out. Expected: you get signed out and the radio tab goes to "request access", or you stay signed in on that tab because it didn't propagate or something. Actual: you're now not signed in in the sandstorm UI, but the stream is going?!

**Comment by dwrensha** [comment]
Good catch. We need to close those grain views. Note that the same thing can happen in a single tab if you do `Meteor.logout()`.

**Comment by kentonv** [comment]
We also have to kill any open websockets. Probably this is all best-solved by implementing MembraneRequirements.
