### ISSUE TITLE
gogs git clone crashing, due to a Sandstorm error

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1634]
When I do a git clone of a gogs repository on my self-hosted Sandstorm at rose.sandcats.io, I get:

```
Cloning into 'password-store'...
remote: Error: ReferenceError: _this is not defined
remote: C++ location:(javascript):??
remote: type: failed
```

**Comment by paulproteus** [comment]
...never mind, the problem goes away when I do:

```
sudo sandstorm update
```

So I'll close this.

**Comment by kentonv** [comment]
Probably this: https://github.com/sandstorm-io/sandstorm/commit/dcbbe19e44c13db0c2dbba685871c37b293d090b

**Comment by paulproteus** [comment]
So it would seem. In hindsight: I had my server set to `UPDATE_CHANNEL=dev` but hadn't restarted the server, so the auto-updater wasn't running. So anyway, 'sudo sandstorm update' triggered a restart of Sandstorm as well as the auto-updater.
