### ISSUE TITLE
Connect app to outside Sandstorm API

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#1648]
Hi guys,

I'm working on an app which should connect to an API outside sandstorm in the internet.

I've read about `HackSessionContext`and tried to find some information and examples but didn't manage to get closer to the solution. Is there any example or can you give me some advice? I'm working with PHP for this very small app I'm building.

Thanks!
JJ

**Comment by paulproteus** [comment]
Hi @JamborJan!

I can just give a short answer for now, because I'm in between a few other tasks at the moment:

See https://github.com/jparyani/Tiny-Tiny-RSS and look at https://github.com/jparyani/Tiny-Tiny-RSS/blob/sandstorm/.sandstorm/build.sh for `sandstorm-httpGet`

I can say more later! Let me know if that's a good starting-point.

**Comment by JamborJan** [comment]
Hi @paulproteus that helped a bit as I'm now able to use ```sandstorm-httpGet``` when logged into the vagrant box while ```vagrant-spk dev```is running. But I get an error here:

```bash
vagrant@localhost:~$ sandstorm-httpGet
sandstorm-httpGet: missing argument <url>
Try 'sandstorm-httpGet --help' for more information.
vagrant@localhost:~$ sandstorm-httpGet https://jambor.pro
*** Uncaught exception ***
kj/async-io.c++:436: failed: connect(): No such file or directory; toString() = unix:/tmp/sandstorm-api
stack: 0x423380 0x41f010 0x422650 0x4163c0 0x415780 0x417900 0x402730 0x40303c 0x402953 0x4027cd 0x4ae601
vagrant@localhost:~$ 
```

Thanks!

**Comment by paulproteus** [comment]
sandstorm-httpGet only works from within a grain sandbox, since it assumes
/tmp/sandstorm-api routes to the context of an active grain.

So if you can do something like the "nsenter" thing, then you'll get better
results!

**Comment by JamborJan** [comment]
Sorry for the delay. Obviously I have to enter the grain. So I did ```vagrant-spk devjoin``` when exact one grain was open while running ```vagrant-spk dev```.

As I don't want to start too complicated I simply wanted to get the sandstorm website. I understood that ```sandstorm-httpGet```can basically be used like ```curl``` here and would display the websites source code. right? 

Anyway, what I get is this:

```
# sandstorm-httpGet https://sandstorm.io
*** Uncaught exception ***
(remote):0: failed: remote exception: This vat only supports a bootstrap interface, not the old Cap'n-Proto-0.4-style named exports.
stack: 0x437320 0x419270 0x417900 0x402730 0x40303c 0x402953 0x4027cd 0x4ae601
```

Any ideas what happened here or what the right way to do this is?

**Comment by jparyani** [comment]
Unfortunately, `sandstorm-httpGet` is very out of date, and is written against a much older version of Sandstorm. It still works with old sandstorm-http-bridge's, but it won't work out of the box today. You would be better off using https://github.com/dwrensha/wordpress-sandstorm/blob/master/sandstorm/getPublicId.c%2B%2B and changing it to call the http get method instead of getPublicId.

**Comment by JamborJan** [comment]
Thanks for the reply @jparyani. I guess thats like twice the complexity my current development skills allow me to handle. I'm more the "No matter which language, put things together and make it" work type of coder - and not a real developer :-)

I will try to have a look at it but I'm not sure how fast I have results.

**Comment by paulproteus** [comment]
Hi all,

I'll see if I can whip up a code sample for this in the next 1-2 weeks.

**Comment by JamborJan** [comment]
Hi @paulproteus, 

did you have any chance to llok into this? I'm now building also a sandstorm app based on meteor and I would really like to include the http bridge to connect to the outside world.

Thx.

**Comment by paulproteus** [comment]
Hi @JamborJan !

I haven't been able to package this up yet, I'm afraid! I just wanted to leave an update saying that, so your question doesn't go unanswered.

**Comment by JamborJan** [comment]
Maybe someone can add some links to code snippets from other projects using the http bridge where I can check how it is done and learn from.

**Comment by zenhack** [comment]
Is there anything actionable to do for this issue? Or should we just close this?

**Comment by ocdtrekkie** [comment]
I think we should close this because we don't want to provide documentation on using HackSession.
