### ISSUE TITLE
Page title doesn't identify grain

### ISSUE THREAD

**Issue by coyotebush** [sandstorm-io/sandstorm#165]
Grain URLs can be bookmarked, shared, and so on, which is great. But in a list of open tabs/bookmarks/history, the titles are all just `Sandstorm`, and it's hard to find a particular grain without going via the home page. How about including the grain title to get something like `Untitled Todo List - Sandstorm`?

**Comment by gemlog** [comment]
This might be combined with bug #15 for always using the same named string var for the grain in scope, which you prolly already do anyhow. It would kill both these minor bothers.
