### ISSUE TITLE
SMTP relay with mailgun

### ISSUE THREAD

**Issue by max133** [sandstorm-io/sandstorm#1656]
Hi

i read in a post from kentonv that is possible to use mailgun for smtp relay https://github.com/sandstorm-io/sandstorm/issues/531#issuecomment-114279629

I tried that and used this smtp url: `smtp://postmaster:8casdfDefaultPasswordblablabla51@sandboxd3700xxxxxxxxxxxxxxxxxxxef0cd.mailgun.org`

In the logs i got this Exception: 
> Exception while invoking method 'testSend' AuthError: Invalid login - 535 5.7.0 Mailgun is not loving your login or password

I got this data from mailgun:
```
SMTP Hostname: smtp.mailgun.org
Default SMTP Login: postmaster@sandboxd370blablabla68ef0cd.mailgun.org
Default Password: 8c61blablablablabla51  Manage SMTP credentials
API Base URL: https://api.mailgun.net/v3/sandboxd370blablablablabla8ef0cd.mailgun.org
API Key: key-3ab0blablablabla76
```

I think my smtp url is wrong, but what should i use instead?

**Comment by dwrensha** [comment]
The username in the URL should be `postmaster%40sandboxd370blablabla68ef0cd.mailgun.org`. Note that it's essential to percent-encode `@` as `%40`. The full SMTP URL should be:

```
smtp://postmaster%40sandboxd370blablabla68ef0cd.mailgun.org:8c61blablablablabla51@smtp.mailgun.org
```

**Comment by max133** [comment]
Perfect, 
thank you very much

**Comment by Apidcloud** [comment]
Sorry to revive this issue, but I believe I'm facing the same thing.

Given the same data from mailgun, I have tried the following:
smtp host:smtp.mailgun.org 
Username (optional): postmaster%40sandboxd370blablabla68ef0cd.mailgun.org
Password (optional): xxblablablablablaxx
Sandstorm server's own email address: no-reply@sharelatex.sandcats.io

But the 'test' is showing internal error after 5 or 6 seconds. What am I doing wrong?

Thanks!

**Comment by dwrensha** [comment]
Does it work if you use "postmaster@sandboxd370blablabla68ef0cd.mailgun.org" for the username?
After the changes in https://github.com/sandstorm-io/sandstorm/pull/1761, the percent-encoding is not necessary.

**Comment by Apidcloud** [comment]
Yeah, it works with the '@'. My bad, didn't know it was fixed :+1:
