### ISSUE TITLE
admin settings page: Chrome asks to save my SMTP password

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#1661]
Apparently, Chrome thinks it is seeing a login page.

<img width="371" alt="admin-settings-password" src="https://cloud.githubusercontent.com/assets/495768/13883265/190a76c4-ecff-11e5-8bbb-71c135af6344.png">

**Comment by dwrensha** [comment]
Firefox hits a similar problem, when I click the "Test" button in the SMTP config section.

**Comment by zarvox** [comment]
Ahhh, it sees an `<input type="password">` and assumes it's being helpful.
