### ISSUE TITLE
Highlight "share access" as a part of guided tour

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1671]
Through user testing it appears that figuring out how to "share" a grain with someone else is difficult to figure out the first time as most users poke around in the app's UI before looking in the navigation bar. The results vary but some apps such as Rocket.chat have a lot of invite & member type of functions that consistently confuse users.

So far I've seen positive results as a result of our added tour guide- specifically highlighting how to add new grains. I propose we do the same with "Share Access" to onboard users quicker. As a result of this proposed change, I suspect that users will be able to figure out how to "Share Access" more quickly(and also realize this is an action that exists!).

I threw together this UI. I think we should obviously use similar styling as seen in https://github.com/sandstorm-io/sandstorm/pull/1344. (I'm not attached to the copy)

For clarification, after the user clicks "got it" on the grain creation step, next they'll see the "share access" action highlighted.

I don't think we want to add too many things to the tour guide for onboarding but I'm convinced that this is an important thing to add.

![highlight-shareaccess](https://cloud.githubusercontent.com/assets/855341/13895490/f685557e-ed30-11e5-958a-1388676a071c.png)

**Comment by paulproteus** [comment]
+1, thank you for filing this with such clear text!

**Comment by paulproteus** [comment]
This is now live, so I'm marking this as closed. Thanks @neynah for filing!
