### ISSUE TITLE
App Market list loses scroll position

### ISSUE THREAD

**Issue by kpreid** [sandstorm-io/sandstorm#1678]
1. Go to https://apps.sandstorm.io/
2. Scroll down.
3. Click on an app to get the details.
4. Go back.
5. The scroll position is lost.

This is especially annoying on small (phone) screens.

(Please consider having the server actually deliver the list in HTML. Then the layout will be prompt so this won't happen, and it's friendlier to machine readers anyway.)

**Comment by neynah** [comment]
Let's close this since I moved the issue to the appropriate App Market repo.
