### ISSUE TITLE
Share-by-identity sends emails that result in Sandstorm seeming to hang before ever loading the grain

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1690]
Steps to reproduce:

- Alice shares a grain (by identity) with Bob

- Bob visits their email

- Bob clicks the link

Expected behavior:

- Bob sees the grain

Actual behavior:

- Bob sees the Sandstorm UI but the grain never seems to start loading, let alone finish loading

Current diagnosis:

- Data availability race w/ Iron Router??

Note: We've seen this happen at least once. I don't know yet if it's reliable.

**Comment by paulproteus** [comment]
Last I heard @zarvox was working on this, so assigning to him for now. I hope that's OK!

**Comment by paulproteus** [comment]
FWIW, one thing that occurs to me is that this is a showstopper-level bug that, when I worked at Eventbrite, would merit a code push the same day. This is not to say we will/won't be able to do that at Sandstorm, but maybe it suggests that we should have a label and/or a process that describes these kinds of urgent & important bugs.

**Comment by kentonv** [comment]
Release pushed. Oasis hotfixed.
