### ISSUE TITLE
Opening revoked sharing link leads to broken "request access" flow

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1693]
1. Create a sharing link.
2. Revoke it.
3. Open it with another account (logged in).
4. Request access, and leave the window open.
5. From the first account, grant access.
6. The requesting account is now in a weird refresh loop.

I'm not sure if visiting a revoked sharing link should show the "request access" flow. I can see arguments either way. It probably shouldn't go into a refresh loop, though. :)

**Comment by dwrensha** [comment]
The title of this issue mentions "revoked" but the repro steps don't do any revoking. Did you leave out a step?

**Comment by kentonv** [comment]
@dwrensha Indeed! Fixed.
