### ISSUE TITLE
Broken sample apache reverse proxy config

### ISSUE THREAD

**Issue by jvasile** [sandstorm-io/sandstorm#1698]
In sandstorm/docs/administering/sample-config/apache-virtualhost.conf:

You suggest a ServerName line that includes the domain of the sandstorm install plus a wildcard for subdomains:

     ServerName example.com *.example.com

This causes Apache to fail to start:

     # service apache2 restart
    Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
    # systemctl status apache2.service
    ● apache2.service - LSB: Apache2 web server
       Loaded: loaded (/etc/init.d/apache2)
       Active: failed (Result: exit-code) since Thu 2016-03-24 02:50:31 UTC; 8s ago
      Process: 7396 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
      Process: 27930 ExecReload=/etc/init.d/apache2 reload (code=exited, status=0/SUCCESS)
      Process: 7428 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)
    Mar 24 02:50:31 jamesvasile apache2[7428]: Starting web server: apache2 failed!
    Mar 24 02:50:31 jamesvasile apache2[7428]: The apache2 configtest failed. ... (warning).
    Mar 24 02:50:31 jamesvasile apache2[7428]: Output of config test was:
    Mar 24 02:50:31 jamesvasile apache2[7428]: AH00526: Syntax error on line 2 of /etc/apache2/si...om:
    Mar 24 02:50:31 jamesvasile apache2[7428]: ServerName takes one argument, The hostname and po...ver
    Mar 24 02:50:31 jamesvasile apache2[7428]: Action 'configtest' failed.
    Mar 24 02:50:31 jamesvasile apache2[7428]: The Apache error log may have more information.
    Mar 24 02:50:31 jamesvasile systemd[1]: apache2.service: control process exited, code=exited ...s=1
    Mar 24 02:50:31 jamesvasile systemd[1]: Failed to start LSB: Apache2 web server.
    Mar 24 02:50:31 jamesvasile systemd[1]: Unit apache2.service entered failed state.

Apache expects ServerName to just be one name, and it can't handle the wildcard there.  Instead, use ServerAlias for the wildcard subdomains:

     ServerName example.com
     ServerAlias *.example.com

All this is on Debian testing and Apache 2.4, btw.

**Comment by paulproteus** [comment]
Thanks! Submitting a pull request to fix this now. That's what I get for pushing sample configuration files I haven't fully verified.
