### ISSUE TITLE
web port stopped responding and sandstorm.log spewing error

### ISSUE THREAD

**Issue by lunixbochs** [sandstorm-io/sandstorm#1707]
URIError: URI malformed
        at decodeURIComponent (native)
        at Url.parse (url.js:185:19)
        at Object.urlParse [as parse] (url.js:101:5)
        at Array.splitSmtpUrl [as 20] (migrations.js:456:24)
        at [object Object].migrateToLatest (migrations.js:561:20)
        at lib/db-deprecated.js:71:35
        at /programs/server/boot.js:249:5
    ** Front-end died immediately after starting.
    ** Sleeping for a bit before trying again...
    Migrations already applied: 20/22
    Applying migration 21

    /programs/server/node_modules/fibers/future.js:245
                                                    throw(ex);
                                                          ^
    URIError: URI malformed
        at decodeURIComponent (native)
        at Url.parse (url.js:185:19)
        at Object.urlParse [as parse] (url.js:101:5)
        at Array.splitSmtpUrl [as 20] (migrations.js:456:24)
        at [object Object].migrateToLatest (migrations.js:561:20)
        at lib/db-deprecated.js:71:35
        at /programs/server/boot.js:249:5
    ** Front-end died immediately after starting.
    ** Sleeping for a bit before trying again...

**Comment by lunixbochs** [comment]
Worked around by clearing my SMTP URL in the meteor db (which was set to `smtp://user@domain:a%=Qym6b@smtp.domain.com:465`)

**Comment by dwrensha** [comment]
Thanks for the report! I submitted #1708 to fix this problem.

Did your outgoing SMTP work in the previous configuration, with the URL `smtp://user@domain:a%=Qym6b@smtp.domain.com:465`?

**Comment by lunixbochs** [comment]
Nope, it never worked, which is probably a different Sandstorm bug.

**Comment by dwrensha** [comment]
The likely reason that it didn't work is that the "@" in the username and the "%" in the password needed to be percent-encoded, as "%40" and "%25", respectively.

**Comment by dwrensha** [comment]
A benefit of the new configuration form is that you don't need to worry about percent-encoding things.
