### ISSUE TITLE
Grain of de-installed app still runs

### ISSUE THREAD

**Issue by mauro3** [sandstorm-io/sandstorm#1724]
I installed Davros and tried it out by creating a grain. I then de-installed Davros.  However the grain still started up.  I would have expected it to not start up and instead tell me to install Davros.

**Comment by ocdtrekkie** [comment]
This is intended functionality. Effectively, the 'installed version' of an app allows you to create grains of that app version. If you still have a grain from that app though, the server will run it.

**Comment by mauro3** [comment]
Hmm, I still find it a bit strange that a de-installed app can still run. So, it must be still installed, right?  Does it get de-installed once I delete all grains?

But feel free to close.

**Comment by ocdtrekkie** [comment]
I think the app's software is removed from the server once no remaining grains for it exist. Bear in mind that while individual users can install/uninstall software, the server keeps the software stored in a common location for all users, so "uninstall" doesn't necessarily remove an app from a server.

**Comment by mauro3** [comment]
Makes sense, thanks! Closing.

**Comment by kentonv** [comment]
Correct, the exact meaning of "install" is kind of weird on Sandstorm. What it really means is "add to your app list", so uninstall means "remove from your app list". The act of downloading the package is separate. The package will automatically be deleted as soon as it is no longer in-use on the server (i.e. all grains deleted and all users have "uninstalled").

Arguably we should use a different word than "install", but there isn't a good word that most people will immediately understand.
