### ISSUE TITLE
Add detail about announcements bonus storage when creating account

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1730]
Suggestion for minor improvement based on feedback from user test:

- When creating an account, the user wasn't sure what would happen if they ended up unsubscribing in the future—specifically if their storage would get taken away or not.

Maybe we can say something like: "Bonus storage is active as long as you're subscribed. You can unsubscribe at any time."

![image](https://cloud.githubusercontent.com/assets/855341/14158264/12dc0dd8-f684-11e5-9053-f5fd3e291620.png)

**Comment by kentonv** [comment]
Maybe. Note, though, that it seems like in this case understanding the details would not have caused the user to choose differently. Presumably, they would only have considered subscribing if it were the case that they could immediately unsubscribe yet keep the storage.

I worry about adding too much fine-print text and possibly overwhelming users.

**Comment by neynah** [comment]
I'm convinced this can be closed for now unless further issues suggest we should provide more information.
