### ISSUE TITLE
Decide: How should LDAP intersect with Sandstorm identity?

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1738]
(See #1737 for context.)

Right now, we use the full `dc` string as a user's Internet-global Sandstorm identity. Implementation link: https://github.com/sandstorm-io/sandstorm/blob/master/shell/packages/accounts-ldap/ldap_server.js#L341

## Is this going to be globally unique?

- Novell eDirectory uses`cn=username,o=orgunit` with no `dc=...` component. Source: "Supposing we wanted to create a tree for a company called Virago, organization name o=Virago, tree name as Virago, with the Distinuguished Name (DN) of the Administrator as cn=ViragoAdmin.o=Virago" [source](http://linux-sxs.org/networking/edir87_linux.html) [other source](https://www.novell.com/documentation//novell-filr1/filr1_hands-on/data/admin_users.html)
- ActiveDirectory uses the fully qualified domain name, expanded into 
- People carelessly following StackOverflow with OpenLDAP might use `dc=nodomain`. [source](http://askubuntu.com/questions/558598/where-is-the-dc-example-dc-com-ldap-dit)

I'm concerned that if we rely on admins configuring the full DN correctly, we might end up with a lot of users with the same identity ID, for example: `cn=john,o=Marketing` (no `dc=`, no `ou=`) or `cn=john,dc=example,dc=com` (people who were careless setting up OpenLDAP). Since LDAP admins didn't necessarily configure their LDAP with any concept of federation in mind, I suspect this is going to be depressingly common.

## Proposal

- For LDAP users, we should hash `("ldap", emailAddress)` so that we are hashing something that people expect to be global.

## Other thoughts

- I'm curious for others' thoughts. I figure we should think hard about this now to avoid sadness later.

CHANGELOG:

- I edited the above to fix the `cn=john,o=Marketing` to fix a typo where, earlier, I had written it as `cn=john,ou=Marketing`.

- I added a link to the user ID definition in the implementation.

**Comment by kentonv** [comment]
If we use email address then people's email addresses can't change.

LDAP's DN is clearly intended to be a global identifier. I believe administrators will _expect_ that Sandstorm treats two different DNs as different users even if they for some reason have the same email address.

If someone has misconfigured their LDAP to be non-global, it won't actually matter to them unless someday they wish to participate in some sort of federation with other LDAP servers, at which point their misconfiguration will be a problem independent of Sandstorm.

I would prefer to stick with DN.

**Comment by paulproteus** [comment]
Okay, but that means:

- Novell eDirectory users are going to have non-global Sandstorm IDs.
- LDAP deployers might not know the Sandstorm-specific implications, if they've failed to configure `dc=...` in a DNS-y way.

If you're OK with the Novell eDirectory situation, I'm OK with that I guess. An alternative is that we can insist on the existence of _some_ `dc=...` component. This is the case I'm actively concerned about.

For the LDAP deployers, I can work on some text to try to help people understand this, and maybe write a self-test that people can dismiss. This case I'm less concerned about, so long as some in-app self-test is OK with you (not necessarily a showstopper for right now).

**Comment by paulproteus** [comment]
> If someone has misconfigured their LDAP to be non-global, it won't actually matter to them unless someday they wish to participate in some sort of federation with other LDAP servers, at which point their misconfiguration will be a problem independent of Sandstorm.

Given that, I'm OK closing this! The status quo works for me.

I'll consider writing a self-test eventually.
