### ISSUE TITLE
Prevent accidental grain deletion

### ISSUE THREAD

**Issue by dlitz** [sandstorm-io/sandstorm#1743]
The ever-present "Delete" trashcan icon in the menubar is scary to me.  I'd like some way to mark important grains as "locked", so that they need to be "unlocked" before they can be deleted.

I can imagine several scenarios where someone might accidentally delete the wrong grain, or delete an entire grain when they mean to delete something else (like a song from a music library).

**Comment by ocdtrekkie** [comment]
It seems logical to me that Delete Grain, Show Debug Log, and Restart Grain probably belong under a menu, since they should all be rarely used.

When you press the trash can though, you do get a pop-up dialog in the center of the window that asks if you really want to delete that grain. Assuming the user is aware of what a grain is, hopefully they know the scope of what they're about to delete.

Multiple users have asked for a "recycle bin" though, which would definitely be a valuable feature.

**Comment by paulproteus** [comment]
I've definitely nearly deleted a grain by accident, and continue to live in
fear. Which is to say I'm +1 on moving these to a menu, or somewhere else
that I'm not going to accidentally ruin my day.

**Comment by zarvox** [comment]
Agreed that the Delete button sitting in the menu is just asking for disaster, and the functionality needs to be relocated.

I think the alternative design I like the best is the "aggregate actions from grain list" option, possibly including the "recycle bin" approach; see https://github.com/sandstorm-io/sandstorm/issues/364

An open question from my point of view is: how should grains in a "recycle bin" behave?  You can't start them, but they are enumerable and can be restored by their owner?  Where in the UI would you expect to find/review them?  For grains that aren't your own - do permissions still flow through a recycle-binned sharing token?

**Comment by ocdtrekkie** [comment]
Yeah #364 has my whole tirade on label/folder support and recycle bin behavior and such as well. :P

I kinda feel like files in your Recycle Bin should not open until you restore them. You wouldn't want someone to accidentally/on purpose end up working out of their Recycle Bin (stranger things have happened), and then their grain gets autodeleted on a cleanup.

Windows won't let you open a file in your Recycle Bin until after you restore it. On the other hand, you can read stuff in your Gmail Trash, and even send replies right out of your trash can, which I've done a couple of times.

**Comment by mitar** [comment]
I completely agree. This should not be in the menu.

Furthermore, when you shared the grain with others, I do not think others should be able to delete it either (it seems they can, at least when I was playing with demo).

Moreover, when you share the grain with others, what if they do not want grain to be deleted? Like, I worked hard to contribute to some text, you decide to scrap it, but I would want to keep it around.

**Comment by kentonv** [comment]
> Furthermore, when you shared the grain with others, I do not think others should be able to delete it either (it seems they can, at least when I was playing with demo).

No, they can't. They can only "forget" it, meaning they'll no longer see it in their own grain list, but the original still exists in the owner's grain list.

**Comment by mitar** [comment]
> No, they can't. They can only "forget" it, meaning they'll no longer see it in their own grain list, but the original still exists in the owner's grain list.

But the icon they have in the toolbar is the same trash icon, no? So it looks like they can delete it.

**Comment by kentonv** [comment]
@mitar Yes, it's the same icon, but it doesn't delete the grain, only forgets it. We should definitely try to make this less confusing, though.

**Comment by paulproteus** [comment]
Hi all here,

In the current proposed design by @neynah and @dwrensha the trash icon will stay where it is, but it will cause a grain to go to the trash, where it is not immediately deleted, but instead deleted after 30 days and can be immediately restored.

I wanted to ask - is that adequate, in your opinion?

Thanks!

**Comment by mitar** [comment]
Hm, I really do not think this is so common operation that it should be shown so visibly. Maybe now during development we create and erase grains often, but we should target normal users, not us developers.

Moreover, this introduces confusion that what if I do want to delete permanently. I press trash. And then I think it is deleted, but it is not. And then admin gets a subpoena and have to give the police the data.

I think the workflow found in GitHub is much better. You have a delete in a special section and it is pretty impossible to delete it by accident. But once you do it, you know it is deleted.

**Comment by ocdtrekkie** [comment]
@mitar I suspect most people would prefer an oops button. The trash icon should tell you it is "sent to Trash". And it's actually much more clear than Windows, which uses an X, tooltip "Delete", but actually sends to the Recycle Bin.

**Comment by mitar** [comment]
> @mitar I suspect most people would prefer an oops button.

How do we know that? User studies?

**Comment by neynah** [comment]
As of #1950 grains now need to be trashed before they are deleted.
