### ISSUE TITLE
Google OAuth setup instructions need update

### ISSUE THREAD

**Issue by jvasile** [sandstorm-io/sandstorm#1756]
The instructions for Google OAuth setup do not match the Google menus and screens, as Google recently changed their interface.

**Comment by kentonv** [comment]
Unfortunately, the text comes from Meteor, which hasn't updated it in almost a year:

https://github.com/meteor/meteor/blob/abd574f38008b45f5e2a6bc322b10bcdde44763a/packages/google/google_configure.html

Meanwhile, Google changes their UI, like, every week.

The good news is that with the upcoming new admin UI we'll more easily be able to take control of this text.

**Comment by ocdtrekkie** [comment]
I like simple ways to help. Don't know if they'll merge that or not. But maybe.

**Comment by ocdtrekkie** [comment]
I guess Meteor is in the process of splitting their accounts packages out of the main repo, so they can pick and choose which PR they want, I offered it to both repos.
