### ISSUE TITLE
Self-Hosted. Cannot build docker container.

### ISSUE THREAD

**Issue by CertainLach** [sandstorm-io/sandstorm#1764]
Hello. I am trying to compile a docker container from Dockerfile located in this repo, bui i am getting this error: Your kernel does not appear to be compiled with support for unprivileged user
namespaces (CONFIG_USER_NS=y), or something else is preventing creation of user
namespaces.
Full log:

```
$ docker build -t classroom_sandstorm .
Sending build context to Docker daemon 17.95 MB
Step 1 : FROM ubuntu:14.04
 ---> a1e4ed2ac65b
Step 2 : RUN apt-get update
 ---> Using cache
 ---> f9af4cba6aa0
Step 3 : RUN apt-get install -y curl xz-utils
 ---> Using cache
 ---> 235fe075d27a
Step 4 : RUN adduser --disabled-password --gecos "" sandstorm
 ---> Using cache
 ---> 888567ee960c
Step 5 : USER sandstorm
 ---> Using cache
 ---> ba50c10dd9f2
Step 6 : ENV HOME /home/sandstorm
 ---> Using cache
 ---> e233da92b90a
Step 7 : ENV USER sandstorm
 ---> Using cache
 ---> fb8725cdc528
Step 8 : ADD ./install.sh /install.sh
 ---> Using cache
 ---> 2e65246d21cd
Step 9 : RUN /install.sh -d -u
 ---> Running in df54687744e5
*** INSTALLATION FAILED ***
Your kernel does not appear to be compiled with support for unprivileged user
namespaces (CONFIG_USER_NS=y), or something else is preventing creation of user
namespaces. This feature is critical for sandboxing. Arch Linux is known to
ship with a kernel that disables this feature; if you are using Arch, you will
unfortunately need to compile your own kernel (see
https://bugs.archlinux.org/task/36969). If you are not using Arch, and don't
know why your system wouldn't have user namespaces, please file a bug against
Sandstorm so we can figure out what happened.

You can report bugs at: http://github.com/sandstorm-io/sandstorm

The command '/bin/sh -c /install.sh -d -u' returned a non-zero code: 1
```

**Comment by paulproteus** [comment]
Hi! Sandstorm self-containerizes, so you're going to have an easier time
not using Docker. See our install docs here:
https://docs.sandstorm.io/en/latest/install/

If using Docker is essential, we can leave this open until we can provide a
high-quality Dockerfile. But that will take a little while. This Dockerfile
is only intended for use by our automated tests.

Let me know what you think.

**Comment by Creeplays** [comment]
Thank you for answer) Yes, docker is essential for me, i will wait or try to compile kernel with namespaces support.

**Comment by paulproteus** [comment]
For what it's worth, if your kernel does not support unprivileged user
namespaces, then you won't be able to run Sandstorm. So this feature in
your kernel is in fact critical.

If you're on Debian/Ubuntu, and/or you have
a /proc/sys/kernel/unprivileged_userns_clone file, you can enable/disable
the feature at runtime. You can read more about that here:
https://github.com/sandstorm-io/sandstorm/blob/master/install.sh#L460

So Docker or no Docker, you do need that kernel feature!

**Comment by ocdtrekkie** [comment]
I believe this topic is fully resolved.
