### ISSUE TITLE
Better pre-setup message

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1775]
Currently if you visit a server that hasn't been configured yet -- and you don't go to the /setup route -- you see this:

![screenshot from 2016-04-05 21-41-31](https://cloud.githubusercontent.com/assets/4001805/14305994/472f0c96-fb77-11e5-906e-5c10c4d57372.png)

We should do better! :)

**Comment by zarvox** [comment]
All the "main" routes should probably redirect to `/setup` unless `hasUsers` is true or `devAccounts` are enabled.

Then, `/setup` redirects to the nice `/setup/expired` page if you got there without a valid setup session:

![pixels1](https://cloud.githubusercontent.com/assets/307325/14306135/e235d21e-fb78-11e5-910d-f28d056038e6.png)

**Comment by kentonv** [comment]
@zarvox Well... apparently it didn't work, since the above screenshot is from a server that has the setup wizard and has dev accounts disabled. :/

**Comment by kentonv** [comment]
(whoops, misread your post as present tense rather than "should" -- bogus reply deleted)
