### ISSUE TITLE
Conceptual question: network access management and non source access for apps

### ISSUE THREAD

**Issue by adityamenon** [sandstorm-io/sandstorm#1780]
Hello there,

I have a question (idea?) for the team - related to commercial services "apps" being run people by on their own Sandstorm servers. Sorry if this is the wrong place!

Let's say Facebook wants to provide "Facebook for Work" on Sandstorm. I see two main concerns from the parties involved:

1. Facebook's concern: We don't want our source code to be leaked out to folks running the servers. Our code is proprietary. Reverse engineering risks notwithstanding, we are at best willing to run binary blobs on your servers.
2. User's follow-up concern: We have no idea those binaries are doing. We don't want them transmitting data over to the motherships of those binary owners. We want to own our data.

Is (1) possible? If yes, (2) is a problem. Since Sandstorm already controls access to whether a piece of data ("grain") is accessible by an app at all, would it be possible to configure how much network access an app itself has? Would it be possible to lock down "Facebook for Work"'s communications into the local Sandstorm cluster and never outside the firewall ("analytics" be damned)?

I really like the idea behind Sandstorm, it's super cool & it gels toward the way I want the internet to progress. I had a similar/parallel idea but it's wonderful to see an entire team with the actual chops to pull it off top-to-bottom, doing it ;)

**Comment by ocdtrekkie** [comment]
@adityamenon Nothing prevents Sandstorm from running closed source apps. Sandstorm actually has a _fantastic_ closed source app called **draw.io**

The goal is for apps to be completely unable to talk to the outside world without the user's permission. Right now there are some workarounds while the Powerbox is finished, but you have to implement a specific API to have a Sandstorm app talk to an outside server. The other exception to this right now is client-side JavaScript, but the Sandstorm team intends to close this off as well in the future.

So someday it should be pretty safe to put your sensitive data in a grain of a closed source/proprietary app, and still be 100% sure your data isn't leaving your server.

**Comment by adityamenon** [comment]
Thanks! My query is resolved. Closing :+1:
