### ISSUE TITLE
Offer templates copy with leading and trailing spaces on Android/Firefox

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#1795]
So, I was setting up ownCloud/Davros, and I kept getting wrong password errors, and was very confused. This was fast enough the template was not expiring. I figured out there were a few spaces before and after everything I copied from offer templates via the clipboard button. Leading spaces accidentally in the URL field weren't a problem, but leading spaces I failed to remove at the beginning of the password were.

**Comment by kentonv** [comment]
Hmm, is this a bug in Sandstorm or a bug in Davros? @mnutt?

**Comment by ocdtrekkie** [comment]
I thought Sandstorm itself handled the generation of the keys and the copy to clipboard option and such, which is why I filed it here.

**Comment by mnutt** [comment]
I don't believe the offer template I'm requesting has any leading or trailing spaces (https://github.com/mnutt/davros/blob/master/app/templates/clients.hbs#L24) so it's likely the code I wrote in Sandstorm to copy-to-clipboard. It's probably not relevant, but can you tell me what browser you're using? Android/Chrome?

**Comment by ocdtrekkie** [comment]
Android/Firefox (in the issue title)

Specifically, Android 4.4/Firefox... 44. Lotta 4s.

**Comment by kentonv** [comment]
I'm unable to reproduce this in Android/Chrome nor Linux/Chrome, FWIW.

But probably throwing a `.trim()` into the code somewhere wouldn't hurt?

**Comment by zarvox** [comment]
Reproduces in Linux/Firefox 45.0.1.  Possibly a `clipboard.js` edge case?

**Comment by zarvox** [comment]
Specifically, I get two extra newlines on the clipboard before the contents of the `<pre>` and two extra newlines after the contents of the `<pre>`, despite them not appearing in the DOM as far as I can tell.

**Comment by ocdtrekkie** [comment]
\o/ @zarvox 

I always love when someone determines that I am not crazy.

**Comment by kentonv** [comment]
Hmm, seems like the bug is in clipboard.js?

**Comment by zarvox** [comment]
Actually it turns out to be a Firefox selection edge case.  Patch inbound.

**Comment by zarvox** [comment]
Wow that was a fast merge.
