### ISSUE TITLE
Installer claims URL expires in 15 minutes even when it's not an admin token

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1803]
When install with dev accounts enabled, the installer no longer creates an admin token. Instead it shows the server's root URL at the end. However, it still claims this URL expires after 15 minutes.

**Comment by paulproteus** [comment]
+1, will fix shortly.

**Comment by kentonv** [comment]
Not urgent FWIW. (I'm not going to push another release for a week unless there is something broken.)

**Comment by paulproteus** [comment]
I'll get to this shortly, i.e. within the next 1-2 weeks.
