### ISSUE TITLE
UI: "Can What?" Permissions dialog isn't big enough to read it.

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#1816]
Oasis, using Firefox on Windows. The options are "Can Edit" and "Can View", but you definitely can't tell which this link is from this display.

![canwhat](https://cloud.githubusercontent.com/assets/4399499/14449969/0451be6a-003f-11e6-8240-7f35aa09db60.png)

**Comment by neynah** [comment]
Same issue as https://github.com/sandstorm-io/sandstorm/issues/877. We should fix it!

**Comment by ocdtrekkie** [comment]
Oops! I am sorry, I didn't know it was duplicate.
