### ISSUE TITLE
Admin Panel Redesign: Identity Providers

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1820]
Changes required to ship:
- [x] add a string about organization management below the table
- [x] link organization management button to "For Work" tab
- [x] display "Not enabled" tags for LDAP & SAML
- [x] For non-SFW: change "To enable LDAP..." -> "Configure Sandstorm for Work..." and make it a button right-aligned
- [x] disable save button until changes are made
- [x] configuration modals(per identity): rearrange checkbox to be towarads the bottom

Current mock-ups:
![identityproviders1](https://cloud.githubusercontent.com/assets/855341/14478823/f68cee1e-00cd-11e6-91f9-d1ad773cd165.png)

![githubconfig1](https://cloud.githubusercontent.com/assets/855341/14478918/a4c87f5c-00ce-11e6-9b06-a504d80bb729.png)

**Comment by kentonv** [comment]
I do not believe that putting the checkbox at the bottom will fix any confusion. It's bad UX to make people notice and click on an extra small box when 99.99% of people who click the "save" button obviously want to enable the service, with the failure mode being "it doesn't work for no apparent reason". Please find a better solution here.

Possibilities:
1. Make primary button "Save and Enable" but have a separate "Save but leave disabled" button.
2. Don't toggle "enabled" inside this form at all. Instead, let people manipulate the "enabled" / "not enabled" indicator in the provider table. (I'm not sure what this would look like.)

**Comment by neynah** [comment]
Interesting. I agree that most people will want it enabled so I like possibility 1. For possibility 2 we can show the status in the table (as the mock-up currently does) and just have a button beside it that says "Enable" if the status is "Disabled and "Disable" if the status is "Enabled".

**Comment by kentonv** [comment]
I prefer 1 as well. For the common case, it avoids making the user think about an extra thing and click an extra button. I suspect most users will expect that when they click "save", the service is now enabled.

In fact, I'd like to modify my suggestion. I don't think anyone ever wants to "save but leave disabled". Therefore, I don't think we need that button. Instead, let's just have the "save" button also enable the configuration. I don't think it even needs to be "save and enable" because everyone will assume that "save" also enables.

If the service is already enabled, then we add a third button: "disable". This button would be red.

**Comment by zarvox** [comment]
This seems pretty good.  I'd add a slight refinement: making the "Save" button contain the verb "Enable" in the popup if the login service is not yet enabled, and "Save" or "Update" if it is currently enabled.

To summarize: popups should have the following buttons:

* (if service currently disabled) "Enable" or (if service currently enabled) "Save".  Default action.  Disabled unless the form has valid content (e.g. for Google OAuth, Client ID + Secret must be nonempty).
* "Cancel".  Dismisses the dialog without changing any durable state at all.  Equivalent to clicking the X at the top right of the modal, or outside of the modal.
* (if service currently enabled) "Disable", in danger colors.

Note that in this setup, the passwordless email login modal has no content.  We might consider writing a line or two that explains passwordless email login to show in the modal, or that to use email login you'll need to also configure an email relay.  While it's tempting to think we could remove the modal entirely for email, I believe it's better to keep the modal for all the login providers for consistency in the forms and workflows (one place to show success/failure messages, same button text for equivalent-state providers on the login provider list, a clear place to add copy if needed, etc.).
