### ISSUE TITLE
Admin Panel Redesign: Network Capabilities

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1823]
Changes required to ship:
- [ ] link grain title to grain
- [ ] add checkbox filters to show "active" and "revoked", uncheck "revoked" but default
- [ ] add confirmation for revoking, something like: "Are you sure, this will break this app..."
- [ ] for the user, display "Temporarily unavailable, try again later" if capability has been revoked"

Out of scope:
- [ ] where in cap'n p does "grain title" get saved
- [ ] Admin may have access to any key
- [ ] pagination so the tables don't extend forever
- [ ] Users will need a place to revoke capabilities

Current mock-up:
![networkcapabilities3](https://cloud.githubusercontent.com/assets/855341/14690995/bcff8724-0703-11e6-8160-6aed60a336a4.png)
([Previous mock-up can be viewed here.](https://cloud.githubusercontent.com/assets/855341/14691046/fe3a7d02-0703-11e6-89a6-cebb305ea0cb.png))

**Comment by kentonv** [comment]
Since these capabilities are granted primarily to grains, not people -- and will usually be granted to grains owned by the admin -- it seems like the grain title should be emphasized in the "granted to" column, maybe with "owned by X" shown only if it doesn't match the "Granted by" column.

**Comment by neynah** [comment]
@kentonv That seems better. I updated the mock-up above to reflect your suggestions.

@zarvox Active capabilities have a "Revoked" button; perhaps revoked capabilities will just be labeled as "Revoked". Can the admin take any action(s) on revoked capabilities in this first version?
