### ISSUE TITLE
Admin Panel Redesign: For Work

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1827]
Changes required to ship: 
- [ ] Change "Feature key" -> "For Work"
- [ ] update to match wizard / admin onboarding UI
- [ ] update SFW string to list more things

Current mock-up:
![featurekey1 1](https://cloud.githubusercontent.com/assets/855341/14904722/18c8bbdc-0d5f-11e6-89d5-65db01ee0ea6.png)

[Previous mock-up](https://cloud.githubusercontent.com/assets/855341/14479486/f98912ea-00d3-11e6-9071-e00c08d3bf61.png)

**Comment by kentonv** [comment]
I feel like this page could use more work. The "request feature key" button feels haphazardly-placed and easy to miss. I think we need to make it bigger and more obvious somehow, or maybe rethink the interaction here to do a better job encouraging people to get a key.

**Comment by neynah** [comment]
Perhaps our call to action to get a feature key should be emphasized over entering a feature key especially now that users(recent installs) would only see this view if they did the standard set up.

**Comment by neynah** [comment]
I lightly propose this hoping people have suggestions for improvements/better copy:
![for-work1](https://cloud.githubusercontent.com/assets/855341/14656860/d9662a28-063e-11e6-8452-cbce0beb8593.png)

Note: I changed "Request a feature key" -> "Get your feature key". I feel like "Get your feature key" is a more accurate description of what this button enables the user to do. I suspect it also better fits the expectation that the user can click this button and eventually succeed at getting a feature key vs succeeding at requesting a feature key.
