### ISSUE TITLE
Admin Panel Redesign: Admin Alerts

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1829]
Changes required to ship:
- none currently

Current mock-up:
![adminalerts2](https://cloud.githubusercontent.com/assets/855341/14570958/a7fa9a28-02fb-11e6-84c4-32009d700b1e.png)

Once the user has made changes, "Send alert" button will no longer be disabled. It will be styled as a primary button.

**Comment by zarvox** [comment]
Some amendments to the design, based on discussion with Kenton (the primary user of this feature):

* renamed Admin Alerts to Maintenance Message
* removed $ACCOUNT_EXPIRES, $ACCOUNT_EXPIRES_IN, and $APPNAME, which were legacy from the old demo server setup
* placed the copy above the form
* renamed the "Send alert" button to "Set message"
