### ISSUE TITLE
Make basic `spk` commands work on Mac OS X

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1840]
Some `spk` commands arguably do not really require Linux and could be made to work on Mac OS X as well (basic commands and not `spk dev`).

Related: https://github.com/sandstorm-io/meteor-spk/issues/17

**Comment by ocdtrekkie** [comment]
I will note that if I could "spk verify" on Windows, I would be super excited, but I know that's a super tall order.

**Comment by kentonv** [comment]
@ocdtrekkie How do you feel about Cygwin? If we make it work on OSX then it'll probably work on Cygwin.

(Also, I'm curious why you're so interested in `spk verify`... :) )

**Comment by ocdtrekkie** [comment]
I have no problems dealing with Cygwin, but also... you know we get Bash in July, right? Actually... I kInda wonder if it'll "just work" with Bash? Ubuntu subsystem and stuff?

I only open up Ubuntu for dev work, all of my files and stuff (SPKs, grain backups, etc.) are stashed on Windows.

**Comment by kentonv** [comment]
Well, it's not "bash" that will make it work, it's the Linux compatibility layer, which indeed may solve the problem (for Windows) without needing any changes on Sandstorm's end. Though I suspect the user experience may turn out pretty similar to running a VM.

**Comment by ocdtrekkie** [comment]
We shall have to see, Microsoft and Canonical claim the whole thing is totally magical..............

**Comment by paulproteus** [comment]
@mitar since there is vagrant-spk, do you still have this need?

If so, you should at least know that it's not currently a core team priority, so if you want it, you might have to add it yourself. We would review pull requests that add it.

I would be a big fan of someone adding `spk` to homebrew for that reasons, so long as the `spk` tool indicated clearly which features are unavailable due to not running on Linux.

**Comment by mitar** [comment]
What if `spk` would simply use `vagrant-spk` internally?

I really like how Docker made it. So that client works always over the socket. And then you can have a boot2docker virtual image and then all local commands simply work. Personally I think this is where `vagrant-spk` should go with `spk` being just an interface to it with same API as normal `spk`.

**Comment by ocdtrekkie** [comment]
@mitar But vagrant-spk uses spk. So that'd be quite circular. Spk is like, the really baseline tool, and vagrant-spk is a package that implements spk in a much more compatible and easier to use way. 

You shouldn't need to use spk at all, and solely use vagrant-spk and the commands it supports. (Which I believe includes spk's entire command set.)

**Comment by mitar** [comment]
I am saying, that for the whole tooling around Sandstorm it would be great if there would be one command, let's call it `spk`. And then you or have another one, `spk-daemon` which really do everything, or you have `spk` in two versions, one which calls `vagrant-spk`, and one which does it by itself.

But from the user perspective it is just `spk`. And from the tools calling this tool is just `spk`.

**Comment by ocdtrekkie** [comment]
@mitar I'm saying that tool is vagrant-spk. It sounds like you don't want to use spk, so don't use spk.

**Comment by mitar** [comment]
I am saying that to the end-user it should not matter how tool is implemented. I install "Sandstorm SDK" on my machine (Linux or Mac OS X or Windows) and I can start creating Sandstorm apps using `spk` and I open some address to see and interact with grains. This is it.

**Comment by ocdtrekkie** [comment]
You're not listening. `vagrant-spk` is the only dev tool the end user needs to know exists. You can start creating Sandstorm apps with it, and that's it.

**Comment by ocdtrekkie** [comment]
It's also the only one that the development tutorial teaches you to use.

**Comment by mitar** [comment]
And I am saying that exposing implementation in the name of the app is not a smart idea because you might have different implementations underneath for different cases.
