### ISSUE TITLE
Prevent deletion of a grain if users with whom it was shared does not agree with

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1842]
When you share the grain with others, what if they do not want grain to be deleted? Like, I worked hard to contribute to some text on grain you shared with me, you decide to scrap it, but I would want to keep it around. This is especially important in collaborative tools.

**Comment by ocdtrekkie** [comment]
This is one reason I've noted I'd like a "clone grain" functionality to be available to offer up to certain roles. Similarly, those roles should allow those users to download the grain backup themselves.

Clone grain is being tracked in https://github.com/sandstorm-io/sandstorm/issues/1703

**Comment by mitar** [comment]
Yes, but cloning might be different (you are getting access also to their data - you are becoming admin over the whole grain).

Hm, how does Google Doc address this. If a document is shared with me with all editing capabilities, and then owner deletes it, what happens? What happens if I added it to my Drive before that?

**Comment by kentonv** [comment]
The owner owns the grain. When contributing to someone else's grain, you need to consider the possibility that the owner might delete it. If you are concerned, you can work out an agreement with the owner, or you can copy/paste a backup of your work. I agree that we should support a more automated way to "clone" a grain, as discussed in #1703, but that's really all we can do here.

Google Docs works the same way: if the owner deletes the doc, it's gone. But, if you have access you can make a copy before that happens.

**Comment by mitar** [comment]
I think control over your data is one of very important aspects of modern web. I hoped that sandstorm would be improving here, not accepting the status quo. If I am contributing my data to somebody else, I at least want a way to be able to export it, keep it.

I would even say, that might be a legal requirement in EU countries. To be able to download all your data you have input into a system. Facebook has a download data button for that reason.

**Comment by kentonv** [comment]
> If I am contributing my data to somebody else, I at least want a way to be able to export it, keep it.

That's really between you and the grain owner. Sandstorm has no idea how the apps work and so cannot help you.

Consider that it's a critical security feature that owners be able to revoke sharing. You're proposing that owners not be allowed to revoke sharing links. Sorry but there's just no way this is going to fly.

**Comment by mitar** [comment]
Maybe then this Sandstorm is really not suitable platform for having online voting. I thought that because of high security focus it could be a perfect match. Imagine an official running elections on Sandstorm, they start a voting, invite everyone to vote, people start voting (contributing data), and then official discovers that voting is not going according to "plan". So they can just decide to destroy the grain, without people having any proof how they voted.

I do agree that there are use cases where owner should be able to revoke sharing. But there are also use cases when people should be able to participate knowing that owner cannot revoke their access to data, and then users can decide if they want or do not want to participate.

**Comment by ocdtrekkie** [comment]
Maybe you shouldn't have the vote started by the grain owner then?

**Comment by ocdtrekkie** [comment]
I mean, as long as your data lives on a server, someone ultimately has the ability to turn off that server or delete the data on it. Someone has the ultimate authority. If you want to ensure it isn't deleted because of a unpleasant result, you probably need to give grain ownership (and server admin ownership for that matter) to someone impartial. So maybe make your app controlled by an admin person, but then let them grant people the role to create a poll/election in their grain.

The only way to really avoid that single point of failure would be to maybe do something blockchain-like, where there's a number of PCs which have the voting record, and the consensus of those PCs on what has taken place is considered the authoritative record?

**Comment by mitar** [comment]
> I mean, as long as your data lives on a server, someone ultimately has the ability to turn off that server or delete the data on it.

Hm, I hoped that this is Sandstorm's business model (long term). To offer to host such grains, me paying them, and they will make sure data is copied around redundant and that nobody can really just come and delete it (because of Sandstorm's focus on the security) without permissions. So the only missing piece is then that Sandstorm would not allow deletion based on permissions.

**Comment by ocdtrekkie** [comment]
@mitar The problem is, "you paying for it". Because when you stop paying for it, it ends up deleted, presumably.

**Comment by mitar** [comment]
> The problem is, "you paying for it". Because when you stop paying for it, it ends up deleted, presumably.

That one can be solved through [OpenCollective](https://opencollective.com/).

**Comment by ocdtrekkie** [comment]
"Anyone in your collective can submit expenses. The owner of the collective can approve those expenses with one tap."

Account has an owner, and it uses PayPal, I believe it said, where one person has ultimate legal control.

**Comment by mitar** [comment]
> "Anyone in your collective can submit expenses. The owner of the collective can approve those expenses with one tap."

I think this is a reimbursement.

But in general, owner of grain on Sandstorm does not have to be the same as owner of OpenCollective account. So you need two people to collude.

But this is just an example. You can imagine a similar smart contract which is regularly paying to Sandstorm address and members are refilling it.

I am just saying that you can distribute payments maybe easier then distribute technology.
