### ISSUE TITLE
Trusted UI components for apps

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1847]
Currently, most apps are not written with Sandstorm in mind and are just wrapped to be able to run there. But in the long term Sandstorm as a platform could provide apps some new primitives to use. One such primitive I would love to see are some trusted UI components. For example, my app could ask Sandstorm to ask the user for some sensitive data which would be provided directly to the server-side of my app, without possibly compromised client-side could hijack it.

Browsers allow such UI only through extensions. But Sandstorm could be here an interesting intermediary instead.

**Comment by kentonv** [comment]
Thanks for the idea, but this seems too open-ended for the issue tracker. Feel free to start a thread on the mailing list.
