### ISSUE TITLE
Enhancement: Include Github issues in app-store listing or sandstorm shell

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#185]
Especially now when many apps are under heavy development to get ported to sandstorm it would be good to see bugs and improvements right in the app store of sandstorm or in the shell.

With these information contributors would easy see where some additional work would be needed and users of apps would also have an overview about an apps status.

I assume some projects will get more attention as more and more users can easy use the apps with sandstorm. Having such an overview might also help to lower unnecessary noise e.g. when users open the same bug or improvement several times.

Please let me know if it would be of interest of you if I create such an plugin for the sandstorm shell or if you are working on something like this already.

![bildschirmfoto_2014-12-15_um_10_14_22](https://cloud.githubusercontent.com/assets/7508960/5433045/832130aa-8443-11e4-895c-26eef5be011b.png)

Origin of this request was this issue in Sandstorms Dev Google Groups discussion: 
https://groups.google.com/forum/#!topic/sandstorm-dev/vpM1kKxIGIk

**Comment by neynah** [comment]
Hmm. Although we don't display GitHub issues right in the shell, we do now link GitHub repos on inidividual App pages as well as on the App Market. Let me know if this is sufficient! :)

**Comment by JamborJan** [comment]
From my point of view this is sufficient. A deeper integration would make more trouble and should not be the goal. What if more and more developers host their code on other platforms e.g. on sandstorm based GitLab instances. So current status okay from my side. Issue can be closed.
