### ISSUE TITLE
A way for an app to open a dialog of all users with access to the app

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1850]
Currently, I have an integrated admin interface for users and their permissions in the app. Now, to my understanding, Sandstorm would take care of this and I would just trust the headers. But for users which expect the admin interface to exist I would like to prompt a message/give a link/redirect to Sandstorm page/dialog which would show all users with access to the app and which permissions/roles they have.

**Comment by zarvox** [comment]
This could probably be implemented over `postMessage`, in a way similar to what we do for `startSharing`.  ( @paulproteus did `startSharing` ever get documented? )

**Comment by paulproteus** [comment]
@zarvox - I'm slow to reply to this, but:

Yes, it is documented here: https://docs.sandstorm.io/en/latest/developing/path/ - look for startSharing there.

**Comment by mitar** [comment]
Yes, this is for starting sharing. This ticket is for that other dialog where you audit with whom you shared in the past. I would like that I could show that window as well.

**Comment by paulproteus** [comment]
For showing who you have shared access with, it "should be" "pretty
straightforward" (famous last words, I know) to do something very similar
to startSharing and build a new way for a grain to request that of the
shell.

https://github.com/sandstorm-io/sandstorm/search?utf8=%E2%9C%93&q=startsharing
should show you all the relevant code & docs. If you're interested in that,
I do think we would be happy to merge it.

**Comment by mitar** [comment]
I made #1926.

**Comment by mitar** [comment]
Done with #1926 and #1941.
