### ISSUE TITLE
Error with copy/paste credentials from Google

### ISSUE THREAD

**Issue by ruihildt** [sandstorm-io/sandstorm#1861]
As I was configuring loggin with Google, I copied the credential ID / password from the Google interface by clicking on the button.

It didn"t work first because it added extra space before and after the credential ID / key.

I'm using firefox developer edition 47.

@dwrensha suggested it was similar to #1795.

**Comment by zarvox** [comment]
Strictly speaking, the copy/paste weirdness is either a Firefox bug or a Google bug; not sure which.

That said, perhaps we should `.trim()` client IDs and secrets before saving them?  I imagine we would actually want that behavior for a majority of text inputs.

**Comment by kentonv** [comment]
Yeah, it seems like Google is suffering from exactly the same Firefox bug we hit. But we can totally .trim() on our end in this case.
