### ISSUE TITLE
Switch official Sandstorm build process to be based on Debian jessie, not Debian unstable

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1864]
Rationale:
- There are lots of subtle issues that arise from our use of Debian unstable as the source of the files in the Sandstorm bundle.

Status:
- We'll aim to do this in the next few months. We'd like to do it sooner, but we also want to do it carefully, so it'll probably take a bit of @kentonv focus time to do it.

**Comment by zenhack** [comment]
This smells out of date to me.
