### ISSUE TITLE
"undefined" in share link for anonymous users

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1869]
See `undefined` in the share link:

![sandstorm_build_wiki_ _alpha sandstorm io_-_2016-04-18_16 24 17](https://cloud.githubusercontent.com/assets/585279/14622888/28bf5cce-0582-11e6-9381-041cdee7d247.png)

**Comment by dwrensha** [comment]
Good catch. This specifically happens for grains that still use the old sharing model.

**Comment by zarvox** [comment]
I guess the right thing to do for old-sharing-model grains is to give the current route instead?  (Or migrate all known old-sharing-model grains to the new model.)

**Comment by dwrensha** [comment]
If you're logged in, you see "This grain uses the old sharing model. You can share it by copy/pasting the URL from the location bar", which is reasonable.

**Comment by ocdtrekkie** [comment]
Do we have a ballpark on what's actually left of the old sharing model grains? They predate Oasis, so AFAIK, it'd be entirely on Alpha and people's own self-hosted servers, right?

**Comment by neynah** [comment]
I also found "null" in the share link (while logged out): https://github.com/sandstorm-io/sandstorm/issues/1065#issuecomment-201542062

**Comment by paulproteus** [comment]
![screenshot from 2016-04-27 18 20 27](https://cloud.githubusercontent.com/assets/25457/14872830/e0f69dce-0ca4-11e6-9ff9-c04e29c25949.png)


There is no longer a "Share" button for anonymous users in this case, so closing the issue! Thanks @dwrensha for fixing it, presumably in #1879

**Comment by mitar** [comment]
There is no title either anymore? ;-)

**Comment by paulproteus** [comment]
In the case of viewing a grain to which you do not have access, while not logged in, yes, there is no title. But I think that is OK! :)

**Comment by mitar** [comment]
My example was from: https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands

Where you do have access.

**Comment by paulproteus** [comment]
@mitar d'oh. I meant to leave the image as a comment on this bug: https://github.com/sandstorm-io/sandstorm/issues/1065#issuecomment-201542062
