### ISSUE TITLE
Seeing the websocket proxy warning in Admin Settings

### ISSUE THREAD

**Issue by zombiezen** [sandstorm-io/sandstorm#1898]
This is probably my fault, since I'm running a custom server that does Websocket proxying, so I'd like to know what I messed up.  Apps seem to be running fine for me, even ones that need websockets.  What exactly does this check do?  I checked the Sandstorm server log and couldn't find anything useful.

**Comment by paulproteus** [comment]
Wow, fascinating.​

https://github.com/sandstorm-io/sandstorm/blob/94586c2e13202b96dab7aa54ebd9b56e96f04e44/shell/client/admin-client.js#L141
is the code. It's pretty simplistic. What's the value of

"Meteor.connection._stream.socket.protocol"

for you? For me, on rose.sandcats.io, it is:

"websocket"

which is consistent with this self-test.

**Comment by zombiezen** [comment]
`xhr-polling`. :confused: 

I'm digging into the SockJS source... Chrome dev tools indicates that the Sandstorm shell does open a websocket briefly, sends no data, then falls back to XHR.

**Comment by paulproteus** [comment]
Thanks for digging into this! I am curious what you discover the issue is.

**Comment by zombiezen** [comment]
Aha. Found error logs on my frontend proxy that uses Gorilla Websockets (a Go package).  This isn't a Sandstorm issue, sorry for the noise.

**Comment by zombiezen** [comment]
Hm. Actually, has anything changed in Sandstorm/Meteor wrt to Websockets recently?  The issue that I'm seeing is that reserved bits are getting set while reading frames from the Sandstorm server.  I know this used to work.

**Comment by zombiezen** [comment]
Ah found it. This is the unimplemented `permessage-deflate` extension in gorilla/websocket#3. I can kludge around it locally.

**Comment by paulproteus** [comment]
Honestly, that was fascinating. Thanks!
