### ISSUE TITLE
Intro.js overlay has been broken since at least 0.159

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1899]
It's invisible, but the user still has to click once to dismiss it -- seems like a CSS problem. Seems broken on Oasis. 0.159 was the Meteor 1.3 update which I know involved some changes to the way the CSS is included.

**Comment by kentonv** [comment]
Problem is that in the blackrock build, the CSS symlink does NOT point into the directory where the build is happening, but rather into the Sandstorm directory's copy of node_modules. If the Sandstorm directory happens to be clean, then the symlink is broken. Ugh.

**Comment by paulproteus** [comment]
That is too bad. Thanks for catching that and fixing it.

**Comment by kentonv** [comment]
I mostly blame myself, but I partly blame Meteor for being like "Broken symlink? Meh, I'm sure it wasn't important. Carry on."
