### ISSUE TITLE
404 Error when installing

### ISSUE THREAD

**Issue by Deathsbman** [sandstorm-io/sandstorm#1901]
I'm using a fresh install of Ubuntu with Gnome on the HP Proliant ML110 G6 with a Xeon X3450 and 8gb of ram. I ran the HTTPS-verified install, however when I opened my sandcats.io link I received Access Error: 404 -- Not Found instead of the setup page. Any ideas as to how I could fix this?

**Comment by paulproteus** [comment]
Hi there,​

Can you provide a screenshot of the 404? I wonder if you need to enable
port forwarding on your router.

Here is a list of common problems & things to think about, in case that
helps:
https://oasis.sandstorm.io/shared/4vrj4sIOFYy1iJfYKkvkqJGUTvBXLhb6CLODn-HQ2UF

If you are still having problems, then by all means please respond here!
The link is intended to help you succeed faster, but we probably will still
have to chat about things and that's OK.

**Comment by Deathsbman** [comment]
I have set a static IP and port forwarded 433 and 80 . However when accessing the admin token Firefox tries to connect but then fails leaving a blank page.


Sandstorm port forward setup
![technicolor_gateway_-_sandstorm_-_waterfox_2016-04-27_11-10-58](https://cloud.githubusercontent.com/assets/18638234/14843800/3353e778-0ca7-11e6-9281-6d95077d8451.png)

Sandstorm assigned to the server
![technicolor_gateway_-_game_ _application_sharing_-_2016-04-27_11-10-41](https://cloud.githubusercontent.com/assets/18638234/14843799/335000ae-0ca7-11e6-941b-e3b409a0bd7e.png)

**Comment by dwrensha** [comment]
By default Sandcats uses port 443, not 433. Does it work if you forward port 443?

**Comment by Deathsbman** [comment]
I have changed it to use port 443, but I am still unable to connect.

Thank you both for helping me with this.

**Comment by TheLinuxNerd** [comment]
having same issue,

**Comment by paulproteus** [comment]
Hi @Deathsbman ,

Did you change the TCP forwarding, not just the UDP forwarding? Also Sandstorm only needs TCP, not UDP, so I suggest removing the UDP lines to avoid confusion.

Probably you are experiencing the hairpin routing problem described in https://oasis.sandstorm.io/shared/4vrj4sIOFYy1iJfYKkvkqJGUTvBXLhb6CLODn-HQ2UF . Usually the only real advice I can give is to switch your home router, though. :(

**Comment by ocdtrekkie** [comment]
I'm going to close this since there's not enough here to figure out why the original requestor couldn't connect and it's been four years.
