### ISSUE TITLE
Disable e-mail sharing for demo users and rate-limit for everyone else

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1906]
It looks like someone has discovered that they can send spam messages through the Sandstorm sharing dialog. :(

We should:
* Disallow demo users from sending sharing e-mail. They'll need to share by link only.
* Rate-limit sharing emails sent by real users, probably using the same mechanism as we use to rate-limit email from apps.

This is somewhat of an emergency as the longer this spammer continues their activity the more reputation we lose.

**Comment by ocdtrekkie** [comment]
I at least slightly respect this spammer for the fairly creative method of spamming via the share dialog on a not-even-1.0-yet platform.
