### ISSUE TITLE
'Email us' link broken on https://sandstorm.io/community

### ISSUE THREAD

**Issue by josephg** [sandstorm-io/sandstorm#1920]
At [https://sandstorm.io/community](https://sandstorm.io/community)

![image](https://cloud.githubusercontent.com/assets/47413/14908416/7b2573cc-0e1a-11e6-9f53-425a5309b265.png)

'Email us' links to `https://sandstorm.io/community@sandstorm.io`

**Comment by kentonv** [comment]
Fixed, thanks!

Amusingly, I learned about this through a Twitter bot before seeing it here:

https://twitter.com/brokencodebot/status/725912611913486336
