### ISSUE TITLE
frontend crashes on API access to non-open grain

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#193]
Start a new Hacker CMS grain, and generate an API key. Now restart the Sandstorm server with:
```
$ sudo sandstorm stop
$ sudo sandstorm start
```
 Now try making an API request with curl:

```
$ curl http://api.sandstorm-lithium.dwrensha.ws:6080 -H "Authorization: Bearer mWlZGAQVdtfWu3ROKFFTEaqODjlfApXSIX6bPhjtTl4"
curl: (52) Empty reply from server
```

In `/opt/sandstorm/var/log/sandstorm.log` we get this error:
```
/bin/node: symbol lookup error: /programs/server/npm/capnp/node_modules/capnp/bin/linux-x64-v8-3.14/capnp.node: undefined symbol: _ZN2kj1_5Debug11logInternalEPKciNS1_8SeverityES3_NS_8ArrayPtrINS_6StringEEE
** Front-end died! Restarting it...
```

I'm at the latest Cap'n Proto commit https://github.com/kentonv/capnproto/commit/517aaa22983f7fbf53faafad9a9ed8bad9a1ac6a.
Perhaps a recent Cap'n Proto change broke the node bindings?

**Comment by kentonv** [comment]
This looks like what happens when there's an ABI version mismatch between a library and its client. Try rebuilding node-capnp from scratch. ("make clean" in the Sandstorm directory should accomplish this, I think.)

**Comment by dwrensha** [comment]
"make clean" did not fix it, but "git clean -xfd" did.
