### ISSUE TITLE
No such file or directory; name = /var/mail/tmp/_Qa8lI_Valn8JIBtmb2kcd1

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1934]
Hm, it seems that receiving e-mails do not work if app does not create before necessary spool directory?

There is no `/var/mail/tmp` nor `/var/mail/new` and it seems http-bridge code currently assumes there is.

**Comment by paulproteus** [comment]
Hi @mitar,

I talked with Jason and Kenton in person and learned that this is the desired behavior. Creating the directory is an indication that your app actually wants to receive mail, in the current HackSessionContext world.

I've also added docs on those lines, which will go live momentarily.

I think that addresses the question you had in this issue; if not, do let me know.
