### ISSUE TITLE
Provide session ID as x-client-ip for HTTP bridge for Meteor apps

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1943]
`x-client-ip` header is one of [whitelisted headers](https://github.com/sockjs/sockjs-node/blob/master/src/transport.coffee#L133) in sock.js which is used by Meteor. My proposal is that HTTP bridge (maybe only when running for Meteor app) would provide **in addition** session ID as `x-client-ip` header (or any other whitelisted headers, if preferred, maybe `x-forwarded-for`).

This would allow us to access the header on the server side through `connection.httpHeaders` which would in turn allow us to use capnproto RPC to connection to the hack session and get all necessary data for the session from there using [node-capnp](https://github.com/kentonv/node-capnp), without having to go through HTTP request ping-pong between client and server. We could more or less simply expose hack session as part of Meteor `connection` object. This would be the cleanest possible integration with Meteor. Every Meteor connection would then have immediately hack session associated with it (we could make a lazy accessor method for it).

**Comment by mitar** [comment]
Maybe this could just be an argument to HTTP bridge which Meteor apps can then use:

```
argv = ["/sandstorm-http-bridge", "--session-id-header=x-client-ip", "4000", "--", "node", "start.js"],
```

**Comment by mitar** [comment]
On IRC, in discussion with @zarvox, we could maybe just patch sock.js in meteor-spk to whitelist all Sandstorm headers.

**Comment by mitar** [comment]
Another option would be to use node.js middleware to register before the sock.js for the same endpoint and store away headers or modify them so that the session header is copied to `x-client-ip`.

**Comment by kentonv** [comment]
You don't want this -- it would be a security hole.

SockJS is intentionally XSRF-able -- the connection could originate from any origin. In particular, SockJS has a transport that involves iframe-ing a page inside the app's origin and then postMessage()ing through it. Any third-party origin would be able to access that transport, and on the server side we have no way to tell that the messages originate off-origin. Sandstorm will add all the usual headers identifying the user as it has no way to know that these requests originated from a different origin. This is why SockJS absolutely requires that you authenticate the third party through messages passed over the transport, not using headers, and why they have the whitelist.

accounts-sandstorm's rendezvous protocol avoids this problem by making a regular non-XSRF-able XHR independently of SockJS.

**Comment by mitar** [comment]
But this is a bad design from sock.js? Sock.js does receive origin information through `postMessage` and it could use it to allow only permitted message to be received?

**Comment by kentonv** [comment]
@mitar I don't know that I'd call it "bad" design. Their goal is to do everything WebSocket does. WebSocket supports cross-origin connections. I suppose technically WebSocket supports an "origin" header which sock.js is failing to emulate in some cases. However, sock.js is very clear in the documentation that authentication must be carried out via messages on the socket, not by auxiliary cookies or headers, so it seems fair enough to me.

**Comment by mitar** [comment]
> Their goal is to do everything WebSocket does. 

I think their goal is to not agree with origin-based security model of the web and allow everyone to connect to everyone (I think all endpoints are CORS-connectable by default) and then do authentication through an app. I think this is a valid design decision to have, but I do not like that it is forced on users as the only one. In particular, for Sandstorm which uses origin-based security a lot it then goes against the stream.

As a fact, there is really no reason why [this line here](https://github.com/sockjs/sockjs-client/blob/master/lib/iframe-bootstrap.js#L42) couldn't simply be `e.origin === location.origin`.

We could create a Meteor package which serves iframe with code with such check.

**Comment by mitar** [comment]
BTW, it is sock.js [philosophy](https://github.com/sockjs/sockjs-client):

> All the transports must support cross domain connections out of the box. It's possible and recommended to host a SockJS server on a different server than your main web site.

"Out of the box" means "change the default security model of the web". Really no surprise that it is then surprising how it works.
