### ISSUE TITLE
Porting Guide should mention Vagrantfile

### ISSUE THREAD

**Issue by phildini** [sandstorm-io/sandstorm#196]
As a developer trying to make apps for Sandstorm, I would like the documentation to reference my happiest path.

It would be great if the Porting Guide could mention the pre-existing Vagrantfile as an alternative to install.sandstorm.io. 

Not a huge deal, but would have saved me an hour or so of mangling.

**Comment by paulproteus** [comment]
I'm super glad the Vagrantfile was useful to you, @phildini ! Your wish is my command.

**Comment by paulproteus** [comment]
I added this last week! Marking as resolved.

To wit: https://github.com/sandstorm-io/sandstorm/wiki/Porting-Guide
