### ISSUE TITLE
Admin Panel Redesign: Customization

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#1960]
We need a place for some other fields that are currently supported, which approximately all fall under the category of "white-labeling" or "server customization":

* Server title
* Splash URL
* Signup Dialog: 
* Terms of Service URL 
* Privacy Policy URL

Barring any objections, I plan to make a basic form with our existing form styles for each of these at `/admin-new/customization`, and add a nav pill to admin-new named "Customization".  (Suggestions for better names than "customization" welcome.)

**Comment by paulproteus** [comment]
Just brainstorming:

- Whitelabeling
- Server identity
- Publicly-visible server customization
- Customization
- Personalization
- Personalize this server

**Comment by neynah** [comment]
@zarvox Sounds great, feel free to poke me to take a look at it once you've made some progress!

Also, I like "Personalization" so far! Sounds less vague than "Customization".

**Comment by ocdtrekkie** [comment]
Suggestion: Can this be the same panel as App Sources? That is generally going to be a personalization/white-labeling activity as well.

**Comment by zarvox** [comment]
Hmmm.  I think I'm (barely) -0 on that idea for now, mostly because I think if I were an admin looking for a "disable checking for app updates" or "where do app updates come from" option, I'd be somewhat surprised to find it placed under "Personalization".  And I think if/when we add multi-app-index support, we'd wind up needing to pull those config options back out again later, and the less we shuffle things about, the better off our users will be.

The merge works marginally better in the context of whitelabeling, though I'm not sure whitelabeling also carries with it expectations of separate server URLs or outgoing connections, and again it might reach a level of complexity that we want to split app things out again.

I think part of the challenge is that these last few options are sufficiently obscure/niche usecases that it's hard to join them into a unified hierarchy, which is comforting insofar as it means that even if we're not thrilled with the ontology, it probably won't hurt a large fraction of users. :)
