### ISSUE TITLE
Mail with replyTo bounces erroneously

### ISSUE THREAD

**Issue by awans** [sandstorm-io/sandstorm#197]
I've got a sandstorm set up to get mail forwarded from Gmail, and it works fine unless the inbound email has a Reply-To: header set. In which case I get:

    Delivery to the following recipient failed permanently:
    ...
    The error that the other server returned was:
    550 Type error in field: replyTo

I noticed instead of using the mailparser mail.replyTo object, sandstorm emits:

    replyTo: mail.headers['reply-to'] || {}

Changing that line to 

    replyTo: mail.replyTo || {}

Seems to result in a different error:

    550 No field named: 0

So I figure I'm a good bit out of my depth here.

I can reliably reproduce this by sending myself a message to any Google Group.

(aside: Hi Kenton! Not sure if you remember me from our Google days when I was working on OAuth, but I set up my Sandstorm server over the holiday—neat stuff!)

**Comment by kentonv** [comment]
Hey Andrew! Yep, I remember you. :) Thanks for trying Sandstorm!

Jason's the expert on the e-mail code so I've assigned this to him.
