### ISSUE TITLE
App Upload confused with "Upload File"

### ISSUE THREAD

**Issue by jacksingleton** [sandstorm-io/sandstorm#1985]
People using Sandstorm for the first time initially thought that the "Upload" button on the Apps page would let them upload a local file.

Although when you're familiar with Sandstorm, the fact that it's on the Apps page makes it clear that it is for uploading a new application, it makes sense to me that this is confusing especially when coming to Sandstorm as an alternative to Google Docs.

As upload app is a fairly advanced feature, maybe it can even be hidden or de-emphasized.

**Comment by ocdtrekkie** [comment]
I kinda wish you could just upload arbitrary files without an app to wrap them.

Would changing "Upload" to "Upload App" or something similar make it less confusing?

**Comment by jacksingleton** [comment]
Yeah I think that would help.
