### ISSUE TITLE
Idea: pre-allocate (instead of randomizing) domains for cors workaround

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#1998]
The drawbacks of requiring wildcard certs are well-acknowledged. Unfortunately it's looking like let's encrypt isn't going to support them anytime soon. My understanding is that the randomized domains thing is just there to prevent grains from being able to bypass cors on each other. I had an idea: rather than picking random domains, pre-allocate a decently-sized pool of them, get a cert that's valid for all of them from let's encrypt, and and allocate one from the pool to each new grain. We can re-use domains from grains that have been deleted. Obviously this puts a hard cap on the number of grains you can have running at once, but I suspect we could pick a large enough number for most people, and and we might be able to rig up something to get more when we start to run out.

Thoughts?

**Comment by paulproteus** [comment]
Another purpose of the hostnames is to defang CSRF attacks. Getting a Let's
Encrypt cert involves publishing the hostnames, which is bad for using the
hostname as a CSRF token of last resort.

Relevant links:

- "Quick thoughts on Let's Encrypt, as a CA" -
https://groups.google.com/forum/#!msg/sandstorm-dev/-CvczbyYgmo/je0YWcxEj-AJ

- "Randomized, unguessable hostnames can help mitigate certain common
security bugs in apps, such as XSRF, reflected XSS, and clickjacking
attacks. All of these attacks involve an attacker tricking the user's
browser into performing actions on another site using the user's
credentials. But for any of these attacks to work, the attacker must know
the address to attack. If every user gets a different hostname, and indeed
the hostnames change frequently, then it is much harder to launch these
kinds of attacks"
https://docs.sandstorm.io/en/latest/administering/wildcard/

Given that, I think doing this in batch can't work, but let me know if you
see a different path forward.

**Comment by zenhack** [comment]
Any way we could stick the secret in the path, rather than the domain name? Depending on how sandstorm handles the paths (I'm a little fuzzy), that might mean leaking the secret to the grain it's pointing at, which might be a problem. It would however have the advantage of not transmitting the secret in plain text. We could do pre-allocation for cors stuff, and then stick the last-ditch csrf bit in the path.

**Comment by kentonv** [comment]
Putting the secret in the path creates complications for apps, many of which contain lots of host-relative links in their UI which would have to be updated to account for the leading token component. (Otherwise putting the token in the path would be great.)

Even disregarding the secret requirements, pre-allocating certificates would probably put an excessive amount of load on the Let's Encrypt servers. Keep in mind that we want a new host for every _session_ -- that means every time you open a grain, it's on a new host. And really, even allocating a new host per grain would probably generate far too much load for Let's Encrypt.

I think the most promising solution here is probably suborigins, but that's still only a proposal (and will still require apps to deal with a new leading path component).

I'm closing this issue since unfortunately I don't think pre-allocation is a viable strategy. Sorry.

**Comment by zenhack** [comment]
Quoting Kenton Varda (2016-05-17 20:16:16)

>    Even disregarding the secret requirements, pre-allocating
>    certificates would probably put an excessive amount of load on the
>    Let's Encrypt servers. Keep in mind that we want a new host for
>    every session -- that means every time you open a grain, it's on a
>    new host. And really, even allocating a new host per grain would
>    probably generate far too much load for Let's Encrypt.

A critical part of my idea was to *recycle* the domains; it wasn't just
block allocation. So you wouldn't be actually hitting let's encrypt for
new sessions/grains on a regular basis; only if load exceeds previous
numbers. It's not as obvious to me that the load would be problematic
for the scale of deployments at which wildcards are a burden. But I
agree with your other points, which makes the whole thing moot - I
hadn't realized it wasn't just a CORS issue. Oh well.

**Comment by kentonv** [comment]
Thanks for the suggestion. Unfortunately recycling domains would allow an app to see the data stored in cookies / localStorage by a previous app, and could allow an app to intentionally leak data to another app through this channel, both of which we'd consider security problems.

**Comment by zenhack** [comment]
Quoting Kenton Varda (2016-05-20 17:31:12)

>    Thanks for the suggestion. Unfortunately recycling domains would allow
>    an app to see the data stored in cookies / localStorage by a previous
>    app, and could allow an app to intentionally leak data to another app
>    through this channel, both of which we'd consider security
>    problems.

Good call, hadn't thought of that.
