### ISSUE TITLE
docs: Decide what "I" vs. "we" means, then make the docs consistent

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2015]
Quoth @zarvox 

> Do we use "I" or "we" in the docs? I think I've seen both; we should probably attempt to be consistent. (I prefer "we" in documentation maintained by multiple individuals, unless there's also clearly attributed authorship for each article/unit, so we know who is "I".)

See also: https://github.com/sandstorm-io/sandstorm/pull/1979

**Comment by kentonv** [comment]
I always use [royal "we"](https://en.wikipedia.org/wiki/Royal_we). :P

**Comment by kentonv** [comment]
(In all seriousness, I vote for "we".)

**Comment by paulproteus** [comment]
+1 to "we". I'll submit a PR that makes the docs consistent.

Here's my grep that shows how I'm finding the "I" examples.

```bash
paulproteus@slittingmill:~/projects/sandstorm/docs$ git grep I[^a-zA-Z]
```
