### ISSUE TITLE
Blue text displayed during Sandstorm installation is really hard to read

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2037]
![image](https://cloud.githubusercontent.com/assets/855341/15840760/ee1b5668-2c00-11e6-9ea0-fbad63d34b94.png)
![image](https://cloud.githubusercontent.com/assets/855341/15840933/2a7e8cdc-2c02-11e6-8bd6-6195e3923637.png)

**Comment by paulproteus** [comment]
I guess that's PuTTY or powershell?​ Can you specify what SSH client or
terminal is being used?

**Comment by zarvox** [comment]
Looks like powershell.

Maybe the blue would be better off as cyan?

**Comment by neynah** [comment]
The one at the bottom is PowerShell

**Comment by neynah** [comment]
What are potential colour options? Cyan or any other colour that's bright would work.

**Comment by zarvox** [comment]
Anything from https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by neynah** [comment]
Thanks for the link. Cyan/gray look like the best options. I would go with Cyan.

**Comment by paulproteus** [comment]
Note that it could be on a white background, or a dark background; you
never know with terminals.​

**Comment by neynah** [comment]
Is default text specified as white or does it vary across terminals?

**Comment by zarvox** [comment]
Depends on the terminal's settings.  On most Linux systems, the default terminal colors are white-on-black; on OSX, Terminal.app defaults to black-on-white.

**Comment by paulproteus** [comment]
Gentle consensus on today's call was to consider using the ANSI escape
codes that are not specific colors for these prompts that, in the
screenshot, are hard to read. Reference:
http://bluesock.org/~willg/dev/ansi.html

Options:

- Reverse video

- Bold

Drew, I think you mentioned "double intensity" or something like that. Was
that equal to what Will Guaraldi Kahn-Greene describes as "bold"?

**Comment by zarvox** [comment]
Yes, "bold" is what I intended.

**Comment by neynah** [comment]
The fix for this issue has been reverted so we should reopen this.

**Comment by paulproteus** [comment]
This has been un-reverted so we can close it again! Screenshot for verification:

![screenshot from 2016-10-13 17 24 37](https://cloud.githubusercontent.com/assets/25457/19371676/f22e69e2-9169-11e6-8220-c1d82d7a8d4a.png)
