### ISSUE TITLE
"Upload app..." button disappears during search

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2038]
When typing in the search box the "Uninstall..." button remains but the "Upload app..." button disappears.

The behaviour is strange but I don't think this is super urgent.
![image](https://cloud.githubusercontent.com/assets/855341/15841610/71f0fe10-2c07-11e6-955f-50716e679c0b.png)
![image](https://cloud.githubusercontent.com/assets/855341/15841616/7ce66c6a-2c07-11e6-9bd9-1cf8a3e07b5b.png)

**Comment by paulproteus** [comment]
I agree the behavior is strange. FWIW I think the alternative is actually worse - it'd be as if "Upload app" were contextually sensitive to the thing you were searching for. Given that, I prefer this as-is; I think "the cure is worse than the disease", as some people like to say. Curious what others think.

**Comment by zarvox** [comment]
Perhaps a solution to the button(s?) being contextually-weird is to find a different place in the visual hierarchy for it, which makes it clear that the button lives outside the realm of the search results.

**Comment by zarvox** [comment]
To make a specific proposal:

* add a horizontal rule below Apps, like we have for all of the Admin routes
* place the uninstall and upload buttons *above* that horizontal rule

We could also, in due time, breadcrumb out Apps / App Title when looking at the app details page, which I think would also be reasonable and help give people a sense of location in some hierarchy.
