### ISSUE TITLE
What are Network capabilities?

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2039]
Might be worth adding a short description about what this page is for.

User tested said 

> its unclear what granted by and granted to refer to in network capabilities. Theres no data yet b/c it is a new server. Do users or apps grant network access?

![image](https://cloud.githubusercontent.com/assets/855341/15842359/2bddaf6c-2c0d-11e6-922a-7ed1cd3486f0.png)

@paulproteus proposes "(i) Sandstorm's <a href="...">security model</a> means that apps have no network access until granted to them. This page enables granting network access."

**Comment by neynah** [comment]
> This page enables granting network access.

This is somewhat confusing since capabilities aren't granted on this page. Perhaps "This page displays capabilities granted to and from grains."?

**Comment by paulproteus** [comment]
To make sure I understand your proposal, let me attempt to repeat it.

Add info box to the top, saying e.g.:

(i) Sandstorm's security model means that apps have no network access until
granted to them. This page displays capabilities granted to and from grains.


If so, IMHO we should define capability. Let me propose another version.


(i) This page displays network capabilities granted to grains. Sandstorm's
security model means that apps have very limited network access until
granted to them. A grain can request full network access while it is being
used; only an admin can say yes, which grants a "network capability" to the
app.


or


(i) This page displays network capabilities granted to grains. Sandstorm's
security model means that apps have very limited network access until
granted to them. A grain can request more network access while it is being
used; only an admin can say yes, which grants a "network capability" to the
app.

You wrote "to and from" grains. Is it true that this page handles the
"from"? I thought it doesn't so I wonder why you said it; I could easily be
mistaken.

**Comment by neynah** [comment]
@paulproteus I think this is pretty close:

>This page displays network capabilities granted to grains. Sandstorm's
security model means that apps have very limited network access until
granted to them. A grain can request full network access while it is being
used; only an admin can say yes, which grants a "network capability" to the
app.

However, referring to apps & grains in the same paragraph makes it seem like we're talking about different things—is that what you intended? I removed "Sandstorm's security model" because it feels like a strange time to sell them on our security model unless it's a required piece of information for them to comprehend this page. (FWIW, I'm not fluent in network capabilities just trying to improve the comprehension from a user's perspective.)

What about: 

This page displays network capabilities granted to grains. By default, grains have very limited network access until granted to them. A grain can request full network access while it is being
used; only an admin can say yes, which grants a "network capability" to the
grain.

Also, perhaps we can say something better than: "...only an admin can say yes".

**Comment by zarvox** [comment]
Given the length of that paragraph, and the technical nature of the explanation, perhaps it belongs behind one of those (?) icon things.

**Comment by paulproteus** [comment]
+0 to using a questionmark

**Comment by neynah** [comment]
Hmm on second thought, I suppose some basic info about this page should still be on this page. Perhaps a question mark would be appropriate if we were describing what network capabilities are. I'm not sure if we need to though.

**Comment by neynah** [comment]
Suggested change. Still very much open to comments & suggestions.
![networkcapabilities4](https://cloud.githubusercontent.com/assets/855341/16062529/80326a8a-3248-11e6-8be2-4c8add852ca2.png)

**Comment by paulproteus** [comment]
I suggest:

- striking "until granted to them"

- replacing "can say yes" with "can approve the request"

Generally looks great.

**Comment by neynah** [comment]
![networkcapabilities4 1](https://cloud.githubusercontent.com/assets/855341/16062610/1c2a3116-3249-11e6-8fc1-7d9c44a96887.png)

**Comment by kentonv** [comment]
Note that I suspect this page will grow to cover other kinds of "frontend capabilities" in the future. We might want to consider changing the title and description to be more general.
