### ISSUE TITLE
Splash page should explain admin account setup

### ISSUE THREAD

**Issue by ragesoss** [sandstorm-io/sandstorm#204]
The first user to sign in to a sandstorm server becomes the admin; they can install new apps, and an invitation from that user is required for other users to be able to install apps and so on.

In the case that no admin account has been created yet, the splash screen should explain how this works: that the first user to sign in will become the admin, and after that other users can sign in but without an invitation they will not be able to do much.

**Comment by paulproteus** [comment]
Thanks for filing this, Sage!

**Comment by jparyani** [comment]
Fixed in e7f75f84478c61de2154e48615f0e54827ba641f
