### ISSUE TITLE
Update docs to match roles in Admin Panel.

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2040]
https://docs.sandstorm.io/en/latest/administering/guide/#accounts-authentication-and-access-control
![image](https://cloud.githubusercontent.com/assets/855341/15871175/131aa73c-2ca8-11e6-9b65-00f7c566d305.png)
![image](https://cloud.githubusercontent.com/assets/855341/15871160/0120af40-2ca8-11e6-9c0f-bc3535a04dc6.png)

**Comment by ocdtrekkie** [comment]
I can take this and probably send the PR this evening and take a look at if there's any important notes to add here.

**Comment by paulproteus** [comment]
Thanks! I'd be grateful for that!​
