### ISSUE TITLE
install.sh: Give good advice to people on RHEL/CentOS 7.2

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2043]
Per https://github.com/sandstorm-io/sandstorm/issues/64#issuecomment-223464905 , it seems it's possible for RHEL/CentOS 7.2 users to get user namespaces. Tasks:
- [ ] Manually test if CentOS 7.2, when combined with the advice on that issue, can possibly work with Sandstorm.
- [ ] If so, during install.sh, and probably also in our online documentation, tell people what to do to make a CentOS/RHEL 7.2 machine compatible with Sandstorm.

**Comment by paulproteus** [comment]
BTW huge thanks to @M4rtinK for looking into this. If you're willing to test out some of the above, I'd love to help you do that.

**Comment by paulproteus** [comment]
Here's what my research shows so far:

- My kernel version is `3.10.0-327.22.2.el7.x86_64` and I had to run `sudo grubby --args="user_namespace.enable=1" --update-kernel=/boot/vmlinuz-3.10.0-327.22.2.el7.x86_64` in order for user namespaces to exist. I did have to upgrade my kernel 

- If you disable the `assert_usable_kernel_version` check within `install.sh`, then you can install Sandstorm.

- However, upon launching a grain, one runs into this error in `sandstorm.log`

```
*** Uncaught exception ***
sandstorm/supervisor.c++:863: failed: unshare(CLONE_NEWUSER | CLONE_NEWNS | CLONE_NEWIPC | CLONE_NEWUTS | CLONE_NEWPID): Operation not p
ermitted
stack: 0x5965c1 0x595ec2 0x5bfd89 0x5bfd7a 0x48a9ff
capnp/rpc.c++:123: info: returning failure over rpc; exception = kj/async-io.c++:120: failed: expected result >= minBytes; Premature EOF
stack: 0x49b0c2 0x57ede0 0x57e960 0x57dd70 0x57cb50 0x4378f0
```

- However, the test program in `install.sh` works fine. Here's the strace of it.

```
execve("/tmp/testprog", ["/tmp/testprog"], [/* 25 vars */]) = 0
setuid(65534)                           = -1 EPERM (Operation not permitted)
unshare(CLONE_NEWUSER)                  = 0
_exit(0)                                = ?
+++ exited with 0 +++
```

- Therefore, maybe it's one of the other `unshare` parameters that is being blocked by non-root? Or something like that.

**So close!**

How I'm testing:

- `mkdir /tmp/rofl ; cd /tmp/rofl ; vagrant init bento/centos-7.2; vagrant up --provider virtualbox ; vagrant ssh`

Other notes:

- Using the CentOS 7 Atomic Host Vagrant box resulted in `curl` being unable to do HTTPS handshakes, so that didn't work.

**Comment by zarvox** [comment]
The unshare(2) man page documents three possible reasons for getting an EPERM when calling unshare:

       EPERM  The calling process did not have the required privileges for this operation.

       EPERM  CLONE_NEWUSER was specified in flags, but either the effective user ID or the effective group ID of the  caller  does
              not have a mapping in the parent namespace (see user_namespaces(7)).

       EPERM (since Linux 3.9)
              CLONE_NEWUSER  was  specified  in  flags and the caller is in a chroot environment (i.e., the caller's root directory
              does not match the root directory of the mount namespace in which it resides).

I'm not sure which of these is likely to be responsible for this error.

**Comment by ocdtrekkie** [comment]
This is probably able to be closed now, because Sandstorm should work on kernel 3.10 now without userns anyhow?

**Comment by kentonv** [comment]
@ocdtrekkie Indeed, thanks.
