### ISSUE TITLE
Make a mockup for the "(?)" on the /grains page

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2045]
We plan to add a "(?)" button on /grains.

This page tracks the creation of mockups (or other high-clarity information) to answer the following questions.

- On the /grains page, how will the (?) thing look before it is clicked
- On the /grains page, how will the (?) thing look after it is clicked, i.e. where will the text go
- On the /grains page, how will the (?) thing look when it is being hovered-over

- Both desktop & mobile for the above

**Comment by neynah** [comment]
Mock-ups also show proposed text change "You don't have any grains yet..." for when there are 0 grains.

![grains1](https://cloud.githubusercontent.com/assets/855341/15914559/ce31e3de-2d96-11e6-8f75-9130c8a23a0a.png)
![grains2](https://cloud.githubusercontent.com/assets/855341/15914563/d0ff029a-2d96-11e6-911f-b601ffc2b0ef.png)
![grains-hover](https://cloud.githubusercontent.com/assets/855341/15914722/25695b18-2d98-11e6-8b9f-3d110cf7aada.png)

**Comment by paulproteus** [comment]
@neynah you have an interesting question-mark here! How should I create it?

**Comment by neynah** [comment]
I'll open a PR for the icon once I export it. :)

**Comment by paulproteus** [comment]
Question: Should I remove the table header text in the case of no grains, then? I'll assume yes for now.

**Comment by neynah** [comment]
Yes. I think the labeling is distracting especially since there is no relevant data displayed in the columns. Thanks for clarifying, I should have specified. :)

**Comment by paulproteus** [comment]
Is it OK if I remove the gray header? Turns out that's easier than blanking
out the labels.​

**Comment by neynah** [comment]
Yes, I think that's OK as long as the white box is still the same width (to give the impression that there will be some sort of table/list here once you have grains).

**Comment by neynah** [comment]
Question mark icon PR: #2064

**Comment by paulproteus** [comment]
@neynah you have chosen new text for this. Do you want me to copy your new text, or would you prefer we go with the text in the Etherpad, which is:

> Every document, chat room, mail box, notebook, blog, and everything else you create is a grain. Grains are private until they are shared.

I prefer the text in the Etherpad, but I'll use whatever you request.

**Comment by paulproteus** [comment]
Also arguably the text should be:

> Each document, chat room, mail box, notebook, blog, and everything else you create is a grain. Grains are private until they are shared.

Each creates a singular noun, and grain is a singular noun, so I guess that's arguably better.

**Comment by neynah** [comment]
I prefer "grain is..." over "...is grain" because it's easier to process but I'll leave it up to you.

**Comment by paulproteus** [comment]
I'll close this for now and move the finest-grained discussion of details to #2084. Thanks @neynah !
