### ISSUE TITLE
On /grains, show a (?), and when clicked, show a speech bubble containing information about what a grain is

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2046]
Proposed text: "Every document, chat room, mail box, notebook, blog, and everything else you create is a grain. Grains are private until they are shared."

- [x] Asheesh will make this work at _all_
- [x] Asheesh will wait on #2045
- [x] Asheesh will adjust the implementation to correspond to the mockup

**Comment by neynah** [comment]
Mock-ups also show proposed text change "You don't have any grains yet..." for when there are 0 grains.

![grains1](https://cloud.githubusercontent.com/assets/855341/15914559/ce31e3de-2d96-11e6-8f75-9130c8a23a0a.png)
![grains2](https://cloud.githubusercontent.com/assets/855341/15914563/d0ff029a-2d96-11e6-911f-b601ffc2b0ef.png)
![grains-hover](https://cloud.githubusercontent.com/assets/855341/15914722/25695b18-2d98-11e6-8b9f-3d110cf7aada.png)
