### ISSUE TITLE
Make a mockup for contextual info on /apps

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2047]
This issue tracks the creation of a mockup of what users see when you have 0 apps installed.

Relevant info:

- Proposed text: "Welcome to your workspace. Get started by installing an app from the App Market, all made secure by Sandstorm." or "Welcome! Create spreadsheets, documents, and more. Get started by installing an app from the App Market, secured by Sandstorm."

- Need mockup on desktop & mobile

- We would only show this if the user has 0 apps.

**Comment by paulproteus** [comment]
I just edited this b/c I accidentally hit submit too early.

**Comment by neynah** [comment]
First draft. Assume similar styling to existing intro.js (including the font-size), however let's not dim the background or emphasize the button.
![apps-welcome1](https://cloud.githubusercontent.com/assets/855341/15912622/49b4c182-2d8a-11e6-8bc3-6c889a52f796.png)

**Comment by paulproteus** [comment]
I want to brainstorm alternatives to this sentence a little more:

- "Get started by installing an app from the App Market, secured by Sandstorm."

I know I wrote it, but I don't love the way "secured by Sandstorm" shows up at the end. Maybe:

> Welcome!
>
> Create spreadsheets, documents, and more in this private space.
>
> Get started by installing an app from the App Market.
> "Got it"

Arguably if we're _really_ good at this, we can solve the problem that sysadmins think that this is global across the server. So maybe instead:


> Welcome!
>
> Create spreadsheets, documents, and more in your own private space.
>
> Get started by installing an app from the App Market.
> "Got it"

or

> Welcome!
>
> Create spreadsheets, documents, and more in your own private workspace.
>
> Get started by installing an app from the App Market.
> "Got it"

I'll work on the code behind this now, anyway.

**Comment by paulproteus** [comment]
UX question: Is it OK if, when this hint is visible, only the `+` of install is clickable? FWIW that is vastly easier for me to implement.

Also I took some liberties with the text, and it looks like this now:

![screenshot from 2016-06-14 17 48 56](https://cloud.githubusercontent.com/assets/25457/16064696/56b0c78c-3258-11e6-9e7a-dc7b3a482325.png)

**Comment by neynah** [comment]
Unfortunately, the entire button should be a click target. Could we possibly make an SVG with the plus sign and a white background square to make the click target larger? :(

**Comment by paulproteus** [comment]
D'oh - I mean the entire square is the click target, yes, anywhere there works. So I think that we have what you want, in the way that you're expressing.

But if you click on "Upload app..." the first click dismisses the hint, and the second click starts the upload-app process.

**Comment by neynah** [comment]
Ahh, I see. Maybe we should darken the background a slight touch then. But I'm OK with that change happening later rather than now. :)

**Comment by paulproteus** [comment]
OK! I think it's sensible to close this mockup-issue as a success, then!
