### ISSUE TITLE
Add intro.js guided-tour highlight when user is on their first grain, to teach renaming & sharing

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2049]
While the grain loads, display an intro.js modal guided-tour thing that says:

> Congrats on your first grain! You can rename it and share it with others.
> (Thanks!)

The word "Thanks!" would be a button the user clicks to dismiss this guided tour modal.

Implementation notes:

- Probably skip on mobile. @neynah are you OK with that?

To implement this without using any server-side storage, some ideas.

- We can store in e.g. the Meteor.Session when the user sees the intro.js box on /apps/{{appId}}.
- If the user saw that during this session, at a time when they had 0 grains, then store a note-to-self in the Meteor.Session saying that the first time we see a grain window, show this guided-tour popup thing.

No mockup needed, I believe!

I will also submit a screenshot as part of a PR that claims to fix this, and probably deploy a test build somewhere so people can play with it.

**Comment by neynah** [comment]
Yeah let's skip on mobile for now. There are many things we need to fix on mobile from the ground up! :)

**Comment by kentonv** [comment]
Saying "congrats" feels cheesy to me, but highlighting the top bar and letting the user know what they can do with it seems like a good idea.

**Comment by neynah** [comment]
It's important to provide some sort of feedback to indicate that they've accomplished the tour. Maybe it's OK to leave out congrats since the (Thanks) button sufficiently indicates that they're done.

How about:

"You've created your first grain! You can rename it and share it with others. (Thanks)"
