### ISSUE TITLE
`spk pack` fails with error: "Struct has no field named 'alwaysInclude'"

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#205]
With the latest version of Sandstorm built with the new Ekam setup, `spk pack` fails this error:
```
*** Uncaught exception ***
sandstorm-pkgdef.capnp:53: failed: Struct has no field named 'alwaysInclude'.
```

If I comment out the `alwaysInclude` and `bridgeConfig` fields in my `sandstorm-pkgdef.capnp`, I instead get this error:
```
*** Uncaught exception ***
/ekam-provider/canonical/capnp/compiler/compiler.c++:804: failed: Dependency ID not present in compiler?; depId = 15964277956980293782
```

**Comment by kentonv** [comment]
Side-effect of making spk be an alternate personality of the sandstorm binary: it was trying to find `.capnp` files relative to the binary location. Fixed now.
