### ISSUE TITLE
Improve Oasis splash page

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2050]
Current problems with the Oasis splash page:
- It doesn't make clear-enough what Sandstorm is.
- It doesn't make clear-enough how Sandstorm helps people get things done.

@neynah was interested in proposing some changes.

Technical notes:
- https://docs.sandstorm.io/en/latest/administering/faq/#can-i-customize-the-root-page-of-my-sandstorm-install provides docs on how to modify one's own splash page. Nena I suspect this will be useful to you w/r/t proposing splash page changes by making changes at nenadev.sandcats.io first.

**Comment by neynah** [comment]
Probably won't get to the design part for at least a couple weeks but it'd be good to start brainstorming strings. 1st suggestion, largely based on copy from our front-page:

"Sandstorm is an open source operating system for personal and private clouds.

- Create Google-Docs-like spreadsheets, documents, forms, and more.
- Share documents, diagrams, and other files with others and collaborate in real-time.
- Communicate with others securely using great chat applications like Rocket.Chat.

Sign in to install any app from the Sandstorm App Market."

**Comment by ocdtrekkie** [comment]
The current splash page is pretty good, and Oasis is shutting down. Not really a Blackrock code issue, so I'm closing it.
