### ISSUE TITLE
runit compatibility: start flag for not forking

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/sandstorm#2058]
[runit](http://smarden.org/runit/) likes the processes it manages to stay in the foreground. So it'd be cool if sandstorm did that, so I could easily write a runit service for sandstorm.

If this is uncontroversial, I'll happily submit a pull request adding a --foreground flag to start.

**Comment by paulproteus** [comment]
@kentonv I think you're authoritative about the question of if we'd accept this patch.

**Comment by kentonv** [comment]
Sure, seems reasonable.

**Comment by mrdomino** [comment]
Just getting back to this. The `unshare(CLONE_NEWPID)` makes this sorta nontrivial. I guess I'd keep everything as-is but have the parent process wait on the child instead of exiting, but when I do that in the obvious way, I get weird behavior -- it seems like some Sandstorm processes don't start up until I kill the parent. I'll keep looking at it.

**Comment by kentonv** [comment]
@mrdomino Probably because of the locking that happens on `pidfile`. The parent locks it before forking, and then the child also tries to lock it. The parent normally releases its lock by exiting. You'll need to explicitly release the lock instead, I suppose.

**Comment by mrdomino** [comment]
I no longer think this is worth it. Afaict if you wanted termination of the parent process to cause the tree to die, you'd have to use another lock file. (Or atexit but then I believe weird things will happen when the parent dies weirdly.)

The simple solution of polling the pid file from a run script and adding a "sandstorm stop" to a finish script suffices for runit, and I'll put that up at some point.

**Comment by mrdomino** [comment]
FYI, runit script is here: https://github.com/mrdomino/runit-sandstorm
