### ISSUE TITLE
"Install this app?" question provides no information to help the user chose

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#206]
Steps to reproduce:

1. Visit https://sandstorm.io/apps/
2. Select local.sandstorm.io:6080 and choose an app
3. Watch the progress bar as your computer successfully downloads the app
4. See this question: "Install this app?"

Expected results:

* In the final step, if it's going to ask you a question, it should give you enough information so you can answer the question.

Actual results:

* In the final step, the user sees no information to inform a decision of clicking yes or no.

Proposal:

* Change the text to say, "You're about to install ${APP_NAME}. If that's what you want, click the big green "Continue" button. Otherwise, click the "Go back" link next to it." (And adjust the buttons accordingly.)

Screenshot for amusement:

![install-this-app](https://cloud.githubusercontent.com/assets/25457/5864761/4a1dfaea-a239-11e4-9fb9-27830d618131.png)

**Comment by ocdtrekkie** [comment]
Duplicate of #15

**Comment by paulproteus** [comment]
Agreed. I'm closing this in favor of #15! Thanks @ocdtrekkie
