### ISSUE TITLE
"Confirm your profile" UI looks congested

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2065]
1. The current width causes too many line-breaks in the text and makes the text more difficult to scan.

2. There's an overload of information on this page. Perhaps we can make adjustments to a few of the strings to reduce their length and improve/maintain the same level of comprehension.

3. Sections are pretty close together; some padding adjustments would help.

1st draft with the same copy to begin with (I'll update the mock-up to include the bottom items as well):

![image](https://cloud.githubusercontent.com/assets/855341/15917610/3f270c7e-2db3-11e6-9912-5eef91fa18ab.png)

**Comment by zarvox** [comment]
For consistency, we should probably put the Continue button to the right of the Cancel button - the majority of our forms put the default option at the edge, and stack other buttons next to that button.

Perhaps we can reduce the amount of copy explaining handles.

**Comment by neynah** [comment]
Yeah I agree, we should move the "Continue" button to the right.

This text seems like too much cognitive overload in this context: "This is only your first choice; an app may make you rename if someone has already taken the name within the specific grain".

Perhaps we should replace all the handle text with: "To be displayed in apps that use handles. Your handle must start with a letter and contain only lower-case letters, digits, and underscores."

**Comment by zarvox** [comment]
Additional proposals:

* Rename "Avatar" to "Profile picture".  It's a fairly technical word, and I think "profile picture" communicates the purpose equally clearly.
* Stop giving the avatar an entire column, and instead make it the first of the rows in the form.  This allows the rows to be wider, likely without requiring additional vertical space.  (This also reduces the number of vertical lines on the overall grid, which helps reduce the feeling of clutter.)
* Consider incorporating suggestions from #2112 on how we might nudge people to merge accounts, if it's likely that they accidentally logged in with a different identity than one they used previously.

**Comment by neynah** [comment]
>Rename "Avatar" to "Profile picture". It's a fairly technical word, and I think "profile picture" communicates the purpose equally clearly.

Yeah, I think "Profile picture" > "Avatar".

>Stop giving the avatar an entire column, and instead make it the first of the rows in the form. This allows the rows to be wider, likely without requiring additional vertical space. (This also reduces the number of vertical lines on the overall grid, which helps reduce the feeling of clutter.)

I think it's especially congested since the profile picture has a separate column so +1 on removing that column.

>Consider incorporating suggestions from #2112 on how we might nudge people to merge accounts, if it's likely that they accidentally logged in with a different identity than one they used previously.

Interesting, so we can display other identities we think they own here & ask them to merge? I assume the information we display will be those identity cards.

**Comment by zarvox** [comment]
> Interesting, so we can display other identities we think they own here & ask them to merge? I assume the information we display will be those identity cards.

I'm still in the ideation phase, and we should probably have a discussion with @kentonv of exactly what information we can show under what circumstances to balance usability against risk of unintended information disclosure.  If two identities share a verified email address, I think that's reasonably strong evidence that the user knows about both of them and we should offer the option of linking them.  We can additionally consider storing information about successful identity logins in the browser's localStorage as a "related accounts" source.  In all cases, we'd need to require that you reauthenticate with the other account you're trying to merge.

I'd also be okay with other options:

* Offering a "wait, I think I already have a different account" button which lets users self-direct toward merging their account with another when they accidentally log in with e.g. a different email than one they used in the past, as @pgrm suggested in #2112.
* Showing an additional step in this new-user-onboarding flow, if we believe you have likely-to-be-the-same accounts (via sharing verified email addresses, or localStorage, or anything else we consider sufficiently helpful and non-privacy-leaking).  Copy might be something like "Sandstorm has detected the following accounts that might be related to this account.  Would you like to merge these accounts into this one?" followed by a list of accounts and "Merge" or "Keep separate" buttons.  Clicking on "Merge" would start the appropriate login flow to merge in that account/identity, and "Keep separate" would hide it from the list.
* Showing a similar thing as the above on the /accounts page.

**Comment by kpreid** [comment]
Kibitzing: This (setting up user information that is socially helpful but not necessary to use the service, and avoiding/fixing accidental multiple accounts) is a thing that [Stack Exchange](http://stackexchange.com/) has dealt with a lot. It might be worth studying their choices.
