### ISSUE TITLE
If user has HTTPS_PORT=443, but they stop using sandcats, they will experience redirect sadness

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2070]

**Comment by ocdtrekkie** [comment]
I am closing this as I don't feel it adequately reflects the appropriate state of Sandstorm. Sandstorm's built-in HTTPS now supports other certificates, both of the manually-uploaded and auto-renewing variety. Using HTTPS_PORT without SANDCATS_BASE_DOMAIN is now a viable scenario, though as mentioned in #3313, we need some better tooling around getting HTTPS certs entered when HTTPS certs are in a sad state.
