### ISSUE TITLE
Google configuration instructions don't match Google API Credentials UI

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2074]
Instruction 4 misses a step where the user needs to select OAuth Client ID.

This should be the updated string:
"4. On the left sidebar, go to "Credentials". Press the "Create credentials" button, select "OAuth Client ID", then select "Web application" as the type."

![image](https://cloud.githubusercontent.com/assets/855341/15979063/a852a49c-2f16-11e6-86d5-96e438bd752c.png)
![image](https://cloud.githubusercontent.com/assets/855341/15979081/c4891ad8-2f16-11e6-98ca-fda44b52153e.png)

**Comment by paulproteus** [comment]
Any chance you would submit a PR for this? : )​

**Comment by neynah** [comment]
@zarvox volunteered to fix it but I could as well. I'll assume he's going to fix it until he tells me otherwise. :)

**Comment by ocdtrekkie** [comment]
Didn't I just fix this thing? :/

**Comment by neynah** [comment]
@ocdtrekkie This screenshot is from today. Would you mind testing/checking it again?

**Comment by ocdtrekkie** [comment]
I have no problem looking tonight because I can send the update to meteor too.

**Comment by zarvox** [comment]
Awesome, I'm thrilled to leave this one in @ocdtrekkie's capable hands. :)

**Comment by ocdtrekkie** [comment]
Fixes also submitted to Meteor as https://github.com/meteor/meteor/pull/7203

**Comment by zarvox** [comment]
@ocdtrekkie Thanks for the fix!
