### ISSUE TITLE
Automatically update apps

### ISSUE THREAD

**Issue by dutt** [sandstorm-io/sandstorm#208]
To make it easy to maintain a sandbox installation automatic update of the framework and applications is needed.

**Comment by JamborJan** [comment]
Are you talking about sandstorm itself, or the apps?

Sandstorm has automatic update feature. 

But from a system stability aspect its a wIdee question: what are you doing with your Linux OS, what's with the apps? How are you testing? 

So now where the whole project is in development mode auto updates are handy but as soon as I have a stable platform I don't want an auto update to destroy my stability.

**Comment by ocdtrekkie** [comment]
Yeah, Sandstorm, the framework, already can update automatically. There should be an option to automatically update apps from the app store as well eventually, but it's not quite that far along yet. (As the "app store" does not yet really exist.)

**Comment by dutt** [comment]
Ah, if it's already in the framework and planned for the store you can close this issue.

**Comment by dwrensha** [comment]
App autoupdates are an important missing feature. I think it makes sense to keep this issue open so that those interested can track our progress on it.

**Comment by kentonv** [comment]
Yeah, this will come with the app store, which is being worked on, but I agree we should leave the issue open as a reminder.

**Comment by zarvox** [comment]
As of v0.119, Sandstorm notifies you when app updates are available by checking the app market index.  I think we can close this as fixed!
