### ISSUE TITLE
install.sh: Reports bad file descriptor, when instead it should exit with a kernel-version-too-old error message

### ISSUE THREAD

**Issue by Zottelchen** [sandstorm-io/sandstorm#2081]
When I try to install sandstorm on a fresh debian 8 system it just shows:

```
install.sh: line 195: read: 3: invalid file descriptor: Bad file descriptor
install.sh: line 196: VALUE: unbound variable
*** Please answer "yes" or "no".
install.sh: line 192: 3: Bad file descriptor
install.sh: line 193: 3: Bad file descriptor
install.sh: line 194: 3: Bad file descriptor
```

over and over and over...

**Comment by paulproteus** [comment]
Hi @Zottelchen !

Thanks for writing. This is a new error, I think, and it's a really important one that we fix, so thank you very much for submitting the issue report!

If you download this version of the install script, e.g. by doing:

```bash
curl https://raw.githubusercontent.com/sandstorm-io/sandstorm/v0.148/install.sh > install.sh
bash install.sh
```

does the problem go away?

Also, what service provider are you using for the Debian 8 system?

Thanks so much. It'll be really good if we can get to the bottom of this.

**Comment by Zottelchen** [comment]
@paulproteus Thank you for your help on this issue.

With this version I get another error:
```
Detected Linux kernel version: 2.6.32-042stab113.11
*** INSTALLATION FAILED ***

Sorry, your kernel is too old to run Sandstorm. We require kernel version 3.13
or newer.
```

It is a vServer from BladeTec.de (a cheap german provider but they are having some internal problems right now).

```
$ inxi -v7 -c12
System:    Host: vserver Kernel: 2.6.32-042stab113.11 x86_64 (64 bit gcc: 4.4.6)
           Console: tty 0 Distro: Debian GNU/Linux 8
Machine:   No /sys/class/dmi machine data: try newer kernel, or install dmidecode
CPU:       Quad core Intel Xeon X5675 (-HT-MCP-) cache: 12288 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 24533
           Clock Speeds: 1: 3066 MHz 2: 3066 MHz 3: 3066 MHz 4: 3066 MHz
Graphics:  Card: Failed to Detect Video Card!
           Display Server: N/A driver: N/A
           tty size: 80x24 Advanced Data: N/A for root out of X
Network:   Card: Failed to Detect Network Card!
           WAN IP: 37.114.60.148 IF: venet0 ip: 37.114.60.148 ip-v6: N/A
Drives:    Optical: No optical drives detected.
Partition: ID-1: / size: 60G used: 128K (1%) fs: simfs dev: /dev/simfs
           label: N/A uuid: N/A
RAID:      No RAID data: /proc/mdstat missing-is md_mod kernel module loaded?
Unmounted: No unmounted partitions detected
Sensors:   None detected - is lm-sensors installed and configured?
Info:      Processes: 32 Uptime: 11:39 Memory: 72.5/4096.0MB
           Init: systemd v: 215 runlevel: 3 Gcc sys: 4.9.2
           Client: Shell (bash 4.3.301 running in tty 0) inxi: 2.1.28
```

**Comment by Zottelchen** [comment]
Nevermind that. The VPS is using OpenVZ, which means I can't use my own kernel.

**Comment by paulproteus** [comment]
Hi @Zottelchen !

It looks like if you choose a "RootBlade" from the same provider, you would be able to use KVM, and therefore get whatever kernel you want.

I'll also see if I can diagnose this specific issue so that the install script can avoid crashing.

**Comment by paulproteus** [comment]
FWIW, I got myself an account there, and will attempt to debug this in the fullness of time.

**Comment by paulproteus** [comment]
Thanks greatly @Zottelchen for reporting this! I was able to root-cause the issue and fix it. I really appreciate your willingness to share the issue with us.
