### ISSUE TITLE
Things to fix in end-user onboarding so far

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2102]
- [x] The question mark is not in a circle anymore. Wonder what's up with that.

- [x] Need to fix the grain-view question mark on mobile.

- [x] Bring back the top table header on the app details page, and leave the top table header absent on the grains page.

- [x] zarvox reports that the tests fail.

**Comment by paulproteus** [comment]
- Bring back the top table header on the app details page, and leave the top table header absent on the grains page.

**Comment by paulproteus** [comment]
- @zarvox reports that the tests fail, so I should look into that.

**Comment by zarvox** [comment]
specifically: https://github.com/sandstorm-io/sandstorm/pull/2103 failed, I think: https://build.sandstorm.io/job/Sandstorm%20PRs%20-%20build/587/

**Comment by paulproteus** [comment]
The question mark is in a circle now.

I'm going to call this done.

**Comment by neynah** [comment]
Great, thank you @paulproteus
