### ISSUE TITLE
When a grain is deleted, we should delete any capabilities that it owned

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#2117]
Example:

1. Create a sandstorm-test-python grain
2. Grant it an `IpNetwork` capability
3. Trash the grain, then remove it from your trash.

There is now an entry in the `ApiTokens` collection with a `owner.grain.grainId` value that refers to a grain that no longer exists in the `Grains` collection.

We should probably remove any such tokens when we destroy the grain.  We should also consider making a migration to remove any tokens with an `owner.grain.grainId` which is not in the Grains collection.

**Comment by dwrensha** [comment]
This is implemented (but not the migration) as part of #2027. I could split it into its own pull request if that seems appropriate.

**Comment by zarvox** [comment]
No rush, IMO.  I just discovered that the admin caps UI broke when such an apitoken existed, but #2118 works around that issue, so I'm happy letting that go in at its own pace.

I'm happy to hear the root cause is already fixed in #2027 though! :)

**Comment by dwrensha** [comment]
Fixed in #2027.
