### ISSUE TITLE
My account UI(mobile) gets cut off

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2122]
We should adjust the layout for small screens. Also, it seems that some buttons towards the bottom of the page are misaligned because they don't fit. I'll mock up improvements for the top half of the page to start.

Current screenshot (Nexus 5X):
![image](https://cloud.githubusercontent.com/assets/855341/16214343/0f085572-370c-11e6-9e42-c26e867264e7.png)

**Comment by neynah** [comment]
This adjusted layout is for mobile only.
- Left & right padding for page are consistent
- Profile editing section fits in screen now
- Identities UI elements should stack to fit in a mobile view.
- Less padding allows for buttons to be inline with text
- "primary email address for service-related notifications" & "add new email address" will take up full width of screen
- Payment methods column titles are left-aligned
(Happy to provide more details for implementation)

![2122-mobileui](https://cloud.githubusercontent.com/assets/855341/17422160/44fee6c0-5a64-11e6-910c-a94dadfebed4.png)

**Comment by zarvox** [comment]
One issue I forsee with this is that if you have multiple identities, it's a bit hard to discern:

1. that you can edit them separately
2. which one you are currently editing

In the desktop view, this is supposedly solved by having the actively-displayed card connect to the rest of the editor pane.  (I personally find this very subtle.)  This mobile view doesn't seem to have such a hint.

Any way we can make that clearer?

**Comment by neynah** [comment]
Sounds like we should style the "editing" vs "not-editing" identity cards differently. Maybe a light grey/purple border around the identity card of the identity being edited is sufficient. I will think about this more.
