### ISSUE TITLE
Guided tour(mobile): "create new grain" text box blocks the "create new grain" button

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2124]
Currently blocks the action it's asking you to take. Would be great if this displayed just below the "create new grain" button instead.

![image](https://cloud.githubusercontent.com/assets/855341/16214421/df696a80-370c-11e6-9952-8e9b576503ee.png)

**Comment by paulproteus** [comment]
Eek. Let me see.
