### ISSUE TITLE
Referral program(mobile) styling tweaks

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2125]
"Get up to 30GB..." text is too compressed on small screens. We should reduce the padding on smaller screens (scale using percentages).

Images are too small. They should take up a larger portion of the screen width on smaller screens.

![image](https://cloud.githubusercontent.com/assets/855341/16214520/f142b4fe-370d-11e6-8707-ee347485cd9d.png)

**Comment by paulproteus** [comment]
Self-assigning now to see if I can investigate and/or fix.
