### ISSUE TITLE
Splash page link on self-hosted should be configurable

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#213]
Currently when you visit a Sandstorm server and are logged out or otherwise don't have permission to install apps, you see the splash page with text saying that you need to join the Sandstorm mailing list for an invite.

For self-hosted instances, this is totally wrong. The server's admin is the one that can send invites. It somehow hadn't occurred to me before, but this text actually looks pretty bad because it implies that you need permission from us for self-hosted servers.

We should make this configurable. A simple config file option specifying HTML to inject should be good, with a default along the lines of: "Contact the server admin for an invite."

**Comment by kentonv** [comment]
Also we should then configure our own text to direct people to the preorder page rather than the mailing list.

**Comment by kentonv** [comment]
#204 is not the same thing but probably makes sense to fix at the same time.

**Comment by kentonv** [comment]
Maybe I shouldn't assign @paulproteus since this would be a great one for a community member (in that it's pretty straightforward)?

**Comment by ocdtrekkie** [comment]
As the amount of text visible in the Sandstorm front end is likely to increase over time, and may be localized, it would be worthwhile to put such configuration in a completely separate file to other configuration options.

**Comment by kentonv** [comment]
Of course, we should really have an admin page where admins can edit this stuff through the UI, rather than use the .conf file. :)

**Comment by kentonv** [comment]
In #241 (closing as duplicate), Jake pointed out that this text should also be configurable: "You've been invited to join the Sandstorm alpha!"
