### ISSUE TITLE
In mobile view, users can't switch between grains

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2134]
I imagine we'll want to make other fixes(#2126, etc.) to the nav menu first but some form of grain switching is important for navigation as well. 

![image](https://cloud.githubusercontent.com/assets/855341/16286186/aba92292-388f-11e6-9166-25267d1bb638.png)

**Comment by dwrensha** [comment]
Fixed by #2311.

**Comment by zarvox** [comment]
Well, mostly.  If you have more things than fit on the screen at once, you still can't scroll the list in the mobile view.
