### ISSUE TITLE
Apps & grains(mobile): search box displays oddly in the top right

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2139]
Current screenshots (nexus 5x):
![image](https://cloud.githubusercontent.com/assets/855341/16318914/ebffdb9a-3945-11e6-870b-bfb5d776aa54.png)

Suggested tweaks:
- move search box to display consistently beneath page title
- extend search box to fill full width of space available
- move "upload app" and "uninstall" buttons to the top right (this change is also consistent with (non-mobile) changes @zarvox and I have been discussing; to move the buttons to the top right aligned with the page title).

![image](https://cloud.githubusercontent.com/assets/855341/16319040/72b54814-3946-11e6-844e-5a01d58cc265.png)

**Comment by zarvox** [comment]
Additional suggested change to gain consistency with the admin routes: a horizontal rule just below the top-level heading text (1px solid #a2a2a2 is what the admin routes use).

On the "Apps" page, the "upload app" and "uninstall" buttons would sit above this rule.
