### ISSUE TITLE
Ist not possible to scroll / move in mobile view

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#215]
Tested with iOS8 on iPhone 5s

No matter which app / grain is opened its not possible to scroll or move the page.

E.g. GitLab has a mobile view but it's not possible to scroll down. In other apps with no mobile view like ethercalc it's not possible to move the sheet in any direction.

**Comment by dwrensha** [comment]
Ugh. I'm seeing this too on Safari on iOS8.

I tried changing our CSS [here](https://github.com/sandstorm-io/sandstorm/blob/e71362d6543c7ce1ed5ce3f2b6549218c3dbca0f/shell/client/shell.css#L228) to this:
```
#app.main-content {
   overflow: auto;
   -webkit-overflow-scrolling:touch;
}
```
and that made scrolling seem to at least partially work. But GitLab's infinite scrolling is still broken after this change; it fails to load more content when you reach the bottom.

Maybe someone who knows more about CSS than I do can help here?

**Comment by kentonv** [comment]
We need to do a lot more work on mobile, but I'm in favor of any small changes that help even if they don't fix everything.

(I don't know much about mobile CSS, personally.)

**Comment by JamborJan** [comment]
I do some tests and send a PR when I find a proper solution.

**Comment by JamborJan** [comment]
I'm still struggeling with my build server so I cannot test with that.

Is it possible to change the CSS on my server without doing the build process?

I had an issue in the past on mobile devices where ```cursor: pointer;``` helped e.g. when labels where not click-able etc. maybe that helps here too. Would test it if I'm able to get the stuff running.

**Comment by kentonv** [comment]
Unfortunately it's pretty impossible to change the CSS without rebuilding the whole shell (or running it in dev mode). But it sounds like you've got the build working now. :)

**Comment by JamborJan** [comment]
Yes, build is okay now. Will do the CSS stuff and tests tomorrow and let you know the results.

**Comment by JamborJan** [comment]
Found a solution with:

```
#app.main-content {
  overflow: hidden;
  -webkit-overflow-scrolling:touch;
  overflow-y: scroll;
  overflow-x: scroll;
}
```

It fixes the total in-usability on mobile for now but a general overhaul of the mobile experience might be required.
