### ISSUE TITLE
sandstorm-http-bridge should support ETags in the case of 204 responses

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#2160]
Setting ETags on a 204 response can be useful in [certain situations](http://fideloper.com/etags-and-optimistic-concurrency-control).

Currently, when the app's http server gives us a 204 we [always](https://github.com/sandstorm-io/sandstorm/blob/432be37489b210b19d9677f29befcd5c910a0f76/src/sandstorm/sandstorm-http-bridge.c%2B%2B#L337) return the [`Response.noContent`](https://github.com/sandstorm-io/sandstorm/blob/v0.169/src/sandstorm/web-session.capnp#L308-L314) variant, which does not allow ETags to be set. 

Perhaps sandstorm-http-bridge should, in the 204 case, check to see if any etags are present, and if so then use the `Response.content` variant with [`content.statusCode`](https://github.com/sandstorm-io/sandstorm/blob/v0.169/src/sandstorm/web-session.capnp#L283) set to 204.

**Comment by kentonv** [comment]
I think the right thing to do here is to add an `eTag` field to `noContent`.

It's actually a mistake that the `SuccessCode` enum includes 204 -- this means it's possible to represent a response that has status 204 but actually has a body. The Cap'n Proto representation of HTTP is intended to make it hard to represent invalid responses. In practice I believe we never use `SuccessCode.noContent` today, so perhaps we should deprecate it.

**Comment by koivunej** [comment]
If I am the only one at the moment blocked by this I'd like to take a shot at solving this.

**Comment by dwrensha** [comment]
@koivunej: Go for it! It looks like there are at least three places that would need to be updated: [web-session.capnp](
https://github.com/sandstorm-io/sandstorm/blob/v0.170/src/sandstorm/web-session.capnp#L308-L314), [proxy.js](https://github.com/sandstorm-io/sandstorm/blob/v0.170/shell/server/proxy.js#L1632-L1636), and [sandstorm-http-bridge.c++](https://github.com/sandstorm-io/sandstorm/blob/v0.170/src/sandstorm/sandstorm-http-bridge.c%2B%2B#L351-L355).
