### ISSUE TITLE
"share access" guided tour masks the button it is highlighting on firefox

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2163]
![screenshot from 2016-07-01 11-51-52](https://cloud.githubusercontent.com/assets/4001805/16531652/537983a6-3f82-11e6-9949-6d9acc9828a6.png)

**Comment by paulproteus** [comment]
Thanks @kentonv for reporting. I was able to reproduce this, and probably other browsers have a similar issue, like desktop Safari.
