### ISSUE TITLE
Let admins delete users

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2166]
Example use case: The admin created a test user account to experiment, but now that test user shows up in sharing auto-completes (due to Sandstorm for Work autocomplete-all-in-org) and on the admin user list.

Deleting a user (account) should:

* Delete all the account's grains.
* Delete all identities associated with the account that aren't associated with other accounts.
* If BlackrockPayments is present, unsubscribe from all plans and delete the Stripe customer data.

The UI should make clear that the user account will be recreated if the user logs in again, and that to prevent this the admin would need to disallow visitors (Sandstorm for Work feature).

It may make sense to implement #1684 (allowing a user to delete their own account) at the same time as this.

**Comment by ocdtrekkie** [comment]
What might be a nice option, would be if you could provide some sort of pending deletion notice and countdown feature. So admins could set like a two week deletion option, and the user would be notified the account will be deleted at a certain time. So they have time to either remove their stuff or ask the admin not to delete it.

Obviously, a server admin should always have the right to immediately suspend or delete an account (they can access the actual server anyways), but it'd be preferable to have a sort of "user recycle bin" where it can be undone easily, and people can still potentially retrieve their files.

**Comment by kentonv** [comment]
@ocdtrekkie Interesting thought although probably more than we will have time to implement in the short term. :/

**Comment by ocdtrekkie** [comment]
My concern is that admins don't have a lot of visibility into accounts, so instant permanent deletion is probably not the best default mode for admins to delete accounts.

**Comment by ndarilek** [comment]
Nice. I'd also like the ability to do something other than delete grains. Maybe send them all to the trash of the admin who deleted them, or to some communal trash that all admins have access to. This obviously has privacy implications, so perhaps it should be a configuration option.

I'm planning to roll out Sandstorm for my housing co-op, and my concern is that someone will individually create a grain or app on which our organization comes to depend. Deleting their account is a great way to ensure that their slate with us is wiped more or less clean, but it doesn't take into account whether they've created something on which we rely, which is something Sandstorm encourages but doesn't really support in a safe way. That I can potentially wipe out a critical piece of infrastructure worries me.

As an alternative, I'd accept an option for individual grains to be marked as protected in some way, so deleting the account wouldn't destroy grains that are marked in this way. Or maybe there's some other heuristic to protect a grain, like making it available in a collection.

**Comment by ocdtrekkie** [comment]
Another note, which might cover the "block this user without 'for Work' case as well. How about a "disable/freeze user" option? For the "I don't want to insta-delete their stuff, but this user is causing a problem on our server" option? This would presumably prevent them from doing anything on the server, even if not "for Work", unless they created a new identity.

**Comment by zarvox** [comment]
So, it sounds like there are actually three separate set of requirements here:

1. For Oasis: some users want to deactivate/disable their own accounts, and Kenton wants to not have to take manual action for each of these users.
2. For Sandstorm: admins want to be able to deal with users leaving their human organizations while maintaining business continuity around grains those users may own.
3. For Sandstorm: admins want to be able to temporarily deactivate problematic or compromised accounts.

This issue focuses on requirement 1.  I think https://github.com/sandstorm-io/sandstorm/issues/2078 focuses on requirement 3.  I'm not sure there's a single ticket that focuses on requirement 2, but #988 and #2078 are both related.

My expectation is that it will be fairly trivial to implement requirement 3, somewhat involved to implement requirement 2 (since there's much more UX that needs to be messaged clearly, and audit trails that need to be created), and requirement 1 winds up being entirely orthogonal.

**Comment by ocdtrekkie** [comment]
I didn't notice #2078 was already a thing. \o/

**Comment by kentonv** [comment]
@zarvox FWIW, this issue is *not* focused on Oasis -- in fact, it's based on a request from a user. He had created some test accounts when setting up, and now he is disappointed that they appear  in the sharing auto-complete for everyone in the organization.

**Comment by scrumit** [comment]
Either resolve #1683 or #1736 please.

**Comment by jparyani** [comment]
Fixed by #2402

**Comment by jparyani** [comment]
Opened #2539 to track an issue mentioned in this thread about transferring grain ownership.
