### ISSUE TITLE
/ekam-provider/canonical/sandstorm/run-bundle: No such file or directory

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#217]
I have a new setup debian server with all requirements installed for making sandstorm builds.

The described process of building / installing the binaries is working, at least no errors are shown (some warnings).

I can also run ```make install```. But the sandstorm process dies right after I started it with the following in the log ```/opt/sandstorm/var/log/sandstorm.log```:

```
** Starting Sandstorm at: Tue Jan 27 19:20:13 2015
*** Uncaught exception ***
/ekam-provider/canonical/sandstorm/run-bundle.c++:1246: failed: mount("proc", "proc", "proc", MS_NOSUID | MS_NODEV | MS_NOEXEC, ""): No such file or directory
stack: 0x51a1d1 0x45684a 0x4a3e93 0x4a24b3 0x4a1f8d 0x4ba590 0x4b9749 0x4b973a 0x4596e1 0x45a365 0x51ae7a 0x4578dc 0x499562 0x5e8060 0x401b87
** Server monitor died. Aborting.
```

**Comment by paulproteus** [comment]
Hi @JamborJan ! Glad you're setting up Sandstorm.

I had a vaguely similar problem which went away when I installed Sandstorm as root. So my first question is, did you do so? And if you didn't, can you try with a fresh Sandstorm that is installed as root via the `install.sh` script?

It'd be nice to not _require_ that Sandstorm be installed as root. I hope you can try this so we can see if that makes the problem go away temporarily, and then we can figure out how to make sure Sandstorm properly works when not installed as root.

**Comment by JamborJan** [comment]
Build fails with:

```
Makefile:166: recipe for target 'bundle' failed
make: *** [bundle] Error 1
```
In Makefile at that line:

```
bundle: tmp/.ekam-run shell-build make-bundle.sh
        $(call color,bundle)
        @./make-bundle.sh
```
When running build again (what I did the first time) it runs over that point and so the proc folder and some other stuff is missing in the build.

**Comment by kentonv** [comment]
I've updated `make-bundle.sh` in commit 907747c so that now it will delete the directory on failure (so that `make` again doesn't erroneously succeed) and will indicate the line number of the failure. So if you run it again, it should tell us more precisely what failed.

**Comment by JamborJan** [comment]
Okay, now ```make```ends with:

```
fibers@1.0.1 node_modules/fibers

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)
make-bundle.sh: FAILED at line 135
Makefile:167: recipe for target 'bundle' failed
make: *** [bundle] Error 1
```

**Comment by JamborJan** [comment]
make-bundle.sh line 135:
```
strace tmp/dnstest 2>&1 | grep -o '"/[^"]*"' | tr -d '"' | copyDeps
```

**Comment by JamborJan** [comment]
As I installed the system new I might have missed an dependency. When you write in the requirements
```C and C++ libraries and headers```what would be an appropriate package I find with ```dpkg --get-selections```?

Only to exclude the failure in front of keyboard error.

**Comment by kentonv** [comment]
Ah, you probably need to install `strace`.

(C and C++ libraries and headers are already covered by `build-essential`.)

**Comment by jparyani** [comment]
A tested list of all dependencies that are needed to run sandstorm under Ubuntu 14.04 (but should work under debian testing or unstable) is available in Dockerfile.dev (https://github.com/sandstorm-io/sandstorm/blob/293bf61241bfd8b27da3926f8bfa9ec1e5075e0a/Dockerfile.dev#L34). You can ignore the line `apt-get install default-jre-headless` since we only need it for testing purposes.

**Comment by JamborJan** [comment]
After having installed ```strace``` I was able to run ```make``` again and it was successful.

@kentonv 's fix was working so ```make```didn't assume it was successful at the first try.

After ```make install``` I'm now able to use my own build.

**Comment by kentonv** [comment]
FWIW, I've updated the readme to have a nice copyable apt-get line.

**Comment by JamborJan** [comment]
Nice :-) at least I had something to do tonight and the next guy will have it easier.
