### ISSUE TITLE
"Try app" leads to lots of "actions"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#221]
Steps to reproduce:

* Visit https://demo.sandstorm.io/appdemo/70awyqss6jq2gkz7dwzsnvumzr07256pzdt3hda9acfuxwh6uh7h

* Click the button

* Repeat the above two steps 4 times

Result:

![too-many-actions](https://cloud.githubusercontent.com/assets/25457/5930782/4f61a024-a649-11e4-8aed-ec09fd5a2308.png)

Desired result:

Only one button at the top

**Comment by mquandalle** [comment]
I came here to report the exact same problem :)

**Comment by paulproteus** [comment]
Since this only affects demo users, whose accounts get deleted every hour, maybe I can get away without writing a migration script to remove the bad data.

I'll see if I can write a patch to stop doing this bad behavior.

**Comment by paulproteus** [comment]
Workaround available:

* If you "uninstall" the app, you don't lose your data, but this does delete all your UserActions. So you can uninstall the app, then reinstall it, and you'll now be in good shape.

* For the demo site, demo data gets deleted after an hour, so that should "auto-heal".

@kentonv , apologies for this snafu. Pleas review the pull request linked-to here -- #222 !

**Comment by kentonv** [comment]
Fixed pushed in build 0.64.
