### ISSUE TITLE
Clicking "+ install" on the dashboard reloads the page instead of taking you to the app store

### ISSUE THREAD

**Issue by scottybo** [sandstorm-io/sandstorm#2231]
I've noticed this problem happening in Firefox, both on mobile (Android) and desktop (Linux Mint). Logged into Oasis, brand new account.

When clicking on the big "+" button to install my first app, the website reloads the page, instead of launching the app store.

My environment(s)

**Mobile:**
- Cyanogenmod
- Firefox 47.0

**Desktop:**
- Linux Mint 18
- Firefox 47.0 (v 1.0 of Firefox for Linux Mint)

Addons:
- uBlock Origin
- Clean Links
- Open HTTP Requester
-- Lastpass

**Comment by scottybo** [comment]
Ah - found the culprit, it's the "Clean Links" plugin. Closing this topic, but leaving it just in case this issue happens for anyone else.

**Comment by paulproteus** [comment]
Thanks for asking the question, and thanks especially for sharing the answer!
