### ISSUE TITLE
Admin users page doesn't work on Alpha

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2233]
Probably because of broken DB records. The following is printed in the console, and the UI claim no users exist.

    Exception in template helper: Error: unrecognized identity service: 
    at Function.te.fillInProfileDefaults (https://alpha.sandstorm.io/5f4a3c4ba915149c72efa86720c63f1c875f79e2.js?meteor_js_resource=true:148:29271)
    at https://alpha.sandstorm.io/5f4a3c4ba915149c72efa86720c63f1c875f79e2.js?meteor_js_resource=true:215:19390
    at Array.map (native)
    at https://alpha.sandstorm.io/5f4a3c4ba915149c72efa86720c63f1c875f79e2.js?meteor_js_resource=true:215:19315
    at https://alpha.sandstorm.io/5f4a3c4ba915149c72efa86720c63f1c875f79e2.js?meteor_js_resource=true:42:1838
    at https://alpha.sandstorm.io/5f4a3c4ba915149c72efa86720c63f1c875f79e2.js?meteor_js_resource=true:42:1661
    at Array.forEach (native)
    at Function.A.each.A.forEach (https://alpha.sandstorm.io/5f4a3c4ba915149c72efa86720c63f1c875f79e2.js?meteor_js_resource=true:1:865)
    at h.Cursor.forEach (https://alpha.sandstorm.io/5f4a3c4ba915149c72efa86720c63f1c875f79e2.js?meteor_js_resource=true:42:1583)
    at h.Cursor.map (https://alpha.sandstorm.io/5f4a3c4ba915149c72efa86720c63f1c875f79e2.js?meteor_js_resource=true:42:1807)

**Comment by dwrensha** [comment]
On that server, can you confirm whether there exist entries in the `Users` table that have a `profile` field but don't have a `profile.service` field? If such entries exist, do they look otherwise unusual?

**Comment by kentonv** [comment]
> db.users.find({profile: {$exists: true}, "profile.service": {$exists: false}}).count()
    0

**Comment by jparyani** [comment]
Perhaps try `db.users.distinct("profile.service")`

**Comment by kentonv** [comment]
> db.users.distinct("profile.service")
    [ "github", "google", "email", "undefined" ]

**Comment by kentonv** [comment]
WTF?

    > db.users.find({"profile.service": "undefined"}).pretty()
    {
        "_id" : "<identity id hex>",
        "createdAt" : ISODate("2014-06-20T07:09:32.454Z"),
        "lastActive" : ISODate("2014-06-23T03:06:29.983Z"),
        "profile" : {
            "service" : "undefined"
        },
        "services" : {
            "password" : {
                "srp" : {
                    "identity" : "<some base64>",
                    "salt" : "<some base64>",
                    "verifier" : "<some hex>"
                }
            }
        }
    }

**Comment by kentonv** [comment]
I guess this suggests that at some point a little over two years ago it was possible to create a username/password account on Alpha and one such account was created. I think I vaguely remember @dwrensha worriedly telling me one day that he was seeing a username/password option enabled on Alpha?

**Comment by ocdtrekkie** [comment]
https://github.com/sandstorm-io/sandstorm/commit/5ed3dceb7bb24ea9c1ce1b1b01c8bcf911217256

**Comment by ocdtrekkie** [comment]
Added here: https://github.com/sandstorm-io/sandstorm/commit/d2f527630e9fb6f29e290cf39d1bb3db29b08147

**Comment by kentonv** [comment]
Well, I deleted that user and now it works. I guess I'll close this.
