### ISSUE TITLE
Roundcube & Rocketchat Installation fail with "Package hash did not match"

### ISSUE THREAD

**Issue by TheLux83** [sandstorm-io/sandstorm#2239]
Hey there,

I've installed Sandstorm on 2 of my private vServers and on both I'm not able to install Roundcube or Rocketchat. Though it works with Browserquest, Davros and Tiny Tiny RSS.

The Error message: 
Downloading app: https://app-index.sandstorm.io/packages/22bfa7ff4bb738030a9ab30ce1ae4c7f
Failed to install app: Error: Package hash did not match.
    at AppInstaller.<anonymous> (server/installer.js:356:15)
    at Request.<anonymous> (server/installer.js:237:23)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/programs/server/npm/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)
Downloading app: https://app-index.sandstorm.io/packages/c510c6bd0043c5dc679799690bbf00d4
App ready: c510c6bd0043c5dc679799690bbf00d4
fetching keybase 5C95C99E6952707D22ED65BB18069B0BFD4F67D2
Downloading app: https://app-index.sandstorm.io/packages/3635303df393fa80b1fb4e06f413d3e7
App ready: 3635303df393fa80b1fb4e06f413d3e7
fetching keybase EECEE2789B7897C41B8DB85247A668D5DF5B9D02
fetching keybase EECEE2789B7897C41B8DB85247A668D5DF5B9D02

I know that you had a similar problem back on january. https://github.com/sandstorm-io/sandstorm/issues/1388

If I use one of you Test Instances, I have no problem installing Roundcube.

I use Ubuntu Server 14.04 LTS on both machines and I use your own DNS Server (sandcats.io)

Do you need any more infos?

**Comment by paulproteus** [comment]
Hi @TheLux83 ! Thanks for reporting this. It was a transient issue with our own app hosting service, which we've fixed. I'll close for now, but if you see the issue again, please reopen!
