### ISSUE TITLE
Make some apps be available for all Sandstorm users on first account creation

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2242]
This issue tracks the task of making sure that, when Sandstorm is first installed, the Sandstorm server downloads some apps that are useful and makes them available for users. (By contrast a different issue covers an admin UI to customize it.)

Useful testing to do:

- [ ] Make sure the guided tour doesn't show up if you have apps auto-installed

See also:

- https://github.com/sandstorm-io/sandstorm/issues/2246 'Create visual design for initial admin onboarding flow ("wizard"), to show info about apps that are available to new user accounts'

**Comment by frigginglorious** [comment]
Not just apps auto-installed, but specific grain access as well!

I like the idea of making a list of users by their gmail accts, all with access to grains I create that are specific to that list, that group of people. I would be able to make them guests with only access to the specific grains that I've spun up for them to use.

**Comment by ocdtrekkie** [comment]
@frigginglorious What you're talking about is definitely a different type of request then this. This appears to be the goal that if you sign up on Sandstorm or first get an account, you have like... Etherpad and Davros, which are most likely to be used by pretty much everyone.

What you're looking for can now be solved with Collections! If you invite someone to a Collection by email, and that Collection has the grains you want them to access, when they click that link and log in, they'll have a guest account (which can't install apps or create grains) with access to all of the grains in that Collection. Test version of it is available in the sandstorm-dev mailing list.

**Comment by neynah** [comment]
![img_1886](https://cloud.githubusercontent.com/assets/855341/17003971/606f90a0-4e87-11e6-86e4-dffa6c78b4f9.jpg)

**Comment by paulproteus** [comment]
Since I believe @frigginglorious 's use-case is handled by Collections, per @ocdtrekkie 's remark, I think we'll keep the original scope of this ticket for now. If there's a separate request for a new feature, though, I would be very happy to see a new issue filed!

**Comment by kentonv** [comment]
Implemented in #2287
