### ISSUE TITLE
Create visual design for admin configuration area, for apps that are available to new user accounts

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2245]
This issue tracks the creation of satisfactory visual mockups for https://github.com/sandstorm-io/sandstorm/issues/2247 .

Here's my proposed process.

- @neynah self-assigns this issue.
- This issue gets closed when @kentonv or @jparyani believe we have a visual design that meets all requirements of #2247  and specifies all of the user interactions that need to be specified.

**UPDATED:** I had linked the wrong ticket number in here. Fixed now!

**Comment by neynah** [comment]
Current mock-ups are here: https://oasis.sandstorm.io/shared/XMcEqD8G-Z6YM7nc2nFFLGZ98wlB7ytcsPXS1nw5W4z

**Comment by kentonv** [comment]
Implemented in #2287
