### ISSUE TITLE
Allow admins to choose which apps are already available to new users on their server

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2247]
Requirements:

- Admins should be able to choose which apps within certain categories decided by the Sandstorm team are installed by default for new users, specifically a "Productivity suite" (Davros, Etherpad, Rocket.Chat, Wekan) and "System apps" (Collections).
- If new apps are added to these suites, the admin will receive a notification. (This probably doesn't require any code changes now, but instead requires that we create a notification in the future when we add an app.)
- The admin can also choose any app on the market.
- In v2 (aka not important for this issue), the admin can _also_ choose any app they have uploaded themselves.
- For any servers that existed before this feature existed, when they update to a version of Sandstorm that contains this feature, all server admins should see a notification telling them about this new feature in the Sandstorm admin area.
- Visual design to be decided in https://github.com/sandstorm-io/sandstorm/issues/2245 but a whiteboard sketch is on the left side at https://cloud.githubusercontent.com/assets/855341/17003971/606f90a0-4e87-11e6-86e4-dffa6c78b4f9.jpg . The important aspects are:
    - There are checkboxes within each section ("Productivity suite", "System apps", "All apps on market") for the apps related to that section.
    - We'll repeat apps between "Productivity suite" and "All apps on market". Therefore their checkboxes should be synchronized.
    - Because we never change what apps a user has installed, for users that already exist, we do not need to send any notifications. (This contradicts the information in https://cloud.githubusercontent.com/assets/855341/17003971/606f90a0-4e87-11e6-86e4-dffa6c78b4f9.jpg , but this ticket is authoritative.)

**Comment by kentonv** [comment]
Implemented in #2287
