### ISSUE TITLE
A slightly easier way to do a two-line GPG-verified curl|bash install

### ISSUE THREAD

**Issue by adamierymenko** [sandstorm-io/sandstorm#2248]
From [the ZeroTier download page](https://www.zerotier.com/product-one.shtml):

    curl -s https://raw.githubusercontent.com/zerotier/ZeroTierOne/master/doc/contact%40zerotier.com.gpg | gpg --import

    curl -s https://install.zerotier.com/ | gpg --output - >/tmp/zt-install.sh && bash /tmp/zt-install.sh

This installs the key and then uses a single line to check the cert. Also see the script itself whose [source is here](https://github.com/zerotier/install.zerotier.com). It uses some bash escaping tricks to result in a script that is valid with or without being piped through GPG.

**Comment by zarvox** [comment]
That script appears to download the signing key over HTTPS, then import that key into the GPG keyring.  That is equivalent in terms of trust to fetching the install script itself over HTTPS - any attacker that can break HTTPS can replace the initial public key download with their imposter signing key.  And if you trust HTTPS to deliver the public key unmodified, then you can equivalently trust HTTPS to deliver the script unmodified, in which case you might as well just use the existing install instructions, or a git clone.

**Comment by kentonv** [comment]
Yeah, sorry, this does not add any meaningful security compared to fetching the install script over HTTPS from Github (which is already listed in our docs as "Github-verified install"). This is a common misunderstanding about how PGP key management works.
