### ISSUE TITLE
docs: When user namespaces check fails in install.sh, send user to a web that explains what this is about

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2261]
Context:

- People sometimes say "I want to run Sandstorm on CentOS 7" and then they really mean "CentOS 7 running in an old kernel" and then the details get really fuzzy.
- Frequently the people emailing us are not the people maintaining the kernel version, but instead customers of the companies maintaining the kernel version, so it's useful to put all our info in a web page.

**Comment by Finkregh** [comment]
This is also an issue when you are running a grsec-enabled kernel (as in alpine linux per default)

**Comment by paulproteus** [comment]
Just a small remark: If grsec blocks Sandstorm by default, that is eye-opening and fascinating!

**Comment by kentonv** [comment]
It seems unsurprising to me that grsec would block user namespaces -- for the same reasons we block it inside the sandbox.
