### ISSUE TITLE
Enhance 'Install this app?' dialog

### ISSUE THREAD

**Issue by gemlog** [sandstorm-io/sandstorm#227]
This is very minor. It asks the same question twice without mentioning just which app you are granting permission to install. It should name the app whose name must be in a convenient var at that point. This is more of a quibble than a bug.

**Comment by gemlog** [comment]
dupe, sorry.

**Comment by kentonv** [comment]
No problem, dupes are actually good feedback, in the absence of issue voting.

(For others watching, this is a dupe of #15.)
