### ISSUE TITLE
Failed to get D-Bus connection during install

### ISSUE THREAD

**Issue by jonschoning** [sandstorm-io/sandstorm#228]
Config written to /opt/sandstorm/sandstorm.conf.
	Finding latest build for dev channel...
	Downloading: https://dl.sandstorm.io/sandstorm-64.tar.xz
  	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 	 Dload  Upload   Total   Spent    Left  Speed
	100 17.2M  100 17.2M    0     0  2076k      0  0:00:08  0:00:08 --:--:-- 2059k
	created: /usr/local/bin/spk
	Start sandstorm at system boot? [yes]
	ln -s '/etc/systemd/system/sandstorm.service' '/etc/systemd/system/multi-user.target.wants/sandstorm.service'
	Failed to get D-Bus connection: No connection to service manager.

>

	$ uname -a; lsb_release -a
	Linux penrose77 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
	No LSB modules are available.
	Distributor ID: Ubuntu
	Description:    Ubuntu 14.10
	Release:        14.10
	Codename:       utopic

**Comment by kentonv** [comment]
@zined do you happen to know anything about this? I am still avoiding learning systemd myself. :)

**Comment by keedon** [comment]
Got the same problem (alsoubuntu 14.10)

**Comment by kentonv** [comment]
So, our current check for whether systemd is installed is:

    if [ -d /etc/systemd/system ] && which systemctl > /dev/null

Apparently, this is no good. Googling for better solutions, it seems like most answers are either sketchy or overcomplicated, but perhaps this works:

    if grep -q systemd /proc/1/comm

Any comments? If not I'll go ahead and implement this soon.

**Comment by zined** [comment]
@kentonv i'd say checking `/proc/1/comm` is far superior to checking arbitrary directories for existance, as there could be distributions/packages creating systemd paths for compat reasons. :+1:
