### ISSUE TITLE
sandstorm-http-bridge crashes if ETag header has no quotation marks

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2295]
Context:

- @ocdtrekkie has a Sandstorm app (EtherDraw) that "used to work" with old versions of Sandstorm's sandstorm-http-bridge. With new versions of sandstorm-http-bridge, the app "doesn't work".
- Further review indicates that EtherDraw is sending an `ETag` of `1.0.6` for the `socket.io.js` file, which is invalid per the HTTP RFC. The HTTP RFC specifies that an ETag MUST have a double-quote mark around the actual value, plus an optional `W/` prefix.
- Our code crashes in the case of an invalid ETag; see: https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/sandstorm-http-bridge.c++#L786
- I've reproduced the issue with a PHP script that starts with: `<?php header("ETag: invalid"); ?>`

Options:

We can:

- 1.  Drop ETag data that is invalid, and stop crashing sandstorm-http-bridge. This will result in more HTTP traffic as the browser doesn't know as much about how to cache the data. It would also be undiscoverable for app authors, unless we log it somewhere (perhaps stderr so it appears in the grain log, though if it appears in the grain log, then we're wasting user storage as well).
- 2. Silently upgrade ETag data that lacks quotes into a version with quotes. This also has impact on caching because browsers will send an `If-None-Match` header that the app backend won't understand as the same ETag. See also [this issue in Play Framework](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1522-etags-header-is-not-being-set-in-line-with-specification-standard). We probably should write something to stderr each time we do this from sandstorm-http-bridge asking the packager to fix the app.
- 3. Continue to crash in the face of invalid ETag data.
- 4. Have further discussion.

I'll note that we already have workarounds for other app bugs in sandstorm-http-bridge; consider the parsing of the `Date:` header.  Note also that this is a blocker for @ocdtrekkie reuploading the EtherDraw app.

My plan:

- Implement option 1 above and submit a pull request with it, awaiting review/merge by @kentonv.

**Comment by ocdtrekkie** [comment]
Would the invalid ETag be a EtherDraw issue? Or a socket.io issue?

**Comment by paulproteus** [comment]
I think it's an issue with how EtherDraw configures a HTTP server to serve up static files from its filesystem. It depends where the string `1.0.6` is coming from!

**Comment by ocdtrekkie** [comment]
It seems the version of socket.io my app has is 1.0.6. It also looks like this is an old version. EtherDraw's package.json requests "socket.io": "~1.0.0", but the current release is 1.4.8.

**Comment by paulproteus** [comment]
Yeah, I was figuring it was a socket.io version number. The bug is how the version number gets encoded into an ETag.

My hunch now is that it is indeed a socket.io bug. This line:

`        io.enable('browser client etag');`

in this discussion https://github.com/socketio/socket.io/issues/1542

suggests that socket.io is the one doing it.

**Comment by ocdtrekkie** [comment]
My opinion on the above Sandstorm fix would be that the grain log is the right place for it. It's where people look first, and users tend to predominantly be the ones to report issues with apps. Regarding grain log size, Sandstorm probably needs some way to handle/clean up old grain log data.

**Comment by ocdtrekkie** [comment]
And then I'm wondering if socket.io 1.4.8 has yet fixed this issue, and if socket.io 1.4.8 will work with EtherDraw.

**Comment by paulproteus** [comment]
@ocdtrekkie A build with the workaround/fix is available at https://gfmriy43mmhh2ai3uk0o.oasis.sandstorm.io/sandstorm-0-fast.tar.xz aka https://oasis.sandstorm.io/shared/Y72PzOvmzh8A-gIG7aSjvwQjOVZ4uqFYwXbXSf6d1KC for your pleasure. This should "unstuck" you in terms of building an EtherDraw package.

It's worth figuring out the actual issue, but IMHO it shouldn't be a showstopper.

**Comment by paulproteus** [comment]
See also @kentonv 's proposed patch to socket.io at: https://github.com/socketio/socket.io/pull/2603

**Comment by paulproteus** [comment]
@ocdtrekkie FWIW It _seems_ that if you can place:

```
io.disable('browser client etag');
```

in the right place, you'll stop socket.io from emitting invalid data.

https://github.com/byrichardpowell/draw/blob/a9e7bcca41d2b0b978c1cea50f2b192bef720ad1/app.js#L70 (or a similar place in your fork) looks plausible.

**Comment by dwrensha** [comment]
Indeed, looks like that's how I worked around the problem with sharelatex: https://github.com/dwrensha/real-time-sharelatex/commit/937382c24780893ce76922c58fd5583b50b7187b

**Comment by ocdtrekkie** [comment]
Note the current upstream for EtherDraw is JohnMcLear/draw

Just dropping the io.disable line causes an app crash because there's no disable method.

**Comment by paulproteus** [comment]
*nod*

@ocdtrekkie if you do the 'sudo sandstorm update' trick within the VM where you're doing the packaging, you can ship an updated app market SPK without even waiting for us to release the fixed sandstorm-http-bridge!

**Comment by ocdtrekkie** [comment]
At the point where it's been six months, I'm not in any pressing urgency, I think... I'm also kinda hoping that maybe sockets.io decides to merge that PR, then I can PR the updated sockets.io to EtherDraw and then into the Sandstorm port. But that might be just me dreaming.

**Comment by kentonv** [comment]
@ocdtrekkie I had the same problem with Etherpad itself. I fixed socket.io and I updated Etherpad to use the fixed version as follows:

https://github.com/kentonv/etherpad-lite/commit/b6316e0247b78d86c496667ffe0a8d415c23b2df

Note that I explicitly made a patch on top of 1.3.7 to use there because I found Etherpad no longer worked with the latest version of socket.io and I didn't want to track down why. You could try telling EtherDraw to use my same 1.3.7 branch and see if it works.

**Comment by ocdtrekkie** [comment]
I can't figure out the magic of getting EtherDraw to use your fork. :/
