### ISSUE TITLE
sandstorm doesn't install with umask 077

### ISSUE THREAD

**Issue by sixcorners** [sandstorm-io/sandstorm#2300]
Running the curl | bash install script with a umask set to 077 results in the E_NEVER_LISTENED error.

This was done on Ubuntu 16.04.

**Comment by paulproteus** [comment]
Hi @sixcorners ,

Thanks for trying Sandstorm, and I'm sorry to hear the installer didn't work for you!

The installer seemingly assumes a umask of 0022. I'll test tomorrow morning with 077 and find out what happens, and work on adjusting install.sh as needed.

Thanks!

**Comment by paulproteus** [comment]
Thanks a great deal @sixcorners . I'm able to reproduce the problem. I'll aim to push a fix today, and it will go live to https://install.sandstorm.io/ within a week.
