### ISSUE TITLE
docs: Should explain how to add "roles" to Sandstorm apps

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2301]
Context:

- I was going to ask a developer to add support for sharing roles within a Sandstorm app.

- However, I noticed that when I searched for roles within the docs -- https://docs.sandstorm.io/en/latest/search.html?q=roles -- no technical documentation seemed to show up.

- This page IMHO should explain it: https://docs.sandstorm.io/en/latest/developing/auth/ but doesn't say anything about it.

**Comment by dwrensha** [comment]
Closing as a dupe of #489.
