### ISSUE TITLE
Links to keybase.io in how to publish docs dead

### ISSUE THREAD

**Issue by TC01** [sandstorm-io/sandstorm#2306]
The [documentation on how to publish a Sandstorm application](https://github.com/sandstorm-io/sandstorm/blob/master/docs/developing/publishing-apps.md#sign-up-with-keybaseio) has two links to keybase.io explaining how to get set up, specifically:

* https://keybase.io/docs/command_line/prerequisites

* https://keybase.io/docs/command_line/installation

Both appear to be dead.

**Comment by paulproteus** [comment]
Thanks @TC01 !

Hey @cjb, since you're a friend of mine, and you're involved with Keybase, is there a chance that you can fix the Keybase docs to add a redirect for this page that we linked to?

If not, then I guess that's life! But I figured I should ask.

Thanks!

**Comment by cjb** [comment]
Oh, bummer, sorry about this! Please could you change the link to https://keybase.io/download ? We rewrote all the docs when switching to the version of Keybase that includes the filesystem.

I'll ask about a redirect, too.

**Comment by paulproteus** [comment]
Close #2309

**Comment by paulproteus** [comment]
...closed in #2309.
