### ISSUE TITLE
Sandstorm doesn't start; rs.initiate mongo command failed

### ISSUE THREAD

**Issue by johkra** [sandstorm-io/sandstorm#234]
Note: I run Arch Linux with a self compiled 3.18.5 kernel which enables CONFIG_USER_NS.
$ zgrep USER_NS /proc/config.gz 
CONFIG_USER_NS=y

Sandstorm installed today using the install.sh script fails to start for me. Please see the log files for details:

$ cat /opt/sandstorm/var/log/sandstorm.log
** Starting Sandstorm at: Sun Feb  1 14:41:37 2015
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 6
all output going to: /var/log/mongo.log
child process started successfully, parent exiting
Sun Feb  1 13:41:46.669 Error: couldn't connect to server 127.0.0.1:6081 at src/mongo/shell/mongo.js:147
exception: connect failed
*** Uncaught exception ***
/ekam-provider/canonical/sandstorm/run-bundle.c++:2372: failed: expected WIFEXITED(status) && WEXITSTATUS(status) == 0; mongo command failed; command = rs.initiate({_id: 'ssrs', members: [{_id: 0, host: 'localhost:6081'}]})
stack: 0x51ac01 0x4566ce 0x4ad030 0x4ac7e0 0x4a5037 0x4a2534 0x4a1f8d 0x4bafc0 0x4ba179 0x4ba16a 0x4596e1 0x45a365 0x51b8aa 0x4578dc 0x499562 0x5e8a90
** Server monitor died. Aborting.

$ cat /opt/sandstorm/var/log/mongo.log
Sun Feb  1 13:41:37.592 [initandlisten] MongoDB starting : pid=6 port=6081 dbpath=/var/mongo 64-bit host=septemfibra
Sun Feb  1 13:41:37.592 [initandlisten] db version v2.4.12
Sun Feb  1 13:41:37.592 [initandlisten] git version: nogitversion
Sun Feb  1 13:41:37.592 [initandlisten] build info: Linux ip-10-76-106-115 2.6.32-356-ec2 #69-Ubuntu SMP Mon Aug 26 15:32:17 UTC 2013 x86_64 BOOST_LIB_VERSION=1_49
Sun Feb  1 13:41:37.592 [initandlisten] allocator: tcmalloc
Sun Feb  1 13:41:37.592 [initandlisten] options: { auth: true, bind_ip: "127.0.0.1", dbpath: "/var/mongo", fork: true, logpath: "/var/log/mongo.log", nohttpinterface: true, noprealloc: true, nopreallocj: true, oplogSize: 16, pidfilepath: "/var/pid/mongo.pid", port: 6081, replSet: "ssrs", smallfiles: true }
Sun Feb  1 13:41:37.604 [initandlisten] journal dir=/var/mongo/journal
Sun Feb  1 13:41:37.604 [initandlisten] recover : no journal files present, no recovery needed
Sun Feb  1 13:41:37.607 [initandlisten] allocating new ns file /var/mongo/local.ns, filling with zeroes...
Sun Feb  1 13:41:37.649 [FileAllocator] allocating new datafile /var/mongo/local.0, filling with zeroes...
Sun Feb  1 13:41:37.649 [FileAllocator] creating directory /var/mongo/_tmp
Sun Feb  1 13:41:37.650 [FileAllocator] done allocating datafile /var/mongo/local.0, size: 16MB,  took 0 secs
Sun Feb  1 13:41:37.650 [initandlisten] waiting for connections on port 6081
Sun Feb  1 13:41:37.652 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:37.652 [rsStart] replSet info you may need to run replSetInitiate -- rs.initiate() in the shell -- if that is not already done
Sun Feb  1 13:41:38.652 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:39.652 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:40.652 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:41.653 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:42.653 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:43.653 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:44.653 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:45.654 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
Sun Feb  1 13:41:46.654 [rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)

**Comment by kentonv** [comment]
Hmm, I'm afraid I'm mostly stumped here.

At first startup, we start the Mongo server, then connect to it using the Mongo client to execute some setup commands. In your case, the client reported that it was unable to connect, which is odd since the server clearly reports that it is listening.

This is probably crazy, but is it possible that you don't have a loopback interface at 127.0.0.1? (E.g. perhaps you aren't running ipv4 at all?)

If that's not it, I guess I'd try deleting /opt/sandstorm and trying again. Maybe it's a rare timing issue, or something...

**Comment by kentonv** [comment]
BTW, thanks for providing so much detail in your report. :)

**Comment by johkra** [comment]
Thanks a lot for pointing me in the right direction with your "crazy" question about localhost! This is NOT a sandstorm problem and I'm closing this bug.

What happened: I was NATing lo. I use nftables and recently replaced my explicit NAT rules with the masquerade keyword available since kernel 3.18. And I did not restrict the masquerading so it applied to all interfaces including lo. *facepalm*

**Comment by kentonv** [comment]
Hah, nice. :)
