### ISSUE TITLE
‘Restore backup’ puts broken page in history

### ISSUE THREAD

**Issue by kpreid** [sandstorm-io/sandstorm#2354]
1. Restore a backup.
2. Press the Back button. (Assuming this is not one of those apps that breaks it independently, as in #238.)

You will see a page with URL `/upload` and content "Uploading... / Unpacking…”.

I imagine it's not usefully avoidable that this history entry is present (or would replaceState work here?), but it should at least say “Upload complete” or something like that, and have a link into the uploaded grain or back to the grain list, rather than displaying content that implies it's doing something.

**Comment by zarvox** [comment]
Good call; I think we should use `replaceState` when navigating away from `/upload` or `/uploadBackup`.  Then, clicking "back" takes you back to the place you were before your last action: clicking the "Upload app..." or "Restore backup..." button.
