### ISSUE TITLE
Create documentation on Sandstorm's current security/isolation features

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#236]
There are a number of blog posts describing security-related aspects of Sandstorm's design:

* https://blog.sandstorm.io/news/2014-08-11-roundcube.html talks about the importance of single sign-on.

* https://blog.sandstorm.io/news/2014-08-13-sandbox-security.html talks about the small number of device nodes, seccomp-bpf, and future plans to move ELF parsing into userspace.

* https://blog.sandstorm.io/news/2014-07-03-team-update.html discusses UID namespaces.

There are other security measures I couldn't quickly find a reference for:

* One-time-use subdomains, for app instances.

* Future plans to use Content-Security-Policy.

* IFRAME layer to prevent apps from leaking information to the world.

We would do well to convert this into a wiki page that lists at least the current security features, so that app developers and prospective users can better-understand how (and why) Sandstorm works.

Having this public document might also help people believe Sandstorm isn't "magic" (see also https://news.ycombinator.com/item?id=8972066 ).

**Comment by kentonv** [comment]
This post discusses one-time subdomains:

https://blog.sandstorm.io/news/2014-07-24-tinytinyrss-plus-security-discussion.html

**Comment by paulproteus** [comment]
As a remark, we describe the general goals here now:

https://github.com/sandstorm-io/sandstorm/wiki/Sandstorm-App-Developer-Handbook

**Comment by ocdtrekkie** [comment]
This exists now: https://docs.sandstorm.io/en/latest/using/security-practices/

**Comment by kentonv** [comment]
Yep, thanks.
