### ISSUE TITLE
Remote exception: fork() Cannot allocate memory

### ISSUE THREAD

**Issue by melissabutterfly321** [sandstorm-io/sandstorm#2365]
I am using subdomain of sandcats.io - with my own server.
I was able to install one extra app. Now, any other app I try install I get following error: 
I installed iPython... tried open notebook... 
Closed it.

Tried install another app ...
Failed to install app

remote exception: fork(): Cannot allocate memory

======================

Is there still a limit if using subdomain from sandcats !?!?!?

Please help.

**Comment by melissabutterfly321** [comment]
ubuntu@ip-4:/var/log$ ps -auxwww
-bash: fork: Cannot allocate memory
ubuntu@ip-4:/var/log$ 


This will then happen also.
After 3 minutes it goes back to normal . WTF

**Comment by dwrensha** [comment]
Sounds like you're running out of memory. How much RAM does your machine have? I recommend 1GB as a bare minimum for running Sandstorm.

**Comment by kentonv** [comment]
It looks like your server is out of memory. I actually recommend 2GB of RAM, and you'll also want to enable swap space, preferably on SSD.

I'm closing this issue since it isn't a bug in Sandstorm, but feel free to post more replies if you need further help.

**Comment by neuroradiology** [comment]
the following solution is documented to work as of 4/18/2020 on ubuntu 18.04 using a VM with 2GB RAM

**Solution**: Enable swap (I used 6GB, and it was enough)

**Detailed instructions**: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Summary** of commands

Confirm there is enough free space
`df -h`

Allocate swap
`sudo fallocate -l 6G /swapfile`

Verify correct allocation: 
`ls -lh /swapfile`

Restrict swap to root:
`sudo chmod 600 /swapfile`

Mark file as swap
`sudo mkswap /swapfile`

Enable swap
`sudo swapon /swapfile`

Confirm 
`sudo swapon --show`

Make it permanent.
First backup your 
`sudo cp /etc/fstab /etc/fstab.bak`

Append swap setting to original fstab
`echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab`

Consider adjustment of swappiness and cache pressure, which are detailed in previous link.
