### ISSUE TITLE
Slow connection / loading of sandstorm ETHERPAD ???

### ISSUE THREAD

**Issue by melissabutterfly321** [sandstorm-io/sandstorm#2366]
Why is it slow ? 

I am using own server. Using dns of sandcats .. is that slowing this down ??? 

Takes sometimes a minute to open etherpad instance.

WHY ETHERPAD original is so fast but editing with ETHERPAD app in sandstorm is so slow ?

Also I can't copy tables into it from other text editors like html tables ... but on etherpad original
I can ? 

https://beta.etherpad.org/ compare with that..

Any fixes for this ???

**Comment by ocdtrekkie** [comment]
Similar to #2365 ...How much RAM do you have? What sort of specs are you running this on?

Bear in mind that Sandstorm starts the Etherpad server software in a sandbox each time you open a document, whereas the Etherpad website at beta.etherpad.org is simply running Etherpad all the time. This distinction is a big part of Sandstorm's security model, which protects you from vulnerabilities in Etherpad and other applications.

**Comment by melissabutterfly321** [comment]
1 gb ram.
Linux.

**Comment by kentonv** [comment]
@melissabutterfly321 I recommend expanding the RAM on your machine. Others recommended 1GB but I would actually set 2GB as a minimum. You should also make sure you have swap enabled when running on machines without very much RAM.

Etherpad on Sandstorm typically takes 5-10 seconds to start on a properly-specced machine. We know that's still too long and we're working on making it better. But it definitely shouldn't take a minute.

**Comment by kentonv** [comment]
I'm closing this issue since it looks like it isn't a bug in Sandstorm, but please feel free to reply with further questions if you have them.
