### ISSUE TITLE
Back/forward navigation should work normally

### ISSUE THREAD

**Issue by kpreid** [sandstorm-io/sandstorm#238]
1. Go to Home at alpha.sandstorm.io.
2. Click on one of your documents.
3. Press the browser's Back button.
4. Observe it failing to go back to Home.

The Back button should always work. The URL (and the page title, but that's #165) should always uniquely identify where you have navigated to (both inside a grain and in Sandstorm's own UI). It should be possible to bookmark pages within a grain. (I'm lumping all these together because the fixes are related.)

**Comment by paulproteus** [comment]
Thanks for filing this. I totally agree with you.

**Comment by kentonv** [comment]
This is actually a bug in individual apps. Most apps work correctly. I've noticed that Ghost and LibreBoard have a redirect at startup that fails to use "replace" and therefore injects a history step which breaks the back button.

Updating the URL is also something that requires app cooperation. We have a postMessage() API for the app to update the outer URL, but most of our apps don't currently use it. For single-page apps (e.g. etherpad) it doesn't matter, of course, but ideally we should update the multi-page ones.

**Comment by kpreid** [comment]
Ah, I got unlucky. I tested two apps and found they both failed so I assumed it was Sandstorm's problem.

Suggest an existing app that does do outer-URL updating so I can try to break it?

(I hope your outer-URL-updating supports the fragment — a lot of “single-page” apps these days use the fragment extensively for navigation.)

**Comment by paulproteus** [comment]
I'll let Kenton remark on the thread with a specific app that works well
with the outer-URL updating.

Having said that, I think in the future, to help people have a good
experience with Sandstorm-ified apps, it might be interesting to expose
(and/or automatically test apps to find out) which Sandstorm platform
feature they support.

Outer-URL navigation updating is an interesting one. It seems to me that it
would be pretty feasible to write an automated test that looked for any
link on the page, clicked it, made sure the inner frame navigated, and then
check the outer frame to make sure its URL changed too.

@jparyani I'm curious what you think.

**Comment by kentonv** [comment]
MediaWiki does the outer-URL updating.

**Comment by paulproteus** [comment]
@neynah says this is closed, so I am going to mark it as such!
