### ISSUE TITLE
Make install create $BUILD_DIR atomically, or do *.xz download atomically

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#239]
Last Saturday at FOSDEM, I was trying to convince someone to install Sandstorm. So they attempted to download Sandstorm, and the *.xz download got interrupted mid-way due to the wifi being flaky. They ran the install script again, and were then asked:

```
echo "$BUILD_DIR is already present. Should I use it or re-download?"
```

However, the `$BUILD_DIR` contained about 17% of Sandstorm, so when they chose yes, sadness ensued.

We have a few options here:

* My preferred one: Wait until the `*.xz` file is fully downloaded before extracting. This makes it slightly slower but has an extremely simple implementation.
* Create `$BUILD_DIR.tmp` (using e.g. `mktemp -d $BUILD_DIR.XXXXXXXX`) and extract into there, and only when done, move that to `$BUILD_DIR`. I'd be happy with this too. This is probably what @kentonv would prefer, so I'll probably write a patch to do this.
* Focus on having `curl` retry, although having `curl` retry is really a separate thing than atomicity of download/extraction.
* Probably something else I'm not considering.

Anyway, today, at Philz Coffee in San Francisco, I was trying to install Sandstorm. I got the same problem of a flaky connection leading to a partially-downloaded `*.xz` file, so now I'm especially motivated to fix the issue.

**Comment by kentonv** [comment]
You are correct about my preference, in that it also guards against problems if the unpack fails post-download (say, because the user got board and ctrl+c'd, or because they ran out of disk). Also make sure to delete the temp directory on error. :)

**Comment by paulproteus** [comment]
#359 did not manage to do this; just remarking that this will still be nice to have. Perhaps I'll get to it soon. If someone else wants to, I won't object. (-:

**Comment by paulproteus** [comment]
Well, `do-download` in `install.sh` now starts with `rm -rf $BUILD_DIR` and it downloads the Sandstorm bundle into a fresh `mktemp -d` directory called `WORK_DIR` so I think it's safe to close this issue now.
