### ISSUE TITLE
appdemo should rely on app-index

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2397]
Context:

- If an app author uploads a new version of an app to Oasis, this can break the `/appdemo/` functionality.

- You can see this with Davros right now.

Proposed fix:

- Modify the `appdemo` code so that, rather than querying Mongo for the most recent `Package` available on this Sandstorm install, it queries the app index for the version to use.
- If that version is not available on this server, then ... ??? TODO: Someone help me design this.

Side-effects:

- This will have the result that appdemo only works for apps in the app index. In my opinion, this change is desired behavior.

**Comment by dwrensha** [comment]
To more fully describe the current situation: when I try to do a davros appdemo right now, I get a `window.alert()` that says "somehow, you seem to have attempted to launch a package you have not installed".

**Comment by ocdtrekkie** [comment]
Something about the most recent package installed being offered to the appdemo probably being a security leak somehow anyways. If people are testing preview builds or something or giving out SPKs to beta testers, current functionality would be bad.
