### ISSUE TITLE
"Download backup" should create data within a wrapper directory

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#240]
Steps to reproduce:

* Log into a Sandstorm instance, then create an instance of an app, and use it for a little while.
* Click the "Download backup" link at the top.
* Find a *.zip file in your ~/Downloads directory.
* Unzip it.
* Discover it has created files at the top level.

Expected behavior:

* The data should be within a directory like `grain-id/var` or something like that, to avoid stomping on files in the current working directory where the user unzipped it.

This issue is probably pretty bite-sized, so marking as such.

**Comment by kentonv** [comment]
Hmm, traditionally zip etiquette says _not_ to create a wrapper directory -- this differs from tar etiquette. GUI-based unzip tools (particularly on Windows/Mac) typically create a wrapper directory automatically. Unfortunately the unix unzip tool decides to match tar here, despite annoyingly _not_ matching tar on so many other points.

**Comment by paulproteus** [comment]
Interesting, okay. I could live with this staying the way it is if we also document it somewhere.

**Comment by ocdtrekkie** [comment]
I think I'd second @kentonv on that. I actually always make sure the zip tool is creating an appropriate folder for just this reason (and it usually does), and nothing makes me sadder then lots of nested folders to get to the stuff.

**Comment by paulproteus** [comment]
I added docs at https://github.com/sandstorm-io/sandstorm/wiki/Using-the-Sandstorm-Top-Bar so I will now close this!
