### ISSUE TITLE
Outbound email from app-index crashes with exception

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2409]
Impact:

- When app authors submit apps to the app index, they see an error message related to email.

Context:

- @simonv3 was trying to do an app market upload, presumably via `vagrant-spk upload`

- However, he got this exception in the console:

```
Error: remote exception: remote exception: remote exception: Error: Invalid recipient "App Index Notifications 
                 &lt;app-index@corp.sandstorm.io&gt;”
```

Diagnosis attempt:

- This string appears in the app index code:

```
$ git grep 'App Index Notifications'
src/sandstorm/app-index/app-index.c++:            to.setName("App Index Notifications");
```

- In the shell/imports/server/email.js file, the `send()` function takes the data from the Cap'n Proto email sending call and passes it to nodemailer.
- It creates `opts.envelope` containing the raw `to` value.
- This issue wasn't known to occcur a week ago, which suggests me to that this is related to the recent changes in how we send outbound emails.

I think @zarvox or @kentonv would be the fastest at root-causing this. If we can't do that soon, we might want to remove the call to `setName()` in the app-index and get a new version of the app index up.

**Comment by simonv3** [comment]
for what it's worth: I think the command I ran was `vagrant-spk publish`.

**Comment by zarvox** [comment]
I forgot to provide the magic incantation in the commit message, but this should be fixed when https://github.com/sandstorm-io/sandstorm/pull/2424 lands.
