### ISSUE TITLE
Missing key 'intrinsicName' in field [0].profile

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2412]
I see this exception in the Oasis logs:

    Exception while invoking method 'inviteUsersToGrain' Error: Match error: Missing key 'intrinsicName' in field [0].profile
     at exports.check (packages/check/match.js:34:1)
     at server/grain-server.js:405:7
     at [object Object].inviteUsersToGrain (server/grain-server.js:399:29)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
     at packages/ddp-server/livedata_server.js:711:19
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at packages/ddp-server/livedata_server.js:709:40
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at packages/ddp-server/livedata_server.js:707:46
     at Session.method (packages/ddp-server/livedata_server.js:681:23)
     at packages/ddp-server/livedata_server.js:551:43

Not sure what causes it. @dwrensha can you investigate?

**Comment by dwrensha** [comment]
Can you give me a better idea of how recent and how frequent this error is?

Perhaps some identity records in the database are somehow incomplete? Maybe try querying:

```javascript
db.users.find({"profile.service": "google", "services.google.name": {$exists: false}})
```

and

```javascript
db.users.find({"profile.service": "github", "services.github.username": {$exists: false}})
```

**Comment by dwrensha** [comment]
Or perhaps those fields do not [have type `String`](https://docs.mongodb.com/manual/reference/operator/query/type/), which you could detect like so:

```
db.users.find({"profile.service": "github", "services.github.username": {$not: {$type: 2}}})
db.users.find({"profile.service": "google", "services.google.name": {$not: {$type: 2}}})
```

**Comment by kentonv** [comment]
None of those queries returned results.

It looks like we've seen this error 7 times total in the last 30 days, 4 on 8/18 and 3 on 8/16. Perhaps it's not worth investigating further.
