### ISSUE TITLE
Outgoing e-mail attachments are broken

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2430]
It seems like outgoing e-mail attachments are broken in multiple ways:

1\. When I send an image named `image.png` from RoundCube, the received mail has a MIME part with these headers:

    Content-Type: image/png; name=image.png; name=attachment-1.bin
    Content-Disposition: attachment; filename=attachment-1.bin; size=17691
    Content-Transfer-Encoding: base64

I don't know where `attachment-1.bin` came from but it's clearly wrong.

Additionally, the body of this part is corrupted (which I only know because the image contained severe corruption artifacts).

2\. The Sandstorm icon in invoices sent by Blackrock is broken. The code is:

    SandstormEmail.send({
      to: email,
      from: config.acceptorTitle + " <" + config.returnAddress + ">",
      subject: mailSubject,
      text: mailText,
      html: mailHtml,
      attachments: [
        {
          filename: "sandstorm-logo.png",
          contents: ICON_BASE64,
          contentType: "image/png",
          cid: iconCid
        },
      ],
    });

This produces a MIME part with the headers:

    Content-Type: image/png; name=sandstorm-logo.png
    Content-ID: <dEbLnvMRAypsAzqr5>
    Content-Disposition: attachment; filename=sandstorm-logo.png

These look roughly correct, except that `Content-Transfer-Encoding` is missing. Additionally, the part has an empty body.

**Comment by zarvox** [comment]
There are several things going wrong here.

* #2431 should fix the replaced-filename issue.
* A one-character PR against Blackrock fixes the missing sandstorm-logo content.
* As for the corrupted attachments in email from roundcube: something else is going wrong on either the node-capnp or the sandstorm-smtp-bridge side which is probably related to either node-capnp on node4 or a longstanding bug in the roundcube package's smtp bridge.

To elaborate on that third point: I attempted to send myself an email with an embedded image from a roundcube grain.  If I add a `console.log(attachment.content.length)` after https://github.com/sandstorm-io/sandstorm/blob/master/shell/server/drivers/mail.js#L274 , I see 2994, when the embedded image is actually 60043 bytes.  Those 2994 body bytes, base64-serialized with \r\n separators, happen to take exactly 4096 bytes on the wire, which is a very suspicious number.  Further investigation required.

**Comment by zarvox** [comment]
Looks like `g_mime_stream_read` at https://github.com/jparyani/sandstorm-smtp-bridge/blob/f558e5c5d13b6cef280836038751a5ae2ee94b53/src/sandstorm/sandstorm-smtp-bridge.h#L243 might return early after reading a single page, and we're not checking the number of bytes actually read or calling it in a loop.  So the image corruption issue is likely a bug in the smtp bridge.

Filed https://github.com/jparyani/sandstorm-smtp-bridge/issues/1

**Comment by kentonv** [comment]
OK, the sandstorm-side bugs are fixed so I'll close this.
