### ISSUE TITLE
SMTP cannot be un-configured once configured

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2446]
The email configuration page will not let you submit it with fields empty, so you cannot delete the existing configuration.

Since it's possible to have to SMTP configuration if you never configured it in the first place, it ought to be possible to deconfigure it. This could perhaps be accomplished with an extra button rather than allowing blank fields.

Since this should be really easy and we have a user requesting it, let's try to implement this for the next push.

**Comment by kentonv** [comment]
Forgot @zarvox is on vacation. Maybe @jparyani can take this as a Friday task?

**Comment by jparyani** [comment]
He actually submitted a PR before he left. See #2447. Did you mean I should be the one to review it?

**Comment by kentonv** [comment]
Oh duh, why didn't I see that?

**Comment by kentonv** [comment]
I had filed the bug after midnight the night before @zarvox left, and I didn't imagine he'd actually do it at 1AM! Sorry @zarvox.
