### ISSUE TITLE
tracking progress on stretch goals with milestones, labels, and/or issues

### ISSUE THREAD

**Issue by dckc** [sandstorm-io/sandstorm#2449]
Please add a milestone for each of the stretch goals and populate them with issues that represent the bulk of the work involved in completing them:
- Indie App Market
- Powerbox
- GPG login
- Per-document encryption
- End-to-end encryption

Or use labels rather than milestones, if you prefer. If you'd like, I'd be happy to open an issue to represent each one of them. I'm most interested in the powerbox, so perhaps I'll start with that one and see if it proves useful...

**Comment by ocdtrekkie** [comment]
I am going to close this, because at this juncture, Sandstorm's development is definitely/probably not dictated by the stretch goals from the original Indiegogo campaign. At least the Powerbox exists!
