### ISSUE TITLE
outsourced hosting with custom domain name

### ISSUE THREAD

**Issue by dckc** [sandstorm-io/sandstorm#2458]
Sandcats and oasis are really cool, and the notion that I can back up a grain and restore it on a self-hosted service is nice in theory, but none of the sharing URLs would go with it. This often gives me pause.

With wordpress.com, xyz.wordpress.com is free, and for a small fee ($36/year) they will host a blog at xyz.com for you (or map a subdomain: blog.xyz.com).

Please consider doing likewise with sandstorm hosting.

I vaguely recall some explanation that this interacts poorly with sandstorm's random domain stuff, but I don't recall the details. I'd appreciate an explanation about the technical challenges (or a pointer, if it's already written up.)

**Comment by kentonv** [comment]
We have vague plans to have a "hosted Sandstorm for Work" which is really backed by Oasis but is externally indistinguishable from a self-hosted instance, hosted on the admin's choice of domain, and supporting many of the Sandstorm for Work features (like SAML login). But this is just an idea so far, and probably not something we can do for at least several months.

**Comment by dckc** [comment]
Meanwhile, I realized this issue is about the sandstorm service, not the software, so maybe it belongs elsewhere?
