### ISSUE TITLE
The "delete account" button needs more confirmation

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2463]
Currently the "delete account" button, when clicked, immediately suspends the user's account and logs them out. They can restore their account by logging in again -- no harm done. However, this would be _terrifying_ to someone who clicked it accidentally. We need an extra confirmation step in there.

**Comment by zarvox** [comment]
Proposal: when you click on the "delete account" button, show a modal which makes you type the literal text "Yes, please delete my account" into an input box (if it's your own account) or "Yes, delete this account" (if you're doing so administratively to another user's account).  Only enable the final "actually make the Meteor call to delete my account" button when the text is correctly entered.

This has two purposes:

1. Make it impossible to accidentally click/navigate on things in a way that results in the deletion of your account
2. Make it impossible to delete your account without acknowledging that what you are doing is deleting your account
