### ISSUE TITLE
Decide how email notifications should interact with multi-identity

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#2469]
I propose that we always send email to the primary (or first) verified address of the **identity** that is participating in the grain that produces an activity event.  If that identity has no email address on file, then we will send no message to grains that report events to that identity.  Given that all app-facing grain interaction is contextualized by an identity, not an account, I think this is the correct approach.

If you have an account with multiple identities that are all members of the same grain, you should receive separate emails for each identity, or in a future world with inline replies, we will be unable to contextualize your reply to an identity.

**Comment by kentonv** [comment]
I suggest posting our etherpad writeup here if you're OK with that.

**Comment by ocdtrekkie** [comment]
We no longer have multi-identity, so I am going to close this. We clearly already set a primary email for notifications.
