### ISSUE TITLE
Can't setup auth via Google for non-public instance (?)

### ISSUE THREAD

**Issue by bcg-didi** [sandstorm-io/sandstorm#248]
I just tried to create a Client ID via Google for a Sandstorm instance which isn't reachable from the Internet.
After step 7 (Clich "Create Client ID") the Google site very briefly shows me an error message (too short for reading it), nothing else happens. No Client ID is created.

Via github it works.

I'm not 100% sure if it's because of it not being publicly reachable, that's my guess.
It may also be that Google doesn't like the URL http://sandstorm:6080/

**Comment by paulproteus** [comment]
Hi ​bcg-didi,

Thanks for filing the issue!

My guess is yeah, Google wouldn't like a hostname that doesn't have a "."
in it. Perhaps you can use a hostname like "sandstorm.yourdomain.com" but
have the IP address route to a private IP? It depends on what your needs
are precisely.

I hope this helps; let me know!

**Comment by kentonv** [comment]
Hmm, I've successfully configured Google with `localhost` before, so I don't think that's the problem. Google does not expect to be able to connect to your server; it only redirects the user's browser there.

Unfortunately I haven't run into this myself and don't know what the problem might be. Please let us know if you find something.

**Comment by bcg-didi** [comment]
Then it looks more like a problem between Google and me, thus closing.
Thx for the instant feedback!
