### ISSUE TITLE
If base URL in sandstorm.conf ends in "/", then share-notification emails go to a 404

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2493]
What I know so far:

- my sandstorm.conf is below.

- When I sent a sharing link to my mom, she clicked it and saw a Sandstorm 404 message.

- She forwarded me the email, and it contains a HREF to: `https://rose.sandcats.io//shared/S0SHeV6VgULuORhsoCz93M3GOYyGjRS7B4iLYz7EJBu`

- Note the two `/` characters after `https://rose.sandcats.io`.

My sandstorm.conf

```
SERVER_USER=sandstorm
PORT=6080
HTTPS_PORT=443
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://rose.sandcats.io/
WILDCARD_HOST=*.rose.sandcats.io
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=no
SANDCATS_BASE_DOMAIN=sandcats.io
```

Partial contents of the email, with the actual subject line modified, and my mom's email address modified.

```

---------- Forwarded message ----------
From: Asheesh Laroia (via rose.sandcats.io) <no-reply@notifications.
asheesh.org>
Date: Mon, Aug 29, 2016 at 11:17 AM
Subject: {{personal information removed}} - Invitation to collaborate
To: mymom@gmail.com




Open Shared Grain
<https://rose.sandcats.io//shared/S0SHeV6VgULuORhsoCz93M3GOYyGjRS7B4iLYz7EJBu>
Note: You will need to log in with your Google account with address
mymom@gmail.com to access this grain.
```

**Comment by paulproteus** [comment]
`grain-server.js` has this line:

```
          const url = ROOT_URL + "/shared/" + result.token;
```

`ROOT_URL` comes from:

```
const ROOT_URL = process.env.ROOT_URL;
```

the `ROOT_URL` env var comes from `run-bundle.c++`

```
        KJ_SYSCALL(setenv("ROOT_URL", config.rootUrl.cStr(), true));
```

@kentonv would you be +1 on a patch that removes any trailing `/` character in `run-bundle.c++` where we parse the configuration file?

**Comment by kentonv** [comment]
Yes, that's what I'd do.

**Comment by paulproteus** [comment]
I just implemented this, and then I noticed that this would trigger the code in Sandstorm that removes the OAuth config, but that doesn't seem right to me since the OAuth config would almost definitely still be right.

Given that, I will:

- Continue to implement this as a change to `run-bundle.c++` to normalize the `ROOT_URL` that pull out of the config file, and also

- Adjust the "Did the ROOT_URL change?" handling so that it gracefully accepts the removal of a trailing slash as a non-event.
