### ISSUE TITLE
Add a feedback form to account deletion

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2513]
We should add a text box where people can optionally write some feedback. The feedback should be included in the notification e-mail sent to the admin.

Suggested copy:

> Optional: Why have you decided not to use [server name]? This feedback will be sent to the server admin.

**Comment by neynah** [comment]
Great idea. I have another suggestion:

>We're sorry to see you go. Feel free to share any feedback you have with the server admin.
