### ISSUE TITLE
Problems with existing Etherpad grain

### ISSUE THREAD

**Issue by enricodetoma** [sandstorm-io/sandstorm#2528]
I have an existing Etherpad grain which I can no longer access.
When debugging it, I get this output:

```
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain no longer in use; shutting down.
** SANDSTORM SUPERVISOR: Starting up grain.
Upgrading from dirty.db to sqlite...
module.js:327
    throw err;
    ^

Error: Cannot find module 'ueberDB'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/src/sandstorm-migrate.js:12:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
```

**Comment by ocdtrekkie** [comment]
Any idea how old this grain is? Etherpad on Sandstorm stopped using dirty a long time ago.

It sounds like the latest package may be missing some files Etherpad needs to upgrade very old grains.

**Comment by enricodetoma** [comment]
It might be a year ago or something like that.
I can try to upgrade it manually, if I understand how to do it...

**Comment by kentonv** [comment]
Thanks for reporting this!

I've filed a bug on the Etherpad package: https://github.com/kentonv/etherpad-lite/issues/29

I'll try to look at this tomorrow.

Closing this bug in favor of https://github.com/kentonv/etherpad-lite/issues/29

**Comment by kentonv** [comment]
This is fixed in the Etherpad update I just pushed, which should land on your server within 24 hours (or you can go to the app market and install it again to get the update now).

**Comment by enricodetoma** [comment]
Thank you very much, the Etherpad grain has been upgraded and works perfectly!
