### ISSUE TITLE
README.md should probably stop telling people to not use Sandstorm

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2548]
**About this ticket**

The purpose of this ticket is to track making a decision about how we can adjust README to scare people off less. Sticking to the status quo for now is an OK decision if that's what we want.

I'm hoping we can deal with this in the next week or so (by 2016-09-21).

**Details**

Quoth README.md:

> **Caveats**
> 
> Sandstorm is in early beta. Lots of features are not done yet, and more review needs to be done before relying on it for mission-critical tasks. That said, we use it ourselves to get work done every day, and we hope you'll find it useful as well.

A prospective user brought this up with me as a reason they're going to probably not go with Sandstorm. Interestingly whatever else they do will probably be less stable and secure than Sandstorm.

Therefore I think we do the world a disservice by saying this, or at least in this way.

Proposed alternate text (I'm open to others' brainstorming)

> **Project status**
> 
>  The Sandstorm core team and hundreds of companies use Sandstorm to get work done every day. We hope you'll find it useful as well, and we hope you'll give us feedback on what you want to see us work on next. Our security model already provides an unprecedented degree of hardening; we look forward to getting a formal security audit in the future.

**Comment by paulproteus** [comment]
(We could also mention auto-updates in there, possibly.)

**Comment by paulproteus** [comment]
Also possible we could mention priority-support in there.

**Comment by ocdtrekkie** [comment]
Fixed a long time ago via https://github.com/sandstorm-io/sandstorm/commit/a222715367065fde88239e98651259476f32f085
