### ISSUE TITLE
Whitelist x-requested-with

### ISSUE THREAD

**Issue by mrdon2** [sandstorm-io/sandstorm#2555]
The X-requested-with header, usually supplied by jQuery should be added to the whitelist.  It is used by a number of Ruby on Rails applications and is a requirement for porting Trac.

**Comment by mrdon2** [comment]
PR here: https://github.com/sandstorm-io/sandstorm/pull/2556

**Comment by zarvox** [comment]
Fixed in https://github.com/sandstorm-io/sandstorm/commit/8d274080e65afb25c43dd6f3c87ec2a2c9865dde
