### ISSUE TITLE
Make it easier to dev vagrant-spk apps without Vagrant

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#2557]
So, I have some weird app dev'ing issues. Like that I can't run vagrant-spk in my Linux environment because my Linux environment is already a VM, and I can't use vagrant-spk for some apps on Windows because of Windows file length limit and node_modules. However, I had an app where I was pretty sure the /.sandstorm folder was arranged perfectly for the app to work, but couldn't run it because of the Windows file length limit. So I figured "Hey, why not take this and run this with spk on my Linux VM?"

Given that Sandstorm itself seems to have no issue using spks made by vagrant-spk with /.sandstorm folders, I found it weird that the "spk dev" command was unable to find my sandstorm-pkgdef.capnp file.

**Comment by paulproteus** [comment]
Hi @ocdtrekkie !

To make this work, you'd have to specify the path to your pkgdef via e.g. this:

https://github.com/sandstorm-io/vagrant-spk/blob/master/vagrant-spk#L680

```
spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef
```

Note also the `cd` on the line before that.

In general, if you're going to use a vagrant-spk oriented package without vagrant-spk, my advice is to read the `vagrant-spk` source code for any special flags it passes to `spk`. If you do that, it should be pretty smooth sailing.

I hope that helps! Let me know, and once you're able to succeed, I hope you'll close this ticket. :)

**Comment by ocdtrekkie** [comment]
I'm a bit confused why I'd cd into the .sandstorm directory before passing that flag. If I run spk dev _in_ the .sandstorm directory, it finds the pkgdef... but then doesn't know the application itself is outside of it.

I will try this hopefully sometime this week though.

**Comment by paulproteus** [comment]
Yeah; I'm honestly surprised that vagrant-spk does a cd into the `.sandstorm/` directory. I would figure that vagrant-spk would cd into the app directory instead.

**Comment by ocdtrekkie** [comment]
I feel like there is more than one app package I could work on usefully if the spk tool conveniently would check for the vagrant-spk locations for things when it didn't find a pkgdef in the root. If it didn't look there until it was otherwise going to return it's "pkgdef not found" error, it would have no burden on spk's performance in other contexts and the spk tool would be able to reliably run any Sandstorm app package from source with the standard commands.

I don't _believe_ any other vagrant-spk behavior would cause issues, as everything else is in scripts and the pkgdef file, just in vagrant-spk's preferred default format.

**Comment by kentonv** [comment]
Does using the `--pkg-def` flag to specify the pkgdef location not work? E.g.

    cd /opt/app
    spk dev --pkg-def=.sandstorm/sandstorm-pkgdef.capnp:pkgdef

You would of course have to manually run `build.sh`, if there is one.

**Comment by ocdtrekkie** [comment]
I suppose, though I feel it should be simpler. But I guess this may not be the only frustration vagrant-spk adds to running an app with spk. This is me trying to launch that budget app that never got published for Sandstorm.

1. Apparently a sourcePath was set for /home/vagrant/bundle, which I commented out.
2. Apparently meteor-spk must be located at /opt/meteor-spk because a sourcePath is set for that to get meteor-spk.deps. I made a copy of my meteor-spk folder there for now to fix this.
3. Apparently the app itself must be located at /opt/app because the launch command is specifically set to look there. Renamed the folder I have this app in.
4. Apparently I realized I'm gonna need that /home/vagrant/bundle because build.sh dumps the Meteor stuff there.
5. build.sh -> Illegal operation: -o pipefail, commented this out.
6. Can't create a folder for /home/vagrant for access reasons, so rest of script dies.

Coming from the land of "I ported some apps to Sandstorm with spk while barely understanding Linux" to "I can't even figure out how to get apps already ported to Sandstorm to run without knowing more Linux"... :/

On the bright side, I'm now less annoyed with spk not finding .sandstorm automatically, I'm just more annoyed that vagrant-spk apps don't use relative paths.

**Comment by ocdtrekkie** [comment]
I suspect my best solution is going to end up being "assemble a physical Linux machine just so I can run vagrant-spk on it". :/

**Comment by kentonv** [comment]
Yeah, all the paths in the pkgdef will probably be wrong. You may have to edit them or move stuff around on your filesystem.

It would maybe be possible to create a tool which uses mount namespaces to set up directories to look like vagrant-spk without creating a full VM, but that would be a fair amount of my time to write, and it might ultimately not work for other reasons. Buying a little Linux box seems easier.

> build.sh -> Illegal operation: -o pipefail, commented this out.

`-o pipefail` is a bash-ism. Is build.sh not running with bash as the shell? First line should be `#! /bin/bash`.

**Comment by ocdtrekkie** [comment]
Just running `build.sh` didn't work, so I did `sh build.sh`. I have no idea what pipefail even does. Your first line is indeed what's there.

I have an i3 box that someone gave me. I just installed Ubuntu on it.

**Comment by ocdtrekkie** [comment]
I have edited this issue title to better reflect that it is a wider request than initially anticipated.

**Comment by kentonv** [comment]
@ocdtrekkie Oh, if you typed `sh build.sh`, then that would ignore the first line of the file and execute it using `sh` (a minimal shell) rather than `bash` (a fancy shell). You should try `bash build.sh`.

**Comment by ocdtrekkie** [comment]
I am closing this issue because I now have reasonable ways to run vagrant-spk, I think vagrant-spk is no longer the "sole recommended strategy" for packaging apps, and there is no clean/good solution here anyways. vagrant-spk-built apps should probably be hacked on using vagrant-spk.
