### ISSUE TITLE
Admin feature key page user testing feedback

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#2573]
On the feature key page:

* the "trial" tag shouldn't be green
* the "trial" tag should be the right-most of the tags
  * to the right of that, there should be a link to upgrade to a paid subscription that deep-links to the upgrade form directly in the feature key vendor.

**Comment by neynah** [comment]
Screenshot of existing UI for context:

![image](https://cloud.githubusercontent.com/assets/855341/18766986/a5f365f8-80d1-11e6-9d96-1a5009f97729.png)
