### ISSUE TITLE
install.sh: Support a mode where Sandstorm for Work is the default

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2580]
Context:
- When people get Sandstorm for Work feature keys, they get told to install Sandstorm.
- However, the Sandstorm installer re-asks them if they want Sandstorm for Work.
- People find this confusing.

Proposal:
- [tbd; saving this issue now to make sure the problem statement is defined]

**Comment by ocdtrekkie** [comment]
Closing because Sandstorm for Work doesn't exist, Sandstorm for Work feature keys don't exist, and the features from Sandstorm for Work are now just in Sandstorm.
