### ISSUE TITLE
Davros sync error

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/sandstorm#2593]
I'm seeing errors like "Error transferring https://me:pass@api-url/remote.php/webdav/filepath-chunking-1234567890-1-2 - server replied: Internal Server Error" on trying to sync _filepath_. Nothing shows up in the Davros logs, which leads me to suspect that Sandstorm, not Davros, may be where the bug lies.

**Comment by kentonv** [comment]
Does anything show up in the Sandstorm server log?

Is there any pattern to the kinds of files that show this error?

@mnutt

**Comment by mrdomino** [comment]
Sadly, I don't have the grain anymore, so I can't tell.

The file in question was a Gimp xcf of about 22MB.

**Comment by ocdtrekkie** [comment]
I think I'm going to go ahead and close this, as there's not enough diagnostic info to troubleshoot Sandstorm, others have not shown up to report the same, and the problematic grain doesn't exist anymore.
