### ISSUE TITLE
Apps don't really load

### ISSUE THREAD

**Issue by bitsandnumbers** [sandstorm-io/sandstorm#260]
I've got Sandstorm setup on a freenas server. I've created a virtual box jail and everything installed flawlessly following the virtual box install process in your wiki. I've setup my hosts file (in the vbox jail) to point my local ip to apps.domain.com and *.apps.domain.com, and also setup dnsmasq in the same way.

Now, I can access Sandstorm with "apps.domain.com:6080". I logged in successfully using github, I can install apps. But when I try to create a new file, I get the menu on top and a blank page. Although, I don't get quite much logs.

For instance, with LibreBoard, I get this:

> ...*\* SANDSTORM SUPERVISOR: Starting up grain.
> /ekam-provider/canonical/sandstorm/supervisor.c++:1121: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.
> *\* Starting Mongo...
> note: noprealloc may hurt performance in many applications
> about to fork child process, waiting until server is ready for connections.
> forked process: 6
> all output going to: /var/mongo.log
> child process started successfully, parent exiting
> *\* Starting Meteor...
> Meteor._wrapAsync has been renamed to Meteor.wrapAsync
> Starting board-background-color migration.
> Finishing board-background-color migration.
> Starting lowercase-board-permission migration.
> Finishing lowercase-board-permission migration.
> Starting change-attachments-type-for-non-images migration.
> Finishing change-attachments-type-for-non-images migration.
> Starting card-covers migration.
> Finishing card-covers migration.
> *\* SANDSTORM SUPERVISOR: Grain still in use; staying up for now.

Where `/ekam-provider/canonical/sandstorm/supervisor.c++:1121: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.`is the only error I get on each apps. I don't know if it is the culprit though.

So there's no error as to the wildcard, as I could see in other issues pulled to this hub, but the apps don't seem to load at all, although there's no log proving that.

Any idea what could be wrong ?

**Comment by dwrensha** [comment]
Does the server log show any errors? (Its default location is /opt/sandstorm/var/log/sandstorm.log.)

**Comment by bitsandnumbers** [comment]
Not quite, the only errors are:
`/ekam-provider/canonical/node-capnp/capnp.cc:1800: error: e = /ekam-provider/canonical/kj/async-io.c++:418: disconnected: connect(): Connection refused; toString() = unix:/var/sandstorm/grains/XkSqY3bRwx7Ai6LMgo8LRX/socket
stack: 0x7ff76141d401 0x7ff76141b9aa 0x7ff7613c3000 0x7ff7613b95b1 0x7ff76141e0aa 0x7ff7613b8d4f 0x7ff7613b7dcb 0x7ff7614010ec 0x7ff7613fa122 0x7ff76141e0aa 0x7ff7613f787d 0x7ff7613f8447 0x7ff7613f895d 0x7ff7613f6489 0x7ff761417141 0xa13f47`

and 
`Exception from sub (...) : Peer disconnected`

**Comment by dwrensha** [comment]
Does the browser console report any errors when the app iframe fails to load?

Is the DNS resolving correctly? If you do `dig xyz.apps.domain.com`, does it return the IP address of your server?

**Comment by bitsandnumbers** [comment]
So I got this error trying with Firefox (I was using Safari), and I get : 

`Firefox can't establish a connection to the server at 505w3p818vaq4ka5wnml.local.sandstorm.io:6080`

So I must have a bad setup somewhere, although I could not find relevant informations in your docs. Since I'm in a vbox environment, should I setup the hosts file the server that hosts the box, or in the box itself ?? Because I already setup the wildcard on the dns server and on the box host too...

**Comment by dwrensha** [comment]
Do you expect to connect at *.local.sandstorm.io? It sounds like are setting up your own domain *.apps.domain.com or whatever. If so, your /opt/sandstorm/sandstorm.conf file should have lines like these:

```
BASE_URL=https://apps.domain.com:6080
WILDCARD_HOST=*.apps.domain.com
```

If you change these, make sure you do `sudo sandstorm stop` and `sudo sandstorm start` to make sure the changes come into effect.

**Comment by bitsandnumbers** [comment]
Thanks, I overlooked the wildcart_host line in the conf file !

Ok, so now apps load properly. Although Safari has some struggles with some apps: opening a file in LibreBoard for instance redirects to the LibreBoard login page, while it opens the file with Firefox. GitLab failed completely to install (stuck on "verifying", no error log that I could see, I had to restart the box since nothing was working afterwards).

I have some questions:
- Is it possible to assign a default network interface instead of having to choose each time the vagrant box is loaded ?
- If I restart my server, will the vagrant box load automatically ? Otherwise, do you have advices on what to do to achieve that ?
- Is there a nice way to upgrade a Sandstorm instance when new versions are available ?

Anyway, thank you very much for your fast answers, I really think your project is an important piece of the open source future !

**Comment by dwrensha** [comment]
On Sun, Feb 15, 2015 at 10:54 AM, bitsandnumbers <notifications@github.com>
wrote:

>
> opening a file in LibreBoard for instance redirects to the LibreBoard
> login page, while it opens the file with Firefox.
>

That sounds like a bug in the app.


> GitLab failed completely to install (stuck on "verifying", no error log
> that I could see, I had to restart the box since nothing was working
> afterwards).
>

That sounds like a bug in our app installation code, where I think there
may be some race conditions lurking. I think the easiest workaround would
be to start over with a fresh install of Sandstorm. Hopefully you won't run
into it again, and meanwhile we should work on fixing the issue.


> I have some questions:
>
>    - Is it possible to assign a default network interface instead of
>    having to choose each time the vagrant box is loaded ?
>
>
>    - If I restart my server, will the vagrant box load automatically ?
>    Otherwise, do you have advices on what to do to achieve that ?
>
>
I'll defer to @paulproteus or someone else with Vagrant knowledge for these.



>    - Is there a nice way to upgrade a Sandstorm instance when new
>    versions are available ?
>
>
I think the Vagrant install chooses all of the default options. In
particular, it should choose "yes" for "keep Sandstorm updated?". So it
should automatically check and pull the latest build from
install.sandstorm.io.

**Comment by bitsandnumbers** [comment]
> I think the Vagrant install chooses all of the default options. In
particular, it should choose "yes" for "keep Sandstorm updated?". So it
should automatically check and pull the latest build from
install.sandstorm.io.

Oh, thanks. Very nice to hear. Easiest update process ever ;-)

As for GitLab, I won't fresh install Sandstorm because when I got the issue, I had it installed since max. 2 hours ;-) I'll wait and hope a fix is pulled that allow me to install without uninstalling everything first :-)

**Comment by bitsandnumbers** [comment]
(sorry for double post, but it must be visible)

Concerning the error I get with Safari, with the apps not opening and showing a blank page:

If I change the user agent in safari to firefox, the apps load normally.

It must be an issue with headers or something...

**Comment by paulproteus** [comment]
@dwrensha + @jparyani -- I wonder if the conversion from HTTP into capnp-HTTP into the sandbox should log a list of header names that it drops.

**Comment by ocdtrekkie** [comment]
Original issue was resolved, there's some various notes in here, but it's been five years and a lot of redesigning, so I'm going to close this.
