### ISSUE TITLE
Question about mediagoblin

### ISSUE THREAD

**Issue by Snarkly** [sandstorm-io/sandstorm#2616]
Due to technical limitations, video is disabled in the Sandstorm version of MediaGoblin. I use sandstorm hosted on oasis and I was wondering if I host sandstorm on my own server instead would I then be able to upload videos or would it make no difference.

**Comment by jparyani** [comment]
Video support is completely disabled in the package, regardless of it being hosted on oasis or not. It's blocking on gstreamer, which was I having problems getting to work inside the Sandstorm sandbox.

Closing in favor of https://github.com/jparyani/mediagoblin/issues/2 where there's more discussion on what it would take to re-enable video support for mediagoblin.
