### ISSUE TITLE
Decide how to clarify the "renewal" info in SfW dashboard and/or SfW admin area

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2622]
Context:
- # 2621 is a docs pull request where I document what "expires" or "next renewal" means in the Sandstorm admin panel, w/r/t Sandstorm for Work.
- I wrote the PR because a customer was confused. Perhaps we can clarify the text on this page so that it's easier to understand.
- Specifically, it seems to clear to me that customers don't know what auto-renewal means, so "Next Renewal" probably isn't very meaningful to them.
- Here's the line in the template:

```
shell/client/admin/feature-key.html:          {{#if featureKey.isTrial}}Expires{{else}}Next Renewal{{/if}}
```
- Here's the current UI for trial customers:

![screenshot from 2016-10-04 10 45 02](https://cloud.githubusercontent.com/assets/25457/19085573/c758472a-8a38-11e6-8b51-016dd988a6bf.png)

Proposal:
- For trial keys, let's say to "Billing starts on:"
- For non-trial keys, let's say: "Next billing date:"
- If possible, I'd like to show payment info here, such as:
  - The expected price the customer will pay on the next billing date. (This helps free-of-cost customers understand how this UI affects them. This also presumably helps elastic-billing customers understand how much they'll pay.)
  - The last 4 of the card on file, if there is one.

For discussion/review by @neynah @zarvox . Not necessarily urgent to figure this out now, but wanted to leave a note somewhere with some thoughts.

**Comment by zarvox** [comment]
> For trial keys, let's say to "Billing starts on:"

This will only work if the user has provided us billing information, which most don't at the time of sign up.  Given that we can't charge them until they've given us something to charge, I find this phrasing confusing.

> For non-trial keys, let's say: "Next billing date:"

+1

> If possible, I'd like to show payment info here, such as:
>   * The expected price the customer will pay on the next billing date. (This helps free-of-cost customers understand how this UI affects them. This also presumably helps elastic-billing customers understand how much they'll pay.)
>   * The last 4 of the card on file, if there is one.

The former is complicated by usage-based billing relying on a user count from the user's Sandstorm server, but the pricing information/logic/deals/etc. living in the SfW dashboard.  With the exception of the user count, the SfW dashboard is the better place for this information to live.

The latter is complicated by the fact that it's kinda infoleaky to show card details to anyone except the card owner, whereas any admin has access to the feature key.  Also, there's the fact that we don't plumb that through to the Sandstorm server anywhere to date, and (given the previous line) we might not want to.

**Comment by ocdtrekkie** [comment]
Feature keys are gone.
