### ISSUE TITLE
Split cleaning self and cleaning deps/node into separate make targets

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#2623]
The recent addition of our patched version of node has resulted in 20-minute longer build and test times on Jenkins.

@kentonv prefers to build all official release artifacts clean for each release, but is okay with our CI caching the built node to avoid 2x test run times.

- [ ] Move cleaning deps/node into separate `clean-node` target
- [ ] Add `deepclean` target which deps on `clean` and `clean-node`
- [ ] Call `make deepclean` in the release script

**Comment by kentonv** [comment]
I ended up adding a `ci-clean` instead, and it looks like Jenkins has been updated to use this.
