### ISSUE TITLE
make fails on ubuntu 14.04 in Vagrant

### ISSUE THREAD

**Issue by diracdeltas** [sandstorm-io/sandstorm#263]
While running `make` on the default ubuntu 14.04 vagrant box with all dependencies installed:

```
[snip]
> link: capnp/endian-test.o
> test: capnp/endian-test
> link: capnp/endian-reverse-test.o
> test: capnp/endian-reverse-test
> link: capnp/endian-fallback-test.o
> test: capnp/endian-fallback-test
> install: node-capnp/node-capnp.ekam-manifest
> terminate called after throwing an instance of 'std::logic_error'
>   what():  Already fulfilled this promise.
> Aborted (core dumped)
> make: *** [tmp/.ekam-run] Error 134
```

using Ubuntu clang version 3.5.0-4ubuntu2~trusty1 (tags/RELEASE_350/final) (based on LLVM 3.5.0)

using

**Comment by paulproteus** [comment]
Perhaps we should "just" switch the base box to use Debian stable!!

```
config.vm.box = "chef/debian-7.6"
```

is one way to do that.

**Comment by paulproteus** [comment]
There is also the chance that the filesystem sharing is messing it up.

**Comment by paulproteus** [comment]
I notice in https://github.com/sandstorm-io/sandstorm/blob/master/Vagrantfile that we're not using NFS. If we want reasonable filesystem sharing, we should use NFS. (FWIW I'm totally to blame on that; I am the author of this Vagrantfile.)

**Comment by paulproteus** [comment]
http://docs.vagrantup.com/v2/synced-folders/nfs.html discusses that.

Looks like adding this:

```
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
```

would switch that. @diracdeltas can you see if that makes this problem go away? Note you might need stop & start Vagrant.

**Comment by paulproteus** [comment]
And thank you for trying this. This stuff should work, and you're forging a path ahead for everyone.

**Comment by paulproteus** [comment]
Turns out adding NFS support also requires changing the network configuration, so I'll see if I can make that change here. Testing it now.

**Comment by paulproteus** [comment]
I found that it did help some, but that I still had other problems building Sandstorm.

Looking into NFS + 14.10 upgrade now.

I would use Debian inside the Vagrant, but Jessie isn't released yet, and Wheezy has too old a kernel to run Sandstorm.

**Comment by paulproteus** [comment]
I currently consistently get this error with NFS and 14.04 and clang-3.5 (as well as clang-3.4):

@kentonv does this ring any bells to you? Going to see if I get it in my Debian system outside VirtualBox now.

```
compile: sandstorm/union-fs.c++
  In file included from /ekam-provider/canonical/sandstorm/union-fs.c++:17:
  /ekam-provider/canonical/sandstorm/union-fs.h:23:10: fatal error: 'sandstorm/package.capnp.h' file not found
  #include <sandstorm/package.capnp.h>
           ^
  1 error generated.
compile: sandstorm/sandstorm-http-bridge.c++
  /ekam-provider/canonical/sandstorm/sandstorm-http-bridge.c++:45:10: fatal error: 'sandstorm/grain.capnp.h' file not found
  #include <sandstorm/grain.capnp.h>
           ^
  1 error generated.
capnpc: sandstorm/supervisor.capnp
  sandstorm/grain.capnp:23:38-48: error: 'GenericPersistent' has no member named 'persistent'
  sandstorm/grain.capnp:44:31-41: error: Not defined: persistent
  sandstorm/grain.capnp:23:7-17: error: Type names must begin with a capital letter.
  sandstorm/supervisor.capnp:59:37-47: error: Not defined: Capability
capnpc: sandstorm/ip.capnp
  sandstorm/grain.capnp:23:38-48: error: 'GenericPersistent' has no member named 'persistent'
  sandstorm/grain.capnp:44:31-41: error: Not defined: persistent
  sandstorm/grain.capnp:23:7-17: error: Type names must begin with a capital letter.
capnpc: sandstorm/web-session.capnp
  sandstorm/grain.capnp:23:7-17: error: Type names must begin with a capital letter.
compile: capnp/rpc-test.c++
  /ekam-provider/canonical/capnp/rpc-test.c++:451:19: warning: 'makeRpcServer' is deprecated: Please transition to using a bootstrap interface instead. [-
    Wdeprecated-declarations]
          rpcServer(makeRpcServer(serverNetwork, restorer)) {}
                    ^
  /ekam-provider/canonical/capnp/rpc.h:391:18: note: 'makeRpcServer<capnproto_test::capnp::test::TestSturdyRefHostId, capnproto_test::capnp::test::TestSturdy
    RefObjectId, capnproto_test::capnp::test::TestProvisionId, capnproto_test::capnp::test::TestRecipientId, capnproto_test::capnp::test::TestThirdPartyCapId
    , capnproto_test::capnp::test::TestJoinResult>' has been explicitly marked deprecated here
  RpcSystem<VatId> makeRpcServer(
                   ^
  /ekam-provider/canonical/capnp/rpc-test.c++:475:22: warning: 'restore' is deprecated: Please transition to using a bootstrap interface instead. [-
    Wdeprecated-declarations]
      return rpcClient.restore(hostId, ref.getObjectId());
                       ^
  /ekam-provider/canonical/capnp/rpc.h:75:22: note: 'restore' has been explicitly marked deprecated here
    Capability::Client restore(typename VatId::Reader hostId, AnyPointer::Reader objectId)
```

**Comment by paulproteus** [comment]
Bizarrely I can repro this on my Debian system, suggesting something weird is happening on my laptop that doesn't happen in Jenkins.

**Comment by paulproteus** [comment]
Okay. I think this problem boils down to us needing to use NFS. I'll submit a pull request with NFS-ification of Vagrant shortly -- @diracdeltas , after I do, I'd love test it on your system and see it it resolves this.

**Comment by paulproteus** [comment]
Also seemingly needed: `ruby-dev` or `nodejs-dev`; will finish investigating tomorrow presumably.

**Comment by paulproteus** [comment]
I believe that `apt-get install nodejs-dev` is not required, but having done the Meteor install before `make` is required. Testing that theory now.

**Comment by diracdeltas** [comment]
FWIW, the build happened flawlessly on my host machine (debian Jessie) so I'll give my cautious +1 for switching to debian on Vagrant.

@paulproteus lmk when new vagrantfile is ready to test!

**Comment by paulproteus** [comment]
Hi @diracdeltas ,

Thanks for filing this. I know it took me a year to address it, so thank you for your patience.

**Comment by paulproteus** [comment]
Indeed the new Vagrantfile is ready for you to test, if you wish, but if you don't wish to a year later, that is A-OK!
