### ISSUE TITLE
E_NEVER_LISTENED when installing from HTTPS-verified install

### ISSUE THREAD

**Issue by raz-l** [sandstorm-io/sandstorm#2632]
Everything good so far until the final step:

```
Your server is coming online. Waiting up to 90 seconds....................
*** INSTALLATION FAILED ***

Your server never started listening.
```
And it returns the error code:  `E_NEVER_LISTENED`

Mongo starts and suddenly stops working. RAM is not a concern neither applications using any vital port.

mongo log:
https://gist.github.com/raz-l/f15da0d922dc08427ba9104863b303ee

sandstorm.log:
https://gist.github.com/raz-l/501c5dfed5a6f01bd713077b8d36ebba

any help is greatly appreciated.

**Comment by kentonv** [comment]
Hmm, I feel like I saw this happen once... but only once, and when I wiped and installed again it didn't happen. If I'm remembering correctly, then that means this is some sort of rare timing issue that is hard to reproduce. By any chance did you try deleting /opt/sandstorm and installing again? Maybe it will work on the second try?

**Comment by raz-l** [comment]
yes, I tried deleting all and installing again, same error.

**Comment by zarvox** [comment]
A couple of possible ideas:

* Maybe a firewall is blocking connections?  Are you running a firewall, or something that would set iptables rules?
* Maybe a mandatory access control system like SELinux or AppArmor is blocking access.  Does anything interesting show up in `/var/log/audit.log` or in the output of `journalctl -f` when you attempt to launch Sandstorm?

Any additional information about your setup that you could provide would be helpful.  For instance:

* is this running on bare metal, a VM, or under some other container manager already?
* Which distribution/version are you running?

Thanks!

**Comment by raz-l** [comment]
It's a KVM virtualization. Yes, there are iptables running on the host. Could be that the problem? Here's the actual config: https://gist.github.com/raz-l/cb6ec1a347fd4cc9fc3d498656c53df8.

**Comment by paulproteus** [comment]
Hi @raz-l !

I wonder - could it be the case that the install worked fine, but our _detection code_ to see if the server started listening properly is actually at fault?

Given that, can you try connecting to it? Also, what port number is Sandstorm attempting to use? If it's 6080, that appears blocked by your firewall config.

**Comment by zarvox** [comment]
Looks like there's nothing in the iptables rules explicitly allowing loopback connections.  Sandstorm needs to connect to Mongo running on localhost on port 6081, and it can't (likely because of these firewall setting), so it thinks that Mongo failed to start.

The solution is to allow the Sandstorm -> Mongo connection.  Most tools I've seen allow all connections from the `lo` loopback device early on the INPUT chain, like so:

```
iptables -I INPUT -i lo -j ACCEPT
```

**Comment by raz-l** [comment]
Yeah, that did the trick, thanks everyone!
