### ISSUE TITLE
[Docs] "Edit on GitHub" links should be removed

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2638]
Top right "Edit on GitHub" links hit 404s.

![image](https://cloud.githubusercontent.com/assets/855341/19218076/5b5038d4-8da4-11e6-8f3b-5281d2e894f3.png)

**Comment by ar-jan** [comment]
There's an extraneous `tree/master/docs/` on the edit link (e.g. github.com/sandstorm-io/sandstorm/**tree/master/docs/**edit/master/docs/administering/sandcats-https.md). Looks like the MkDocs [edit_uri](https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md#edit_uri) isn't configured correctly?

**Comment by paulproteus** [comment]
@ar-jan & @neynah - thanks for reporting & providing such useful info to make this easy to fix!

And as always, thanks to the mkdocs team for making such an enjoyable docs generation  tool.
