### ISSUE TITLE
Cannot creat an admin account

### ISSUE THREAD

**Issue by Spacebody** [sandstorm-io/sandstorm#2639]
I set the logging in by google and github account, but I can't create an admin account because when I logged in by the account then the URL will turn to the initial setup page, and I need to setup again. What's wrong? The settings are all correct.

**Comment by Spacebody** [comment]
If use the HTTPS-verified install.

**Comment by kentonv** [comment]
Hi @Spacebody,

Sorry for the slow reply.

Did you try looking in the system log to see if there was an error message? There is a button at the bottom of the setup wizard to open the system log. My guess is that there will be an error message in there that explains what's going wrong.

**Comment by Spacebody** [comment]
Thnaks @kentonv ,
I solved this problem by using the source code to install.

**Comment by kentonv** [comment]
Hmm, that shouldn't produce any different results, though...

But, OK. I'll close this since you say it's fixed.

**Comment by Mher594** [comment]
I have same problem

**Comment by Spacebody** [comment]
Try to use source code to install, it might work.
