### ISSUE TITLE
Demo: Landing page redesign

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2657]
Changes proposed:
1. Provide a visual hint/preview of the demo so that users know what they're getting into. Some users voiced that they were hesitant to click on "Try a quick demo" since they had no idea what they would be doing next.
2. Added string "with all the apps you need, all in one place." to be consistent with our website. It also hints that Sandstorm is a work space where users can use many apps
3. Change string from "Try a quick demo" -> "Start" and also using arrows instead of the play icon. Play icon gives the impression there is some sort of video so it should be removed. "Try a quick demo" hints at non-permanence; users can actually create things and carry over their data to an actual account so instead I chose to use the string "Start". Also, the band is now styled it as a button to make it more obvious that it should be clicked.
4. Styling improvements

Proposed design (draft 1):

![oasis-demo1 1](https://cloud.githubusercontent.com/assets/855341/19397494/ed175566-91fc-11e6-9fd3-10f088bb0310.png)

Mobile (draft 1):

![oasis-demo-landing-mobile1](https://cloud.githubusercontent.com/assets/855341/19541184/566b8742-9619-11e6-84a2-084351fcdaa6.png)

Current design:

![oasis-demo-old1](https://cloud.githubusercontent.com/assets/855341/19397492/eb6048f4-91fc-11e6-856f-e32aba3a2dad.png)

**Comment by paulproteus** [comment]
@neynah can you add a screenshot/mockup for how this works on mobile?

**Comment by zarvox** [comment]
Some questions:

How do we expect this to interact with the user's session state?  If a logged-in user accidentally navigates to the demo start page, should we log them out and start a demo?  Ask them if they want to log out and start a demo?  Something else?

What would appdemo look like?

**Comment by neynah** [comment]
> @neynah can you add a screenshot/mockup for how this works on mobile?

For sure, I'll do that today.

>How do we expect this to interact with the user's session state? If a logged-in user accidentally navigates to the demo start page, should we log them out and start a demo? Ask them if they want to log out and start a demo? Something else?

We currently don't log people out but we still show them the demo landing page and then show them their grains (since they're already signed in). I don't have a good answer to this question but I think the current behaviour is strange. Perhaps we do want to ask them if they'd like to log out and try the demo. What are your thoughts on this proposed behaviour?

>What would appdemo look like?

Possibly this but I will file a separate issue for it today.
![oasis-demo4 1](https://cloud.githubusercontent.com/assets/855341/19400354/b240e188-920a-11e6-8935-9ccb3ce94cb5.png)

**Comment by kentonv** [comment]
> Perhaps we do want to ask them if they'd like to log out and try the demo. What are your thoughts on this proposed behaviour?

If a user is already logged in with an account, I can't imagine why they would want to log out and log into a temporary demo account instead. So maybe we just want to redirect them to their home page?

Note that we should carefully consider appdemos here. If someone who is already logged into Sandstorm visits etherpad.org and clicks to try a demo, we should almost certainly have them try etherpad using their existing account, not a demo account.

**Comment by neynah** [comment]
> If a user is already logged in with an account, I can't imagine why they would want to log out and log into a temporary demo account instead. So maybe we just want to redirect them to their home page?

Hmm. If a user is already logged in and clicks on a link to the generic Sandstorm demo then maybe we should skip the demo landing page altogether (in this case) and just redirect them to /apps so they can install apps.

> Note that we should carefully consider appdemos here. If someone who is already logged into Sandstorm visits etherpad.org and clicks to try a demo, we should almost certainly have them try etherpad using their existing account, not a demo account.

I do think the existing behaviour for appdemos should remain the same; including the "Try Etherpad" landing page.

**Comment by zarvox** [comment]
> I do think the existing behaviour for appdemos should remain the same; including the "Try Etherpad" landing page.

Interesting, could you elaborate?  My gut reaction is to do the opposite if you're already logged in to Oasis - install the app, add the app to your user, and create a grain with that app.  You get the bonus of being able to easily create more things with that app later.

If you are already logged in to a Sandstorm account, the topbar/sidebar will be familiar to you, there's not a whole lot of useful content that we'll tell you in that landing page interstitial, and there is value in dropping you right into the thing that you thought you were demoing.

**Comment by neynah** [comment]
>Interesting, could you elaborate? My gut reaction is to do the opposite if you're already logged in to Oasis - install the app, add the app to your user, and create a grain with that app. You get the bonus of being able to easily create more things with that app later.

>If you are already logged in to a Sandstorm account, the topbar/sidebar will be familiar to you, there's not a whole lot of useful content that we'll tell you in that landing page interstitial, and there is value in dropping you right into the thing that you thought you were demoing.

We currently show them the Etherpad landing page interstitial and once they click the "Try Etherpad" button drop them into a grain (which I think is better than just directly dropping them into a grain). I think the landing page interstitial does provide useful content- specifically, it tells the user what app they're about to use. We don't know where the user is coming from/how they got to the app demo so (I think) we can't safely assume that they already have sufficient context (that they are trying Etherpad) before they get to the Etherpad demo.

**Comment by kentonv** [comment]
I think users might find it surprising to be suddenly in their Oasis account if they didn't know the page was going to direct them to Oasis. So some interstitial makes sense. It may make sense to use slightly different language in the interstitial.

**Comment by zarvox** [comment]
> We currently show them the Etherpad landing page interstitial and once they click the "Try Etherpad" button drop them into a grain (which I think is better than just directly dropping them into a grain). I think the landing page interstitial does provide useful content- specifically, it tells the user what app they're about to use. We don't know where the user is coming from/how they got to the app demo so (I think) we can't safely assume that they already have sufficient context (that they are trying Etherpad) before they get to the Etherpad demo.

Do you mean that there exist appdemo links that are not contextually bound to the target by the person who made the link?  I am skeptical.  For instance, for Etherpad, http://etherpad.org/ reads "Etherpad is a highly customizable Open Source online editor providing collaborative editing in really real-time." and the appdemo link reads "Or try a demo".  I think users would prefer that we accept that they already expressed intent to try a demo of etherpad by following that link.

Similarly for the appdemo links from the app market - there are a bunch of apps which show the app title, icon, and have a button "Demo".  The context is already set; skipping the interstitial for logged-in users here would save users a click and let them immediately see the thing they wanted.

Am I missing something here?

>I think users might find it surprising to be suddenly in their Oasis account if they didn't know the page was going to direct them to Oasis.

I'm not sure I agree with that - arguably, this is true of any sharing link or grain link or any other route in the product as well.  I guess we have the incognito/identity interstitial in some cases, but that's also uninformative about what the impact of the choice you're making is, since you know nothing about the grain that you'd be revealing your identity to, or its owner.

**Comment by zarvox** [comment]
Also (entirely orthogonally) I kinda love the concept that if appdemo links dropped you straight into a new grain if you're logged in you could make a bookmark for "new etherpad doc" using that link. :)

**Comment by neynah** [comment]
>Do you mean that there exist appdemo links that are not contextually bound to the target by the person who made the link? I am skeptical. For instance, for Etherpad, http://etherpad.org/ reads "Etherpad is a highly customizable Open Source online editor providing collaborative editing in really real-time." and the appdemo link reads "Or try a demo". I think users would prefer that we accept that they already expressed intent to try a demo of etherpad by following that link.

I'm not saying that at all. For Etherpad specifically, the link on their home page is contextually bound; however, we can't make this assumption for all traffic that gets directed to our demo links (now and in the future).

>Similarly for the appdemo links from the app market - there are a bunch of apps which show the app title, icon, and have a button "Demo". The context is already set; skipping the interstitial for logged-in users here would save users a click and let them immediately see the thing they wanted.

Yes, and we have control over the App Market so we can ensure that that context is set. We can't ensure that third-parties that are directing traffic our way will set that context reliably.

**Comment by neynah** [comment]
If we can assume with confidence that users will be equipped with context before/while arriving at the demo grain then I'm happy to drop the interstitial. I'm just not personally convinced yet.

**Comment by zarvox** [comment]
I think that we're doing the due diligence on our side to provide context through the links we create, and I believe that app authors (who are likely the majority of other appdemo sources?  if I had data on this or a set of appdemo referrers that would be cool) are similarly incentivized to explain the demo link.

It's totally true that we can't guarantee that all links created ever will result in that context being set well.  I personally think that is probably okay, so long as we do continue to set context for things under our control, and in the worst case, we still have:

1. the Sandstorm topbar with "New Example App app instance" as the title of the thing
2. the app icon in the navbar
3. a familiar brand/navbar/toolbar/username + picture

I also suspect that logged-in users would rather jump straight to the juicy demo than click through interstitials - they've already seen the guided tour prompts at least once, and they're signed in to an account, so I don't think they're missing out on much.

OTOH, for users that are not logged in yet, absolutely keep the landing page - they don't know what Sandstorm is and why the app demo is running inside it.

In any event, I won't die on this hill if you really want to keep the interstitial, but I do think that it's more likely to get in the way of logged-in users than be beneficial to them.  Up to you!  :)

**Comment by neynah** [comment]
>OTOH, for users that are not logged in yet, absolutely keep the landing page - they don't know what Sandstorm is and why the app demo is running inside it.

Ultimately, I don't want to significantly worsen the UX for non-logged-in users (by removing context provided by the interstitial) just to make the UX a bit better for logged-in users. But I see now that you're only suggesting that we remove the interstitial for logged-in users. I am mostly +1 for removing the interstitial for logged-in users (and continuing to display it for non-logged-in users).

However, I do think @kentonv brings up an important concern though: 

>I think users might find it surprising to be suddenly in their Oasis account if they didn't know the page was going to direct them to Oasis. So some interstitial makes sense. It may make sense to use slightly different language in the interstitial.
