### ISSUE TITLE
Demo: Sidebar design tweaks

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2658]
Changes proposed:
- timer is less important than our call-to-actions so should be moved to the bottom; also deemphasized the colour (the fact that it ticks down by the second already brings attention to it)
- string changes to emphasize "collaboration" and "free account" over "keep your data"
- added "Get Sandstorm" button to make it more obvious there is an alternative way to use Sandstorm
- use more current Sandstorm colours

Proposed design (draft 1):

![oasis-demo2 3](https://cloud.githubusercontent.com/assets/855341/19399871/6f086640-9208-11e6-8e3d-9cd86c729f1c.png)

Existing design:

![oasis-demo-old2](https://cloud.githubusercontent.com/assets/855341/19399217/3eb073be-9205-11e6-968b-f4a86e363ecd.png)

**Comment by paulproteus** [comment]
At the bottom, I suggest you replace the string:

> This demo expires in:

with:

> You must sign up within the hour to keep your data. Time remaining:

or

> To keep your data, sign up within:

or something like that.

Rationale: This is not what normally is seen as a "demo" where the data is definitely doomed. Instead, they have the chance to keep the data. Therefore, the call-to-action of the timer is that they should "Sign up".

Not a showstopper, and is an easy string-fix that we can decide is out-of-scope for this ticket; if so, let me know and I'll pipe down. :)

**Comment by neynah** [comment]
I think this is a great suggestion.
>To keep your data, sign up within:

or

>Time remaining until sign up:

I'm not sure which one I prefer. Possibly the second one since we already mention keeping your data below the "Create a free account" button.

**Comment by paulproteus** [comment]
For this string:

> Time remaining until sign up:

I think "until sign up" is confusing language. I think if you try saying it out loud, you'll see what I mean. Maybe instead:

> Time remaining until you must sign up:

For what it's worth.

**Comment by neynah** [comment]
Ah. True that. How about just

>"Sign up within:"

**Comment by zarvox** [comment]
Questions:

* What happens on mobile?
* What does this do when the sidebar is collapsed?
* If there is insufficient space to show everything in the sidebar, what is the overflow behavior?

**Comment by zarvox** [comment]
Additional question:

* We currently change the color of the demo timer from yellow to red at 10 minutes.  Do we intend to remove this color change, which IIRC was added in response to previous user feedback indicating that it was too easy for your demo time to expire without you noticing?

**Comment by zarvox** [comment]
Additional question: what color is the primary foreground text in the sidebar (e.g. "Start collaborating...")? The font rendering + weight + hinting don't give me any pixels that are thick enough to confidently color-pick from the screenshot <_<

Is that color supposed to be the same as the foreground color on the buttons?

**Comment by neynah** [comment]
> What happens on mobile?

I'm happy to mock-up what this would look like on mobile but I'm not proposing any drastic changes there. Currently on mobile this sidebar is hidden behind the hamburger menu- I don't think we should change this behaviour for now.

> What does this do when the sidebar is collapsed?

Currently when the sidebar collapses we just show the timer. I think changing this behaviour is out of scope in the short term.

>If there is insufficient space to show everything in the sidebar, what is the overflow behavior?

Unfortunately, the current behaviour is to just push everything down off the screen it seems, however, I think we should limit the vertical space the open grains can take. The existing elements "copy, buttons, timer" should take priority and always be displayed. Fortunately in demo-mode users are unlikely to have more than 5 grains open at a time.

>We currently change the color of the demo timer from yellow to red at 10 minutes. Do we intend to remove this color change, which IIRC was added in response to previous user feedback indicating that it was too easy for your demo time to expire without you noticing?

I should have specified- yes, we should (for now) retain the colour changing to red at 10 minutes.

>Additional question: what color is the primary foreground text in the sidebar (e.g. "Start collaborating...")? The font rendering + weight + hinting don't give me any pixels that are thick enough to confidently color-pick from the screenshot <_<

Is that color supposed to be the same as the foreground color on the buttons?

My bad. I'll try to be more detailed/have larger screenshots. The white text is absolutely white (#fff), the font weights are normal.
