### ISSUE TITLE
400 The SSL certificate error

### ISSUE THREAD

**Issue by wizaxx** [sandstorm-io/sandstorm#2661]
Both trying to recover  Sandcats subdomain AND creating a new one give the same error and causes the installation script to loop.
Error in consolle is:
`<html>
<head><title>400 The SSL certificate error</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The SSL certificate error</center>
<hr><center>nginx/1.9.11</center>
</body>
</html>
`

Any suggestion?

**Comment by kentonv** [comment]
@paulproteus any thoughts?

**Comment by paulproteus** [comment]
@kentonv thanks for the ping, and @wizaxx thanks for filing this issue.

Typically, this occurs when the system's clock is set to a time that is significantly different than the current time.

@wizaxx can you run the command:


```
date
```

and also run the command:

```
curl -s --head http://google.com | grep ^Date
```

to see what google.com thinks the current time is?

Thanks for your patience. I'm looking forward to getting this issue resolved.

**Comment by ocdtrekkie** [comment]
Going to close this one for lack of response.
