### ISSUE TITLE
Install Failure - Your server never started listening

### ISSUE THREAD

**Issue by haynes11** [sandstorm-io/sandstorm#2669]
Hello guys,

I'm trying to install Sandstorm on CentOS7 (Upgraded Kernel to 4.4.25 so sandstorm could install)

![screenshot_1](https://cloud.githubusercontent.com/assets/19718532/19452734/1362fa18-94aa-11e6-9236-59646476ab3c.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/19718532/19452735/1364c1ea-94aa-11e6-8120-3428d85853f0.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/19718532/19452736/1366b46e-94aa-11e6-9999-167ca6a2ae3e.png)
I'm getting the following error running the install script (See screenshots, for log + install + Cpanel DNS setup). I believe I have entered all the values correctly including the whole wildcard DNS. Sandstorm is being setup on "cloudapps.techsu.net" which is hosted on another server. The DNS settings as you can see in the screenshot I believe are correct in regards to A record pointing to the server that is hosting Sandstorm and the CNAME I believe is also setup correctly.

I'm unsure of if DNS is related to the issue in the log? just thought I'd mention as it might be! Any advice on the error you see will be very welcome!

Thank You,
Jerome Haynes

**Comment by kentonv** [comment]
I think this is the problem where the installer script fails to detect that you already have an SMTP daemon running on port 25, in which case Sandstorm decides to map itself to this port.

@paulproteus What's the best way to work around this, until we manage to fix the installer?

**Comment by paulproteus** [comment]
@kentonv the best way is to modify sandstorm.conf - change `SMTP_LISTEN_PORT` to 30025.

Right now it's probably:

`SMTP_LISTEN_PORT=25`

Change that to

`SMTP_LISTEN_PORT=30025`

See also e.g. https://docs.sandstorm.io/en/latest/administering/config-file/#smtp_listen_port

**Comment by kentonv** [comment]
@haynes11 After editing `/opt/sandstorm/sandstorm.conf` to change `SMTP_LISTEN_PORT`, you'll want to run:

    sudo sandstorm start
    sudo sandstorm admin-token

**Comment by haynes11** [comment]
It actually turns out that because it was a brand new virtual machine the vm wasn't picking up the network interface at all! Though thanks guys! Got Sandstorm working now!

**Comment by kentonv** [comment]
Great!

FWIW @haynes11 as of the very latest release, Sandstorm now works on the default CentOS 7 kernel. We haven't updated the installer script yet, so it still complains in this case, but since you have already installed it, you should be able to switch back to the default kernel and everything should continue to work. Just in case you didn't want to track security updates on your custom kernel... :)
