### ISSUE TITLE
Can't install Sandstorm because of Rocket Chat

### ISSUE THREAD

**Issue by desgyz** [sandstorm-io/sandstorm#2673]
I am unable to finish installing Sandstorm because Rocket.Chat will not install and because it's a pre-installed app it will not let me pass that section. It has the blue bar next to it indicating its downloading it is frozen, but underneath it, Wekan has already finished downloading.

This is my first time installing Sandstorm, I have no idea what to post but I guess the last bit of the log will be helpful.

`Running new server startup function 1
Running new server startup function 1
Since Tue Oct 18 2016 07:24:21 GMT+0000 (UTC) is more than three days away from Thu Oct 27 2016 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
Downloading app: https://app-index.sandstorm.io/packages/e813a833d983fbc38d87da62ea461fa7
Downloading app: https://app-index.sandstorm.io/packages/19b0e88934e0f85d8b92e288a6c0a371
Downloading app: https://app-index.sandstorm.io/packages/efbc8d5c9586acc919ccbeca1cd18f2e
Downloading app: https://app-index.sandstorm.io/packages/3cffd7d785b8c95423512570c03aa36d
Downloading app: https://app-index.sandstorm.io/packages/5695213427725c8ead577171eb7fa62a
App ready: 3cffd7d785b8c95423512570c03aa36d
fetching keybase 6B7486EA873576FD72845C5E50E4D7384B1B4D65
fetching keybase 6B7486EA873576FD72845C5E50E4D7384B1B4D65
keybase lookup error: Error: ETIMEDOUT
    at [object Object]._onTimeout 
(/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:772:15)
    at Timer.listOnTimeout (timers.js:92:15)
App ready: e813a833d983fbc38d87da62ea461fa7
fetching keybase 211BF6A1E4CD72C957B705FA8EE8B9250C803854
App ready: 19b0e88934e0f85d8b92e288a6c0a371
fetching keybase 880223DF25AA25A9433AF0FB40678458440DDCF1
App ready: efbc8d5c9586acc919ccbeca1cd18f2e
fetching keybase AD1E0DD65E86C787D602EDF15D34826FE06DA95D
Successfully updated sandcats IP
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.`

Regards,
Desgyz

**Comment by jparyani** [comment]
It's interesting that you have a line like:
```
fetching keybase 6B7486EA873576FD72845C5E50E4D7384B1B4D65
keybase lookup error: Error: ETIMEDOUT
at [object Object]._onTimeout (/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:772:15)
at Timer.listOnTimeout (timers.js:92:15)
```

I wonder if you had internet connectivity issues, which caused the Rocket.chat download to fail in an unexpected way that went unreported.

From your server's shell, could try and run `sudo sandstorm restart` and see if it restarts the download?

**Comment by desgyz** [comment]
Hello,

Thanks, that seem to fix it. Surprised I didn't just do that first.

Thanks,
Desgyz
