### ISSUE TITLE
HTTPS via sandcats stopped working

### ISSUE THREAD

**Issue by alexander-vidoni** [sandstorm-io/sandstorm#2683]
Hi, 

since two hours ago i can not connect to sandstorm via HTTPS via sandcats.io.
Yesterday it worked.
For debugging I altered sandstorm.conf to no longer use https.
Unencrypted connections are working - no data loss.
Restarting sandstorm, rebooting the machine had no effect.

I am running version 191.

While inspecting the sandcats directory 

> /opt/sandstorm/var/sandcats/https/<MY_SANDCATS_DOMAIN>/

i saw this:

```
-rw------- 1 sandstorm sandstorm 3272 Oct  4 09:37 0
-rw------- 1 sandstorm sandstorm 1602 Oct  4 09:37 0.csr
-rw------- 1 sandstorm sandstorm 5400 Oct  4 09:38 0.response-json
-r-------- 1 sandstorm sandstorm 1702 Oct 10 17:24 1476113072126
-rw-rw---- 1 sandstorm sandstorm  922 Oct 10 17:24 1476113072126.csr
-rw-rw---- 1 sandstorm sandstorm 5036 Oct 10 17:24 1476113072126.response-json
```

My current local time (Germany), writing this post, is October the 20th 2016 13:28:00

I read that the certs are outdated after 10 days and are renewed automatically.

The certs in https directory are about 10 days old and not renewed.

I don't have any idea why.

Could it be possible that there is a timezone problem in the process of renewing the certs?

**Comment by paulproteus** [comment]
Hi @alexander-vidoni ,

Thanks for reporting this issue, and sorry it's affecting you.

I wonder if you can provide me the contents of `/opt/sandstorm/var/log/sandstorm.log`. I just did a manual test of this procedure on `rose.sandcats.io` and it seems to be working OK.

If you're not comfortable submitting the log file here, you can alternatively email it to support@sandstorm.io and I can look at it there.

Thanks so much for your patience!

**Comment by alexander-vidoni** [comment]
Hi @paulproteus,

I just sent the log file to support@sandstrom.io.

**Comment by kentonv** [comment]
In the support thread we figured out that the `SANDCATS_BASE_DOMAIN=sandcats.io` line had been lost from Alexander's `sandstorm.conf`, which seems to explain the problem.

Arguably Sandstorm could hard-code a check for `sandcats.io` in the BASE_URL and then automatically assume `SANDCATS_BASE_DOMAIN=sandcats.io` to avoid this problem.

**Comment by alexander-vidoni** [comment]
Hi @kentonv , Hi @paulproteus ,

I added the missing line an the system came back immediately.
Thank you for your for your support investigating this issue.
