### ISSUE TITLE
Grains don't immediately move to trash

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2684]
Behaviour observed in user test:
User selects all grains, clicks "move to trash", nothing happens (grains are unselected and remain in main list).
User selects all grains again, clicks "move to trash", nothing happens again.
User then clicks "View trash (0)", doesn't see any grains in the trash then clicks "restore backup", cancels the file selector, then the grains magically appear in his trash list.

![image](https://cloud.githubusercontent.com/assets/855341/19578975/24cd125e-96d3-11e6-9849-ae39cffbc20e.png)

@paulproteus suggests this issue is likely due to a slow network and that "we should probably display a spinner to show the operation is still in progress".

**Comment by kentonv** [comment]
Instead of a spinner, we should let Meteor's client-side prediction take effect. :)
