### ISSUE TITLE
Grain isn't restarted when `spk dev` starts/stops

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#269]
Lately I've noticed that killing `spk dev` or starting it again doesn't seem to restart the grain, so instead it ends up in a very broken state. I thought this worked before.

**Comment by dwrensha** [comment]
Diagnosed: this broke when `/bin/sandstorm-supervisor` became a symlink pointing to `/bin/sandstorm`. Now when we call `killall("/bin/sandstorm-supervisor");` in `run-bundle.c++`, nothing gets killed!

I'll see if I can come up with a fix...
