### ISSUE TITLE
Server crashed after update to 192

### ISSUE THREAD

**Issue by funwhilelost** [sandstorm-io/sandstorm#2692]
Had the server go down after the automatic update to 192.

```
** Time: Sat Oct 22 18:50:51 2016
Checking for updates on channel dev...
Downloading: https://dl.sandstorm.io/sandstorm-192.tar.xz
Checking signature...
Signature is valid.
** Successfully updated; restarting.
```

```
** Restarting to apply update
** Shutting down due to signal
Not killing Dev daemon because it is not running.
*** Uncaught exception ***
sandstorm/run-bundle.c++:1345: failed: unshare(CLONE_NEWNS): Operation not permitted
stack: 0x4e62d4 0x4e1bdf 0x507a96 0x50796d 0x49219d 0x492ca0
** Server monitor died. Aborting.
```

After manually starting the server it's working fine.

**Comment by paulproteus** [comment]
For @kentonv : 

This looks like the same error message that I experienced last last week when I was doing `sandstorm update` (as non-root) as part of the App Market deploy code, fwiw.

**Comment by kentonv** [comment]
Sadness, it appears that I did in fact break updates for non-root installs.

On the bright side, based on our stats it seems a negligible number of users run Sandstorm this way.

More bad news: The problem cannot be fixed without one more crash. But after the next update, future updates should work correctly.

**Comment by kentonv** [comment]
Fix in https://github.com/sandstorm-io/sandstorm/pull/2713

**Comment by funwhilelost** [comment]
The prompt fix is super appreciated.  Happy to reboot and help out when I can.
