### ISSUE TITLE
Update "Welcome to Sandstorm!" installation selection page

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2701]
Quick changes we should make to update this installation-picker page to match our [website](https://sandstorm.io/get):
- "Standard" -> "Sandstorm Standard"
- Update SfW price to reflect current discount: "$10 / user / month" -> "~~$10~~ $5 / user / month" (Note, the ~~$10~~ should be greyed out)
- Link "Sandstorm Standard" to https://sandstorm.io/features
- Link "Sandstorm for Work" to https://sandstorm.io/business

Non-trivial changes we should make in the near future:
- Update feature table to be consistent (or at least list some of the same features) with: https://sandstorm.io/get
- Style feature table to be consistent with: https://sandstorm.io/get (requires mock-up)

Current UI:
![image](https://cloud.githubusercontent.com/assets/855341/19705908/f4297daa-9ac3-11e6-9174-9c82302ff7fe.png)

**Comment by paulproteus** [comment]
This would be great; thanks for filing such a clear bug report.

I propose when we make this change, we also measure if the change improves
click-rate on the "Begin Sandstorm for Work" setup. Would that be OK with
you and whoever ends up implementing it?

(Current status: feeling inspired by the book _The Lean Startup_)

**Comment by neynah** [comment]
>I propose when we make this change, we also measure if the change improves
click-rate on the "Begin Sandstorm for Work" setup. Would that be OK with
you and whoever ends up implementing it?

That sounds worth measuring.

**Comment by neynah** [comment]
Proposal:
- Display full feature comparison lists matching our website
- Standard -> Sandstorm Standard
- Add graphics & colours; style buttons
- Change bold weighting of product title text to regular weighting
- Include text "Introductory Offer - Save 50%"
- Center text and also include "(You can change your mind later.")

The I'm hoping to see is more clicks on "Begin Sandstorm for Work Setup" relative to clicks on "Begin Standard Setup".

@paulproteus are we currently tracking this information?

![admin-panel-onboarding-plan-revision1](https://cloud.githubusercontent.com/assets/855341/20730255/3901162c-b63a-11e6-92a5-3511fcc9483f.png)

**Comment by kentonv** [comment]
One weird thing here: The left column says "open source" at the top but both are actually open source. Saying "open source" on the left seemingly implies that the right side isn't open source. Thoughts?

**Comment by neynah** [comment]
> Saying "open source" on the left seemingly implies that the right side isn't open source. Thoughts?

I could see that, although I don't have enough information to indicate that this is a significant problem. If we were to remove the word "open source" do you think users would think Sandstorm is not open source? If we think users will think Sandstorm is open source whether it's stated or not on this page then I would say let's just remove it (instead of adding it to both).
