### ISSUE TITLE
Use darker shade of red for "danger" button styles

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2702]
The current red (#ff0000) we use for "danger" button styles definitely draws attention, however, the red is too bright (making the foreground white text difficult to read).

A few screenshots of our existing UI (these red danger buttons can be found in other places as well):
![image](https://cloud.githubusercontent.com/assets/855341/19707036/1da992cc-9aca-11e6-9d20-22b80cdc9849.png)
![image](https://cloud.githubusercontent.com/assets/855341/19707081/5bf88dee-9aca-11e6-8045-151c20f31d6f.png)
![image](https://cloud.githubusercontent.com/assets/855341/19707130/b830b460-9aca-11e6-9f9a-68cf2bb5db6e.png)

Changes proposed:
- change default background colour from #ff0000 to #941515
- change hover background colour from #cc0000 to #af1010

![image](https://cloud.githubusercontent.com/assets/855341/19707482/b2c7a310-9acc-11e6-9c46-0e9b8ca5df2a.png)
![image](https://cloud.githubusercontent.com/assets/855341/19707470/9bea8b26-9acc-11e6-8cb6-6b0796ecd621.png)

**Comment by zarvox** [comment]
Counterproposal: make danger buttons be secondary buttons with red text, with the additional effect that on hover you get the (reduced-brightness) red color and white text:

![default](https://cloud.githubusercontent.com/assets/307325/19709999/ce101c3e-9adf-11e6-8c51-bf8d364ed3de.png)

![on-hover](https://cloud.githubusercontent.com/assets/307325/19710012/de91bf04-9adf-11e6-9361-3ce0bff9df74.png)

Thoughts?

**Comment by neynah** [comment]
Yeah I prefer the secondary button styling you proposed. But, let's go with #af1010 for the bg hover colour- it's a touch darker.
