### ISSUE TITLE
Web Publishing doesn't serve static files with spaces

### ISSUE THREAD

**Issue by mnutt** [sandstorm-io/sandstorm#2725]
Steps I took to reproduce:

* create a Davros grain, add a file with spaces in it.
* turn on web publishing (this currently just symlinks davros's `data` directory to `www`)
* go to the file, attempt to access its public URL.

It appears that it doesn't urldecode the URL paths before serving the files.

(zarvox comment from IRC: _just thinking out loud: it should probably be the supervisor that handles decoding the path before trying to open the file it serves_)

**Comment by dwrensha** [comment]
I suppose the solution is to use `percentDecode()` from `util.h` on the path [here](https://github.com/sandstorm-io/sandstorm/blob/f73d854f077ccf3df51bf3c6668157b260b1dcc0/src/sandstorm/supervisor.c%2B%2B#L2102).

**Comment by kentonv** [comment]
Hmm, IMO this is more-correctly fixed in pre-meteor.js. getWwwFileHack() should receive an already-decoded string.
