### ISSUE TITLE
Amazon SES Email Sending

### ISSUE THREAD

**Issue by RexFuzzle** [sandstorm-io/sandstorm#2734]
Hi

I seem to be having a problem sending emails through the amazon ses service. The error that is given when I click the send button in the test email dialog is the following:
```Error while trying to send test email: {"code":"EAUTH","response":"535 Authentication Credentials Invalid","responseCode":535,"command":"AUTH PLAIN"} [other-email-sending-error]```
I have tried all the listed ports as well as 587 and had no luck. I believe my SES service is setup correctly with the right policies and users etc, but I may be wrong.
Any guidance would be appreciated.
Thank you.

**Comment by jparyani** [comment]
I just tested, and using Amazon SES works for me. Did you click the `Create My SMTP Credentials` under the `SMTP Settings` tab in SES? If so, be careful to not copy paste any extra spaces around the password (I did that by accident the first time).

**Comment by RexFuzzle** [comment]
Thank you. I'll have to have a look again.

**Comment by RexFuzzle** [comment]
Sorry, seems I had a username password issue.
