### ISSUE TITLE
build failure with clang 3.9

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#2741]
When I do 

```
CAPNP_SKIP_FUZZ_TEST=yes make continuous CXX=/home/david/Desktop/llvm-3.8.1.src/build/bin/clang++ CC=/home/david/Desktop/llvm-3.8.1.src/build/bin
/clang
```

the build succeeds.

When I do 
```
CAPNP_SKIP_FUZZ_TEST=yes make continuous CXX=/home/david/Desktop/llvm-3.9.0.src/build/bin/clang++ CC=/home/david/Desktop/llvm-3.9.0.src/build/bin/clang
```

I get the errors:
```
jstest: node-capnp/capnp-test.js
  full log: tmp/node-capnp/capnp-test.js.log
install: node-capnp/node-capnp.ekam-manifest
```

The full log is:
```
$ cat tmp/node-capnp/capnp-test.js.log 
/home/david/src/sandstorm/node-capnp/capnp.js:42
    throw new Error(
    ^

Error: `./capnp.node.node` is missing. Try reinstalling `node-capnp`?
    at Object.<anonymous> (/home/david/src/sandstorm/node-capnp/capnp.js:42:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/david/src/sandstorm/node-capnp/capnp-test.js:23:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

The ekam output has the line

```
compile: node-capnp/capnp.cc
```

indicating that `capnp.cc` gets compiled successfully. The `capnp.node` file does not get built, however:

```
$ ls tmp/node-capnp/
capnp.o       capnp.o.syms	 test.capnp.c++  test.capnp.o	    test.capnp.o.syms
capnp.o.deps  capnp-test.js.log  test.capnp.h	 test.capnp.o.deps
```

Note that, in a non-ekam-managed project, I can successfully build and install the latest node-capnp through npm:

```
$ CXX=/home/david/Desktop/llvm-3.9.0.src/build/bin/clang++ npm install ~/src/node-capnp/
```

It seems like the problem is that clang 3.9 includes some subtle change that somehow interferes with whatever magic ekam is doing.

**Comment by zarvox** [comment]
Looks like clang's C++ symbol mangling changed from creating the symbol `_Z7_module` in clang-3.8 to creating the symbol `_ZL7_module` (added an `L` between Z and 7) in clang trunk (and probably also 3.9).  The latter of these doesn't match ekam's [nodejs module detect logic](https://github.com/sandstorm-io/ekam/blob/master/src/ekam/rules/compile.ekam-rule#L179..L187).

https://github.com/gchatelet/gcc_cpp_mangling_documentation suggests that the `L` prefix indicates that the variable is const, so we can probably just make ekam's symbol test accept an optional L there.
