### ISSUE TITLE
Support SAML logout hook

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2743]
SAML generally expects applications to redirect the user to a logout endpoint at the SAML provider when they express the intent to log out. Currently Sandstorm does not do so, but it should.

With simplesamlphp, the effect of this bug is that after a user logs out of Sandstorm, if they click "login with SAML" they are logged back in without any password prompt, because simplesamlphp has kept a cookie on its own domain that keeps the user logged in. This is problematic on public computers.

**Comment by dwrensha** [comment]
Is this the same as #2165?

**Comment by kentonv** [comment]
Yup.
