### ISSUE TITLE
Struggling with basic setup -- grains error "Error: Unauthorized [403]"

### ISSUE THREAD

**Issue by brycefisher** [sandstorm-io/sandstorm#275]
Hi Sandstorm!

I'm trying to setup a local sandstorm instance to play around with on my Ubuntu 14.04 (no vagrant). I've used the easy install method and managed to setup dnsmasq. I've downloaded and installed both Gitlab and Draw.io. Creating a new grain for either one results in this error:

*Error: Unauthorized [403]* and a stacktrace from NodeJS
![sandstorm-unauthed-err](https://cloud.githubusercontent.com/assets/220106/6321398/88cd0094-bab0-11e4-9441-ac981a6ffa3d.png)

Presumably, I haven't setup https correctly between the grain and the legacy bridge, but I don't have any insight into that. Thanks in advance for the help!

**Comment by dwrensha** [comment]
That error seems to indicate that your Sandstorm session cookie is invalid or not present. Can you verify that your browser is indeed sending the "sandstorm-sid" cookie?

**Comment by brycefisher** [comment]
Yeah! You're right. Something's screwy in my browser. Tried another browser and I'm in! Thanks @dwrensha

**Comment by kentonv** [comment]
It may be that your browser is set to disallow "third-party cookies" or something like that. This means that cookies in iframes will be ignored unless the domain name matches the outer page, for some arbitrary definition of "match". I notice you are using a non-fully-qualified hostname, which may confuse your browser's matching algorithm.

**Comment by brycefisher** [comment]
Yeah, turning off Do Not Track seems to have resolved the issue in Firefox.

Hmm, I'll try putting a .com or .io in the spoofed domain name and see if that works better with Do Not Track turned on...

**Comment by robinp** [comment]
For posterity, with current sandstorm - if you do a local setup with local DNS, be sure to use a fully qualified-alike domain. So, `mystorm.io` would work, but just `mystorm` will cause your cookie be very mysteriously eaten by major browsers.

(By the way, with an OpenWRT-based browser, it is easy to add a wildcard domain in LuCi: Network > DHCP and DNS, and stick in `Addresses` something like `/mystorm.io/1.2.3.4` just with your IP.)
