### ISSUE TITLE
Show app "marketing version" in UI

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#276]
The app manifest contains a field `appMarketingVersion` which is an arbitrary string that should indicate the app version (e.g. "1.23.9-alpha1~asheesh2" or whatever else you want). We should actually display this in the UI, and make sure our ports all fill this in, so that users can tell what version they have installed. Note that since old grains could be pinned to older versions, we'll need to have a way to inspect the version per-grain. Probably, we need to merge a bunch of the top bar functionality into a drop-down menu that could also include an "about" option, or something.

**Comment by ocdtrekkie** [comment]
I assume if an app does not have appMarketingVersion set, it should display appVersion instead?

**Comment by paulproteus** [comment]
FWIW I'd rather call this `appDisplayVersion` or `appVersionString` or something without marketing in the name, because I think marketing is sort of a distracting term here. But the ship has possibly sailed on that.

**Comment by kentonv** [comment]
@ocdtrekkie No, because we don't want to give app authors any excuse to abuse `appVersion`. E.g. I'd hate for someone to push a bugfix package and decide not to bump the `appVersion` because they didn't want the visible version number to change -- any new package build should _always_ bump the version number. The other thing is that users could be confused by `appVersion` in the case where the app has a marketing version but the packager forgot to specify it. Perhaps the field really should have been named `packageVersion` or `buildNumber`.

@paulproteus It may still be possible to change since it's not currently being used, but I actually didn't invent the term -- other systems use this term for this purpose. I don't find it distracting; I actually think it's very clear about its purpose.
