### ISSUE TITLE
Exception while invoking method 'updateApps' Error: No such package on server

### ISSUE THREAD

**Issue by strugee** [sandstorm-io/sandstorm#2772]
Today on my Sandstorm I got offered an update to Rocket.Chat version 0.46.0. However, clicking "apply updates" generated a JS alert that said "500 Internal Server Error."

Checking my `sandstorm.log`, I see the following:

```
Exception while invoking method 'updateApps' Error: No such package on server: 6fc85797bb55a4f8f140a18047b46759
    at packages/sandstorm-autoupdate-apps/autoupdate-apps.js:47:15
    at Array.forEach (native)
    at [object Object].updateApps (packages/sandstorm-autoupdate-apps/autoupdate-apps.js:44:14)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
```

Maybe the update got pulled or obsoleted, and my local Sandstorm isn't in sync? In any case, seems like there are two bugs to solve:

1. Improving usability when errors like this _do_ occur - the JS alert could be more specific about what actually happened
2. Making sure that this particular error (no such package on server) doesn't happen again

**Comment by kentonv** [comment]
It seems like what happened here is that the package got garbage-collected off your local machine before you managed to click the update notification.

We should check the garbage collection code and make sure that it doesn't collect packages that are still the subject of pending notifications.

**Comment by strugee** [comment]
@kentonv wouldn't surprise me if that was it. I don't use my Sandstorm very heavily (yet) so it'd been a couple months since I last logged in :thumbsup:

**Comment by dwrensha** [comment]
We [appear to check](https://github.com/sandstorm-io/sandstorm/blob/v0.196/shell/server/installer.js#L59-L61) whether a package is referenced by a notification before we garbage collect it, so I'm puzzled about how this could happen.

If I remember correctly, @zarvox recently reported seeing the same error on an Etherpad update.

**Comment by zarvox** [comment]
> If I remember correctly, @zarvox recently reported seeing the same error on an Etherpad update.

That's correct - my dev instance has an Alice Dev Admin with a notification about the Etherpad v20 update (packageId a3024432ac3868b1765de660e6c1ec7c), but indeed, that package is not in the DB:

```
ssrs:PRIMARY> db.packages.find({ appId: "h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60" }, { appId: 1, _id: 1, "manifest.appVersion": 1 })
{ "_id" : "a33e26d3b0fa40c658e2235dab438f1a", "manifest" : { "appVersion" : 11 }, "appId" : "h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60" }
{ "_id" : "19b0e88934e0f85d8b92e288a6c0a371", "manifest" : { "appVersion" : 16 }, "appId" : "h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60" }
{ "_id" : "576b16f6f0b9db12e7bec28bd24a5194", "manifest" : { "appVersion" : 13 }, "appId" : "h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60" }
{ "_id" : "a9fc7e902b320a695a54077a56daf8f4", "manifest" : { "appVersion" : 14 }, "appId" : "h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60" }
{ "_id" : "17a60a00262b707e0538d6b93d1804c7", "manifest" : { "appVersion" : 15 }, "appId" : "h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60" }
{ "_id" : "303601a2efeea5bf41bcc1696ec69471", "manifest" : { "appVersion" : 17 }, "appId" : "h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60" }
```

I am similarly perplexed as to how we get into this state.

**Comment by jparyani** [comment]
Looking at the package garbage collection led me to fix a small bug in how the autoupdate notifications are checked (#2780), but I'm not sure that's what you guys were running into here, since the bug was a very weird corner-case.

**Comment by strugee** [comment]
This should probably be reopened as #2780 contained the phrase "fixes #2772" but the full sentence was:

> I don't think this actually fixes #2772

which obviously shouldn't have caused this to be closed.

**Comment by zarvox** [comment]
That's a pretty hilarious accident.  Reopening.

**Comment by ocdtrekkie** [comment]
I kinda wonder if this has happened again since 2016, or if it was indeed fixed by the PR in question.

**Comment by strugee** [comment]
I haven't observed it since then that I can recall. Hard to tell though because I still rarely use my Sandstorm and it was always intermittent.

**Comment by strugee** [comment]
Might not be a bad idea to just close this if no one subscribed has seen it since and reopen if a new report comes in?

**Comment by ocdtrekkie** [comment]
I'm going to close it then. Nobody seems to be sure what caused it, a PR might've fixed it, and it's been a long time. Someone can always open an issue if we ever see it again.
