### ISSUE TITLE
Storage quota not displayed correctly for LDAP-quota users

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2778]
![quota](https://cloud.githubusercontent.com/assets/4001805/20685722/6634f436-b56a-11e6-9033-62defa025c29.png)

The customer reports that quota is being *enforced* correctly, it just isn't displayed right.

**Comment by zeigerpuppy** [comment]
Please note, as clarification, I am unsure why this is called an `LDAP-quota`.  

Our user authentication is occurring via SAML (which reads from an LDAP database).  The quota field is listed as `ssQuota` in our schema and is properly enforced for SAML authenticated users.   

Nevertheless, I have tried logging in the same users via LDAP  and the same behaviour occurs, the quota is enforced but not displayed.
Is it possible that the field name `quota` is hard-coded in the display routine but not the quota enforcement routine.  We could change our LDAP schema to have the quota field as `quota` but it would be preferable to keep it as `ssQuota` if possible.

**Comment by jparyani** [comment]
So the reason it's called LDAP quota is that it queries the LDAP server periodically to figure out what the quota is. The reason for this is that SAML is much harder to query dynamically.

So to make this whole system work, your users must have matching email addresses to query from their SAML user to the LDAP server. Before this change, that mapping wasn't working.

**Comment by zeigerpuppy** [comment]
Thanks for the clarification, that makes sense.  Our users do have matching email addresses but at the moment their email address is not used as the account unique identifier in SAML.

**Comment by zeigerpuppy** [comment]
I can confirm that the quota display is now functioning properly

**Comment by zeigerpuppy** [comment]
Just a cosmetic thing, but email users that don't have a quota setting, now show "1.6G of used"
Would it be possible to set this to "1.6G of Unlimited used" if there is no quota for that user.

It may also make sense to have a hard limit enforced somewhere, so that even without a quota, all users would have a limit (I'd probably set this to 100GB for our "unlimited" users).

**Comment by kentonv** [comment]
Hmm, are these e-mail users allowed to create grains at all? Presumably not, right? So it should always say zero bytes used. I agree the quota display should probably not be shown at all in this case, just trying to clarify.
