### ISSUE TITLE
login interstitial "go back" button can be unreachable if there are too many identities.

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#2784]
If my window is tall enough, I see the "go back" button:

![tall-enough](https://cloud.githubusercontent.com/assets/495768/20692589/f78a3824-b5a6-11e6-892e-3c0b0ebf3070.png)

But if the window is not tall enough, I don't see it:

![too-many-ids](https://cloud.githubusercontent.com/assets/495768/20692567/d3cca494-b5a6-11e6-9c99-27e6e39a4449.png)

and I cannot scroll down to it!

**Comment by neynah** [comment]
Yeah this is bad. :(

In addition to making it possible to scroll down to the "Go back" button we could also adjust the layout to show 2 identities per row instead of only 1.
