### ISSUE TITLE
Doesn't work on CentOS 7 after "successful installation"

### ISSUE THREAD

**Issue by doughnet** [sandstorm-io/sandstorm#2792]
Getting this error:
â sandstorm.service - Sandstorm server
   Loaded: loaded (/etc/systemd/system/sandstorm.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-12-01 23:39:59 UTC; 1s ago
  Process: 1059 ExecStop=/opt/sandstorm/sandstorm stop (code=exited, status=0/SUCCESS)
  Process: 1054 ExecStart=/opt/sandstorm/sandstorm start (code=exited, status=0/SUCCESS)
 Main PID: 1056 (code=exited, status=1/FAILURE)

Dec 01 23:39:59 SANDSTORM systemd[1]: Starting Sandstorm server...
Dec 01 23:39:59 SANDSTORM sandstorm[1054]: Sandstorm started. PID = 1056
Dec 01 23:39:59 SANDSTORM systemd[1]: Started Sandstorm server.
Dec 01 23:39:59 SANDSTORM systemd[1]: sandstorm.service: main process exited, code=exited, status=1/FAILURE
Dec 01 23:39:59 SANDSTORM sandstorm[1059]: Sandstorm is not running.
Dec 01 23:39:59 SANDSTORM systemd[1]: Unit sandstorm.service entered failed state.
Dec 01 23:39:59 SANDSTORM systemd[1]: sandstorm.service failed.

**Comment by zarvox** [comment]
Sorry to hear you're having trouble.

What does `/opt/sandstorm/var/log/sandstorm.log` contain?  If there's some sort of configuration error, posting your `/opt/sandstorm/sandstorm.conf` might also help us get to the bottom of things.

**Comment by orboan** [comment]
Here the same problem. This is the output of /opt/sandstorm/var/log/sandstorm.log :

...
ERROR: child process failed, exited with error number 100
*** Uncaught exception ***
sandstorm/run-bundle.c++:2139: failed: **mongod failed to start. Initial exit code: ; status = 100; bailing out now. For troubleshooting, read /opt/sandstorm/var/log/mongo.log (or var/log/mongo.log within your Sandstorm if installed to a different place) and visit: https://docs.sandstorm.io/en/latest/search.html?q=mongod+failed+to+start
stack: 0x4c1404 0x4bd6df 0x4b9e74 0x4b9009 0x4b8ffa 0x504f7d 0x505a80
** Server monitor died. Aborting.
** Starting Sandstorm at: Wed Mar 29 14:35:26 2017
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 8
ERROR: child process failed, exited with error number 100
*** Uncaught exception ***
sandstorm/run-bundle.c++:2139: failed: **mongod failed to start. Initial exit code: ; status = 100; bailing out now. For troubleshooting, read /opt/sandstorm/var/log/mongo.log (or var/log/mongo.log within your Sandstorm if installed to a different place) and visit: https://docs.sandstorm.io/en/latest/search.html?q=mongod+failed+to+start
stack: 0x4c1404 0x4bd6df 0x4b9e74 0x4b9009 0x4b8ffa 0x504f7d 0x505a80
** Server monitor died. Aborting.

**Comment by kentonv** [comment]
Hi Oriol,

Did you try the troubleshooting steps here? https://docs.sandstorm.io/en/latest/administering/faq/#mongod-failed-to-start-whats-going-on

If that doesn't help, let us know what's in your mongo.log.

**Comment by ocdtrekkie** [comment]
Closing for lack of response.
