### ISSUE TITLE
No grains can be created with standard setup on Ubuntu Server 16.04

### ISSUE THREAD

**Issue by classner** [sandstorm-io/sandstorm#2798]
Hi Sandstorm team,

I just set up a fairly standard installation on Ubuntu Server 16.04 using github as identification method. Sandstorm runs, but it is not possible to create grains.

The grain display only shows:

~~~~~
Error: remote exception: expected result >= minBytes; Premature EOF
    at Error (native)
C++ location:(remote):??
type: failed
~~~~~

From the sandstorm logfile:

~~~~~
capnp/rpc.c++:142: info: returning failure over rpc; exception = kj/async-io.c++:1322: failed: expected result >= minBytes; Premature EOF
stack: 0x4a8662 0x59eb00 0x59f160 0x59f790 0x59cf60 0x5a1360 0x425350
Exception while invoking method 'keepSessionAlive' Error: remote exception: expected result >= minBytes; Premature EOF
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at waitPromise (imports/server/async-helpers.js:39:35)
    at [object Object].keepSessionAlive (server/proxy.js:474:9)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    - - - - -
    at Error (native)
~~~~~

**Comment by classner** [comment]
Found #1883 and think it's related to the wildcards not being resolved properly. I'll find out and close this issue if this is the reason.

**Comment by classner** [comment]
The problem persists with a sandcats domain. :-/ Any ideas to find out more?

**Comment by dwrensha** [comment]
Have you checked the grain logs, as described [here](https://github.com/sandstorm-io/sandstorm/issues/1883#issuecomment-213101041)?

**Comment by classner** [comment]
Thank you for the pointer! Just checked the grain logs, and for all grains, the log contains:

~~~~~
sandstorm/supervisor.c++:1206: failed: seccomp_load(ctx): Invalid argument
stack: 0x5bc042 0x5bb9fe 0x5cc9a9 0x5cc99a 0x494e5d
~~~~~

**Comment by classner** [comment]
Could this issue be related to https://github.com/scaleway/kernel-tools/issues/250 and #1759? I am using hosteurope as provider and I think they tinkered with the kernel as well...

**Comment by dwrensha** [comment]
Yes, it sounds like the kernel you're using has been compiled without seccomp support. Does hosteurope provide any way to choose which kernel is used? Even if so, it's surprising that the default kernel they gave you does not have seccomp. It might be good to contact hosteurope support and alert them to the issue.

**Comment by classner** [comment]
Unfortunately not! There is only a standard kernel per OS version that can be used. Thank you for the quick response, I'll contact the hosteurope support!

Is there any way to circumvent the issue in the meanwhile (I read Kenton's comments in the other threads, is there any update on this)?

**Comment by dwrensha** [comment]
I don't know of anything new on our side.

**Comment by classner** [comment]
Checked with hosteurope, and they do not offer "kernel access" for the virtual servers. :( No sandstorm there, then.

Would be great if you would allow an option to compile without the SECCOMP features if people really want to do it. I'll close the issue for now.

**Comment by kentonv** [comment]
@classner Could you ask hosteurope why they disabled seccomp?

IMHO this is a very weird thing to do. Apparently they went out of their way to disable a standard feature of the Linux kernel, and I can't think of any reason why they'd want to do that. IMO your hosting provider is providing a broken service and if I were you I'd look for a different provider that doesn't randomly cripple their kernels.

It's kind of like if you rented a car and found that all the door locks were removed. You ask the rental agency "Can I get a car with door locks?" and they just say: "Sorry, we've removed the door locks from all our cars. The cars work fine without them."

But why would you do that???? :/

**Comment by classner** [comment]
Hi Kenton!

I will do that for the next server migration! It's also quite annoying in other parts of the server setup... Their answer was quite definitive, so I'm not going to follow up. But I couldn't agree more: this is not the way vservers should be configured. The only reason I could think of is marketing: it prevents 'sub-virtualization', forcing customers to move to root servers if they want to run virtualized packages. Only speculating...

Thanks for checking this!
