### ISSUE TITLE
cannot start after system update?

### ISSUE THREAD

**Issue by mpkosewski** [sandstorm-io/sandstorm#2801]
Ok in short, a couple weeks ago I found my server box was off for some reason and didn't turn it back on until tonight. I did an "apt-get update" for my server box (a flavor of debian jessie) since it's been a while since it's been updated. And now for some reason I can no longer start sandstorm. I used to be able to restart my system and start sandstorm no problem. But for some reason, after I run "service sandstorm start" and type in my url as I normally would, it just constantly loops in a "waiting for litterbox.sandbox.io". The only thing that I know that's changed has was the system update. Its been a while since I've ran it so I'm not sure if I'm missing something or what. 

Also if it helps, I've setup sandstorm with apache2. I tried starting apache2 before and then sandstorm and vise-versa and still no luck. If I start the apache2 service before sandstorm, I get the default apache2 webpage. I re-read through as many docs/instructions I could find on the sandstorm site for setting up it up to try and refresh my memory. 

My guess is theres something now mis-configured within apache2 or something may have got reset during the system update. 

Here is my logfile for sandstorm if it helps. 
[sandstorm.txt](https://github.com/sandstorm-io/sandstorm/files/648519/sandstorm.txt)

If you need any more info let me know. I appreciate your guy's patience and help! 

-Mike

**Comment by dwrensha** [comment]
These lines seem relevant:

```
SANDCATS_BASE_DOMAIN is configured but your HOSTNAME doesn't appear to contain it: litterbox.tech litterbox.sandcats.io
No key, so can't listen for HTTPS yet. Will retry in three seconds.
No key, so can't listen for HTTPS yet. Will retry in three seconds.
No key, so can't listen for HTTPS yet. Will retry in three seconds.
```

It looks like your `/opt/sandstorm/sandstorm.conf` file might have some issues.

Does it work if you change your `BASE_URL` to `https://litterbox.sandcats.io` and your `WILDCARD_HOST` to `*.litterbox.sandcats.io`?

Alternatively, if you don't want to use the free sandcats wildcard certificate, does it work if you remove the `HTTPS_PORT` and `SANDCATS_BASE_DOMAIN` lines?

**Comment by mpkosewski** [comment]
thats actually how I have it setup. For now I'm perfectly fine with the sandcats certs, I just want to get it up and running before I make too many modifications :)

**Comment by dwrensha** [comment]
What's in your configuration file for `SANDCATS_BASE_DOMAIN`? I think it should be `sandcats.io`.

**Comment by mpkosewski** [comment]
SANDCATS_BASE_DOMAIN=litterbox.tech
aahhhhh....so maybe something changed after recent sandstorm update? I know i had an issue with this domain not being setup completely correct but previously it just took me to a notification page with a redirect link. I'll change that as well when I get home tonight from work :)

**Comment by paulproteus** [comment]
FWIW please try the following:

`SANDCATS_BASE_DOMAIN=sandcats.io`

in your sandstorm.conf, and restart Sandstorm.

I'm the maintainer and main author of the sandcats.io service, and I've seen lots of people think that the should change `SANDCATS_BASE_DOMAIN`, but the only reason that config line exists is so that I can test the sandcats code against a different API host. I really should have called it `SANDCATS_API_ENDPOINT_URL` or something like that. Oops.

So please try the above and I think you'll be happy.

At some point, it seems like you do want to change the URL to be `litterbox.tech`. By all means let's work on that, too, but I don't want you to be misled about which config entries cause which changes in behavior.

**Comment by mpkosewski** [comment]
All good. Just glad I asked cuz I spent a whole weekend getting a crash course in learning more about and setting up my own domain, dns, server and cloud. My brain is still getting used to wrapping around it all. Not my area of expertise lol 

But yeah I'll try it tonight and update with what happens. Once that's done, then yeah I'd love to try and make it litterbox.tech. 

My end goal is to have my own secure cloud that isn't apart if Google Drive or Dropbox or whatnot and be able to share with roommates and a few friends etc. :)

**Comment by mpkosewski** [comment]
ehhh just as I feared....I still get the apache2 default html page =/

**Comment by mpkosewski** [comment]
Ah ha!!! fixed it! Here's where my intuition led me to try after reading over part of one of your docs.
I commented out the listening port for apache2. So basically:



Here's where on your doc's that really kinda pushed me to try this:

> If you are using nginx to speak HTTPS on port 443 and HTTP on port 80, you should disable that before proceeding.
