### ISSUE TITLE
Error during vagrant-spk dev in meteor project.

### ISSUE THREAD

**Issue by aruntk** [sandstorm-io/sandstorm#2810]
I'm facing the following issue during `vagrant-spk dev`. I've tried installing node-gyp, reinstalling meteor and node, resetting the project, rebuilding packages etc. But none worked. I'm on osx sierra. 

Source code - https://github.com/CommonGarden/Grow-IoT/tree/sandstorm

<img width="686" alt="screen shot 2017-01-01 at 5 08 51 am" src="https://cloud.githubusercontent.com/assets/6007432/21579616/fa5c6f82-cfe0-11e6-96b6-7024d64a3599.png">
<img width="706" alt="screen shot 2017-01-01 at 5 09 09 am" src="https://cloud.githubusercontent.com/assets/6007432/21579617/fa62e970-cfe0-11e6-8d2b-55d1941fb4c7.png">

**Comment by dwrensha** [comment]
Which Meteor version are you using? 1.4+ won't work without some fiddling, unfortunately. https://github.com/sandstorm-io/vagrant-spk/issues/193

[Rocket.chat](https://github.com/RocketChat/Rocket.Chat) has figured out how to use a newer Meteor with vagrant-spk, but if I remember correctly it isn't super pretty.

**Comment by aruntk** [comment]
1.4.2.3. The latest version as of now.

**Comment by aruntk** [comment]
solved by changing sandstorm sh files. 
https://github.com/CommonGarden/Grow-IoT/tree/sandstorm
