### ISSUE TITLE
Wekan cards are unable to be clicked in Android (Samsung Galaxy S7 Edge)

### ISSUE THREAD

**Issue by kodb-avv** [sandstorm-io/sandstorm#2813]
Sandstorm comes up fine in Chrome browser and I am able to manipulate cards and choose grains.  However, when tapping on the card it will not open in Chrome on the phone.
Android 6.0.1 with October 1, 2016 security patch.
kernel 3.18.20
Samsung model # SM-G935V

**Comment by kentonv** [comment]
This sounds like a bug in Wekan. I suggest filing it against the Wekan project here:

https://github.com/wefork/wekan/issues

(I'm closing this issue since it's not a bug in Sandstorm itself, but thanks for reporting!)
