### ISSUE TITLE
mrdomino radio is down

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/sandstorm#2828]
My groovebasin instance seems to have stopped working -- across restarts of the grain, the sandstorm instance, and the whole VM. The grain just never comes up. All other grains seem to be working fine. The logs are not much help for the grain:

```
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
shm_open() failed: Function not implemented
```

and there's nothing special in the system log either. There seems to be plenty of RAM, load averages are sub-1.0, nothing else looks out of the ordinary.

For reference the grain in question is https://mrdomino.sandcats.io/grain/LocTtiaStkTv3HSNRFbYM3

**Comment by kentonv** [comment]
How strange! When did it stop working? There hasn't been a groovebasin package update in a long time, and nothing has changed in the supervisor lately. Have you updated the underlying OS at all (particularly the kernel)?

**Comment by kiwano** [comment]
The kernel on the host server (the sandstorm instance is running in an LXC container, so same kernel) hasn't been updated in the past 82 days, and the problem with the groovebasin instance is about a week old. (The most recent reboot of the host server was to upgrade the kernel in response to the dirtycow vulnerability.)

**Comment by mrdomino** [comment]
Yes, this is very mysterious. It happened while I was on retreat, so I don't think it was an (at least manual) upgrade...

**Comment by kiwano** [comment]
unattended upgrades on the underlying os don't seem to be a thing on the server in question, so that's another potential source of problem that can be ruled out

**Comment by kentonv** [comment]
The `shm_open()` error seems to be normal, so that's a red herring. Are there no other messages in the debug log?

Stab in the dark: Are you out of disk space?

**Comment by kiwano** [comment]
still about 2.4TB of unused disk space on that filesystem, so it's not disk space; it may be something glitchy with groovebasin itself (we spun up 2 more instances, the first of which died while copying over the library from the first dead instance -- but the second seems to be running now)

**Comment by kentonv** [comment]
Presumably its database is in a bad state but annoying that it doesn't report any errors...

**Comment by ocdtrekkie** [comment]
I'm going to close this one as it appears to be a corrupted grain of a particular app. I don't think there's an action item here for the Sandstorm project.
