### ISSUE TITLE
Cannot delete notebooks in Paperwork (CSS bug?)

### ISSUE THREAD

**Issue by xarinatan** [sandstorm-io/sandstorm#2829]
Hello,
I couldn't find a place to specifically report bugs for Paperwork, and saw there was one previous bugreport for that app here, so I figured I'd put it up here.

The paperwork app seems to work well, aside from 2 things, which is uploading attachments and deleting notebooks.

The notebook deletion bug however seems to be simply CSS related.. if I select a notebook, go to 'edit' and hit 'delete notebook' the entire interface 'freezes' and if I open it up with the developer tools, I see an invisible div popped up in front that's called 'modalNotebookDelete'. 

Might be easy to fix? It would be really nice to be able to delete notebooks in any case :)

**Comment by ocdtrekkie** [comment]
The best place to file issues is with that app's GitHub repository. If you check the Sandstorm App Market, you'll see a Report Issue button on the top right (which also appears on the app detail page of Sandstorm as well): https://apps.sandstorm.io/app/vxe8awcxvtj6yu0vgjpm1tsaeu7x8v8tfp71tyvnm6ykkephu9q0 which leads here: https://github.com/JamborJan/paperwork/issues

**Comment by xarinatan** [comment]
Oh I didn't see that icon there, thank you! I'll submit my issue there as it doesn't seem to be on their tracker yet :)
