### ISSUE TITLE
Send Invite: Failed to send to ... E-mail delivery failure: Error: No such grain: spameri

### ISSUE THREAD

**Issue by benwinding** [sandstorm-io/sandstorm#2830]
Hey Guys,

Here's what I've setup in my sandstorm configuration:

- Google account, logged in as admin
- Mailgun email linked to **Admin Panel > Mail Configuration** - Test successfully sends emails

However, on all my grains, I can't Share Access and send invites to any emails, it just displays the following message in the UI:

    Failed to send to: example@email.com

And in the **Admin / System Log** it displays the following error relating to email:

```
E-mail delivery failure: Error: No such grain: spameri
    at server/drivers/mail.js:145:25
    at imports/server/async-helpers.js:24:17
    at imports/server/async-helpers.js:12:3
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at packages/meteor/dynamics_nodejs.js:123:1
    at imports/server/async-helpers.js:22:5
    at inMeteor (imports/server/async-helpers.js:21:10)
    at tryDeliver (server/drivers/mail.js:137:22)
    at server/drivers/mail.js:179:20
    at Array.map (native)
```

Any help in resolving this would be much appreciated.

Thanks,
Ben

**Comment by kentonv** [comment]
The system log error you copied is an error when mail is being sent *to* Sandstorm. It looks like someone tried to send an e-mail to `spameri@<your server>`, which failed.

But the problem you're describing is going the other way.

Are there any other error messages in the system log, that repeat every time you try to send a sharing email?

**Comment by benwinding** [comment]
Hi Kentonv,

I looked in the system log and the debug logs of each grain, but could not find any messages at all that were popping up after I pressed **share access** within a grain.

I opened the chrome developer tools and noticed this message:

`Error: Message failed: 554 Free accounts are for test purposes only. Please upgrade or add the address to authorized recipients in Account Settings.`

Do I need a paid account to share access to grains? Even when hosting my own instance?

Cheers,
Ben

**Comment by kentonv** [comment]
Whoops, indeed, that looks like the error Mailgun gives if you are using a "sandbox" account.

Unfortunately Mailgun currently cannot be used with Sandcats because Sandcats doesn't provide the necessary SPF DNS records, which Mailgun refuses to operate without. Some other mail delivery services seem to be willing to work without these. Though, ideally we'd engineer some way for users to set these records...

**Comment by benwinding** [comment]
Yes, it seems that with the free _sandbox account_, you need to add authorized email addresses to Mailgun, which is kind of annoying (no free lunch I guess).

So, I'm using my hosting provider's email account system, _(Siteground)_ and it's working now! :+1: 

One last thing to note, is that I was getting the error: `550 Relay Not Permitted`, until I made following two fields the same. _I think Siteground throw this error to prevent spam from hiding the true email._

![image](https://cloud.githubusercontent.com/assets/11782590/22250568/50e49866-e297-11e6-90f1-eb1ae311ec23.png)

Thanks for your help Kentonv!
