### ISSUE TITLE
Unable to find other users on same sandstorm server

### ISSUE THREAD

**Issue by francis-specialeffect** [sandstorm-io/sandstorm#2831]
First off, Sandstorm is awesome, been following the project for a while now but have only recently started using it.

On my initial install everything was working perfectly and I was able to share grains with other members of the server by typing their name in the 'Send an invite' of 'Share Access' and pressing SEND. I then decided I would need more RAM and so completely reinstalled on a new server, under the same domain, in a completely identical manner. Everything was working as it was, except that when trying to share grains as I had done before, other user's names do not appear on the 'Send an invite' option, and typing in their full name returns 'Unknown user "user". Try entering an e-mail address.'

However, the users do appear in the Users section of the Admin panel, and I've tried making a few test users on different authentication providers and still no luck, any ideas? I'm lost :(

**Comment by francis-specialeffect** [comment]
OK, so this was me not realising that you have to have sent the user a share grain link in the past and for them to reveal their identity to you, before you can just add them by name. So problem solved, but I'm going to leave this open as I feel like though this is probably the best way to handle contacts, it is perhaps not well documented enough. 

I wonder if it would be good to have the option to add contacts without sharing a grain via link, a contacts page of sorts. Perhaps there is and I'm just being ignorant, but I have gone through the documentation and can't find a lot of information when it comes to sharing grains.

**Comment by ocdtrekkie** [comment]
This is mostly a privacy feature, as in general, users won't know about other users on a Sandstorm server unless it is a organization one. (And Sandstorm for Work makes it easy to mark all organization users as visible to each other.)

As an admin, you obviously can see all of the users in the admin panel, though it is worth noting that that doesn't mean you want to share with them necessarily, especially on a large public Sandstorm server, so my guess is admins probably don't want contact overload by default.

Documentation on how contacts work is probably a good idea, I don't see anything useful on Sandstorm's docs about the topic outside of the organization settings for Sandstorm for Work.

**Comment by francis-specialeffect** [comment]
Yeah, I agree that this probably is the best way to handle contacts at the moment, and some additional documentation would be good. But I still think there's a potential feature to be had with a way to manage contacts regardless of whether or not you're using Sandstorm for Work.

Currently the only way to view your contacts as far as I can see is to 'Share Grain' and 'Send an invite'. This is fine and works, but I feel like it could be improved. My suggestion would be to have a contacts page of sorts on the sidebar, where you can view and manage everyone with whom you've shared your identity. This would also make it possible to add contacts without sharing a grain via link, which is just slightly neater and more intuitive in my opinion. You could also from the contacts page, have the ability to remove contacts, and share grains from there, though that might be overly complicating things.

**Comment by francis-specialeffect** [comment]
Making a seperate issue :)
