### ISSUE TITLE
Tried to build with clang even though it isn't available

### ISSUE THREAD

**Issue by strugee** [sandstorm-io/sandstorm#2834]
When I clone Sandstorm on my Arch Linux system and invoke `make`, I get a bunch of normal output and then a bunch of errors ending with the following:

```
[snipped]
compile: kj/test.c++
  src/ekam-rules/compile.ekam-rule: line 119: clang++: command not found
compile: sodium/crypto_onetimeauth_poly1305/donna/poly1305_donna.c
compile: sodium/crypto_onetimeauth_poly1305/onetimeauth_poly1305.c
  src/ekam-rules/compile.ekam-rule: line 119: clang: command not found
compile: joyent-http/http_parser.c++
  src/ekam-rules/compile.ekam-rule: line 119: clang++: command not found
==== build failed. You might need to: make update-deps ====
make: *** [Makefile:257: tmp/.ekam-run] Error 1
```

The result of `make | sponge sandstorm-make-log.txt` can be found [here](https://github.com/sandstorm-io/sandstorm/files/733085/sandstorm-make-log.txt). I'm happy to provide more debugging, but I'm not sure where to look.

Here's some version info:

```
% gcc --version
gcc (GCC) 6.2.1 20160830
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

% make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by kentonv** [comment]
There's documentation here on prerequisites for building Sandstorm:

https://docs.sandstorm.io/en/latest/install/#option-4-installing-from-source

It looks like you are missing Clang.

I suppose the bug here is that this section of the docs wasn't easy to find. Any suggestions on how we could make it more visible?

**Comment by strugee** [comment]
@kentonv ah yeah. I got confused since (IIRC) the `ekam` docs said it worked on GCC.

I didn't think to look there because I associate docs.sandstorm.io with administrative documentation. The most basic fix to this would be just putting a section in README.md on how to contribute with links to e.g. that page, but having a dedicated CONTRIBUTING.md would be better. That's where most projects I see have docs on how to contribute - in the same repo.

**Comment by wdk122** [comment]
I'm getting similar error messages installing from source on a fresh instance of Debian Jessie, following the installing from source instructions in the Sandstorm docs. Running `make` after cloning and entering the Sandstorm repo produces [this output](https://gist.github.com/wdk122/fa606661afd4ce0c0dc3d66366595933) on my machine. Here's a subset of the output:
```
...
[RUNNING] learn: capnp/compiler/capnp-test.ekam-rule
[BLOCKED] learn: capnp/compiler/capnp-test.ekam-rule
[RUNNING] learn: capnp/bootstrap-test.ekam-rule
[BLOCKED] learn: capnp/bootstrap-test.ekam-rule
[FAILED ] learn: capnp/compiler/capnp-test.ekam-rule
src/capnp/compiler/capnp-test.sh: 41: src/capnp/compiler/capnp-test.sh: src/capnp: c
cmp: EOF on -
FAILED: encode
[FAILED ] compile: sodium/crypto_core/hsalsa20/ref2/core_hsalsa20_ref2.c
src/ekam-rules/compile.ekam-rule: 119: src/ekam-rules/compile.ekam-rule: clang: not found
[FAILED ] compile: sodium/crypto_core/hsalsa20/core_hsalsa20.c
src/ekam-rules/compile.ekam-rule: 119: src/ekam-rules/compile.ekam-rule: clang: not found
[FAILED ] compile: sodium/crypto_core/salsa/ref/core_salsa_ref.c
src/ekam-rules/compile.ekam-rule: 119: src/ekam-rules/compile.ekam-rule: clang: not found
[FAILED ] compile: kj/common.c++
src/ekam-rules/compile.ekam-rule: 119: src/ekam-rules/compile.ekam-rule: clang++: not found
...
```
My `which clang` command produces no output, but `which clang-3.4` produces `usr/bin/clang-3.4`.

**Comment by strugee** [comment]
I'm guessing `/usr/bin/clang` is supposed to be managed by dpkg's alternatives system? @wdk122 `sudo dpkg-reconfigure clang` or `sudo dpkg-reconfigure clang-3.4` _might_ fix this problem, but I'm really not sure as I'm not a dpkg expert.

**Comment by kentonv** [comment]
Hey Bill,

Two options:

1. Install the package `clang` (no version number), which should install a relatively new version of Clang and set up the commands with no suffix. (We should probably update the docs to suggest this.)

2. You can instruct the build to use a specific `clang` by setting environment variables when running `make`:

    CXX=clang++-3.4 CC=clang-3.4 make

**Comment by zenhack** [comment]
I think we can close this; the build pulls in clang itself now.
