### ISSUE TITLE
"Disallow Collaboration" Will Block Admin Login Via GitHub

### ISSUE THREAD

**Issue by epiepo** [sandstorm-io/sandstorm#2862]
After selecting "Disallow Collaboration" via the Organizational Settings in the Admin Panel, all admin-account logins via GitHub don't work. The user is admin user logged out and any new login via GitHub redirects to the Sign-In page of Sandstorm. 

This doesn't happen for non-admin users. The only way to work around this issue is to choose a user account, issue a new admin-token, promote this user to Admin and disable the "Disallow Collaboration" setting. 

Fully reproducible.

**Comment by LyR33x** [comment]
I dont know why this is closed, that issue is still not fixed

**Comment by zenhack** [comment]
This looks like a dupe of #2863, which is still open. I imagine @epiepo accidentally created the same issue twice and then closed this one.
