### ISSUE TITLE
Docs: Meteor packaging tutorial is out of date

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#2866]
> Compatibility note: Sandstorm's Meteor tooling is currently compatible with Meteor 1.3.5.1 and earlier. If your app uses Meteor 1.4, you may need to wait until September 2016 for an updated vagrant-spk that is compatible with Meteor 1.4.

https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial-meteor/

It's way past September 2016, and meteor-spk 0.3.1 is supposed to support Meteor 1.4.2. I am still playing with meteor-spk at the moment and I don't know if the vagrant-spk method in the tutorial works so I don't want to just submit a PR to delete this line, but there's definitely some updates needed.

**Comment by kentonv** [comment]
The note applies to vagrant-spk. I don't really understand the details but apparently vagrant-spk needs some sort of separate update to support Meteor 1.4 and it never happened. :/

**Comment by ocdtrekkie** [comment]
The meteor-spk readme suggests that vagrant-spk's meteor stack is "the" way to package Meteor apps, so if the vagrant-spk support doesn't work, we should probably adjust that recommendation. While the app I was trying to package was kinda buggy in itself, I think, meteor-spk did reasonably seem to package it with 1.4.2.6.
