### ISSUE TITLE
Demo Mode weirdness if already logged in

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#288]
"Somehow, you seem to have attempted to launch a package you have not installed." alert comes up when I've previously installed an app on my logged in demo account.

This message at first seems really weird, but here's my theory. When Sandstorm sees that I have old Libreboard installed, it doesn't install new Libreboard because that's redundant. And then, when Sandstorm tries to launch new Libreboard, it's confused about why it can't.

How to repro:
1. Click on "try on sandstorm" link ([screenshot](https://www.evernote.com/shard/s59/sh/31f72c29-243b-4c63-8816-7e52e63d054c/efba47bcde2acab53e5fb414d9ee2d7f/deep/0/Libreboard.png)). Make sure this is an app you have installed a while ago. (If I uninstall Libreboard and try this again, the problem goes away. I didn't confirm (oops), but I suspect I had an older version of Libreboard already installed?)
2. Launch the demo ([screenshot](https://www.evernote.com/shard/s59/sh/a1c57589-8c39-4ab3-be94-970ad13b4a6e/32df199469fd1a3df372bd91e23e16f6/deep/0/Sandstorm.png))
3. This alert pops up. "Somehow, you seem to have attempted to launch a package you have not installed." ([screenshot](https://www.evernote.com/shard/s59/sh/8e4ed081-fc8d-4bfb-bc20-93db9074de63/ae0ba8837381d4a74ee66cf3afdd25ab/deep/0/Blank-Skitch-Document.png))

**Comment by paulproteus** [comment]
I think the theory is right!

I kind of wonder if for appdemo purposes we should refuse to operate if you're already logged in?

I'm reminded of the following joke:

Q. What does a hacker do when confronted with a function that works improperly for some values in the domain?

A. The hacker changes the domain.

**Comment by paulproteus** [comment]
I guess if you already have the app installed, one thing it could do is take you to whatever version you _do_ have installed. That probably makes sense.

**Comment by paulproteus** [comment]
@neynah says this is closed, so I am going to mark it as such!
