### ISSUE TITLE
Etherpad 1.6.1~2017-03-03 breaks display of UL & LI formatting

### ISSUE THREAD

**Issue by kotowicz** [sandstorm-io/sandstorm#2881]
[ Not sure this is the right place to report this bug ]

my sandstorm instance informed me about an update of Etherpad today. After upgrading Etherpad to version 1.6.1~2017-03-03 we experience incorrect display of formatted text. This affects mostly bullet lists and indentations. This appears to be a display issue in the editor, since the revision history displays things correctly.

**Editor View:**

![screenshot from 2017-03-07 13 53 33](https://cloud.githubusercontent.com/assets/592595/23657390/24b30922-033e-11e7-9628-1d60c020328c.png)

**Revision View:**

![screenshot from 2017-03-07 13 53 40](https://cloud.githubusercontent.com/assets/592595/23657395/2ab9f1f0-033e-11e7-8a2f-0231958efbb5.png)

We experience the same issue across different browsers and OSes.

**Comment by ar-jan** [comment]
Can confirm that lists don't work in the new version. Should probably be filed in https://github.com/kentonv/etherpad-lite.

**Comment by kotowicz** [comment]
@ar-jan: see this [link](https://oasis.sandstorm.io/shared/OeXLBgPOvYiH3W9P9yAlbzc5dlgVZiRT-N-8K7yZbXz) for a simple example - list is rendered correctly in the Timeslider view but not the pad itself:

![screenshot from 2017-03-07 18 57 05](https://cloud.githubusercontent.com/assets/592595/23670447/fef23c2e-0367-11e7-85aa-0009ec1eec8e.png)


![screenshot from 2017-03-07 18 57 17](https://cloud.githubusercontent.com/assets/592595/23670449/020c5d0e-0368-11e7-9a70-51ea690f8b70.png)

this behaviour is new since today - not sure what's causing it.

**Comment by kentonv** [comment]
Oh my god, Etherpad's runtime asset minification pipeline is held together by duct tape and twine.

Working on a fix...

**Comment by kentonv** [comment]
Ugh that was surprisingly painful. Fix is up -- you can force an update by re-installing from the app market, or wait for the auto-update within 24 hours.

**Comment by kentonv** [comment]
BTW, for future reference, the best place to report Etherpad-Sandstorm issues is: https://github.com/kentonv/etherpad-lite

Thanks for reporting this!

**Comment by ar-jan** [comment]
Thanks for the quick fix!
