### ISSUE TITLE
Wordpress app database no connection

### ISSUE THREAD

**Issue by ktdocker90** [sandstorm-io/sandstorm#2882]
i have to test wp app repository develop by you! But wordpress show installation page, prompt filling database information page.
![screencapture-local-sandstorm-io-6080-grain-lzphyybhw83ls5g5s7cuhb-1488873637570](https://cloud.githubusercontent.com/assets/17218942/23658215/3952026c-0374-11e7-9522-a7361c958119.png)

**Comment by dwrensha** [comment]
That looks like what would happen if you dropped a plain WordPress install into a VM using the base LEMP vagrant-spk stack. Did you try https://github.com/dwrensha/wordpress-sandstorm ? It should handle of the configuration automatically.

**Comment by ktdocker90** [comment]
give me details commands, please.

**Comment by kentonv** [comment]
Closing because this isn't a Sandstorm bug.

(I don't know how to answer the question about "details commands", sorry.)
