### ISSUE TITLE
How to suggest apps to Sandstorm?

### ISSUE THREAD

**Issue by MatheusRV** [sandstorm-io/sandstorm#2884]
I have a list of good apps, with categories and description. Where could I place this apps request?

**Comment by ocdtrekkie** [comment]
The official location is technically at https://sandstorm.io/vote though you cannot vote on them (only submit them), and very few people (if anyone) still looks at that list.

You can also submit a list to the Sandstorm-dev mailing list: https://groups.google.com/forum/#!forum/sandstorm-dev

And then finally, I operate a couple of newer lists that you may or may not want to participate in or look at:

Ports in Progress: http://sandsheep.com/pip is basically a list of apps that someone has tried to port at some point or another, but isn't listed in the App Market. Many of them are incomplete, but you may find some workable options in there.

Bounty Board: http://sandsheep.com/bb is where you can post requests for things to be done along with an amount of money you'd offer up to the developer who does the work. There are both some specific app porting bounties there as well as some general bounties offered to any new apps submitted to the market.

**Comment by kentonv** [comment]
Hi @MatheusRV,

Thanks for offering suggestions, but note that what we really need is volunteers to actually do the work -- or people willing to offer money to pay other people to do the work. :)

Closing this thread since I think the question has been answered.
