### ISSUE TITLE
Broken Image Files

### ISSUE THREAD

**Issue by GGRIFFIN53** [sandstorm-io/sandstorm#2886]
Upon attempting to upload an image within a grain created for a class the image appears as broken on the site. I have attempted to upload an image through both Chrome as well as Firefox. The image appears broken regardless of it being a png or jpg file. I am using a Dell Inspiron 15 that is running Windows 10. I am unsure as to whether the problem is stemming from my computer or from the platform itself.

**Comment by dwrensha** [comment]
Which app is the grain an instance of?

**Comment by GGRIFFIN53** [comment]
Using the GitLab app

**Comment by kentonv** [comment]
This sounds like a bug in the GitLab app rather than Sandstorm. Can you report it here instead: https://github.com/dwrensha/gitlab-sandstorm/issues

Thanks!
