### ISSUE TITLE
spk dev seems broken on Ubuntu 16.10

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/sandstorm#2888]
Steps to reproduce:

```bash
mkdir foo
cd foo
cat >>start.sh <<EOF
#!/bin/sh
nc -l 8080
EOF
spk init -p8080 /start.sh
spk dev
```

Expected results: the example app is available for development in Sandstorm. This is the case on Ubuntu 14.04.

Actual results on Ubuntu 16.10:

```
App is now available from Sandstorm server. Ctrl+C to disconnect.
*** Uncaught exception ***
sandstorm/fuse.c++:369: failed: read(/dev/fuse): Input/output error
stack: 0x57d1ee 0x57a709 0x622269 0x620c9d 0x463ddd 0x4648e0
```

**Comment by mrdomino** [comment]
Looks like the same issue as #2526.

**Comment by urakagi** [comment]
This issue still seems to exist. Is downgrading to 15.10 or even 14.04 LTS a better idea?
