### ISSUE TITLE
Backup error 

### ISSUE THREAD

**Issue by lapieh** [sandstorm-io/sandstorm#2892]
I have `Error: Backup failed: Error: Internal server error [500]` when I want to archive a grain. The installation of sandstorm is recent (Debian Jessie) via curl + bash.

In `/opt/sandstorm/var/log/sandstorm.log`  : 
```
*** Uncaught exception ***
sandstorm/util.c++:56: failed: open(name.cStr(), flags, mode): Permission denied; name = metadata
stack: 0x5078f0 0x50a543 0x463b05
capnp/rpc.c++:142: info: returning failure over rpc; exception = sandstorm/util.c++:995: failed: expected exitCode == 0; child process failed; name = backup; exitCode = 1
stack: 0x5b4c7c 0x47aa62 0x5271e0
Exception while invoking method 'backupGrain' Error: remote exception: expected exitCode == 0; child process failed; name = backup; exitCode = 1
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at waitPromise (imports/server/async-helpers.js:39:35)
    at [object Object].backupGrain (server/backup.js:66:5)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    - - - - -
    at Error (native)
```
The start of the zip file is present with the owner's permissions 644 (no writable) ....
Did I miss something ?

Thx

**Comment by dwrensha** [comment]
User `astuce` reported the same problem on IRC this morning: https://botbot.me/freenode/sandstorm/2017-03-15/?msg=82470008&page=1

It seems likely that the problem has to do with https://github.com/sandstorm-io/sandstorm/commit/4ea8df7403381d9b657b121b3c98d8081b27414d.

I initially guessed that maybe the non-userns sandboxing strategy is to blame, but `astuce`'s `/proc/sys/kernel/unprivileged_userns_clone` is `1`, which seems to eliminate that possibility.

**Comment by lapieh** [comment]
I applied this recipe : 
https://lists.debian.org/debian-user/2015/05/msg00177.html

I have no more error....

Thanks for the indication 👍

**Comment by polettix** [comment]
Same here.

It didn't work out of the box, I had to *restart* `sandstorm` after setting `/proc/sys/kernel/unprivileged_userns_clone` to `1`, so this might be what happened to `astuce`.

This is what I did:

    # run commands as root to activate things now
    echo 1 > /proc/sys/kernel/unprivileged_userns_clone
    systemctl restart sandstorm
    # make sure this persists
    echo 'kernel.unprivileged_userns_clone = 1' >> /etc/sysctl.d/10-unpriv-lxc

Thanks all, @lapieh :1st_place_medal:

**Comment by kentonv** [comment]
I guess I broke backup/restore under the privileged (non-userns) sandbox. :( I will fix this for today's release.
