### ISSUE TITLE
/ekam-provider/canonical/sodium/core.c:16:10: fatal error: 'crypto_stream_salsa20.h' file not found

### ISSUE THREAD

**Issue by iramykytyn** [sandstorm-io/sandstorm#2894]
Can not build sandstorm from sources. Failure looks like below. It is looking for crypto_stream_salsa20.h header, but it does not present there. At least it looks like.

link: sandstorm/app-index/app-index.o
  tmp/sandstorm/app-index/indexer.o: In function `sandstorm::appindex::Indexer::writeImage(kj::ArrayPtr<unsigned char const>, kj::StringPtr)':
  /ekam-provider/canonical/sandstorm/app-index/indexer.c++:(.text+0x583d): undefined reference to `crypto_generichash_blake2b'
  tmp/sandstorm/spk.o: In function `sandstorm::SpkTool::doPublish(kj::StringPtr)':
  /ekam-provider/canonical/sandstorm/spk.c++:(.text._ZN9sandstorm7SpkTool9doPublishEN2kj9StringPtrE[_ZN9sandstorm7SpkTool9doPublishEN2kj9StringPtrE]+0x8c0): undefined reference to `crypto_generichash_
    blake2b'
  tmp/sodium/crypto_core/curve25519/ref10/curve25519_ref10.o: In function `crypto_core_curve25519_ref10_fe_isnonzero':
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x642): undefined reference to `crypto_verify_32'
  tmp/sodium/crypto_core/curve25519/ref10/curve25519_ref10.o: In function `crypto_core_curve25519_ref10_ge_frombytes_negate_vartime':
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x2f79): undefined reference to `crypto_verify_32'
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x2fd5): undefined reference to `crypto_verify_32'
  tmp/sodium/crypto_sign/ed25519/ref10/open.o: In function `_crypto_sign_ed25519_verify_detached':
  /ekam-provider/canonical/sodium/crypto_sign/ed25519/ref10/open.c:(.text+0x2a4): undefined reference to `crypto_verify_32'
link: sandstorm/spk-standalone.o
  tmp/sodium/crypto_sign/ed25519/ref10/open.o: In function `_crypto_sign_ed25519_verify_detached':
  /ekam-provider/canonical/sodium/crypto_sign/ed25519/ref10/open.c:(.text+0x2a4): undefined reference to `crypto_verify_32'
  tmp/sodium/crypto_core/curve25519/ref10/curve25519_ref10.o: In function `crypto_core_curve25519_ref10_fe_isnonzero':
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x642): undefined reference to `crypto_verify_32'
  tmp/sodium/crypto_core/curve25519/ref10/curve25519_ref10.o: In function `crypto_core_curve25519_ref10_ge_frombytes_negate_vartime':
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x2f79): undefined reference to `crypto_verify_32'
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x2fd5): undefined reference to `crypto_verify_32'
  tmp/sandstorm/spk.o: In function `sandstorm::SpkTool::doPublish(kj::StringPtr)':
  /ekam-provider/canonical/sandstorm/spk.c++:(.text._ZN9sandstorm7SpkTool9doPublishEN2kj9StringPtrE[_ZN9sandstorm7SpkTool9doPublishEN2kj9StringPtrE]+0x8c0): undefined reference to `crypto_generichash_
    blake2b'
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
install: sandstorm/sandstorm.ekam-manifest
  sandstorm/run-bundle: not found
link: sandstorm/run-bundle.o
  tmp/kj/async-io-unix.o: In function `kj::Function<void ()>::Impl<kj::CaptureByMove<kj::(anonymous namespace)::SocketAddress::lookupHost(kj::LowLevelAsyncIoProvider&, kj::String, kj::String, unsigned int
    )::$_5, kj::(anonymous namespace)::SocketAddress::LookupParams> >::operator()()':
  /ekam-provider/canonical/kj/async-io-unix.c++:(.text+0xcb57): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for 
    linking
  tmp/sodium/crypto_core/curve25519/ref10/curve25519_ref10.o: In function `crypto_core_curve25519_ref10_fe_isnonzero':
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x642): undefined reference to `crypto_verify_32'
  tmp/sodium/crypto_core/curve25519/ref10/curve25519_ref10.o: In function `crypto_core_curve25519_ref10_ge_frombytes_negate_vartime':
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x2f79): undefined reference to `crypto_verify_32'
  /ekam-provider/canonical/sodium/crypto_core/curve25519/ref10/curve25519_ref10.c:(.text+0x2fd5): undefined reference to `crypto_verify_32'
  tmp/sodium/crypto_sign/ed25519/ref10/open.o: In function `_crypto_sign_ed25519_verify_detached':
  /ekam-provider/canonical/sodium/crypto_sign/ed25519/ref10/open.c:(.text+0x2a4): undefined reference to `crypto_verify_32'
  tmp/sandstorm/spk.o: In function `sandstorm::SpkTool::doPublish(kj::StringPtr)':
  /ekam-provider/canonical/sandstorm/spk.c++:(.text._ZN9sandstorm7SpkTool9doPublishEN2kj9StringPtrE[_ZN9sandstorm7SpkTool9doPublishEN2kj9StringPtrE]+0x8c0): undefined reference to `crypto_generichash_
    blake2b'
link: sandstorm/update-tool.o
compile: sodium/core.c
  /ekam-provider/canonical/sodium/core.c:16:10: fatal error: 'crypto_stream_salsa20.h' file not found
  #include "crypto_stream_salsa20.h"
           ^
  1 error generated.

**Comment by dwrensha** [comment]
Fixed by https://github.com/sandstorm-io/sandstorm/commit/22fcd96cb957f424848ec70acc51474f5e7c8a22.
