### ISSUE TITLE
Application Update Request: Wekan version from 0.11 to 0.16

### ISSUE THREAD

**Issue by busecdo** [sandstorm-io/sandstorm#2898]
The default version of Wekan on Sandstorm is currently 0.11.  Any chance it could be updated to 0.16?

**Comment by ocdtrekkie** [comment]
The proper place for application update requests is on the app's issues itself. This is pending @dwrensha checking if the new admin panel needs to be hidden, as it does not apply to Sandstorm, and then publishing the updated package.

**Comment by ocdtrekkie** [comment]
Actually, correction, the Wekan 0.16 version is currently in the experimental market: https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h?experimental=true

So it should be offered in the primary app market once it's been tested.

**Comment by dwrensha** [comment]
As far as I can tell, there no admin panel to hide.

**Comment by ocdtrekkie** [comment]
Interesting! I haven't seen where it is on Wekan standalone (@xet7?) but perhaps Wekan doesn't treat the grain owner as an admin anyways or something.

I upgraded a copy of my Ports in Progress Wekan to 0.16, and I only see one funky issue: When I delete a checklist, the keyboard shortcuts popup appears. Which is weird. But not a dealbreaker.

**Comment by ocdtrekkie** [comment]
I filed it as an issue, and since the Wekan PR is out to update to release 19 and the SPK is in the experimental queue, I think this issue can/should be closed.

**Comment by dwrensha** [comment]
metadata pull request on the wekan repo: https://github.com/wekan/wekan/pull/930
