### ISSUE TITLE
Login LDAP error

### ISSUE THREAD

**Issue by Anastico** [sandstorm-io/sandstorm#2903]
Hello,

I'm testing sandstorm with a local install with xip.io for the dns wildcard and a LDAP authentification...

Was working well before this error when i tryed to share a grain with someone, he get this error when trying to connect on Sandstorm : 

![bug_st1](https://cloud.githubusercontent.com/assets/26741899/24407053/062ae262-13ca-11e7-9e25-997ed471c6a8.png)

Thanks for your help

**Comment by kentonv** [comment]
Did any interesting messages show up in the server log? (You can view it at `/admin/status` or by SSHing to the server an looking at `/opt/sandstorm/var/log/sandstorm.log`.)

**Comment by Anastico** [comment]
kentonv,
Thanks for your reply, I didnt find something very helpful in the log, but maybe I'm missing it so  I uploaded it :
[sandstorm2.pdf](https://github.com/sandstorm-io/sandstorm/files/889250/sandstorm2.pdf)

For one of my member who It wasnt working, its now working and I didn' t changed anything...

**Comment by kentonv** [comment]
Hi @Anastico,

The error is coming from Active Directory. Based on some Googling, it looks like this error message -- while incredibly confusing, like all AD error messages -- basically boils down to "wrong password". See, for example: http://stackoverflow.com/questions/31411665/ldap-error-code-49-80090308-ldaperr-dsid-0c0903a9-comment-acceptsecurityc

I am not an Active Directory expert so I don't think I can offer much more help here, sorry.
