### ISSUE TITLE
Setting sandcats.io subdomain not working

### ISSUE THREAD

**Issue by orboan** [sandstorm-io/sandstorm#2904]
Hello, 
running the sandstorm installation script on a CentOS 7 server, it keeps asking you in a continous loop the sandcats subdomain you want to use:

Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).

Type the word none to skip this step, or help for help.

What *.sandcats.io subdomain would you like? [] gfkfafdawef

We need your email on file so we can help you recover your domain if you lose access. No spam.

Enter your email address: [] sdhkag@gmail.com

Registering your domain.
...

Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).

Type the word none to skip this step, or help for help.

What *.sandcats.io subdomain would you like? [] iiiuuu

We need your email on file so we can help you recover your domain if you lose access. No spam.

Enter your email address: [] huhuh@gmail.com

Registering your domain.

...

Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).

Type the word none to skip this step, or help for help.

What *.sandcats.io subdomain would you like? []

--

Only entering 'none' the loop stops and the script porceeds with the next command.

What is the problem? Is there a solution?

**Comment by kentonv** [comment]
That's very strange, especially since it works fine for most people, and there's really not many variables here.

@paulproteus does this ring any bells?

**Comment by staticwaveuk** [comment]
Also facing the same issue on a new installation on a new centos7 build.

**Comment by kentonv** [comment]
Hi all,

I wonder if this is because centos has stopped trusting Startcom, which, unfortunately, was the issuer of the certificate for the sandcats.io coordinator service. We've switched over to a Let's Encrypt certificate. Can you try the installer again and see if it works now?

**Comment by staticwaveuk** [comment]
Looks like this has fixed it for me. Not sure about others.

**Comment by kentonv** [comment]
Great, seems this is probably fixed, then!

**Comment by ecspresso** [comment]
I also have this problem. Tried on fresh install of Ubuntu 16.04 and 17.04. I run the installer via HTTPS, follow instructions and only 'none' will get me past the loop.

**Comment by kentonv** [comment]
@ecspresso The cert for sandcats.io temporarily expired a few days ago, which would have caused this problem. I've updated it now, so it should work if you try again.

**Comment by ecspresso** [comment]
Sorry for late reply, it did indeed work. Thanks!

**Comment by jpmendo** [comment]
Hello all. I would like to report the same loop-issue. I provide a desired subdomain and my email address. The screen then displays 
* Registering your domain. 
* ...
* Choose your desired Sandcats subdomain

Kentonv, perhaps the certificate expired again?
