### ISSUE TITLE
Instructions for building from source fail on debian jessie

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#2908]
In particular, the suggested command for installing dependencies:

```
sudo apt-get install build-essential libcap-dev xz-utils zip \
    unzip strace curl clang-3.4 discount git python
curl https://install.meteor.com/ | sh
```

does not install a `clang++` executable, which later causes the build to fail, for obvious reasons. Installing "clang" seems to do the trick. This also works on ubuntu trusty and later. Ubuntu precise and debian wheezy as far as I can tell just don't package clang >= 3.4.

One simple solution is to just remove the `-3.4` in that command. Precise is only supported until the end of the month. Wheezy is still supported for a year and change, but I'm not sure whether the kernel is even recent enough to run sandstorm? 3.2.0.

**Comment by kentonv** [comment]
Thanks.
