### ISSUE TITLE
E_NEVER_LISTENED error

### ISSUE THREAD

**Issue by baloe** [sandstorm-io/sandstorm#2909]
I have a virtual server running Ubuntu, and a domain `mydomain.com`.
I installed sandstorm through `curl https://install.sandstorm.io | bash` not using the sandcats service.
Instead, I entered `sandstorm.mydomain.com` and `*.sandstorm.mydomain.com`, fine.
Now I cannot figure out how to make my server show the sandstorm frontend upon browsing `sandstorm.mydomain.com`.
I cannot find any file such as `index.php` which I would otherwise setup the subdomain to point to.

This ought to be a common concern for less experienced users so it would be really helpful to include an explanatory section in the documentation.

Thanks, Bastian

**Comment by Michael-S** [comment]
What are you seeing when you browse to sandstorm.mydomain.com?  Nothing?  A default web page unrelated to Sandstorm?

How is your DNS set up?  Do you have just mydomain.com pointing to the IP address of your virtual server?  I think you might need *.sandstorm.mydomain.com or sandstorm.mydomain.com or both pointing to the address of your virtual server.

I'm not skilled with DNS, so it's possible I'm wrong.   But for my own private mail server (not related to Sandstorm) I had headaches that way.

**Comment by baloe** [comment]
so I realized I made a few mistakes, for once I did not include a port number and did not specify a port number when browsing either. As a result, I was shown a default web page I get for any arbitrary subdomain.

**Update 1** I did a fresh reinstall, not using any subdomain, but the default port 6080. When entering mydomain.com:6080 the browser keeps looking for a website eternally. 

**Update 2** I did a fresh reinstall, selecting the **sandcats subdomain service** this time which actually reveals the error:
```
root@vmd16704:/opt/sandstorm# curl https://install.sandstorm.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 78791  100 78791    0     0  76654      0  0:00:01  0:00:01 --:--:-- 76719
Sandstorm makes it easy to run web apps on your own server. You can have:

1. A typical install, to use Sandstorm (press enter to accept this default)
2. A development server, for working on Sandstorm itself or localhost-based app development

How are you going to use this Sandstorm install? [1] 
We're going to:

* Install Sandstorm in /opt/sandstorm
* Automatically keep Sandstorm up-to-date
* Configure auto-renewing HTTPS if you use a subdomain of sandcats.io
* Create a service user (sandstorm) that owns Sandstorm's files
* Configure Sandstorm to start on system boot (with systemd)
* Listen for inbound email on port 30025.

Rest assured that Sandstorm itself won't run as root.
OK to continue? [yes] 
As a Sandstorm user, you are invited to use a free Internet hostname as a subdomain of sandcats.io,
a service operated by the Sandstorm development team.
...
Sandcats.io protects your privacy and is subject to terms of use. By using it,
you agree to the terms of service & privacy policy available here:
https://sandcats.io/terms https://sandcats.io/privacy

Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).
Type the word none to skip this step, or help for help.
What *.sandcats.io subdomain would you like? [] test123
We need your email on file so we can help you recover your domain if you lose access. No spam.
Enter your email address: [] bastianloehrer@gmail.com
Registering your domain.
Successfully registered!
Congratulations! We have registered your test123.sandcats.io name.
Your credentials to use it are in /opt/sandstorm/var/sandcats; consider making a backup.
Now we're going to auto-configure HTTPS for your server.

* This will take about 30 seconds, and needs no input from you.
* Thanks to GlobalSign for their help making this happen.

Generating certificate request...
Requesting certificate (BE PATIENT)...
Successfully auto-configured HTTPS!

Config written to /opt/sandstorm/sandstorm.conf.
Finding latest build for dev channel...
Downloading: https://dl.sandstorm.io/sandstorm-205.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26.9M  100 26.9M    0     0  5558k      0  0:00:04  0:00:04 --:--:-- 5574k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0    480      0 --:--:-- --:--:-- --:--:--   479
GPG signature is valid.
Created symlink from /etc/systemd/system/multi-user.target.wants/sandstorm.service to /etc/systemd/system/sandstorm.service.
Your server is coming online. Waiting up to 90 seconds.............................................................................................*** INSTALLATION FAILED ***

Your server never started listening.

Hmm, installation failed. Would it be OK to send an anonymous error report to the sandstorm.io team so we know something is wrong?
It would only contain this error code: E_NEVER_LISTENED [yes] 
Sending problem report...
... problem reported successfully. Your installation did not succeed.

You can report bugs at: http://github.com/sandstorm-io/sandstorm```

**Comment by baloe** [comment]
**Okay, I figure this is probably related to firewall settings ... https://github.com/sandstorm-io/sandstorm/issues/2632
Will look into it later**

**Comment by baloe** [comment]
never mind, 6080 among other ports were blocked by my server-side firewall; after permitting communication through 6080 and 6081 sandstorm can be reached

**Comment by TMXHUB** [comment]
Perdi toda a calma e tranquilidade tentando instalar o sandstorm faz três dias na minha máquina, depois contratei um vps pensando que o problema fosse no meu cenário. Profundamente lamentável.

**Comment by ocdtrekkie** [comment]
@TMXHUB Is this related to this issue report?

Translation (via Bing): "I lost all the calm and tranquility trying to install the sandstorm three days ago on my machine, then I contracted a vps thinking that the problem was in my scenario. Deeply regrettable."

**Comment by TMXHUB** [comment]
> @TMXHUB Is this related to this issue report?
> 
> Translation (via Bing): "I lost all the calm and tranquility trying to install the sandstorm three days ago on my machine, then I contracted a vps thinking that the problem was in my scenario. Deeply regrettable."

Yah! **E_NEVER_LISTENED error** 
m use lots of recomendations from this forum. 

Like this:

```
iptables -I INPUT -i lo -j ACCEPT
```

But now I gave up. The promise of easy installation is not true. I will have to hire someone to help me. I've been working with technology for 22 years. I would like to leave the collaboration group of the nonprofit organization that I participate in more cool and smart. But I am accepting that Sandstorm-io is not for me. Thank you all.
