### ISSUE TITLE
sandcats.io DNS IP not updated: Couldn't send update sandcats hostname { [Error: certificate revoked] code: 'CERT_REVOKED' }

### ISSUE THREAD

**Issue by ggramlich** [sandstorm-io/sandstorm#2912]
I currently cannot connect to my sandstorm installation through my sandcats.io address.

Looking into the /opt/sandstorm/var/log/sandstorm.log I see numerous lines of
`Couldn't send update sandcats hostname { [Error: certificate revoked] code: 'CERT_REVOKED' }`

The last line before the first occurrence of the error is

`Since Tue Apr 11 2017 00:17:08 GMT+0000 (UTC) is more than three days away from Mon Apr 17 2017 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.`

I also tried a sandstorm restart, which did not help.

**Comment by kentonv** [comment]
Hi @ggramlich, did your IP address change in the last 48 hours?

**Comment by ggramlich** [comment]
@kentonv Yes, it changes every 24h, because of my DSL provider. I have not had any issues with sandcats.io DNS since I started using it, about 2 months ago, until now.

**Comment by kentonv** [comment]
Hi @ggramlich,

The sandcats.io coordinator service was using a certificate from Startcom, which has recently been de-trusted as a CA. I suspect the "certificate revoked" error is because of this. So, we've now switched to a Let's Encrypt certificate.

Can you check your server again and see if it has now updated?

**Comment by ggramlich** [comment]
I just did a tail on the log before I saw your response :-)

```
Couldn't send update sandcats hostname { [Error: certificate revoked] code: 'CERT_REVOKED' }
Couldn't send update sandcats hostname { [Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
Couldn't send update sandcats hostname { [Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
Successfully updated sandcats IP
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
Since Wed Apr 12 2017 05:26:07 GMT+0000 (UTC) is more than three days away from Mon Apr 17 2017 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
```

It works again now. Thanks a lot.

**Comment by paulproteus** [comment]
@kentonv and @ggramlich ,

Yesterday I worked on switching the service to use a Let's Encrypt certificate, as Kenton said. I just wanted to say thanks to @ggramlich for filing this issue -- I hadn't noticed the issue yet -- and thanks to @kentonv for asking me to help address it.

I'm gratified to see that my work fixed the issue for you @ggramlich !

**Comment by ggramlich** [comment]
@paulproteus You are very welcome. Thanks for your awesome service.
