### ISSUE TITLE
Setup/Login

### ISSUE THREAD

**Issue by Hippititimus** [sandstorm-io/sandstorm#2918]
Hello,

Im pretty new to Sandstorm and Github.  I installed ok on  my Linux server, however in the setup no matter which authentication method i use, whether email or Google account the setup will not use SMTP.  I have tried using my own domain settings,  Sendrid and a Zoho email service.  All respond the same way.

"Error while trying to send test email: {"code":"EAUTH","response":"535 Incorrect authentication data","responseCode":535,"command":"AUTH PLAIN"} [other-email-sending-error]"

In sendgrid i have used basic Auth and API kieys to no avail and with all email addresses i have tried every possible port (all of which are open on my server firewall

I cannot login using any metod as the Google Auth just leaves me on the login page and email login cannot send the login message so i cannot get into the installation.

Any advice  would be appreciated.  

Hippi

**Comment by Hippititimus** [comment]
FYI  I have tried with the 

> Sandstorm server's own email address 
and various other email sending addresses to match the various ways i was setting up.

Hippi

**Comment by kentonv** [comment]
Hi @Hippititimus,

Hmm, the only thing I can think of is: What port are you using? Many hosting providers and ISPs will intercept or block port 25. For Sendgrid, try port 2525 instead -- this is what we use and it works well.

Other than that, I'm not sure what to say. The error sounds like the username or password is wrong.

**Comment by DEVAHMEDDAOUDI** [comment]
Hello @Hippititimus @kentonv ,
So have you solved your problem? I can not connect with a "normal" email address, I can only connect with a Gmail email address. How to do ? I activated SMTP 25 in my server. Help me . Thank you

Ahmed DAOUDI

**Comment by ocdtrekkie** [comment]
I am going to close this one on lack of response as well. I do know Sendgrid works well with Sandstorm, as I currently use it on mine.
