### ISSUE TITLE
CLONE_NEWPID run-bundle.c unimplemented

### ISSUE THREAD

**Issue by MatheusRV** [sandstorm-io/sandstorm#2929]
Runing Windows 10 with Ubuntu Bash 

Note: Sandstorm's storage will only be accessible to the group 'sandstorm'.

Config written to /opt/sandstorm/sandstorm.conf.
Finding latest build for dev channel...
Downloading: https://dl.sandstorm.io/sandstorm-207.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26.7M  100 26.7M    0     0   721k      0  0:00:37  0:00:37 --:--:--  143k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0     40      0  0:00:07  0:00:07 --:--:--    74
GPG signature is valid.
*** Uncaught exception ***
sandstorm/run-bundle.c++:625: unimplemented: unshare(CLONE_NEWPID): Function not implemented
stack: 0x45b0a9 0x45b09a 0x504ba3 0x5056a0

**Comment by kentonv** [comment]
Sorry, we don't support Windows Subsystem for Linux.

WSL only implements a subset of the Linux system call API -- generally, the most common ones. Sandstorm uses a lot of uncommon system calls in order to set up containers and sandboxing. It's highly unlikely that it will work on WSL any time soon, and we won't be putting any effort into making it happen. Sorry.

**Comment by buoyantair** [comment]
@kentonv Hello, this same issue happened to me while trying to run it on a docker container

**Comment by buoyantair** [comment]
@kentonv Here's my output

```
root@6ff752c724d8:/# curl https://install.sandstorm.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 79206  100 79206    0     0  54512      0  0:00:01  0:00:01 --:--:-- 54474
Sandstorm makes it easy to run web apps on your own server. You can have:

1. A typical install, to use Sandstorm (press enter to accept this default)
2. A development server, for working on Sandstorm itself or localhost-based app development

How are you going to use this Sandstorm install? [1] 1
We're going to:

* Install Sandstorm in /opt/sandstorm
* Automatically keep Sandstorm up-to-date
* Configure auto-renewing HTTPS if you use a subdomain of sandcats.io
* Create a service user (sandstorm) that owns Sandstorm's files
* Configure Sandstorm to start on system boot (with sysvinit)
* Listen for inbound email on port 25.

Rest assured that Sandstorm itself won't run as root.
OK to continue? [yes] 
Note: Sandstorm's storage will only be accessible to the group 'sandstorm'.
As a Sandstorm user, you are invited to use a free Internet hostname as a subdomain of sandcats.io,
a service operated by the Sandstorm development team.
...
Sandcats.io protects your privacy and is subject to terms of use. By using it,
you agree to the terms of service & privacy policy available here:
https://sandcats.io/terms https://sandcats.io/privacy

Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).
Type the word none to skip this step, or help for help.
What *.sandcats.io subdomain would you like? [] [REDACTED]
We need your email on file so we can help you recover your domain if you lose access. No spam.
Enter your email address: [] [REDACTED]
Registering your domain.
Successfully registered!
Congratulations! We have registered your maxibunny.sandcats.io name.
Your credentials to use it are in /opt/sandstorm/var/sandcats; consider making a backup.
Now we're going to auto-configure HTTPS for your server.

* This will take about 30 seconds, and needs no input from you.
* Thanks to GlobalSign for their help making this happen.

Generating certificate request...
Requesting certificate (BE PATIENT)...
Successfully auto-configured HTTPS!

Config written to /opt/sandstorm/sandstorm.conf.
Finding latest build for dev channel...
Downloading: https://dl.sandstorm.io/sandstorm-243.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 50.7M  100 50.7M    0     0  2524k      0  0:00:20  0:00:20 --:--:-- 4772k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0    303      0  0:00:01  0:00:01 --:--:--   303
WARNING: gpg not installed; not verifying signatures (but it's HTTPS so you're probably fine)
*** Uncaught exception ***
sandstorm/run-bundle.c++:667: failed: unshare(CLONE_NEWPID): Operation not permitted
stack: 4bd6ac 64de33 64f18d

```

**Comment by buoyantair** [comment]
@zenhack I'd like to run sandstorm locally because it's easy for me to setup certain things quickly. I don't know if I should install it directly via my terminal on my own personal laptop... Docker was a good place for me because I could just run the container every time I open my laptop and I would be able to open sandstorm locally and try new apps etc.  What is your advice for me?

**Comment by zenhack** [comment]
I'd say installing it directly on your laptop is fine; I've got a dev instance set up on mine that way. I don't know that putting it in a container on top of that really buys you anything.
