### ISSUE TITLE
Is it possible to install sandstorm.io without access to SSH/Shell Console?

### ISSUE THREAD

**Issue by gesundelehre** [sandstorm-io/sandstorm#2930]
If not, it would be pretty hard to install on a free Web Host somewhere.
Thanks for the reply

**Comment by ocdtrekkie** [comment]
AFAIK, there's no free host that would give you the requisite permissions to install anything like Sandstorm.

The only reason things like PHP apps work on free hosts is because they preinstall PHP for you... You're not, in reality, installing anything.

**Comment by kentonv** [comment]
Sorry, as Jake says, Sandstorm just isn't going to work on a free host. If it did, that host would lose tons of money, as Sandstorm is much more resource-hungry than a typical PHP app (or static web site).
