### ISSUE TITLE
"Remember me" option for login

### ISSUE THREAD

**Issue by kasbah** [sandstorm-io/sandstorm#2933]
Hey, I am using sandstorm.io to run Piwik so I can stop running Google Analytics. Thanks very much! 

It would be nice to not have to click so many times to login, can we add a "remember me" option to keep session cookies for longer?

**Comment by kentonv** [comment]
Hi @kasbah,

Normally once you log into Sandstorm, you are logged in permanently unless you choose to log out. So, "remember me" is the default.

Are you finding you have to log in again every time you visit Sandstorm? Are you always using the same browser? Do you have any browser extensions installed that might be wiping your data after each session?

**Comment by kasbah** [comment]
Hmm, thanks, looks like I had it set to remove cookies on Firefox close. It's a bit confusing why I continue to be logged into GMail and GitHub across browser restart when those cookies were supposed to be removed but that's no fault of sandstorm.io.
