### ISSUE TITLE
Error $ROOT_URL - Front-end died immediately after starting

### ISSUE THREAD

**Issue by HannanAkbar** [sandstorm-io/sandstorm#2934]
Sandstorm server is not accessible via https://sub.example.com/ returned error 504 - gateway time-out. However Nginx reverse proxy is not showing any visible error except the upstream timed out error in the error.log. HTTPS certificate is also configured correctly.

**sandstorm.conf**

```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=127.0.0.1
BASE_URL=//sub.example.com
WILDCARD_HOST=*.sub.example.com
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=30025
```

**sandstorm.log**

```
Error: $ROOT_URL, if specified, must be an URL
    at Error (native)
    at packages/meteor.js:1218:13
    at packages/meteor.js:1233:4
    at packages/meteor.js:1380:3
    at /programs/server/boot.js:303:34
    at Array.forEach (native)
    at Function._.each._.forEach (/programs/server/node_modules/underscore/underscore.js:79:11)
    at /programs/server/boot.js:128:5
    at /programs/server/boot.js:352:5
    at Function.run (/programs/server/profile.js:510:12)
** Front-end died immediately after starting.
** Sleeping for a bit before trying again...
/programs/server/boot.js:356
}).run();
```

CURL is not giving back any response.
`curl http://127.0.0.1:6080`

**Comment by zenhack** [comment]
Quoting Hannan A. (2017-05-06 00:17:42)

> BASE_URL=//sub.example.com

What happens if you change this to `https://sub.example.com`?

**Comment by HannanAkbar** [comment]
@zenhack 
Yes, I tried that. Same error.

**Comment by HannanAkbar** [comment]
@zenhack Thanks. It worked after changing to `https://` and restarting the sandstorm service.

**Comment by zenhack** [comment]
@HannanAkbar, glad to hear it.

I'm not sure the information is actually omittable; it may control whether sandstorm will redirect http -> https.

We should probably be displaying better error messages for bad config files though.

//cc @kentonv

**Comment by kentonv** [comment]
Sorry, your Sandstorm server must have exactly one origin, for a bunch of reasons ranging from localStorage consistency to OAuth configuration. http and https are different origins, therefore you cannot have Sandstorm serving on both. That said, if you configure BASE_URL to be https, and Sandstorm receives an http request for the same hostname, it will automatically redirect to https (I think).
