### ISSUE TITLE
Failed to install app

### ISSUE THREAD

**Issue by franzperdido** [sandstorm-io/sandstorm#2936]
Failed to install gitlab app on my sanstorm server today.

Got the following error message:
`  remote exception: expected exitCode == 0; child process failed; name = spk; exitCode = 1`

I'm no expert, so can't exclude personal failure. But would be very grateful for advice! 

This is my log:

*** Uncaught exception ***
kj/io.c++:322: overloaded: miniposix::write(fd, pos, size): No space left on device; fd = 3
stack: 0x4cb211 0x4cb361 0x4cb361 0x4cb361 0x4cb361 0x4cb361 0x4c6c4f 0x4de73d 0x4de56d 0x504ba3 0x5056a0
capnp/rpc.c++:142: info: returning failure over rpc; exception = sandstorm/util.c++:995: failed: expected exitCode == 0; child process failed; name = spk; exitCode = 1
stack: 0x5e9a58 0x5e97cb 0x4fb712 0x553140
Failed to install app: Error: remote exception: expected exitCode == 0; child process failed; name = spk; exitCode = 1
    at Error (native)

**Comment by ocdtrekkie** [comment]
Do you have disk space available on that drive?

**Comment by franzperdido** [comment]
It's a VM but it should have more than enough space...

**Comment by zenhack** [comment]
Have you actually checked?  `df -h`. The exception pretty clearly states that's what it thinks is going on, so I'd like to rule out it being right before moving on.

**Comment by franzperdido** [comment]
Ok, I appear to have problems with VirtualBox in general. Closing this issue for now until I can be sure it is not some home-made problem.
Thanks for your efforts!

**Comment by zenhack** [comment]
You're welcome, and best of luck.
