### ISSUE TITLE
Redesign /accounts UI to display only 1 profile

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2943]
Currently if a user has multiple "credentials" (e.g. Google, GitHub, etc) they will have a profile attached to each of those accounts.

Profile switching has caused a lot of confusion for users and so we'll be transitioning from displaying multiple profiles to only 1 single profile.  (Users may still have multiple accounts linked, however, only one profile will be displayed and editable.)

This is what a user will see (today) if they have multiple profiles:

![image](https://cloud.githubusercontent.com/assets/855341/26617329/855bc5ba-4589-11e7-8210-aace12f75bac.png)

Here's a rough draft of what we could possibly do:
![image](https://cloud.githubusercontent.com/assets/855341/26617296/3af941e6-4589-11e7-8b17-891d92d4534a.png)

Hoping for some feedback from @kentonv so I can make some tweaks and post a design update by the end of the week.

**Comment by kentonv** [comment]
Looks good to me, except that instead of "identities" we should call them "linked credentials" or maybe "linked accounts".

**Comment by kentonv** [comment]
(Sorry for now replying sooner, I generally batch Sandstorm stuff to weekends.)

**Comment by ocdtrekkie** [comment]
I am closing this issue because this appears to have been done during the identity refactor, and my Sandstorm server's account settings look like the rough draft in this issue.
