### ISSUE TITLE
Grains not loading on port 80 (local server using xip.io)

### ISSUE THREAD

**Issue by hendrikweisser** [sandstorm-io/sandstorm#2945]
I'm new to Sandstorm. I have installed the server in a VirtualBox VM running Xubuntu 16.04.2. I currently have it set up to be accessible only locally, using a "xip.io" DNS address as described in the documentation (https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-use-sandstorm-with-an-internal-ip-address).

The problem is that grains are not loading *if the port is set to 80*. I've tested under Firefox and Chromium with both Wekan and Etherpad. The corresponding "sandstorm.conf" is:
```
SERVER_USER=sandstorm
PORT=80
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://10.0.2.15.xip.io:80
WILDCARD_HOST=*.10.0.2.15.xip.io:80
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
```

A similar problem has been described in issue #1469, but the difference is that I'm using the "xip.io" service and *can* successfully ping example domains:
```
$ ping -c 3 example.10.0.2.15.xip.io
PING example.10.0.2.15.xip.io (10.0.2.15) 56(84) bytes of data.
64 bytes from 10.0.2.15: icmp_seq=1 ttl=64 time=0.044 ms
64 bytes from 10.0.2.15: icmp_seq=2 ttl=64 time=0.061 ms
64 bytes from 10.0.2.15: icmp_seq=3 ttl=64 time=0.068 ms

--- example.10.0.2.15.xip.io ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2028ms
rtt min/avg/max/mdev = 0.044/0.057/0.068/0.013 ms
```

Interestingly, if I reconfigure Sandstorm to use port 6080 (i.e. replace "80" with "6080" in "sandstorm.conf" and restart the server), things work fine.

(I noticed when I set up the server, although I used port 80 to set BASE_URL and WILDCARD_HOST during installation, initially the PORT value in "sandstorm.conf" was still 6080. I then changed it to 80 after the URL in the setup token wouldn't work. Perhaps the port setting is not updated everywhere correctly, if a value other than 6080 is used?)

**Comment by kentonv** [comment]
Hi,

I think the problem may be that port 80 is the default port for HTTP, and so shouldn't be specified at all. That is, you should remove the `:80` suffix, so you have:

    BASE_URL=http://10.0.2.15.xip.io
    WILDCARD_HOST=*.10.0.2.15.xip.io

Can you try this and let me know if it works?

**Comment by ocdtrekkie** [comment]
I'm going to close this for lack of response.
