### ISSUE TITLE
Add support for "If-*" headers to powerbox

### ISSUE THREAD

**Issue by mbjorkegren** [sandstorm-io/sandstorm#2950]
Just talked with @kentonv about this.
We'd like to use "If-None-Match" to enable requests that return a 304 response code.
It looks like ETag in the response headers might necessary as well, if it's not there already.

**Comment by zenhack** [comment]
Quoting mbjorkegren (2017-06-12 14:39:37)

>    Just talked with @kentonv about this.
>    We'd like to use "If-None-Match" to enable requests that return a 304
>    response code.
>    It looks like ETag in the response headers might necessary as well, if
>    it's not there already.

web-session.capnp seems to suggest that all of the necessary support is
there, just a question of whether the server actually passes that
information on.

**Comment by kentonv** [comment]
Yes, this is already supported in `web-session.capnp`, `proxy.js`, and `sandstorm-http-bridge`, it's only missing for outgoing Powerbox HTTP API requests, due to being missing from (the poorly-named) `external-ui-view.js`.

I'll implement on Saturday.
