### ISSUE TITLE
Error Message unclear, DNS fails to resolve "WILCARD_HOST Misconfigured"

### ISSUE THREAD

**Issue by QantumEntangled** [sandstorm-io/sandstorm#2951]
I'm getting the "WILCARD_HOST Misconfigured" error message but after reading through the documentation fully and trying multiple changes to my configuration it's still not working. My only conclusion is that something is either missing from the docs, log, or I'm completely insane (all are equally likely IMO).

I have my server running on an updated Ubuntu 16.04 VM inside a VMware cluster. It's pulling a private IP in my Dev-LAN with 1:1 NAT to a dedicated Public IP. This is the standard configuration we deploy Dev-Test servers in, that way we have LAN access but also all outbound traffic goes and comes from a Static Public IP, without having to fuss with port-forwarding. Once we're ready to teardown and build a production server it will use Port-Forwarding and be behind out firewall.

I've set my own DNS for this box and I was able to acquire Let'sEncrypt SSL certs, resolve webapps, etc., everything works great. But this box is for some reason having issues.

**/opt/sandstorm/sandstorm.conf**
```
SERVER_USER=sandstorm
PORT=80,6080
HTTPS_PORT=443
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://mydomainname.sandcats.io
WILDCARD_HOST=mydomainname-*.sandcats.io
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
SANDCATS_BASE_DOMAIN=sandcats.io
ALLOW_DEMO_ACCOUNTS=false
```
*I've also tried `WILDCARD_HOST=*.mydomainname.sandcats.io` and `WILDCARD_HOST=*.mydomainname.sandcats.io`

**/etc/hosts**
```
127.0.0.1       localhost
127.0.0.1       sandstorm
127.0.0.1       sandstorm.mydomainname.com
127.0.0.1       mydomainname.sandcats.io

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
*I originally intended to use my actual domain with SandStorm but that is apparently not supported in the installer and I'd like to get it working before I try to get it operational.

**System Log**
```
** Shutting down due to signal
** Restarting
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 485
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/mydomainname.sandcats.io/0.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/mydomainname.sandcats.io/0.response-json.response-json
Certificate we want to use: /var/sandcats/https/mydomainname.sandcats.io/0 valid starting Thu Jun 08 2017 00:15:23 GMT+0000 (UTC) until Sat Jun 17 2017 07:59:59 GMT+0000 (UTC)
We have only the one key that we know about. We'll need to renew soon.
Migrations already applied: 34/34
Since Tue Jun 13 2017 22:27:03 GMT+0000 (UTC) is more than three days away from Sat Jun 17 2017 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
```

I checked my Dev-Console in Chrome and I see that I'm unable to resolve https://mydomainname-selftest-bUnchoFrandOm123414gsdg234t.sandcats.io/ so I dropped that into my terminal and did a dig for it and the sandcats.io NS doesn't respond with an A, CNAME, or ANAME record.

From what I can tell there's an issue with the DNS server not responding with an IP address for my site.

**Comment by QantumEntangled** [comment]
I just checked out of curiosity and `/var/sandcats` doesn't exist. After installing the OS and updating I ran the installer and that was it, not sure if it got removed or what's supposed to be there.

**Comment by zenhack** [comment]
Yeah, if the sandcats dir is missing it's not going to work -- that's where your .sandcats.io certs are stored, and general mutable state for the sandcats logic, which manages e.g. dynamic dns (which is probably why you were seeing this particular problem).

fwiw, I would expect the WILDCARD_HOST value not to work -- should be something like *.foo.sandcats.io -- though it sounds like you weren't actually getting that far.

**Comment by QantumEntangled** [comment]
I'm not fully sure what was wrong with that install, I wasn't able to get it working, but I will say that having the log say "`/var/sandcats/`" is very confusing because it's actually in `/opt/sandstorm/var/sandcats`

So maybe modifying that to read "`SANDSTORM_INSTALL_DIR`" or something would make troubleshooting simpler.

To resolve I blew away my server and created a new one with a new subdomain, and put it directly on public IP space. I think our core router MAY have had a routing loop because I was on the inside in a parralel LAN to the Server (although that _SHOULDN'T_ have mattered). But it's working now :)

**Comment by kentonv** [comment]
FWIW there were two problems here:

1. With Sandcats you need to use `*.mydomainname.sandcats.io`; it does not support `mydomainname-*.sandcats.io`. I know you said you tried both but most of your debugging seems to have been for the latter which definitely won't work.
2. Sandcats DNS always maps to your public IP address, so you need to have the ports forwarded on your NAT. The reason you were able to see your server without that is because you edited `/etc/hosts` to override the main domain `mydomain.sandcats.io`. That would make Sandstorm come up, but as there is no way to configure a wildcard host using `/etc/hosts`, you would then get an error that the wildcard host isn't working.

It looks like you've now set up a public IP and everything works, so I'll close this issue. I wonder if we should change sandcats so that it automatically maps to an internal IP instead if you don't have port forwarding set up... a lot of people apparently didn't expect that it would always map to the public IP.

(BTW, the logs say `/var/sandcats` instead of `/opt/sandstorm/var/sandcats` because inside the Sandstorm container, `/opt/sandstorm` is actually root. That said the logs could perhaps be modified to make things clearer.)
