### ISSUE TITLE
sandstorm on lan network 

### ISSUE THREAD

**Issue by icf20** [sandstorm-io/sandstorm#2953]
i did try to run and setup this over lan
doing this https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-use-sandstorm-with-an-internal-ip-address is not working 

are there any other solutions ?

**Comment by icf20** [comment]
@kentonv `http://10.0.0.2.xip.io:6080/setup/token/zzzzzzzzzz `

returns 

`No se puede acceder a este sitio web`

`No se ha podido encontrar la dirección DNS del servidor de 10.0.0.2.xip.io.
DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by kentonv** [comment]
Unfortunately, xip.io is horribly unreliable, and often returns NXDOMAIN randomly. Sometimes it starts working again after a minute or two. But, you may want to try setting up your own DNS instead.

xip.io is not affiliated with Sandstorm so unfortunately I don't have any ability to fix this. So, I'm closing this issue. Sorry.
