### ISSUE TITLE
Video player and storage

### ISSUE THREAD

**Issue by Reneeeee** [sandstorm-io/sandstorm#2958]
Recently discovered Sandstorm and I love it: Kenton and his team did an excellent job!

That said, I do 'miss' the possibility to upload and being able to play video's through a player (just like Groove Basin for audio, that works very well). VLC player comes to mind.

Of course this could have to do with performance issues or other difficulties that I'm not aware of.

**Comment by zenhack** [comment]
I don't see any reason this couldn't be done -- just no one has written an app that does this yet.

@kentonv, do we have a place to catalogue misc. "I think it would be cool to have an app that does X" queries? This seems like the kind of thing that doesn't really make sense on the sandstorm core bug tracker, but might be nice to have a list somewhere for folks looking for inspiration.

**Comment by Reneeeee** [comment]
You're right about that @zenhack. I didn't mean to mess up the core but didn't know where to put it either.

**Comment by ocdtrekkie** [comment]
@zenhack Well, the old App Committee file allowed anyone to submit app porting requests, but nobody really does anything with it anymore.

http://sandsheep.com/pip is for listing app packages that are in progress (or abandoned partway) but doesn't really intend to be there for general requests. http://sandsheep.com/bb is for placing a bounty on something you want, including app requests, but generally shouldn't be added to unless you either are offering to port something for money or are offering money for someone to port something.

The biggest challenge is that there are plenty of requests, but not many people actively porting apps right now.

**Comment by kentonv** [comment]
Thanks for the idea. As mentioned above, I don't think we should track app requests on the Sandstorm core issue tracker, so I will close this, but feel free to start a thread on the sandstorm-dev mailing list.
