### ISSUE TITLE
Restoring Backed Up Grain - Premature EOF

### ISSUE THREAD

**Issue by ertanalytics** [sandstorm-io/sandstorm#2964]
Moving to a new machine on ubuntu and tried the backup method by copying the /opt/sandstorm directory.  Biggest problem is that I get this error when trying to load grains that were included in the folder backup load.  

![image](https://user-images.githubusercontent.com/7130518/28348612-95c7f50e-6c03-11e7-86b9-af0b9fa241dc.png)

**Comment by zenhack** [comment]
What does the grain log say?

**Comment by zenhack** [comment]
Which app is this? It looks like the error is being raised inside the grain.

Also, I have a *hunch* that this and #2963 may be related to more incorrect permissions/ownership -- might be worth just looking though /opt/sandstorm and seeing if anything looks off.

**Comment by ertanalytics** [comment]
Do you happen to have the correct permission listing?

**Comment by ertanalytics** [comment]
ls -la /opt/sandstorm/ on a working system should do the trick.  All of mine appear to have the same issue, so if they are wrong I would not see it, but here are mine:

/opt/sandstorm/

drwxr-xr-x  5 root root      4096 Jul 19 09:15 .
drwxr-xr-x  3 root root      4096 Jul 18 16:53 ..
lrwxrwxrwx  1 root root        13 Jul 18 16:56 latest -> sandstorm-211
lrwxrwxrwx  1 root root        16 Jul 18 16:56 sandstorm -> latest/sandstorm
drwxr-xr-x 17 root root      4096 Jul 15 18:35 sandstorm-211
-rw-r--r--  1 root root       196 Jul 18 16:56 sandstorm.conf
drwxrwx--T  3 root sandstorm 4096 Jul 19 13:18 tmp
drwxr-xr-x  7 root sandstorm 4096 Jul 18 16:53 var

/opt/sandstorm/var/

drwxr-xr-x  5 root root      4096 Jul 19 09:15 .
drwxr-xr-x  3 root root      4096 Jul 18 16:53 ..
lrwxrwxrwx  1 root root        13 Jul 18 16:56 latest -> sandstorm-211
lrwxrwxrwx  1 root root        16 Jul 18 16:56 sandstorm -> latest/sandstorm
drwxr-xr-x 17 root root      4096 Jul 15 18:35 sandstorm-211
-rw-r--r--  1 root root       196 Jul 18 16:56 sandstorm.conf
drwxrwx--T  3 root sandstorm 4096 Jul 19 13:18 tmp
drwxr-xr-x  7 root sandstorm 4096 Jul 18 16:53 var

 /opt/sandstorm/var/sandstorm

drwxrwx--- 8 root      sandstorm 4096 Jul 19 09:15 .
drwxr-xr-x 7 root      sandstorm 4096 Jul 18 16:53 ..
drwxrwx--- 8 root      sandstorm 4096 Jul 18 21:43 apps
drwxr-x--- 2 sandstorm sandstorm 4096 Jul 19 14:47 backups
drwxrwx--- 2 root      sandstorm 4096 Jul 18 16:53 downloads
drwxrwx--- 3 sandstorm sandstorm 4096 Jul 19 14:53 grains
drwxrwx--- 2 root      sandstorm 4096 Jul 19 09:15 socket
drwxrwx--T 2 root      sandstorm 4096 Jul 19 14:53 tmp

Please let me know if you need other directories.

**Comment by ertanalytics** [comment]
The permissions change worked.  I created a fresh install on another machine and walked through all the files and folders.  Thanks for taking the time!

**Comment by zenhack** [comment]
You're welcome! Glad you got it sorted out.
