### ISSUE TITLE
Oasis/Edge/GitHub login - Authentication not persisting

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#2967]
Weird behavior, can't figure it out, Edge doesn't have that many settings to begin with. I have "send Do Not Track requests" on, but turning them off didn't help either.

1. Lately, every time I go to Oasis, I have to log in again with GitHub.
2. I just tried to install an app via the App Market, and instead of directing me back to my own Oasis account, it opened up a demo on Oasis instead.

Issue doesn't occur for me in Firefox, even with Do Not Track enabled, and Privacy Badger running.

**Comment by kentonv** [comment]
This sounds related to localStorage. We store your login token in localStorage rather than in a cookie. It sounds like possibly your browser is not retaining localStorage across sessions. I don't know why that could be, though. Maybe some sort of privacy setting?

**Comment by ocdtrekkie** [comment]
There's nothing mentioning localStorage in settings. Edge doesn't actually have that many settings to begin with. I got annoyed and started using Firefox again here. So I am not sure if others will have this issue or not.

**Comment by Michael-S** [comment]
According to the answer by Vlad Bezden on https://stackoverflow.com/questions/32374875/localstorage-not-working-in-edge  "Could you also check if you have 'Enable DOM Storage' selected? You can find it under: Internet Options -> Advanced tab -> Security group box" 

If you feel like trying again, maybe that is related to the problem?  I don't have Edge available, so I can't check it myself.

**Comment by ocdtrekkie** [comment]
Enable DOM Storage is indeed checked.

**Comment by ocdtrekkie** [comment]
I am going to close this because A. I do not still use Edge as my primary browser, and B. Edge is being replaced (today!) by a fork of Chromium.
