### ISSUE TITLE
Unable to set clean URL for Grain "No such grain for public ID: www [404]"

### ISSUE THREAD

**Issue by ShauneDonohue** [sandstorm-io/sandstorm#2971]
If this is duplicate I apologize I was unable to locate an issue that solved my problem.

I setup a grain (Hugo) that publishes static web site and was able to create a site without much trouble. When I try and setup a cleaner URL like www.example.com It does not work. I updated the DNS records with the appropriate CNAME and TXT records but when I go to the new URL all I get is "No such grain for public ID: www [404]".
If it matters I do not have SandStorm running on the root site but as a sub-domain of sandstorm.example.com, in case it is not obvious example.com is not my domain :)

Any thoughts on what might be wrong?

**DNS**
A Record | * | xxx.xxx.xxx.xxx
A Record | @ | xxx.xxx.xxx.xxx
CNAME Record | www | 9apnxh1f948uxmmtinuu.sandstorm.example.com.
TXT Record | sandstorm-www.www | 9apnxh1f948uxmmtinuu

**sandstorm.conf**
BASE_URL=https://sandstorm.example.com
WILDCARD_HOST=*.example.com

**dig TXT sandstorm-www.www.example.com**
; <<>> DiG 9.9.5-3ubuntu0.15-Ubuntu <<>> TXT sandstorm-www.www.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20261
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;sandstorm-www.www.example.com. IN TXT

;; ANSWER SECTION:
sandstorm-www.www.example.com. 1799 IN TXT "9apnxh1f948uxmmtinuu"

;; Query time: 18 msec
;; SERVER: xxx.xx.xxx.xxx#53(xxx.xxx.xxx.xx)
;; WHEN: Mon Aug 14 13:08:56 UTC 2017
;; MSG SIZE rcvd: 90

**Comment by dagelf** [comment]
Where did you get the public ID from?

**Comment by ShauneDonohue** [comment]
it was displayed on the Grains landing page.   Generated from the Hugo Grain

**Comment by ocdtrekkie** [comment]
Does 9apnxh1f948uxmmtinuu.sandstorm.example.com display correctly when you navigate to it directly?

**Comment by ShauneDonohue** [comment]
@ocdtrekkie you must have read my mind!!!  I just noticed that the public URL is different then what the HUGO landing page is displaying for **Editing Your Site**  I am waiting for my DNS change to replicate to see if that solved it.

Page looks like this for future reference 

Your public site is available at **_https://9apnxh1f948uxmmtinuu.example.com_**.

To set up your domain to point at your public site, add the following DNS records to your domain. Replace blog.example.com with your site's hostname.

Name | Type | Value
-- | -- | --
blog.example.com | CNAME | **_9apnxh1f948uxmmtinuu.sandstorm.example.com_**
sandstorm-www.blog.example.com | TXT | 9apnxh1f948uxmmtinuu

**Comment by ocdtrekkie** [comment]
Since your WILDCARD_HOST is *.example.com, that is probably why Sandstorm is putting it at 9apnxh1f948uxmmtinuu.example.com instead of 9apnxh1f948uxmmtinuu.sandstorm.example.com

**Comment by ShauneDonohue** [comment]
All Sandstorm Grains stopped responding when I set  WILDCARD_HOST is *.sandstorm.example.com

**Comment by ocdtrekkie** [comment]
I would think if the CNAME is set to whichever version of 9apnxh1f948uxmmtinuu.example.com or 9apnxh1f948uxmmtinuu.sandstorm.example.com actually shows the website, your DNS for www should work. In theory.

But I also don't know why you wouldn't be able to set your WILDCAST_HOST to *.sandstorm.example.com, because you should be able to do that.

**Comment by ocdtrekkie** [comment]
(Consider that `alpha-*.sandstorm.io` is the WILDCARD_HOST for Sandstorm Alpha, while `*.oasis.sandstorm.io` is the WILDCARD_HOST for Sandstorm Oasis.)

**Comment by ShauneDonohue** [comment]
It would appear that the DNS change did replicate but it is still not displaying correctly.
On the Sandstorm server when I run host www.example.com it returns what I would expect 9apnxh1f948uxmmtinuu.example.com but I am still getting a No such grain for public ID: www [404].  I can confirm that https://9apnxh1f948uxmmtinuu.example.com does render.

When I originally set up my server I was using sandcats.io for DNS resolution but recently purchased my own domain and switched over to that.

**Comment by ocdtrekkie** [comment]
My thought is that it might be necessary to get things working with WILDCARD_HOST being *.sandstorm.example.com. It might be thinking 'www' is supposed to be a Sandstorm grain ID like '9apnxh1f948uxmmtinuu' and not even checking for the TXT record. Though again, really spitballing ideas here, troubleshooting server config isn't really something I am good at.

**Comment by ShauneDonohue** [comment]
I tried again to set the WILDCARD to include sandstorm but soon as I do that once again none of the grams render, just get the spinning wait image. 
I know you said your not a server config guy but this is my config if it helps
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://sandstorm.example.com
WILDCARD_HOST=*.sandstorm.example.com
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25

**Comment by ocdtrekkie** [comment]
There's some notes here which are meant to be added to the docs: https://github.com/sandstorm-io/sandstorm/issues/2970

Since I see you are using 6080, does it help to add that where applicable?

**Comment by ShauneDonohue** [comment]
OK so you are on to something.   If I change my WILDCARD_HOST=*.sandstorm.example.com:6080 the web site does some up but non of my grains will come up.
I did not add 6080 to the BASE_URL because the link you sent me said it should be what the user would type in not the internal.

**Comment by ocdtrekkie** [comment]
Do you have some sort of proxy config to get people to the 6080 without them typing it?

**Comment by ShauneDonohue** [comment]
I setup nginx according to https://docs.sandstorm.io/en/latest/administering/reverse-proxy/ for SSL access

**Comment by ocdtrekkie** [comment]
I have almost no idea how that would add to this problem, but I'm guessing it is a part of it. When you changed your WILDCARD_HOST, did you change your Nginx config appropriately? It looks like it has stuff that would be relevant in it.

**Comment by ocdtrekkie** [comment]
The Nginx config would be why you don't have :6080 in your Sandstorm config, since Nginx is essentially making it port 443.

**Comment by ShauneDonohue** [comment]
I did update the nginx config.  I can send that over if you think it would help.  In the Admin panel I am seeing WARNING: This server seems to have its WILDCARD_HOST misconfigured. and in the browser console I get the following error


d6f9da7d58853a6307e70a509fff184f5d8cf84c.js?meteor_js_resource=true:131 GET https://selftest-02116573a9801a994e06.sandstorm.example.com/ net::ERR_INSECURE_RESPONSE

WILDCARD_HOST self-test failed. Details: Error: network
    at XMLHttpRequest.y.onreadystatechange (d6f9da7d58853a6307e70a509fff184f5d8cf84c.js?meteor_js_resource=true:131)

**Comment by ocdtrekkie** [comment]
I am definitely not equipped to troubleshoot Nginx configs. But my guess is that this is correct for the Sandstorm config:

BASE_URL=https://sandstorm.example.com
WILDCARD_HOST=*.sandstorm.example.com

And that everything else that is a problem lives in Nginx land.

**Comment by ShauneDonohue** [comment]
Not that I have solved this but to possibly help someone else I tracked down the issue to do with the wildcard CERT I am using.  COMODO does not appear to support sub-subdomains and adding in a Subject Alternative Names of *.sandstorm.example.com does not work so I was getting a net::ERR_INSECURE_RESPONSE error because the cert could not be validated for selftest-02116573a9801a994e06.sandstorm.example.com.

I set my server to not use sandstorm so BASE_URL=https://example.com and WILDCARD_HOST=*.example.com.  Unfortunately this still does not solve my immediate  problem of using WWW.example.com because I think it is conflicting with Sandstorm on the domain root.  I still get  No such grain for public ID: www [404]

For the time being I am going to setup a URL redirect but would love to figure out how to get around this if someone has any ideas.

**Comment by ocdtrekkie** [comment]
If nobody more informed than me shows up sooner, Kenton's usually checking in on these things on weekends.

I am guessing there's gotta be some way to tell Nginx to exclude the www from being treated like a Sandstorm grain ID. I almost wonder if the Sandstorm Alpha style format of sandstorm-*.example.com as a wildcard host could work for you since you can't do sub-subdomains.

**Comment by ShauneDonohue** [comment]
@ocdtrekkie you are a genius.   I switched to using  WILDCARD_HOST=sandstorm-*.example.com and that did it.  Web site and grains are now responding correctly.
Thank you so much for all your help!!

**Comment by ocdtrekkie** [comment]
Hey, I'm good for something!
