### ISSUE TITLE
Porting apps automatic

### ISSUE THREAD

**Issue by MatheusRV** [sandstorm-io/sandstorm#2973]
Is possible create a script to automatic integrate apps to sandstorm? How hard is do that?

My university is considering use sandstorm, but we need to integrate 3 apps, and I try to port a simple app and failed..

**Comment by zenhack** [comment]
It's never going to be technically feasible to do this 100% automatically for arbitrary apps. That said, there's always room for improving the tooling; it would be helpful to know where you got stuck. Folks on the mailing list and IRC channel are also generally pretty willing to help troubleshoot.

**Comment by kentonv** [comment]
As @zenhack says, it's not likely feasible to write an automated script.

If you need help porting a specific app, don't hesitate to e-mail the sandstorm-dev list.

(I'm going to close this issue since this isn't directly actionable for Sandstorm.)
