### ISSUE TITLE
First connexion token not working...

### ISSUE THREAD

**Issue by Willy5** [sandstorm-io/sandstorm#2979]
I have a problem in the configuration, when i launch "sudo sandstorm admin-token" the link return a 404... When i clik on "sign in" to the right, the message is "generate a token"... i can't pass this step for start the configuration. Can you help me ? 

![sans titre 4](https://user-images.githubusercontent.com/5772618/30235810-c8e0ed8c-950d-11e7-8463-a6ee53aca62a.png)

![sans titre 8](https://user-images.githubusercontent.com/5772618/30235811-c8e6916a-950d-11e7-848a-44cdd2587d9c.png)

![sans titre 10](https://user-images.githubusercontent.com/5772618/30235812-c8f60a3c-950d-11e7-9c8e-130dcd8ab3f9.png)

**Comment by zenhack** [comment]
Per https://docs.sandstorm.io/en/latest/administering/config-file/#base_url, your BASE_URL can't have a path -- it has to be at the root of the domain.

**Comment by Willy5** [comment]
Big thanks ! It's ok ! :)

**Comment by zenhack** [comment]
You're welcome!
