### ISSUE TITLE
Error: remote exception: Peer disconnected

### ISSUE THREAD

**Issue by hoangsoft90** [sandstorm-io/sandstorm#2982]
``
Error: remote exception: Peer disconnected.
    at Error (native)
C++ location:(remote):??
type: disconnected
``
i test with setupvm lemp , but after vagrant-spk dev, it show up above error, when access grain on browser.

**Comment by zenhack** [comment]
What shows up in the grain's debug log (monitor icon at the top of the page)?

**Comment by ocdtrekkie** [comment]
Closing for lack of response/information.
