### ISSUE TITLE
out of memory!

### ISSUE THREAD

**Issue by hoangsoft90** [sandstorm-io/sandstorm#2983]
Error when i ran:
``
vagrant-spk enter-grain
$ curl http://127.0.0.1:8000/
``

**Comment by MatheusRV** [comment]
Could you be more specific, we need more information

**Comment by ocdtrekkie** [comment]
I am going to close this, largely for lack of information. However, note that vagrant-spk 1.0 has just been released with an updated version of enter-grain, which should work a lot better than the old version.
