### ISSUE TITLE
Setting up the IP address

### ISSUE THREAD

**Issue by TNick** [sandstorm-io/sandstorm#2988]
I have a subnet of 16 IPs routed through my static IP (let us call it `10.255.0.10`).
One of those IPs (let us call it `10.0.0.87`) is routed by the router's firewall to a container image that runs a nginx reverse proxy.

I have successfully installed sandstorm in another container.
The problem is that the IP that gets assigned to the free sandcats subdomain is the static IP of the router (`10.255.0.10`) as tools like [viewdns.info](http://viewdns.info) show. As far as I can tell there is no way to tell sandcats.io server that my IP is different.

I tried changing [this line](https://github.com/sandstorm-io/sandstorm/blob/master/shell/server/sandcats.js#L111) to something like
```
options.localAddress = process.env.REQ_IP;
```
and setting the IP in the environment, as the server needs to bind to `0.0.0.0` but that did not work.

How can I tell the sandcats.io server that my IP address is `10.0.0.87` until LetsEncrypt solves this in Jan 2008? Please provide some hints about what part of the code should be modified.

PS [I know](https://juanjoalvarez.net/en/detail/2017/jan/12/how-set-sandstorm-behind-reverse-proxy-keeping-you/) that I have to transfer the credentials to the reverse proxy.

**Comment by kentonv** [comment]
Hi Nicu,

The Sandcats.io central server is designed to detect your server's IP address based on the source address of the pings sent from your server. Somehow, you need to get those pings to appear as though they are coming from the address that you want to use. Note that this includes both UDP and TCP traffic.

One way you could accomplish this is to set up iptables and NAT such that packets destined for sandcats.io are NAT'd behind the address you want. This is theoretically straightforward but in practice will be complicated to implement unless you are an iptables expert.

Another solution might be to *block* UDP traffic from your Sandstorm server to sandcats.io. Your server sends a UDP ping to sandcats.io every minute, which sandcats.io compares against what is stored in the database. If it dosen't match, then sandcats.io sends back a reply saying so. Your Sandstorm server, upon receiving the reply, does a TCP/HTTPS request to actually update the IP address stored server-side. If you block UDP, then the system will never detect that the IP is different, and will never attempt an update -- but other Sandcats requests to fetch new certificates will still work as expected.

So, once you've blocked UDP, then all you need to do is manually perform the update request to sandcats.io such that it comes from the correct IP one time. It will stay mapped to that IP as long as sandcats.io never receives any requests coming from a different IP.

You can perform the update request manually using curl. In fact, the install script does this, so you can refer to the install script: https://github.com/sandstorm-io/sandstorm/blob/master/install.sh#L1772-L1792

It looks like you want something like (disclaimer: not tested):

    curl -X POST --data-urlencode "rawHostname=your-sandcats-hostname" -H "X-Sand: cats" \
      -H "Accept: text/plain" --cert id_rsa.private_combined http://sandcats.io/update

Note that the request is authenticated via the client cert `id_rsa.private_combined` which you'll have to obtain from the Sandstorm server at `/opt/sandstorm/var/sandcats/id_rsa.private_combined`.

**Comment by TNick** [comment]
Big thanks!

I was in the process of looking into that. The nasty part is that it expects a parameter called `pubkey` that is [40 characters](https://github.com/sandstorm-io/sandcats/blob/6e686d51aec7fda99e43f971f942ba2c397bdf11/sandcats/lib/validation.js#L486) in length and `ssh-keygen -lf` is longer than that.

**Comment by kentonv** [comment]
I believe the `pubkey` parameter is generated by nginx on our end, based on the client certificate. You don't have to generate it yourself.

**Comment by TNick** [comment]
Oh. But the error that I'm getting is `Your client is misconfigured. You need to provide a client certificate.` which, according to the [source code](https://github.com/sandstorm-io/sandcats/blob/6e686d51aec7fda99e43f971f942ba2c397bdf11/sandcats/server/register.js#L47), indicates that `pubkey ` is missing.

**Comment by TNick** [comment]
My bad. Forgot to change from http to https. The cert was not used.
I assume that `x-real-ip` is also overwritten by nginx?

**Comment by kentonv** [comment]
Whoops, my fault for writing the wrong URL. Edited my comment to avoid confusing anyone else in the future.

Yes, `x-real-ip` comes from nginx.

**Comment by TNick** [comment]
So I transferred the certificate to the reverse proxy.
```bash
curl ipinfo.io/ip
```
returns `10.0.0.87` which is correct.

Running 
```bash
curl -X POST \
  --data-urlencode "email=XXX@gmail.com" \
  --data-urlencode "rawHostname=XXX" \
  -H "X-Sand: cats"  \
  --cert ./sandstorm_id_rsa.private_combined  \
  https://sandcats.io/update
```
returns `{"text":"Update successful."}`.

Which is nice but 
```bash
dig XXX.sandcats.io
```
still returns the wrong ip.
