### ISSUE TITLE
Porting PHP Apps: set $_SERVER['HTTPS'] dpending on HTTP_X_FORWARDED_PROTO

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#299]
I have a really odd thing. I tested my port of Paperwork (https://github.com/JamborJan/paperwork) on different sandstorm servers which I have set up and with different accounts and for me the app is always and in every constellation working. I can create new grains, edit and delete existing grains.

But others cannot. I have one friend testing it on the same server where I also am able to use the app as expected. He can install the app from SPK but is not able to create a grain. The result is a white screen and the Sandstorm Shell shows this log:

```
...** SANDSTORM SUPERVISOR: Starting up grain.
/ekam-provider/canonical/sandstorm/supervisor.c++:1121: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 13
[22-Mar-2015 17:31:30] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[22-Mar-2015 17:31:30] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
```
Same result with @ocdtrekkie and his test on a completely different server.

I have by the way the same log and it is working. I tried many things so far, another computer, another browser. Cach and other things cleaned. I'm not able to reproduce this issue.

Has anyone any ideas? Can one of the sandstorm developers download my SPK and test it? https://jambor.pro/paperwork.spk

Thanks

**Comment by jparyani** [comment]
I'm running into problems with mixed http/https content that the app is trying to serve. Also, when I install the app on my local box, and connect over http://local.sandstorm.io, I get the following errors in the browser's javascript console. Note that it's trying to load https assets over an http connection:

```
Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/css/freqselector.min.css Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/css/typeahead.min.css Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/css/mathquill.css Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/css/bootstrap-editable.css Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/js/jquery.min.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/js/libraries.min.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/js/angular.min.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/js/paperwork.min.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/js/paperwork-native.min.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/js/bootstrap.min.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/js/tagsinput.min.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/ckeditor/ckeditor.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js Failed to load resource: net::ERR_CONNECTION_CLOSED
https://d5tpirylmzkcbv0bpjqi.local.sandstorm.io:30000/js/bootstrap-editable.min.js Failed to load resource: net::ERR_CONNECTION_CLOSED
4cfed50f7754024287c53604e5039cdf2be2cd2c.js:149
```
Then when trying it over an https connection on https://alpha.sandstorm.io, I get the following error, again in the javascript console:

>Mixed Content: The page at 'https://alpha.sandstorm.io/grain/cffdehJgHyexDHbGyHiWgq' was loaded over HTTPS, but requested an insecure resource 'http://alpha-8kbl7mdsd02oap2g04uc.sandstorm.io/login'. This request has been blocked; the content must be served over HTTPS.

Did you edit the links to assets to be forced to https? If not, it seems to be a bug upstream in paperwork. Separately, it appears to be defaulting to http for some endpoints, specifically `/login`. We pass the header `x-forwarded-proto` that most frameworks know to use when building urls, but you may have to manually edit paperwork to respect it.

**Comment by JamborJan** [comment]
Thanks @jparyani I have in deed forced https. I didn't know about ```HTTP_X_FORWARDED_PROTO```. Either I din't read about it in the docs so far or I simply missed an update there. Sorry for that.

I will now try to check for that header and select the protocol. For all others reading this, here is how to get the value in php.

```
$sandstorm_forwarded = array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) ? $_SERVER[ 'HTTP_X_FORWARDED_PROTO'] : 'HTTP_X_FORWARDED_PROTO not set';
```

What I don't understand is that I don't get this issue. Not on one of my 2 PC's, not on my mobile devices, different browsers, different users. I don't understand that point.

**Comment by JamborJan** [comment]
@jparyani do you know why the HTTPS header is not set for the request forwarded to the app? It seems that Paperwork only uses this and it would work, when this is set to some value but not off or like now not set at all.

I'm not that experienced here so there might be a really good reason to not have this set.

**Comment by jparyani** [comment]
Sorry, but I'm not sure what header you're talking about. What's the header's name?

As an aside, according to https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields, `X-Forwarded-Proto` is the defacto standard for specifying the protocol. Unfortunately there's no real standard for this, so it wouldn't shock me if paperwork used some other header.

**Comment by JamborJan** [comment]
I'm trying to find out what exactly they are using but so far they always debugged and asked me for that HTTPS header (see https://github.com/twostairs/paperwork/issues/281). My current test looked like:

```
        echo array_key_exists('HTTPS', $_SERVER) ? $_SERVER[ 'HTTPS'] : 'HTTPS not set'."<br>";
        echo $_SERVER['SERVER_PORT']."<br>";
        echo array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) ? $_SERVER[ 'HTTP_X_FORWARDED_PROTO'] : 'HTTP_X_FORWARDED_PROTO not set';
        die();
```

and brought me:

```
HTTPS not set
33411
https
```
Which basically always provided the right results. I tried to check their code as much as I can but I'm not sure if I found the right place and all affected parts.

I have build a new SPK can you please try it once more? http://jambor.pro/paperwork.spk. As mentioned before for me everything looks fine no matter how I test. You should remove a previous version as I have not increased the version number (sorry).

**Comment by jparyani** [comment]
Ah ok, it seems to be a PHP server variable (see http://php.net/manual/en/reserved.variables.server.php). I'm not sure where it's set, but if it's user overridable, then you may want to do something like:
```php
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == "https")
  $_SERVER['HTTPS'] = "on";
```
I'm not sure that's possible though. If it's not, you'll probably want to do something similar to https://github.com/twostairs/paperwork/commit/dabdc0ab7a7f7db29ac4143f65776720355a6477, except change all the script/style tags to have relative paths. You can either change HTML::style/HTML::script to do so (I have no clue how to do this, but I'm guessing it's possible), or you can manually change them all like so:
```php
[[ HTML::style('css/themes/paperwork-v1.min.css') ]]
->
<link media="all" type="text/css" rel="stylesheet" href="/css/themes/paperwork-v1.min.css">
```
and similarly for script:
```php
[[ HTML::script('ckeditor/ckeditor.js') ]]
->
<script type="text/javascript" href="/ckeditor/ckeditor.js"></script>
```

**Comment by JamborJan** [comment]
I will try that too. Have you been able to test my spk? If it works I'm more or less sure that I found the main reason and don't have to look for other reasons.

**Comment by dwrensha** [comment]
This rings a bell. I set `$_SERVER['HTTPS']` in the WordPress port:
https://github.com/dwrensha/wordpress-sandstorm/blob/2fbe2f9bcdd3782ea577ba1ab69a48944b6b87be/wp-config.php#L26

**Comment by jparyani** [comment]
Your latest spk has the same problem as before for me. Resources are trying to be loaded over https, but can't because my server is at http://local.sandstorm.io

![screen shot 2015-03-23 at 2 22 44 pm](https://cloud.githubusercontent.com/assets/1595880/6790875/246b203a-d168-11e4-98b5-20e1721914a8.png)

**Comment by paulproteus** [comment]
As a meta-remark: I find this thread super-interesting; on one hand, we could document this stuff in a future PHP porting guide for Sandstorm. For another, we can integrate a fix for this so that `$_SERVER['https']` is accurate within PHP for apps within Sandstorm, as part of the `vagrant-spk` work.

@JamborJan , let me know if you try the code workaround that David Renshaw linked to, and if that works for you.

**Comment by JamborJan** [comment]
Sure @paulproteus, will let you know tomorrow.

**Comment by JamborJan** [comment]
@jparyani but that seems to be better than the white screen before. Would be interesting if it now works on a https connection.

Will hopefully fix the pending point tomorrow.

**Comment by JamborJan** [comment]
I have been able to solve the issue for my fork, the paperwork guys need to take a look at this for sure (see https://github.com/twostairs/paperwork/issues/281).

@paulproteus what I have done for the port so far in a quick summary:

HTTP / HTTPS: get the right protocoll and depending on that force Paperwork to use the right one:
https://github.com/JamborJan/paperwork/blob/master/frontend/app/routes.php

Login: detect if we are in sandstorm mode or not, if yes get the user from sandstorm. Is this a new grain: add user, is this an existing grain: login with this user.
https://github.com/JamborJan/paperwork/blob/master/frontend/app/controllers/UserController.php

Layouts: removed some stuff like logout buttons and others which are not required when in sandstorm mode
https://github.com/JamborJan/paperwork/tree/master/frontend/app/views/layouts

Config: set the right base path depending on grain URL (hope this works, not sure):
https://github.com/JamborJan/paperwork/blob/master/frontend/app/config/paperwork.php

I can write a manual for that with some more details and examples. This issue can be closed for now.
