### ISSUE TITLE
viewed in chrome, notifications icon displays "N"

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#2991]
After applying https://github.com/sandstorm-io/sandstorm/commit/692299f052cd9307604e3faaafe244a55ff49687, I see an "N" in my notifications icon:

<img width="193" alt="notifications" src="https://user-images.githubusercontent.com/495768/31855169-2c724e82-b673-11e7-9598-4fdebf7f2c5e.png">

**Comment by kentonv** [comment]
Does ctrl+F5 fix it? I noticed several things broken that fixed themselves after a full refresh, but I don't quite understand why they happened...
