### ISSUE TITLE
Front end died immediately after starting (216)

### ISSUE THREAD

**Issue by m-burg** [sandstorm-io/sandstorm#2993]
My sandstorm instance updated itself to 216 a few hours ago and since then I have not been able to reach it.

Sandstorm version 216
System: Ubuntu Server 14.04.5 64 bit

These are the last 50 lines of `/opt/sandstorm/var/log/sandstorm.log`
```
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1501575174181.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1501575174181.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1502182837084 because 1503043199000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1502182837084.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1502182837084.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1502789359948 because 1503647999000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1502789359948.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1502789359948.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1503391497177 because 1504252799000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1503391497177.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1503391497177.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1503998035797 because 1504857599000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1503998035797.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1503998035797.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1504602733976 because 1505462399000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1504602733976.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1504602733976.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1505210243995 because 1506067199000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1505210243995.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1505210243995.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1505810689944 because 1506671999000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1505810689944.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1505810689944.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1506416565983 because 1507276799000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1506416565983.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1506416565983.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1507019072090 because 1507881599000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1507019072090.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1507019072090.response-json.response-json
Skipping /var/sandcats/https/<my domain>.sandcats.io/1507628025032 because 1508486399000 is in the past.
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1507628025032.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1507628025032.response-json.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1508229606141.csr.response-json
Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/<my domain>.sandcats.io/1508229606141.response-json.response-json
Certificate we want to use: /var/sandcats/https/<my domain>.sandcats.io/1508229606141 valid starting Tue Oct 17 2017 08:40:14 GMT+0000 (UTC) until Fri Oct 27 2017 07:59:59 GMT+0000 (UTC)
We have only the one key that we know about. We'll need to renew soon.
Migrations already applied: 37/37
Since Sun Oct 22 2017 11:13:25 GMT+0000 (UTC) is more than three days away from Fri Oct 27 2017 07:59:59 GMT+0000 (UTC) not renewing HTTPS cert yet.
/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Invalid PORT specified
    at Object.exports.main (packages/webapp/webapp_server.js:905:15)
    at /programs/server/boot.js:376:27
    at /programs/server/boot.js:390:5
    at Function.run (/programs/server/profile.js:510:12)
    at /programs/server/boot.js:387:11
** Front-end died immediately after starting.
** Sleeping for a bit before trying again...

```

Please let me know if I need to provide more information

**Comment by GitHubGeek** [comment]
My sandstorm instance went down about 6 hours ago. Probably related to this.

**Comment by m-burg** [comment]
Do you have any log output?

**Comment by Michael-S** [comment]
My self-hosted Sandstorm instance is down with the same Javascript stacktrace as @m-burg

**Comment by dwrensha** [comment]
Looks like this is related to https://github.com/sandstorm-io/sandstorm/commit/8d45ddcdb627e3a2ab5e938311d66b871a5bb508.

To debug this, I would try editing /opt/sandstorm/latest/sandstorm-main.js.

**Comment by Michael-S** [comment]
Thanks, I'll give it a go.

**Comment by georgeowell** [comment]
Can confirm. Our Sandstorm instance is totally inaccessible right now.

To downgrade, download https://dl.sandstorm.io/sandstorm-215.tar.xz
nano /opt/sandstorm/sandstorm.conf --> change to UPDATE_CHANNEL=none
then do `sudo sandstorm update sandstorm-215.tar.xz`

**Comment by ocdtrekkie** [comment]
It's like 6 AM for Kenton still, I'm sure he'll fix it today. In the meantime folks, make sure you add any details you can about what your distro and kernel and such is, and anything else you think may be useful in figuring out why it failed for you guys and not Kenton's Sandstorm instances.

(And of course, if you shut off auto-update and do a rollback, make sure to remember to enable it again when it's fixed!)

**Comment by Michael-S** [comment]
I don't know that I have any additional details to add that are notable.  My home workstation/server running a sandcats Sandstorm instance has been up for well over a year and this is the first service disruption ever caused by a child not tripping over the power cord or internet service outages.  The host operating system is Ubuntu MATE 16.04 64-bit, 32GB of RAM.

**Comment by georgeowell** [comment]
@ocdtrekkie proposed on IRC that it might good to have a "stable" update channel where releases are delayed for a week or so for production deployments. Seems "dev" is the only channel right now.

**Comment by ocdtrekkie** [comment]
@georgeowell See conversation on #2536. I'm right with you on that. :P

**Comment by m-burg** [comment]
When I do a dev installation from source it starts up normally on my machine.

Ubuntu 16.04.3 linux 4.10.0-37-generic 64 bit

**Comment by kentonv** [comment]
Hello,

I am looking at this now and should have a fix within an hour.

**Comment by kentonv** [comment]
Apparently servers with HTTPS enabled have been passing multiple ports in the PORT environment variable for a long time, and Meteor just spontaneously started deciding this is an error, but none of my multiple test configs had a multi-port config. :( Fix in the works...

**Comment by m-burg** [comment]
Thanks, Kenton

**Comment by kentonv** [comment]
Fix pushed. Do:

    sudo sandstorm update

(Or it will happen automatically within 24 hours.)

**Comment by zombiezen** [comment]
Thanks for the speedy resolution, @kentonv. 👍

**Comment by aittam** [comment]
Thanks @kentonv !

**Comment by kentonv** [comment]
Post-mortem:

* During every release, I do a `meteor update`. This very rarely has any visible effect, especially for minor updates. In this case, we updated 1.5.2 -> 1.5.2.2.
* However, it turns out that in 1.5.2.1, Meteor merged [a major change to the handling of the PORT environment varibale](https://github.com/meteor/meteor/pull/8702).
* When a Sandstorm server is configured with multiple ports (which is commonly the case for Sandcats, operating on HTTP and HTTPS), we set the PORT environment variable to a comma-separated list of ports. In retrospect, this was a poor choice. But, it used to work: Meteor, in its PORT-parsing code, would parse the first number and ignore the rest. But in 1.5.2.1, it stopped working.
* Sadly, it's impractical for me to rigorously test every feature with every release. So, I tend to focus on testing "the things that chanaged". In this release, the major change was i18n, which mostly involves changes to high-level HMTL templates.
* Since the Sandcats code didn't change, I didn't think to explicitly test in Sandcats mode. I tested on my local dev instance, I ran `make test` to run automated tests, and I brought up Testrock (the staging environment for Oasis), and I verified that Sandstorm Alpha updated correctly. None of these cases are configured with multiple ports.

Resolution:

* In the future, I will always test-update a Sandcats server before pushing a release, even if it seems like nothing changed that would affect Sandcats.

**Comment by GitHubGeek** [comment]
Thank you Sandstorm Team! Much appreciated 💯

**Comment by kentonv** [comment]
Thanks, but, I don't deserve thanks here -- this was an embarrassing failure on my part. This release never should have gone out like this. :/ Sorry for the trouble, I'll try to make sure it doesn't happen again!

**Comment by Xia0ben** [comment]
Hi,

As you are doing this in your free time, yeah, you do deserve thanks =). So thanks !
