### ISSUE TITLE
Backup solution

### ISSUE THREAD

**Issue by zafai** [sandstorm-io/sandstorm#2996]
Hello,

I am currently working on setting up my own sandstorm server.
There is a problem I don't know a solution right now, maybe you have an idea.

Is there an easy and secure way to backup the gains automatically from the command line.
The only solution I found in the FAQ is to stop the complete sandstorm installation then backup it and start it again...

I need to backup all data every night for security reasons.

Thank you

**Comment by Michael-S** [comment]
Maybe one of the official developers has a better solution, but I think rsync could at least make the backup process quick.  Stop sandstorm, rsync -av --delete to another directory (possible on another machine), start sandstorm.  Then use something like "zip -rf --fifo --symlinks sandstorm20171026.zip sandstorm_backup_directory" to make a complete independent backup.   Making the rsync backup will be slow the first time you do it, but after that the day-to-day rsync processes should be quick unless there are colossal changes.

And if you're familiar with rsync and zip and just wanted a better option, I apologize for providing nothing useful here.

**Comment by ertanalytics** [comment]
I do this nightly and have successfully restored.

I schedule a python script to run SSH commands like this:
`
sudo sandstorm stop
sudo service sandstorm stop

tar -cf $HOME/sandstorm-snapshot-from-$(date -I).tar /opt/sandstorm

sudo service sandstorm start
`

This is the same info that is in the backups section of the docs:

https://docs.sandstorm.io/en/latest/administering/backups/

Here is the full Python script I use:

`##

import paramiko, time
from datetime import datetime
from Email_Alert import send_mail

try:

    now = datetime.now()
    targetIP = '0.0.0.0'
    username = 'USER'
    password = '1q2w3e4r5T'
    output = ''


    ssh_client = paramiko.SSHClient()
    ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh_client.connect(targetIP, username=username, password=password)

    remote_conn = ssh_client.invoke_shell()
    time.sleep(10)
    remote_conn.send('sudo service sandstorm stop\n')
    time.sleep(1)
    remote_conn.send(password+'\n')
    output = output+remote_conn.recv(15000)
    time.sleep(1)
    output = output+remote_conn.recv(15000)
    remote_conn.send('sudo sandstorm stop\n')
    output = output+remote_conn.recv(15000)
    time.sleep(1)
    output = output+remote_conn.recv(15000)
    remote_conn.send('sudo tar -cf $HOME/sandstorm-snapshot-from-latest.tar /opt/sandstorm\n')
    output = output+remote_conn.recv(15000)
    time.sleep(5)
    output = output+remote_conn.recv(15000)
    print(output)
    #Seems to force it to wait for an additional output to the shell, so this command waits until the copy is finished
    remote_conn.send('sudo service sandstorm start\n')
    output = output+remote_conn.recv(15000)
    time.sleep(1)
    output = output+remote_conn.recv(15000)
    remote_conn.send('sudo sandstorm start\n')
    output = output+remote_conn.recv(15000)
    time.sleep(1)
    output = output+remote_conn.recv(15000)
    #Grab the remote file and save it locally with a timestamp
    timestr = time.strftime("%Y-%m-%d")
    sftp = ssh_client.open_sftp()
    latestlocalpath = 'sandstorm-snapshot-latest.tar'
    localpath = 'F:/sandstorm-snapshot-from-'+timestr+'.tar'
    remotepath = '/home/'+username+'/sandstorm-snapshot-from-latest.tar'
    sftp.get(remotepath, localpath)
    sftp.get(remotepath, latestlocalpath)
    sftp.close()
    
    print(output)
    with open("Backup SSH REMOTE Log.txt", "a") as myfile:
        myfile.write(output)
    
    ssh_client.close()

except:
    titleString = os.path.basename(sys.argv[0])
    errormsg = str(sys.exc_info()[0])
    send_mail(1,titleString,errormsg)
    
    print "Unexpected error:", sys.exc_info()[0]`
