### ISSUE TITLE
Does not start in LXC

### ISSUE THREAD

**Issue by volkerp** [sandstorm-io/sandstorm#3004]
Unable to run in a LXC, either root or user installation.

Tried the curl pipe bash installation mode as root first.
Installer gives no indication on problems with lxc. Claims server is online, which is not.

`sandstorm start` returns no error even though unable to start.

Same result with non-root installation. No errors reported what so ever, but unable to start.

In both cases sandstorm.log shows
```
** Starting Sandstorm at: Sun Oct 29 10:56:57 2017
*** Uncaught exception ***
sandstorm/run-bundle.c++:1351: failed: mount("none", "/", nullptr, MS_REC | MS_PRIVATE, nullptr): Permission denied
stack: 0x572334 0x56e00a 0x56a6cd 0x569849 0x56983a 0x4a7dd1 0x4a88e4
** Server monitor died. Aborting.
```

Regards
....Volker

**Comment by ocdtrekkie** [comment]
Sandstorm uses a lot of the same containerization features used by LXC, which I don't think containers themselves generally have access to. I don't think it's possible to run Sandstorm inside most containerization environments. That being said, if I'm right (I am not an expert on Linux platform things), documentation and/or the installer should be better improved to inform you of this.

**Comment by zenhack** [comment]
Containerizing sandstorm itself is definitely somewhat uncharted
territory, but it may well be possible to get this working. I know LXC
drops CAP_SYS_ADMIN by default, which would cause the error you're
seeing. You could look into re-enabling that for your container, though
worth noting it would basically defeat the security features of LXC.
It's possible you'll need other posix caps as well. If you're just doing
it for deployment convenience though that may be fine. If you're looking
for extra sandboxing, trying to containerize is probably a no-go, though
sandstorm does do some self-containerization.

Quoting Jacob Weisz (2017-10-29 08:51:19)

**Comment by kentonv** [comment]
It looks like LXC is not actually giving Sandstorm root privileges. There are a number of reasons this could be (I don't really know how LXC does things). It could be denying CAP_SYS_ADMIN as @zenhack says, or it could be that a seccomp filter was installed that blocks mount().

**Comment by kentonv** [comment]
(And in the case where you installed without root privileges, it may be that LXC denies access to user namespaces...)

**Comment by volkerp** [comment]
I see that running in LXC is tricky or not feasible. But I suggest that the install and startup scripts give warnings when not able to run (for whatever reason)
