### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Minege** [sandstorm-io/sandstorm#3005]
Hello,

When i'm on the login page, i can login with github and email, but when i click on github for exemple, it open up the github page, i authorize the access, and then it take me back on that login page..

And when i log over email, it says user not in organisation. But i'm the admin and i already logged once. In total i could log only 2 times in 2 days !

**Comment by Minege** [comment]
`Token not found : myemail@gmail.com `

**Comment by ocdtrekkie** [comment]
Did you by chance enable the setting to restrict users to members of your organization? This setting only works with LDAP, SAML, etc. and will lock you out of logging in with other login methods like Gmail or GitHub.

If you need to get to your admin panel but cannot login, you can use the admin token login method to get in and change your settings: https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-log-in-if-theres-a-problem-with-logging-in-via-the-web

**Comment by Minege** [comment]
Thanks ocdtrekkie,
Just tried to enable guest access, and now it works.

You need to disable this setting :
**Disallow collaboration with users outside the organization.**
Users will be required to log in as a member of your organization to view sharing links. Guest access will be disabled.

**Comment by ocdtrekkie** [comment]
Glad you got it working. This is because it's impossible to define regular Gmail or GitHub users as part of an organization.

**Comment by Minege** [comment]
Yes, i understand.
