### ISSUE TITLE
Firefox 57 on Windows: grain frame fails to load

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#3009]
The console says "SecurityError: The operation is insecure."

![img_20171118_225519960](https://user-images.githubusercontent.com/495768/32987267-6e5f066c-ccb4-11e7-86a4-e9562a5113a4.jpg)

**Comment by ocdtrekkie** [comment]
Interesting. Do you see this on all grains? I've been using Oasis via Firefox 57 since the day it released and had no issue.

**Comment by dwrensha** [comment]
Actually, I don't even get past login. (Maybe "grain frame" is not super precise -- what I mean is, the area where grains usually render is blank.)

**Comment by dwrensha** [comment]
@ocdtrekkie could you try logging in? Maybe go to demo.sandstorm.io in a private window?

**Comment by ocdtrekkie** [comment]
As a useful note, if your issues are with 0.219, Kenton is fixing them right now.

**Comment by ocdtrekkie** [comment]
Version number is not showing changed, but Kenton just deployed some fixes to Oasis. Is your issue better?

**Comment by dwrensha** [comment]
I have lost access to my Windows machine until at least Tuesday.

**Comment by ocdtrekkie** [comment]
FWIW, I have no issues logging in via GitHub login in a private Firefox 57 window. I did not test that prior to these fixes being deployed though, so if your issue is not one of them Kenton just fixed, it may still occur.

My guess is that it pertains to these messages from kentonv:
separately, it appears node now aborts the process when an HTTP client decides to disconnect before they've received the full response. WTF?
I must be missing something because that's a ridiculously stupid behavior, if that's what it's doing.
JFC, it also aborts when it fails an SSL handshake

**Comment by kentonv** [comment]
Was this a one-time thing or did it happen consistently the same way?

**Comment by dwrensha** [comment]
I did not succeed after multiple tries in Firefox. I eventually switched to Internet Explorer and succeeded.

**Comment by Albibek** [comment]
Hi. I have probably the same issue on LINux with Firefox 57. It reproduces on cookie-using grains, found it on Etherpad and Tiny Tiny RSS. Both say my cookies are disabled and refuse to work.

**Comment by kentonv** [comment]
FWIW I just tested Firefox 57 on Linux and was not able to reproduce any issues.

@Albibek Your problem sounds different from @dwrensha's -- he didn't even open a grain. If grains complain about cookies, one possibility is that your browser settings or an extension are blocking cookies for some reason. Sometimes browser privacy settings or privacy-related extensions see Sandstorm's use of cookies inside of iframes and incorrectly think it is an advertisement or a tracker, and then they block the cookies. You can try disabling extensions and settings to see if it fixes the problem.

**Comment by dwrensha** [comment]
It's now working for me, after I've restored default settings by clicking Help -> Troubleshooting Information -> Refresh Firefox.

I think my problem was that `dom.storage.enabled` was set to false, probably leftover from me debugging some other problem long ago.
