### ISSUE TITLE
TTRSS hasn't gotten feeds since 0.219

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3010]
I realized last night that my TTRSS grain's last feed stories it picked up were all before the release of 0.219, and they still don't work today. 0.220 does not appear to have fixed the issue.

**Comment by scottjw** [comment]
I see the following in the grain's log when a feed update is attempted. The feed does not update.

`[14:34:50/294] Base feed: http://securityaffairs.co/wordpress/feed
[14:34:50/294]  => 1970-01-01 00:00:00, 103 1
*** Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: ReferenceError: req is not defined
    at Promise (server/hack-session.js:429:9)
    at new Promise (<anonymous>)
    at inMeteor.then.safe (server/hack-session.js:415:14)
    at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
stack: 0x439ff0 0x41b9c0 0x41a050 0x402730 0x40303c 0x402953 0x4027cd 0x4b4e71
[14:34:50/294]     0.1007 (sec)`

**Comment by ocdtrekkie** [comment]
I wonder if that needs a `const` before it like the other thing broken that way.

**Comment by scottjw** [comment]
Did this perhaps break because of the following two changes in [v0.219](https://github.com/sandstorm-io/sandstorm/commit/5614213541d993902cbfc1867c5bab85f70b9349)?
```
- Updated Meteor to version 1.6, a new major release.
- Updated Node.js to version 8 (from 4).
```

**Comment by ocdtrekkie** [comment]
@scottjw Most certainly, yes. 0.220 fixed a very similar issue in a different part of Sandstorm's code.

**Comment by scottjw** [comment]
@ocdtrekkie Are you talking about the change in commit 9ebe85674a81017bed46a77f8360fd9152f42fb0?

**Comment by ocdtrekkie** [comment]
No, my guess was that it's similar to https://github.com/sandstorm-io/sandstorm/commit/05b113851552fe9a816cd160e63e1390104a8684

Based on your error message: (remote):0: failed: remote exception: remote exception: remote exception: remote exception: ReferenceError: req is not defined
    at Promise (server/hack-session.js:429:9)

And this line: https://github.com/sandstorm-io/sandstorm/blob/b96667e1de9e060a7caf7f861005740f1d412fe7/shell/server/hack-session.js#L429

**Comment by kentonv** [comment]
Sorry all, I'll push a fix tonight.

**Comment by kentonv** [comment]
(Node.js version 8 apparently now disallows inadvertent assignments to globals. This is good! But they only detect it at runtime, not at compile time. So what used to be buggy-but-working code is now broken, and there's no way to find it without testing absolutely everything in the codebase. And yeah, we don't have great test coverage. :( )

**Comment by kentonv** [comment]
Fixed on Oasis. Self-host release coming.

**Comment by kentonv** [comment]
This was the fix: https://github.com/sandstorm-io/sandstorm/commit/30eb8f46ef47deb594ef24e10615de4da11d9178

Classic JavaScript bug, but I'm shocked that Node 8 would make this a runtime error (yet... not a compile-time error).

**Comment by kentonv** [comment]
Update for self-hosters is pushed. Do:

    sudo sandstorm update

Or just wait and you'll get it within 24 hours.

**Comment by scottjw** [comment]
Thanks @kentonv updates work again.
