### ISSUE TITLE
RocketChat.io app loader keeps spining when installing

### ISSUE THREAD

**Issue by MartiniHenry1988** [sandstorm-io/sandstorm#3021]
I have setup my Sandstorm.io on a local machine, When I try to install rocketchat.io, the loader appears and keeps spining non stop, what could be the issue? How can I fix it?

**Comment by ocdtrekkie** [comment]
Was this after Rocket.Chat was installed on your server, when you first tried to open a copy of it? How long did you let it run? Rocket.Chat is, to my recollection, fairly slow to start up. Do other apps work fine on your server?

**Comment by MartiniHenry1988** [comment]
I installed Sandstorm.io and I click on install RocketChat, and then a spinner appeared and it keeps loading non stop

**Comment by ocdtrekkie** [comment]
Does this occur when you try to install any other apps?

**Comment by MartiniHenry1988** [comment]
@ocdtrekkie I will check that and I will let you know.

**Comment by ocdtrekkie** [comment]
I'm going to close this since there was no followup on whether or not it was app-specific.
