### ISSUE TITLE
Firefly III - remote exception: expected result >= minBytes; Premature EOF

### ISSUE THREAD

**Issue by estefanlee** [sandstorm-io/sandstorm#3022]
While using Firefly III, I suddenly get the following error:
Error: remote exception: expected result >= minBytes; Premature EOF
C++ location:(remote):??
type: failed

The debug log shows the following message:
...*** couldn't connect to grain (Error: remote exception: expected result >= minBytes; Premature EOF) ***

**Comment by ocdtrekkie** [comment]
Tagging @JC5

When you say suddenly, can I assume that means that Firefly III is correctly loaded, and you are using it, and then it stops working in the middle of using it?

**Comment by JC5** [comment]
What were you trying to do? What was the page you happened to visit at that moment?

**Comment by estefanlee** [comment]
Yes, exactly: I was storing a new transaction

**Comment by JC5** [comment]
One final detail: did you submit the form already, or did you only visit the page, when it crashed.

**Comment by estefanlee** [comment]
I'm sorry, not sure. I'll try to reproduce the problem and I'll be more precise.

Yesterday I got this error twice and I wasn't able to recover loosing all my data previously stored in firefly III. Now I'm doing a grain backup quite often but it's very uncomfortable. Could you suggest a better way?

Thanks a lot.

**Comment by JC5** [comment]
Well, let me at least apologize for running into this problem. Firefly III is being developed by me, and this shouldn't happen.

I shall try and replicate your problem. I have a feeling I know what is going on, but nothing definitive yet.

**Comment by JC5** [comment]
A possible cause has been identified (the excessive creation of cache directories, which clogs resources). I will try to get a fix for the next release. In the mean time, you can recover your data by temporarily changing this limit (please see the linked issue).

**Comment by estefanlee** [comment]
OK, many thanks!

**Comment by ocdtrekkie** [comment]
This can be closed. It's marked as "fixed" in the Firefly repo.
