### ISSUE TITLE
Setup loop when attempting to use Github for administrator account

### ISSUE THREAD

**Issue by mozebdi** [sandstorm-io/sandstorm#3025]
I am attempting to setup a Sandstorm server on a self-hosted subdomain. Currently I can access it over HTTPS, I have a working wildcard SSL cert through Cloudflare, and face no issues accessing other HTTPS services hosted on that domain. However, whenever I try to use the Github sign-on option to complete the setup by creating an admin account, I am redirected to the same "create administrator account" page with no change. The Sandstorm server appears to be running with no issues according to systemctl status.

**Comment by ocdtrekkie** [comment]
At any point did you ever try to "disallow collaboration with users outside the organization"? This isn't usually the context I hear of these sorts of issues, but it's always a good one to check when people are having issues with Google or GitHub login.

**Comment by mozebdi** [comment]
Nope - I have that box unchecked on my setup.

**Comment by mozebdi** [comment]
It appears that this issue also occurs when attempting to create the administrator account using a Google OAuth account. I might hypothesize that OAuth is not a valid way to create an administrator account - is this correct? If so, then why is OAuth allowed as a way to set up the administrator account?

**Comment by ocdtrekkie** [comment]
I am pretty sure you should be able to. It is probably some other sort of bug. I don't know what to suggest looking at though, I'm hoping someone else can jump in with another idea.

**Comment by ocdtrekkie** [comment]
My best impression is that something is wrong with how OAuth callback is working, but I am not sure how to troubleshoot it.

**Comment by kentonv** [comment]
After some IRC debugging it sounds like the problem may be that @mozebdi had an nginx proxy set up to implement HTTPS, but had configured `BASE_URL=http://<hostname>`. BASE_URL needs to match what is written in the browser. This can cause OAuth to fail because OAuth is very sensitive to the origin URL that it is authorizing, and unfortunately OAuth isn't very good at reporting errors when it fails.

**Comment by mnaamani** [comment]
> At any point did you ever try to "disallow collaboration with users outside the organization"? This isn't usually the context I hear of these sorts of issues, but it's always a good one to check when people are having issues with Google or GitHub login.

I did see the same problem, trying to complete the setup with google and github login and I had the option checked to disallow collaboration with users outside the organisation. So after unchecking the option and successfully completing setup, if you go back into the admin setting and re-enable the option, then logout. You can no longer login with OAuth

Does this mean in Sandstorm that users logging in with OAuth are not considered to be part of the organisation?

**Comment by ocdtrekkie** [comment]
@mnaamani Public Google or GitHub accounts are not considered part of an organization, so cannot log in if that setting is selected. I do believe you can define a Google Apps domain, so that is likely supported with this configuration option on, but I haven't tested it personally.

**Comment by mnaamani** [comment]
Thanks for that clarification @ocdtrekkie 
So LDAP and SAML login providers are ideally the ones to use for organisation users?

**Comment by ocdtrekkie** [comment]
It sounds like this got troubleshooted out, so I'm going to close it.
