### ISSUE TITLE
Fix Mongodb

### ISSUE THREAD

**Issue by lramage94** [sandstorm-io/sandstorm#3026]
https://docs.sandstorm.io/en/latest/administering/faq/

"In theory, this error message can occur if your Sandstorm database (stored in /opt/sandstorm/var/mongo) has become corrupted. So far, we have seen no instances of this in the wild. If it does occur, you can likely recover from the situation. Even if there is a problem with the Sandstorm MongoDB instance, note that grain data is safely stored separately, so any grain data would not be affected."

How does one reset/restore the mongo database?

**Comment by kentonv** [comment]
Unfortunately there isn't an easy answer -- if there was, it would be automated. I've never experienced Mongo corruption that wasn't automatically repaired, so I don't know much about this subject myself. You can probably find guides on the internet or in MongoDB's own documentation. Sandstorm's database is stored at `/opt/sandstorm/var/mongo`; you'll probably have to run some sort of repair tool on it.

Note that I recommend using the Mongo binaries that are bundled with Sandstorm. They are an older version of Mongo. If you use a newer version to do the repair, there's a risk that the result will no longer be compatible with Sandstorm's version.

Of course, you should make a backup of your database before doing any repair. Don't forget to maintain the file ownership and permissions.

**Comment by lramage94** [comment]
Thanks for the reply. I may have a slightly bigger problem than I originally thought. I do not have that folder.

![screen shot 2018-01-22 at 12 28 29 pm](https://user-images.githubusercontent.com/1371474/35234624-cf76f840-ff6f-11e7-9c75-6ea9473c2808.png)

**Comment by kentonv** [comment]
@lramage94 Yikes. I don't know what to tell you. :(

Maybe try checking `/lost+found`? (ext4's fsck tool will sometimes relocate files there when recovering from filesystem corruption.)

Otherwise, it seems that something removed a huge chunk of your Sandstorm installation's data files and the only way to get them back is to figure out where they went... Sandstorm definitely wouldn't have done this to itself.

**Comment by lramage94** [comment]
I did perform a hard reboot on the system (for an issue not related to this), so maybe it broke it? 

I guess I will just reinstall from scratch.

Thanks!
