### ISSUE TITLE
Custom App Market URL

### ISSUE THREAD

**Issue by morgan8ter** [sandstorm-io/sandstorm#3029]
Sandstorm Version - 0.224
OS - Fedora 26 (Server Edition)

Sandstorm is working well except for an issue I'm experiencing with admin/app-sources

I would like to use a custom App market and have set the custom App market URL to https://apps.example.local and it sets the Install... from app market link/button correctly, however following that link/button goes to https://apps.sandstorm.io/?host=https://sandstorm.example.local instead of https://apps.example.local/?host=https://sandstorm.example.local

I can't see any issues in the system log and I haven't found any other posts related to this. Has anyone else seen this or have any suggestions to resolve. Let me know if there is any other info that I can provide that will help.

**Comment by ocdtrekkie** [comment]
The redirect link back to your Sandstorm server is located in the App Market code, not Sandstorm itself, and the App Market code isn't customized by your Sandstorm server's settings. If you are hosting a version of https://github.com/sandstorm-io/sandstorm-app-market on your domain, you may have to find that in the code and change it yourself.

**Comment by ocdtrekkie** [comment]
Ah, there's a settings.json for some of the app market URL settings, documented in the app market's readme. And I think I misread where you're having the issue. :/

There's a good chance there's something hardcoded somewhere though, not a lot of people run their own app market, so it probably hasn't been super well tested in that regard.

**Comment by kentonv** [comment]
Whoa... Indeed, after changing the app market URL to something random, if I go to the apps page and hover over the "Install" button, the status bar shows the URL I set, but if I click on it, I always end up at apps.sandstorm.io instead. This seems to be a bug. In fact, it looks like several hard-coded copies of the link have shown up in the source code, even though I thought we had carefully replaced all of them.

**Comment by morgan8ter** [comment]
Happy that you were able to reproduce this issue. Just noticed that it appears to occur only when the "Install" button is clicked, but works as expected if you right click the button and choose open in a new tab.

**Comment by ocdtrekkie** [comment]
Clearly, we have the solution: Tell everyone to always right click and open in a new tab! :D

I think this should be pretty easy to find and fix before the next Sandstorm release, I might dig around a bit tomorrow or the next day.

**Comment by ocdtrekkie** [comment]
There are plenty of references that are like, specific app links in documentation or even the admin panel that should remain, but these are the ones I think need to be changed, @kentonv, to resolve this for @morgan8ter. I will probably avoid doing my own PR on this one since each one likely has a little different solution, they're all in different types of files in the code. 

This appears to be the misbehaving line of code here, which hardcodes the official app market on install button click: https://github.com/sandstorm-io/sandstorm/blob/b96667e1de9e060a7caf7f861005740f1d412fe7/shell/client/apps/applist-client.js#L195

Also, and this one has irritatingly ended up in our i18n files, but when you accept an invite to Sandstorm, it suggests you install some apps, and the URL is hardcoded: https://github.com/sandstorm-io/sandstorm/blob/55de6e81f2c21dc327eb313383bbc4483d65d9ae/shell/i18n/en.i18n.json#L55

Probably worth fixing: The App Market link on the app page should probably route to a self-hosted source if it exists: https://github.com/sandstorm-io/sandstorm/blob/b96667e1de9e060a7caf7f861005740f1d412fe7/shell/client/apps/app-details.html#L90

**Comment by gischer** [comment]
Well, I thought I had fixed this issue with PR #3568 but it seems to not be the case.  It is pretty mysterious to me at this point why not.

I am using a custom App Market URL (https://app-market.mansia.net) on my site (mansia.net).  In the html, the href is set correctly to `https://app-market.mansia.net?host='https://mansia.net'`.  But a click on the icon takes me to `https://apps.sandstorm.io/?host='https://mansia.net'`   I cannot see why this should be so from looking at the code.

In `sandstorm/shell/imports/client/apps/applist-client.js`
Here is the helper that sets the href:

```
 appMarketUrl: function () {
    const ref = Template.instance().data;
    const appMarket = ref._db.collections.settings.findOne({ _id: "appMarketUrl" });
    if (!appMarket) {
      return "#";
    }

    return appMarket.value + "/?host=" + document.location.protocol + "//" + document.location.host;
  },


```

And here is the code that is run when the "Install from market" button is clicked:

```
"click .install-button": function (event) {
    event.preventDefault();
    event.stopPropagation();
    const ref = Template.instance().data;
    const appMarket = ref._db.collections.settings.findOne({ _id: "appMarketUrl" });
    let url = "https://apps.sandstorm.io/?host=";
    if (appMarket) {
      url = appMarket.value + '?host=';
    }
    window.open(url +
        document.location.protocol + "//" + document.location.host, "_blank");
  },

```

Now, I could just modify the <a> tag to include target="_blank" and getrid of the event above entirely.  I don't think it has any purpose at this point.  I am prepared to do a PR to address this.

But mysteries bug me. I mean, it could be something dumb, and that would be a relief, but maybe it's something I don't understand and which will come up again and cause more problems?   Also, perhaps there was a purpose in doing things this way?  Maybe not, though.

As an administrative aside - can I/should I use the same fork I used for #3568 to address this, or should I create a new one.

**Comment by ocdtrekkie** [comment]
I would do a new fork from master, as it's a new change. I am kind of wondering if that "appMarket" variable isn't successfully being set somehow... This seems like it's just not overwriting that default let url = in the click event. At least, that's how it's behaving.

**Comment by gischer** [comment]
I just wasn't sure that deleting the old fork wouldn't damage some record keeping.  I'll get on this.

Meteor sometimes loses some context and this means that Template.instance() will do something odd.  But I would have thought that would leave evidence of a thrown exception in the browser console and it isn't.
