### ISSUE TITLE
installer breaks with openrc

### ISSUE THREAD

**Issue by ghost** [sandstorm-io/sandstorm#3030]
$ curl https://install.sandstorm.io | bash
main: line 1554: service: command not found
main: line 1582: update-rc.d: command not found

```
configure_sysvinit_init_system() {
  # WARNING: This function should only be run if we already know 
  # sysvinit is the current init system. It relies on its caller to
  # verify that.

  # Stop Sandstorm, since we don't know what its configuration is.
  if [ -e /etc/init.d/sandstorm ] ; then 
    service sandstorm stop || true # line 1554
  fi
...
  # Mark as executable, and enable on boot.
  chmod +x /etc/init.d/sandstorm
  update-rc.d sandstorm defaults # line 1582
```

**Comment by Michael-S** [comment]
Would you mind including what Linux distribution you're using, so that anyone who wants to work on this can test with the exact same setup?  Gentoo (systemd is optional in Gentoo)?

**Comment by lramage94** [comment]
I have tested this on both Gentoo and Alpine Linux.

Openrc is the default init system for both of those distributions.

 I haven't tested it yet, but this may also affect TrueOS (based on FreeBSD), and Artix Linux (Arch-Openrc, Manjaro-Openrc).

**Comment by Michael-S** [comment]
For some of the container features Sandstorm uses APIs specific to Linux kernel 3.10 or newer, (please see https://docs.sandstorm.io/en/latest/install/) so TrueOS definitely won't work.

I'm not one of the project contributors.  I might be able to take Gentoo for a spin in a VM in a few days, but I don't want to promise if I can't manage it.

**Comment by lramage94** [comment]
Oh alright. I am new to this project. I saw in there that it had support for sysvinit and assumed it could support the BSD's too. 

I will look into it as well. I have sandstorm running ( I manually created /etc/init.d/sandstorm and enabled it ), but I just figured I'd make a bug report. When I have time, I may be able to submit a pull request.

**Comment by kentonv** [comment]
I'd be happy to accept a PR to the installer script adding support for other init systems. :)

**Comment by ocdtrekkie** [comment]
A fix for this was merged already.
