### ISSUE TITLE
Translate error

### ISSUE THREAD

**Issue by MatheusRV** [sandstorm-io/sandstorm#3031]
Hello, 

I win an opensource account on LingoHub and want to put all translations on same server.

Butt 

nl.i18n.json has an error

```
The uploaded file seems to be invalid and could not be parsed. Please verify that the file has a valid syntax. If you have questions, contact the Support.

 Could not parse file content

Could not parse input for format 'Standard JSON'
Reason: 'Duplicate field 'subtext'
 at [Source: java.io.StringReader@7f9400fa; line: 1093, column: 16]'
```

https://translate.lingohub.com/sandbird/sandstorm-shell/dashboard

**Comment by ocdtrekkie** [comment]
Looks like just a duplicate line. I opened up #3032 for Kenton to merge.

**Comment by ocdtrekkie** [comment]
Another note @MatheusRV is that you may want to examine which apps already have translation setups and how they accept i18n changes. For instance, while a simple PR to Sandstorm is fine, Wekan uses Transifex (and only accepts translation updates via Transifex), and I believe Etherpad has a similar arrangement for TranslateWiki.

Many apps currently have no translations though, and would probably welcome PRs to add it.

**Comment by MatheusRV** [comment]
Nice, the app used for translate is open, I suggest Zanata installed on a sandstorm.io server. 

But right now we are finishing the Portuguese Translations, that's why I choose LingoHub.

**Comment by MatheusRV** [comment]
Closing for now.
