### ISSUE TITLE
All piwik visitors appear with IP 10.240.0.0

### ISSUE THREAD

**Issue by kasbah** [sandstorm-io/sandstorm#3035]
Hello, I have been using Piwik for analytics for quite some time and it has been working really well. But now, all visitors since Sunday 4 February 2018 at 08:17 (GMT) appear to be coming from IP 10.240.0.0. The last two IP digits are anonomized so the actual IP is probably a bit different.

**Comment by kentonv** [comment]
Hi @kasbah,

Ouch, I guess this was caused by the HTTP stack rewrite (PR #3007). I'll try to get this fixed today.

**Comment by kentonv** [comment]
Will deploy fix at 11 PM PST / 7 AM GMT.
