### ISSUE TITLE
Cannot run vagrant-spk: 404 when downloading the box sandstorm/debian-jessie64

### ISSUE THREAD

**Issue by dmitry-sher** [sandstorm-io/sandstorm#3043]
```
sherd@osboxes:~/Mailpile$ vagrant-spk vm up
Calling 'vagrant' 'up' in /home/sherd/Mailpile/.sandstorm
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'sandstorm/debian-jessie64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'sandstorm/debian-jessie64'
    default: URL: https://vagrantcloud.com/sandstorm/debian-jessie64
==> default: Adding box 'sandstorm/debian-jessie64' (v8.2.1) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/sandstorm/boxes/debian-jessie64/versions/8.2.1/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
Command failed with a non-zero exit status (1).
```

**Comment by dmitry-sher** [comment]
there are numerous solutions here:

https://github.com/hashicorp/vagrant/issues/9442

i've just added this line 
```
Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com') 
```

before 
```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
```

**Comment by ocdtrekkie** [comment]
Ahhhh... bitrot. :(

If you want to open a PR to update it, perhaps we can get someone to push an updated version of vagrant-spk. At the moment vagrant-spk doesn't really have an owner and is sort of on life support.

**Comment by dmitry-sher** [comment]
https://github.com/sandstorm-io/vagrant-spk/pull/209

**Comment by dmitry-sher** [comment]
I need to add that my fix worked for me on vagrant 1.9.4.
But it didn't helped my friend with vagrant 2.0.2. We are looking now into the problem for his version.

**Comment by dmitry-sher** [comment]
OK.. actually the problem persists for every version of vagrant. The solution from PR works only if you have already that box file downloaded. And it's nowhere on the internet anymore. I was lucky because i had that file from my previous attempts with sandstorm last summer. 

I can share mine one on a Google Drive. Or please advise me any other way to share vbox file. I don't know what's the actual differences for Sandstorm Debian 8.2.1 are from any other images and is there any reason to use the Sandstorm Debian 8.2.1. Or you can swap that image with any other debian 8.2.1 one.

**Comment by ocdtrekkie** [comment]
I believe it is effectively a snapshot of Debian 8.2.1 because they broke vboxsf support, based on the description here: https://github.com/sandstorm-io/vagrant-spk/commit/2e8a484af5f7f391b3d3c8d812ecaa7bf6480407

**Comment by ocdtrekkie** [comment]
This might work: https://app.vagrantup.com/debian/boxes/contrib-jessie64 ?

**Comment by ocdtrekkie** [comment]
@dmitry-sher So @Kasgel put this together: https://github.com/sandstorm-io/vagrant-spk/pull/210 and that gets... further. Another issue though, https://github.com/capnproto/capnproto/issues/635 is currently holding up vagrant-spk-based packaging.

**Comment by kentonv** [comment]
OK I fixed the capnp issue at git master. I guess that should fix whatever's going wrong here? I don't quite know what vagrant-spk is doing under the hood that involves invoking capnp.

**Comment by ocdtrekkie** [comment]
I think this can be closed.
