### ISSUE TITLE
Firefly III - the system doesn suggest tag anymore

### ISSUE THREAD

**Issue by estefanlee** [sandstorm-io/sandstorm#3045]
I'm using version 4.7.
Adding a new a new withdrawal, when I type the first letter of an existing tag the application doesn't suggest the complete word anymore.

**Comment by ocdtrekkie** [comment]
@estefanlee Issues with apps can generally reported directly to the app (though make sure the author knows you're on Sandstorm!). In this case, @JC5 handles Firefly III's packaging directly, and you can report the issue directly to Firefly III: https://github.com/firefly-iii/firefly-iii/issues

**Comment by estefanlee** [comment]
OK, thank you very much.

**Comment by JC5** [comment]
This is a known issue, and it'll be fixed in the next release of Firefly III :)

**Comment by ocdtrekkie** [comment]
Note that Firefly III 4.7.1 is now approved on Sandstorm, which appears to fix this issue.

**Comment by estefanlee** [comment]
Thanks a lot for the information

Il 05 mar 2018 08:04, "Jacob Weisz" <notifications@github.com> ha scritto:
