### ISSUE TITLE
Some error after fresh install

### ISSUE THREAD

**Issue by asterom** [sandstorm-io/sandstorm#3054]
Hello, we have some error when start app

** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain no longer in use; shutting down.
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: privileged
[06-Mar-2018 13:15:52] ERROR: failed to open error_log (/var/log/php-fpm.log): No such file or directory (2)
[06-Mar-2018 13:15:52] ERROR: failed to post process the configuration
[06-Mar-2018 13:15:52] ERROR: FPM initialization failed
started php-fpm. status code: 78
2018/03/06 13:15:52 [emerg] 29#29: mkdir() "/var/lib/nginx/client-body" failed (2: No such file or directory)
started nginx. status code: 1
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
*** lost connection to grain (probably because it shut down) ***

But file exist!
ls -la
-rw-r-----php-fpm.log /var/log

/var/lib/nginx

exist body and we crete client-body dir

drwx------  2 www-data root 4096 Mar  2 17:13 body
drwx------  2 www-data root 4096 Mar  6 15:46 client-body

**Comment by ocdtrekkie** [comment]
Important information to include if you have an issue with an app... Which app?

**Comment by asterom** [comment]
wordpress

**Comment by asterom** [comment]
Other app - rocket chat, Etherpad, very nice work.

**Comment by ocdtrekkie** [comment]
@asterom Was this a fresh/empty WordPress grain, or did you modify the file contents? Did you import a WordPress, install any plugins, themes, etc.?

**Comment by ocdtrekkie** [comment]
Also, we now have an experimental version of WordPress 4.9.4 if you'd like to try it, here on the experimental market: https://apps.sandstorm.io/app/aax9j672p6z8n7nyupzvj2nmumeqd4upa0f7mgu8gprwmy53x04h?experimental=true

**Comment by ocdtrekkie** [comment]
We never got a response on this one, and WordPress has been updated since, so I'm going to close this.
