### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 502

### ISSUE THREAD

**Issue by timshannon** [sandstorm-io/sandstorm#3055]
I've recently had music consistently stop during playback in Groove Basin.  Checking the chrome dev tools I see this here accompanies the interruption in playback:

`WebSocket connection to 'wss://ui-bc67ae489980c43915efce631cbfc979.townsourced.com/' failed: Error during WebSocket handshake: Unexpected response code: 502`

It doesn't look like there are any recent updates to Groove Basin, and this has only started recently (in the past week I believe), so I assume it's due to a recent sandstorm update.

I'm seeing these entries accompanying these errors in the sandstorm System Log from the admin page:

```
kj/compat/http.c++:3468: error: HttpService threw exception after generating a partial response; too late to report error to client; e = sandstorm/web-session-bridge.c++:839: failed: app did not finish writing HTTP response stream
stack: 0x6ac990 0x6af740
```

**Comment by dwrensha** [comment]
I confirm that I am seeing the same error. The stream always halts after a minute or two. :(

This seems likely to be related to https://sandstorm.io/news/2018-02-19-http-rewrite-and-more.

**Comment by kentonv** [comment]
Hmm, I bet this is because the Supervisor now shuts down the grain based on lack of incoming traffic rather than based on it being open in the UI. I guess outgoing traffic needs to be considered as well, but specifically outgoing traffic to a real client, not app-initiated outgoing traffic... Will fix today.
