### ISSUE TITLE
Last activity is not updating for some grains

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3059]
In this case, I can speak to an EtherCalc grain that I opened twice today. Both times I had to dig down and find it, because the last time it *says* it was updated was on March 11th. But that isn't true.

**Comment by ocdtrekkie** [comment]
I have not made any sense out of what causes this to update or not. Happens to multiple apps, including some Etherpad grains of mine which show their last opened date correctly, and some which do not.

**Comment by kentonv** [comment]
Hmm, digging into the code, it looks like the last-used time may only be updated after a grain has been open for a minute. Is this consistent with your observations?

**Comment by ocdtrekkie** [comment]
Seems plausible, I do a lot of quick-update operations on some documents.

**Comment by garrison** [comment]
After this fix, my most recently opened apps listed are now all Radicale and Piwik instances.  It used to be (even prior to the HTTP gateway change) that these would only be at the top of the list if I opened them explicitly through the Sandstorm UI, not if e.g. my phone synced with Radicale or somebody visited a page with a Piwik javascript include on it.

Is this portion of the change intentional?  The recently-used list is a bit less useful this way, but I could get used to it.

**Comment by ocdtrekkie** [comment]
I definitely noticed that change and mentioned it on IRC, though I only really access one app over the API, so I didn't see how irritating that would be. (I said I liked the change.)

I don't think it was intentional.

**Comment by kentonv** [comment]
It used to be that accessing grains through the API did not update the last-accessed time. In my opinion, that was a bug. I did intentionally fix that here.

However, I could be convinced that this is not desired behavior, I guess? Does anyone else have an opinion on this?

**Comment by ocdtrekkie** [comment]
I kinda liked that my TTRSS instance floated to the top, but I would agree with @garrison that if you're using Radicale and Piwik and the like that see a lot of access from external sources, that would be really irritating.

**Comment by ar-jan** [comment]
I'd previously noticed the lack of updating "last activity" when accessing a grain via API - in my case, `git push` etc. to Gitlab and syncing with Radicale. I like the change to how it works now.

**Comment by ocdtrekkie** [comment]
I want to say when I mentioned it during the Sandstorm-the-company days, I think... maybe Jason... said it was an intentional choice. Maybe there should eventually be a feature or option for either apps to denote if their API usage should show as an activity update or not, or users should be able to prevent a grain from bumping up their grain list or something.

Arguably, accessing the API is indeed "activity", so the last activity should, arguably, update. And in some cases, like TTRSS, API use may represent the user just using a third party app instead of the web UI.

Another interesting aspect/useful feature is that, say, if you're using a Sandstorm grain for metrics/telemetry, such as Piwik, which you may not check often, the fact that it is showing activity updates means your telemetry is still working, and it falling down the list may suggest your analytics is no longer functional.

**Comment by garrison** [comment]
I could imagine that both dates/times -- the most recent open through the UI as well as the most recent activity of any sort -- could be useful information.  So one thought is to store them both.  And then the remaining question would be which one the grain-selection UI should sort by.
