### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Geocali** [sandstorm-io/sandstorm#3070]
I kept my sandstorm server shut down for some time, and started it yesterday 16 may at 18h37 (16h37 according to the sandstorm logs) and now I get this error when I try to access it :

ERR_CONNECTION_REFUSED

I tried to clear the cache of my browser, and my sandstrom server is running:

`$ sudo service sandstorm status`

> ● sandstorm.service - Sandstorm server
>    Loaded: loaded (/etc/systemd/system/sandstorm.service; enabled; vendor preset: enabled)
>    Active: active (running) since mer. 2018-05-16 20:42:00 CEST; 13h ago
>   Process: 5070 ExecStop=/opt/sandstorm/sandstorm stop (code=exited, status=0/SUCCESS)
>   Process: 5075 ExecStart=/opt/sandstorm/sandstorm start (code=exited, status=0/SUCCESS)
>  Main PID: 5086 (sandstorm/top)
>     Tasks: 73
>    Memory: 155.2M
>       CPU: 2min 53.419s
>    CGroup: /system.slice/sandstorm.service
>            ├─ 5086 ../latest/sandstorm (top-level)                           
>            ├─18605 ../latest/sandstorm (updater)                             
>            ├─18606 ../latest/sandstorm (server monitor)                      
>            ├─18607 ../latest/sandstorm (back-end)                            
>            ├─18611 /bin/mongod --fork --bind_ip 127.0.0.1 --port 6081 --dbpath /var/mongo --logpath /var/log/mongo.log --pidfilepath /var/pid/mongo.pid --auth 
>            ├─18662 ../latest/sandstorm (dev daemon)                          
>            ├─18663 /bin/node sandstorm-main.js
>            └─18664 ../latest/sandstorm (gateway)                             
> 
> mai 16 20:42:00 obrasileiro systemd[1]: Starting Sandstorm server...
> mai 16 20:42:00 obrasileiro sandstorm[5075]: Sandstorm started. PID = 5086
> mai 16 20:42:00 obrasileiro systemd[1]: Started Sandstorm server.

I checked the certificates :

`$ /opt/sandstorm/var/sandcats/https/geocali.sandcats.io# ls`

> 0                            1517301392975                1519723396322                1522227745269                1524646892522
> 0.csr                        1517301392975.csr            1519723396322.csr            1522227745269.csr            1524646892522.csr
> 0.response-json              1517301392975.response-json  1519723396322.response-json  1522227745269.response-json  1524646892522.response-json
> 1515485188782                1517904980142                1520454998277                1522833748644                1525248971508
> 1515485188782.csr            1517904980142.csr            1520454998277.csr            1522833748644.csr            1525248971508.csr
> 1515485188782.response-json  1517904980142.response-json  1520454998277.response-json  1522833748644.response-json  1525248971508.response-json
> 1516093887065                1518518225056                1521021338427                1523438609042                1525856434900
> 1516093887065.csr            1518518225056.csr            1521021338427.csr            1523438609042.csr            1525856434900.csr
> 1516093887065.response-json  1518518225056.response-json  1521021338427.response-json  1523438609042.response-json  1525856434900.response-json
> 1516697627296                1519116371185                1521622861843                1524038933213                1526488652904
> 1516697627296.csr            1519116371185.csr            1521622861843.csr            1524038933213.csr            1526488652904.csr
> 1516697627296.response-json  1519116371185.response-json  1521622861843.response-json  1524038933213.response-json  1526488652904.response-json

Here is the end of the contents of the logs

`$ sudo less /opt/sandstorm/var/log/sandstorm.log`

> Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/geocali.sandcats.io/1525856434900.csr.response-json
> Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/geocali.sandcats.io/1525856434900.response-json.response-json
> Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/geocali.sandcats.io/1526488652904.csr.response-json
> Skipping unreadable HTTPS key information file while examining: /var/sandcats/https/geocali.sandcats.io/1526488652904.response-json.response-json
> Certificate we want to use: /var/sandcats/https/geocali.sandcats.io/1526488652904 valid starting 2018-05-16T16:37:41.000Z until 2018-05-26T07:59:59.000Z
> We have only the one key that we know about. We'll need to renew soon.
> Since 2018-05-17T06:59:51.995Z is more than three days away from 2018-05-26T07:59:59.000Z not renewing HTTPS cert yet.

Maybe there is a way to force the renewal of the certificate ?

**Comment by xet7** [comment]
Try updating sandstorm:
`sudo sandstorm update`

**Comment by Geocali** [comment]
It is already the last version

> Checking for updates on channel dev...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100     4  100     4    0     0      6      0 --:--:-- --:--:-- --:--:--     6
> No update available.

**Comment by xet7** [comment]
Try stopping and starting sandstorm:
```
sudo sandstorm stop
sudo sandstorm start
```
If normal login does not work, login with admin-token url, and configure auth methods again:
```
sudo sandstorm admin-token
```

**Comment by Geocali** [comment]
ok, I stopped and restarted, and generated the new admin token.

However, when I try to access the URL, I have an ERR_CONNECTION_REFUSED

**Comment by xet7** [comment]
Have you installed all updates and rebooted server?

**Comment by Geocali** [comment]
Yes, there was no update available, I restarted the server, and also installed all linux updates, in case.

**Comment by xet7** [comment]
There are 2 options:

a) wait that your sandstorm server gets SSL cert, it takes some time

b) Login steps:
- modify /opt/sandstorm/sandstorm/sandstorm.conf to have http login url like http://your-server-ip-address 
- `sudo sandstorm stop`
- `sudo sandstorm start`
- `sudo sandstorm admin-token`
- and login to that http URL
- maybe set authentication again, download backups of grains, etc

**Comment by ocdtrekkie** [comment]
> These certificates expire weekly, so Sandstorm also checks every (approximately) 2 hours if the certificate it is using is on the last 3 days of its lifetime. If so, Sandstorm takes the same action as the install script: generate new key, generate certificate signing request, send that to Sandcats.io, store the response. 

https://docs.sandstorm.io/en/latest/administering/sandcats/

In theory, it should renew itself within a couple of hours.

**Comment by ocdtrekkie** [comment]
Well, I guess the log suggests it already renewed the cert, since it says that's valid through 5/26, sorry, that's not the issue.

**Comment by Geocali** [comment]
Ok, for some reason, my router inverted the IP addresses of 2 of my computers, one of which didn't have sandstorm installed.
Everything works fine, thanks for your amazing work and your help !!
