### ISSUE TITLE
When installing, subdomain and email questions loop

### ISSUE THREAD

**Issue by jpmendo** [sandstorm-io/sandstorm#3076]
Hello all. 
During installation, I provide a desired subdomain and my email address. The screen then displays:
* Registering your domain.
* ...
* Choose your desired Sandcats subdomain

The subdomain and email questions are in some sort of loop. 

[This closed thread](https://github.com/sandstorm-io/sandstorm/issues/2904) refers to the same issue. It was then suggested that the issue relates to an expired certificate.

**Comment by zenhack** [comment]
Yeah, it does look that's the problem:

```
[isd@rook ~]$ curl https://sandcats.io
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by ocdtrekkie** [comment]
The certificate expired on Sunday, June 3, 2018, 10:49 PM.

Just a handful of hours too late! It should get fixed soon.

**Comment by kentonv** [comment]
Sorry, fixed now. I need to set up some cron jobs I guess.

**Comment by jpmendo** [comment]
Thank you all for responding so fast! 
Looking forward to installing this for the first time.
