### ISSUE TITLE
Static sites have an unexpected redirect

### ISSUE THREAD

**Issue by tucker-m** [sandstorm-io/sandstorm#3083]
I was setting up a site using Hugo last night and noticed this. This same issue happened when using two Sandstorm apps to host a static HTML site, Hugo and Davros, which makes me think it's a problem with Sandstorm itself. Or maybe Oasis specifically.

When you go to a URL for a folder, and you leave off the slash at the end of the URL, you get a redirected to a page that doesn't exist. You can see it at the link below.

[https://v5ic9nqpn52pibivtxw6.oasis.sandstorm.io/**categories/test**](https://v5ic9nqpn52pibivtxw6.oasis.sandstorm.io/categories/test)

It wants to add a slash at the end of the URL, but when you go to that URL, it'll redirect you to [https://v5ic9nqpn52pibivtxw6.oasis.sandstorm.io/**categories/categories/test/**](https://v5ic9nqpn52pibivtxw6.oasis.sandstorm.io/categories/categories/test/), adding that extra /categories in there. The response's `Location` header says `categories/test/`. I think it's that relative location that's causing a problem.

There's no issue if you try going to [https://v5ic9nqpn52pibivtxw6.oasis.sandstorm.io/**categories/test/**](https://v5ic9nqpn52pibivtxw6.oasis.sandstorm.io/categories/test/) with a slash at the end. It's only if you leave off the trailing slash that it redirects you to a path that doesn't exist.

Here's the same site hosted on Github Pages: https://tucker-m.github.io/categories/test. If you go to that link, you'll get a 301 response, with the `Location` header being the absolute URL `http://tucker-m.github.io/categories/test/`, and you don't get a 404.

**Comment by kentonv** [comment]
Yikes, thanks for catching that. I believe I've fixed the code, but unfortunately I won't be able to push a release until July 8th, as I'll be out of town until then.

**Comment by kentonv** [comment]
I managed to push out a release today, so this is now fixed.

**Comment by tucker-m** [comment]
Wow, thank you!

**Comment by kentonv** [comment]
Unfortunately because I deployed this as a hotfix, and then at some point there was an incident requiring a restart, it got reverted. I will try to re-deploy the hotfix today then do a real release next weekend.
