### ISSUE TITLE
sandstorm not running

### ISSUE THREAD

**Issue by ITbody** [sandstorm-io/sandstorm#3086]
8.719997] type=1400 audit(1533586584.978:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/sbin/tcpdump" pid=1093 comm="apparmor_parser"

**Comment by ITbody** [comment]
anyone can please help i have installed sandstorm it was working fine but unfortunately it stoped, dont know whats the reason i reinstalled it again and agin but no success above is the logs related to this problem

**Comment by Michael-S** [comment]
apparmor is a security system for the Linux kernel.  I know it's used by Ubuntu Linux and many Linux distributions that derive from Ubuntu, I'm not sure how popular it is elsewhere.

I'm not sure why apparmor might be causing problems.  I have apparmor running on my Sandstorm server and sandstorm runs fine.  You may want to try disabling it to see if that fixes the problem.  systemctl stop apparmor.service   - then start Sandstorm again with systemctl restart sandstorm.service - then see if it works.

Good luck.

**Comment by ocdtrekkie** [comment]
I'm going to close this one since there was no followup on whether or not apparmor was causing the problem and/or if disabling it fixed it.
