### ISSUE TITLE
sandstrom: internal server error

### ISSUE THREAD

**Issue by ITbody** [sandstorm-io/sandstorm#3087]
Hellow everyone! In need help, I have installed sandstorm on at my home, the installation was successful but when i configure admin account from browser it gives error "internal server error" any help ?
my sandstorm.conf configuration
port=6080
bind_ip=0.0.0.0
listen on port 25
add entry to my iptables 6080, 25, 30025

**Comment by Michael-S** [comment]
Hello ITbody.  Sandstorm logs are usually in the directory /opt/sandstorm/var/log/ - so can you do something like "sudo cat /opt/sandstorm/var/log/sandstorm.log" and "sudo cat /opt/sandstorm/var/log/mongo.log" (or skip "sudo" and run the commands as root) to see if there are any useful errors there?

Good luck.

**Comment by ITbody** [comment]
code: 'EMESSAGE',
  response: '450',
  responseCode: 450,
  command: 'DATA' }
Token not found: engnawazish@gmail.com
E-mail delivery failure: Error: No such grain: rhce160120622
    at inMeteor (server/drivers/mail.js:162:25)
    at inMeteorInternal (imports/server/async-helpers.js:24:17)
    at Meteor.bindEnvironment.callback
(imports/server/async-helpers.js:12:3)
    at runWithEnvironment (packages/meteor.js:1356:24)
    at packages/meteor.js:1369:14
    at Promise (imports/server/async-helpers.js:22:5)
    at new Promise (<anonymous>)
    at inMeteor (imports/server/async-helpers.js:21:10)
    at tryDeliver (server/drivers/mail.js:154:22)
    at Promise.all.grainPublicIds.map.publicId
(server/drivers/mail.js:196:20)
    at Array.map (<anonymous>)
    at Promise.resolve.then (server/drivers/mail.js:150:45)
    at
/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Exception while invoking method 'createAndEmailTokenForUser' { Error:
Message failed: 450
    at SMTPConnection._formatError
(/programs/server/npm/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._actionSMTPStream
(/programs/server/npm/node_modules/smtp-connection/lib/smtp-connection.js:1358:30)
    at SMTPConnection.<anonymous>
(/programs/server/npm/node_modules/smtp-connection/lib/smtp-connection.js:854:18)
    at SMTPConnection._processResponse
(/programs/server/npm/node_modules/smtp-connection/lib/smtp-connection.js:669:16)
    at SMTPConnection._onData
(/programs/server/npm/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  code: 'EMESSAGE',
  response: '450',
  responseCode: 450,
  command: 'DATA' }

**Comment by ocdtrekkie** [comment]
"No such grain" is a very strange thing to see as part of sending an email out from the admin panel. What SMTP server are you using?

**Comment by ITbody** [comment]
i tried gmail, and hotmail

**Comment by ITbody** [comment]
This is my home PC that i want to configure for sandstorm, installed ubuntu
14.4 no other configuration like my own domain or mail server etc.

**Comment by ocdtrekkie** [comment]
As noted in the docs, Gmail really doesn't work for Sandstorm's SMTP, and in my own testing with another piece of software, Outlook (aka Hotmail) is even more restrictive: https://docs.sandstorm.io/en/latest/administering/email/

You probably want to look at a Mailgun or Sendgrid type thing. Both have pretty generous free tiers for as much mail as you're likely to generate with Sandstorm.

**Comment by ITbody** [comment]
you mean to create and account like mailgun or in sendgrid? and then try
with that? litterally I have no idea how to deal with sandstorm, that's why
please dont my if i ask a stupid question.

**Comment by ocdtrekkie** [comment]
Yeah, Mailgun and Sendgrid, unlike Gmail and Outlook, are intended for use with things like Sandstorm.

**Comment by ITbody** [comment]
Ok i'll try that will let you know if it works, thanks for having your time.
worm regards,

**Comment by Michael-S** [comment]
I don't know Sandstorm as well as ocedtrekkie - were you trying to set up Sandstorm to send email?  Or were you trying to use email-based login?  I mean logging in based on a code sent to an email address, not using a GMail or Github account to login?

**Comment by ITbody** [comment]
yes i was trying to logging in based on code sent to my gmail id.

**Comment by Michael-S** [comment]
No, that should work.  I have it working myself.  I only needed to set up non-Gmail to have Sandstorm applications like Roundcube work with my email.  Logging in by email using GMail works fine.

So something else must be wrong for you.  My /opt/sandstorm/sandstorm.conf file has this (except instead of 'foobar' it has the real domain name I selected).  Can you post what you have, except for hiding your own chosen domain (since you should not have to share it here)?

SERVER_USER=sandstorm
SANDCATS_BASE_DOMAIN=sandcats.io
PORT=80,6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://foobar.sandcats.io
WILDCARD_HOST=*.foobar.sandcats.io
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
HTTPS_PORT=443

**Comment by ocdtrekkie** [comment]
@Michael-S , the issue is that for you to get an email login email on your Gmail, your Sandstorm server has to have SMTP configured, and SMTP can't use Gmail, AFAIK. Which isn't to say there isn't other problems, but I would be highly doubtful using Gmail's SMTP settings in the admin panel would work.

**Comment by Michael-S** [comment]
@ocdtrekkie   thanks for the correction.  I checked my account settings, and you are right - I have my Sandstorm installation set to use my own mail server to send email instead of using GMail.  I'll amend my previous post.

**Comment by biennino** [comment]
@Michael-S Any updates on this? did you get it to work?  I'm having the same issue now.  also while trying to send a test email via the settings in sandstorm, I get

Error while trying to send test email: {"code":"ETIMEDOUT","command":"CONN"} [other-email-sending-error]

Please help anyone.

**Comment by Michael-S** [comment]
@biennino  - I had not remembered my settings correctly when I made some of my earlier comments on this issue.  I run my own mail server using the https://mailinabox.email software and I have no problems setting Sandstorm to send mail through that.   Sandstorm currently can't send email through GMail.  Are you trying to use GMail?

**Comment by ocdtrekkie** [comment]
This one looks resolved.
