### ISSUE TITLE
Unable to complete setup after fresh install

### ISSUE THREAD

**Issue by bonyboy** [sandstorm-io/sandstorm#3088]
I am having trouble completing the Sandstorm setup on a fresh install, but recovered Sandstorm subdomain. I have tried refreshing the token with no success.

[Sandstorm logs can be found here.](https://gist.github.com/bonyboy/67c25ee3685afc905cd9e416b09d3234)

[Screenshot of port forwarding I've setup.](https://imgur.com/a/rPmhH8H)

Is there other information I can provide to help diagnose this problem?

Thanks for your help!

**Comment by ocdtrekkie** [comment]
Is the Sandstorm service running? Are you able to get to the localhost URL for your Sandstorm server's web interface? It looks like install completed, so what are you trying to do that you can't?

**Comment by ocdtrekkie** [comment]
I'm going to close this for lack of response.
