### ISSUE TITLE
ALLOW_DEMO_ACCOUNTS=true but not work?

### ISSUE THREAD

**Issue by hoangsoft90** [sandstorm-io/sandstorm#3093]
i set ALLOW_DEMO_ACCOUNTS=true in sandstorm.conf, but when install app still login required.
i explode sandstorm code, i found userId=null in packages/accounts-base.js
``
userId() {
    // This function only works if called inside a method or a pubication.
    // Using any of the infomation from Meteor.user() in a method or
    // publish function will always use the value from when the function first
    // runs. This is likely not what the user expects. The way to make this work
    // in a method or publish function is to do Meteor.find(this.userId).observe
    // and recompute when the user record changes.
    const currentInvocation = DDP._CurrentMethodInvocation.get() || DDP._CurrentPublicationInvocation.get();

    if (!currentInvocation) throw new Error("Meteor.userId can only be invoked in method calls or publications.");
	console.log('userId=',currentInvocation.userId);  //=null
    return currentInvocation.userId;
  }
``
Please help?

**Comment by kentonv** [comment]
Hi Hoang,

I'm not sure what you are expecting here. `ALLOW_DEMO_ACCOUNTS=true` enables the demo behavior seen at https://demo.sandstorm.io . This is not what you want. The demo code is designed only to power demo.sandstorm.io, and it includes a signup flow designed specifically for Sandstorm Oasis.

Sorry, but there is no way to allow users to install apps without logging in.
