### ISSUE TITLE
app static asset not_found

### ISSUE THREAD

**Issue by hoangsoft90** [sandstorm-io/sandstorm#3094]
when i access `http://static.mydomaincom/igr8W9PwPRW9Hcw4H`
 it show `not found`
Explain me, please : how asset work? how i can fix it? thank a man

**Comment by ocdtrekkie** [comment]
I don't think there's enough information here to even guess what is happening here.

What are you expecting to see at this URL?

**Comment by kentonv** [comment]
This was probably a configuration problem. Given it was filed in 2018, we should probably just close.
