### ISSUE TITLE
vagrant-spk vm up - HTTPS URL throwing SSL error

### ISSUE THREAD

**Issue by ssivachidambaram** [sandstorm-io/sandstorm#3095]
Command used  `vagrant-spk vm up`

In `setup.sh` file, we have HTTPS URL in below command,
`wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc`

While running this, we're getting below error.

```
The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what
went wrong. Command failed with a non-zero exit status (1).
```

**Note** Already we tried config.vm.box_download_insecure = true. But still getting error.

**Comment by ocdtrekkie** [comment]
Interesting. The instructions are taken right from here: https://www.postgresql.org/download/linux/debian/ and the HTTPS cert for the key seems fine. What is above your error message?

**Comment by ssivachidambaram** [comment]
@ocdtrekkie Waiting for your help and if you need any more details i'll provide.

**Comment by ocdtrekkie** [comment]
@ssivachidambaram Sorry, I first looked at your reply during the GitHub incident: https://blog.github.com/2018-10-30-oct21-post-incident-analysis/ and was unable to reply. And then I got busy. :|

I have no idea why unzip would give you difficulty installing. I see a `default: dpkg-preconfigure: unable to re-open stdin: No such file or directory` which I don't understand there, and it looks like it fails just after processing triggers for man-db, which I am unsure why is the case. I sort of wonder if the failure could've been after installing unzip but before moving on to anything else that wrote to the output. It may be worth throwing a few `echo` statements in your script to help make sure we know which step it's failing on.

It may be worthwhile to spin up the VM with a setup script that doesn't have the failing commands, then use `vagrant-spk vm ssh` to enter the VM and see if you can run them manually, and what happens.

One other thing I noticed is that you're installing `python-software-properties`. This may give you issues in Debian Stretch (the current box vagrant-spk uses by default) if you're trying to grab that from the default repository, as it seems they don't have such a package, only a `python3-software-properties` exists. It looks like the older version existed in Debian Jessie.

**Comment by ssivachidambaram** [comment]
> Sorry, I first looked at your reply during the GitHub incident: https://blog.github.com/2018-10-30-oct21-post-incident-analysis/ and was unable to reply. And then I got busy. :|

No Problem.

> I have no idea why unzip would give you difficulty installing. I see a default: dpkg-preconfigure: unable to re-open stdin: No such file or directory which I don't understand there, and it looks like it fails just after processing triggers for man-db, which I am unsure why is the case. I sort of wonder if the failure could've been after installing unzip but before moving on to anything else that wrote to the output. It may be worth throwing a few echo statements in your script to help make sure we know which step it's failing on.

Problem in this line in the script.

`RESTYABOARD_VERSION=$(curl --silent https://api.github.com/repos/RestyaPlatform/board/releases | grep tag_name -m 1 | awk '{print $2}' | sed -e 's/[^v0-9.]//g')`

If i comment this line, its working perfectly.

> It may be worthwhile to spin up the VM with a setup script that doesn't have the failing commands, then use vagrant-spk vm ssh to enter the VM and see if you can run them manually, and what happens.

I have tried the above command after connected using `vagrant-spk vm ssh`, its working fine. But while run using `vagrant-spk vm up` its not working.

> One other thing I noticed is that you're installing python-software-properties. This may give you issues in Debian Stretch (the current box vagrant-spk uses by default) if you're trying to grab that from the default repository, as it seems they don't have such a package, only a python3-software-properties exists. It looks like the older version existed in Debian Jessie.

Thank you for the information. I have removed that code.

**Comment by ocdtrekkie** [comment]
I personally don't know enough about Linux scripting to troubleshoot why that line wouldn't work. (I certainly don't know my sed and awk.) I was kinda hoping someone else might jump in here too. :|

**Comment by ssivachidambaram** [comment]
@ocdtrekkie 

> I personally don't know enough about Linux scripting to troubleshoot why that line wouldn't work. (I certainly don't know my sed and awk.) I was kinda hoping someone else might jump in here too. :|

Thanks for your reply. Actually the mentioned sed & awk command is working fine in `vagrant-spk vm up` but its not working through `vagrant-spk vm up`. So i thought problem is not in the command but not sure why its not working. Is there any log is written to debug this command while running `vagrant-spk vm up`

**Comment by ssivachidambaram** [comment]
@ocdtrekkie 

I've fixed the issue by changing the command.

`RESTYABOARD_VERSION=$(curl --silent https://api.github.com/repos/RestyaPlatform/board/releases | grep tag_name -m 1 | awk '{print $2}' | sed -e 's/[^v0-9.]//g')`

=>

`RESTYABOARD_VERSION=$(curl --silent https://api.github.com/repos/RestyaPlatform/board/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')`
