### ISSUE TITLE
generate metadata for altered backup

### ISSUE THREAD

**Issue by crackcomm** [sandstorm-io/sandstorm#3096]
I have manually inserted some posts into my wordpress sqlite database, is there some way to regenerate metadata file to import it?

**Comment by ocdtrekkie** [comment]
I *think* you should be able to download a copy of your Sandstorm grain, replace whatever you need to in the zip file, and "restore" the grain from that zip file. That's if you're talking about the metadata from a Sandstorm grain backup. But that would create a "new" grain, so have new API keys and such for assigning to DNS.

If you're trying to use the import/export features in WordPress, you would best ask @JamborJan.

**Comment by crackcomm** [comment]
I digged into the log now I see
```
caution: filename not matched:  data/*
caution: filename not matched:  metadata
*** Uncaught exception ***
sandstorm/util.c++:678: failed: expected exitCode == 0; child process failed; name = unzip; exitCode = 11
stack: 4843a6 485b42 64ebf2
Unzip failure: remote exception: Premature EOF.
```

**Comment by ocdtrekkie** [comment]
@crackcomm Is it possible that when you re-zipped the files, it ended up inside a subfolder inside the zip file or something to that effect?

**Comment by crackcomm** [comment]
@ocdtrekkie that's exactly what was happening :)

**Comment by ocdtrekkie** [comment]
Definitely not the first time it's happened. ;) AFAIK the metadata has like the app and package IDs so Sandstorm knows what app the grain should be opened in, but it doesn't have anything like a hash of the data as far as I'm aware.

**Comment by crackcomm** [comment]
I think I'm gonna try Wordpress import/export anyways ^^ Thanks for your help @ocdtrekkie

**Comment by ocdtrekkie** [comment]
We resolved this back in 2018, and grain backup hacking isn't really a "feature", so I don't think there's an action item here for us. I'm going to close this.
