### ISSUE TITLE
"rebind" error.

### ISSUE THREAD

**Issue by ghost** [sandstorm-io/sandstorm#3097]
It occurs the error "'rebind' declared as a pointer to a reference of type 'sandstorm::SessionContext::Client &' using rebind = _Up*;" when I make it. how to solve it?

**Comment by zenhack** [comment]
Can you provide the full error message, as well as what platform you're
building on and what versions of the various tools sandstorm depends on
(e.g. clang version -- all the stuff listed in the building
instructions)?

Quoting Frxian Zhu (2018-10-29 04:51:47)

**Comment by ocdtrekkie** [comment]
Ghost account with no response, think this is safe to close.
