### ISSUE TITLE
DNS resolution unavailable on boot to Sandstorm server

### ISSUE THREAD

**Issue by zombiezen** [sandstorm-io/sandstorm#3099]
I migrated my self-hosted Sandstorm server to a new physical machine using the backup/restore mechanism described in the docs. The DNS host has remained the same (a Sandcats domain), while the physical address and details of networking have changed (new NIC and Debian 8 -> 9).

On my new machine, when it first starts up, Sandstorm will not allow Google logins. The observed effect is that when the browser is kicked back to the last "leg" of the OAuth authorization flow, Sandstorm just renders the same "Sign in" page.  In `/opt/sandstorm/var/sandstorm.log`, I'm seeing:

```
{"line":"424","file":"oauth.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with Google. getaddrinfo EBUSY",
"time":{"$date":1541366045734},"level":"warn"}
Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with Google. getaddrinfo EBUSY
    at getTokens (packages/google-oauth/google_server.js:105:7)
    at Object.getServiceData [as handleOauthRequest] (packages/google-oauth/google_server.js:80:58)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
    at middleware (packages/oauth.js:194:5)
    at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  message: 'Failed to complete OAuth handshake with Google. getaddrinfo EBUSY' }
```

as well as:

```
Couldn't send UDP sandcats ping { Error: getaddrinfo EAI_AGAIN
    at Object._errnoException (util.js:992:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'sandcats.io' }
```

The issue seems to resolve itself if I run `sudo sandstorm restart` after the machine steady-states, but this is inconvenient (having to SSH in from another machine).

Another clue in this puzzle: for bad Sandstorm sessions, I see this in the logs:

```
** Starting Sandstorm at: Sun Nov  4 13:13:51 2018
WARNING: Couldn't read host's /etc/resolv.conf, DNS may be broken
WARNING: Wanted to fall back to /etc/resolv.conf.host-initial, but it is unavailable.  Carrying on without DNS.
```

For good Sandstorm sessions, I see this:

```
** Restarting
WARNING: /etc/resolv.conf is unreachable from container, using backup from host
```

My suspicion is that the systemd service description is not listing all the proper dependencies (perhaps [systemd-resolved.service](https://manpages.debian.org/stretch/systemd/systemd-resolved.service.8.en.html)?).

**Comment by zombiezen** [comment]
In digging a little further into systemd docs, I believe my suspicion to be correct. Sandstorm's current systemd unit depends on `network.target`:

https://github.com/sandstorm-io/sandstorm/blob/eb2832d84143dd5800aa674f7206abe690031511/install.sh#L1529-L1532

According to [Running Services After the Network is up](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/), I believe this should be `network-online.target`.

I'll test this on my machine and if results are positive, I will send a PR.

**Comment by xet7** [comment]
Try:

1. Get admin-token URL:
```
sudo sandstorm admin-token
```
2. Use admin-token URL to login

3. Reconfigure OAuth

**Comment by zombiezen** [comment]
@xet7 I originally thought it to be an OAuth configuration issue, but that is not the case. Restarting the Sandstorm server so that it can reach Google auth servers does fix the issue without a change in configuration.
