### ISSUE TITLE
Using the auto install curl | bash does not generate trusted ssl certificate

### ISSUE THREAD

**Issue by InDaPond** [sandstorm-io/sandstorm#3109]
First of all, this is probably just a mistake on my own.
The way I read 

> The installer will offer you free dynamic DNS and valid HTTPS via sandcats.io, a service maintained by the Sandstorm development team.

from the install guide, I figured after using the auto-install, firefox/chrome will establish the https-connection which is provided at the end of the successful installation for further configuration.

When I tried this though, both browsers stated that the cert-authority cannot be trusted, and therefore traffic can be intercepted and read by others.

Since I am not well aware of the implications, I thought I rather ask here.
I wanted to setup this server for my own team, but for now I uninstalled it right away - I am way too scared that there might be a security breach through that server setup.

**Comment by xet7** [comment]
You should wait that certificate is issued and installed, it takes some time, it is not instant.

Sandstorm is safe to use.

**Comment by InDaPond** [comment]
Oh, so something will change if I wait?

> Because MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT : certificate cannot be trusted because it it self signed by the authority  (rougly translated into english by me)

looked like something had already been done, but is not sufficient anymore to pass the security check

**Comment by xet7** [comment]
Yes, sometime it will change to valid cert, usually within 24h or more ( just guessing ).

**Comment by xet7** [comment]
Change should happen automatically.

**Comment by ocdtrekkie** [comment]
@InDaPond Did you select Sandcats as part of the installer and configure a yournamehere.sandcats.io address for Sandstorm? What URL are you seeing the self-signed at?

**Comment by InDaPond** [comment]
I did, I think it might be a problem with port-forwarding of my router.

**Comment by ocdtrekkie** [comment]
Going to close this for lack of status update.
