### ISSUE TITLE
sandstorm wild card issue

### ISSUE THREAD

**Issue by ITbody** [sandstorm-io/sandstorm#3112]

**Comment by ITbody** [comment]
ki

WARNING: This server seems to have its WILDCARD_HOST misconfigured. Until you fix it, you will not be able to use any apps. You can read more info in the Sandstorm docs and in your browser's Javascript console. You'll need to adjust DNS, SSL/TLS certificates, or edit the sandstorm.conf file. If you see no information in the JS console, or wish to test if you have fixed the problem, reload this page to re-run the test. If you're still having problems, please file an issue.
Admin System log
System log
Download full log
...** Starting Sandstorm at: Tue Jan  1 14:25:59 2019
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 8
child process started successfully, parent exiting
Successfully added user: {
	"user" : "sandstorm",
	"roles" : [
		"readWriteAnyDatabase",
		"userAdminAnyDatabase",
		"dbAdminAnyDatabase"
	]
}
** Back-end and Mongo started; now starting front-end...
** Starting Gateway...
Tue, 01 Jan 2019 14:26:08 GMT body-parser deprecated undefined extended: provide extended option at app/app.js:5506:39
Migrations already applied: 0/39
Applying migration 1
Applied migration 1
Applying migration 2
Applied migration 2
Applying migration 3
Applied migration 3
Applying migration 4
Applied migration 4
Applying migration 5
Applied migration 5
Applying migration 6
Applied migration 6
Applying migration 7
Applied migration 7
Applying migration 8
Applied migration 8
Applying migration 9
Applied migration 9
Applying migration 10
Applied migration 10
Applying migration 11
Applied migration 11
Applying migration 12
Applied migration 12
Applying migration 13
Applied migration 13
Applying migration 14
Applied migration 14
Applying migration 15
Applied migration 15
Applying migration 16
Applied migration 16
Applying migration 17
Applied migration 17
Applying migration 18
Applied migration 18
Applying migration 19
Applied migration 19
Applying migration 20
Applied migration 20
Applying migration 21
Applied migration 21
Applying migration 22
Applied migration 22
Applying migration 23
Applied migration 23
Applying migration 24
Applied migration 24
Applying migration 25
Applied migration 25
Applying migration 26
Applied migration 26
Applying migration 27
Applied migration 27
Applying migration 28
Applied migration 28
Applying migration 29
Applied migration 29
Applying migration 30
Applied migration 30
Applying migration 31
Applied migration 31
Applying migration 32
Applied migration 32
Applying migration 33
Applied migration 33
Applying migration 34
Applied migration 34
Applying migration 35
Applied migration 35
Applying migration 36
** Migrating to new identity model! **
see: https://sandstorm.io/news/2017-05-08-refactoring-identities
tagging accounts...
tagging credentials...
building identity map...
migrating users...
migrating ApiTokens...
migrating membrane requirements...
migrating identity capabilities...
migrating contacts...
migrating notifications...
migrating desktop notifications...
migrating subscriptions...
Applied migration 36
Applying migration 37
Applied migration 37
Applying migration 38
Applied migration 38
Applying migration 39
Applied migration 39
Running new server startup function 1
Running new server startup function 1
Downloading app: https://app-index.sandstorm.io/packages/e813a833d983fbc38d87da62ea461fa7
Downloading app: https://app-index.sandstorm.io/packages/4304ec4879f67496dd269283aa24ea21
Downloading app: https://app-index.sandstorm.io/packages/db68360103a2f7ea2166c52799703ab4
Downloading app: https://app-index.sandstorm.io/packages/7e0fc8fce431c4646c0133fa18cae535
Downloading app: https://app-index.sandstorm.io/packages/5198a2ec87bcc4b29e787b77079ba590
App ready: 7e0fc8fce431c4646c0133fa18cae535
fetching keybase 6B7486EA873576FD72845C5E50E4D7384B1B4D65
Admin token deleted.
App ready: e813a833d983fbc38d87da62ea461fa7
fetching keybase 211BF6A1E4CD72C957B705FA8EE8B9250C803854
App ready: 4304ec4879f67496dd269283aa24ea21
fetching keybase 880223DF25AA25A9433AF0FB40678458440DDCF1
App ready: 5198a2ec87bcc4b29e787b77079ba590
fetching keybase 5C5580353165D42FD89E1371A9FF0AD7DEE40258
App ready: db68360103a2f7ea2166c52799703ab4
fetching keybase D95FF05115356E73D9AAEBA834952FA52E8A5E3A
Downloading app: https://app-index.sandstorm.io/packages/3a60f95351fb52f9c5c52d24b7ba7248
App ready: 3a60f95351fb52f9c5c52d24b7ba7248
fetching keybase 5C95C99E6952707D22ED65BB18069B0BFD4F67D2
fetching keybase 5C95C99E6952707D22ED65BB18069B0BFD4F67D2
** Shutting down due to signal
** Restarting
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 130
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
** Starting Gateway...
Tue, 01 Jan 2019 14:38:17 GMT body-parser deprecated undefined extended: provide extended option at app/app.js:5506:39
Migrations already applied: 39/39
Admin token deleted.
Unhandled exception in Promise:  { Error: remote exception: grain is not running cppFile: '(remote)', line: 0, kjType: 'disconnected' }
Unhandled exception in Promise:  { Error: remote exception: grain is not running cppFile: '(remote)', line: 0, kjType: 'disconnected' }
Unhandled exception in Promise:  { Error: remote exception: grain is not running cppFile: '(remote)', line: 0, kjType: 'disconnected' }
Unhandled exception in Promise:  { Error: remote exception: grain is not running cppFile: '(remote)', line: 0, kjType: 'disconnected' }
Unhandled exception in Promise:  { Error: remote exception: grain is not running cppFile: '(remote)', line: 0, kjType: 'disconnected' }

**Comment by ITbody** [comment]
any help why this is happening..

**Comment by ocdtrekkie** [comment]
We'd need to see what your Sandstorm config file looks like, probably.

**Comment by ocdtrekkie** [comment]
That looks correct to me. Since you aren't using Sandcats, you'd be depending on your own DNS setup somewhere to handle the wildcard? If your DNS is set up correctly, and you visit `http://foo.test1.mydomain.com:6080`, you should see something like `No such grain for public ID: foo [404]`.

Issues setting up DNS are relatively common and depending what you're doing, there's probably some useful tips in previously opened issues.

**Comment by ITbody** [comment]
My primary domain is my domain.com the server where I want to deploy sandstorm is subdomain like test1.mydomain.com 
The question where I need to check my dns setup I have mx and A record on ISP side as I do not have my own domain setup. My domain with http://test1.mydomain.com is working fine but when I figure it out with sandstorm it gives dns issue I mean wild card issue.
Nawazish Ali RHCE

**Comment by ocdtrekkie** [comment]
Your wildcard record would need to be added wherever your MX and A records are.

**Comment by ITbody** [comment]
You mean I have to add *.test1.mydomain.com:6080 on ISP side right?

**Comment by ocdtrekkie** [comment]
Yeah, though without the port number, that's not part of the domain name.

*.test1.mydomain.com needs to point at the same destination as test1.mydomain.com does.

**Comment by ITbody** [comment]
Ok thanks let me fix this and will then update about the peoceedings.

**Comment by ocdtrekkie** [comment]
Closing since there's been not update in a year.
