### ISSUE TITLE
Wekan does not allow for moving cards between and within lists 

### ISSUE THREAD

**Issue by pantraining** [sandstorm-io/sandstorm#3113]
With the last update of the Wekan API, it is impossible to move any cards between lists, but also to move them up or down manually (only top or bottom via menu is possible), drag-and-drop does not work at all.
Thanks for any solution, as it limits the usability of the whole Wekan instance...

**Comment by xet7** [comment]
@pantraining 

Please continue at https://github.com/wekan/wekan/issues/2143

and close this, because this is bug in Wekan. Not in Sandstorm.
