### ISSUE TITLE
Sandstorm Email Configuration not working

### ISSUE THREAD

**Issue by archiecodes** [sandstorm-io/sandstorm#3114]
I am trying to use this email configuration:
![image](https://user-images.githubusercontent.com/42045366/52139399-f535fb80-2647-11e9-8bc7-94cdba980eca.png)

The "Sandstorm Server's own email address" is system@SANDSTORMHOSTNAME.TLD

I am trying to send the test email to archie@serveradmin.xyz, and I get the error:
```
Error while trying to send test email: {"code":"EMESSAGE","response":"450","responseCode":450,"command":"DATA"} [other-email-sending-error]
```

I am not running anything other than Sandstorm (with roundcube) on the server.

**Comment by ocdtrekkie** [comment]
Outgoing email requires an external SMTP server of some kind: https://docs.sandstorm.io/en/latest/administering/email/

**Comment by archiebaer** [comment]
Can't I use the built in one?

**Comment by ocdtrekkie** [comment]
Doesn't look like it, according to the documentation, it's for delivering inbound mail to grains.

**Comment by archiebaer** [comment]
But I can send emails from roundcube.

**Comment by archiebaer** [comment]
Doesn't that use an SMTP server?

**Comment by archiebaer** [comment]
Oh, wait, I can't. That explains why.

**Comment by archiebaer** [comment]
Wait a minute, what's all this about then: `First, a quick rundown of how email works in sandstorm. Sandstorm is running an SMTP server on port 30025 that will accept email ...`. Doesn't seem to work.

**Comment by archiebaer** [comment]
I suppose I could do without email, I just didn't want to pay for a Gluu server or be at the mercy of google or something. It works good for temp email addresses though. Why can't sandstorm handle authentication itself? Is there any app I can install that will do all the LDAP stuff on the same server?

**Comment by xet7** [comment]
@archiebaer 

Tutanota seems to have only their webmail client free.

Protonmail paid accounts can have bridge https://protonmail.com/bridge/ that could be installed to send/receive email, but I have not tested it yet.

**Comment by xet7** [comment]
@archiebaer 

You can install http://mailslurper.com to your server and just send email to yourself on same server, and read email on web interface, if that is required for some apps.

**Comment by Michael-S** [comment]
I use Sandstorm for my music (Groovebasin), file (Davros), git (Gogs), spreadsheets (Ethercalc), and documents (Etherpad) hosting.  But for email I use https://mailinabox.email separately with my own rented server and domain.  They package Roundcube by default but it works with POP3 and IMAP so I set up my accounts in Thunderbird.

**Comment by ocdtrekkie** [comment]
@archiebaer https://docs.sandstorm.io/en/latest/administering/faq/#why-do-you-support-only-google-github-and-passwordless-email-for-login

There are a couple SAML services you could set up to handle authentication for Sandstorm: https://docs.sandstorm.io/en/latest/administering/for-work/#authentication-provider-saml-20

**Comment by archiebaer** [comment]
Is there anything in the App Store that could authenticate users (LDAP/SAML/OpenID)? I really would prefer not to have to rent a 2nd server, or install something else on the server and complicating it even more (I already have NGINX running as a reverse proxy).

**Comment by xet7** [comment]
Well, you could google search for some identity provider server. You could for example try does this work:
https://github.com/amdonov/lite-idp

But I have not tried it. YMMV.

**Comment by archiebaer** [comment]
Not a sandstorm app.

**Comment by ocdtrekkie** [comment]
There is nothing like that available within the Sandstorm App Market.
