### ISSUE TITLE
Invalid Subtext

### ISSUE THREAD

**Issue by archiebaer** [sandstorm-io/sandstorm#3115]
![image](https://user-images.githubusercontent.com/42045366/52143669-fbca7000-2653-11e9-82c7-d83b58248342.png)

It seems someone made a typo there. (Admin/Personalization)

**Comment by ocdtrekkie** [comment]
Ooh, good catch. I can submit a PR for it. In case you're curious, it should say "The name of this server, as used when communicating with users."

**Comment by archiebaer** [comment]
Okay. Should I close the issue?

**Comment by ocdtrekkie** [comment]
Up to you. Whenever Kenton merges the fix, it will automatically close this issue.

**Comment by archiebaer** [comment]
And in 20 minutes. Oh, 1 minute left.

**Comment by archiebaer** [comment]
It should've closed by now. Reload?

**Comment by archiebaer** [comment]
Wait, ` ocdtrekkie referenced a pull request that will close this issue 21 minutes ago ` ?

**Comment by archiebaer** [comment]
Oh, I misunderstood the wording.
