### ISSUE TITLE
WILDCARD_HOST misconfigured: Can't config with internal IP !?

### ISSUE THREAD

**Issue by Michael2222** [sandstorm-io/sandstorm#3120]
Hello,
I have installes a new ubuntu 18.04 server with sandbox in my local network. The machine has the IP 192.168.178.173, but I can't run correct with this config file:

```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://192.168.178.173:6080
WILDCARD_HOST=*.192.168.178.173:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
```
I get allways the warning:
`WARNING: This server seems to have its WILDCARD_HOST misconfigured.`

What am I doing wrong?
Thank you!

**Comment by ocdtrekkie** [comment]
It's impossible to do wildcard DNS with an IP address, you need a domain of some sort. I've seen people use xip.io as well.

**Comment by Michael2222** [comment]
OK, now I have tried with my DynDNS:
1. version:
```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://example.dyndns.org:6080
WILDCARD_HOST=*.example.dyndns.org:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
```
==> WARNING: This server seems to have its WILDCARD_HOST misconfigured.

2. version:
```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://example.dyndns.org:6080
WILDCARD_HOST=*.local.sandstorm.io:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
```

==> WARNING: This server seems to have its WILDCARD_HOST misconfigured.

Both version are not working.
Have you an hint?

**Comment by kpreid** [comment]
Have you confirmed that your actual dyndns.org domain is configured for wildcards? You can test it by looking up `somerandomstringhere.example.dyndns.org` (with your actual subdomain substituted, of course) using your favorite DNS tool and checking that the response is an A record with your IP address.

I've never used DynDNS but a web search suggests that you have to configure a wildcard rather than it being available by default.

**Comment by Michael2222** [comment]
Hello,
now I have logged in in dyndns and active the Wildcard checkbox.
Then I have check this with https://mxtoolbox.com and yes, he returned an A Record, but the result from sandstorm is the same:
==> WARNING: This server seems to have its WILDCARD_HOST misconfigured.

**Comment by ocdtrekkie** [comment]
Your first example should definitely be the way. Local.sandstorm.io only returns 127.0.0.1

**Comment by ocdtrekkie** [comment]
What if you navigate to foo.example.dyndns.org:6080 in your browser? If your DNS is working correctly, Sandstorm should return something like "No such grain".

**Comment by Michael2222** [comment]
If I use foo.example.dyndns.org:6080 I get this output:

```
ERROR: The server threw an exception. Details:

(remote):0: failed: remote exception: remote exception: Error: Host "sandstorm-www.foo.example.dyndns.org" must have exactly one TXT record.
    at QueryReqWrap.Dns.resolveTxt [as callback] (server/gateway-router.js:556:20)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:240:10)
stack: 6b8dc0 600410 5f1c60 71fa70 7225f0
```
Additional, I have also checked again with www.ultratools.com:

```
foo.example.dyndns.org results:
ns4.dyndns.org.
A 
IN	example.dyndns.org.	60
IN	192.71.221.18	60 (I have change the IP)
TXT 86 ms 
IN	example.dyndns.org.	60
LOC 83 ms 
IN	example.dyndns.org.	60
SOA 81 ms 
IN	example.dyndns.org.	60
NS 81 ms 
IN	example.dyndns.org.	60
SRV 81 ms 
IN	example.dyndns.org.	60
SPF 82 ms 
IN	example.dyndns.org.	60
CNAME 81 ms 
IN	example.dyndns.org.	60
MX 82 ms 
IN	example.dyndns.org.	60
AAAA 82 ms 
IN	example.dyndns.org.	60

```

**Comment by ocdtrekkie** [comment]
Well, your wildcard entry is definitely getting you to the Sandstorm server, but it's treating it like a static publishing URL, not a grain URL. I'm trying to remember what causes that. (There's a LOT of wildcard-troubleshooting issues in this GitHub repo to sift through.)

**Comment by ocdtrekkie** [comment]
I don't think you should have a TXT record at all at your Sandstorm Base URL. Do you have one there, and can you remove it?

**Comment by ocdtrekkie** [comment]
I am going to close this one for non-response.
