### ISSUE TITLE
Getting Errer when trying to install Sandstorm

### ISSUE THREAD

**Issue by seyo-IV** [sandstorm-io/sandstorm#3122]
Im getting the following Error when i try to execute the snippet form the Docker installation section

This script is trying to install to /opt/sandstorm.

You seem to already have a /opt/sandstorm directory with a Sandstorm
installation inside. You should either:

1. Reconfigure that Sandstorm install using its configuration file --
/opt/sandstorm/sandstorm.conf -- or the admin interface. See docs at:
https://docs.sandstorm.io/en/latest/administering/

2. Uninstall Sandstorm before attempting to perform a new install. Even if you
created a sandcats.io hostname, it is safe to uninstall so long as you do not
need the data in your Sandstorm install. When you re-install Sandstorm, you can
follow a process to use the old hostname with the new install. See uninstall
docs at:
https://docs.sandstorm.io/en/latest/install/#uninstall

3. Use a different target directory for the new Sandstorm install. Try running
install.sh with the -d option.

4. Retain your data, but restore your Sandstorm code and configuration to a
fresh copy. To do that, keep a backup  of /opt/sandstorm/var and then do a
fresh install; stop the Sandstorm service, and restore your backup of
/opt/sandstorm/var. You may need to adjust permissions after doing that.
*** INSTALLATION FAILED ***

Please try one of the above. Contact
https://groups.google.com/d/forum/sandstorm-dev for further help.

You can report bugs at: http://github.com/sandstorm-io/sandstorm

**Comment by ocdtrekkie** [comment]
Did you try installing Sandstorm before, and then have to try again? Presumably, if you have no data you are trying to preserve, you just need to delete /opt/sandstorm, which contains your existing Sandstorm install.

**Comment by seyo-IV** [comment]
actualy a fresh install. i can try deleting it and reinstalling

**Comment by ocdtrekkie** [comment]
If it's a fresh install should be no harm in deleting it and trying again.

**Comment by seyo-IV** [comment]
im getting the error when i run this
`docker run --privileged -i -t -v sandstorm-data-volume:/opt/sandstorm --name sandstorm-build buildpack-deps bash -c 'useradd --system --user-group sandstorm ; curl https://install.sandstorm.io/ > install.sh && REPORT=no bash install.sh -d -e'`
