### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by seyo-IV** [sandstorm-io/sandstorm#3123]
I have successfully installed sandstorm and have it running behind nginx reverse proxy. My problem is i cant see the icons of the apps. My nginx configuration is like in the example configuration.
![icons](https://user-images.githubusercontent.com/32060944/52701385-66e04480-2f7a-11e9-8893-1c437d5bdcaa.PNG)

**Comment by ocdtrekkie** [comment]
Usually this suggests you have an issue with your DNS wildcard entry. #2986 is similar.

The icons in question are served from a subdomain, so if there's an issue with either your HTTPS certificate or your wildcard DNS entry, the icons may not load. You can try with foo.mysandstormdomain.com in your browser, and you should get no certificate errors, but a "No such grain" error, if all of your wildcard stuff is correct.

**Comment by seyo-IV** [comment]
That is how my sandstosrm.conf look like. Im not using the sandstorm domain, im using my own.

`SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://server.seyo-iv.space
WILDCARD_HOST=*.server.seyo-iv.space
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
`

Il try to reinstall and use a sandcats domain instead.

**Comment by seyo-IV** [comment]
Ok i did reinstall it. Now im running under the sandcats subdomain and it works. Can live with that.

**Comment by kentonv** [comment]
Sorry that this is confusing. It looks like the problem is that you didn't configure your DNS to accept `*.server.seyo-iv.space`. E.g. if I try to do a ping I get this:

    $ ping foo.server.seyo-iv.space
    ping: foo.server.seyo-iv.space: Name or service not known

If you try to set this up again in the future, make sure to add `*.server.seyo-iv.space` in your DNS config. (The `*.` is important.)
