### ISSUE TITLE
E_PKG_STALE error during install

### ISSUE THREAD

**Issue by SethSanchez** [sandstorm-io/sandstorm#3127]
I'm not sure what else may be wrong. Server was in UTC by default, but changing to CST (-5) didn't help either.

Server is Ubuntu 18.04 LTS. Bash = `GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)`.

Pulling the install.sh file from github directly doesn't make a difference.

```
Config written to /opt/sandstorm/sandstorm.conf.
Finding latest build for dev channel...
Downloading: https://dl.sandstorm.io/sandstorm-244.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 52.1M  100 52.1M    0     0   151M      0 --:--:-- --:--:-- --:--:--  151M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0   7948      0 --:--:-- --:--:-- --:--:--  7750
GPG signature is valid.
*** INSTALLATION FAILED ***

The downloaded package seems to be more than a month old. Please verify that
your computer's clock is correct and try again. It could also be that an
attacker is trying to trick you into installing an old version. Please contact
security@sandstorm.io if the problem persists.

Hmm, installation failed. Would it be OK to send an anonymous error report to the sandstorm.io team so we know something is wrong?
It would only contain this error code: E_PKG_STALE [yes] yes
Sending problem report...
... problem reported successfully. Your installation did not succeed.

You can report bugs at: http://github.com/sandstorm-io/sandstorm
root@sandstorm:~# date
Wed Mar 13 23:33:44 CDT 2019
```

**Comment by ocdtrekkie** [comment]
See https://github.com/sandstorm-io/sandstorm/issues/3126 for details. E_PKG_STALE simply means the release is more than a month old. As the case is, there has not been a new release in over a month, so this is not wholly unexpected.

You can make a modification to install.sh similar to the one here: https://github.com/sandstorm-io/sandstorm/pull/3014/files and the script will run.

**Comment by SethSanchez** [comment]
Ah, that's helpful, thank you!

Glad to see there's a PR going to fixing that already.

**Comment by dckc** [comment]
I just got the "more than a month old" error; I'm trying to set up a server to transfer from oasis. I see the latest release is Nov 23.
