### ISSUE TITLE
Contact Otter - How to Disable Google Analytics?

### ISSUE THREAD

**Issue by avidbrandy** [sandstorm-io/sandstorm#3128]
Hello,

I'm an amateur developer, and recently set up Sandstorm on a local server to learn and create a work environment. I noticed that Google Analytics was trying to run, which was confusing because it seems against everything I've read about Sandstorm. 

Isolating it, I identified that Contact Otter is bringing several scripts with it including Google Analytics. Trying to find more information on the issue, the only thing I could dig up was [this issue from 2 years ago,](https://github.com/phildini/logtacts/issues/64), in which the developer acknowledges this as inappropriate and says it will be removed.

Is there a way to disable this through Sandstorm, or is it just the cost of using Contact Otter? Any nudge or info on options I can pursue is greatly appreciated.

**Comment by kpreid** [comment]
The facility to block this in Sandstorm does not yet exist. See for example #2906 and https://docs.sandstorm.io/en/latest/using/security-practices/#true-confinement.

You could try modifying Sandstorm's served Content-Security-Policy to restrict client network access to the Sandstorm server only. I don't know exactly where to do that or what else would break. https://github.com/sandstorm-io/sandstorm/blob/cddbe90f6edd23ff2c68665dc7eaa0661d6c5ec3/src/sandstorm/web-session-bridge.c%2B%2B#L1259 looks like the code that generates the header, so you'd want to change it to always emit a CSP header but add the `frame-ancestors` part when it applies.

(I notice there doesn't seem to be an issue filed for "close the remaining confinement holes". Perhaps there should be. Anyone know what exactly should be listed under that?)

**Comment by ocdtrekkie** [comment]
I mean, the easiest solution would not be to modify Sandstorm's sandboxing, but to fix Contact Otter. Removing the GA script from a fork would be trivial, and then you'd have to re-key the app since you don't have @philidini's key. Forking has no real downside since he isn't supporting the app and isn't going to publish an update for it.

**Comment by xet7** [comment]
Thanks for info! I will fork Contact Otter to SandstormPorts https://github.com/sandstormports and try to make required changes.

**Comment by xet7** [comment]
I did fork Contact Otter to https://github.com/sandstormports/contactotter

**Comment by avidbrandy** [comment]
You're awesome, thank you! I appreciate the responses. I'm an amateur, and setting up Sandstorm locally has been a fun brutal introduction to many basic concepts for me. Looking forward to learning futher.

**Comment by ocdtrekkie** [comment]
I think I am going to go ahead and close this for now, as an issue with Contact Otter should be (and is) reported via the app's own repo, here: https://github.com/phildini/logtacts/issues/64

And of course, #2906 would be the Sandstorm platform representation of this issue. Hopefully once that is addressed, Sandstorm apps will be protected from Google Analytics even if Google Analytics was included in the app package.
