### ISSUE TITLE
Wekan boards not loading after latest upgrade

### ISSUE THREAD

**Issue by hiromipaw** [sandstorm-io/sandstorm#3132]
Since latest Wekan upgrade today I am not able to load some of our boards. The browser console is full of meteor errors such as the one copied below.

Some boards seems to load fine after a long time in the loading state. Is there something we should do on our side? Any log we could share so that it could be easier to troubleshoot this?

Shall we get in touch with Wekan instead?

Thanks.

``
Exception in template helper: limitToShowCardsCount@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:323:304158
f._wrapCatchingExceptions/<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:17173
O/</<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:231:4785
e._withTemplateInstanceFunc@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:37698
O/<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:231:4728
p.call@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:123:1926
class/<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:323:276337
f.If/</<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:27982
n/</<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:19013
e._withTemplateInstanceFunc@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:37698
n/<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:18956
f._withCurrentView@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:23097
n@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:18914
e.Computation.prototype._compute@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:2301
e.Computation@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:1263
e.autorun@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:4233
f.View.prototype.autorun@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:19093
f.If/<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:27930
n@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:20384
e.nonreactive@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:4414
f._fireCallbacks/<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:20299
f._withCurrentView@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:23097
f._fireCallbacks@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:20267
f._createView@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:20568
f._expandView@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:21518
visitObject@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:21907
visit@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:57:1139
visitArray@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:57:1946
visit@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:57:1101
visitAttribute@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:57:3051
visitAttribute@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:22259
visitAttributes@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:57:2900
visitAttributes@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:22096
f._expandAttributes@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:22533
d@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:16150
n/</<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:19013
e._withTemplateInstanceFunc@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:37698
n/<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:18956
f._withCurrentView@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:23097
n@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:18914
e.Computation.prototype._compute@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:2301
e.Computation@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:1263
e.autorun@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:4233
f.View.prototype.autorun@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:19093
t@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:16312
e@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:15106
f._materializeDOM@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:14811
f._materializeDOM@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:14847
t@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:21171
e.nonreactive@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:4414
t@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:21138
n/</<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:19013
e._withTemplateInstanceFunc@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:37698
n/<@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:18956
f._withCurrentView@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:23097
n@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:59:18914
e.Computation.prototype._compute@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:2301
e.Computation.prototype._recompute@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:2542
e._runFlush@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:21:3718
e@https://ui-255a51e6db8a3b21f55b2b280b796d1f.storm.torproject.org/dde565b9b359dceb4eaad44288690fbdbbb476c2.js?meteor_js_resource=true:1:2469
``

**Comment by ocdtrekkie** [comment]
cc: @xet7 relating to https://github.com/wekan/wekan/issues/2220

If you click "All boards", and then select the board in question, it should load fine. Basically, Wekan for Sandstorm used to have some custom logic to show one board and not show any of the other boards within Wekan, and that was removed not in the latest Sandstorm package, but the one before.

xet7 says the bug loading the board has been there a while, but revealing the All Boards option gives you a workaround.

**Comment by hiromipaw** [comment]
Thanks!!

**Comment by ocdtrekkie** [comment]
I'm closing this because it's a Wekan issue, not a Sandstorm issue, but I believe this is actually fixed in newer versions of the Wekan SPK.
