### ISSUE TITLE
Change email of the Sandcats dyndns record maintainer

### ISSUE THREAD

**Issue by SteamWind** [sandstorm-io/sandstorm#3134]
Hello,
I would like to know if it is possible to change the email associated to my sandcats dns record or if it is possible to revoke the dns record because I don't need it...
Thank you.

**Comment by ocdtrekkie** [comment]
The terms only provide for deleting the entry by emailing support@sandstorm.io and then presumably you could recreate it with a new email address, presumably if you did need it with a different email address.

**Comment by SteamWind** [comment]
Thank you, I have sent my request to this email address.
I didn't found this case in the documentation. Maybe it could be described in the [FAQ](https://docs.sandstorm.io/en/latest/administering/faq) or the [Free sandcats.io HTTPS](https://docs.sandstorm.io/en/latest/administering/sandcats-https/).
