### ISSUE TITLE
What function to unpack spk file in sandstorm ui?

### ISSUE THREAD

**Issue by clickgumshoe** [sandstorm-io/sandstorm#3138]
I will custom sandstorm code & need to find unpack spk function. My purpose is: copy some file that no ship with apk file by default. So i can add my code after unpack job complete, to copy my file in /opt/sandstorm/var/sandstorm/apps/<packageId>/

Thanks a lot.

**Comment by ocdtrekkie** [comment]
Duplicate of #3139
