### ISSUE TITLE
Adding a subdomain to sandstorm config

### ISSUE THREAD

**Issue by seyo-IV** [sandstorm-io/sandstorm#3142]
is there a way to add a subdomain pointing to a grain? If so, how do i do that?
Or is there a way giving a grain another name?

**Comment by seyo-IV** [comment]
okay i found a workarround for my problem. I use a fullscreen iframe on my homepage in a html file.

**Comment by ocdtrekkie** [comment]
That's not a bad way to do it. I've used my hosting's redirecting ability too to a share URL.

**Comment by seyo-IV** [comment]
The problem when i redirect from my domain to sandcats.io i get a ssl error, i assume you use your own domain for hosting sandstorm.
