### ISSUE TITLE
 licensing server is unable to connect with my wp site

### ISSUE THREAD

**Issue by seyo-IV** [sandstorm-io/sandstorm#3145]
I have a plugin installed for wp. Somehow I can't register the product because my site is unable to connect to the licensing server. Is there a reason for blocking it? Not sure if its a sandstorm or wp related error.

**Comment by xet7** [comment]
Sandstorm WordPress issues are here:
https://github.com/sandstormports/wordpress-sandstorm/issues

Please add issue to there instead and mention what plugin it is. And close this issue here.

**Comment by seyo-IV** [comment]
Okay

**Comment by ocdtrekkie** [comment]
As I noted in https://github.com/sandstormports/wordpress-sandstorm/issues/41 the ultimate issue is that Sandstorm is designed to isolate apps and prevent them from calling home or leaking information. Ideally you'd be able to open a powerbox and grant your WordPress grain access to reach out and talk to a server but that doesn't work presently.

If there's a way to handle some sort of "offline activation" for this license, that might be a method to pursue.
