### ISSUE TITLE
Error: Certificate Renewal 504

### ISSUE THREAD

**Issue by SwapFaceL** [sandstorm-io/sandstorm#3149]
Hi,

I've installed sandstorm via the install script on ubuntu server 18.04 LTS. Everything was working as expected for months already.

Suddenly I noticed today that the certificate for XXX.sandcats.io was outdated. I was a bit surprised as I expect it to renew automatically. As it seems this did not work anymore.
After several attempts to fix it, I reinstalled it completly fresh and tried to obtain a certificate and after reading the log, there seems to be a problem:

** Starting Sandstorm at: Fri Aug 16 15:38:33 2019

** Starting back-end...

** Starting MongoDB...

note: noprealloc may hurt performance in many applications

about to fork child process, waiting until server is ready for connections.

forked process: 8

child process started successfully, parent exiting

** Back-end and Mongo started; now starting front-end...

** Starting Gateway...

Fri, 16 Aug 2019 13:38:37 GMT body-parser deprecated undefined extended: provide extended 
option at app/app.js:5506:39

Migrations already applied: 39/39

Skipping unreadable HTTPS key information file while examining: 

/var/sandcats/https/XXX.sandcats.io/1565960324959.response-json

Skipping unreadable HTTPS key information file while examining: 

/var/sandcats/https/XXX.sandcats.io/1565960324959.csr.response-json

Skipping unreadable HTTPS key information file while examining: 

/var/sandcats/https/XXX.sandcats.io/1565961289820.response-json

Skipping unreadable HTTPS key information file while examining: 
/var/sandcats/https/XXX.sandcats.io/1565961289820.csr.response-json

HTTPS mode is enabled but no certs found.

shouldGetAnotherCertificate: There is no key, so yes get a new one.

renewHttpsCertificateIfNeeded: Happily choosing to renew certificate.

generateKeyAndCsr created new key & certificate request for *.XXX.sandcats.io

storeNewKeyAndCsr successfully saved key and certificate request to 
/var/sandcats/https/XXX.sandcats.io/1565962717872 and 
/var/sandcats/https/XXX.sandcats.io/1565962717872.csr respectively of [...]
Submitting certificate request for host XXX where the request has length 926

resetting oauth

sandstorm/gateway.c++:998: error: refused HTTPS connection because no TLS keys are configured
sandstorm/gateway.c++:998: error: refused HTTPS connection because no TLS keys are configured

Received HTTP error while renewing certificate (will keep retrying) 504
Error response contained information 

**I guess the error is: Received HTTP error while renewing certificate (will keep retrying) 504
How to solve it?**

FYI:
These lines were produced when trying to access the site:
*sandstorm/gateway.c++:998: error: refused HTTPS connection because no TLS keys are configured*

**Comment by SwapFaceL** [comment]
Used an own certificate now via reverse proxy.

**Comment by kentonv** [comment]
It looks like Globalsign had an outage earlier this week, and the Sandcats server has been mysteriously sad ever since. I rebooted the server and now it seems to be issuing certificates just fine. Sorry for the inconvenience.
