### ISSUE TITLE
Detect websockets problems as a configuration error

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#316]
Right now, it's easy to accidentally configure a self-hosted Sandstorm so that WebSockets don't work properly, which results in Meteor apps' client code going into a reload-forever loop.

(Hat tip to @mquandalle for reporting this on IRC.)

This bug tracks adding a feature to Sandstorm's shell so it can detect this problem and inform the user.

**Comment by paulproteus** [comment]
Hey @jparyani , maybe this can end up showing up as a Sandstorm shell notifications; iirc you've been working on that feature-set. And/or I could write it if I knew more about the way notifications work.

**Comment by oshepherd** [comment]
This can trip up people even if they think they've configured WebSockets correctly, because e.g. their nginx is too old (One example of this case is an install on Debian Wheezy, which has nginx 1.2, too old for websockets)

**Comment by paulproteus** [comment]
What I would love to see is Sandstorm doing a set of self-diagnostics when
the admin first logs in, and having this be one of them.​

**Comment by paulproteus** [comment]
@jparyani , do you think it's OK for the shell to grow these features, or should it necessarily be a separate Sandstorm app called self-diagnostics?

**Comment by jparyani** [comment]
@paulproteus How do you envision these tests being run? Would some of these tests be run by the user's browser, or would we operate a testing server that does the connectivity tests on your behalf?

In either case, making it a notification to the server admin(s) is probably a good idea. If you don't want to block on notification functionality being implemented, we could still start work on this and dump the results to sandstorm.log as a temporary measure.

**Comment by paulproteus** [comment]
​I imagine them being run in the user's browser -- with some logic like:

if (user.isAdmin() && ! sandstormSelfCheck.alreadyDoneOnce()) {
    // add some Javascript to the page that does these
    // tests.
}

as part of the code that executes on a request to the shell home, aka
"files list". (Note that my mind is still in Django-land, not Meteor-land,
so we might have to translate the above to Meteor-style thinking.)

That way, we piggy-back on an existing URL we basically know they are going
to hit.

They might end up running these tests twice. They're basically harmless, so
that seems fine to me.

This is for tests that do end-to-end sanity-checking of the Sandstorm
install.

For server-side sanity-checking we can do that without this mechanism.

**Comment by ocdtrekkie** [comment]
I am a big fan of things being separate apps wherever possible, @paulproteus, though I kinda imagine there will be configuration things you want to test that cannot be easily tested from a separate app.

**Comment by paulproteus** [comment]
A few months ago, @ocdtrekkie , I wasn't sure that a separate app was the way to go.

But now I think you're right to have this be a separate app, @ocdtrekkie , since making such an app would be easy, but getting code changes into the core of Sandstorm would be more work.

**Comment by ocdtrekkie** [comment]
@paulproteus I think my primary concern when I suggested if you were trying to decide between the two that you go for a separate app, is ensuring the shell/UI isn't a monolithic entity. (As many are likely to want to customize it for various reasons.) It looks like a lot of work went into splitting up components of Sandstorm into a more package-based design, so this may be a non-issue.

But I like to keep it in the back of people's minds.

**Comment by mquandalle** [comment]
Thank you for digging out this issue @paulproteus, I have seen the reports about LB not working on sandstorm and I had no clue about what I could do. Now I just hope this issue gets resolved :)

**Comment by paulproteus** [comment]
(-:​

**Comment by ocdtrekkie** [comment]
Sandstorm does this now, doesn't it? Can close?

**Comment by kentonv** [comment]
Indeed!
