### ISSUE TITLE
Extract app data from backup

### ISSUE THREAD

**Issue by n-serrette** [sandstorm-io/sandstorm#3170]
Hi,

I would like to know if their is a way to extract data from a backup zip. I would like to transfer this data to a standalone version of the app.
Thanks

**Comment by ocdtrekkie** [comment]
The app data is in the backup zip, but how easy it is to transfer depends on the app. Which app?

**Comment by xet7** [comment]
For Wekan, here is example:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

Most likely with other apps something similar could work.

**Comment by n-serrette** [comment]
the app in question is Firefly III.
Thanks for the link, i will look a it.

**Comment by ocdtrekkie** [comment]
So basically, all the grain zip is is the data storage part of a given app. In Firefly III's case, that's a MySQL database. @JC5 might have an idea how you could get that data from the grain zip into a fresh Firefly III install.

Often the ideal case is to use the app's own import/export function, but Firefly III's does say it isn't enough to fully reproduce a Firefly III installation.

**Comment by JC5** [comment]
There is no easy way to extract your data from your Sandstorm instance. It's a database, like @ocdtrekkie mentions. You could copy all the files to the data directory of a new MySQL instance and start it from there. There are some guides on the web. But unfortunately I never really gave this much thought when I designed the Sandstorm grain.

**Comment by xet7** [comment]
Well, could PHP based passthru code be added to Sandstorm Firefly so that there would be button to download dump of MySQL ? It would make it easier to users.
https://stackoverflow.com/questions/6750531/using-a-php-file-to-generate-a-mysql-dump

**Comment by xet7** [comment]
I did try to go manual route but got lost when I did not figure out correct MySQL version:
https://github.com/sandstormports/firefly-iii/wiki/Sandstorm-Firefly-to-Standalone

**Comment by JC5** [comment]
Unfortunately I'm not able to add something like that to the version of Firefly III that's currently in Sandstorm. But the mysqldump tool should be available if you can enter the grain.

**Comment by ocdtrekkie** [comment]
I was a bit surprised that import/export didn't include basically a full database backup option.

I know vagrant-spk has an enter-grain tool for dev work, not sure whether or not there's a way someone could enter a production grain.

**Comment by xet7** [comment]
I did get database dump working :)

https://github.com/sandstormports/firefly-iii/wiki/Sandstorm-Firefly-to-Standalone

**Comment by xet7** [comment]
@n-serrette 

If it works also for you with above instructions, you can close this issue :)

**Comment by ocdtrekkie** [comment]
Nice work, @xet7

**Comment by n-serrette** [comment]
I will test it tomorrow, thanks for your work!
