### ISSUE TITLE
spacejam tests broken as of Meteor 1.8.2

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#3188]
When I try to update to Meteor 1.8.2, the tests no longer run. It looks like they fail in the spacejam stage. The tests hang after printing this:

```
=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: spawning phantomjs
phantomjs: Running tests at http://localhost:4096/local using test-in-console
TYPE_MISMATCH_ERR: DOM Exception 17: The type of an object was incompatible with the expected type of the parameter associated to the object.

  http://localhost:4096/packages/random.js?hash=12299754ae4ff2f712be4beac9e83f1a2767afc3:186
  http://localhost:4096/packages/random.js?hash=12299754ae4ff2f712be4beac9e83f1a2767afc3:278
  http://localhost:4096/packages/random.js?hash=12299754ae4ff2f712be4beac9e83f1a2767afc3:229
  http://localhost:4096/packages/random.js?hash=12299754ae4ff2f712be4beac9e83f1a2767afc3:249
  http://localhost:4096/packages/ddp-client.js?hash=eb08b9f44ae64f2796293bd3e55b9d578fa4893d:774 in subscribe
  http://localhost:4096/packages/ecmascript-runtime-client.js?hash=5b30537e50eb15e04414a25f8255a85e32b4a76c:7682 in bound
  http://localhost:4096/packages/autoupdate.js?hash=5aadf4beac05bd9d8656e96a2c5f41ef8d237f29:200
  http://localhost:4096/packages/autoupdate.js?hash=5aadf4beac05bd9d8656e96a2c5f41ef8d237f29:204
  http://localhost:4096/packages/modules-runtime.js?hash=e45bec2ec3e2453a582f7d943d64a6c995a6f6e3:352 in fileEvaluate
  http://localhost:4096/packages/modules-runtime.js?hash=e45bec2ec3e2453a582f7d943d64a6c995a6f6e3:248 in require
  http://localhost:4096/packages/modules-runtime.js?hash=e45bec2ec3e2453a582f7d943d64a6c995a6f6e3:268 in require
  http://localhost:4096/packages/autoupdate.js?hash=5aadf4beac05bd9d8656e96a2c5f41ef8d237f29:393
  http://localhost:4096/packages/autoupdate.js?hash=5aadf4beac05bd9d8656e96a2c5f41ef8d237f29:400
TypeError: 'undefined' is not an object (evaluating 'Package.autoupdate.Autoupdate')

  http://localhost:4096/global-imports.js?hash=ed60db5bc8cd4937052d0dcf9b644dd3f61ce603:3
TYPE_MISMATCH_ERR: DOM Exception 17: The type of an object was incompatible with the expected type of the parameter associated to the object.

  http://localhost:4096/packages/random.js?hash=12299754ae4ff2f712be4beac9e83f1a2767afc3:186
  http://localhost:4096/packages/random.js?hash=12299754ae4ff2f712be4beac9e83f1a2767afc3:278
  http://localhost:4096/packages/random.js?hash=12299754ae4ff2f712be4beac9e83f1a2767afc3:229
  http://localhost:4096/packages/random.js?hash=12299754ae4ff2f712be4beac9e83f1a2767afc3:249
  http://localhost:4096/packages/tinytest.js?hash=d7080fddb73915a50e693702703f12e5c51111aa:81
  http://localhost:4096/packages/test-in-console.js?hash=7fba2aa99973f535ac55902856ba4b43dff09175:271
  http://localhost:4096/packages/meteor.js?hash=d522625a3ade81e56b990f2722ff3ed57f63222d:1157
  http://localhost:4096/packages/meteor.js?hash=d522625a3ade81e56b990f2722ff3ed57f63222d:938
  http://localhost:4096/packages/meteor.js?hash=d522625a3ade81e56b990f2722ff3ed57f63222d:950
```

In order to reproduce this, do:

```
cd shell
meteor update --release 1.8.2
cd ..
make test
```

I haven't had time to debug much, but it seems like the problem could be that PhantomJS does not correctly mock out some web API function that the `random` package is using -- perhaps `crypto.getRandomValues()`?

However, it doesn't look like `random` has changed lately, and PhantomJS itself has been inactive for years. So, WTF?

**Comment by zenhack** [comment]
Hm, on my machine the tests run with chromium, not phantomjs, maybe because I don't have the latter installed -- can you run it with a different browser, and if so does it work?

**Comment by kentonv** [comment]
@zenhack I think the failure is happening in the "unit test" stage, which operates entirely differently from the Selenium-based tests. This is the same tests that broke after your PR due to not being able to find `capnp.node`. I don't know very much about how these tests work, TBH.

**Comment by zenhack** [comment]
Hm, the tests in that directory don't even use the browser -- they just exercise the sandstorm cli. My guess is they're only using nightwatch at all because it means being able to use the same test harness? Maybe we should just run these tests via node and skip selenium entirely.

**Comment by kentonv** [comment]
@zenhack You must be looking at something different. I am thinking specifically of this test: https://github.com/sandstorm-io/sandstorm/blob/master/shell/packages/sandstorm-permissions/permissions-tests.js

We run that test through `meteor test-packages`, which is a whole different way of running tests. See [src/test-packages.sh](https://github.com/sandstorm-io/sandstorm/blob/master/shell/test-packages.sh). I guess PhantomJS is involved in this test harness, probably on the expectation that Meteor apps will want to test both client-side and server-side code, though the code we test this way is strictly server-side.

I think we had imagined at the time that we'd have more unit tests that run this way in the future, but in practice we've ended up using the Selenium-based test suite for almost everything.

**Comment by zenhack** [comment]
No, you're right, I was looking at this:

https://github.com/sandstorm-io/sandstorm/tree/master/tests/unittests

**Comment by kentonv** [comment]
Lol, I had no idea that was even a thing.

**Comment by kentonv** [comment]
For now I am proceeding with:

    SKIP_UNITTESTS=1 make test

This kinda sucks, but the code being tested -- the permissions algorithm -- hasn't changed in years and I've never seen these tests fail, so I'm not too worried about it for the moment.

The "unit test" in question is [permissions-test.js](https://github.com/sandstorm-io/sandstorm/blob/master/shell/packages/sandstorm-permissions/permissions-tests.js). The test runner we were using, `spacejam`, was abandoned many years ago. It in turn executes the tests using PhantomJS, a fake headless browser which itself was also abandoned years ago. The test itself is written using a unittest harness called `Tinytest`, for which I've struggled to find any documentation at all; it may too be abandoned. It seems like a waste of time to try to coax this stack into working, given it is long-abandoned.

The good news is that there's probably no need for this test to run inside a browser in the first place. In fact, in practice the code in question runs server-side. We should switch to some test runner that executes the code in Node.js.

There is a `meteor test` command that is probably the best starting point, but someone needs to figure out how to use it. We may need to replace `Tinytest` with something else, but our usage looks pretty simple so that should be easy.

**Comment by zenhack** [comment]
I have some work on a branch porting this over to using `meteor test` with mocha & chai (which is what the meteor docs recommend, and they're actually widely used and actively maintained). I plan on getting back to it in the next couple days, but adding a note here on the off chance anyone else decides to tackle this, so we don't duplicate the work.
