### ISSUE TITLE
Meteor 1.9 doesn't work at all

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#3189]
Just trying to update to Meteor 1.9 fails with C++ compiler errors, apparently due to node-sass not being able to build against Node 12. To reproduce:

```
cd shell
meteor update
```

It errors out with no changes having been made.

Not sure where to start with this. Surely node-sass has been updated for Node 12? Do we need to update the package somehow _before_ we update Meteor? How?

**Comment by xet7** [comment]
Wekan currently uses Meteor 1.9, only errors I see are about Node 12 changes about `new Buffer(` changing to `Buffer.alloc()` etc. You could look at Wekan dependencies:
https://github.com/wekan/wekan/tree/master/.meteor

**Comment by xet7** [comment]
For Meteor 1.9, I usually do this:
```
sudo npm -g install npm
sudo npm -g install n
sudo n 12.14.1
sudo npm -g uninstall node-gyp node-pre-gyp fibers
sudo npm -g install node-gyp node-pre-gyp fibers
```

**Comment by xet7** [comment]
And maybe also:
```
sudo node-gyp rebuild
```

**Comment by xet7** [comment]
Just in case, here is also a script I use to convert Wekan x64 bundle to RasPi3/4 arm64 bundle:
https://releases.wekan.team/raspi3/maintainer-make-bundle.sh

**Comment by kentonv** [comment]
@xet7 I'm sure Meteor 1.9 works for some apps, otherwise it wouldn't have been released. :) But Sandstorm itself currently cannot be updated to Meteor 1.9 for some reason. Need to investigate more.

**Comment by kentonv** [comment]
It looks like the problem is that we're still on node-sass 3.x. 4.x was released several years ago but Meteor assumes major version number increases are backwards-incompatible. It does appear that node-sass has continued to update the 3.x branch in the meantime, but it hasn't been updated for node12? I can't tell if there's actually any incompatibility expected in the upgrade, though.

So I'm going to bump us to 4.x an hope nothing breaks...

**Comment by kentonv** [comment]
That seems to work, and now I can upgrade to Meteor 1.9.x. New problem: node12 insists on querying disk files using the new statx() syscall which it invokes directly which bypasses ekam's syscall rewriting, so the node-capnp test spuriously fails... ugh

**Comment by xet7** [comment]
@kentonv 

Thanks a lot for trying to upgrade! I'm also currently upgrading Wekan dependencies.

**Comment by kentonv** [comment]
Solved statx() with: https://github.com/capnproto/ekam/pull/30

New problem: node12 breaks fibers: https://github.com/nodejs/node/issues/29767

Meteor worked around it with a flag: https://github.com/meteor/meteor/commit/c37bab64a4750eafbc6483ee82f67e6ff6221029

I guess I can do that too.

**Comment by kentonv** [comment]
Ughhhh... the pinned version of the icon-font-builder code doesn't work with node 12. If I update to latest versions, they produce broken fonts. Whyyyyyyyyy?
