### ISSUE TITLE
Consider putting a tmpfs at /dev/shm, to support shm_open and friends.

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#3196]
background: yesterday @orblivion hit an issue where postgres wouldn't start because it was trying to open something in `/dev/shm`, which doesn't currently exist in the sandbox. It may be possible to work around this, but it seems sensible to make a tmpfs available to grains at `/dev/shm` to generally improve compatibility with software that expects it.

**Comment by ocdtrekkie** [comment]
This sounds plausibly harmless, after I read what `/dev/shm` is. Are there any downsides you can think of? Postgres support is pretty important, I think, there's several interesting apps that expect it as their sole supported database.

**Comment by orblivion** [comment]
It's possible to turn off the need for shared memory in Postgres. I'm far
off from getting my app to work, so I don't know yet how that affects
performance.

I think Ian did mention one possible downside: it might be smaller than
Postgres (or other programs) expects it to be. I suppose that's still
better than it not being there at all though? So long as the error messages
are useful.

**Comment by abliss** [comment]
refs: https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/posix/shm_open.c;h=eeb6cb558901681958fd082dfe3c6c8f1233296b;hb=eeb6cb558901681958fd082dfe3c6c8f1233296b
https://code.woboq.org/userspace/glibc/sysdeps/posix/shm-directory.h.html
https://code.woboq.org/userspace/glibc/sysdeps/posix/shm-directory.c.html#_M/SHMDIR
`# define SHMDIR (_PATH_DEV "shm/")`

**Comment by kentonv** [comment]
Yeah this would be fine, and should be easy. I believe `/dev` in the sandbox is already a tmpfs, so probably we just need one extra `mkdir()` in there to create `shm`.

**Comment by zenhack** [comment]
Quoting Kenton Varda (2020-02-02 21:02:37)

>    Yeah this would be fine, and should be easy. I believe /dev in the
>    sandbox is already a tmpfs, so probably we just need one extra mkdir()
>    in there to create shm.

It is, but it's mounted read-only, so that would presumably require more
than a mkdir() for apps to actually use it.

**Comment by kentonv** [comment]
@zenhack I mean we should add a `mkdir()` to the supervisor to create this directory at the same time as it creates the rest of `dev`'s contents.
