### ISSUE TITLE
Docs shouldn't call out to the Google Fonts API.

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3199]
I'm going to work on this one, but like Sandstorm and Sandstorm.io, our Docs site shouldn't call the Google Fonts API. Fixing this is fairly trivial, but we have to decide how to go.

Embedding sandstorm.io/fonts/sourcesans.css and using Source Sans would be nice because users already have it cached from sandstorm.io but the change may or may not be preferred, it's a major font departure, but would unify the Docs look with the website better. I'm going to start by making a test grain with this version to see how it looks.

Otherwise, I'd like to add the fonts we need for Docs to sandstorm.io/fonts as well and have a central hosting/caching location for them there.

**Comment by ocdtrekkie** [comment]
Quick browser hack to compare the two.

Before:
![docs-latoroboto](https://user-images.githubusercontent.com/4399499/74568602-f29a0180-4f3d-11ea-87c1-5bfb1af7643d.png)

After (plastering Source Sans on everything):
![docs-sourcesans](https://user-images.githubusercontent.com/4399499/74568603-f463c500-4f3d-11ea-8e94-907c2b43f499.png)

**Comment by zenhack** [comment]
Looks fine to me.

**Comment by kentonv** [comment]
Yeah seems fine.

**Comment by ocdtrekkie** [comment]
I'll work up a PR soon. If we have to use a modified CSS file anyways, there's a good chance I'll tweak that blue to a more Sandstorm purple while I'm at it.
