### ISSUE TITLE
Required settings for Caddy/Reverse Proxy to access grains

### ISSUE THREAD

**Issue by kennyparsons** [sandstorm-io/sandstorm#3210]
When accessing sandstorm via my reverse proxy (caddy), I can configure oauth, and all major settings, but no grains load. They stay stuck on this screen: 
![image](https://user-images.githubusercontent.com/5930491/74166508-49c16e80-4bec-11ea-9889-c74b6764f13f.png)

I think this has to do with the settings for the reverse proxy. What are the required settings to get everything flowing properly.

**Comment by xet7** [comment]
@kennyparsons 

I think Sandstorm requires working wildcard domain.

**Comment by xet7** [comment]
@kennyparsons 

If you don't put Sandstorm behind Caddy, but instead register it as yourservername.sandcats.io, then you get automatic SSL and grains/oauth/etc do work.

**Comment by ocdtrekkie** [comment]
https://docs.sandstorm.io/en/latest/administering/wildcard/ has some information about troubleshooting wildcard DNS, which is usually the problem if everything but grains work.

https://docs.sandstorm.io/en/latest/administering/reverse-proxy/ links to some sample configs for Apache and Nginx reverse proxy setups, though there are some updated SSL recommendations in open PRs right now. The sample configs might give you some insight into anything else you might be missing.

**Comment by kennyparsons** [comment]
@xet7 I want https, so it's gotta go behind my proxy to get ssl. 

So here's my caddyfile

```
sandcats.mydomain.dev {
  proxy / http://192.168.2.xx:6080 {
  	transparent
  	websocket
  	}
}

```
Would I also add a wildcard like so?
```
sandcats.mydomain.dev {
  proxy / http://192.168.2.xx:6080 {
  	transparent
  	websocket
  	}
}
*.sandcats.mydomain.dev {
  proxy / http://192.168.2.xx:6080 {
  	transparent
  	websocket
  	}
}
```

**Comment by ocdtrekkie** [comment]
I am not personally familiar with Caddy configuration. But if your DNS is set up right, you should be able to DNS lookup any arbitrary subdomain of your Sandstorm server's domain, and it return the same IP address as your Sandstorm server. And then your Caddy setup needs to also know to pass any of those subdomains through to the Sandstorm server as well.

**Comment by xet7** [comment]
@kennyparsons 

Caddy wildcard is possible with:

a) CloudFlare
https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

b) Your own bought wildcard SSL cert, with similar config like at a)

c) With Let's Encrypt, if you allow Caddy to update your nameserver TXT records with DNS challenge:
https://caddyserver.com/v1/docs/automatic-https#dns-challenge

For Sandstorm, you need to add those wildcard domains to `/opt/sandstorm/sandstorm.conf` and then do:
```
sudo sandstorm stop
sudo sandstorm start
```

**Comment by kennyparsons** [comment]
@xet7 I am using option 3. Still having the same problem
```
 tls {
    protocols tls1.2 tls1.3
    dns cloudflare
    ciphers ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256
    key_type p384
    must_staple
    wildcard
  }
```

**Comment by xet7** [comment]
@kennyparsons 

Check in CloudFlare DNS, that you use DNS only (gray cloud icon) and not proxy (orange cloud icon).

**Comment by kennyparsons** [comment]
@xet7 all are set to DNS only (no orange cloud)

**Comment by xet7** [comment]
@kennyparsons 

Please ask about LE wildcard settings at caddy forums, or search that forum for answers first.

**Comment by ocdtrekkie** [comment]
I was under the impression Cloudflare required an enterprise plan to do wildcard DNS. Have you tested the DNS resolution itself, like `dig foo.sandcats.mydomain.dev` to make sure you get a response?

Also, can you show us your sandstorm.conf contents (with domains swapped out as necessary for privacy)?

**Comment by kennyparsons** [comment]
@ocdtrekkie dig works fine. 
```
excalibur:~ kennyparsons$ dig foo.sandcats.mydomain.dev

; <<>> DiG 9.10.6 <<>> foo.sandcats.mydomain.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47460
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
; PAD: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ("........................................................")
;; QUESTION SECTION:
;foo.sandcats.mydomain.dev.	IN	A

;; ANSWER SECTION:
foo.sandcats.mydomain.dev. 300	IN	A	7x.4x.3x.1x

;; Query time: 32 msec
;; SERVER: 192.168.2.6#53(192.168.2.6)
;; WHEN: Mon Feb 10 18:55:28 CST 2020
;; MSG SIZE  rcvd: 151
```
Here's my conf
```
cat /opt/sandstorm/sandstorm.conf
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://sandcats.mydomain.dev/
WILDCARD_HOST=*.mydomain.dev/
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
SANDCATS_BASE_DOMAIN=mydomain.dev

```

**Comment by ocdtrekkie** [comment]
Is your wildcard host meant to be *.sandcats.mydomain.dev? Or was that a typo while converting?

Also, if you are using your own domain, not Sandcats, you need to remove the SANDCATS config line.

**Comment by kennyparsons** [comment]
@ocdtrekkie Do you mean remove the SANDCATS_BASE_DOMAIN line?

I looked in the console for errors and I'm getting 421 errors (the same errors that caddy gives when a site isn't defined). 
`421 Site ui-dc4e6f558cf4c9315b334fc25a11c2c4.mydomain.dev is not served on this interface`

**Comment by ocdtrekkie** [comment]
Yeah, delete that line from your configuration entirely. And as I said, you might need your wildcard host to have the subdomain if that was off too compared to what we discussed above.

**Comment by kennyparsons** [comment]
@ocdtrekkie Yes, that was a typo. I removed the line, fixed the typo, restarted standstorm. Still same loading icon. and now the errors in the console only have `ERR_SSL_PROTOCOL_ERROR`

What protocols are available?

**Comment by kennyparsons** [comment]
I'm using this tls directive in my caddyfile:
```
  tls {
    protocols tls1.2 tls1.3
    dns cloudflare
    ciphers ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256
    key_type p384
    must_staple
    wildcard
  }
```

**Comment by ocdtrekkie** [comment]
Sandstorm itself is serving over HTTP in this instance before your Caddy server then serves it over HTTPS, so I don't see why you'd see an issue with your TLS settings from Sandstorm's side.

(Presumably when we figure this out, we should have an example config for Caddy in our docs too?)
