### ISSUE TITLE
spk dev breaks Go's static file serving. 

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#3219]
If I use the Go standard library's support for serving static files, attempts to serve files cause a panic. Below is a stack trace from running [yata][1] in dev mode, when fetching `trash.svg`. I have seen this consistently with other Go programs as well. It only affects dev mode; it works fine in a built spk. When I was last working on this stuff a couple years ago this worked fine.

From the error it looks like maybe Go is trying to monitor a file for changes, and the fuse filesystem is not handling that correctly?

```
2020/02/12 19:12:19 http: panic serving 127.0.0.1:55348: read /etc/mime.types: not pollable
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc000196000)
	/usr/lib/go/src/net/http/server.go:1767 +0x139
panic(0x8beae0, 0xc000129530)
	/usr/lib/go/src/runtime/panic.go:679 +0x1b2
mime.loadMimeFile(0x92e0d3, 0xf)
	/usr/lib/go/src/mime/type_unix.go:47 +0x33e
mime.initMimeUnix()
	/usr/lib/go/src/mime/type_unix.go:53 +0x67
mime.initMime()
	/usr/lib/go/src/mime/type.go:85 +0x60
sync.(*Once).doSlow(0xcc3b08, 0x9491a8)
	/usr/lib/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/usr/lib/go/src/sync/once.go:57
mime.TypeByExtension(0xc00012e0dc, 0x4, 0xc00012e0dc, 0x4)
	/usr/lib/go/src/mime/type.go:107 +0x35d
net/http.serveContent(0x9c3240, 0xc0001ba000, 0xc0001ac300, 0xc00012e0d7, 0x9, 0x52dd61, 0xed5d647f3, 0xca67c0, 0xc0001d3a28, 0x7f352467b008, ...)
	/usr/lib/go/src/net/http/fs.go:196 +0x118a
net/http.serveFile(0x9c3240, 0xc0001ba000, 0xc0001ac300, 0x9bbee0, 0x9b2380, 0xc000134084, 0x11, 0x433e01)
	/usr/lib/go/src/net/http/fs.go:622 +0x6db
net/http.(*fileHandler).ServeHTTP(0xc000020630, 0x9c3240, 0xc0001ba000, 0xc0001ac300)
	/usr/lib/go/src/net/http/fs.go:725 +0xa1
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000150000, 0x9c3240, 0xc0001ba000, 0xc0001ac300)
	/home/isd/go/src/github.com/gorilla/mux/mux.go:162 +0x104
net/http.serverHandler.ServeHTTP(0xc000166000, 0x9c3240, 0xc0001ba000, 0xc0001ac000)
	/usr/lib/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000196000, 0x9c3cc0, 0xc00012c100)
	/usr/lib/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2928 +0x384
```

[1]: https://github.com/zenhack/yata

**Comment by kentonv** [comment]
Huh, I guess this probably means Go can't serve static files from all sorts of filesystems (especially FUSE ones).

There's probably some way to stub out inotify within our FUSE protocol implementation such that it acts like the files never change...

**Comment by zenhack** [comment]
Hm, looking at the relevant code (in type_unix.go), there's nothing resembling file monitoring going on. I will investigate more.

**Comment by zenhack** [comment]
(small update: the "polling" is happening in the bowel's of Go's runtime, not in the logic for static file serving, and I think has to do with asyncio, not inotify. I will dig deeper).

**Comment by kentonv** [comment]
Hopefully they aren't trying to `poll(2)` a disk file, though? That would be a silly thing to do... (And I'm not sure how it could be broken by the filesystem, presumably it just always returns `POLLIN | POLLOUT` for disk files...)

**Comment by zenhack** [comment]
Jotting down my current understanding for later:

The Go runtime has one giant epoll instance for the whole program, with hooks into the scheduler. The standard library's `os` and `net` packages shell out to some common helper types that for some kinds of files (sockets obviously) it makes sense to epoll.

Reading through the implementation of go's os.Open and the Read() method for its File type, I get the impression it's not supposed to go down the code paths where epolling actually happens for disk files. But the only way that error gets signaled in the Read() path is if this flag here gets set:

https://github.com/golang/go/blob/go1.13.7/src/runtime/netpoll_epoll.go#L96

The call to Read() checks that and returns the error accordingly. There's nowhere else in the codebase where that flag gets set to true, and the only way that "not pollable" error can arise via the Read() codepath is if that flag is set.

So, more investigation needed.

**Comment by zenhack** [comment]
More notes for myself for later: I did a git bisect on the Go source tree and it blamed this commit:

https://github.com/golang/go/commit/a5fdd58c84b6b0a1ae5a53faebc0550024e3a066

...but that looks like it's just adding some checking, so the actual problem is presumably before that.

This is probably a Go bug rather than a sandstorm bug, so I'll see if I can put together a coherent bug report and report it upstream.

**Comment by zenhack** [comment]
I put together a simple C program that captures the essential behavior of the Go runtime, and behaves the same way as Go in and out of dev mode:

```c
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/epoll.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

int check(const char *context, int retcode) {
	if(retcode >= 0) {
		return retcode;
	}
	perror(context);
	exit(1);
}

#define CHECK(expr) check(#expr, expr)

int main(void) {
	int mimefd = CHECK(open("/etc/mime.types", O_RDONLY));
	int efd = CHECK(epoll_create(1));

	struct epoll_event ev;
	ev.events = EPOLLIN;

	CHECK(epoll_ctl(efd, EPOLL_CTL_ADD, mimefd, &ev));

	int nready = CHECK(epoll_wait(efd, &ev, 1, -1));
	if(nready != 1) {
		fprintf(stderr, "unexpected number of events returned: %d\n", nready);
		exit(1);
	}
	fprintf(stderr, "events = %x, EPOLLERR = %x\n", ev.events, EPOLLERR);

	return 0;
}
```

When run outside of dev mode, `epoll_ctl` sets `errno` to `EPERM`, indicating that the file descriptor does not support epoll, as expected:

```
epoll_ctl(efd, EPOLL_CTL_ADD, mimefd, &ev): Operation not permitted
```

However when run with spk dev, the debug console shows that the program gets as far as `epoll_wait`, and returns `EPOLLERR` as the events for the file descriptor:

```
events = 8, EPOLLERR = 8
```

Go is relying on the `EPERM` behavior; it expects disk files to return an error here and not add the file descriptor to the epoll instance. Instead, when in dev mode, the error is deferred until `epoll_wait()`, and the runtime reports this to the caller of `Read`.

The `epoll_ctl(2)` man page documents the behavior that Go is expecting here, and that we see outside of dev mode.

**Comment by zenhack** [comment]
Another interesting tidbit: If I point the call to open at something in a filesystem provided by `sshfs` (also fuse), I get this result instead:

```
events = 1, EPOLLERR = 8
```

the value `1` is `EPOLLIN`. So in this case the fd just shows up as readable, rather than returning an error at any point.

**Comment by zenhack** [comment]
I dug through the kernel source a bit, as far as I can tell it's not actually possible for fuse filesystems to implement the behavior documented in the man page. `epoll_ctl` reports the desired error here:

https://github.com/torvalds/linux/blob/45d0b75b98bf1de4b3a5b09188c75f3bfa3152b0/fs/eventpoll.c#L2104

It checks if the file is pollable using `file_can_poll`, defined here:

https://github.com/torvalds/linux/blob/45d0b75b98bf1de4b3a5b09188c75f3bfa3152b0/include/linux/poll.h#L81

...which just checks if the `poll` callback is null.

The fuse driver specifies the callbacks for all files statically:

https://github.com/torvalds/linux/blob/45d0b75b98bf1de4b3a5b09188c75f3bfa3152b0/fs/fuse/file.c#L3354

...so for a file on a fuse file system, `file_can_poll` will always return true, and thus `epoll_ctl` will never return `EPERM`.

---

One possible way to make this work is to actually implement the poll callback, and report the file as readable as long as the cursor is not at the very end of the file.

**Comment by zenhack** [comment]
Actually, would it break anything to just always report readability, even if the cursor *is* at the end of the file? That would be a bit simpler, and I think Go would still behave correctly.

**Comment by zenhack** [comment]
Also, question: is there a reason we're speaking the raw fuse protocol ourselves, rather than just using libfuse?

**Comment by zenhack** [comment]
Also: I tried this out with a couple of other fuse filesystems and they all behaved the same way sshfs did (probably libfuse is handling that?)

**Comment by kentonv** [comment]
It's been a long time since I looked at it, but my recollection is that libfuse provides a "high level" and a "low level" API, and I didn't like either one.

IIRC libfuse's "high level API" tries to do a lot of things for you. Among those things, it tries to hide the VFS tree by converting all paths back into fully-qualified path strings. I don't like this because it means I just have to parse them again, and it implies race conditions when directories are moved while they have open file descriptors (think of clients using `openat()`). Also, the high level API insists on using its own event loop (so would have had to run on its own thread, separate from the KJ event loop) and it is a crappy C-function-pointer-callback API with no user data pointer so you have to rely on thread-locals to find out _which_ FUSE filesystem you are currently operating on, if you have more than one in a process. Basically, it's convenient if you want to write a program whose sole purpose is to create and run one FUSE filesystem (and you don't really care if `openat()` works correctly in the presence of directories being moved), but for anything more complicated, it becomes more trouble than it's worth.

The "low level API" didn't have any of those problems, but also didn't really do anything beyond read requests off the file descriptor and call the corresponding callback. I found it easier to just do that myself rather than work around a C API.

Anyway!

I think the bug here is that the `FUSE_POLL` operation is new since I wrote this code, and I made a poor choice of "default" logic in my code. Check this out:

https://github.com/sandstorm-io/sandstorm/blob/da68e162d9e5cbb774e2849498c72af4db53f6c2/src/sandstorm/fuse.c++#L743-L755

As you can see, for any newly-added operation, we'll fail with `EROFS`. For the exact set of operations that existed at the time, this was correct, because everything not handled in the switch was a write operation. However, `FUSE_POLL` was added later, and is not a write operation. We _should_ respond with `ENOSYS` to indicate we don't support the operation. According to the docs, the kernel will then apply default behavior, which is probably what all the other filesystems you tested are relying on.

So I think we should adjust the above code to explicitly list every known write operation to respond with `EROFS`, and then change the `default` to be `ENOSYS`. That should be forwards-compatible.

**Comment by zenhack** [comment]
Quoting Kenton Varda (2020-02-29 18:54:27)

>    It's been a long time since I looked at it, but my recollection is that
>    libfuse provides a "high level" and a "low level" API, and I didn't
>    like either one.
>
>    IIRC libfuse's "high level API" tries to do a lot of things for you.
>    Among those things, it tries to hide the VFS tree by converting all
>    paths back into fully-qualified path strings. I don't like this because
>    it means I just have to parse them again, and it implies race
>    conditions when directories are moved while they have open file
>    descriptors (think of clients using openat()). Also, the high level API
>    insists on using its own event loop (so would have had to run on its
>    own thread, separate from the KJ event loop) and it is a crappy
>    C-function-pointer-callback API with no user data pointer so you have
>    to rely on thread-locals to find out which FUSE filesystem you are
>    currently operating on, if you have more than one in a process.
>    Basically, it's convenient if you want to write a program whose sole
>    purpose is to create and run one FUSE filesystem (and you don't really
>    care if openat() works correctly in the presence of directories being
>    moved), but for anything more complicated, it becomes more trouble than
>    it's worth.
>
>    The "low level API" didn't have any of those problems, but also didn't
>    really do anything beyond read requests off the file descriptor and
>    call the corresponding callback. I found it easier to just do that
>    myself rather than work around a C API.

That makes sense; kinda the flavor of answer I was expecting.

>    I think the bug here is that the FUSE_POLL operation is new since I
>    wrote this code, and I made a poor choice of "default" logic in my
>    code. Check this out:
>
>    [1]https://github.com/sandstorm-io/sandstorm/blob/da68e162d9e5cbb774e28
>    49498c72af4db53f6c2/src/sandstorm/fuse.c++#L743-L755
>
>    As you can see, for any newly-added operation, we'll fail with EROFS.
>    For the exact set of operations that existed at the time, this was
>    correct, because everything not handled in the switch was a write
>    operation. However, FUSE_POLL was added later, and is not a write
>    operation. We should respond with ENOSYS to indicate we don't support
>    the operation. According to the docs, the kernel will then apply
>    default behavior, which is probably what all the other filesystems you
>    tested are relying on.
>
>    So I think we should adjust the above code to explicitly list every
>    known write operation to respond with EROFS, and then change the
>    default to be ENOSYS. That should be forwards-compatible.

Can confirm that returning ENOSYS for FUSE_POLL fixes the problem. I'll
find some time soonish to submit a pr with the cleaner version of the
fix.
