### ISSUE TITLE
Trying to run sandstorm install inside of docker fails on sysctl kernel.unprivileged_userns_clone

### ISSUE THREAD

**Issue by arthurlutz** [sandstorm-io/sandstorm#322]
Even with -u which seems to be the option mentionned in the README for lxc/docker I get : 

```sysctl: setting key "kernel.unprivileged_userns_clone": Read-only file system
```

This is inside a debian jessie container I built using mkimage.sh (https://github.com/docker/docker/blob/master/contrib/mkimage.sh)

**Comment by jparyani** [comment]
Can you try running with `--privileged`?

**Comment by kentonv** [comment]
Actually I think what you need to do here is set the sysctl _outside_ of Docker. Namely you need to set `kernel.unprivileged_userns_clone` to `1`. Since the container shares the host kernel and this is a kernel setting, you do unfortunately need to set it on the host; there's no way to do it just within a single container.

**Comment by kentonv** [comment]
(You'll also want to edit `/etc/sysctl.conf` to set this again after reboot.)

**Comment by arthurlutz** [comment]
I seem to still be getting this bug even after applying the recommended commands. 

Debian seems to ignore the unprivileged stuff https://github.com/lxc/lxc/issues/250 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=689035 Altough I'm on a recent version of libcap2 (libcap2:amd64        1:2.24-8)

**Comment by paulproteus** [comment]
Hi Arthur,

I'll test this on my own machine today, and add it to the tests for the
install script. Thanks for commenting on the issue, and I hope we can get
your problems resolved.

**Comment by kentonv** [comment]
FWIW, I have been using Debian-Testing on my desktop all along while developing Sandstorm, and never had an issue. So I don't think the problem applies to Debian in general.
