### ISSUE TITLE
ERR_CONNECTION_REFUSED on *.sandcats.io

### ISSUE THREAD

**Issue by evdcush** [sandstorm-io/sandstorm#3230]
I am getting `ERR_CONNECTION_REFUSED` splash whenever I try to connect to my `*.sandcats.io` page. 

This error:

![sandcats_error](https://user-images.githubusercontent.com/28853935/74726930-a9bab380-5283-11ea-86f5-0b634cd4b384.png)

I'm new to self-hosting. I was hoping sandstorm would be as simple as `curl https://install.sandstorm.io | bash`, but after reviewing the documentation, it's clear there must be some assumption about the user's setup or network config that has not been explicitly spelled out for newbies like me.

Specifically, it seems like there should be some extra installation steps or documentation regarding some sort of CA requirements?

The [FAQ](https://docs.sandstorm.io/en/latest/administering/faq/) mentions the `ERR_CONNECTION_REFUSED` error in relation to `WILDCARD_HOST` and `BASE_URL` port disagreement, but that does not seem relevant to my case. However, the FAQ also mentions the need to "import a CA certificate into all web browsers where you want the Sandstorm server to able to be (sic) viewed".

I thought this might be my error, but the documentation is confusing to me. The [custom certificate documentation](https://docs.sandstorm.io/en/latest/administering/self-signed/) seems directed towards users of nginx. 

**what more do I need to do beyond 'curl https://install.sandstorm.io | bash' to use Sandstorm**?

What part of the setup process am I missing?

My `sandstorm.conf`:

```
SERVER_USER=sandstorm
PORT=80
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://foobar.sandcats.io
WILDCARD_HOST=*.foobar.sandcats.io
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
SANDCATS_BASE_DOMAIN=sandcats.io
HTTPS_PORT=443
```

My setup:
- Ubuntu 18.04 server on old thinkpad 
- OpenWRT router, with all relevant ports forwarded

Just to be stupid obvious, I am trying to access the `*.sandcats.io` page from a different machine from my server, on the same home network. The admin-token does not work, though I get the `Sandstorm static publishing needs further configuration (or wrong URL)` splash if I go to the IP of the server instead.

I also have a registered domain name I was planning on using, but that shouldn't be necessary for sandcats.io correct?

**Comment by ocdtrekkie** [comment]
Usually Sandcats is pretty straightforward. It does handle your DNS and SSL configuration for you, and you should be able to disregard most everything in docs about configuring those things.

Have you pinged your Sandcats address to see what it returns? It’s a dynamic DNS service so you should see your public IP address as a result.

**Comment by zenhack** [comment]
One possible thing to try: if you punch `https:` into your url bar explicitly, do you get anything different? sandstorm forwards `http` -> `https` anyway, but many home ISP's block port 80 so that would break the fowarding and this is what you'd see.

**Comment by evdcush** [comment]
@ocdtrekkie you are correct, pinging the sandcats address returns my public IP.

@zenhack there was no difference explicitly entering https. Not entirely sure how to check if port is blocked by ISP, but 

`curl portquiz.net:80 --connect-timeout 1` shows open port, as does 6080.

**Comment by ocdtrekkie** [comment]
Is your Sandstorm reachable from outside your network? (Is this a hairpin routing issue?)

**Comment by evdcush** [comment]
@ocdtrekkie got a 504 when trying to access it from outside my network.

**Comment by ocdtrekkie** [comment]
Is there anything useful/interesting in your log at: /opt/sandstorm/var/log/sandstorm.log

**Comment by evdcush** [comment]
Hmm, nothing that looks useful/interesting to me. 

The only thing that may be different from a standard log is a group of notes about "`Skipping unreadable HTTPS key information file while examining /var/sandcats/https/foobar.sandcats.io/0.csr.response-json`"

Assuming nothing is wrong with my sandstorm installation, what *could* cause this error? I've tried different devices, different browsers on the client side.
