### ISSUE TITLE
Issue with groups on install, if USERGROUPS_ENAB is no

### ISSUE THREAD

**Issue by jeffmendoza** [sandstorm-io/sandstorm#326]
I tried installing on openSUSE. Ran into an issue here: https://github.com/sandstorm-io/sandstorm/blob/master/install.sh#L424
The usermod was failing to add $SUDO_USER to the group because the group didn't exist. After looking at the 'useradd' man page, turns out:

           If not specified, the behavior of useradd will depend on the USERGROUPS_ENAB variable in /etc/login.defs. If
           this variable is set to yes (or -U/--user-group is specified on the command line), a group will be created for
           the user, with the same name as her loginname. If the variable is set to no (or -N/--no-user-group is
           specified on the command line), useradd will set the primary group of the new user to the value specified by
           the GROUP variable in /etc/default/useradd, or 100 by default.

Sure enough: 

    jeffmendoza@suse:~$ cat /etc/login.defs  | grep USERGROUPS_ENAB
    USERGROUPS_ENAB no

Further manpage reading:

       -U, --user-group
           Create a group with the same name as the user, and add the user to this group.

           The default behavior (if the -g, -N, and -U options are not specified) is defined by the USERGROUPS_ENAB
           variable in /etc/login.defs.

Might be worth specifying -U on the useradd?

**Comment by kentonv** [comment]
Thanks for the report. Will fix.

**Comment by paulproteus** [comment]
See also #1306 

Closed in eeb5c74b13f660f9d2d96556ec50229387058971
