### ISSUE TITLE
Issue with domain wildcards

### ISSUE THREAD

**Issue by JS-E** [sandstorm-io/sandstorm#3265]
Hey there!

Just wondered if you could help me out using Sandstorm, really impressed with the features it can provide and i would love to use it for a variety of projects i've got going Great job!

I setup a little sandstorm test enviroment on an AWS system and i wanted it to be hosted completely on my AWS server. So after changing the base url it was up and i could login and see the main page. Unfortunately when i tried to install and run an app (EtherCalc to be specific) the page was just infinitely loading... I had a look online and apparently this issue is caused when the wildcard domain url isn't set, however, when i set it to be *[base_url_here] the whole system stopped responding and i couldn't access it all. I was then forced to terminate the instance and boot another one.

I would like to have it hosted on a static ip address that's assigned by Elastic IP on AWS.

Am i doing something wrong or is there something i need to configure that i'm not doing?

Appreciate the time,

Keep up the good work 👍

**Comment by ocdtrekkie** [comment]
Can you show us what your sandstorm.conf looks like, replacing domains and sub domains to obscure your setup location?

**Comment by ocdtrekkie** [comment]
Also, https://docs.sandstorm.io/en/latest/administering/config-file/ is my reference I always compare to.

**Comment by JS-E** [comment]
Sure here it is:

```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://THIS-IS-AN-AWS-ELASTIC-IP:6080
WILDCARD_HOST=*.THIS-IS-AN-AWS-ELASTIC-IP:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=30025
```
This is a test server i've just booted up for testing purposes :)

**Comment by ocdtrekkie** [comment]
If THIS-IS-AN-AWS-ELASTIC-IP is an IP address, its not going to work, you can't have subdomains of an IP address. It does need a domain name with a wildcard DNS entry.

**Comment by JS-E** [comment]
Okay i thought that might pose an issue. So i've terminated that instance and set up a new one on a site i have that is connected using a subdomain that can point to an IP. After doing a little google, i found out that i can create a SRV record to forward a subdomain to the correct port. Would that then let Sandstorm create it's wildcard domains? For example i'd like it to be...

**sandstorm.mysite.com**
**.sandstorm.mysite.com**

**Comment by ocdtrekkie** [comment]
I am not positive about whether or not the SRV record to forward to the correct port will work or not (nobody I've heard of has done that), but yeah, *.sandstorm.mysite.com is a viable choice for the wildcard setting. You definitely want the config for those lines to look like it should look in the web browser, so you would not put :6080 on BASE_URL or WILDCARD_HOST if the port is being redirected.

Just remember in your DNS, you'll need both the entry for the base subdomain and for the wildcard.

**Comment by ocdtrekkie** [comment]
https://community.cloudflare.com/t/dns-srv-record-redirect-ip-and-port/53346/8 suggests SRV records don't do any sort of port redirection, just to communicate what port a service can be found on.

Is there a reason you can't use port 80 (or 443) on your Sandstorm server?

**Comment by JS-E** [comment]
@ocdtrekkie So i'm running another application on port 80 and i want 443 to be reserved for when i upgrade to https.

So on my godaddy hosting dns page, i already have a sub domain that points to ip, but i'll need another subdomain (sandstorm) to point to the 6080 port that i want it to hit, and also need godaddy to know that sandstorm is okay to create subs on that domain too. Is that along the right lines?

**Comment by ocdtrekkie** [comment]
So my guess is the SRV record isn't going to help you here, and you need to use :6080. So make sure your config is like this:

```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://SANDSTORM.MYSITE.COM:6080
WILDCARD_HOST=*.SANDSTORM.MYSITE.COM:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=30025
```

And then yes, you need two DNS entries, one that points to `SANDSTORM` (in the example above) with the destination being your Sandstorm server's IP, and one that points to `*.SANDSTORM`, which also has the destination of your Sandstorm server's IP.

**Comment by JS-E** [comment]
@ocdtrekkie Appreciate the info, sooo i've added some dns records to godaddy and i can now access it on sandstorm.mysite.com:6080 (would prefer it to redirect that subdomain port 80 to 6080...not ideal, but it'll do for now) and i can sign in. Now i'm still getting that issue with apps not loading and if i go onto the admin panel i get the 'WILDCARD-HOST MISCONFIGURED' error banner at the top, so something still is wrong 👎 

The wildcard host has been set up like you said and i added a A record on godaddy that points to the IP and uses *.sandstorm.mysite.com  

Any other ideas, i'm getting closer haha

**Comment by ocdtrekkie** [comment]
If you run like a ping foo.sandstorm.mysite.com does it try to ping the IP address of your Sandstorm server?

**Comment by JS-E** [comment]
Oh wait! It works.

So in the DNS entries of godaddy, i was doing an A name of *.sandstorm.mysite.com then having it point to the ip address. Instead i did: *.sandstorm ONLY, and it detected it all fine and was all happy

**Comment by JS-E** [comment]
Really appreciate your help @ocdtrekkie 😄

**Comment by ocdtrekkie** [comment]
Awesome! No problem. I'm going to mark this one closed, but feel free to open another one if you have another issue while you're getting started, or comment on this one if you have further wildcard-related issues so I can reopen it. :)

**Comment by ocdtrekkie** [comment]
Oh, some additional notes about the port issue:

- You can customize your web server on port 80 to forward applicable requests to Sandstorm. Our reverse proxy page has advice on this for Nginx or Apache: https://docs.sandstorm.io/en/latest/administering/reverse-proxy/ though the example configs use some dated SSL settings because the PRs to update them haven't been adequately tested. It may be outside my skill set to help you with this if you get stuck though. ;)

- If you end up using a separate server for Sandstorm which has it's own IP address, you shouldn't have any problem using port 80 on that server for your Sandstorm setup, and you can still put it's IP addresses in your DNS as you did for this configuration, and it shouldn't have any conflict with your main server.
