### ISSUE TITLE
Prevent email login bounces/spam?

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3267]
Hi,
currently when using email login with email address that does not have account or invite on Sandstorm server, this happens:
1) Add email address and click button
1) Email login token is sent
2) Token is added to login form
3) User gets message that user does not have access to any grains.

I have received bounce from AWS SES for some .de email address that does not have account on my Sandstorm server.

Could this be changed to work this way?
1) Add email address and click button
2) If that email address does not have any account or invite on Sandstorm server, don't send login token by email

**Comment by ocdtrekkie** [comment]
I think you're looking for a setting that would disable guests from signing in, as Sandstorm lets anyone sign in fir the purposes of identifying themselves on public grains or grains shared with them.

**Comment by xet7** [comment]
@ocdtrekkie 

Probably, but does that affect for example SandForms in any way?

**Comment by xet7** [comment]
@ocdtrekkie 

It seems that my Sandstorm server has in Admin Panel a list of Guest users. Those could be SandForms, WordPress or other shared grain users. Would it be possible to list to what grains those visitors have access?

Public grains is still useful feature, so I don't know yet would setting to prevent having public grains be useful.

**Comment by ocdtrekkie** [comment]
Like by design, anyone can sign into a Sandstorm server, and if they visit a shared grain it is added to their grain list so they can find it again.

**Comment by ocdtrekkie** [comment]
I think it'd be fair to say this would be duplicate of #2995 ?

**Comment by xet7** [comment]
@ocdtrekkie 

Yes.

Moved to #2995
