### ISSUE TITLE
Install script fails on Alpine Linux (no useradd command)

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#3272]
Apparently Alpine Linux doesn't have a `useradd` command, it has `adduser` instead, so the install script fails here if it is asked to create the sandstorm user:

https://github.com/sandstorm-io/sandstorm/blob/2131dcb7cc28177416980c427ff3304651e6cb93/install.sh#L1183

Ironcally, the comment above that says we're using usermod because adduser isn't generally available. Perhaps we could try usermod and fall back to adduser if it's not available.

Relevant discussion on IRC:

https://freenode.irclog.whitequark.org/sandstorm/2020-03-19#26600332;

**Comment by ocdtrekkie** [comment]
Doesn't sound like a particularly extensive project, I bite-sized it.
