### ISSUE TITLE
Github OAUTH Fails.

### ISSUE THREAD

**Issue by JohhnyKinuthia** [sandstorm-io/sandstorm#3273]
I have tried to install sandstorm on a self-hosted server but I am unable to complete the last step of the installation process where an admin account has to be created via either Github or Google.
Whenever I try to sign up using either Google or Github, I am redirected back to the 'Log in to create your admin account' screen... The system log shows the following:
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Google. failed [400] {   "error": "redirect_uri_mismatch",   "error_description": "Bad Request" }
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with GitHub. redirect_uri_mismatch
Any help is very much appreciated.

**Comment by ocdtrekkie** [comment]
I know OAuth is super picky about the redirect URI. Make sure http/https matches, make sure it includes the port if you're not using 80 or 443, etc.

**Comment by JohhnyKinuthia** [comment]
Hi I am using https port(443) but the problem is that the OAuth server redirects to https://domainname.com/setup/user instead of https://domainname.com/. This causes Sandstorm to delete the admin token.

**Comment by JohhnyKinuthia** [comment]
Thank  you very much. I have updated the BASE_URL in the sandstorm config file to https and everything works as expected.
