### ISSUE TITLE
fix node SSL bug

### ISSUE THREAD

**Issue by abliss** [sandstorm-io/sandstorm#3284]
The version of node bundled with sandstorm, 8.15.1, seems to have a bug in its SSL implementation. As a result, tiny-tiny-rss cannot use sandstrom-httpGet to fetch certain feeds (for example, ones on https://nitter.net).

Minimal example:
```
$ /opt/sandstorm/latest/bin/node -e "require('https').get('https://nitter.net', (e,r,b) => {console.log(e);});"                                         events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO 140122876737344:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:

    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
```

I'm not sure when exactly the bug was fixed. It might be https://github.com/nodejs/help/issues/1730 . My system node is v10.18.1 and it is able to fetch.

**Comment by abliss** [comment]
Looks like there's a workaround:
```require("tls").DEFAULT_ECDH_CURVE = "auto"```
This seems to fix the bug in this case.

**Comment by zenhack** [comment]
Is your sandstorm installation up to date? The upgrade to meteor 1.9 should have updated node to 12.x

**Comment by abliss** [comment]
Probably fixed by the upgrade to node 12 which I somehow had not received.
