### ISSUE TITLE
"sandstorm dev-shell" fails

### ISSUE THREAD

**Issue by ankitmhn** [sandstorm-io/sandstorm#3303]
Running sandstorm dev-shell after running make in the sandstorm folder returns this message:
`sandstorm dev-shell
/home/wekan/.meteor/packages/meteor-tool/.1.8.0.unq2g3.soqs++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node: bad option: --no-wasm-code-gc`

Any ideas please? It would be great if somebody could point me to an updated guide get the dev environment setup locally I've already gone through steps around "hacking the shell" on the documentation page. Thanks!

**Comment by zenhack** [comment]
Hm, have you installed the built version of sandstorm (make update)? The
1.8 in the error message is suspicious, since sandstorm master is on
meteor 1.10, and if you're trying to run dev-shell against an older
version of sandstorm installed on the system, that might cause problems.

Quoting ankitmhn (2020-04-28 14:21:09)

>    Running sandstorm dev-shell after running make in the sandstorm folder
>    returns this message:
>    sandstorm dev-shell
>    /home/wekan/.meteor/packages/meteor-tool/.1.8.0.unq2g3.soqs++os.linux.x
>    86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev
>    _bundle/bin/node: bad option: --no-wasm-code-gc
>
>    Any ideas please? It would be great if somebody could point me to an
>    updated guide get the dev environment setup locally I've already gone
>    through steps around "hacking the shell" on the documentation page.
>    Thanks!

**Comment by ankitmhn** [comment]
This was the error on the VM from the [Wekan virtual appliance](https://github.com/wekan/wekan/wiki/virtual-appliance) for developers. Which is the only time I had "make" complete without any errors. But then I got the error above when I run `sandstorm dev-shell` On my local installation though I seem to be running into the error in issue #3177 
I tried the compiler flags as suggested but it doesn't seem to work either :(

**Comment by zenhack** [comment]
Can you post a full build log?

**Comment by ankitmhn** [comment]
Okay, I got it to progress a bit more this time using the -fPIC flag on the line for `LIBS2` . However I get this error now: 
```
==== custom color icons/upload.svg ====
==== custom color icons/upload.svg ====
==== custom color icons/restore.svg ====
==== custom color icons/restore.svg ====
Finding meteor-tool installation (can take a few seconds)... meteor-tool@1.8.2
cd icons && PATH=/bin:$PATH /bin/npm install
/bin/sh: 1: /bin/npm: not found
Makefile:297: recipe for target 'icons/node_modules' failed
make: *** [icons/node_modules] Error 127
```

**Comment by zenhack** [comment]
Hm, what does `./find-meteor-dev-bundle.sh` print?

**Comment by ankitmhn** [comment]
`./find-meteor-dev-bundle.sh` prints this: `/home/ankit/.meteor/packages/meteor-tool/.1.10.1.qxau23.f3ni++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle`

**Comment by zenhack** [comment]
What about: `./find-meteor-dev-bundle.sh METEOR@1.8.2`?

If that comes up short, try:

`curl https://install.meteor.com/?release=1.8.2 | sh`

Looks like 5e1b35206 added the requirement to also have an older version of meteor installed, but didn't update the docs accordingly. I probably didn't notice because I had the old toolchain installed from earlier.

//cc @kentonv

**Comment by ankitmhn** [comment]
Looks like `curl https://install.meteor.com/?release=1.8.2 | sh` did the trick. Thank you!

**Comment by zenhack** [comment]
No problem. I opened a pr (#3304) to fix the doc bitrot; sorry about that.
