### ISSUE TITLE
Feature Request: Sandstorm as installable PWA for mobile

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3305]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

**Comment by zenhack** [comment]
I'm way ahead of you:

https://github.com/sandstorm-io/sandstorm/pull/3155

:P

...it should already work; do you not see the add to home screen button on your mobile browser?

**Comment by xet7** [comment]
Oops I have not tried. I'm too slow.
