### ISSUE TITLE
ACME.js phones home.

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#3310]
A leftover task from #3299: we agreed we should patch out ACME.js's telemetry (sending an opt-out mechanism upstream if possible). I wanted to make sure we had an open issue tracking it.

**Comment by kentonv** [comment]
Yep, I already have a patch locally which will be in today's release. Turns out to be as easy as:

    import Maintainers from "@root/acme/maintainers.js";
    Maintainers.init = (me) => {};

I've also been in touch with the author and he said he understands and may add an option.

**Comment by ocdtrekkie** [comment]
Fixed by https://github.com/sandstorm-io/sandstorm/commit/84b22287bea298ab2f9b901dcee3fd8dddae9dfa
