### ISSUE TITLE
createAccountForCredential TypeError: Cannot read property 'findOne' of undefined

### ISSUE THREAD

**Issue by flyinghuman** [sandstorm-io/sandstorm#3322]
Hello,

on a new installation with latest-version 264 no other users can be created via LDAP Login. After login with LDAP the user sees this message: **Failed to create account. Internal server error (500)** surrounded in Sanstorm GUI. The Admin user works like expected and all apps are working too within this admin-user. Here is the Log: 

`stack: 709c10 7109e0
Exception while invoking method 'createAccountForCredential' TypeError: Cannot read property 'findOne' of undefined
    at Function.SandstormDb.fillInProfileDefaults (imports/sandstorm-db/profile.js:233:30)
    at MethodInvocation.createAccountForCredential (imports/server/accounts/credentials/credentials-server.js:193:17)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43`

We use nginx reverse Proxy with wildcard HTTPS Certificates (on Admin user all works fine.) LDAP is the only active Auth-Provider enabled.

Thanks!

![sandstorm](https://user-images.githubusercontent.com/3713548/81165284-092a8480-8f92-11ea-99bb-13c67cb9fc63.png)

Edit: Enabling Email Authentication; Registering with Email and after that add LDAP to this Account is working - but that is only a bad workaround because each user must do this for himself...

**Comment by snowball77** [comment]
Same issue on our server...

**Comment by zenhack** [comment]
uggh, this probably got broken by some of the recent refactoring. We really need better tests for some of this stuff. I'll dig into it.

**Comment by zenhack** [comment]
I've submitted a patch which should fix this: #3323

Per the description though, I don't have an actual LDAP setup to test this against.

**Comment by zenhack** [comment]
@zarvox, can we re-open this until we have confirmation that it actually fixes the problem?

**Comment by flyinghuman** [comment]
okay, thanks. how can i test it? i only use the tz package for installation. which file i must replace?

**Comment by flyinghuman** [comment]
The Patch resolves the problem. can be closed.
