### ISSUE TITLE
Suggested location for static files to be used by the shell?

### ISSUE THREAD

**Issue by ankitmhn** [sandstorm-io/sandstorm#3347]
I'm wondering if there's a default (recommended?) location where I could store the static files for my custom Sandstorm build? 

For more context, I wish to replace the default avatar image (which looks like a QR code) with an image from one of ~20 random images that I have.

Also, please excuse me if this is a silly question but what does this piece of code mean: `<p>{{_ (con txt "picture.subtext")}}</p>`? If someone could point me to where these keywords are defined within the codebase, I could take it from there or point me to resources that could explain what it does, it would be very helpful. I'm primarily a React dev and this is my frist brush with Meteor/Blaze. Thanks!

**Comment by zenhack** [comment]
The contents of `shell/public` are served as static files.

> Also, please excuse me if this is a silly question but what does this piece of code mean: `<p>{{_ (con txt "picture.subtext")}}</p>`?

This is part of our internationalization framework; see: https://github.com/TAPevents/tap-i18n

The actual translations for this are under `shell/i18n`. See also the "Internationalization" section in CONTRIBUTING.md
