### ISSUE TITLE
Can't fetch certificate, Sandstorm uses redundant domains in the request

### ISSUE THREAD

**Issue by Phaen** [sandstorm-io/sandstorm#3375]
I have a server that is running Sandstorm, but where the Sandstorm interface is not on the root domain, but on the sandstorm subdomain. When trying to fetch a certificate, it will however try to fetch a certificate for both the wildcard subdomain and the sandstorm subdomain, the second of which is obviously redundant. As a result, the request will fail with the following error:
```
[400] Error creating new order :: Domain name "sandstorm.<DOMAIN>" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request. [couldnt_renew_cert]
```

Looking at the ACME.js log, we can see that it indeed orders a certificate for both domains:
```
ACME.js notification: certificate_order {
  account: {
    key: { kid: 'https://acme-v02.api.letsencrypt.org/acme/acct/<ID>' }
  },
  subject: 'sandstorm.<DOMAIN>',
  altnames: [ 'sandstorm.<DOMAIN>', '*.<DOMAIN>' ],
  challengeTypes: [ 'dns-01' ]
}
```

Is there any way to fix this, or is this an issue with Sandstorm?

**Comment by ocdtrekkie** [comment]
I will go ahead and mark it as a bug at the moment, our Let's Encrypt support is very new, so it's definitely at least investigating what has happened here! And much of it's testing relates specifically to the configuration Sandcats uses by default, where the wildcard is a subdomain *under* the address of the Sandstorm interface.

**Comment by ocdtrekkie** [comment]
Likely the offending code: https://github.com/sandstorm-io/sandstorm/blob/master/shell/imports/server/acme.js#L145-L151
Probably should check if the baseHost is inside the wildcard when assembling that list?

Alpha is presumably an example where this would be an issue as well, as an example?
alpha.sandstorm.io uses alpha-*.sandstorm.io subdomains, so the wildcard host would be *.sandstorm.io, which would cause this issue. (Though I don't believe Alpha is using this code at present.)

**Comment by zenhack** [comment]
> Probably should check if the baseHost is inside the wildcard when assembling that list?

Yeah, this sounds like the right fix to me.
