### ISSUE TITLE
Sandstorm aggressively caches this one time that my DNS didn't work, resulting in app packages that can never be installed

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#339]
I just tried to install Let's Chat, and I guess my DNS hiccup'd so that I got this record in `db.packages`:

```
{ "_id" : "c87750d0ccb310217e5f7050ccd0ec3d", "appId" : null, "error" : "getaddrinfo ENOTFOUND", "manifest" : null, "progress" : -1, "status" : "failed" }
```

Then I end up in a state where:

* I visit http://local.sandstorm.io:6080/ and click "Install apps", then
* I click to install Let's Chat, and
* When redirected back to my local Sandstorm, I permanently see that same error message. Clicking reload doesn't help; repeating the above doesn't help.

Removing that "row" successfully works around the issue.

**Comment by paulproteus** [comment]
Restarting Sandstorm didn't seem to help either.

**Comment by paulproteus** [comment]
For clarity here:

The way I removed the "row" is (as I recall):

Launch the Sandstorm database shell:

```
$ sandstorm mongo
```

Make sure there is at least one "row" with this error:
```
> db.packages.find({'error': 'getaddrinfo ENOTFOUND'});
```

Remove it:

```
> db.packages.remove({'error': 'getaddrinfo ENOTFOUND'});
```

Hooray.

**Comment by eitland** [comment]
Had the same problem. 

db.packages.find({'error': 'getaddrinfo ENOTFOUND'}); returned 4 documents. 

After deleting them the package in question installed fine.

Thanks a lot @paulproteus !

**Comment by zarvox** [comment]
I think this is fixed, possibly by recent improvements to the install flow!

In a VM, I disabled my DNS by commenting out all the nameservers in `/etc/resolv.conf`, verified that I failed to install the app, reenabled the nameservers, and then clicked the "Try again" button, and the app I was installing installed successfully.
