### ISSUE TITLE
App index doesn't display SVGs in review interface

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3392]
This is a tiny literally-only-affects-me bug because it's in app market review. But I spent some time looking at if I can fix it, and the fix is probably very, very simple:

![image](https://user-images.githubusercontent.com/4399499/88226226-5b924d80-cc31-11ea-8c95-418fd1237784.png)

This is an escaping bug, in that when encodeURIcomponent is applied to the data portion of the SVG, such that the SVG data looks like `%3Csvg width='44'`, it displays fine.

![image](https://user-images.githubusercontent.com/4399499/88226737-289c8980-cc32-11ea-93a7-bb7f1d1d67c4.png)

The code governing the display of SVGs in this interface is here: https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/app-index/review.html#L93 and I am wondering if replacing the "data" on that line with `encodeURIComponent(data)` will fix it?

**Comment by kpreid** [comment]
Yes, `encodeURIComponent` is the correct tool for escaping content in a `data:` URL. You could also use an [object URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to embed a reference to the data instead of inlining it, which might have better performance (or not hit URL length limits) for large images.

**Comment by ocdtrekkie** [comment]
I probably won't get creative here because testing it is hard/annoying. And I am the only one who will be annoyed by it as a performance issue. At least in Firefox's case, I found "Firefox supports data URLs of essentially unlimited length" in the page about it.

Also, i,i, https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/app-index/review.html#L29 "when using G+ URLs as references to information seemed like a safe bet".
