### ISSUE TITLE
Demo language should not encourage creating an account on Alpha

### ISSUE THREAD

**Issue by pflegende** [sandstorm-io/sandstorm#3397]
sandstorm Demopad
Samstag 1 August 2020 12:00
little hint, after some years  ... tears ... ;)

good stuff on sandstorm,
also after some years looking around
;)

but let me say some little hint:

  the acc crossLogin gh seems doesnt work ...

Create account
Your demo data will be transferred to your new account.
with GitHubwith Googlewith e-mail

gh, gmai both has no action  / reaction

after connecting to sandstorm

dont understand because this usability is so long in the repo
looks not good,

may be somebody thinks here is someone collecting accountdata by connecting gh, goo acc's
 to sandstorm without some need

https://alpha.sandstorm.io/grain/GsTJZGHExhutxEWNF4f9fD/

https://alpha.sandstorm.io/grain/ubzMFNCPre4KsXFyMAHRRT/  

CU
tdiky9ccdj9l@opayq.net

keep healty!
:)

**Comment by ocdtrekkie** [comment]
So it's a bit hard to understand here, but my guess is you tried our demo and then were surprised logging in didn't save your grains.

Unfortunately, Sandstorm no longer offers Sandstorm as a service, you have to run your own server. In the past, you could convert from the demo to a paid Sandstorm account, but when that was shut down, the demo was moved to Alpha, a testing server, where only certain users can log in.

**Comment by ocdtrekkie** [comment]
I think we should mark this as a bug, because the demo shouldn't still have language about saving your data if you log in, it's not true anymore.

**Comment by zenhack** [comment]
@ocdtrekkie, could you update the title to reflect that? I'd like to be able to tell what this issue is about from the title if I'm skimming the issues list in the future.

**Comment by pflegende** [comment]
great!
thx.

**Comment by pflegende** [comment]
that's better and more clearly ...
(and causes not in a direction of missunderstanding ...)

hope you do not take the bad.
was not bad meant.

:+1:

**Comment by ocdtrekkie** [comment]
We appreciate you letting us know this was confusing to you!

**Comment by zenhack** [comment]
Hm, on demo.sandstorm.io this appears to have been updated at least in the English version of the UI:

![Screen Shot 2020-08-04 at 16 10 27](https://user-images.githubusercontent.com/883774/89340140-44aa1d00-d66d-11ea-8637-6e6fd30d62c8.png)

But I can't find the text of that warning message anywhere in the source tree, and the old message ("your demo data will be transferred to your new account") still appears in the relevant places in the code (haven't taken the time to figure out how to actually set up demo mode to confirm this is what get displayed though).

Are we sure alpha is running the same version of the code that's in the repo? (@kentonv?)

**Comment by kentonv** [comment]
Sorry, I had forgotten to push my changes.

**Comment by zenhack** [comment]
We should probably also update the corresponding text for other languages.

@xet7, @urakagi, @malsony, @m-burg, @jeau, any interest in updating the translations you've worked on in the past?

(I wish there was an easier way for me to tag folks who've worked on translations than using git blame and trying to correlate with usernames... Maybe we could put together a team so I could just do @sandstorm-io/l10n?)

**Comment by xet7** [comment]
@kentonv @zenhack 

Should this be updated too? https://github.com/sandstorm-io/sandstorm/blob/master/shell/i18n/en.i18n.json#L7

**Comment by ocdtrekkie** [comment]
@xet7 The line below that is "cannotUpgrade", so as long as we are triggering that code path, it should be fine.

**Comment by xet7** [comment]
I added updated Finnish translation https://github.com/sandstorm-io/sandstorm/pull/3400

**Comment by kentonv** [comment]
Whoops, I guess I should have at least deleted the text for languages I don't know.
