### ISSUE TITLE
seccomp rule denying CLONE_NEWUSER doesn't account for s390x being weird

### ISSUE THREAD

**Issue by smcv** [sandstorm-io/sandstorm#3402]
Forwarding this from Flatpak, which has seccomp rules descended from Sandstorm's:

Sandstorm has

```
  CHECK_SECCOMP(seccomp_rule_add(ctx, SCMP_ACT_ERRNO(EPERM), SCMP_SYS(clone), 1,
      SCMP_A0(SCMP_CMP_MASKED_EQ, CLONE_NEWUSER, CLONE_NEWUSER)));
```

but this is apparently wrong on the s390, s390x and cris architectures, where the clone syscall puts its arguments in a different order. This can be solved by using `SCMP_A1` instead of `SCMP_A0` on the affected architectures, as in this Flatpak PR: https://github.com/flatpak/flatpak/pull/3777

(I don't use Sandstorm myself and I don't own an IBM mainframe, so I am unable to confirm this issue or test a change - just raising an issue FYI.)

**Comment by kentonv** [comment]
Hi Simon,

Thanks for the report.

Seccomp rules are inherently architecture-dependent, and Sandstorm only targets x86_64, so we don't consider this a bug in Sandstorm. If we were to add support for other architectures, we would definitely review the whole seccomp filter for issues like this.
