### ISSUE TITLE
Fetching Let's Encrypt cert hanging indefinitely

### ISSUE THREAD

**Issue by eflynch** [sandstorm-io/sandstorm#3406]
Hi all, I'm new to sandstorm so sorry if I'm missing what's glaringly obvious.

I'm trying to install sandstorm on a VPS (Ubuntu 18.04). When I run the standard install script (via `sudo curl https://install.sandstorm.io | bash`), and register a sandcat domain as prompted, at the point of getting a Let'sEncrypt cert, the process hangs.

```
You must provide an email address, which will be shared with Let's Encrypt.
Your email address for Let's Encrypt: [evan.f.lynch@gmail.com]
success
Your Let's Encrypt account has been created. Now we'll fetch a certificate!
This may take a while. You may be able to see progress in the logs: /opt/sandstorm/var/log/sandstorm.log
...
```

I let it go for a day and a half on the change that I should really take that warning seriously, but I have begun to lose faith. Nothing seems to be logged in the specified location.

**Comment by eflynch** [comment]
I could provide more details of the specific situation I am in, although it seems largely generic as I have a clean VPS and apart from setting up a sudoer account and an ssh key, I haven't done anything but run the installer, so my instinct is that this should be readily reproduced.

**Comment by ocdtrekkie** [comment]
There should be something logged! Is the sandstorm service running on the box?

**Comment by abliss** [comment]
What VPS provider are you using? Have you checked your firewall settings?
Some firewalls cause outgoing packets to silently be discarded, which can
make some client software (usually with a combination of ill-configured
timeouts) hang for a really really long time.

--Adam

**Comment by eflynch** [comment]
Thanks for the quick responses!
Of course, now it seems to have worked despite no intervention on my part, so perhaps I just wasn't patient enough. I'll close this one out.
