### ISSUE TITLE
TT-RSS Update broken?

### ISSUE THREAD

**Issue by jdougan** [sandstorm-io/sandstorm#3412]
After the recent tt-rss (1.13.0-1) update I got  many many powerbox requests with no information as to what they were about.  Since they were modal, I couldn't inspect the rest of the app or go to the sandstorm controls without editing the url.
After a lot of clicking through the powerbox requests I'm seeing HTTP 503 errors on a lot of feeds.  I get a 500 error dialog when I try to take a sandstorm backup. 

What should I do about this?  Is this the right place to ask about this? If not, where? Which additional information do you need?

Is there a way to back down to the previous version of ttrss? I did a sandstorm backup of the ttrss grain just before the update, but that won't restore.

**Comment by ocdtrekkie** [comment]
You may wish to read https://sandstorm.io/news/2020-08-08-tiny-tiny-rss-and-the-powerbox

In short, TTRSS no longer uses a hole in the sandbox to get feeds, it asks for access to each feed through the Powerbox. This is a little annoying the first time through for an upgrade but it's not very painful during normal usage.

You can/should also report TTRSS app bugs directly at github.com/zenhack/ttrss-sandstorm though Ian will see it here too.

**Comment by abliss** [comment]
Also: we apologize for breaking your app! We talked a lot about how to roll out an update to close this hole in the sandbox in the least disruptive way possible. We couldn't figure out a really good solution so we went with the least bad one. If you have suggestions for how to do it better, we are all ears!

**Comment by zenhack** [comment]
Quoting jdougan (2020-08-20 11:10:37)

> I get a 500 error dialog when I try to take a sandstorm backup.

It shouldn't be possible for TTRSS to cause _that_. Is there anything
interesting in your sandstorm.log? What about the debug console (monitor
icon in the top bar)?

-Ian

**Comment by jdougan** [comment]
I'm going to close this off for now. After some heroic effort at my VM provider, I got them to not overwrite my last system backup , restored it, then carefully did the update and clicked all the power box requests. It does appear to be working now though there are issues with ttrss taking way more disk usage when I leave the UI open in my browser.  My VM provider had to shut the instance down as it was interfering with other customers on the node. When I have time I'll report my issues here but the short description is  Powerbox UI needs changing to be more descriptive and asynchronous. Also, I'm still not certain, but it may be burning server resources while it is waiting for input, but I'm less confident in that assessment.
