### ISSUE TITLE
App Index review broken by client side CSP

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3422]
As Kenton suspected, this change does cause breakage with the App Index. Under "authorPgpKeyFingerprint", I get a `fetch/</xhr.onerror@` error. This is called here: https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/app-index/review.html#L161 which I believe not just displays the data from Keybase to the reviewer, but also pushes the data to where it can be found by the app market.

**Comment by zenhack** [comment]
I opened a pr (#3431) that fixes this.

**Comment by zenhack** [comment]
That pr is merged now, can we close this?

**Comment by ocdtrekkie** [comment]
I'll go ahead and close it, but note that Kenton hasn't actually built/signed/updated the new app index package yet.
