### ISSUE TITLE
Allow a grain to provide a path and hash when creating a link for sharing

### ISSUE THREAD

**Issue by troyjfarrell** [sandstorm-io/sandstorm#3428]
Sandstorm allows grains to help the user get a link for sharing an application by posting a message:
```javascript
window.parent.postMessage({'startSharing': {}}, '*');
```
I would like to have the ability to provide a path and hash when creating a link for sharing.  Perhaps we could have 
```javascript
window.parent.postMessage({'startSharing': {path:'/foo/bar', hash: 'baz'}}, '*');
```
or
```javascript
window.parent.postMessage({'startSharing': {append:'/foo/bar#baz'}}, '*');
```
which might yield a link like https://example.sandcats.io/shared/H_fqmZZwHzXvzDeht_MuiojQ7w3ogBO7eauV3buqh2c/foo/bar#baz

**Comment by zenhack** [comment]
Seems reasonable to me.

**Comment by troyjfarrell** [comment]
I'm going to try to make this happen, but I'll need some hand-holding.  The above `window.parent.postMessage({'startSharing': {…})` results in this code running:

https://github.com/sandstorm-io/sandstorm/blob/740f227e1a2c3e9429017133b7395189ac23859e/shell/imports/client/grain-client.js#L1506-L1513

Line 1512 is the most interesting.  Let's look at `globalTopbar.openPopup("share", true)`:

https://github.com/sandstorm-io/sandstorm/blob/740f227e1a2c3e9429017133b7395189ac23859e/shell/imports/sandstorm-ui-topbar/topbar.js#L388-L392

This sets three `ReactiveVar`s to "share", true and false respectively.  Documentation for ReactiveVar is here:
https://docs.meteor.com/api/reactive-var.html

I haven't quite figured out how those `ReactiveVar`s interact with the rest of the code.  I'm not familiar with Meteor, but I suspect that these will appear in the templates (or helper code for the templates.)

I'm probably getting ahead of myself, but I don't see how I'm going to get the `path` and `hash` parts of the URL to the code that needs them, whether via passing them to `currentGrain` or through `globalTopbar`.  (Maybe that will become clear as I read more code.)  This code (which I found by searching for '/shared/') seems to suggest that `currentGrain` might work:

https://github.com/sandstorm-io/sandstorm/blob/740f227e1a2c3e9429017133b7395189ac23859e/shell/imports/client/grain-client.js#L502-L536

The code path between the two is not clear to me.  I believe that I've jumped from where the share dialog is instantiated to where the form submission is handled, but the parts in the middle feel like magic.  Regardless, lines 526 and 527 above, coupled with lines 466 of grain.html (below) make it clear that this is where we need to add the necessary parts to the URL:

https://github.com/sandstorm-io/sandstorm/blob/740f227e1a2c3e9429017133b7395189ac23859e/shell/imports/client/grain.html#L463-L469

So, maybe one of you knows Meteor enough to suggest how we can get `path` and `hash` (and maybe `query`?) from `postMessage` to the submit event handler in `grain-client.js`.  I hope so.

**Comment by zenhack** [comment]
My take would be:

1. Change openPopup to accept some actual data, rather than just an on/off boolean, and pass the data in there.
2. change sandstormTopbarItem so that it passes this extra data to the popup template. This is a little finicky since right now it has a parameter `data` that is supposed to be the whole data context, not 100% sure what the best approach is.
3. Thread the data from the popup template (in this case grainSharePopup) to where it needs to via template parameters.

@zarvox, curious to your thoughts on this.

**Comment by troyjfarrell** [comment]
Having read through the code again, I think that following the pattern implemented by powerboxRequest looks the most reasonable.  Unless someone objects, I'll try to put together a pull request.

**Comment by troyjfarrell** [comment]
I would like to note that this gives us a path for apps to suggest permissions for sharing.
