### ISSUE TITLE
sandstorm-http-bridge does not forward the Host header to API sessions

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#343]
This is a problem for git-http-backend, which returns a 400 if the Host header is not present.

The solution will probably involve adding a field to ApiSession.Params.

**Comment by kentonv** [comment]
What host would we send, though? The API endpoint? What meaning does that really have for apps? Can we instead just fill in a dummy host like "sandbox"? (That could happen in sandstorm-http-bridge with no change to Sandstorm itself.)

**Comment by dwrensha** [comment]
A bogus host would suffice for got - http - back end.

**Comment by dwrensha** [comment]
(Pardon the typos, typing on phone.)

**Comment by paulproteus** [comment]
For Django apps, they use the "Host:" header as part of calculating things
like password reset links. (I realize password reset links from _apps_
don't make much sense in Sandstorm, but it might get used other places.)

See also:

https://docs.djangoproject.com/en/1.8/ref/settings/#allowed-hosts

I haven't dug into the importance yet of the Host: header for Django apps,
but I wanted to leave this note here. I think it should be fine for now to
use a bogus value, and then if we run into any surprises, deal with them
then.

**Comment by kentonv** [comment]
@dwrensha Cool, let's do that.

@paulproteus We're specifically talking about API endpoints here, not user interfaces. We pass through a valid "host" header for the iframe UI path, containing the session hostname.

**Comment by paulproteus** [comment]
*nod*​

It's a little strange to have two different Host: headers for the same app,
but that's not an objection, just a remark.

**Comment by kentonv** [comment]
@paulproteus We have many more than two. We have one for each session. :)

It has indeed been problematic for many apps that, for whatever reason, don't like to use relative URLs.
