### ISSUE TITLE
"Using the grain's title in your app" example from documentation does not work

### ISSUE THREAD

**Issue by troyjfarrell** [sandstorm-io/sandstorm#3430]
The docs contain an example ["Using the grain's title in your app"](https://docs.sandstorm.io/en/latest/developing/path/#using-the-grains-title-in-your-app):
```javascript
var getGrainTitleRpcId = 0;

// Sandstorm will reply via postMessage, so we need to set up a handler:
window.addEventListener('message', function(event) {
  if(event.source !== window.parent) {
    // SECURITY: ignore messages not from the parent.
    return;
  }
  if(event.data.rpcId === getGrainTtileRpcId) {
    console.log("The grain's title is: ", event.data.grainTitle);
  }
})

// Now make the request:
window.postMessage({
  getGrainTitle: {},
  rpcId: getGrainTitleRpcId,
  // If subscribe is true, sandstorm will push future updates to the
  // grain's title. If it is false or absent, the app will not be
  // notified of updates.
  subscribe: true,
}, '*')
```

I get one `message` event which contains no grain title and no follow-up events when the grain title is changed.  Is there a way to run a debugger inside Meteor inside Sandstorm?  This sounds complicated.

**Comment by zenhack** [comment]
Anything interesting in the browser console? All of the relevant code
for this feature runs client-side.

Quoting Troy J. Farrell (2020-09-09 02:00:46)

**Comment by troyjfarrell** [comment]
I hadn't considered that there is no round-trip for this information.  Of course the browser already knows the grain title.

Using the Firefox JavaScript debugger, the message event handler does not get called (back) with the grain title.  There's no error message in the console and the debugger does not break in the event handler.  Let me see if I can trace this further through the frames.

**Comment by troyjfarrell** [comment]
Once you sit back and read the code with fresh eyes, the errors are obvious.  The initial `postMessage` was called on the wrong `window`–should have been `window.parent.postMessage` and `getGrainTtileRpcId` was misspelled.

**Comment by zenhack** [comment]
Derp. Yep, good catch.

Quoting Jacob Weisz (2020-10-22 08:15:23)
