### ISSUE TITLE
Server responds to HEAD requests with HTTP 500

### ISSUE THREAD

**Issue by rs22** [sandstorm-io/sandstorm#3454]
I'm trying to package a Docker [registry](https://github.com/docker/distribution) server as a Sandstorm app. When pushing images, the client makes HEAD requests with the blob ids of individual layers to check if they already exist on the server. The server initially responds with a 404, however Sandstorm turns this response into a 500 internal server error.

This applies to all 404 responses to HEAD requests where the Content-Length header is set on the response. It can be reproduced using the following node.js express HTTP server:

```js
const express = require('express')
const app = express()
const port = 8080

app.get('/empty_response', (req, res) => {
  res.status(404).end()
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

The issue can be observed like this:
```
$ curl --head http://api-<id>.local.sandstorm.io:6080/path_does_not_exist -H 'authorization: Basic <auth>'
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 278
Content-Type: text/plain
```
The following entry appears in the Sandstorm logs:
```
capnp/rpc.c++:146: info: returning failure over rpc; exception = kj/async-inl.h:1230: failed: PromiseFulfiller was destroyed without fulfilling the promise.
stack: 4761a0 677e60
```

This is what the expected response looks like:
```
$ curl --head http://localhost:8080/path_does_not_exist
HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 159
Date: Wed, 21 Oct 2020 09:55:48 GMT
Connection: keep-alive
```

The following works fine (no `Content-Length` set in the response):
```
$ curl --head http://api-<id>.local.sandstorm.io:6080/empty_response -H 'authorization: Basic <auth>'
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag
Content-Security-Policy: default-src 'none'; sandbox
Vary: Authorization
```

I'm not sure where this can be fixed. Is this a problem of the sandstorm-http-bridge or the builtin HTTP server?

**Comment by zenhack** [comment]
Thanks for the report. This is a probably a bug in sandstorm-http-bridge.

**Comment by zenhack** [comment]
What does the grain log show? If my hunch is right and it's a bridge bug the interesting stuff will be in there.

**Comment by rs22** [comment]
Looks like you're right -- this showed up in the logs when activating the `--verbose` flag for `sandstorm-http-bridge`:
```
capnp/rpc.c++:146: info: returning failure over rpc; exception = sandstorm/sandstorm-http-bridge.c++:187: failed: Failed to parse HTTP response from sandboxed app.; error = stream ended at an unexpected time
stack: 4e53db 4ae391 4eabc0 5e51a0
```

**Comment by zenhack** [comment]
Ok, I've tracked down the problem (more or less what I expected it to be); I'll have a patch soonish.
