### ISSUE TITLE
Error 500 on grain backup

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3457]
Tested both on my server and Alpha, here's from my log:

```
capnp/rpc.c++:146: info: returning failure over rpc; exception = sandstorm/util.c++:66: failed: openat(dirfd, name.cStr(), flags, mode): No such file or directory; name = cgroup.freeze
stack: 51f46d 6db3ac 49d276 49d33a 5661a5 565d7d 5280d1 70c170
Exception while invoking method 'backupGrain' Error: remote exception: openat(dirfd, name.cStr(), flags, mode): No such file or directory; name = cgroup.freeze
```

@orblivion noted it first. cc @zenhack

**Comment by orblivion** [comment]
I think my error log is exactly the same.

**Comment by zenhack** [comment]
Ug, it looks like the freeze functionality is compile-time configurable in the kernel, and ubuntu 18.04 doesn't include it. I'll have a patch that makes this degrade gracefully soon (as it does if cgroups2 just isn't supported at all).
