### ISSUE TITLE
SSL Configuration

### ISSUE THREAD

**Issue by Bianconiglio** [sandstorm-io/sandstorm#3467]
Hi,
i have try to configure sandstorm for work in SSL, in normal HTTP work good.

In begin i have try to use cloudflare SSL over HTTP sandstorm configuration but not work.

Do you have a documentation for enable HTTPS?

**Comment by ocdtrekkie** [comment]
From the SSL/TLS Certificates admin page, you can configure the built-in Let's Encrypt client. Cloudflare is a supported DNS provider. Once that's configured correctly, you should be able to set the HTTPS_PORT config option in sandstorm.conf.

**Comment by Bianconiglio** [comment]
thank you for answer.
i have try to upload  SSL/TLS Certificates in admin page but browser give me report that Certificates are not reconize, i have create Certificates in ubuntu and i have upload Certificates from cloudflare to my server and same result.

i have try to install nginx and browser sandstorm from normal http port with cloudflare ssl service in frontend, but not work.

**Comment by ocdtrekkie** [comment]
Note that if you're uploading your own certificate, it needs to be a wildcard certificate. However, as noted above, if you use the ACME configuration to set up Let's Encrypt, your Sandstorm server will generate and renew it's own wildcard certificates. I believe in the case you'd just generate an API token in Cloudflare so that Sandstorm can configure the proof you control the domain.

Another possible issue you may run into: Are you changing the BASE_URL? Even if you use the HTTP_PORT to connect to Sandstorm, your BASE_URL should match what you expect to see in the browser (https://).

**Comment by Bianconiglio** [comment]
now i have configure nginx and sandstorn for work, nginx in port 80 and sandstorm in port 8080 and work!
if i put cloudflare dns in SSL I browse nginx and sandstorm but when i login inside i dont browse image and dont work:

my sandstorm config:

SERVER_USER=sandstorm
PORT=8080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://mydomain
WILDCARD_HOST=*.mydomain
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=30025

my nginx config:

server {
  listen       80;
  server_name  mydomain;

  location / {
    proxy_pass http://0.0.0.0:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  }
}

in HTTP working good

in HTTPS with CLOUDFLARE dont show image inside panel and app dont work.

**Comment by ocdtrekkie** [comment]
If you ping foo.mydomain, do you get the right IP address? Images and apps both are hosted at subdomains.

**Comment by Bianconiglio** [comment]
ip of mydomain is ip of cloudflare
ip of foo.mydomain is real ip of machine

but with  foo.mydomain to HTTP port 80 answer sandstorm and tell me: Sandstorm doesn't recognize this host name

it's possible answer nginx in HTTP in port 80 with foo.mydomain and not sandstorm?

**Comment by Bianconiglio** [comment]
I think problem is cloudflare give me SSL for domain but not give me SSL for subdomain and sandstorm have base_url with https://
for domain but for subdomain want the same but cloudflare dont give me SSL for subdomain

**Comment by ocdtrekkie** [comment]
Yeah, if your Cloudflare plan doesn't cover wildcard subdomains, it isn't going to work to use Cloudflare's SSL. I think you may need a paid plan for that. But you could use Cloudflare for DNS, and Sandstorm's built-in Let's Encrypt support, which should work, I believe even on free plans.

**Comment by Bianconiglio** [comment]
yes cloudflare want a enterprise plane for  subdomain.

Now i have try in admin /SSL/TLS certificates to use acme.

i hace create acme account and it's ok.

in dns provider i try to configure dns. i have select cloudflare, in cloudflare i have create a token, but in sandstorm ask me to put configuration in json format.

do you known the structure of json?

i have try to put {token:'XXXXX'} but not work.

**Comment by ocdtrekkie** [comment]
https://github.com/sandstorm-io/sandstorm/issues/3300#issuecomment-709316971 says `{ token: 'xxx' }` is correct, I am unsure if spacing is an issue though or not.

**Comment by Bianconiglio** [comment]
nothing i have try { token: 'xxx' } and when i click ok tell me there is a error : Invalid JSON: Unexpected token t in JSON at position 2

if i put only { } work good and save.

**Comment by Bianconiglio** [comment]
ok correct is

 { "token": "xxx" }

**Comment by ocdtrekkie** [comment]
Were you able to get everything working then?

**Comment by Bianconiglio** [comment]
i have remove nginx and use only sandstorm.

i have configure correct SSL/TLS certificates and Cloudflare Token.

when reload the sandstorm in browser link is with HTTPS with real IP, but

browser tell me message: :SSLV3_ALERT_CERTIFICATE_UNKNOWN and connection is Not secure but if i read the certificate is correct available and is of cloudflare.

i can login inside sandstorm with HTTPS (Not Secure) and in admin i have again WARNING: This server seems to have its WILDCARD_HOST misconfigured. AND WARNING: This server seems to be unable to create a WebSocket.

**Comment by Bianconiglio** [comment]
ok  now work all correct.

i have put inside sandstorm.conf:

HTTPS_PORT=443
PORT=6080

and in admin SSL/TLS i have click Fetch certificate Now -> after one 1 minute i have refresh browser and sandstorm work in SSL.

Thank you for help.

**Comment by ocdtrekkie** [comment]
Awesome! Glad you got it.
