### ISSUE TITLE
Web publishing appears to be broken

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3472]
EDIT: This appears to be the case on both Alpha and my own server. My guess is Ian's security fix for static publishing is it.

Static publishing appears broken from the two things I've tested (Davros grains and docs.sandstorm.io):

A Davros grain:
```
ERROR: The server threw an exception. Details:

(remote):0: failed: remote exception: remote exception: open: Too many levels of symbolic links; name = www
stack: 70d6f0 49a390 48bc30 52ad90 605f50 609c60
```

docs.sandstorm.io:
```
ERROR: The server threw an exception. Details:

(remote):0: failed: remote exception: remote exception: expected part.findFirst('/') == nullptr; '/' character in path component; did you mean to use Path::parse()?; part = en/latest/index.html
stack: 70d6f0 49a390 48bc30 52ad90 605f50 609c60
```

**Comment by kentonv** [comment]
I rolled back the change and pushed a new release, rather than push a new change that was written under time pressure and could have other issues.

Let's take some time to carefully test before we try to land this again.

**Comment by kentonv** [comment]
Anyone who is still seeing this issue should run:

```
sudo sandstorm update
```

**Comment by zenhack** [comment]
@paulproteus, apparently you're the owner on the docs.sandstorm.io grain? I don't suppose you could send me a backup of that grain so I can test it?

(we should really make it possible to transfer ownership of grains...)

**Comment by ocdtrekkie** [comment]
@zenhack Could you sub your own GitWeb grain URL into the doc_prod Action on a fork, and effectively generate your own?

**Comment by zenhack** [comment]
Good thought, giving it a try.

**Comment by paulproteus** [comment]
https://alpha.sandstorm.io/shared/t1G2BHJHLKv-bNAGiNKlaMGgJSFtfZ9iCyQf3mhbwR5 is a docs.sandstorm.io grain backup! Cheers to all.

**Comment by zenhack** [comment]
Great, saved the backup. In the meantime I took @ocdtrekkie's suggestion and pointed the CI at my own box. The fix appears to work as expected.

**Comment by zenhack** [comment]
Other apps we should verify still work with this:

- [ ] Wordpress
- [ ] Ghost

...and possibly others, I'll have to look at the app market and see if there's anything else.

**Comment by zenhack** [comment]
Aggregating a more complete list of apps that use static publishing here:

- [x] Davros
- [x] Gitweb
- [ ] Hacker slides
- [ ] Hugo
- [ ] Hakyll CMS
- [ ] Ghost
- [ ] Hacker CMS
- [ ] Wordpress

...that's everything I'm aware of after scanning through the app market. I think after going through and making sure this fix works for all of those we can go ahead with this.
