### ISSUE TITLE
Infinite loading grain (wildcard DNS works though?)

### ISSUE THREAD

**Issue by diomat** [sandstorm-io/sandstorm#3478]
Hello fellow sand dwellers,

I have installed Sandstorm according to the docs (Option 2: GitHub-verified install) on my Linux server running Ubuntu 18.04. After configuration to use Github as loginprovider I wanted to start a grain. Unfortunately the loading animation for starting the grain never stops. This is true for any preinstalled grain.

sandstorm.conf

```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://linux1:6080
WILDCARD_HOST=*.linux1:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
```

Message from Debug Log window:

```
...** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain no longer in use; shutting down.
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain no longer in use; shutting down.
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain no longer in use; shutting down.
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
```

After researching the issue I found out I had to set up wild card DNS which I did (on a Windows DNS Server). Pinging example.linux1 works fine now, but grains are still not loading.

sandstorm.log also looks fine to me

```
** Shutting down due to signal
** Exiting
** Starting Sandstorm at: Fri Dec 11 09:26:41 2020
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 8
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
** Starting Gateway...
Fri, 11 Dec 2020 08:27:20 GMT body-parser deprecated undefined extended: provide extended option at app/app.js:1220:39
(node:59) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Migrations already applied: 41/41
Unhandled exception in Promise:  [Error: remote exception: grain is not running] {
  cppFile: '(remote)',
  line: 0,
  kjType: 'disconnected'
}
Downloading app: https://app-index.sandstorm.io/packages/37c3aedbaa2f5a96866226d2136bb293
App ready: 37c3aedbaa2f5a96866226d2136bb293
fetching keybase A1665BE1E8F6A2A3BEC7382A8CCA345A01E9EF4B
fetching keybase A1665BE1E8F6A2A3BEC7382A8CCA345A01E9EF4B
** Shutting down due to signal
** Exiting
** Starting Sandstorm at: Sun Dec 13 01:17:04 2020
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 8
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
** Starting Gateway...
Sun, 13 Dec 2020 00:17:44 GMT body-parser deprecated undefined extended: provide extended option at app/app.js:1220:39
(node:59) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Migrations already applied: 41/41
```

I also checked ports 6080 and 6081 on my Linux machine and they are not occupied by other programs.

I don't know what to do next to solve the problem. Anyone got an idea?

Thanks

**Comment by troyjfarrell** [comment]
Hi diomat.

I've not seen this problem before.  Are there any messages in the browser's JavaScript console?

**Comment by ocdtrekkie** [comment]
IIRC we found an issue with single-name DNS entries, and how certain browsers (*cough* Chrome) handles them from a security standpoint. i.e. using `linux1` and `*.linux1` may be problematic in a way that using `linux1.tld` and `*.linux1.tld` may not. Although I thought that pertained specifically to HTTPS, which isn't in play here from the looks of it.

**Comment by diomat** [comment]
> 
> Hi diomat.
> 
> I've not seen this problem before. Are there any messages in the browser's JavaScript console?

Hi troy,

indeed there is a message

```
Failed to load resource: the server responded with a status of 403 (Unauthorized)
```

I deactivated all adblocking in Firefox (UBlock Origin, Privacy Badger and Privacy Possum). After deactivating Privacy Possum the grain now works in Firefox :)

But!

I also tested with Edge and Google Chrome by generating a sharing link and the error persists in those browsers, although there are no adblocking extensions installed.

Thats...weird?

**Comment by diomat** [comment]
> 
> 
> IIRC we found an issue with single-name DNS entries, and how certain browsers (_cough_ Chrome) handles them from a security standpoint. i.e. using `linux1` and `*.linux1` may be problematic in a way that using `linux1.tld` and `*.linux1.tld` may not. Although I thought that pertained specifically to HTTPS, which isn't in play here from the looks of it.

Oh, that might explain it then. Are there any details?

**Comment by ocdtrekkie** [comment]
I'm not positive if we discussed it on IRC or in a GitHub issue somewhere... But you could probably try it by coming up with some nonsense forward lookup zone in your Windows Server DNS.

**Comment by ocdtrekkie** [comment]
Or, if you're in an Active Directory, you should be able to append the full domain name after your host name to get a complete enough URL.

**Comment by diomat** [comment]
Thanks for the ideas. I'll have to look into setting up forward lookup zones.

This computer is part of AD but appending the FQDN does not work ("Site can't be found").

But my issue is resolved. Thanks for your help troy and trekkie.
