### ISSUE TITLE
I don't receive mail from Gmail into the generated Roundcube grain

### ISSUE THREAD

**Issue by nukedone** [sandstorm-io/sandstorm#3487]
I set up a Sandstorm instance on a domain with custom ports (7443) and (7080). I have a problem that email sent from multiple providers to the Roundcube grain are not received. Is there any port that needs to be forwarded to receive email in Sandstorm. 
Thanks.

**Comment by zenhack** [comment]
@nukedone, yes, setting up inbound email has a couple more steps, including opening up an extra port. See the section "Receiving email into Sandstorm grains" in:

https://docs.sandstorm.io/en/latest/administering/email/

**Comment by nukedone** [comment]
Is it possible to use another port? And if I follow, there shoud be a separate setup of nginx for that. Are the lines that you posted for `nginx.conf` and `/etc/nginx/sites-available/default` all that I need to do (after installing nginx in the first place). Thanks!

**Comment by ocdtrekkie** [comment]
Yes, the inbound mail port is set in sandstorm.conf. I think people have used things like 30025 and so before.

**Comment by nukedone** [comment]
I managed to configure everything. Created my own certificates, added a CA into `/usr/local/share/ca-certificates/` as as `.crt` file, updated certificates with `sudo update-ca-certificates` and set up `nginx.conf` and `/etc/nginx/sites-enabled/default` as reads in [https://docs.sandstorm.io/en/latest/administering/email/](https://docs.sandstorm.io/en/latest/administering/email/). We may close the issue!
