### ISSUE TITLE
Bug: Not Possible to Share Access to Wekan-Grain / Add Users to Wekan Board

### ISSUE THREAD

**Issue by kuchengrab** [sandstorm-io/sandstorm#3489]
Sandstorm Version: 0.278 (https://fair.sandcats.io/)
Wekan Version: 4.75.0
Browser: Firefox 84.0.2 (64-bit) / Chrome 87.0.4280.141 (64-Bit)

Bug description:
**Access sharing of Wekan boards does not work** (A) and **users cannot be added to any board** (B).
Example Board: https://fair.sandcats.io/shared/DWdxiWEzBvvDenKXLNHlHiIH7sRGVFriHIs5AVDZPSP (link with edit permission)

Steps to reproduce (A):
1. Share access via link, email-invite or by directly tagging a user via the _share access_ button
2. User can't see or access the public board, it says:
```
Board not found.
This page may be private. You may be able to view it by logging in.
```
Expected Behaviour:
User can at least see the public board (and edit, if the link has editing permissions)

Steps to reproduce (B):
1. in Wekan, add a user to the board by going to _board settings > click `(+)` icon_
2. Powerbox request pops up: select user
3. click `Connect` — nothing happens OR: 
4. select radio button `member - can edit` and click `Connect` — popup closes, but user does not appear as added to the board (steps can be repeated indefinitely, nothing happens).
![image](https://user-images.githubusercontent.com/46924279/104328254-f175a980-54eb-11eb-8f4d-e081e944998c.png)

Expected Behaviour:
User can be added to the board and subsequently add and move cards.

There is no error logged in either the Sandstorm debug log nor the Firefox Debugger.

With a new Wekan grain, this issue does not come up. Possibly my grain is corrupted somehow?

**Comment by kuchengrab** [comment]
@rasos

**Comment by ocdtrekkie** [comment]
So, to clarify, are you saying it works if you create a Wekan with 4.75, but it doesn't work if you use a Wekan upgraded to 4.75?

Note that this is an issue with the app, and it's best reported directly to Wekan. (I will tag @xet7 here though too.)

**Comment by xet7** [comment]
In Wekan this is issue https://github.com/wekan/wekan/issues/3423 

Yes, I'll try to fix this sometime.

**Comment by kuchengrab** [comment]
I think I have an idea what happened. 
If I go to the [apps section](https://fair.sandcats.io/apps) within fair.sandcats.io and I make a new Wekan grain, it installs a v4.70 Wekan.

My Wekan grain was an old one (v4.26 iirc) and somehow I patched 4.75 on top of it ... by going directly to https://apps.sandstorm.io/, selecting _wekan > select server > list of wekan grains > upgrade_.

thanks, @ocdtrekkie and @xet7 for the quick reaction!

**Comment by xet7** [comment]
Yes, it's possible to upgrade from nearly any old Wekan version to newest, Wekan has migration code.

**Comment by xet7** [comment]
I think this is Wekan bug, not Sandstorm bug, so I think this Sandstorm issue can be closed.
