### ISSUE TITLE
WILDCARD_HOST misconfigured. Until you fix it, you will not be able to use any apps.

### ISSUE THREAD

**Issue by RavenfireIT** [sandstorm-io/sandstorm#3504]
I know this have come up before but I have been unable to resolve:
SERVER_USER=sandstorm
PORT=80
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://ravenfire.sandcats.io
WILDCARD_HOST=*.ravenfire.sandcats.io
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=25
SANDCATS_BASE_DOMAIN=sandcats.io
HTTPS_PORT=443

I am able to login & the Cert seems to be OK, but I still get the warning in the Admin Panel & I am unable to run any apps (also note that the icon for the apps is also missing.

![ksnip_20210301-145822](https://user-images.githubusercontent.com/58718012/109570319-b2e97d80-7a9e-11eb-8f2c-763b2e9245eb.png)

**Comment by zenhack** [comment]
I think I'm missing some context; is there prior discussion somewhere that you're referring to?

**Comment by ocdtrekkie** [comment]
I think they are just acknowledging it's a common issue.

First thing to test is that pinging foo.yourdomain.com and yourdomain.com returns the same IP address.

**Comment by RavenfireIT** [comment]
Hi,

> I think I'm missing some context; is there prior discussion somewhere that you're referring to?
---> I have looked up the issue and it has come up several times.

> First thing to test is that pinging foo.yourdomain.com and yourdomain.com returns the same IP address.
---> Yes, I am able to login via the public url

Internally I resolve to the external IP (was previously configured using my internal IP), the issue is the same either way.

Thanks in advance.

**Comment by RavenfireIT** [comment]
I stand corrected.

No longer works, there is some issue with my router. It would seem that 443 is being redirected to the router interface (pfSense).

Had the issue before but it had been cleared up (I thought).

**Comment by RavenfireIT** [comment]
This issue seems to lie with my WS being internal and the system being resolved externally ...

**Comment by ocdtrekkie** [comment]
https://ravenfire.sandcats.io and https://foo.ravenfire.sandcats.io both resolve to the same IP address (though your server isn't accessible that way, at least, from where I am, so I am guessing you are not port forwarding 443). If you have different DNS internally, it's likely an issue with the wildcard entry (which is why grains and static images don't work, but the main server URL does) in your DNS.

Without knowing more about your internal networking, I can't tell you what's going wrong. But it's usually DNS, particularly if the main URL is working for you.

**Comment by RavenfireIT** [comment]
All is working now, had a couple issues:

1. Router external management cannot be turn off, so I had to change port from 443 (pfSense default)
2. Had to enable reflection to allow hairpin on router
3. Note: all icons show up now

Thanks.

**Comment by ocdtrekkie** [comment]
Glad you got it, hairpinning can definitely be an issue if you are relying on an external DNS provider (like Sandcats) to access a local resource.
