### ISSUE TITLE
GoDaddy DNS support broken

### ISSUE THREAD

**Issue by nanoscopic** [sandstorm-io/sandstorm#3511]
GoDaddy DNS support is broken/does not work.
The reference including the module being used is here: https://github.com/sandstorm-io/sandstorm/blob/ffba0f1689cc6399f32a70f2b86f12de23933c0d/shell/package.json#L28

That module is this: https://www.npmjs.com/package/acme-dns-01-godaddy

The source for that module is here: https://git.rootprojects.org/root/acme-dns-01-godaddy.js

It is broken due to a missing return documented in this issue: https://git.rootprojects.org/root/acme-dns-01-godaddy.js/issues/1

That in turn seems to be a mirror of this: https://git.coolaj86.com/coolaj86/acme-dns-01-godaddy.js/src/branch/master/lib/index.js

Looking at the blame it has been broken for a year. GoDaddy DNS support, has, therefore, been broken for a year due to a single line bug.

I've contacted the author of the module in question. If no response is received in the next week or two I suggest moving to a fork with this fixed.

**Comment by ocdtrekkie** [comment]
@nanoscopic It looks like the author of the dependency has fixed it! That means you should see the fix for this in the next regular release of Sandstorm (likely in about two weeks). Our use of ACME was *mostly* part of enabling Let's Encrypt for Sandcats.io DNS, so most of the focus has been there. There are less people using their own custom DNS and also using our new Let's Encrypt support, so unfortunately some of these are not heavily tested yet. (In fact, it may have been broken for a year, but Sandstorm has supported and included that module for less than a year... it's entirely possible it's never worked with GoDaddy DNS on Sandstorm, and that you are the first to try it.)

**Comment by nanoscopic** [comment]
-nods- Yes, I reached out to the author via email and he fixed and responded the same day. He was very helpful.

I have been wanting some sort of cohesive set of intranet tools for my own company for some time now, and this project looks to have potential, so I am attempting to set it up. I have my own server(s) and domains so I have no interest in hosted services or dynamic DNS.

I was sad to see that RocketChat has become out of date and/or that Matrix support has not been figured out or integrated thus far. I will definitely be wanting/needing a reasonable chat solution.

In my mind the following are necessary tools for any new startup:
1. A ticket tracking tool, or something more minimal such as trello. This is what led me to sandstorm.
2. A git server ( gogs in sandstorm case should work )
3. A chat support/collaboration system
4. A CICD system
5. An artifact tracking system ( can do without in a pinch just using something built into CICD )
6. A docker image server
6b. A docker running system ( or k8s interface ). Optimally portainer.
7. A user email notification system / CRM system for customers
8. An analytics platform / alerts system for logs
9. A system to kick off / track running ansible tasks ( ansible tower is kind of terrible though )
10. An LDAP server; minimal with UI management. Golang based preferably.
11. A static page ECM system
12. Dashboarding for status of all of above

I'm rambling here though. This stuff doesn't really belong in this issue. Just my random thoughts in response to being the first to try this and what I think would be awesome to see.

**Comment by xet7** [comment]
@nanoscopic 

Here's my comments to those:

> In my mind the following are necessary tools for any new startup:
>     1. A ticket tracking tool, or something more minimal such as trello. This is what led me to sandstorm.

Yes, I should really sometime fix Sandstorm Wekan bugs.

>     2. A git server ( gogs in sandstorm case should work )

In addition to gogs, there is already:
- GitLab (not up-to-date)
- GitWeb

Incomplete:
- incomplete port of [Fossil](https://fossil-scm.org) https://github.com/zenhack/sandstorm-fossil that is nowaday kitchen sink of version control, ticketing, forum, wiki, chat, etc. But I don't know is there any other login than password login.

>     3. A chat support/collaboration system

Currently:
- Wekan, if chatting in card comments
- SandChat
- RocketChat (not up-to-date)

Incomplete:
- Matrix

>     4. A CICD system

Currently:
- Maybe Wekan, with existing IFTTT Rules, if I would get Outgoing Webhooks+API working
- Sandstorm maybe has some cron like system

>     5. An artifact tracking system ( can do without in a pinch just using something built into CICD )

- If you mean file storage, maybe existing Davros?

>     6. A docker image server
>        6b. A docker running system ( or k8s interface ). Optimally portainer.

Incomplete:
- There has been some discussion, could Sandstorm apps be built and developed inside Sandstorm. Sandstorm grains have advantage, that they are in active use (loaded to RAM) only when someone using them, when instead Docker containers are always running.

>     7. A user email notification system / CRM system for customers

In future:
- Wekan will have user email notification system

>     8. An analytics platform / alerts system for logs

Currently:
- Piwik

>     9. A system to kick off / track running ansible tasks ( ansible tower is kind of terrible though )

In future maybe:
- Wekan?

>     10. An LDAP server; minimal with UI management. Golang based preferably.

I don't know do these work:
- https://github.com/glauth/glauth
- https://github.com/bradleypeabody/godap

>     11. A static page ECM system

Currently:
- WordPress generates static pages

>     12. Dashboarding for status of all of above

In future:
- Maybe Wekan? Cards from many boards can be linked to one dashboard board, and incoming info with Wekan REST API, if REST API is fixed.

> I'm rambling here though. This stuff doesn't really belong in this issue. Just my random thoughts in response to being the first to try this and what I think would be awesome to see.

Yes, me too rambling here :)

BR,
xet7
Maintainer of Wekan

**Comment by zenhack** [comment]
@nanoscopic, feel free to open separate issues about wishlist items; I can't guarantee we'll get to them in any particular time frame, but it's useful to have a ticket for them.

(Also, if your company is interested in paying for feature prioritization, feel free to get in touch with me by email).

**Comment by ocdtrekkie** [comment]
https://github.com/sandstorm-io/sandstorm/commit/adfe89afa581efbce5b38a6a8f9f261e1fa866c1 includes an update to the GoDaddy plugin, so this should be fixed with the latest release from yesterday.
