### ISSUE TITLE
Publishing Wekan to Experimental App Market does not work

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3516]
This spk works on my local sandstorm. But I can not publish new version to Experimental Sandstorm App Market:
```
~/repos/wekan$ spk publish wekan-5.23.spk 
talking to index server...
uploading package to index...
server returned error on upload: Error: expected n &gt;= minBytes [0 &gt;= 8]; Premature EOF
```

**Comment by zenhack** [comment]
Can someone check the grain log for the index? (@kentonv, @ocdtrekkie)

**Comment by xet7** [comment]
Because uploading does not work, I uploaded newest Wekan spk here:
https://releases.wekan.team/sandstorm/

I also added that link to https://github.com/wekan/wekan/wiki/Sandstorm

**Comment by xet7** [comment]
Now uploading works!
