### ISSUE TITLE
Sandstorm should probably opt servers out of FLoC

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3517]
We probably should defend our users, as much as possible, against hostile web browsers. GitHub Pages has already decided to automatically opt all users out of FLoC, and WordPress is discussing doing the same by default. https://github.com/WICG/floc

`Permissions-Policy: interest-cohort=()`

**Comment by zenhack** [comment]
Agree.

Need to figure out where the optimal place in the code is to add a header that applies to every request; I'm not seeing an obviously right thing in kj-http. I suppose we could create a wrapper `kj::Response` subclass and just do `.cloneShallow()` on the result headers, though I don't know if there's a simpler approach (@kentonv?)

**Comment by zenhack** [comment]
Opened a PR. Did basically the thing I described above.
