### ISSUE TITLE
WARNING: This server seems to have its WILDCARD_HOST misconfigured.

### ISSUE THREAD

**Issue by sHChypp** [sandstorm-io/sandstorm#3521]
Hi there.

I've just make a new install of Sandstorm, but i cannot open any grain.
When i opened admin panel i got information that:
_"WARNING: This server seems to have its WILDCARD_HOST misconfigured. Until you fix it, you will not be able to use any apps. You can read more info in the Sandstorm docs and in your browser's Javascript console. You'll need to adjust DNS, SSL/TLS certificates, or edit the sandstorm.conf file. If you see no information in the JS console, or wish to test if you have fixed the problem, reload this page to re-run the test. If you're still having problems, please file an issue."_

my sandstorm.conf:

![conf](https://user-images.githubusercontent.com/67791307/117033093-599e0480-ad02-11eb-92a6-411887caee5f.png)

I've made forwarder at my DNS server (Win srv 2k12):

![host](https://user-images.githubusercontent.com/67791307/117032577-e09ead00-ad01-11eb-84d8-c416b66f2a16.png)

and CNAME:

![wilcard](https://user-images.githubusercontent.com/67791307/117032634-eeecc900-ad01-11eb-84a6-6d2a9d43b852.png)

Still cannot run any app :/

**Comment by ocdtrekkie** [comment]
I would possibly try *.dit.rydygierkrakow.pl in the wildcard FQDN field. I'm not sure if Windows DNS supports multiple levels of wildcards, and your WILDCARD_HOST setting has the dit subdomain in it.

You can also test whether or not this is the problem:

`ping foo.dit.rydygierkrakow.pl` and see if it returns 192.168.3.59.

**Comment by sHChypp** [comment]
Whoaaa! Thanks for Your ultra-quick response!

![foo](https://user-images.githubusercontent.com/67791307/117034757-e9907e00-ad03-11eb-8ab5-4062b722b65d.png)

**Comment by ocdtrekkie** [comment]
Yeah, so if your CNAME was working, your ping would work.

I would definitely make sure the FQDN of your wildcard entry is *.dit.rydygierkrakow.pl and I would also maybe consider using an A record instead of a CNAME, and referring right back to the IP address.

**Comment by sHChypp** [comment]
Smth like that? 

![new_host](https://user-images.githubusercontent.com/67791307/117036742-0fb71d80-ad06-11eb-8d66-e215c2f68e24.png)

It made this:

![look](https://user-images.githubusercontent.com/67791307/117036832-22315700-ad06-11eb-92c1-46017bddbef5.png)

**Comment by ocdtrekkie** [comment]
That makes sense to me. Windows DNS does like folders. The important question is, does it fix your ability to ping foo.dit.rydygierkrakow.pl?

**Comment by sHChypp** [comment]
I give up, now replies one of our external adress ...

Is there any method to run Sandstorm without using our company domain?

**Comment by ocdtrekkie** [comment]
That's very strange! But basically, the only thing that should need to happen is both your base URL and a random subdomain of your wildcard host (we often use "foo" to test) resolve to the same IP address. Unfortunately, Sandstorm's security model doesn't operate without DNS, so there is no way to use plain IP addresses.

There are two options if you want to avoid using your own domain/DNS:

1. You can use a Sandcats subdomain (an option during install), which will auto-configure dynamic DNS and HTTPS support using Let's Encrypt. This requires your Sandstorm server be connected to the Internet.

2. You can use a service like xip.io that resolves IP addresses for pseudo-domain names. (Right now, xip.io isn't working for me, but sslip.io does, which is similar.) For instance, if you ping 192.168.3.59.sslip.io it will return 192.168.3.59. It will also return 192.168.3.59 if you ping foo.192.168.3.59.sslip.io, so it'll work for the wildcard host too. The upside is that while your DNS requests go out to the Internet, if it's an internal range, no actual traffic to the server in question does. The downside of course, is if the service goes offline (or decides to redirect all DNS requests elsewhere), you may have an issue in the future.

**Comment by sHChypp** [comment]
Let's try sslip.io. I don't want Sandcats , 'cause I don't want the service to be available from the outside.
Jacob, would you be nice and tell me what to do to use sslip.io?
Thank you very much for the help you are showing me. It's very nice.
By the way: are you Hungarian? Your surname is very Hungarian.

**Comment by sHChypp** [comment]
Yeah!
It's working :) I've changed only 2 lines in cfg and done :)
Jacob, thanks a lot for ur help (especially for sslip.io address!)

**Comment by ocdtrekkie** [comment]
Glad you got it working! I believe my name traces back to Austria or something in that general vicinity, but I'm not super genealogically inclined.

**Comment by ocdtrekkie** [comment]
Closing since you got it working, but feel free to reach out with any other questions or issues.
