### ISSUE TITLE
Documentation page is broken

### ISSUE THREAD

**Issue by neuroradiology** [sandstorm-io/sandstorm#3536]
The [documentation page relating to "How it Works"](https://docs.sandstorm.io/en/latest/using/how-it-works/) is broken.

It shows an error of 

`Error : a bytes-like object is required, not 'str' : ['dot', '-Tsvg']`

but the documentation source page on github [appears](https://github.com/sandstorm-io/sandstorm/edit/master/docs/using/how-it-works.md) and previews fine.

It looks like the problem relates to an image that was intended to be inserted between some {% %} tags.

![sandcats-documentation-error-screenshot_20210623_093931](https://user-images.githubusercontent.com/8550951/123126878-00e80f80-d407-11eb-9b20-bbe02709245a.png)

**Comment by zenhack** [comment]
Looks like  a Python 2 to 3 portability issue in the python library that's calling out to graphviz. I'd hazard a guess that just updating the versions that are installed in generate.sh would fix this, though I don't have time to fuss with it today.

**Comment by zenhack** [comment]
(Also, we should probably update the reference to proxy.js here; that file doesn't exist anymore since @kenotnv rewrote the gateway in C++)

**Comment by garrison** [comment]
This is https://github.com/sprin/markdown-inline-graphviz/issues/7.  Before realizing this, I tried updating mkdocs to the latest version (1.2.2), but that alone does not fix it.  There is no more recent release of markdown-inline-graphviz, but comments on that issue describe some workarounds.
