### ISSUE TITLE
Disallow grain service workers

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#3538]
Currently, the CSP policy (even the more restrictive one) does not disallow service workers. This may be a security problem; while discussing the webrtc stuff, it was pointed out that service workers can muck with response headers:

https://github.com/w3c/webrtc-extensions/pull/81#issuecomment-871563136

...so we probably need to block grains from installing service workers. I don't think any existing apps actually use service workers, and if they did they'd probably break a lot for the same reason local storage doesn't really work in Sandstorm, so I don't think there's a downside to getting rid of them.

This is a one-line patch; I'll find time for it soonish.

**Comment by ocdtrekkie** [comment]
There is part of me that really wants to figure out a way for Sandstorm to support apps written as PWAs, because that's... a lot of new web apps. But yeah, I imagine the ethereal nature of grain subdomains makes this a largely harmless change.

Presumably this won't apply to Sandstorm itself, just grains, since Sandstorm has a dummy service worker just to make it count as a "web app" to browsers.

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2021-06-30 14:36:25)

> There is part of me that really wants to figure out a way for
> Sandstorm to support apps written as PWAs, because that's... a lot of
> new web apps. But yeah, I imagine the ethereal nature of grain
> subdomains makes this a largely harmless change.

I have a sense that Sandstorm itself could handle a lot of the work on
this, and maybe we could find a way to provide controlled access to
service workers, e.g. set `worker-src https:worker-src.<wildcard-host>`,
and have trusted workers available from that subdomain for shared use by
grains. They could get pretty flexible through use of SES for
sandboxing. But that's down the line.

> Presumably this won't apply to Sandstorm itself, just grains, since
> Sandstorm has a dummy service worker just to make it count as a "web
> app" to browsers.

Correct.
