### ISSUE TITLE
GitHub Topics

### ISSUE THREAD

**Issue by garrison** [sandstorm-io/sandstorm#3557]
It would be nice to add some GitHub Topics to the Sandstorm repository, which I think might help it be discovered by people with interest in similar projects.  For instance,

- If Sandstorm were to be labeled with the [self-hosting](https://github.com/topics/self-hosting) Topic, it would be number 4 in the list (ordered by stars).
- If Sandstorm were to be labeled with the [self-hosted](https://github.com/topics/self-hosted) Topic, it would be number 8 or 9 in the list.
- If Sandstorm were to be labeled with the [decentralized](https://github.com/topics/decentralized) Topic, it would be number 9 in the list.
- If Sandstorm were to be labeled with the [seccomp](https://github.com/topics/seccomp) Topic, it would be number 2 in the list.
- If Sandstorm were to be labeled with the [capnproto](https://github.com/topics/capnproto) Topic, it would be at the top of the list. :-)

Looking at the other projects in those lists could give an idea of other Topics that might make sense.

**Comment by zenhack** [comment]
As a note, the spellings `capnp` and `capn-proto` seem to also be in use.

**Comment by garrison** [comment]
Might as well be at the top of the list for [sandstorm](https://github.com/topics/sandstorm), too.  I wondered if there is an existing topic called [indie-web](https://github.com/topics/indie-web), but there is not.  [webapp](https://github.com/topics/webapp) seems to make sense, and [webdev](https://github.com/topics/webdev) might fit.

Also, another action item is to [submit pull requests](https://github.com/github/explore/blob/main/CONTRIBUTING.md) to curate the sandstorm and capnproto topics.  One of the fields is `aliases`, so this is probably where the different spellings ought to be handled.

**Comment by zenhack** [comment]
@ocdtrekkie, do you have the necessary permissions to add some of these? Seems like an easy thing to just do and close out.

**Comment by ocdtrekkie** [comment]
I have push access to the repo, but I have absolutely no access to settings, stuff like topics is outside my access level (despite the fact it's far more trivial than push access when you think about it...)

**Comment by zenhack** [comment]
So I guess options then are:

1. Bother Kenton.
2. Close and don't bother.

Opinions? I have a hard time having a strong opinion about this kind of stuff, just trying to prune the issue tracker a bit.

**Comment by ocdtrekkie** [comment]
It is far from the top item on my list, but I think it'd be nice. A lot of self-hosting platforms are getting a lot of new interest and GitHub is, of course, regularly playing with new ways to surface relevant projects to people's home feed.

So if we want to clean up the issue, that means I vote "bug @kentonv", I guess?

**Comment by ocdtrekkie** [comment]
I have the ability to resolve this now, so I did.
