### ISSUE TITLE
Cannot build on Fedora 34

### ISSUE THREAD

**Issue by garrison** [sandstorm-io/sandstorm#3565]
I've been unable to get Sandstorm to build on Fedora 34.  I've created [a minimal Dockerfile to demonstrate the failure](https://gist.github.com/garrison/f025090ce914641f0d1e492612dcbd4e#file-dockerfile-fedora), as I mentioned in #3564.  If I [increase the log output](https://groups.google.com/g/sandstorm-dev/c/ARrmLkmWJcw/m/Em91iRE0DAAJ) and build, everything is successful until

```
✘ link: sandstorm/run-bundle.o
✘ install: sandstorm/sandstorm.ekam-manifest
✘ link: sandstorm/sandstorm-http-bridge.o
✘ link: sandstorm/test-app/test-app.o
    /usr/bin/ld: cannot find -lz
make: *** [Makefile:268: tmp/.ekam-run] Error 1
```

despite both `zlib` and `zlib-devel` being installed.

**Comment by zenhack** [comment]
Interesting. I'm able to reproduce this with vagrant using generic/fedora34, though note that the additional packages you install in the `Dockerfile` beyond don't appear to be necessary to get that far.

As a side note, we should probably change the docs to run dnf with sudo and not do the meteor bit as root, per your comments in the Dockerfile.

I can confirm that passing `-lz` to the compiler (both system compiler and the one we pull in) on a dummy program does successfully link agains libz without incident.

It is interesting that all of the other executables link just fine with the same flags...

**Comment by kentonv** [comment]
Might this have something to do with static vs. dynamic linking? When linking a static binary, `-lz` will look for `libz.a` instead of `libz.so`, which perhaps Fedora doesn't provide due to some sort of philosophical objection to static linking...

**Comment by zenhack** [comment]
Good thought -- looks like fedora splits static libs into separate
packages, so libz.a is in the package `zlib-static`.

Quoting Kenton Varda (2021-09-18 22:51:30)
