### ISSUE TITLE
new installation error(stack in Create admin account)

### ISSUE THREAD

**Issue by la0wei** [sandstorm-io/sandstorm#3607]
debian 11 x64
install by curl https://install.sandstorm.io | bash
stack in Create admin account like this
![stack](https://user-images.githubusercontent.com/3761308/152743774-77ecec6b-74c8-4aed-9e9e-ae1523848de3.PNG)
[sandstorm.log](https://github.com/sandstorm-io/sandstorm/files/8013156/sandstorm.log)

**Comment by zenhack** [comment]
Can you describe the problem in more detail? What exactly is happening, how are you triggering it, and what do you expect to happen instead?

**Comment by la0wei** [comment]
> Can you describe the problem in more detail? What exactly is happening, how are you triggering it, and what do you expect to happen instead?

after install by curl https://install.sandstorm.io/ | bash in terminal.
It shows a  link like  https://xxxxx.sandcats.io/setup/token/54a30c71484036e90c454593f68cc5b65e080506
I just followed the procedure choosed github auth.
when it goes to **Admin account** this step,click "with Github" icon,login and auth.
then nothing happens,still stay in this page.
[sandstorm.log](https://github.com/sandstorm-io/sandstorm/files/8013156/sandstorm.log) log is here.

**Comment by la0wei** [comment]
![1](https://user-images.githubusercontent.com/3761308/152934087-4bc61f37-2e33-48a3-93e3-77f6bb4a2fe5.png)
![2](https://user-images.githubusercontent.com/3761308/152934090-af07d6a3-4773-4ba5-8f5a-f885b5f3c1b8.png)
![3](https://user-images.githubusercontent.com/3761308/152934093-65a7f633-1c20-4210-93ca-7cfad412e5c6.png)
![4](https://user-images.githubusercontent.com/3761308/152934094-8d994810-1bb7-478e-845a-15872103db2b.png)

**Comment by ocdtrekkie** [comment]
It looks like you selected "Disallow collaboration with users outside the organization". This setting works with LDAP or SAML login integration, and serves to disable Google/GitHub/etc. logins from working.

**Comment by la0wei** [comment]
> It looks like you selected "Disallow collaboration with users outside the organization". This setting works with LDAP or SAML login integration, and serves to disable Google/GitHub/etc. logins from working.

YES! cancel this make it work!
I thouht it only associated whith sharing.
I took it for granted that doing that will  get more privacy,so I intentionally to check this out.
Thanks  to @zenhack @ocdtrekkie

**Comment by ocdtrekkie** [comment]
Happy to help, thanks for providing screenshots to help identify the issue. I am going to close the issue but feel free to ask us any other questions that come up!

**Comment by zenhack** [comment]
Probably that section of the UI should just be disabled if there isn't anything configured for organization membership. I'll open a separate issue for that.
