### ISSUE TITLE
Access - Unauthorized! :(

### ISSUE THREAD

**Issue by Bechaker** [sandstorm-io/sandstorm#3617]
This is a private Sandstorm server. In order to install apps, you need to be invited by the admin. The admin can invite you from the admin panel.
Can you authorize me access to use the platform?

**Comment by ocdtrekkie** [comment]
This is the support site for the software itself. I assume you are trying to connect to someone's Sandstorm server? Do you know who runs the server you are trying to use?

**Comment by ocdtrekkie** [comment]
Going to close this one for lack of response. My best guess is that they tried the demo and hence want access to Alpha, but Alpha is not intended for public use.
