### ISSUE TITLE
Feature: Styling/color for offer templates

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3646]
In my case, my application has a preferred dark mode styling, but is intended to be flexible. I'd like my offer templates to look right, but they don't. I tried including style information in the template variable, I tried adding the styling to the iframe, etc. But I can't get the offer template text to be anything but black text. I'm forced to put them in a white box, which isn't my favorite thing.

**Comment by zenhack** [comment]
We probably don't want to go all-in on allowing apps to style the offer iframes, just because there are plenty of ways to inject arbitrary js via css, which defeats the point of splitting it off into an iframe. But we could maybe add a couple options for common use cases.

**Comment by ocdtrekkie** [comment]
I think the big one would be to be able to provide a text color. The iframe will already let me style the background of the frame, but at present, that leaves me with black text on a black background. I think if we could tell Sandstorm the offer template should use a given text/copy icon color, it would blend well with nearly any app styling.
