### ISSUE TITLE
Show a grain's app name in the "My Files" list

### ISSUE THREAD

**Issue by ar-jan** [sandstorm-io/sandstorm#365]
When you view the My Files list you could have multiple grains with the same or similar names from different apps. The My files list would be more useful with a column for the app name, so you don't have to navigate to the specific app's list to find the correct grain.

**Comment by ocdtrekkie** [comment]
My inclination (and this is on my wish list) is that Sandstorm should add an app icon, kinda like a filetype icon on a desktop PC. Actually describing the full name of the app in a column would be pretty wasteful of space and look poor in the long-term.

**Comment by ar-jan** [comment]
Ah, that would be even better, yes.

**Comment by kentonv** [comment]
We should add icons, but icon art tends to be something open source hobbyist developers are not great at, so I'm not sure how much we can rely on it. An app name column doesn't seem like a bad idea (when there's room for it -- we drop unnecessary columns on mobile).

Hmm, for the "shared with me" tab this gets tricky though: we currently don't reveal *other people*'s app names, and it's conceivable that someone might not really want their app names being revealed to others, e.g. if they are running a forked version of an app that they've renamed to distinguish it to themselves, but they want other people to think it's the same app. Maybe that's a silly thing to worry about, though?

**Comment by paulproteus** [comment]
If people secretly fork an app to masquerade as a well-known app, I think
it's sensible to say they ought to also rig the name to look like the
well-known app. : P

Which is to say, if you're intentionally sharing an app instance with
someone, I lean toward it being OK to reveal the app name. We can document
these sorts of information leaks somewhere.

I'm open to other thoughts.

**Comment by zarvox** [comment]
In the new grainlist UI, we have app icons, and these show the app title on hover.  Additionally, the filter-search will also search in app titles.

Do you think we can close this issue, now that we have these additional affordances?

**Comment by ar-jan** [comment]
Yes, this fixes the issue. (Only thing for now is that several apps don't yet have their own logo and app title).
