### ISSUE TITLE
Can't login to self-hosted sandstorm using GitHub with Chrome iOS

### ISSUE THREAD

**Issue by phildini** [sandstorm-io/sandstorm#366]
I have a self-hosted sandstorm server (I can post the link or logs if desired)

The only authentication scheme I have enabled is Github. If I try to login to Sandstorm on Chrome for iOS, I get redirected to the Github login, login to github, and get redirected back with no state change. That is, the login dropdown is still popped open and I am not logged in to the server. No visible error is given.

The login flow works fine on mobile safari.

**Comment by dwrensha** [comment]
I confirm that I see the same behavior with Chrome/iOS both on my self-hosted server and on the alpha server. Logging in as a demo user does work, however.

**Comment by paulproteus** [comment]
Oh my. Thanks for reporting this.​

**Comment by paulproteus** [comment]
I was hoping we could use this <https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging> for debugging Chrome on iOS, but they only support desktop Chrome at the moment, unless the docs are out of date.

Does Chrome on iOS have any way to see anything resembling debug logs? I wonder if it's blocking some redirect URL from GitHub that's too long, or something like that.

**Comment by phildini** [comment]
One option is to run through a proxy, so you can at least see the traffic? There's also some great ideas here: https://css-tricks.com/using-chrome-devtools-to-debug-javascript-in-any-browser-with-ghostlab-2

**Comment by dwrensha** [comment]
I can no longer reproduce this problem. I think it may have been fixed in #354, which switched our login style from "popup" to "redirect".

**Comment by kentonv** [comment]
Yes, I think switching the login mode should have fixed this.
