### ISSUE TITLE
Internal Server Error when requesting email token to log in

### ISSUE THREAD

**Issue by fvlasie** [sandstorm-io/sandstorm#3660]
Everything was working then suddenly I am getting an internal server error when trying to authenticate with email.

**Comment by fvlasie** [comment]
Error while trying to send test email: {"errno":-111,"code":"ECONNECTION","syscall":"connect","address":"172.105.212.147","port":587,"command":"CONN"} [other-email-sending-error]

**Comment by ocdtrekkie** [comment]
I'm reasonably confident we haven't made any changes that should break sending mail... Hmm... Do you know of any recent changes or issues with your SMTP server or service?

**Comment by fvlasie** [comment]
Hello Jacob! It is working everywhere else...let me check the postfix logs to see if anything pops up...

**Comment by fvlasie** [comment]
Postfix says that SASL PLAIN authentication failed: `Sep  5 11:16:03 mail postfix/submission/smtpd[20448]: warning: unknown[132.226.124.184]: SASL PLAIN authentication failed: 
Sep  5 11:16:03 mail postfix/submission/smtpd[20448]: lost connection after AUTH from unknown[132.226.124.184]
Sep  5 11:16:03 mail postfix/submission/smtpd[20448]: disconnect from unknown[132.226.124.184] ehlo=2 starttls=1 auth=0/1 commands=3/4
`

**Comment by ocdtrekkie** [comment]
Did you figure it out? What was it?

**Comment by fvlasie** [comment]
It was the mail server and not Sandstorm's problem.
