### ISSUE TITLE
How to extract key for one app from sandstorm-keyring

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#367]
I have build several test apps one one machine. Now the sandstorm-keyring file has several keys. How can I separate them to keep them save app by app?

**Comment by ocdtrekkie** [comment]
From the wiki: "To pull specific keys out of your keyring to send to people, use the `spk getkey` command (type `spk help getkey` for usage information)."

**Comment by JamborJan** [comment]
RTFM, sorry for bothering ...

**Comment by ocdtrekkie** [comment]
No problem. I wouldn't know if it wasn't for my need for that specific info nugget once. :D
