### ISSUE TITLE
Questionable Idea: Package Patching

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3672]
Okay... so I don't know if this is feasible, a good idea, a bad idea, or a travesty against the platform design. This is kinda a "just for discussion" concept:

We have features pending like a new CSP and a new seccomp filter, both of which have the possibility to break apps, and we're likely to have security changes which break apps in the future. This can be irritating because our packages usually don't require frequent maintenance, and many "abandoned" packages are still used. Old packages can also be hard to reproduce, and in one instance, we kinda hacked in a modification to an existing build (ShareLatex) rather than rebuilding it. And often, the fix needed to say, not load an external script, might be very, very small.

Previous discussion has talked about special-casing app IDs and allowing them to continue using old functionality, but since Sandstorm is a security platform, that often means leaving large security holes in the name of backwards compatibility, which I believe is probably unwise.

I was wondering if in cases where we are shipping breakage to an app package but the fix is minimal/a single file even, we should consider _shipping the fix in Sandstorm itself_ to be applied to the app package on Sandstorm update, as well as when installing the package going forwards. My understanding is we unpack apps after we verify their signature, so presumably the platform could then modify them if needed?

If this wasn't an obscene idea, I would imagine it would only apply to the most recent packageId in the app market, where it was nontrivial to have the author publish a patched version themselves, and wasn't really worth doing the whole key replacement process and taking over ownership of the app entirely. We could remove the patch from Sandstorm if/when the original author submitted an updated package. Since like app replacement keys, this would involve deploying a Sandstorm update, use of this feature would entail a PR and likely be documented in the Sandstorm changelog, providing accountability as to what's being done.

A good example of a fix we could apply today if we had a feature like this is #3128. Shipping a single modified template file for this package would remove GA, and the author of the package is very unlikely to address this themselves any time soon. (Of course, the new CSP will fix it too.)

**Comment by zenhack** [comment]
I think this a bad idea.

I expect the set of changes we will make to the app platform that will actually break things will be very very small -- hopefully *just* the CSP change; once our sandboxing is actually where it theoretically should be, there shouldn't be a strong reason to break backwards compatibility -- certainly not often enough to built out mechanisms to support monkeypatching apps.

I think doing what we did with ShareLaTeX is reasonable given that scope.

And yeah, for the contact otter GA thing, the new CSP just does what we want there.

**Comment by ocdtrekkie** [comment]
> I think this a bad idea.

Okay! I don't have a strong view on it, and I am not surprised, but figured I should ask/pose the thought.

I am not sure how often something will come up that justifies breakage once we've reached the target sandboxing level, but I definitely would like to avoid future ones languishing as long as the new CSP has. I probably should put some renewed modern effort into trying to move the needle on some app updates which would let us finally move forward on it.
