### ISSUE TITLE
Error reinstalling sandstorm

### ISSUE THREAD

**Issue by enricodetoma** [sandstorm-io/sandstorm#3673]
I'm trying to reinstall Sandstorm on a new server.
I used to recovery procedure for my `sandcats.io` subdomain, but I get this error:

```
ERROR: connect(): No such file or directory; address = unix:/opt/sandstorm/var/sandstorm/socket/shell-cli
There might be more information in: /opt/sandstorm/var/log/sandstorm.log
*** INSTALLATION FAILED ***

Failed to create Let's Encrypt account.
```

In `/opt/sandstorm/var/log/sandstorm.log` this is the error:

```
** Starting Sandstorm at: Sun Oct 30 12:04:38 2022
*** Uncaught exception ***
sandstorm/run-bundle.c++:1874: failed: bind(sockFd, reinterpret_cast<sockaddr *>(&sa), sizeof(sockaddr_in)): Address already in use
stack: 632ac4 631225 6301ff 62f9dc 496b97 496751

```

My machine is Ubuntu Jammy 22.04.
During the installation I chose port 6080 because ports 80 and 443 are already in use.

**Comment by ocdtrekkie** [comment]
Sandstorm can be set to run on other ports, but it's definitely failing to start because ports it is configured to use are already in use. Assuming nothing else went wrong, you might be able to set different ports in the config file and then "sudo sandstorm start".

https://docs.sandstorm.io/en/latest/administering/config-file/

**Comment by enricodetoma** [comment]
After stopping Apache2 it went a bit further, but now the error is:

```
ERROR: remote exception: Error: [acme-v2] ********.sandcats.io status:400 Unable to update challenge :: authorization must be pending
    at transformError (/programs/server/npm/node_modules/@root/acme/acme.js:826:10)
    at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
There might be more information in: /opt/sandstorm/var/log/sandstorm.log
*** INSTALLATION FAILED ***

Failed to fetch certificate.
```

And this error is in the log:

`sandstorm/gateway.c++:1029: error: refused HTTPS connection because no TLS keys are configured
`

**Comment by ocdtrekkie** [comment]
Hmmm, so my guess is the installer failed out before setting up Let's Encrypt. Our documentation for this is... not ideal, only under `sandstorm --help`. But I think you can run `sudo sandstorm create-acme-account <email>` and then maybe `sudo sandstorm restart`?

I think you have Sandstorm installed at this point, but you have issues from the incomplete install on the first attempt maybe.

**Comment by enricodetoma** [comment]
@ocdtrekkie thank you for your support. I tried the installation again today and this time it worked, so I didn't even need to do `sudo sandstorm create-acme-account <email>` manually.

**Comment by ocdtrekkie** [comment]
Awesome to hear! Feel free to reach out if you have any other questions or issues!
