### ISSUE TITLE
Can't turn off app updates in App Sources panel

### ISSUE THREAD

**Issue by jdougan** [sandstorm-io/sandstorm#3681]
I go into the Admin /  App sources page, untick the checkbox, hit save. It reports it has saved, then I go beck up to Admin, back down to App Sources, and the change is reverted.

**Comment by zenhack** [comment]
Thanks for the report. I opened #3682 which fixes this.

**Comment by jdougan** [comment]
Is there any way to turn off both app and sandstorm updates manually? I want to stick with 305 temporarily while I'm troubleshooting.

**Comment by ocdtrekkie** [comment]
In sandstorm.conf, you can change the update channel from dev to none (then restart Sandstorm), and for apps, probably set the app index to something invalid.
