### ISSUE TITLE
Anything important worth saving at Google Groups?

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3691]
Hi,
is there anything important worth saving at Google Groups https://groups.google.com/g/sandstorm-dev ?

It seems that it could disappear sometime:

https://ahelwer.ca/post/2023-03-08-google-groups/

https://news.ycombinator.com/item?id=35070618

**Comment by ocdtrekkie** [comment]
Google Groups doesn't have a deprecation date, I think we are fine for now. I would absolutely like to dump it in the future, but it also currently is a good resource for us. I'd really like if GitHub Discussions could adopt mailing list-like capability someday so we can condense our infrastructure, but I doubt they want to do that.

Ideally someday we will have a Sandstorm-hosted infrastructure stack that includes code hosting, the mailing list, etc.

**Comment by jdougan** [comment]
Given how flaky Alphabet/Google can be about keeping stuff running, I hope there is some plan for doing running backups or something.

**Comment by ocdtrekkie** [comment]
I'm not sure there's a ton of really valuable knowledge in the list. It's helpful for asking questions or distributing updates, but I'd say the majority of our "organizational knowledge" exists in GitHub issues. Hopefully if they do announce a deprecation policy though, they will also include advise for migrating archives out.

**Comment by zenhack** [comment]
Worst case, I don't tend to delete my email and am subscribed, so can just fish out the raw mail files. I think most people use Google Groups in mailing list mode anyway (I forget there's a web interface sometimes).
