### ISSUE TITLE
When using "appdemo" functionality, give users a clear path to run the app on their own server

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#370]
When users visit a link like:

https://demo.sandstorm.io/appdemo/qkgkaxfqhgsff8zgx2f4nf1a8xvmpte6wa19egmfkk06mzt7e8dh

(to try Let's Chat)

it'd be nice to have a call-to-action somewhere to help them run the app on their own server, on a Sandstorm instance they run themselves.

To achieve that, I propose the text:

`Run this app on your own server`

at in the top bar, which is slightly long, but I think that's OK, and then

when you click it, it takes you to a "Install Sandstorm with this app pre-installed" flow.

**Comment by jparyani** [comment]
Fixed by #411
