### ISSUE TITLE
sandstorm.conf for non-standard TLD?

### ISSUE THREAD

**Issue by Orv** [sandstorm-io/sandstorm#3702]
I'm a ham radio operator, and I'm trying to install Sandstorm on our RF-based IP network, which uses the domain .local.mesh.   The Sandstorm configurator is objecting to my WILDCARD_HOST.  Here's the contents.  Any suggestions for getting past this?
Thanks.

```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://w6bi-qth-srv.local.mesh:6080
WILDCARD_HOST=*.w6bi-qth-srv.local.mesh:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=30025
```

**Comment by ocdtrekkie** [comment]
What do you mean by objecting to your wildcard host? It looks okay to me. The important test is if your DNS is actually set up to support the wildcard. If you ping an arbitrary subdomain that should match the wildcard, does it return the same IP as the base URL?

**Comment by ocdtrekkie** [comment]
(As an aside, this network sounds really cool. I'm excited to see Sandstorm continuing to be used in neat ways!)

**Comment by Orv** [comment]
This is the error I'm getting:
![image](https://github.com/sandstorm-io/sandstorm/assets/1124405/3f8d80c5-d905-4381-9579-4246acf9b2d4)

BTW, if you'd like to to see our SoCal network, this is an mirrored version of the mapper: https://socalmap.xojs.org/

**Comment by ocdtrekkie** [comment]
Yeah I think the big question is just if doing a lookup on foo.w6bi-qth-srv.local.mesh returns the server's IP address. If not apps and static content things like app icons and stuff all won't show correctly.

**Comment by Orv** [comment]
The software we use is derived from OpenWrt and uses OLSR.  It doesn't support wildcard DNS records.  The senior AREDN dev (arednmesh.org) is going to look into adding that support.  I'll close this ticket as it's our problem not, Sandstorm's.
Thanks for the feedback!

**Comment by ocdtrekkie** [comment]
Always happy to help. I hope it's possible to get it working, because mesh-networked private app platform sounds insanely cool.
