### ISSUE TITLE
I used  HTTPS-verified install, But open site ,it is blank? 

### ISSUE THREAD

**Issue by azwhale** [sandstorm-io/sandstorm#3703]
![1698825057170](https://github.com/sandstorm-io/sandstorm/assets/147499298/b4cc987c-24bb-44e4-a099-c54c64088753)

**Comment by ocdtrekkie** [comment]
Do you have other services running on the same box? The nginx error message suggests your port 443 is going to a different web server.

**Comment by azwhale** [comment]
![1698827403788](https://github.com/sandstorm-io/sandstorm/assets/147499298/a6ab90e2-a351-4cce-bb5f-d952717cb40d)  443 and 80 port  is running sandstorm

**Comment by ocdtrekkie** [comment]
Okay, that looks right on the server to me, is there anything like a router or firewall which might need to open or pass through port 443 from the Internet?

Sandstorm doesn't use Nginx, so somehow port 443 on your public IP (which you should see when you lookup your sandcats subdomain) is getting routed to something else.

**Comment by azwhale** [comment]
![image](https://github.com/sandstorm-io/sandstorm/assets/147499298/1935570d-041d-438b-8ae0-a00d90e16443)
![image](https://github.com/sandstorm-io/sandstorm/assets/147499298/b2ccfc46-699d-4500-b99f-bfa7d7f3446a)
It seems like there is a routing configuration error on the server.

**Comment by azwhale** [comment]
I installed it on my local virtual machine.
