### ISSUE TITLE
Sandstorm Apps icons are not visible

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3714]
Hi,
Sandstorm Apps icons are not visible at my Debian 12 amd64 server. Does someone know why?

![sandstorm-no-icons](https://github.com/user-attachments/assets/3247a04c-e2fe-4fd8-9244-053a7177cfed)

**Comment by xet7** [comment]
This happens both at Firefox Nightly and Chromium browsers.

**Comment by xet7** [comment]
This happens only when Sandstorm is installed to hosting use behind Dynamic DNS of FreeDNS of Namecheap, Caddy proxying with from Ubuntu 24.04 to internal KVM VM where Debian 12 is running, some kind of Let's Encrypt SSL/TLS error at browser inspect network. This does not happen when installing Sandstorm to other VM for development use.

![sandstorm-ssl-alert](https://github.com/user-attachments/assets/70268131-ee7a-4bba-ac01-4a14ab66f598)

**Comment by xet7** [comment]
Because it complained about static subdomain, I added `*.static` and `static` subdomains to have CNAME to same server domain. I also added those to Caddy. I'll check does this help.

**Comment by xet7** [comment]
Ok, that fixed it. Now it works.

**Comment by ocdtrekkie** [comment]
This sounds like your wildcard DNS isn't working. If the icons won't load, it is unlikely grains will either.

**Comment by xet7** [comment]
@ocdtrekkie 

Yes, it looks like wildcard DNS is not working at FreeDNS of Namecheap. So I changed back to CloudFlare DNS, and will make some script to update IP address.

**Comment by Dycool** [comment]
Im facing the same issue, Im using caddy too and a domain I bought from spaceship.com.

**Comment by ocdtrekkie** [comment]
@Dycool How do you have your DNS wildcard set?

**Comment by Dycool** [comment]
Caddy doesn't automatically configure ssl for wildcard domains so that's what I'm figuring out right now.

**Comment by xet7** [comment]
For me, it works at CloudFlareDNS using TLS Strict checking with Origin certificate, that is at /etc/caddy/certs/example.com.pem with above private key and below cert.

DNS records:
```
* A example.com ip-address
@ A example.com ip-address
```
Caddyfile, proxy to KVM VM that is running Debian and Sandstorm:
```
*.example.com example.com {
        tls {
                load /etc/caddy/certs
                alpn http/1.1
        }

        reverse_proxy 123.123.123.123:80
}
```
At /opt/sandstorm/sandstorm.conf is domain, http port etc.

Some related info at:

https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

I also had to wait that Origin Cert certificate becomes active.

But this worked for me only at CloudFlare. It did not work at FreeDNS of Namecheap.

Also, I still need to write script to fix IP address if Dynamic DNS IP address changes, using CloudFlare API, because my cable modem does not have DDNS option for CloudFlare.

**Comment by xet7** [comment]
Now that there is also a way to run Sandstorm at Ubuntu, it would be possible for me to move Sandstorm from KVM VM to run directly at host, without VM, and proxy from Caddy to localhost port of Sandstorm.

https://groups.google.com/g/sandstorm-dev/c/4JFhr7B7QZU?pli=1

**Comment by Dycool** [comment]
I managed to fix the wildcard ssl and its working properly now, however now I have a 502 error everytime I open any grain, which I believe it might be because I have ubuntu 24.04

**Comment by ocdtrekkie** [comment]
@Dycool This is from a user on our mailing list:

At startup I got a lot of errors and saw "Permission denied; name = /proc/self/setgroups"

I found this (run as root):

echo "kernel.apparmor_restrict_unprivileged_userns = 0" >/etc/sysctl.d/99-userns.conf
sysctl --system

And I ran it and restarted the Sandstorm service, everything seemed to work fine.
