### ISSUE TITLE
run-bundle should sanity-check sandcats key permissions

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#372]
Per #368, some installs may have the wrong permissions for Sandcats keys.

This issue tracks doing the work of adjusting `run-bundle` to do similar chown-ing, to fix installs in place.

**Comment by kentonv** [comment]
There's some similar chown/chmod fixing at the top of `runUpdateMonitor()`, FWIW.

**Comment by paulproteus** [comment]
Hi @zarvox - look at this!
