### ISSUE TITLE
curl https://install.sandstorm.io | bash fails even when run as root

### ISSUE THREAD

**Issue by mattl** [sandstorm-io/sandstorm#377]
Hey, trying to install Sandstorm and package up some of my apps (GNU social and GNU FM) after seeing @paulproteus post on HN.

	$ sudo curl https://install.sandstorm.io | bash
	[sudo] password for mattl: 
	% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Dload  Upload   Total   Spent    Left  Speed
	100 43511  100 43511    0     0  18425      0  0:00:02  0:00:02 --:--:-- 18421
	Sandstorm requires sysctl kernel.unprivileged_userns_clone to be enabled.
	Currently, it is not enabled on your system.
	Shall I enable it for you? [yes] yes
	bash: line 266: /etc/sysctl.conf: Permission denied

	~# curl https://install.sandstorm.io | bash
	% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Dload  Upload   Total   Spent    Left  Speed
	100 43511  100 43511    0     0  11272      0  0:00:03  0:00:03 --:--:-- 11272
	Sandstorm requires sysctl kernel.unprivileged_userns_clone to be enabled.
	Currently, it is not enabled on your system.
	Shall I enable it for you? [yes] 
	kernel.unprivileged_userns_clone = 1
	bash: line 273: command manually inside your host and update /etc/sysctl.conf.: No such file or directory

I'm on Debian Jessie amd64 and I do have an /etc/sysctl.conf file

**Comment by dwrensha** [comment]
Looks like there's a typo in the install script. Line 272 should end in a "\".

**Comment by jparyani** [comment]
I've fixed the typo in #379.

That line only should fail if `sysctl -w kernel.unprivileged_userns_clone=1` fails. Can you try running that as root, and let us know the output?

**Comment by mattl** [comment]
# sysctl -w kernel.unprivileged_userns_clone=1 
    kernel.unprivileged_userns_clone = 1

Ran the script again and it worked. I have a server running locally. Thanks

**Comment by zarvox** [comment]
Closing, since this seems to be fixed now.
