### ISSUE TITLE
email token login fails if MAIL_URL is not set, even if db.settings.smtpUrl is set

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#382]
accounts-email-token/token_server.js calls `Email.send()`, which relies on the environment variable `MAIL_URL` being set. It looks like it's completely unaware of `db.settings.smtpUrl`, which should be the authoritative place to set the outgoing email URL.

**Comment by ocdtrekkie** [comment]
So currently one feature uses this info stored in the database and one feature uses this info stored in the config file? Is there a reason a database entry would be preferable to the conf file?

**Comment by dwrensha** [comment]
Yes. The database entry is preferable because it can be easily edited from the admin tab of the Sandstorm shell.

**Comment by jparyani** [comment]
I'm actually not sure how to fix this without re-implementing the Email package inside of accounts-email-token or making accounts-email-token lookup Sandstorm specific database entries (defeating the purpose of making it a generic accounts package). Any ideas?

**Comment by ocdtrekkie** [comment]
I mean, from most website systems I may deal with, generally if I have to move web addresses or something, the best apps let me edit all of that in one config file. (Not that Sandstorm should need to be "moved", so much as "set up somewhere else and have grains migrated".)

Can the database setting update the conf file when it's changed?

**Comment by dwrensha** [comment]
Maybe we can figure something out here, but if using db.settings.smtpUrl for email token login is not feasible, then I'm in favor of ditching db.settings.smtpUrl.

**Comment by jparyani** [comment]
I'm actually leaning towards forking Meteor's Email package and adding a method like `updateMailUrl`. That would solve most of our problems, and centralize how we deal with email (although drivers/mail.js isn't long for this world anyways).

**Comment by kentonv** [comment]
Can accounts-email-token have a setMailUrl() method that Sandstorm core calls?

Can Sandstorm core simply update the environment variable, or does the package make a copy of it early on?

**Comment by jparyani** [comment]
The Email package lazily creates an SMTP connection pool. Once it's sent an email, it's currently impossible to switch to a different MAIL_URL.

My current best plan is to fork the Email package into sandstorm-email, and use that wherever we currently need to use email (currently just drivers/mail.js and accounts-email). This would also require us to inject the email package with something like a `setEmailPackage` method in accounts-email-token if we want it to keep it not reliant on Sandstorm specific code.
