### ISSUE TITLE
sharing: enter key pressed in label field does not create share url

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#383]
Steps to reproduce:

* Click large blue Share button.
* Click in "Label:" box
* Type a label
* Press enter

I'd expect pressing enter here to "submit" the form and cause a link to be created, but instead it does nothing and I have to shift focus to the "Create" button (e.g. with the tab key) to actually create a link.

**Comment by kpreid** [comment]
Generic kibitzing: Please do this by making it a proper `<form>`, not by adding keypress handlers for Enter!
