### ISSUE TITLE
Icons are blurry on 'retina' phone screens

### ISSUE THREAD

**Issue by trstnthms** [sandstorm-io/sandstorm#384]
The icons (menu, share, delete etc.) are blurry on an iPhone 5S. It looks like they are 32px x 32px - for retina screens, they would need to be at least 64px x 64px, if not bigger. A better option might be replacing them with SVGs or with an icon font.

**Comment by dwrensha** [comment]
Since https://github.com/sandstorm-io/sandstorm/commit/f9e5db8a488502bcf10a7d0b5cba7bcab75c6307 we are using vector graphics everywhere.
