### ISSUE TITLE
Unable to access localhost:6080 on my local sandstorm instance

### ISSUE THREAD

**Issue by snakemouse3d** [sandstorm-io/sandstorm#388]
i have installed sandstorm on my local pc running Ubuntu 14.04 and followed "The Easy way setup method".
Here is my config:

SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=127.0.0.1:6080
WILDCARD_HOST=*.127.0.0.1:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false

The installation was successful but i coundn't access the link "localhost:6080/admin/{session-key}" that was printed on the Terminal.
do i need to config something else to install apps on my local instance?

**Comment by ocdtrekkie** [comment]
I think your BASE_URL and WILDCARD_HOST should actually use "localhost" rather than an IP address. Because you can't have subdomains for an IP address. If I was on my other machine, I'd tell you how mine is currently set.

**Comment by snakemouse3d** [comment]
Hi @ocdtrekkie : i changed ip address "127.0.0.1" to "localhost" but everything is still the same.
My new sandstorm config file:

SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=localhost:6080
WILDCARD_HOST=*.localhost:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false

Do you have any other idea?

**Comment by dwrensha** [comment]
I suspect the main problem is that `BASE_URL` needs to include the protocol. Does it work if you use the following values?

```
BASE_URL=http://localhost:6080
WILDCARD_HOST=*.local.sandstorm.io:6080
```

If it still doesn't work after you run `sudo sandstorm restart` with these values, you may want to look in /opt/sandstorm/var/log/sandstorm.log to see whether any error messages are showing mup.

**Comment by ocdtrekkie** [comment]
My WILDCARD_HOST also includes http:// before the *.local.sandstorm.io bit FWIW. And my BIND_IP is 127.0.0.1 which may work if you have no intention of outside access, I think.

**Comment by ocdtrekkie** [comment]
Actually, mine doesn't work currently, so ignore my comment. I will tinker with my install in an hour.

**Comment by snakemouse3d** [comment]
@dwrensha @ocdtrekkie : thanks you two. It's working fine :dancers:

**Comment by paulproteus** [comment]
I'll happily mark this as closed. Many thanks to @ocdtrekkie and @dwrensha helping out!

@snakemouse3d if you're willing to write a blog post about _anything at all_ related to your enjoyment (or non-enjoyment) of Sandstorm, we'd appreciate it. Or a Tweet! Feel free to leave a comment here with a link, or email me directly at community@sandstorm.io
