### ISSUE TITLE
install script errors

### ISSUE THREAD

**Issue by cristobal23** [sandstorm-io/sandstorm#391]
I got some install script errors:

==== install ====
Sandstorm makes it easy to run web apps on your own server. You can have:

1. A full server with automatic setup (press enter to accept this default)
2. A development server, for writing apps.

How are you going to use this Sandstorm install? [1] 1
We're going to:

* Install Sandstorm in /opt/sandstorm
* Automatically keep Sandstorm up-to-date
* Create a service user (sandstorm) that owns Sandstorm's files
* Configure Sandstorm to start on System boot (with sysvinit)

To set up Sandstorm, we will need to use sudo.
OK to continue? [yes] yes
Re-running script as root...
As a Sandstorm user, you are invited to use a free Internet hostname as a subdomain of sandcats.io.
Choose your desired Sandcats subdomain (alphanumeric, max 20 characters).
Type the word none to skip this step.
What *.sandcats.io subdomain would you like? []
./install.sh: line 1131: sancats_register_name: command not found
make: *** [install] Error 127
ubuntu@ip-10-144-192-15:~/sandstorm$

**Comment by paulproteus** [comment]
Fixed by #392! Thank you hugely.

I hope you'll consider joining the sandstorm-dev email list, and doing other things listed at https://github.com/sandstorm-io/sandstorm/wiki/Get-Involved !
