### ISSUE TITLE
curl https://install.sandstorm.io | bash fails when not run as root

### ISSUE THREAD

**Issue by alec** [sandstorm-io/sandstorm#396]
Related to issue #377: when install.sh is run as non-root, it fails while trying to set  kernel.unprivileged_userns_clone because it runs "cat >> /etc/sysctl.conf ..." without non-root permissions.

Easy to reproduce: run "docker build -t sandstorm ." or "curl https://install.sandstorm.io | bash" as non-root.

```
$ docker build -t sandstorm .
[...]
Step 8 : RUN /install.sh -d -u
 ---> Running in b72a5c17c5ef
Sandstorm requires sysctl kernel.unprivileged_userns_clone to be enabled.
Currently, it is not enabled on your system.
/install.sh: line 266: /etc/sysctl.conf: Permission denied
INFO[0052] The command [/bin/sh -c /install.sh -d -u] returned a non-zero code: 1 
```

**Comment by paulproteus** [comment]
​Thanks so much for filing this -- your diagnosis looks right. I will see
what I can do about this in the next 24 hours.

It also underscores the need for more automated testing on our end for our
install process.

**Comment by paulproteus** [comment]
Hi @alec

In case you're curious, I recently refactored the Sandstorm installer and didn't test this case. I've been working on automated testing lately, and I expect you'll see more of an update on this soon.

Many thanks for filing this and bringing it to our attention.
