### ISSUE TITLE
Implement user management in admin panel

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#403]
The admin panel should show a table of users allowing the admin to:

- See when the user last logged in, etc.
- Set whether a user is "invited" (allowed to install apps and create grains).
- Set whether a user is admin.

We may further want to merge the "send invites" page into the admin page. (Perhaps the admin page should have tabs across the top for settings, users, invites, and stats?)

**Comment by jparyani** [comment]
Fixed by #424
