### ISSUE TITLE
Admin token URL should remove the token from the URL if you log in

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#409]
**What I did**

While doing emergency server operations, I went to a URL like:

* http://pintle2.sandcats.io:6080/admin/19bc20df04838fdc03101d898be075cc02de66f2

which allowed me to change my login configuration, yay, so I did so.

* Then I logged in.

**What I saw**

* After logging in, I was still at my admin token URL e.g. http://pintle2.sandcats.io:6080/admin/19bc20df04838fdc03101d898be075cc02de66f2

**What I expected**

* Since the admin token is sort of meaningless for people who are already logged in, I would expect to find myself at http://pintle2.sandcats.io:6080/admin/ instead, without the token in the URL.

**Comment by paulproteus** [comment]
This is... maybe fixed? @dwrensha do you know if it is fixed?

For now, I'll self-assign and test it in a few days.

**Comment by dwrensha** [comment]
Fixed by #1372.

**Comment by paulproteus** [comment]
So great!​
