### ISSUE TITLE
Internal Server Error [500] with fresh Sandstorm install

### ISSUE THREAD

**Issue by Mickydtron** [sandstorm-io/sandstorm#412]
Hello. I am running Ubuntu 14.04.2 on an OVH hosted virtual server, with a version of kernel  3.19 that has been customized by OVH (`3.19.6-xxxx-std-ipv6-64-vps`). I installed sandstorm via the install script, which seemed to work without error, including registering for a sandcats.io subdomain. I was able to access the admin page, log in, and start installing apps. Apps seem to install without error, but none of them will load. 

Trying to create a new instance of any app results in a 'Internal Server Error [500]', although it lists the new instance in the file list. The same error happens when I delete the entry from the list. `sandstorm status` says that sandstorm is running. Looking at sandstorm.log, we see the following whenever sandstorm starts up, either after a `sandstorm restart` or a reboot of the server: 

```
** Shutting down due to signal
Not killing Dev daemon because it is not running.
** Restarting
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 260
all output going to: /var/log/mongo.log
log file [/var/log/mongo.log] exists; copied to temporary file [/var/log/mongo.log.2015-05-18T21-50-34]
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
ERROR: unknown option -r

MongoDB shell version: 2.4.12
usage: /bin/mongo [options] [db address] [file names (ending in .js)]
db address can be:
  foo                   foo database on local machine
  192.169.0.5/foo       foo database on 192.168.0.5 machine
  192.169.0.5:9999/foo  foo database on 192.168.0.5 machine on port 9999
options:
  --shell                               run the shell after executing files
  --nodb                                don't connect to mongod on startup - no
                                        'db address' arg expected
  --norc                                will not run the ".mongorc.js" file on
                                        start up
  --quiet                               be less chatty
  --port arg                            port to connect to
  --host arg                            server to connect to
  --eval arg                            evaluate javascript
  -u [ --username ] arg                 username for authentication
  -p [ --password ] arg                 password for authentication
  --authenticationDatabase arg          user source (defaults to dbname)
  --authenticationMechanism arg (=MONGODB-CR)
                                        authentication mechanism
  -h [ --help ]                         show this usage information
  --version                             show version information
  --verbose                             increase verbosity
  --ipv6                                enable IPv6 support (disabled by
                                        default)
  --ssl                                 use SSL for all connections
  --sslCAFile arg                       Certificate Authority for SSL
  --sslPEMKeyFile arg                   PEM certificate/key file for SSL
  --sslPEMKeyPassword arg               password for key in PEM file for SSL

file names: a list of files to run. files have to end in .js and will exit after unless --shell is specified
*** Uncaught exception ***
sandstorm/run-bundle.c++:2388: failed: expected WIFEXITED(status) && WEXITSTATUS(status) == 0; mongo command failed; command = db.devapps.remove({})
stack: 0x42a0b3 0x424cfa 0x421664 0x420dff 0x4204a0 0x4203dd 0x4e85d7 0x4e9585
```

Creating a new HackerSlides:

```
*** Uncaught exception ***
sandstorm/util.c++:47: failed: open(name.cStr(), flags, mode): No such file or directory; name = /proc/modules
stack: 0x49277f 0x49247f 0x4a9899 0x4a988a 0x4e8901
Exception while invoking method 'newGrain' Error: remote exception: expected result >= minBytes; Premature EOF
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:326:15)
    at waitPromise (app/server/proxy.js:77:35)
    at startGrainInternal (app/server/proxy.js:372:10)
    at [object Object].Meteor.methods.newGrain (app/server/proxy.js:128:5)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    - - - - -
```

Opening and deleting that new HackerSlides:

```
Exception while invoking method 'openSession' Error: remote exception: expected result >= minBytes; Premature EOF
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:326:15)
    at waitPromise (app/server/proxy.js:77:35)
    at openSessionInternal (app/server/proxy.js:239:17)
    at [object Object].Meteor.methods.openSession (app/server/proxy.js:142:12)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    - - - - -
problem deleting grain 3j9ztSvdZ4rRvGzTik5d59: remote exception: expected result >= minBytes; Premature EOF
Exception while invoking method 'deleteGrain' Error: remote exception: expected result >= minBytes; Premature EOF
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:326:15)
    at waitPromise (app/server/proxy.js:77:35)
    at [object Object].Meteor.methods.deleteGrain (app/shared/grain.js:146:11)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1
    - - - - -
```

Additionally, `sandstorm mongo` results in the same `ERROR: unkown option -r`, etc. as was in the log.

**Comment by paulproteus** [comment]
Thanks for filing this! If you found out about Sandcats via my blog post,
then thanks for reading it. Either way, thanks for filing this, and I hope
we can get to the bottom of it quickly.

**Comment by jparyani** [comment]
This is very strange. The only place that a `-r` could be coming from is maybe a mis-generated mongo password. Can you take a look at /opt/sandstorm/var/mongo/passwd and report back if it starts with a `-r`?

**Comment by Mickydtron** [comment]
Thanks for getting to this so quickly. Yes, /opt/sandstorm/var/mongo/passwd does start with -r. Can I tell sandstorm to generate a new mongo password?

**Comment by kentonv** [comment]
Ouch, is this happening for 1/64 Sandstorm installs? :(

@Mickydtron You'll need to delete Sandstorm and reinstall. Since the password is generated randomly at first startup, unless you're extremely unlucky, it should then work.

**Comment by kentonv** [comment]
Wait, actually, I think it's probably best to simply delete /opt/sandstorm/var/mongo and then restart Sandstorm. That way you don't have to go through recovering your sandcats domain.

**Comment by kentonv** [comment]
Actually I think there is a second problem here. The `/proc/modules` error seems unrelated to Mongo.

@Mickydtron are you possibly using a kernel that is compiled without support for modules? What environment are you running this in?

This is just for some code which is checking if iptables is available. I guess we could fix the check to assume it is not available if `/proc/modules` is not present, which at present won't hurt anything. Longer-term perhaps we need a better way of detecting the presence of iptables.

**Comment by kentonv** [comment]
@Mickydtron It looks like we can fix the Mongo password issue without requiring passwords to be regenerated, so we'll do that too and push a release. So now you don't have to do anything except wait for the update, if you'd prefer.

**Comment by kentonv** [comment]
OK, as soon as the CI reports everything is good, I'll push a new release.

**Comment by kentonv** [comment]
OK, do `sudo sandstorm update` (or wait 24 hours for it to happen automatically) and everything should be fixed. Sorry about that!

**Comment by Mickydtron** [comment]
You were correct about everything in this thread. Removing the contents of /opt/sandstorm/var/mongo and restarting did fix the mongo issue, the /proc/modules issue was separate, and now everything is working with the update. 

Thanks!

**Comment by kentonv** [comment]
@Mickydtron - Just for the record, is the lack of /proc/modules because your kernel is compiled without module support, or something else?
