### ISSUE TITLE
Must be admin to send invites

### ISSUE THREAD

**Issue by itscassa** [sandstorm-io/sandstorm#417]
I'm having issues with configuring sandstorm.

When I go to the /admin/<token> URL, and then click on the Invite users link, I'm getting the error:
"Must be admin to send invites."

Am I doing this on a wrong way or is this a bug?

**Comment by jparyani** [comment]
This will be fixed very shortly as I'm working to move the "invite users" page into the admin settings page, and I'll make sure it all works with a token there.

The problem you're facing is that currently we only check your logged in user for admin bits on the "invite users" page. You can fix it by logging in as a user (the first user automatically gets assigned as admin), and then revisiting that page.

**Comment by kentonv** [comment]
In IRC we determined that this was another case of having initially tried to log in using email and having admin rights thus assigned to the email address despite SMTP not actually working. I've filed that problem as #418. Jason has already been working on a fix.
