### ISSUE TITLE
First user becomes admin -- including failed email login attempts

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#418]
Currently, the first user to log in becomes admin. Unfortunately, if the user attempts to log in using an email address first, and finds that doesn't work due to SMTP configuration, a user account is nevertheless created and becomes admin, and now the user cannot administer their server unless they successfully configure SMTP. Of course, the user has no idea this happened so tends to be confused when they later log in via google or github and can't do anything.

This will be fixed with the user management interface Jason is already working on, but I'm filing a bug since this seems to be coming up a bunch suddenly -- probably it only just became possible to enable email login as the initial login mechanism.

**Comment by jparyani** [comment]
Fixed by #424
