### ISSUE TITLE
SMTP URL setting for open non auth smtp server

### ISSUE THREAD

**Issue by ksavoie** [sandstorm-io/sandstorm#423]
I have a internal standalone smtp server that I have set for non-authorized use only within my network.
Trying to find the correct string to use in the SMTP URL. none of the following seem to work

smtp://smtp.myurl.com:25
smtp://anonymous@smtp.myurl.com:25
smtp://anonymous:@smtp.myurl.com:25

Thanks for any assistance. 

(side q: is there no config that would use the local postfix server instead of a remote?)

**Comment by ksavoie** [comment]
Please ignore, just came across the documentation to get mail service operational. 
https://github.com/sandstorm-io/sandstorm/wiki/Configuring-your-server-for-email

**Comment by kentonv** [comment]
FWIW, we just pushed a new build that fixed some issues in SMTP configuration -- in some places we were ignoring the SMTP setting from the admin page and only taking the one from sandstorm.conf (which is an old, deprecated way of setting the SMTP server).

Should be fixed now. If you have auto-updates installed then you'll get the update within 24 hours, or you can do `sudo sandstorm update` to get it immediately.
