### ISSUE TITLE
Refactor install code to use meteor methods instead of client-side inserts/removes

### ISSUE THREAD

**Issue by jparyani** [sandstorm-io/sandstorm#453]
We've been seeing some problems with the install logic (specifically @ocdtrekkie reported having duplicate userActions being present after an upgrade). One of the potential problems is that our removes/insert are happening on the client side at the moment and don't seem to be checking for errors at all (they're logged to the JS console, but users will almost certainly not see it).

This code should be refactored to a server side Meteor method.

**Comment by dwrensha** [comment]
Closing, as all of our database mutations now explicitly must go through Meteor methods: https://github.com/sandstorm-io/sandstorm/pull/2312.
