### ISSUE TITLE
Support various XSRF token standards

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#457]
We should go through all the common web frameworks and find out what their preferred XSRF token header is, and for all cases where the header name seems reasonably obvious as an XSRF header, add support for passing it through WebSession. This will help make sure app developers / porters don't have to do anything for XSRF protection to work correctly.

(Note that Sandstorm has its own [XSRF mitigation](https://github.com/sandstorm-io/sandstorm/wiki/Security-Practices-Overview#client-sandboxing), but it can be defeated by an attacker who can observe the victim's network packets, so apps should still do standard XSRF protection.)

**Comment by dwrensha** [comment]
Here's one that I've seen: [express.csrf](http://expressjs.com/3x/api.html#csrf) uses the "X-CSRF-Token" header.

**Comment by zarvox** [comment]
[Django](https://github.com/django/django/blob/0ed7d155635da9f79d4dd67e4889087d3673c6da/django/middleware/csrf.py#L184) uses "X-CSRFToken".

**Comment by zarvox** [comment]
[Spring](http://docs.spring.io/spring-security/site/docs/3.2.0.CI-SNAPSHOT/reference/html/csrf.html) uses "X-CSRF-TOKEN"

**Comment by zarvox** [comment]
[Flask-WTF](https://flask-wtf.readthedocs.org/en/latest/csrf.html) uses "X-CSRFToken" like Django.

**Comment by zarvox** [comment]
[Rails](https://github.com/rails/rails/blob/08754f12e65a9ec79633a605e986d0f1ffa4b251/actionview/lib/action_view/helpers/csrf_helper.rb#L18) [uses](https://github.com/rails/rails/blob/334140c927664147a4f2ecea8ea8f49fe74eff1c/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L267) "X-CSRF-Token"

**Comment by dwrensha** [comment]
https://github.com/sandstorm-io/sandstorm/blob/v0.178/src/sandstorm/web-session.capnp#L138-L162
https://github.com/sandstorm-io/sandstorm/blob/v0.178/src/sandstorm/web-session.capnp#L381-L400
https://github.com/sandstorm-io/sandstorm/blob/v0.178/shell/server/proxy.js#L1541-L1549
https://github.com/sandstorm-io/sandstorm/blob/v0.178/shell/server/proxy.js#L1596-L1607

**Comment by dckc** [comment]
So it's just a matter of adding the above headers to a white-list? I can certainly do that. Here's hoping I find some time soon...

**Comment by ocdtrekkie** [comment]
I've just ran into this, as a note. If this is an easy fix that will make porting apps with CSRF protections easier, we should do it.

**Comment by zenhack** [comment]
Opened a PR with the headers mentioned above. Haven't audited other frameworks.

**Comment by ocdtrekkie** [comment]
I think if we add the ones mentioned here, we can close this issue. People can open a new issue or PR if they need more.
