### ISSUE TITLE
Kernel panics (machine crash) on Linux 4.0.2-4.0.4 at app startup

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#461]
Unfortunately, Linux kernel 4.0.2 introduced a bug which causes a kernel panic (locking up the whole machine) when Sandstorm starts an app. This problem was fixed in kernel 4.0.5. This is not a bug in Sandstorm, but this issue is here to help users who are experiencing problems.

## Upstream

The bug was caused by a bad backport to stable. Two patches in a serious failed to be backported, leading to broken code. The two commits are:

* https://git.kernel.org/linus/820f9f147dcce2602eefd9b575bbbd9ea14f0953
* https://git.kernel.org/linus/cd4a40174b71acd021877341684d8bb1dc8ea4ae

Patching these into kernel 4.0.4 should fix the problem. Kernel 4.0.5, when released, will include these patches.

The problem has been reported as a security issue (local DoS) but not yet assigned a CVE: http://www.openwall.com/lists/oss-security/2015/05/29/5

## Fedora

The problem was briefly present in Fedora 21 and 22.

Fedora 22: Fixed in kernel-4.0.4-303.fc22 http://koji.fedoraproject.org/koji/buildinfo?buildID=639565
Fedora 21: Fixed in kernel-4.0.4-202.fc21 http://koji.fedoraproject.org/koji/buildinfo?buildID=639405

## Linode

Linode VPSs use a Linode-provided kernel, regardless of distro. Linode allows you to choose which kernel version to use. Do NOT use 4.0.4. Any other version should work.

https://www.linode.com/kernels/

## Others?

If you have spotted this problem on some other distro or hosting service, please post below for tracking purposes.

**Comment by zarvox** [comment]
This is long past now, and distros have been patched a while, so I'm closing the bug.
