### ISSUE TITLE
Installer: check kernel version before checking userns

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#478]
We received a report that the installer complained about being unable to create user namespaces, but it turned out the user in question was using kernel version 3.10. Our installer is supposed to verify that the user is on 3.13 or newer, but I guess that check is occurring after the userns check? We should probably do the version check first, since it's simpler and more informative.

**Comment by paulproteus** [comment]
In theory, in other codebases, I've been advised to "check for features, not for version numbers." I guess I've heard that mostly with regard to web browsers.

I suppose it's unlikely that someone backported user namespaces to older kernel versions in this case, though.

**Comment by paulproteus** [comment]
Fix in progress; making sure it passes a test, then will submit pull request.
