### ISSUE TITLE
Create tests for using install.sh to over-write an existing install

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#482]
Using `install.sh` to overwrite an existing install should either work properly (in which case we ought to clearly define what "work properly" would mean here), or abort with an error (telling you your options).

I imagine the simplest thing is to abort with an error, and tell users:

```
If you want to run the latest Sandstorm code with your existing install, please run:

  $ sandstorm update

If you want to change the settings that your Sandstorm server uses, then edit the sandstorm.conf file.

If you want a fresh install, please stop Sandstorm and then freshly install Sandstorm to a new directory. One way to do this is to run:

  $ sudo service sandstorm stop
  $ sudo mv /opt/sandstorm /opt/sandstorm.bk
  $ curl https://install.sandstorm.io/ | bash
```

@kentonv : +1 -1 ?

**Comment by paulproteus** [comment]
Pinging @posix4e too, since this relates to recent install/reinstall woes.

**Comment by kentonv** [comment]
I think that installing over an existing install should retain all user data (/opt/sandstorm/var) but wipe out everything else (including the config, I think). This is important to have in case you somehow "brick" your install by messing with the Sandstorm binaries (or if *we* ship a broken update!), and also if you have a broken config and you don't know how to fix it.

We should definitely let the user know what will happen before we do it, if only to comfort them.

**Comment by kentonv** [comment]
Related: #660

**Comment by paulproteus** [comment]
#660 covers the bigger goal of having install.sh help the user keep their data while getting a new copy of the Sandstorm code. I declare this issue (#482) resolved by https://github.com/sandstorm-io/sandstorm/commit/c639db73ad5d7b1a9632811363955c705be1e6e1 .
