### ISSUE TITLE
Add docs for app developers integrating with sharing

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#489]
That is, a wiki page

**Comment by dwrensha** [comment]
[triage bump]
We now have https://docs.sandstorm.io/en/latest/developing/auth/#further-reading and https://docs.sandstorm.io/en/latest/developing/path/#helping-the-user-share-access , but I think what's still needed is some basic documentation that actually explains what "permissions" and "roles" are.

**Comment by dwrensha** [comment]
Unassigning myself because I do not plan to work on this within the next two weeks.
