### ISSUE TITLE
Mention need for root in porting guide

### ISSUE THREAD

**Issue by Stuk** [sandstorm-io/sandstorm#49]
In the [Test your app in dev mode](https://github.com/sandstorm-io/sandstorm/wiki/Porting-Guide#test-your-app-in-dev-mode) section, I didn't realize I had to run `spk dev` as root/sudo.

This stopped my progress for an embarrassingly large amount of time!! If you could mention this I'm sure it would save others the trouble.

**Comment by paulproteus** [comment]
Hi @Stuk,

I just wanted to say, as the original author of that Vagrantfile, reading the issue and seeing your pull request gives me a huge amount of joy.

I know it's been a while, but it still deserves saying: thanks for submitting it! And I'm glad @kentonv merged it.
