### ISSUE TITLE
On the /admin page, the "invite" and "email invites" links are broken.

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#492]
They point to a non-existent /invite page.

**Comment by kentonv** [comment]
We should give each tab under `/admin` its own route.

I checked, and it looks like if you define routes like:

    /admin/invite/:token?
    /admin/users/:token?
    /admin/stats/:token?
    /admin/log/:token?

IronRouter will successfully be able to recognize that, say, the URL `/admin/invite` matches the route `/admin/invite/:token?`, _not_ the route `/admin/:token?` with the token being `invite`.

So I think this is what we should do.
