### ISSUE TITLE
Allow an admin to install apps for all users

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#498]
Right now, when an admin invites a user to Sandstorm, they see an empty app list, an area labeled "No files yet", and an indication that they should "Install apps."

This strikes me as unnecessarily lonely. I'm personally excited about using Sandstorm to replace shared shell servers, where e.g. I (the admin) is excited about giving people specific things they can do with a server that I'm providing them.

Given that, I propose the following:
- An admin can (somehow) mark an app as "Installed for all users," and
- Then every account sees this app as installed in the left navigation. 

Suggested implementation by @kentonv:
- The admin can create `UserAction` rows that are `null`, and
- When a user does a query for `UserAction`s (aka installed apps) to display, they look for `userId: null` as well as their own `userId`.
- These apps, for non-admins, don't show an **Uninstall** button.

Commentary by Kenton: This is possibly interesting as a _growth_ action item, and less interesting as a core _engineering_ action item.

(As a side note, I'm curious if @phildini would find this interesting/useful for his own Sandstorm.)

**Comment by ocdtrekkie** [comment]
As a user, this would make me sad. I can see the Enterprise use for this, really, but I'd be irked to be a normal user on a Sandstorm platform with some apps being bloatware.

**Comment by ocdtrekkie** [comment]
If I were to suggest a competing story, I'd suggest letting admins set some sort of default template for a new user, so they have certain apps installed, or even certain grains created. But not block the from removing those or changing them.

**Comment by kentonv** [comment]
FWIW, @ocdtrekkie, I definitely did not imagine this as something a generic paid shared hosting service would use, but rather something for specialized installations where users are expected to want to use certain apps.

With that said, I definitely don't want to enable forced bloatware. So maybe an implementation based on a template that gets copied to the user's account on creation (or upon accepting an invite) makes sense.

I do worry that in some enterprise-y contexts, it could be annoying if users are able to uninstall certain apps. Probably, some confused user will uninstall one of the default-installed apps and then not know how to get it back, generating unnecessary support tickets.

Maybe the solution is to make it part of the Blackrock license agreement that commodity hosts are not allowed to force-install apps (but can default-install them) while enterprise customers are allowed to force-install?

**Comment by ocdtrekkie** [comment]
Yeah, my concern is just that the mechanic built-in to force bloatware may lead to companies forcing bloatware, regardless of intent. (Though arguably, giving people extra, but completely sandbox isolated apps, is not an awful way to market something without violating privacy.)

I'd be wary of heavy-handing the Blackrock license agreement to the degree that Android does with the MADA. Various hosts _should_ be able to create custom experiences that they feel meets their customers' needs. (Also, from a business context, Blackrock having a bunch of terms that Sandstorm isn't subject to just makes the concept of rolling your own clustering or load balancing mechanic, so you can do what you want. Ideally, Blackrock customers should have a lot of freedom so that they want to be Blackrock customers.)

**Comment by JamborJan** [comment]
I see also use cases where I as a Sandstorm hosting provider have a package - lets say for certain industry where I have a hand full of applications I want to have for a customer. The customer is not signing up for the Sandstorm service and looks through the app store which apps might suite his needs. I as a provider say "you are a dentist and according to my expertise you need these 5 apps and thats the price". Much easier and less stress or a customer which would get scared if he sees an app store with (hopefully soon) hundrets of apps.

So thumps up for a template type of thing I can assign to a user and he gets the apps which are linked to this template.

**Comment by ndarilek** [comment]
Any updates on this use case?

I'm looking at using Sandstorm for a new co-op housing community some friends and I are considering starting. Currently I'm working with various third parties to make apps like rocket.chat and wekan more accessible.

It would be nice if I could ship some sort of pre-installed apps template so I can say "let's create a Wekan board for... or an Etherpad for..." Sure folks can individually install Etherpad, but it'd be even nicer if we could just standardize our choices of apps, then ensure that whatever we use is accessible to me out of the gate.

**Comment by ocdtrekkie** [comment]
@ndarilek Wouldn't it be similarly useful to have a custom app list, which still links to the Sandstorm App Market pages for install/download?

I mean, the big thing that scares me about the above proposal more than anything else, is suggesting that a feature to make a user unable to install an app is acceptable. I am very -1 on that, and more like -0 on letting admins install apps for all users. (I seriously have people at the office annoyed with me if I have a desktop shortcut in Users/Public/Desktop where they can't delete it themselves.)

**Comment by ndarilek** [comment]
I'd be fine with letting folks uninstall things, but I'd be likewise 
annoyed if I worked hard to make a bunch of third party apps accessible 
and someone said "we're suddenly tracking this new project on *this* 
Trello-style app," and it's horribly unusable. Or someone might want to 
perform a certain type of work, go to the app market, and find a 
*different* Trello-style app that has no accessibility improvements 
without understanding the issue.

I'd really like to organize around a series of apps that works for 
everyone, and then ensure all new users have those right from the start. 
That isn't to imply your use case is invalid. It's just that I'm working 
hard with third party developers to ensure that some of these types of 
apps that are normally inaccessible *are*, and in my experience, the 
best way to get folks to use the accessible solution is to lower every 
possible barrier.

**Comment by kentonv** [comment]
@ocdtrekkie When you said "unable to install" I assume you meant "unable to *un*install"?

**Comment by ocdtrekkie** [comment]
@kentonv Yes, that is what I meant, sorry.

**Comment by dwrensha** [comment]
With https://github.com/sandstorm-io/sandstorm/pull/2287 an admin can now control a list of apps that new users will have pre-installed. These apps currently do *not* get automatically installed for existing users.
