### ISSUE TITLE
install.sh fyi

### ISSUE THREAD

**Issue by zoowar** [sandstorm-io/sandstorm#499]
Instead of "hacking" fd3 to support "curl https://install.sandstorm.io | bash", consider using [process substitution](http://tldp.org/LDP/abs/html/process-sub.html) in the form of "bash <(curl https://install.sandstorm.io)"

In the current setup, "lsof -p" will show fd0 as a fifo when you pipe the script to bash. If you use process substitution, fd0 will remain fd0 and a different fd will manage the fifo.

Here's an example script for testing "script" and "bash <(script)"
``` bash
#! /bin/bash

main() {
    local result
    read -e -i "/tmp" -p "where? " result
    echo "$result"
}

echo "Result: $(main)" 
lsof -p $$
```

**Comment by kentonv** [comment]
Hi zoowar,

Thanks for the suggestion. Process substitution is cool. But, I think it's a bash-only feature. Some people use other shells and we should give instructions that work for all of them. Plus people who don't recognize process substitution might be wary about copy/pasting this syntax they don't know into their shell. (They're already wary of curl | sh...)

So I think we should stick with our hack. But thanks!
