### ISSUE TITLE
Support GitHub web hooks

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#509]
I would love it if I could use Sandstorm to host GitHub Web Hooks endpoints, pointing the hooks at Sandstorm grains that then do further work.

**Comment by jparyani** [comment]
Just tested it out and this is what the request from github looked like for a webhook = `http://testuser@aws.jparyani.com:10000 `: 

```js
{ authorization: 'Basic dGVzdHVzZXI6',
  host: 'aws.jparyani.com:10000',
  accept: '*/*',
  'user-agent': 'GitHub-Hookshot/becf8d8',
  'x-github-event': 'ping',
  'x-github-delivery': '61ac1200-154d-11e5-9935-99d75b764d06',
  'content-type': 'application/json',
  'content-length': '6150' }
```
