### ISSUE TITLE
'make' from scratch fails

### ISSUE THREAD

**Issue by yuvipanda** [sandstorm-io/sandstorm#524]
/bin/sh: 1: cannot create tmp/changelog.html: Directory nonexistent  
  Makefile:185: recipe for target 'shell/client/changelog.html' failed

Creating the 'tmp' directory fixes this

**Comment by paulproteus** [comment]
Closed by #526 being merged in.

**Comment by paulproteus** [comment]
Thanks to you for reporting this bug, @yuvipanda !
