### ISSUE TITLE
extra 'new instance' buttons when installing an app that's already installed

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#528]
When I install an app that's already installed, sometimes, I get an extra "new (instance)" button:

![image](https://cloud.githubusercontent.com/assets/1584904/8270554/9eebd162-1798-11e5-97dc-0891edb7c529.png)

And if I install it a few more times, I can get more buttons (but not every time).
Repro'd on oasis, alpha, and demo.

**Comment by jadeqwang** [comment]
And uninstall/reinstall fixes it.

**Comment by ocdtrekkie** [comment]
Yeah, I experienced this once. No idea why. @jparyani already noted how he wants to begin to fix this in #453

**Comment by paulproteus** [comment]
@neynah says this is closed, so I am going to mark it as such!
