### ISSUE TITLE
Clarify to user why OAuth credentials were reset after a BASE_URL change

### ISSUE THREAD

**Issue by yuvipanda** [sandstorm-io/sandstorm#530]
I restarted it after changing BASE_URL, and it seems to have lost my github client secrets / id.

**Comment by ocdtrekkie** [comment]
When you change the base URL, Sandstorm resets your OAuth credentials. A lot of users were locking themselves out. Now that the admin token feature exists, this 'feature' may not be needed anymore?

**Comment by yuvipanda** [comment]
Ah yes - I also just realized that changing the URL should also change the GitHub OAuth callback URL, so it won't work anyway. But some notice of this in places would be nice.

**Comment by kentonv** [comment]
I guess the login drop-down could contain some text like "Login services must be reconfigured due to BASE_URL change", then link to the admin page, where of course you're going to be asked to generate a token.

**Comment by paulproteus** [comment]
Closed by https://github.com/sandstorm-io/sandstorm/pull/1387

To quote the screenshot there:

> Google login has been automatically disabled because BASE_URL changed. Please make sure the configuration is correct before re-enabling.

**Comment by paulproteus** [comment]
Thanks for filing @yuvipanda ! It took us a bit, but I think we ended up a solution you'd be happy with.
