### ISSUE TITLE
Getting issue while Run curl https://install.sandstorm.io | bash

### ISSUE THREAD

**Issue by kaiservignesh** [sandstorm-io/sandstorm#550]
I am getting below error message while running "curl https://install.sandstorm.io | " in terminal. Please help me. 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53945  100 53945    0     0   9642      0  0:00:05  0:00:05 --:--:-- 13218
bash: line 332: /tmp/tmp.qgbegv2Hlh: cannot execute binary file: Exec format error
Your kernel does not appear to be compiled with support for unprivileged user 
namespaces (CONFIG_USER_NS=y), or something else is preventing creation of user 
namespaces. This feature is critical for sandboxing. Arch Linux is known to 
ship with a kernel that disables this feature; if you are using Arch, you will 
unfortunately need to compile your own kernel (see 
https://bugs.archlinux.org/task/36969). If you are not using Arch, and don't 
know why your system wouldn't have user namespaces, please file a bug against 
Sandstorm so we can figure out what happened.
*** INSTALLATION FAILED ***
Report bugs at: http://github.com/sandstorm-io/sandstorm

**Comment by ocdtrekkie** [comment]
What is your "uname - a" result? What flavor and version of Linux are you using?

**Comment by kaiservignesh** [comment]
Linux xxxxxxx-xxxxxx-xxxx 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:28:41 UTC 2015 i686 i686 i686 GNU/Linux. 

Ubuntu 14.04

**Comment by ocdtrekkie** [comment]
Ah, so you have a 32-bit install? (Looks like it to me.) Sandstorm requires a 64-bit install.

**Comment by ocdtrekkie** [comment]
See #539, and the fix to the installer, #548, to provide a better error message.

**Comment by paulproteus** [comment]
Sorry you ran into this problem, @kaiservignesh , and thanks to @ocdtrekkie for providing quick, accurate information.

@kaiservignesh I hope you'll try Sandstorm again on a 64-bit machine, and that you'll let me buy you a beverage of your choice if we ever meet in person.

**Comment by paulproteus** [comment]
I'll mark this as resolved once the changes go live for the install script and sandstorm.io/install/ page to indicate more clearly that 64-bit Linux is required.

**Comment by paulproteus** [comment]
https://sandstorm.io/install/ now says 64-bit ; thanks to @kentonv for doing the push!

**Comment by paulproteus** [comment]
Closing, since I think the install page explains the reason behind this problem.
