### ISSUE TITLE
Rename "sandbox" to "var"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#554]
Right now, in the grain storage directory, there is a directory called `sandbox`. This gets mounted into the grain as `/var`.

This creates cognitive load for app maintainers, since they now need to know that `sandbox` == `/var`.

So I propose we rename `sandbox` to `var`.

To make this work for existing grains, we'd have to check for the existence of a directory called `sandbox` and rename it to `var` before starting up a grain. (We'd also have to keep that code in Sandstorm until the end of days.)

**Comment by paulproteus** [comment]
For context: I ran into this "cognitive load" issue when debugging a MySQL-related problem last week, at Open Source Bridge, while working with Yoz on packaging Known.

**Comment by troyjfarrell** [comment]
This seems trivial.  I should be able to finish it some time in 2021.  😀  Please assign it to me.

**Comment by kentonv** [comment]
@troyjfarrell FWIW I would argue against actually spending time on this one. While it might have been better if we named the directory `var` in the first place, changing it now requires a backwards-compatibility story that introduces its own complexity and cognitive overhead that will need to be maintained forever. I think it will also affect the format of backup zips, which might in turn break any tools anyone may have written that process backup zips (I have no idea if any such tools exist, but they might). Meanwhile, the overall benefit seems relatively minor. I think it would be outweighed by the cost.

**Comment by zenhack** [comment]
Yeah, I'm in favor of closing this without implementing.

**Comment by ocdtrekkie** [comment]
I think I agree with Kenton and Ian. When it's user-facing, cognitive load is a really good reason to do something. When it's developer-facing, it's a little less a good reason to do something.

In this case, it only even affects the developer if they are poking around a grain backup for troubleshooting, and my guess is most developers will recognize the contents of their /var directory when troubleshooting.

**Comment by ocdtrekkie** [comment]
I have gone ahead and closed this one, but if you have a compelling argument to move this forward, feel free to present it, and perhaps we will reopen it.
