### ISSUE TITLE
wishlist: show a loading throbber for the time between grain launch and first HTTP reply

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#564]
Right now, some apps take a while to start up because they do migrations, or create databases, or scan thousands of directories, or do some otherwise expensive work on startup.  For instance, for the Piwik package I'm working on, grain launch to content in frame is over 6 seconds.  I intend to reduce this for Piwik, but it'd be nice if the experience were decent even if a third-party app is not the most efficient.

It would be nice if we showed some sort of "Loading..." spinner while the grain spins up and hid it as soon as the first request is completed.  I'm not sure if doing so is compatible with iframe sandboxing, though, since I think we then can't spy the iframe.onload.  Another approach would be to have the proxy emit some signal as it starts/completes proxying the first response to the frontend to hide the spinner, which could go over the Meteor socket.

(sidenote: the fact that we have the disk usage number updating in realtime as the grain launches is actually quite helpful, since it shows the user that something is happening.  But the empty grain frame still feels empty.)

**Comment by paulproteus** [comment]
+1 to the general goal & suggested implementation

**Comment by kentonv** [comment]
The commit was reverted due to a bad interaction with the incognito prompt, so reopening this until it is fixed again...

**Comment by dwrensha** [comment]
Fixed by #584.
