### ISSUE TITLE
Enable Sandstorm to listen on port 80 and 6080 and other ports all at once

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#574]
Goal:
- Allow self-hosted Sandstorm to listen on port 80 automatically, as part of the install.
- Allow existing Sandstorm installs to gain this functionality with a configuration change.

Environment assumptions:
- Sandstorm is configured to run as root.

Proposal link:
- https://oasis.sandstorm.io/shared/mgi_5hnJT2vKp-iv-lzw2Dqclt6KiuR2B3MFD6UTfhW

**OLD PROPOSAL FOLLOWS, PURELY FOR HISTORY'S SAKE**

Proposal:
- `sandstorm.conf` gains a new config option: `PUBLIC_HTTP_PORT`
- If `BIND_IP` (in `sandstorm.conf`) is not `127.0.0.1`, we run the Sandstorm process bound to `127.0.0.1` and a second process (a reverse proxy) on the `BIND_IP`.
- We change the meaning of the `PORT` configuration option. Specifically:
- (1) it is the port number used by the Sandstorm process bound to _localhost_. (As a reminder: `PUBLIC_HTTP_PORT` would be where the HTTP reverse proxy listens instead.)
- (2) the proxy listens on `BIND_IP:PORT` (in addition to `BIND_IP:PUBLIC_HTTP_PORT`) , and its job is to serve a HTTP redirect to `BASE_URL`. (Caution: it probably should only do this if `BASE_URL` == `BIND_IP:PUBLIC_HTTP_PORT` !?)
- Presumably, we'd create a socket as root, and pass it into the reverse proxy process, so the reverse proxy doesn't have to be root.

Other commentary:
- It's cleaner in my opinion to have Sandstorm+Meteor+node listen on port 80, rather than bundling an nginx that listens on port 80 for us.
- We can bind to `localhost:6080` with one process and `0.0.0.0:6080` from a second process, so it's not crazy to have `PORT` and `PUBLIC_HTTP_PORT` be the same.
- If `BASE_URL` and `WILDCARD_HOST` do not use the port number of `PUBLIC_HTTP_PORT`, someone's going to have a bad time. Maybe we should fail to start the server in that case, or something.
- I'm not wedded to these details. If someone comes up with a better plan, cool. I wanted to write this down as one plausible proposal.
- One day soon, I hope to work on implementing a `PUBLIC_HTTPS_PORT` setting.

**Comment by kentonv** [comment]
> It's cleaner in my opinion to have Sandstorm+Meteor+node listen on port 80, rather than bundling an nginx that listens on port 80 for us.

I agree. Wouldn't that change the whole proposal? With no proxy, there's no need for a separate `PUBLIC_HTTP_PORT`.

**Comment by paulproteus** [comment]
In this proposal, I mean that the HTTP reverse proxy would be bundled with
Sandstorm (presumably written in node?). That way, we'd have an easy place
to then add the HTTPS reverse proxy.

**Comment by kentonv** [comment]
I think it should be reasonably easy to make Meteor itself directly listen on both ports, with no proxy.

**Comment by paulproteus** [comment]
I updated the bug description here to contain a link to an Etherpad where Kenton, Jason, and I discussed & decided on one way forward.

If others have comments on that, by all means leave a comment here (and/or leave me a comment on the pad)!

**Comment by ocdtrekkie** [comment]
I strongly suspect this issue is not relevant to Sandstorm as it currently exists (as we have built in HTTPS already, for one, and can use both port 80 and port 443 as part of the install process). And the Oasis link is dead, of course.

**Comment by zenhack** [comment]
Yeah, I think this is solved, and can be closed.
