### ISSUE TITLE
Email forwarded to Mailpile not appearing in Inbox

### ISSUE THREAD

**Issue by rgladwell** [sandstorm-io/sandstorm#580]
I set-up an email forward from my GMail account to a Mailpile app on Oasis Sandstorm. Email is not appearing in the Mailpile Inbox, instead its appearing in a `maildir` and a `var` tag.

**Comment by jparyani** [comment]
Unfortunately, this is a known issue that happened as a side effect of rebasing to the latest Mailpile, and I haven't had time to fix it.

The issue is up at https://github.com/jparyani/Mailpile/issues/8

**Comment by kentonv** [comment]
Put another way, Mailpile deprecated maildir as a mailbox format, but unfortunately that's how Sandstorm delivers mail. We need to engineer something new that Mailpile will be happy with. Sorry for the ugliness.

**Comment by rgladwell** [comment]
@kentonv no worries, just really excited about getting Sandstorm working
