### ISSUE TITLE
Add some help text for email login

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#586]
Some people are surprised when they don't get prompted for a password. We should add an info thingy (letter 'i' in a circle, click for more info) explaining how it works.

**Comment by kentonv** [comment]
> Passwordless E-mail Login allows you to log in using an e-mail address. No password is required; instead, every time you log in, we send you a new email confirmation code. You will only need to log in once per device.

Maybe we could have some sort of a link to a wiki page, which could say things like:

> Sandstorm does not use passwords because passwords are extremely insecure. Most people use the same password for many sites, which means the operator of any of those sites could hijack the user's account on any of the others. Most people also choose easily-guessable passwords.
>
> If you would rather use a password, we recommend logging in using a third-party service like Google or Github, which implement their own password-based login. These services have large security teams well-positioned to deal with account hijacking when it happens. We also recommend enabling two-step authentication when using these services.

**Comment by paulproteus** [comment]
@neynah says this is closed, so I am going to mark it as such!
