### ISSUE TITLE
Poor visibility of sharing links and webkeys, low contrast against background

### ISSUE THREAD

**Issue by erikmaarten** [sandstorm-io/sandstorm#587]
See pictures below. A CSS rule for styling the links in those popups could be something like (if not too specific):

    #share-grain-popup a {props}

![share_link](https://cloud.githubusercontent.com/assets/4586719/8681211/7d99f454-2a66-11e5-9e3b-66707a20a89c.png)
![webkey_text](https://cloud.githubusercontent.com/assets/4586719/8681212/7dc56814-2a66-11e5-99a8-427fc7c7f006.png)

**Comment by kentonv** [comment]
Fixed in master (with completely revised styling for popups); will be released in 0.97 either today or Sunday, and pushed to Oasis shortly thereafter.
