### ISSUE TITLE
[Shell] Terminology in UI: file or grain?

### ISSUE THREAD

**Issue by erikmaarten** [sandstorm-io/sandstorm#589]
These terms seem to be used a bit inconsistently throughout the shell. I'm thinking the following occurrences should all use "file",  or they should all use "grain".

In the Sandstorm shell home screen, grains are called files ("My Files", see below).

![oasis_home](https://cloud.githubusercontent.com/assets/4586719/8703695/ed5382d4-2b1e-11e5-8af1-e50a3b54869a.png)

When deleting a grain, the term grain is used.

![delete_grain](https://cloud.githubusercontent.com/assets/4586719/8703679/d13b879a-2b1e-11e5-8e91-2ba2d1732836.png)

When creating a webkey for access to the grain, the text says that the webkey grants access to the "app". Would "file" or "grain" be more in line with other terminology in the Sandstorm?

![grain_app](https://cloud.githubusercontent.com/assets/4586719/8703677/d137630e-2b1e-11e5-85c3-79abcf7aada1.png)

**Comment by ocdtrekkie** [comment]
As far as I know, terminology here should always be 'file' for a single grain or access to it in the UI. This can get confusing though potentially  if that grain contains many files from a user perspective, or acts more like an app than a document.

**Comment by ocdtrekkie** [comment]
For instance, someone using the webkey UI to grant access to a single 'file' in their mind, and not meaning to share the whole grain?

**Comment by erikmaarten** [comment]
Using 'file' to refer to a grain can be confusing, as you say. Grains are
often not like files on computers. It's not very natural to describe my
TinyTinyRSS grain as a file. Mailpile, Paperwork and Let's Chat grains also
come to mind as examples where 'file' seems misleading.

On the other hand, few people know what a grain is in this context, but
that could be a good thing in the sense that users make fewer assumptions
when they see the word.

**Comment by ocdtrekkie** [comment]
There is a strong goal of ensuring Sandstorm is easy for non-technical users to sit down and understand. I'm not sure if defining a new term helps or hinders that goal.

**Comment by kentonv** [comment]
There has been debate about this. At one time I thought we should go with "files" to avoid introducing new terminology, but these days I lean towards "grain" as a term we define ourselves which avoids confusion with the traditional meaning of "file".

**Comment by paulproteus** [comment]
I'll echo @kentonv because he said words that are true for me as well:

> At one time I thought we should go with "files" to avoid introducing new terminology, but these days I lean towards "grain" as a term we define ourselves which avoids confusion with the traditional meaning of "file".

This issue doesn't request any particular action, but it does request a decision from us. Since @kentonv and I both like "grain" more than "file" now, and the UI consistently says "grain", I'm going to close this. I appreciate @ocdtrekkie & @erikmaarten bringing up various perspectives on the question!
