### ISSUE TITLE
End of Sandstorm grain animation should stop smoothly to avoid causing worry

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#607]
Writes @alexose:

> The animated logo should tween out though (when it stops suddenly it looks like it's frozen)

**Comment by kentonv** [comment]
Making it slow down is going to be hard, but maybe you could make it flash or shimmer or something at the end.

**Comment by zarvox** [comment]
We've removed the sandstorm grain animation, since the SVG feature it used is deprecated, and things like this confused users, so I'm calling this obsolete.
