### ISSUE TITLE
App List not shown on mobile

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#609]
Tested with iOS 8.4 and Sandstorm 0.98

When you login via mobile and tab the main menu icon you see the top level menu with your login name admin settings and about. The list of installed apps is missing.

![image1-1](https://cloud.githubusercontent.com/assets/7508960/8794059/53b76798-2f7f-11e5-961f-516a6b34c62c.png)

**Comment by paulproteus** [comment]
Similar to the other issue, might have to do with the shell UI refactoring
that @kentonv did. Thanks for filing a very clear bug report.
