### ISSUE TITLE
Scrolling on iOS broken

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#610]
Tested with iOS 8.4 and Sandstorm 0.98

I know it has been working somehow in the past but it seems to be broken again.

Scrolling doesn't work for most apps e.g. Wordpress, Piwik. But it does work for some others e.g. GitLab (not talking about the infinit scrolling for commit list).

**Comment by paulproteus** [comment]
Thanks! This might ​have to do with the shell UI refactoring that @kentonv
did.
