### ISSUE TITLE
Installer fails if hostname is unrecognized

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/sandstorm#614]
Don't have the exact error at hand, but when the installer reaches the point where it asks for the instance URL, if your hostname is unresolvable you'll get a "Name or service not known" error and the script fails.

I have a default VM template whose hostname is "debian". This, naturally, doesn't resolve. I had to temporarily set the hostname to something that resolved in order to complete the installer.

It would be nice if, instead of attempting to look up the hostname to place in the URL automatically, the option could be blanked out so those of us who know what we're doing can enter it from scratch. :) I don't have DNS set up for the instance yet and was just trying to see if the installer would complete before going further.

Thanks.

**Comment by paulproteus** [comment]
Thanks, I think I know what this is about.​ I can try to write a test for
it and then see if I can fix it.

**Comment by paulproteus** [comment]
I can reproduce this. The transcript ends with:

```
What *.sandcats-dev.sandstorm.io subdomain would you like? [] none
hostname: Name or service not known
vagrant@debian:/vagrant$ 
```

So that's a good start on fixing it. Hooray!
