### ISSUE TITLE
OAuth not working with Google or GitHub / Fresh Install

### ISSUE THREAD

**Issue by GreatScott** [sandstorm-io/sandstorm#616]
I just set up a Digital Ocean droplet and ran the curl command.

Not sure if it matters but I followed this before installing (but made sure to keep port 6080 open for TCP)
https://www.linode.com/docs/security/securing-your-server

I've attempted to set up Google/GitHub authentication, but I get for each:

"Internal server error
You must configure the <github service/Google> before you can enable it. Click the "configure" link.
For internal server errors, see <install-location>/var/log/sandstorm.log for details."

I've triple checked the URLs supplied to each.

The log is spitting out the following error:

Exception while invoking method 'adminConfigureLoginService' ReferenceError: ObjectIncluding is not defined
    at [object Object].Meteor.methods.adminConfigureLoginService (app/shared/admin.js:829:22)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1

**Comment by paulproteus** [comment]
I think I know how to fix this. Thanks for reporting it.

**Comment by GreatScott** [comment]
How would I go about applying the patch or updating this now that it's been fixed? Thanks!

**Comment by paulproteus** [comment]
Thanks a great deal for filing this, @GreatScott . It seems this is a really important problem that any new Sandstorm user would run into! Sorry it affected you.

@kentonv can you do a release containing this sometime soon? If so, then the easiest way will be for you to run `sudo sandstorm update` once it's released.

**Comment by paulproteus** [comment]
If you want to race to build your own, @GreatScott , you can do a "git clone" of the repository, then run "make bundle" and then `sudo sandstorm update /path/to/bundle/you/created`. I would recommend waiting for us to release a new version, but that is one thing you could do right now.

**Comment by GreatScott** [comment]
Got it, thanks @paulproteus ! I'll probably just wait for the release - not in a huge rush. Looking forward!

**Comment by kentonv** [comment]
Release v0.100 is on the way. Will let you know when it's ready (probably ~10 minutes).

**Comment by ocdtrekkie** [comment]
@kentonv You guys doing anything to celebrate that release number? :)

**Comment by kentonv** [comment]
New release is up! You can update with:

    sudo sandstorm update

Or wait 24 hours and it will happen automatically (unless you disabled that).

@ocdtrekkie: Just hoping that we manage to go stable before build 1000 because that's when we run out of "0.x" build numbers.
