### ISSUE TITLE
Server-side outgoing DNS fails if resolv.conf wasn't ready when Sandstorm started

### ISSUE THREAD

**Issue by vitch** [sandstorm-io/sandstorm#62]
I'm probably doing something else dumb...

I've accessed my self hosted sandstorm instance over https proxied by nginx. I first set up Github authentication. When I try to log in a github window opens and closes and closes then the message "Internal server error" appears in the signin overlay at the top right of the screen.

Looking at `/opt/sandstorm/var/log/sandstorm.log` I see the following message:

```log
{"line":"230","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with Github. getaddrinfo ENOTFOUND","time":{"$date":1406409017886},"level":"warn"}
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Github. getaddrinfo ENOTFOUND
    at getAccessToken (packages/github/github_server.js:46)
    at Object.userAgent [as handleOauthRequest] (packages/github/github_server.js:5)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8)
    at middleware (packages/oauth/oauth_server.js:89)
    at packages/oauth/oauth_server.js:62
```

I thought I'd try Google instead...

When I click "Sign in with google" after choosing my account (my browser is signed into two google apps accounts) I see the following:

![screen shot 2014-07-26 at 22 05 15](https://cloud.githubusercontent.com/assets/9898/3712288/a1679030-1509-11e4-9835-99c0aca8e003.png)

Nothing about this shows up in the logs.

Any ideas?

**Comment by zarvox** [comment]
I believe this is fixed by #1097, which is exciting because now I can close the fourth-oldest open issue. :)
