### ISSUE TITLE
Installing as non-root is confusing

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#629]
No matter which path you choose, if you indicate that you don't want to install as root (and you didn't specify `-u`), the installer bails out.

If you were on the dev mode path, it suggests re-running with -u. However, when skimming, it's surprisingly easy to miss this suggestion entirely, believing instead that non-root installs are simply not allowed. Yes, if you read every word then the message very clearly tells you what to do, but I myself managed to miss it when trying to install Sandstorm just now, despite the fact that I helped design this language.

So now I'm thinking maybe we should revert directly to the non-root custom install flow here, without asking the user to re-run. Actually I can't remember why we decided to instruct the user to start over in the first place, though I think we had some reason...?

**Comment by paulproteus** [comment]
+1 to this being assigned to me; will look into it.

**Comment by paulproteus** [comment]
The one reason I had to want to suggest re-running the installer was implementation simplicity from my perspective, as the maintainer of the program. I think that was all, though.

**Comment by paulproteus** [comment]
I've made this a little nicer in #1406 :

https://asciinema.org/a/dcgz5wkxmgoa2gfj5kpro639l

I'm going to mark as resolved for now, since that's about to land.
