### ISSUE TITLE
new install annoyance: localhost:6080/admin gives ENOTFOUND TXT message

### ISSUE THREAD

**Issue by cben** [sandstorm-io/sandstorm#632]
I've run the install on a home machine.
It told me visit `http://cben-grom.sandcats.io:6080/admin/...`
But that address 404s — it points to the home router's external IP (which makes perfect sense and I'd need port forwarding if I cared but I actually just installed for local work & to get the `spk` command and I'm not at my home now).

So my natural response is editing the address to `localhost:6080/admin/...` but that tells me:

> Error looking up DNS TXT records for host 'localhost': queryTxt ENOTFOUND
> 
> This Sandstorm server's main interface is at: http://cben-grom.sandcats.io:6080
> ...

which leaves no apparent way to start working locally without configuring external connectivity? 

Probably related to #398.

**Comment by cben** [comment]
also related to #618 — the problem preventing use of sandcats is different but being able to proceed via `localhost` would be helpful in both cases.

**Comment by cben** [comment]
> no apparent way to start working locally
Sorry, there was a way — editing BASE_URL in /opt/sandstorm/sandstorm.conf.

OK, I see, to configure either google or github login I now have to set origin to `localhost`.
Let's try giving both `localhost` and `cben-grom.sandcats.io` to Google...  (is that secure?)
Worked, created an admin user.

[sorry if I come off as complaining, I'm just to report any paper-cuts on a newbie's way to installing, not a way

**Comment by paulproteus** [comment]
Thanks a great deal for filing this! It's very useful to have sense of the paper-cuts, as you put it. I will review these in more depth in a couple of days.

**Comment by paulproteus** [comment]
And feel free to keep providing feedback/advice.

**Comment by paulproteus** [comment]
By the way, you might find the "5-minute packaging tutorial" with vagrant-spk to be useful: https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/

**Comment by paulproteus** [comment]
I believe that the new error page addresses the most important part of this issue - the fact that there was no discoverable path from the error message to a fixed server. Changed in 8b374aebc7c8cc28f2a60125c87d0f3bbd388a2e

I'm attaching a screenshot on this and declaring victory. Thanks @cben for filing!

![new-error-page](https://cloud.githubusercontent.com/assets/25457/14968336/1db7edf6-1071-11e6-966f-535d7fd51b58.png)
