### ISSUE TITLE
docs: Remark on how to add an app to the app list

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#634]
@kentonv what is the command you want people to use to generate the `package-id`? I remember you told me something but I couldn't find it in the output of `spk --help`.

**Comment by paulproteus** [comment]
Note that https://docs.sandstorm.io/en/latest/developing/raw-packaging-guide/ does contain this info, so it might be a matter of finding a better place for it.

**Comment by dwrensha** [comment]
> @kentonv what is the command you want people to use to generate the package-id? I remember you told me something but I couldn't find it in the output of spk --help.

You're probably thinking of `spk verify --details <spk>`,

**Comment by paulproteus** [comment]
@dwrensha That's the one. Thank you!

**Comment by zarvox** [comment]
I think this is obsoleted now that we have the app market and app developers no longer need to know specific package ids. :)
