### ISSUE TITLE
Kernel 3.13 requirement

### ISSUE THREAD

**Issue by jgillich** [sandstorm-io/sandstorm#64]
I am sure there are good reasons why you require kernel 3.13 or newer, but I think you should reconsider this anyway. RHEL/CentOS 7 for example comes with kernel 3.10 and this is not going to change till version 8. Since this software targets servers, it should at least support the latest versions of the major server distributions.

**Comment by M4rtinK** [comment]
Well, the RHEL/CentOS kernel is not a plain 3.10 - it has a huge amounts of features backported from newer kernels:

https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Kernel_backporting

Maybe the features you need have since been backported to the RHEL 7 kernel ?

**Comment by kentonv** [comment]
@M4rtinK Unfortunately, it's the opposite: Red Hat has explicitly disabled user namespaces in RHEL 7 due to concerns that they weren't yet ready for prime-time (and indeed, in 3.10 they were broken in several ways, which is why Sandstorm requires 3.13).

Source: http://rhelblog.redhat.com/2015/07/07/whats-next-for-containers-user-namespaces/

**Comment by M4rtinK** [comment]
>@M4rtinK Unfortunately, it's the opposite: Red Hat has explicitly disabled user namespaces in RHEL 7 due to concerns that they weren't yet ready for prime-time (and indeed, in 3.10 they were broken in several ways, which is why Sandstorm requires 3.13).

>Source: http://rhelblog.redhat.com/2015/07/07/whats-next-for-containers-user-namespaces/
Interesting & thanks for the link! 

BTW, from the linked article it seems to be available as a tech preview starting with RHEL 7.2 (released November 2015), so I guess its it at least moving in the right direction: :)

>Update: As of September 2015, user namespaces have been enabled as a Technology Preview in the beta release of Red Hat Enterprise Linux 7.2.

and

>In case someone else comes here from google trying to figure out how to use user namespaces on rhel/centos 7.2, you have to do `sudo grubby –args=”user_namespace.enable=1″ –update-kernel=/boot/vmlinuz-3.10.0-327.3.1.el7.x86_64` and then reboot to enable them. (obviously you have to change the kernel name if you’re running another kernel)
