### ISSUE TITLE
In sandstorm shell, console.log() a note saying you might want the app iframe context

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#654]
Step to reproduce:

As a Sandstorm app developer:

* Open a Sandstorm instance
* Open up the JS console

Expected behavior:

* You are in the JS context of the app. (At least two people seem to have thought this: @ndarilek & @jacksingleton .)

Actual behavior:

* You are in the JS console of the Sandstorm shell.

**Proposal**

* When you view the JS console in the Sandstorm shell, you should see a message vaguely like this one from Facebook:

![Facebook console.log() warning](https://i.stack.imgur.com/Wiatp.png)

But instead with a message like:

```
You're interacting with the **Sandstorm shell**. If you want to interact with the **app**, click the navigation above and change from **top frame** to **app-iframe**.
```

**Comment by kentonv** [comment]
+1

MDN used to print a recruiting message into the dev console. :) But it looks like now they just spew some JS errors. :(

**Comment by jacksingleton** [comment]
Along those lines maybe it could also have a link to the app developer documentation and some encouragement to write or port a sandstorm app!

**Comment by dwrensha** [comment]
Fixed in https://github.com/sandstorm-io/sandstorm/pull/1354.

**Comment by paulproteus** [comment]
Thanks for taking good care of the tickets!
