### ISSUE TITLE
Forever stuck in "Downloading..." state

### ISSUE THREAD

**Issue by campadrenalin** [sandstorm-io/sandstorm#659]
When I try to download apps on my standalone instance, the app is not actually downloaded. I get the "Downloading..." page, stuck at 0% indefinitely.

I can actually load the SPK URLs via curl on the same machine. I know it's not a network issue, not on that level anyways. And the log shows nothing about this stuff. I have to conclude it's something broken in Sandstorm, or Firefox.

http://sandstorm.roaming-initiative.com:6080/install/3b04dd588ab7dbdf5a0299838fb3230d?url=http://sandstorm.io/apps/etherpad10.spk

**Comment by paulproteus** [comment]
Thanks for filing this!

Interestingly, you're not the only person to report a problem like this.​

From what I can tell, you're hosted on Linode, which has nothing special
going on by default on their network. Maybe I can take a quick look at the
download code.

**Comment by paulproteus** [comment]
First question: When you do that, does this message get logged to the
Javascript console?

Downloading app: http://sandstorm.io/apps/etherpad10.spk

​From what I can tell, it should be, based on
https://github.com/sandstorm-io/sandstorm/blob/master/shell/server/installer.js#L355

**Comment by campadrenalin** [comment]
Hmm. Definitely glad I made an official issue, then.

Yeah, hosted on Linode. Should have nothing interesting in the network config.

Nope, no such message. The last thing I see (other than static resources like inbox.svg) is:

    GET http://sandstorm.roaming-initiative.com:6080/sockjs/043/tfv43q9j/websocket

And I kinda suspect this is a websocket connectivity problem, although I don't know how exactly to test that, since I haven't delved that deep into the Sandstorm internals.

**Comment by paulproteus** [comment]
I'll dig into this, hopefully soon.

**Comment by campadrenalin** [comment]
Awesome, thank you! Obviously let me know if there's anything I can do to
help you reproduce and debug.

**Comment by kentonv** [comment]
> From what I can tell, it should be, based on
https://github.com/sandstorm-io/sandstorm/blob/master/shell/server/installer.js#L355

That's server-side, so it should be logged to the server log visible in the admin panel (or at `/opt/sandstorm/var/log/sandstorm.log`).

**Comment by kentonv** [comment]
(The server log could definitely contain more info here. Take a look and let us know what you find.)

**Comment by campadrenalin** [comment]
Per /admin/log, verified against the file in /opt/. This hasn't changed in awhile, and certainly hasn't responded at all to my attempts to install apps.

```
...** Starting Sandstorm at: Tue Aug  4 18:12:44 2015
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
child process started successfully, parent exiting
[object Object]
Successfully added user: {
	"user" : "sandstorm",
	"roles" : [
		"readWriteAnyDatabase",
		"userAdminAnyDatabase",
		"dbAdminAnyDatabase"
	]
}
** Back-end and Mongo started; now starting front-end...
WriteResult({ "nRemoved" : 0 })
Migrations applied: 0/6
Applying migration 1
Applied migration 1
Applying migration 2
Applied migration 2
Applying migration 3
Applied migration 3
Applying migration 4
Applied migration 4
Applying migration 5
Applied migration 5
Applying migration 6
Applied migration 6
** Shutting down due to signal
** Exiting
** Starting Sandstorm at: Tue Aug  4 18:26:35 2015
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
** Request to start front-end, but it is already running
WriteResult({ "nRemoved" : 0 })
Migrations applied: 6/6
** Shutting down due to signal
** Exiting
** Starting Sandstorm at: Tue Aug  4 18:27:49 2015
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
WriteResult({ "nRemoved" : 0 })
Migrations applied: 6/6
** Shutting down due to signal
** Exiting
** Starting Sandstorm at: Tue Aug  4 18:32:32 2015
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
WriteResult({ "nRemoved" : 0 })
Migrations applied: 6/6
** Shutting down due to signal
** Exiting
** Starting Sandstorm at: Tue Aug  4 18:36:35 2015
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
WriteResult({ "nRemoved" : 0 })
Migrations applied: 6/6
resetting oauth
Error: Error looking up DNS TXT records for host 'local.sandstorm.io': queryTxt ENODATA
    at app/server/pre-meteor.js:454:21
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:149:9)
```

**Comment by campadrenalin** [comment]
Aha! Chrome has a websocket recorder in the dev tools! It's shit at copy and paste, but with a little manual touchup...

```
o
["{\"msg\":\"connect\",\"version\":\"1\",\"support\":[\"1\",\"pre2\",\"pre1\"]}"]
["{\"msg\":\"method\",\"method\":\"login\",\"params\":[{\"resume\":\"JjHykTGP_evEbXDMHYypVjcl0UzFd6XnhTMGHpbiWJ4\"}],\"id\":\"1\"}"]
["{\"msg\":\"sub\",\"id\":\"tb5cvaaboD4FZuqfu\",\"name\":\"meteor.loginServiceConfiguration\",\"params\":[]}"]
["{\"msg\":\"sub\",\"id\":\"ALP5rciCLmkCSGk78\",\"name\":\"meteor_autoupdate_clientVersions\",\"params\":[]}"]
["{\"msg\":\"sub\",\"id\":\"Yiv6gwbPC279TRXeS\",\"name\":\"publicAdminSettings\",\"params\":[]}"]
["{\"msg\":\"sub\",\"id\":\"fC9PSKmSY7SoWAg9D\",\"name\":\"credentials\",\"params\":[]}"]
["{\"msg\":\"sub\",\"id\":\"GsEbqx9aLdFBpKkac\",\"name\":\"packageInfo\",\"params\":[\"3b04dd588ab7dbdf5a0299838fb3230d\"]}"]
["{\"msg\":\"sub\",\"id\":\"WMAuA3SRt3M4wfjnM\",\"name\":\"credentials\",\"params\":[]}"]
["{\"msg\":\"sub\",\"id\":\"xSjKFSvQhKkuBKKav\",\"name\":\"grainsMenu\",\"params\":[]}"]
a["{\"server_id\":\"0\"}"]
a["{\"msg\":\"connected\",\"session\":\"ta6dsXyNvgP6YccNv\"}"]
a["{\"msg\":\"added\",\"collection\":\"users\",\"id\":\"Lcky4XAL7xjBkpN9G\",\"fields\":{\"profile\":{\"name\":\"Philip Horger\",\"picture\":\"88JBPQxFaP9bv9gfe\",\"handle\":\"campadrenalin\",\"pronoun\":\"male\"}}}"]
a["{\"msg\":\"updated\",\"methods\":[\"1\"]}"]
a["{\"msg\":\"result\",\"id\":\"1\",\"result\":{\"id\":\"Lcky4XAL7xjBkpN9G\",\"token\":\"JjHykTGP_evEbXDMHYypVjcl0UzFd6XnhTMGHpbiWJ4\",\"tokenExpires\":{\"$date\":1446521431149}}}"]
["{\"msg\":\"sub\",\"id\":\"jvJ5fWxFSuDaYomYA\",\"name\":\"notifications\",\"params\":[]}"]
["{\"msg\":\"sub\",\"id\":\"yoF8n9SdtMTy6vQzm\",\"name\":\"notificationGrains\",\"params\":[[]]}"]
a["{\"msg\":\"added\",\"collection\":\"meteor_accounts_loginServiceConfiguration\",\"id\":\"rPo3v6QHfh2zYER9W\",\"fields\":{\"service\":\"github\",\"clientId\":\"20281b9af910564bb081\",\"loginStyle\":\"redirect\"}}"]
a["{\"msg\":\"added\",\"collection\":\"meteor_accounts_loginServiceConfiguration\",\"id\":\"cQpxFbpmhTR5oBGZv\",\"fields\":{\"service\":\"google\",\"clientId\":\"20728296590-fg0bl1i1g2196lvma7limrls7m33686f.apps.googleusercontent.com\",\"loginStyle\":\"redirect\"}}"]
a["{\"msg\":\"ready\",\"subs\":[\"tb5cvaaboD4FZuqfu\"]}"]
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"iyeZSYipQGQ46uvXH\",\"fields\":{\"current\":true}}"]
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"version\",\"fields\":{\"version\":\"235651e1c3a578430fd8f0650284f3bf852f63f8\"}}"]
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"version-cordova\",\"fields\":{\"version\":\"none\",\"refreshable\":false}}"]
a["{\"msg\":\"added\",\"collection\":\"meteor_autoupdate_clientVersions\",\"id\":\"version-refreshable\",\"fields\":{\"version\":\"84b87c30a26a233f277ab75a24b2c7c7ebf7ac7a\",\"assets\":{\"allCss\":[{\"url\":\"/410f825edb7ad00bfd422d7f1bc93418e1acafb2.css?meteor_css_resource=true\"}]}}}"]
a["{\"msg\":\"ready\",\"subs\":[\"ALP5rciCLmkCSGk78\"]}"]
a["{\"msg\":\"added\",\"collection\":\"settings\",\"id\":\"github\",\"fields\":{\"value\":true}}"]
a["{\"msg\":\"added\",\"collection\":\"settings\",\"id\":\"google\",\"fields\":{\"value\":true}}"]
a["{\"msg\":\"ready\",\"subs\":[\"Yiv6gwbPC279TRXeS\"]}"]
a["{\"msg\":\"changed\",\"collection\":\"users\",\"id\":\"Lcky4XAL7xjBkpN9G\",\"fields\":{\"isAdmin\":true,\"signupKey\":\"admin\"}}"]
a["{\"msg\":\"ready\",\"subs\":[\"fC9PSKmSY7SoWAg9D\"]}"]
a["{\"msg\":\"added\",\"collection\":\"packages\",\"id\":\"3b04dd588ab7dbdf5a0299838fb3230d\",\"fields\":{\"status\":\"download\",\"progress\":0}}"]
a["{\"msg\":\"ready\",\"subs\":[\"GsEbqx9aLdFBpKkac\"]}"]
a["{\"msg\":\"ready\",\"subs\":[\"WMAuA3SRt3M4wfjnM\"]}"]
a["{\"msg\":\"ready\",\"subs\":[\"xSjKFSvQhKkuBKKav\"]}"]
["{\"msg\":\"method\",\"method\":\"ensureInstalled\",\"params\":[\"3b04dd588ab7dbdf5a0299838fb3230d\",\"http://sandstorm.io/apps/etherpad10.spk\",false],\"id\":\"2\"}"]
["{\"msg\":\"method\",\"method\":\"ensureInstalled\",\"params\":[\"3b04dd588ab7dbdf5a0299838fb3230d\",\"http://sandstorm.io/apps/etherpad10.spk\",false],\"id\":\"3\"}"]
a["{\"msg\":\"ready\",\"subs\":[\"jvJ5fWxFSuDaYomYA\"]}"]
a["{\"msg\":\"ready\",\"subs\":[\"yoF8n9SdtMTy6vQzm\"]}"]
a["{\"msg\":\"updated\",\"methods\":[\"2\"]}"]
a["{\"msg\":\"result\",\"id\":\"2\"}"]
a["{\"msg\":\"updated\",\"methods\":[\"3\"]}"]
a["{\"msg\":\"result\",\"id\":\"3\"}"]
a["{\"msg\":\"ping\"}"]
["{\"msg\":\"pong\"}"]	
h
a["{\"msg\":\"ping\"}"]
["{\"msg\":\"pong\"}"]	
h
a["{\"msg\":\"ping\"}"]
["{\"msg\":\"pong\"}"]	
a["{\"msg\":\"ping\"}"]
["{\"msg\":\"pong\"}"]	
h
a["{\"msg\":\"ping\"}"]
["{\"msg\":\"pong\"}"]	
h
a["{\"msg\":\"ping\"}"]
["{\"msg\":\"pong\"}"]
... more like that ...
```

**Comment by kentonv** [comment]
Unfortunately, the websocket log you just posted contains login secrets. I took the liberty of using your login token to log you out, hopefully before anyone else noticed. Please be careful when posting logs publicly.

Looking at the rest now...

**Comment by campadrenalin** [comment]
Thanks. I'm more than half expecting to destroy and recreate the third
party auth configurations anyways, but that certainly takes the immediate
risk out.

**Comment by kentonv** [comment]
Well, resetting the third-party auth actually doesn't revoke existing sessions.

Would you mind giving me app install permissions so I can try some debugging? Just go to:

http://sandstorm.roaming-initiative.com:6080/admin/users

And upgrade me (kenton@corp.sandstorm.io) to "invited user".

**Comment by campadrenalin** [comment]
@kentonv Done!

**Comment by campadrenalin** [comment]
Just got the idea to try uploading an SPK manually. I downloaded http://sandstorm.io/apps/jparyani/laverna-5.spk, then uploaded that to the server. Got a 500 error. That should show up in the logs somehow...

**Comment by kentonv** [comment]
It's really weird that clicking "Cancel" isn't doing anything. Is it producing log messages?

**Comment by kentonv** [comment]
I guess if you gave me admin I could look at the log myself, but I'd understand if you're not comfortable with that. OTOH if you're going to wipe the server anyway...

**Comment by campadrenalin** [comment]
I *am* planning to do that, so admin would probably be fine. For that matter, it may just work after I wipe it. But in the meantime... we'll do it the way that produces debug info for posterity.

**Comment by campadrenalin** [comment]
You've been upgraded again. I figure it's not a problem, since you're already a primary developer and I have no content on here to peek at. If I'm gonna trust the software you've written, I might as well trust you with a blank instance.

**Comment by kentonv** [comment]
Oh, this looks bad:

    Error: connect(): Permission denied; toString() = unix:/var/sandstorm/socket/backend

If the front-end can't connect to the back-end, that would potentially explain some things.

Did you do anything funny with the filesystem permissions under `/opt/sandstorm`?

**Comment by campadrenalin** [comment]
Perhaps unintentionally. I did install with the wrong URL, and reinstalled over the top. I betcha that's a critical component in the problem.

**Comment by campadrenalin** [comment]
Actually, looking like the culprit is running the install script inside a sudo. Which, as a separate bug points out, is a necessary evil when you change the script name. I didn't realize that at the time, it just didn't work until I wrapped the whole thing in sudo (had no idea script name was a factor).

```
philip@li603-71:~$ ls -l /opt/sandstorm/
total 16
lrwxrwxrwx  1 root root        13 Aug  4 18:36 latest -> sandstorm-104
lrwxrwxrwx  1 root root        16 Aug  4 18:36 sandstorm -> latest/sandstorm
drwxr-xr-x 14 root root      4096 Aug  4 05:56 sandstorm-104
-rw-r--r--  1 root root       216 Aug  4 18:36 sandstorm.conf
drwxrwx--T  2 root sandstorm 4096 Aug  5 01:18 tmp
drwxr-xr-x  7 root root      4096 Aug  4 18:12 var
```

**Comment by campadrenalin** [comment]
Install command I used, for reference: `sudo bash install_sandstorm.sh`

**Comment by kentonv** [comment]
Hmm, running the installer under sudo should be fine, and those permissions looks fine.

Try `ls -la /opt/sandstorm/var/sandstorm/socket`?

**Comment by campadrenalin** [comment]
```
philip@li603-71:~$ sudo ls -la /opt/sandstorm/var/sandstorm/socket
[sudo] password for philip: 
total 8
drwxrwx--- 2 root root      4096 Aug  5 01:18 .
drwxrwx--- 7 root sandstorm 4096 Aug  5 01:18 ..
srwxrwx--- 1 root sandstorm    0 Aug  5 01:18 backend
srwxrwx--- 1 root sandstorm    0 Aug  5 01:18 devmode
```

**Comment by kentonv** [comment]
drwxrwx--- 2 root root      4096 Aug  5 01:18 .

That's weird. How did that get to be root:root instead of root:sandstorm? Especially when its parent is correctly root:sandstorm?

**Comment by kentonv** [comment]
What's in your `/opt/sandstorm/sandstorm.conf`?

**Comment by campadrenalin** [comment]
```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://sandstorm.roaming-initiative.com:6080
WILDCARD_HOST=*.sandstorm.roaming-initiative.com:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
```

**Comment by kentonv** [comment]
Hmm well that looks right. I'm confused how `/opt/sandstorm/var/sandstorm/socket` ended up with gid=root.

My best guess is that this is a bug with installing over an existing install. We should test that more.

We should also make sure you get a clearer error when the front-end can't reach the back-end.

In any case, I think if you delete `/opt/sandstorm` and reinstall, it should work.

**Comment by campadrenalin** [comment]
Will try that.

**Comment by campadrenalin** [comment]
Haha! It works! Thank you so much!

**Comment by paulproteus** [comment]
Wow, thank you all for the amazing debugging here.
​

**Comment by dwrensha** [comment]
>Hmm well that looks right. I'm confused how /opt/sandstorm/var/sandstorm/socket ended up with gid=root.
My best guess is that this is a bug with installing over an existing install. 


I tried a fresh install (choosing "2. A development server, for writing apps." and accepting all defaults) and I got:

```
$ ls -l /opt/sandstorm/var/sandstorm/
total 24
-rw-rw---- 1 root sandstorm   40 Aug  5 08:00 adminToken
drwxrwx--- 2 root sandstorm 4096 Aug  5 08:00 apps
drwxrwx--- 2 root sandstorm 4096 Aug  5 08:00 downloads
drwxrwx--- 2 root sandstorm 4096 Aug  5 08:00 grains
drwxr-xr-x 2 root root      4096 Aug  5 08:00 socket
drwxrwx--T 2 root sandstorm 4096 Aug  5 08:00 tmp
```

The socket directory is owned by root:root. This does look wrong to me, but it doesn't seem to be causing problems on this particular server.

**Comment by kentonv** [comment]
@dwrensha Hmm, but in your case the mode has o+rx whereas in @campadrenalin's case only owner and group could access the directory. Still, it seems weird and wrong that this is inconsistent.

Actually it looks like there might be a race. There's two places in run-bundle where the `socket` directory might be created: line 1799 and line 2242. The former case will create it root:root but mode 755, whereas the second will create it root:sandstorm with mode 770. Since they are in different subprocesses I suppose the ordering on first startup is not strictly defined. Both modes *should* be fine, though, and I don't see how either one would result in what @campadrenalin ended up with.

**Comment by paulproteus** [comment]
I think install.sh is to blame here. Rationale:

First I did this to see what the permissions are like on my laptop, where
things seem to work OK.

➜  ~  ls -ld /opt/sandstorm/var/sandstorm/socket
drwxr-xr-x 2 root root 4096 Aug  1 17:31 /opt/sandstorm/var/sandstorm/socket


➜  ~  ls -l /opt/sandstorm/var/sandstorm/socket
total 0
srwxrwx--- 1 root paulproteus 0 Aug  1 17:31 backend
srwxrwx--- 1 root paulproteus 0 Aug  1 17:31 devmode



Then I ran the "chmod" line that lives in install.sh:

➜  ~  cd /opt/sandstorm
➜  sandstorm  sudo  chmod -R g=rwX,o= var/{log,pid,mongo,sandstorm}
var/sandstorm/{apps,grains,downloads,adminToken}
[sudo] password for paulproteus:


Then I examined the permissions:

➜  sandstorm  ls -l /opt/sandstorm/var/sandstorm/socket
ls: cannot open directory /opt/sandstorm/var/sandstorm/socket: Permission
denied

➜  sandstorm  ls -ld /opt/sandstorm/var/sandstorm/socket
drwxrwx--- 2 root root 4096 Aug  1 17:31 /opt/sandstorm/var/sandstorm/socket

So it's going from 755 to 770.

I guess the thing to do is fix install.sh to chmod the var/sandstorm/socket
directory more carefully (or carefully refuse to set that directory's
permissions).

**Comment by kentonv** [comment]
@paulproteus The `chmod -R` line in `install.sh` is immediately preceded by some `chown` lines. It looks like the `chown` and the `chmod` lines are inconsistent with each other, and actually rather weird. The `chmod` line's second argument is totally redundant, for example.

**Comment by paulproteus** [comment]
It seems to originate in

```
commit feba15f5946cd7228868c5437e8f9f88ff2fc207
Author: David Renshaw <dwrenshaw@gmail.com>
Date:   Thu May 28 17:33:17 2015 -0400

    fix ownership and permissions for var/sandstorm
```

from what I can tell. I'll ping David and see what problem that was trying
to solve and see if there's a better way.
