### ISSUE TITLE
Sandstorm struck while opening apps

### ISSUE THREAD

**Issue by shashank-k** [sandstorm-io/sandstorm#667]
I am unable to open any app in sandstorm as it is struck even after 20 min. 
![selection_002](https://cloud.githubusercontent.com/assets/7534403/9132862/4bd14902-3d14-11e5-9f75-7608f1b847fc.png)

Please let me know where I am going wrong

Using Chromium on Ubuntu 14.04 and logged in with Github. 

Log as follows

...** SANDSTORM SUPERVISOR: Starting up grain.
sandstorm/supervisor.c++:1144: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.
** Starting Mongo...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 6
all output going to: /var/mongo.log
child process started successfully, parent exiting
** Starting Meteor...
Meteor._wrapAsync has been renamed to Meteor.wrapAsync
> Starting board-background-color migration.
> Finishing board-background-color migration.
> Starting lowercase-board-permission migration.
> Finishing lowercase-board-permission migration.
> Starting change-attachments-type-for-non-images migration.
> Finishing change-attachments-type-for-non-images migration.
> Starting card-covers migration.
> Finishing card-covers migration.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Starting up grain.
sandstorm/supervisor.c++:1144: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.
** Starting Mongo...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 6
all output going to: /var/mongo.log
log file [/var/mongo.log] exists; copied to temporary file [/var/mongo.log.2015-08-07T09-19-32]
child process started successfully, parent exiting
** Starting Meteor...
Meteor._wrapAsync has been renamed to Meteor.wrapAsync
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain no longer in use; shutting down.
** SANDSTORM SUPERVISOR: Starting up grain.

**Comment by kentonv** [comment]
Hi SK,

Is this on your personal instance or one we run?

If it's your personal instance, what is the contents of `/opt/sandstorm/sandstorm.conf`?

In particular I'm wondering if `WILDCARD_URL` may be set incorrectly. This needs to be set to an actual DNS wildcard host. If it's not, then what you'll observe is that apps don't seem to start, but it's actually that your browser can't reach them because they are placed on the wildcard host. It also means you won't be able to see your profile picture on the account settings page.

We should probably implement some sort of detection of this problem since it's pretty common...

**Comment by shashank-k** [comment]
@kentonv Thanks for the info.

I could fix this myself.

**Comment by jmatsushita** [comment]
Just ran into this problem on a self hosted instance as well (including the profile picture not displaying). +1 for detection and proposing resolution or testing steps!

**Comment by paulproteus** [comment]
Thanks for getting in touch! For now, Jun, have you been able to fix it by
setting up wildcard DNS? I look forward to clarifying these issues in the
interface.

**Comment by jmatsushita** [comment]
Yes this particular problem is solved by setting up wildcard DNS.

**Comment by paulproteus** [comment]
Great! Glad to hear it.
