### ISSUE TITLE
Cant install sandstorm - error no support for unprovileged user namespaces

### ISSUE THREAD

**Issue by JakubBily** [sandstorm-io/sandstorm#671]
Hello guys,

I love sandstorm, so I bought a VPS to have my own server.I tried to install it, but there is this error: 
"
Your kernel does not appear to be compiled with support for unprivileged user
namespaces (CONFIG_USER_NS=y), or something else is preventing creation of user
namespaces. This feature is critical for sandboxing. Arch Linux is known to
ship with a kernel that disables this feature; if you are using Arch, you will
unfortunately need to compile your own kernel (see
https://bugs.archlinux.org/task/36969). If you are not using Arch, and don't
know why your system wouldn't have user namespaces, please file a bug against
Sandstorm so we can figure out what happened.
"

What can I do with it? My VPS is Ubuntu 14.04 - 64 bit running on OpenVZ virtualization platform. 

I saw some other topics with similar issue on the forum, to I am leaving here some results of command some people wanted before. I hope it is going to help to solve the problem quicker. :)

Result of command "uname -a" is :
Linux vps 3.16.6-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

Result of command "cat /proc/self/mounts | grep /tmp" is nothing.

Result of commadd "cat /proc/sys/kernel/unprivileged_userns_clone" is "No such file or directory"

Result of command "unshare --user id" is "unrecognized option "--user"

Can I solve it somehow? Thanks everyone for help.

**Comment by paulproteus** [comment]
Hi JakubBily,

I think this Linux kernel won't work with Sandstorm, and typically with
OpenVZ it's not possible for users to upgrade their kernel to a different
version. Sorry about that. You should get a new host.


Sandstorm relies on a kernel feature that seems to be disabled on your
hosting provider. If you can show them this message and ask them to enable
it, that'd be great! But honestly I wouldn't get my hopes up.

I hope this helps. You may have better luck with a VPS provider that is Xen
or KVM-based rather than OpenVZ-based.

Sincerely,

Asheesh.

**Comment by DiThi** [comment]
My VPS uses a 2.6.x kernel. Since only trusted users will use it, can sandboxing be disabled?

**Comment by kentonv** [comment]
@DiThi Sorry, it can't. The containerization is fundamental to the way apps operate on Sandstorm, independent of security concerns.

**Comment by icekev** [comment]
@kentonv  is there any possible way to have that working on an openvz vps ? What are the causes to this issue and how could this be solved in a way that openvz stays secure ?

**Comment by kentonv** [comment]
@icekev Unfortunately, probably not. OpenVZ is based on a shared kernel, using something similar to containers for isolation. I imagine that they don't want to enable user namespaces because userns has somewhat of a history of privilege escalation vulnerabilities (which is why Sandstorm disallows apps from using it). Even if that's not a concern, I am not sure how userns would interact with OpenVZ -- I imagine it is awkward at best.

**Comment by Samuel29** [comment]
Hi. I'm using a low cost baremetal server to install it.. And I get the same error.

here my OS and system details:
```
➜  sam more /etc/debian_version
8.3

➜  sam uname -a
Linux ----- 3.14.32-xxxx-grs-ipv6-64 #5 SMP Wed Sep 9 17:24:34 CEST 2015 x86_64 GNU/Linux

➜  sam zgrep CONFIG_USER_NS /proc/config.gz
CONFIG_USER_NS=y

➜  sam df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       917G  535G  336G  62% /

➜  sam free -m
             total       used       free     shared    buffers     cached
Mem:          3926       3802        124        209        153       3321
-/+ buffers/cache:        327       3599
Swap:          510          0        510

➜  sam egrep '(model name|flags|cache size|MHz|processor)' /proc/cpuinfo
processor	: 0
model name	: Intel(R) Atom(TM) CPU D425   @ 1.80GHz
cpu MHz		: 1800.064
cache size	: 512 KB
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
processor	: 1
model name	: Intel(R) Atom(TM) CPU D425   @ 1.80GHz
cpu MHz		: 1800.064
cache size	: 512 KB
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
```
Any clue ?

**Comment by paulproteus** [comment]
Can you try running the following:

unshare --user /bin/bash -c id

as root, and then running it as non-root (e.g. an account called sam)?

You can read the manual page for "unshare" to get a sense of what it does; in this case, we create a new "user namespace" and then run bash so that we run the "id" command, which will print out the user ID perceived by the process.

For me, it is:

```
$ id -u
1000
$ unshare --user /bin/bash -c id
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
$ sudo unshare --user /bin/bash -c id
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
```

**Comment by Samuel29** [comment]
Hi @paulproteus 
here is the result. I'm not understanding that namespace feature at all, so I paste it as-is.
```  /  id -u
1000
☁  /  unshare --user /bin/bash -c id
unshare: unshare failed: Operation not permitted
☁  /  sudo unshare --user /bin/bash -c id
[sudo] password for sam:
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
☁  /  man unshare
☁  /  unshare --user /bin/bash -c id
unshare: unshare failed: Operation not permitted```

should my user be added to a specific group ? but what would be the relashionship with the installation script? I assume that the daemon will run as a brand new user, added by this script ?

**Comment by paulproteus** [comment]
Thanks for replying!

To answer your question about how this relates to the installer: Sandstorm
will create a new user account on the server, and that user account uses
user namespaces to containerize Sandstorm apps.

For what it's worth, this first output (without sudo) indicates that the
kernel only allows root (UID 0) to use the Linux kernel feature called user
namespaces.

Does this file exist? If so, what is its contents? Should be either 0 or 1,
if it exists.

/proc/sys/kernel/unprivileged_userns_clone

If that file exists, there's a way to enable the feature, at least!

The bare metal server seems like it is running a configuration not equal to
what you get in /proc/config.gz, as far as I can tell, given the fact that
the "unshare" command works with sudo but doesn't work without sudo.

**Comment by Samuel29** [comment]
```
☁  ~  sudo cat /proc/sys/kernel/unprivileged_userns_clone
cat: /proc/sys/kernel/unprivileged_userns_clone: No such file or directory
```
your hypothesis might be correct about the config.gz outdated contents: my hosting provider preinstalls his own kernels on his servers... perhaps they don't do this in a clean way.

**Comment by paulproteus** [comment]
Well, the good news is that if you ask your provider to enable the user
namespaces feature, then Sandstorm will work!

And you can try installing your own custom kernel if you like!

**Comment by Samuel29** [comment]
I'm currently switching to another kernel (the kernel above has GRsecurity, I can switch to vanilla via the netboot options of my hosting provider)

**Comment by Samuel29** [comment]
Same issue with another kernel.
What I don't understand is that /proc/config.gz is supposed to give the currently running kernel's options...
```
➜  / uname -srvm
Linux 3.14.32-xxxx-std-ipv6-64 #7 SMP Wed Jan 27 18:35:08 CET 2016 x86_64

➜  / zgrep CONFIG_USER_NS /proc/config.gz
CONFIG_USER_NS=y
```

**Comment by Samuel29** [comment]
@paulproteus sorry but is there another kernel option that would be missing ?
here is the current kernel config that was used to compile my kernel
ftp://ftp.ovh.net/made-in-ovh/bzImage/latest-production/config-3.14.32-xxxx-std-ipv6-64

CONFIG_USER_NS=y

**Comment by paulproteus** [comment]
I know of no particular other kernel option that's required, except on
Debian systems, where the /proc file I named allows the user to
enable/disable unprivileged use of this kernel feature. You can read:

man 7 user_namespaces

on your system to learn more. It writes, in part:

   Availability
       Use of user namespaces requires a kernel that is configured with the
CONFIG_USER_NS
       option.  User namespaces require support in a range of subsystems
across  the  ker‐
       nel.  When an unsupported subsystem is configured into the kernel,
it is not possi‐
       ble to configure user namespaces support.

       As at Linux 3.8, most relevant subsystems supported user namespaces,
but  a  number
       of  filesystems  did  not  have the infrastructure needed to map
user and group IDs
       between user namespaces.  Linux 3.9 added the required
infrastructure  support  for
       many  of  the  remaining  unsupported  filesystems (Plan 9 (9P),
Andrew File System
       (AFS), Ceph, CIFS, CODA, NFS, and OCFS2).  Linux 3.11 added support
the last of the
       unsupported major filesystems, XFS.


So maybe you can ask your kernel distributor why "unshare --user" gives an
error, only when run with sudo. It's quite strange to me, but maybe they've
added a patch to the kernel and haven't documented it anywhere.

**Comment by Samuel29** [comment]
the patches they use are mainly to support specific hardware or address driver bugs.
I'm wondering if this isn't a bug from Debian...
I'll continue my investigations tomorrow. and perhaps consider switching to another distro :)

**Comment by paulproteus** [comment]
How did this turn out?

**Comment by samuel-finistere** [comment]
Hi. Sorry I cross posted on issue #1430 (yes I used my 2nd github account)

**Comment by paulproteus** [comment]
Great! Per https://github.com/sandstorm-io/sandstorm/issues/1430 I'll close this.
