### ISSUE TITLE
Home button on generated public WP site calls wp-login.php

### ISSUE THREAD

**Issue by avcobe** [sandstorm-io/sandstorm#672]
1) Generated a public site from the wp site built in the sandstorm server. 
2) removed cookies and history (firefox on mac)
3) browsed to the site but could not go to homepage after leaving it for some other page on the site. (wp-login.php appended on the homepage url)

**Comment by paulproteus** [comment]
Hi @avcobe ,

Thanks for filing this bug! I'm going to move it to the issue tracker specifically for WordPress on Sandstorm: https://github.com/dwrensha/wordpress-sandstorm/issues

I hope you'll participate in the conversation there, and I hope @dwrensha can take a look and find out what is going on.

**Comment by paulproteus** [comment]
I'll close this here, but @avcobe I hope you'll click "Subscribe" on https://github.com/dwrensha/wordpress-sandstorm/issues/7 . Thanks for filing this and I hope you and @dwrensha can get to the bottom of it.
