### ISSUE TITLE
"Send an invite" should de-emphasize "See who has access"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#678]
In #677 I filed an issue about a UI element.

However, the first thing I tried when trying to send the email was clicking the **See who has access** button. I realize that's sort of insane of me, since it doesn't say **Send** but I'm tired, I woke up early to get on a plane, so I clicked the wrong button. In particular I clicked it because I expect the button in the bottom-right of a dialog to mean "Commit the action I have just configured through typing", like how there is a big green **Submit new issue** button in this GitHub issues submit form.

**Comment by kentonv** [comment]
Should be fixed by the redesign happening now.
