### ISSUE TITLE
"Who has access" information can show "null (you)" as one's name, which is odd

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#679]
Steps to reproduce:

* Log in with with a GitHub account where the user never configured a `name` (or configure your Meteor account to have `{profile: {name: null}}` via `meteor shell`)
* Create a grain
* Share it with someone
* Examine the "Who has access" tab

Expected behavior:

* The line where my identity appears (as a way of listing those to whom I have granted access) should say "you" or something.

Actual behavior:

* It claims I am `null (you)`, which if I didn't know Javascript, would be disconcerting.

Screenshots to reproduce, fwiw:

![01-logged-in-as-alic](https://cloud.githubusercontent.com/assets/25457/9230723/c6bf38e6-40d8-11e5-86f7-bc9c12243e14.png)

![02-have-acronymy-shared](https://cloud.githubusercontent.com/assets/25457/9230739/e58bc35c-40d8-11e5-8451-bbc8ce19355b.png)

![03-see-myself-as-null](https://cloud.githubusercontent.com/assets/25457/9230743/ead2fd3a-40d8-11e5-9d23-bc0b9589eed7.png)

I'm filing this bug mostly because it suggests to me we'd do well to some kind of anti-null-in-strings defensive programming pattern in Javascript to save us from issues like this. I don't know what that would be yet, but wanted to document this issue to see if code style guidelines could help.

**Comment by kentonv** [comment]
So, `sandstorm-db/profile.js` now contains code which builds a full profile out of the information we've obtained from other services. It will do things like fall back to github username if github name isn't available. Perhaps we should do a migration that applies this logic to existing `profile` objects, such that they all become "initialized" without the need to execute this profile-building logic at runtime?

We are also planning a first-login splash screen which will let the user explicitly set their name and such (and agree to the terms / privacy policy).
