### ISSUE TITLE
Double scrollbars on small screens.

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#68]
Current file picker UI can provide the unholy double scrollbar menace if you have too many apps and too many documents for the window.

![doublescrollbars](https://cloud.githubusercontent.com/assets/4399499/3782196/e74fafc6-199e-11e4-8ae6-951836042a19.png)

**Comment by paulproteus** [comment]
Yeah, I can confirm this is a bug. I made a new `html-css` label as a reminder to myself of the mindset I'll have to be in when fixing it (if I'll be the one to fix it).

**Comment by paulproteus** [comment]
Hey uh @zarvox do you happen to know enough HTML/CSS to fix this?

**Comment by coyotebush** [comment]
Looks like this is a non-issue in the new UI. Both `.grain-list` and `.navbar-grains` have `overflow-y` set to `auto`.

**Comment by ocdtrekkie** [comment]
@coyotebush Yeah, I'm not surprised if this no longer applies at all.

**Comment by kentonv** [comment]
Just goes to show: If you ignore a bug long enough, eventually it will go away! :)
