### ISSUE TITLE
Renaming shared grain doesn't rename original

### ISSUE THREAD

**Issue by tiagoefreitas** [sandstorm-io/sandstorm#692]
A shared Etherpad grain with the editor role can be renamed by a user opening the share, but it only renames his local one, not the original grain.

Is this by design? It's a bit confusing...not what I would expect.
Maybe it's for the best, not sure about it.

**Comment by ocdtrekkie** [comment]
As far as I recall, this is intentional, that anyone can name the grain the way they want to for their own reference. 

Though the use case of another editor needing to rename the original is a valid issue.

**Comment by paulproteus** [comment]
I do find the current behavior confusing, for what it's worth.

Yesterday, while demo-ing Sandstorm, I watched some user click on the title
of an Etherpad they had received a sharing link to, and do a rename and
say, "That's interesting that I can rename it" and I had to explain to
them, "Well it only renames it for you."

**Comment by dwrensha** [comment]
This problem was addressed in https://github.com/sandstorm-io/sandstorm/pull/1893. It should be less confusing now!
