### ISSUE TITLE
Register TT-RSS as a feed reader in Firefox

### ISSUE THREAD

**Issue by jinnko** [sandstorm-io/sandstorm#694]
TT-RSS has a feature in Preferences>Feeds>Firefox integration to add it as a feed reader, allowing one to easily add RSS subscriptions to the TT-RSS instance.  Unfortunately this doesn't work as expected within Sandstorm.

I found it's possible to make this work manually using the Inspect Element>Console feature.  I took the code off the "Click here to register this site as a feed reader" button and modified it to contain the correct URL, then ran this via the Console.

The code in the page reads as follows:

```
window.navigator.registerContentHandler("application/vnd.mozilla.maybe.feed", "http://localhost:33413/public.php?op=subscribe&feed_url=%s",  "Tiny Tiny RSS")
```

Replacing the localhost then running the code in the Console achieves the desired result:

```
window.navigator.registerContentHandler("application/vnd.mozilla.maybe.feed", "https://URL_TO_YOUR/grain/RANDOM_ID/public.php?op=subscribe&feed_url=%s",  "Tiny Tiny RSS")
```

Note that editing the code inline then re-pressing the button doesn't work.  I don't know why.

As there's no other easy way to register an RSS reader I expect this feature within TT-RSS to work.

**Comment by paulproteus** [comment]
Hi! Thanks for filing this issue. Your steps that explain the issue are
very clear.

Can you re-submit it against the issue tracker specific to the TT-RSS
Sandstorm package? You can find it in the app list -- visit
https://sandstorm.io/apps/ -- and click "Code on GitHub." It seems to be
https://github.com/jparyani/Tiny-Tiny-RSS , so visit there and click
"Issues" and submit it.

I would do that for you, but I'm on a very low-bandwidth Internet
connection. But I hope you can do it.

Thank you for reporting this issue!

**Comment by jinnko** [comment]
Thanks @paulproteus - I've opened jparyani/Tiny-Tiny-RSS#4.

**Comment by paulproteus** [comment]
Thank you for doing that!​
