### ISSUE TITLE
Web publishing docs are outdated

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#699]
The docs here:

https://docs.sandstorm.io/en/latest/developing/web-publishing/

Look like they haven't been updated for the change described here:

https://groups.google.com/d/msg/sandstorm-dev/fsLdSQbv5ZM/7LdR8d2YWB4J

**Comment by paulproteus** [comment]
Assigning this to me, since it pre-dates docs moving into the git repo. (After docs move into the git repo, my theory is that docs+code change at the same time.)

If anyone else wants to do it instead, that's OK with me! But I do want to make sure we do it, so I'm willing to own it.

**Comment by paulproteus** [comment]
Done; see new docs at https://docs.sandstorm.io/en/latest/developing/web-publishing/
