### ISSUE TITLE
grain size reported in topbar can differ from actual disk space used

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#705]
I noticed this with journal files written by Mongo 3.0's WiredTiger engine. With `du` or `ls -s`, the files showed up as 200MB, but `stat()` (and thus the topbar) reported a "total size" more like 100KB. I'm not sure how this is even possible, but I think it has to do with sparseness/compression. It looks like the files in question were intialized by writing a single "\0" byte every 4k or so.

**Comment by kentonv** [comment]
In theory we could report size based on `st_blocks` rather than `st_size`. OTOH it's weird that then a sparse file might show up as very small but as soon as you download a zip become very large. I guess we could do max() of the two?

I'm also somewhat inclined to silently ignore `fallocate()` calls via seccomp.

**Comment by dwrensha** [comment]
Updating with my current understanding:

>  With du or ls -s, the files showed up as 200MB, but stat() (and thus the topbar) reported a "total size" more like 100KB. 

This was due to the files having been allocated with `fallocate()`.

> It looks like the files in question were intialized by writing a single "\0" byte every 4k or so.

This is what happened on Ext3, where `fallocate()` is not supported. In this case, there was not a disparity between `st_blocks` and`st_size`.

**Comment by kentonv** [comment]
A few releases ago (at the same time as we added the size column in the grains table) we switched to using `st_blocks` instead of `st_size`, which I think "resolves" this issue.
