### ISSUE TITLE
Tried to install an app from apps.sandstorm.io and now unable to install

### ISSUE THREAD

**Issue by zombiezen** [sandstorm-io/sandstorm#706]
Restarting the server doesn't help (`sandstorm restart`), and now I only see a "Waiting for write access..." message any time I try to install an app.

**Comment by paulproteus** [comment]
Hi @zombiezen ,

I don't know what's going on here, but I imagine @jparyani or @kentonv can help figure this out. First question for you: is there anything in /opt/sandstorm/var/log/sandstorm.log that looks like a Javascript exception?

**Comment by zombiezen** [comment]
Nothing that seems relevant (there's background noise of WebSocket disconnects).  In fact, the only pertinent line seems to be:

```
Downloading app: https://alpha-j7uny7u376jnimcsx34c.sandstorm.io/packages/f185ee59f2753f3a1063be2a2281596c
App ready: f185ee59f2753f3a1063be2a2281596c
```

So it seems to think it succeeded.  Seems like a bad resource cleanup, and it's quite persistent.

**Comment by paulproteus** [comment]
Hi @zombiezen ,

This issue is fascinating. Sorry it's affecting you. I will try to dig into this more tomorrow.

**Comment by zombiezen** [comment]
Still affected on Sandstorm 106.  When installing an app, the UI hangs on "Unpacking...".  Subsequent installs hang on "Waiting for write access..."

**Comment by zombiezen** [comment]
I've narrowed this down to a websocket proxying issue on my end.  I don't think this is a general Sandstorm issue.. apologies for the noise.

**Comment by paulproteus** [comment]
Oh, websockets proxying issues. They are legion. We should auto-detect them.

Thank you for filing this; it helps us know about another error message
that hints at that sort of problem.

**Comment by zombiezen** [comment]
I haven't eliminated the possibility that this is a peculiarity of how I'm proxying websockets on my end, but after more debugging, it appears to me that Sandstorm's websockets are emitting packets that are split across frames.  SockJS does not handle this well, and I get a client-side `Uncaught SyntaxError: Unexpected end of input` [inside the SockJS client](https://github.com/sockjs/sockjs-client/blob/f529e8855e4649df81af8de1abe251612c59c69c/dist/sockjs-0.3.4.js#L1081).

The split packet in question is a subscription update for the `packages` collection, in particular, inside FileDrop's metadata. The first part of the frame is 2875 bytes, the second is 1477 bytes. This probably messes up the rest of the client code.

**Comment by zombiezen** [comment]
Argh, this is more noise. I've isolated the failure to my websocket proxy again.
