### ISSUE TITLE
libreboard not working

### ISSUE THREAD

**Issue by berndblume** [sandstorm-io/sandstorm#708]
I just installed sandstorm on Ubuntu 15.04. Everything works like a charm, draw.io, etherpad, etc. all work fine.
I also installed libreboard. After opening a "New LibreBoard", I see the libreboard screen, and in the title bar it says "Untitled LibreBoard", and then the MB keep counting for minutes. The page is reloaded every second or so, and the MBs go up and up. In the demo, it does work - it stops at 1.6 MB or so. But on my own server: counting and counting.
You can try yourself at http://sandstorm.hau.to

**Comment by kentonv** [comment]
That's strange! Anything interesting in the debug log (click the monitor icon in the top bar while the app is open)?

**Comment by berndblume** [comment]
Hi Kanton,
Here's a screen shot of the log.
Thanks, Bernd

[image1.PNG]

-----
Sent from an iPad

On Aug 23, 2015, at 12:04 AM, Kenton Varda <notifications@github.com<mailto:notifications@github.com>> wrote:


That's strange! Anything interesting in the debug log (click the monitor icon in the top bar while the app is open)?

-

**Comment by paulproteus** [comment]
Hi @berndblume ,

Any chance you could send me an invite to your server, via https://storm.debian.net/admin/invites ? I'm asheesh@sandstorm.io.

**Comment by paulproteus** [comment]
Thanks! I received your invite and can test now!

**Comment by paulproteus** [comment]
OK, I think I know what's going on. When I visit your server, and I try to visit a LibreBoard instance, I see this message in my browser's Javascript console:

> WebSocket is closed before the connection is established.

Also, the LibreBoard reloads itself in an infinite loop.

The infinite loop causes the LibreBoard to keep taking up slightly more disk space as it reloads.

@berndblume , my guess is that you need to configure your frontend web server (nginx? apache?) to proxy web sockets. https://github.com/sandstorm-io/sandstorm/blob/master/nginx-example.conf shows one way to do that for nginx; if you're not using nginx, I can perhaps help you by providing some sample config you can use.

https://github.com/sandstorm-io/sandstorm/issues/316 discusses this issue in more detail.

**Comment by berndblume** [comment]
Hi Asheesh,

that might be it, indeed! :-)

I am using nginx as a reverse proxy, but I was unaware I have to take special action in order to have nginx proxy web sockets.

I will check the links you provided and will let you know if I was able to fix it or not.

Thanks, Bernd


On Aug 25, 2015, at 4:00 PM, Asheesh Laroia <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I think I know what's going on. When I visit your server, and I try to visit a LibreBoard instance, I see this message in my browser's Javascript console:

WebSocket is closed before the connection is established.

Also, the LibreBoard reloads itself in an infinite loop.

The infinite loop causes the LibreBoard to keep taking up slightly more disk space as it reloads.

@berndblume<https://github.com/berndblume> , my guess is that you need to configure your frontend web server (nginx? apache?) to proxy web sockets. https://github.com/sandstorm-io/sandstorm/blob/master/nginx-example.conf shows one way to do that for nginx; if you're not using nginx, I can perhaps help you by providing some sample config you can use.

#316<https://github.com/sandstorm-io/sandstorm/issues/316> discusses this issue in more detail.

**Comment by berndblume** [comment]
Hi Asheesh,

I’ve updated my nginx config and now it works like a charm!

Thanks so much for your help! :-)

Bernd


On Aug 25, 2015, at 4:00 PM, Asheesh Laroia <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I think I know what's going on. When I visit your server, and I try to visit a LibreBoard instance, I see this message in my browser's Javascript console:

WebSocket is closed before the connection is established.

Also, the LibreBoard reloads itself in an infinite loop.

The infinite loop causes the LibreBoard to keep taking up slightly more disk space as it reloads.

@berndblume<https://github.com/berndblume> , my guess is that you need to configure your frontend web server (nginx? apache?) to proxy web sockets. https://github.com/sandstorm-io/sandstorm/blob/master/nginx-example.conf shows one way to do that for nginx; if you're not using nginx, I can perhaps help you by providing some sample config you can use.

#316<https://github.com/sandstorm-io/sandstorm/issues/316> discusses this issue in more detail.

**Comment by paulproteus** [comment]
Hooray! So glad to hear it. I'll mark this as closed.
