### ISSUE TITLE
Full on, federated Apache Wave

### ISSUE THREAD

**Issue by bb010g** [sandstorm-io/sandstorm#730]
I love Wave and am glad to see it on Sandstorm at all, but I think a bit of the point of it was missed during packaging. Wave was created to be federated—Google knew from the start it couldn't succeed at all if it was just another proprietary Google product. Watch [the introductory Google IO talk](https://youtu.be/v_UyVmITiYQ?t=1h5m17s) (01:05:17–01:11:48), and they demo three Wave servers communicating in complete harmony. (Here are [some](https://en.wikipedia.org/wiki/Google_Wave_Federation_Protocol) [pages](http://www.waveprotocol.org/federation) [about](https://en.wikipedia.org/wiki/Apache_Wave#Federation_protocol) the protocol.) Wave is still at its core a communications platform, not a document editing platform. It's not Etherpad. Dovecot and Roundcube are both seen as communication platforms, and thus kept in their more "monolithic" setups because you don't want a new email address every time you send an email. You want to be able to quickly send a message on the side. Wave is made to work with an open web, and I think it fits very well with Sandstorm's long term goal of ubiquitous self hosting. Just let it be free.

**Comment by ocdtrekkie** [comment]
Well, I would suppose that when Sandstorm sharing is working over federation, which is a goal, I believe, that people can ideally just use Sandstorm sharing features to share Waves?

This may be better to file on https://github.com/jparyani/wave/issues

**Comment by bb010g** [comment]
You shouldn't have to drag other people running non-Sandstorm Wave servers over to Sandstorm just to talk, though. Also, what about bots, like (Aunt Rosie)[http://andrewhitchcock.org/?post=322]?

**Comment by kentonv** [comment]
Agreed that Wave on Sandstorm doesn't meet Wave's full potential. Though to be honest I never really understood what Wave was going for with the federation stuff. Every time I used it, it seemed to be a document editor. So it's hard for me to say exactly what a federated Wave on Sandstorm should look like. Hopefully, though, someone will figure it out and figure out how to combine the Wave vision with the Sandstorm capability/powerbox model and it will be cool.

And agreed that this discussion belongs on the Wave port bug tracker, not here. :)
