### ISSUE TITLE
New UI: Make buttons in install flow purple (or grey).

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#774]
As one of the first things users will see on messing with Sandstorm, the Cancel, Install, Upgrade, and Upgrade Files buttons in the install flow should probably be styled for the new UI.

**Comment by paulproteus** [comment]
I think @kentonv and I just finished this last night, and it's in "master".
Out of curiosity, where are you testing?

**Comment by ocdtrekkie** [comment]
I was told to test on testrock.

**Comment by dwrensha** [comment]
@paulproteus: I think @ocdtrekkie is referring to the "Install", "Cancel", "Upgrade", etc. buttons that are currently blue.

**Comment by paulproteus** [comment]
Got it, like this one:

![old-blue-button](https://cloud.githubusercontent.com/assets/25457/9548027/06991492-4d6c-11e5-846c-97c488ae7291.png)

**Comment by ocdtrekkie** [comment]
Yes. Those are the bluest thing left in this entire app.

Also, while you're at it, Show Changelog on the about screen, but I'm far less worried about it.

**Comment by kentonv** [comment]
We have a rewrite of the install UI coming some time after launch (with Keybase author verification). I suppose we could at least change the button colors for launch, though.
