### ISSUE TITLE
New UI: Stripe in Edge Browser

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#776]
Might be out of your control:

![stripeinedge](https://cloud.githubusercontent.com/assets/4399499/9547174/f9c97b66-4d5d-11e5-981e-16eaf67c2f7d.png)

**Comment by kentonv** [comment]
It seems to do that in IE11 as well. Clicking "remember me" causes it to suddenly fix itself (even if you then un-check it).

I suspect this has something to do with our hack that keeps Stripe's javascript out of our origin. When the invisible iframe is clicked, it opens the stripe window and resizes itself at the same time -- maybe stripe records the small frame size too soon and messes up its own style in an attempt to fit? Maybe we can solve this by giving the iframe's inner document an explicitly large size (even when the viewport is small)?

**Comment by jparyani** [comment]
Fixed by #783

**Comment by jparyani** [comment]
Thanks for the report @ocdtrekkie!

**Comment by kentonv** [comment]
testrock updated

**Comment by kentonv** [comment]
oops, didn't mean to hit re-open
