### ISSUE TITLE
New UI: Last Activity has unusually large field (Edge browser)

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#777]
I feel like, especially with the existence of my really long title, that the Last Activity field should probably be smaller.

![lastactivitybigfield](https://cloud.githubusercontent.com/assets/4399499/9547226/68f0c602-4d5e-11e5-95dc-4a0ab44a1acf.PNG)

**Comment by dwrensha** [comment]
I think the width is like this because we're going to add more columns, like "collaborators".

**Comment by ocdtrekkie** [comment]
I feel like the title column should be "all the space that isn't needed for the other columns", but I don't know if people share my feels there.

Also, I feel the icon column being headed with "App" feels silly, I think that should be blank.

**Comment by kentonv** [comment]
Yeah, we don't need to be reserving this space if we're not filling it yet.

(PS we really need to visually distinguish "shared with me" in this table; currently it's impossible to tell the difference without opening the grain.)

**Comment by kentonv** [comment]
Fixed in ee59c65.
