### ISSUE TITLE
Spk Init should provide the metadata structure

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#787]
Ideally, app developers coming to the platform shouldn't need to look up someone else's app manifest (see Etherpad example) to figure out what should be in their app's pkgdef file in order to publish to the app store.

Placing the metadata fields in the initial pkgdef file, perhaps commented out (so that there isn't failures during testing for nonexistent screenshots, descriptions, etc.) may be prudent.

**Comment by zarvox** [comment]
I am so +1 on this.  People should not need to read comments in the Sandstorm source to build packages that target the Sandstorm platform.

Commented-out examples accompanied with explanations are probably the best way to go here.  We should probably add good examples for both `metadata` and `bridgeConfig`.

**Comment by ocdtrekkie** [comment]
I am currently attempting to wrangle a slightly trimmed down version of the comments in Sandstorm source to something that can be put on docs.sandstorm.io as per @paulproteus and the chocolate cake challenge. But am not sure there is any better way to document the information format of the manifest file than to just give them a manifest file that they just need to fill in the blanks on.
