### ISSUE TITLE
Click on label for check box does not toggle check ("I have read and agree to the Terms of Service")

### ISSUE THREAD

**Issue by jacksingleton** [sandstorm-io/sandstorm#798]
Pretty small one but a bit of a pet peeve of mine...

Clicking on the label for a checkbox or radio should toggle the check on/off.

It looks like in this case there is not "label" tag so the browser doesn't know to toggle the check box.

<img width="465" alt="screen shot 2015-08-29 at 12 41 45 am" src="https://cloud.githubusercontent.com/assets/1058938/9560681/5d9b753e-4de7-11e5-94d3-d55c0ff4d075.png">

**Comment by zarvox** [comment]
Fixed by #806.  Thanks for the helpful report!

**Comment by paulproteus** [comment]
Thanks to both of you!
