### ISSUE TITLE
Weird issues with demo

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#830]
So, I had been testing the "demo" behavior on Oasis before my talk.

- You cannot sign out of the demo, so there is no way around this oddity for an hour.
- If you are in the demo (countdown in the top right is running) and you log in, your username is "Demo User", and I was not presented with the account dialog after signing in with Google or GitHub.
- Even when I logged in with the credentials for my Oasis account, I ended up being called "Demo User" and not finding my own grains. (Additional log out and log in seemed to fix this.)

Not sure if anyone else can reproduce, but it seemed really odd.

**Comment by kentonv** [comment]
> You cannot sign out of the demo, so there is no way around this oddity for an hour.

FWIW, you can do `Meteor.logout()` on the console. But yeah, generally we're trying to encourage people to log in. It seems like for most people there should be no particular reason to log out of the demo.

> * If you are in the demo (countdown in the top right is running) and you log in, your username is "Demo User", and I was not presented with the account dialog after signing in with Google or GitHub.
> * Even when I logged in with the credentials for my Oasis account, I ended up being called "Demo User" and not finding my own grains. (Additional log out and log in seemed to fix this.)

These sound really odd, but I cannot reproduce them. Can you provide more specific step-by-step instructions? Your username should only ever be "Demo User" while the countdown is ticking in the corner...

**Comment by ocdtrekkie** [comment]
Issue appears to be fixed/no longer present. I cannot reproduce it again either. Closing.

**Comment by kentonv** [comment]
Hmm, well we haven't changed anything... so that's worrying... >_>
