### ISSUE TITLE
Is it translatable?

### ISSUE THREAD

**Issue by diff-** [sandstorm-io/sandstorm#832]
Can we translate it to a locale language?
Would you release translation strings on Transifex.com to make it possible for us to have a contribution?

**Comment by kentonv** [comment]
No, at present we're not ready to localize the Sandstorm UI. We definitely want to do this, but there's still a lot of big missing features in Sandstorm, and the UI hasn't settled down yet, so probably it's too early to start trying to translate things now -- the translations would be out-of-date too quickly and supporting them would probably slow down development. :/ But we definitely plan to do this within the next year!

**Comment by np** [comment]
What's the status of this? Can this be re-opened?

**Comment by kentonv** [comment]
Sorry, this is still on the backburner. We have a lot on our plate...
