### ISSUE TITLE
Remember set of open grains on update

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#833]
Currently, when a Sandstorm update occurs and the user clicks to reload, all their sidebar grain tabs are closed except the one they're currently on (that one is re-opened only by virtue of the grain route being hit on reload). We should integrate with Meteor's `Reload` package to save the list of grain IDs and restore them on reload, which should be pretty easy.

**Comment by neynah** [comment]
Is this issue safe to close now?

**Comment by jparyani** [comment]
Yes this has been fixed already.
