### ISSUE TITLE
Consider an uninstall script or sandstorm command

### ISSUE THREAD

**Issue by zoowar** [sandstorm-io/sandstorm#84]
Installing the easy way states: This will install a self-contained and (optionally) auto-updating Sandstorm bundle. It won't touch anything on your system other than your chosen installation directory and (optional) init script.

In addition to the optional init script, the installation process for a root install modifies /usr/local/bin by adding symbolic links to "sandstorm" and "spk".

Consider an uninstall script or sandstorm command

**Comment by paulproteus** [comment]
Hi @zoowar -- thanks for filing this!

The least we could do here is have a wiki page that explains how to uninstall Sandstorm. I believe that the steps are:

* Stop Sandstorm, then
* Back up your apps and data if you want them, and then
* Remove `/opt/sandstorm` (or wherever the Sandstorm directory is), and
* Remove the init script and/or systemd service, and
* Remove the `/usr/local/bin/sandstorm` symlink.

@kentonv does that match your understanding?

Do you have an opinion on "write uninstall script" vs. "write wiki page"?

**Comment by kentonv** [comment]
I think an uninstall script should remove only the files the install script / auto-updater created, so:

* `/opt/sandstorm/sandstorm-*` (the installed bundles)
* `/opt/sandstorm/{sandstorm,latest,sandstorm.conf}`
* `/usr/local/bin/{sandstorm,spk}` (installed symlinks)
* `/etc/init.d/sandstorm` and any `rc.d` links to it (or systemd equivalents)

Don't delete `/opt/sandstorm/var`, where all the user data lives. This way if they re-install Sandstorm later it will pick up where it left off.

This should be easy to implement as a subcommand, e.g. `sandstorm uninstall`.

**Comment by paulproteus** [comment]
​I'm vaguely pro the installer leaving a file called

/opt/sandstorm/.installed-files-list

behind, so that the uninstaller can use that as a reference. I like the
subcommand idea.

**Comment by zoowar** [comment]
Is there a reason user data isn't being stored in /var/lib/sandstorm? While we're on the subject of user data: Is there an option to specify the user data directory during installation (sorry, I haven't installed sandstorm in a long time)? For example, I store all my user data in a raid 1 filesystem.

**Comment by paulproteus** [comment]
I think for now, the answer is: we hadn't really thought about it, and we
want to make sure the install remains as easy as possible.

I like the idea of using /var for this stuff. There's a conflict between
"Make sure the system is easy to install and uninstall" and "help people
customize the install to suit their needs".

I think what I'd suggest is that we have an "Advanced installation guide"
that we link to at the end of the easy install that remarks that if you
want things like FHS compliance, you can do things like:

* Stop sandstorm
* mv /opt/sandstorm/var /var/lib/sandstorm
* ln -s /var/lib/sandstorm /opt/sandstorm/var
* Start sandstorm

What do you think of that, zoowar?

**Comment by kentonv** [comment]
> Is there a reason user data isn't being stored in /var/lib/sandstorm?

I agree that's probably more FHS-correct, but it's not entirely clear how Sandstorm fits into FHS given our update strategy.

Since Sandstorm likes to auto-update, you could argue that *all* of `/opt/sandstorm` really belongs under `/var`.

I think the reason I chose `/opt` is because Sandstorm really wants to own its section of the filesystem, and it seemed like `/opt` is the place for things that own their section of the filesystem. But in retrospect that logic may be flawed. Perhaps `/var/lib/sandstorm` would have been the correct default install location.

FWIW, the installer script prompts for install location so you can easily specify `/var/lib/sandstorm` if you want. I'd rather tell people to do that than set up a symlink from `/opt/sandstorm/var`.

**Comment by zoowar** [comment]
@paulproteus Quick correction: If we're talking "FHS-correct", then my comment https://github.com/sandstorm-io/sandstorm/issues/84#issuecomment-73288728 should refer to "/var/opt/sandstorm" (notice "opt" rather than "lib").

Additional worm: You might want to preserve sandstorm.conf (which, if we're talking "FHS-correct", would be located in /etc/opt/sandstorm.

Note on install (you can skip this, as it is all opinion): I think technical or advanced users are either comfortable with manual activities or accept the risk of what they are doing. Non technical users are confused by questions. IMO the objective of easy install should be to install software with sane defaults and only query the user with meaningful questions. Even when a question has a sane default, asking it can lead to a confused user. Non technical users want to push a button.

Back to your question (possibly more worms): There are various methods to accomplish this. What you suggest is reasonable. An alternative to the symbolic link you suggest could be a configuration variable, say SANDSTORM_DATA, in sandstorm.conf. This would also simplify the re-install case as the install script can look for sandstorm.conf. There is also XDG (see, more worms) to consider when installing as a user rather than root. http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html Anyway, I'm just sharing thoughts, not expectations. Keep up the good work.

Are we talking "FHS-correct"? I don't think so. It would be nice if more projects did. Sane standards are a good thing.

**Comment by zoowar** [comment]
@kentonv I like that /opt was chosen, too few projects think about what they are doing. I believe installing sandstorm in /opt is correct. The software does not "change in normal operation", so it is not considered variable.

**Comment by benyanke** [comment]
I agree, leaving behind an .installed-files-list file would be a good idea.

**Comment by paulproteus** [comment]
Hi all,

With the creation of the `sandstorm uninstall` command, and documentation at https://docs.sandstorm.io/en/latest/install/#uninstall , I'm going to close this issue.

Thanks for asking for this and providing thoughts, all!
