### ISSUE TITLE
App sorting should be case-insensitive

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#846]
Poor draw.io is last on the list.

**Comment by paulproteus** [comment]
Per e.g. https://forums.meteor.com/t/how-to-perform-case-insensitive-sorting/1103 https://stackoverflow.com/questions/12205546/meteor-sort-case-insensitive?rq=1 https://github.com/aldeed/meteor-tabular/issues/66 this might require a data migration.

**Comment by kentonv** [comment]
@paulproteus Nah, this is all client-side, so we can just fetch the whole list into an array and sort it.

PS love this typo from your first link: "In mongodb demoralization and duplication is common."
