### ISSUE TITLE
Uploading backups and profile pictures fails in Chrome

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#851]
Roughly 25% of the time, nothing happens after I select a file in the file picker.

The problem goes away if I delete these lines:
https://github.com/sandstorm-io/sandstorm/blob/5f6de637f6420d4c4c051f08bf7dadd5f197b33e/shell/shared/shell.js#L762
https://github.com/sandstorm-io/sandstorm/blob/5f6de637f6420d4c4c051f08bf7dadd5f197b33e/shell/packages/sandstorm-accounts-ui/account-settings.js#L184

It seems that the input element is getting garbage-collected before it can fire its "change" event.

**Comment by kentonv** [comment]
Hmm. Originally we didn't link the element into the DOM at all. We only started doing that to satisfy IE. Interesting that adding and then removing it causes it to get cleaned up differently than not adding it at all.

We could move the unlink to happen during the "change" event callback but I'm not sure how to get notification if the user cancels the dialog.

**Comment by dwrensha** [comment]
If I get rid of both `document.body.appendChild(input)` and `document.body.removeChild(input)` it still doesn't work much of the time. I think what happened here is that the garbage collector became more aggressive on some recent Chrome release.

**Comment by zarvox** [comment]
Is there an issue with having the interactive element that needs to possibly upload a file also provide the `<input>` element in its template?  This seems like a cleaner way to deal with `<input>` lifetimes than inserting the tag and immediately removing it.

**Comment by kentonv** [comment]
@zarvox Yeah that sounds like it should be doable in all cases.
