### ISSUE TITLE
Patching/Fixing a bug in an installed instance of Wekan

### ISSUE THREAD

**Issue by partoneoftwo** [sandstorm-io/sandstorm#852]
Hi

I filed a bug that I found in Wekan, and the developers over there had already fixed the bug in a future/next release.

They said they would post a Wekan .spk "in a few days" [which is fantastic, couldn't be happier as a user]. 

In the meantime I wanted to see if I could do the patch on my own Wekan installation running on Sandstorm. It's a really simple bugfix changing only two lines.

I am writing here because I think this is a more Sandstorm specific question than Wekan.

In the Sandstorm install of Wekan - where is the file `client/components/activities/comments.js`?
The bugfix I am trying to do is this one:
`-            boardId: this.boardId,`
`-            cardId: this._id,`
`+            boardId: this.currentData().boardId,`
`+            cardId: this.currentData()._id,`

I have grepped, and looked "everywhere" in the entire /opt/sandstorm/ folder without finding the right file.

| Some links | Where |
| --- | --- |
| [The bug in question](https://github.com/wekan/wekan/issues/270) | Github |
| [The bugfix I am trying to do manually](https://github.com/wekan/wekan/commit/549f8fee3aee3675ae2c04fa14b88f4a783df2c6) | Github |

Thanks in advance!

**Comment by paulproteus** [comment]
Hi there! The best thing is to go to the app market and visit WeKan, and
then look for a "Code" link, which will take you to a GitHub page.

There, you'll see that you can download WeKan yourself and run the
meteor-spk tool to create a package.

I hope that helps; let me know if you need more info!

I'm glad you're asking these questions, btw. It's nice when people take the
open-source nature of Sandstorm & Sandstorm apps seriously.

**Comment by JamborJan** [comment]
Btw. making the spk will work with a different app id if you follow the instructions but you cannot update the app on your instance since you probably don't have the secret keys for creating the spk matching the original app id.

**Comment by paulproteus** [comment]
But you can export the data, then modify the ZIP file that is the backup
file to match your new Sandstorm package ID, then re-upload the ZIP file
and it'll create a grain of your modified app.

**Comment by JamborJan** [comment]
Are you sure? I thought it will check the app id the backup has been created with.

**Comment by JamborJan** [comment]
Sorry idiotic comment. Sure what you say works.

**Comment by ocdtrekkie** [comment]
I'm going to close this one. Editing apps in place on the server is pretty hacky. You can package your own fork of Wekan and then modify a backup to use it, but that presents challenges for switching back to the main version later, and breaks all the sharing links people may be using.

Currently, Wekan releases are pushed extremely often to the experimental app market, so its unlikely someone would currently need to do this anyhow. I believe @xet7 has this release path down pat.
