### ISSUE TITLE
Should `modprobe fuse` if /dev/fuse is not available

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#858]
Symptoms:

When doing `sudo sandstorm start`, Sandstorm appears to start, then immediately crashes.

The following appears in `sandstorm.log`:

```
*** Uncaught exception ***
sandstorm/run-bundle.c++:1110: failed: mount("/dev/fuse", "dev/fuse", nullptr, MS_BIND, 
                     nullptr): No such file or directory
stack: 0x547433 0x546d2f 0x560c10 0x55fdc9 0x55fdba 0x514a21 0x5156a5
** Server monitor died. Aborting.
```

Indeed, my system didn't have a `/dev/fuse`:

```
root@localhost:/home/vagrant# ls -l /dev/fuse
ls: cannot access /dev/fuse: No such file or directory
```

Doing `modprobe fuse` causes it to grow one.

```
root@localhost:/home/vagrant# modprobe fuse
root@localhost:/home/vagrant# ls -l /dev/fuse
crw-rw-rw- 1 root root 10, 229 Sep  9 19:09 /dev/fuse
```

@kentonv believes the most reasonable fix here is for `run-bundle` to directly call `modprobe fuse`, presumably only in the case that `/dev/fuse` is missing. I'm +1 on that.

**Comment by paulproteus** [comment]
Just ran into this while running the tests. Will work around it for now, but yuck.

**Comment by paulproteus** [comment]
In #1156 we see a message from someone for whom `modprobe` doesn't work (no `modules.dep`)

Therefore I suggest that we emphasize _disabling_ the FUSE functionality, rather than emphasizing _auto-modprobe-ing_.

Details TBD but I wanted to leave that note here.

**Comment by kentonv** [comment]
The line that is failing is merely trying to bind-mount /dev/fuse into the Sandstorm self-container, for possible later use by spk dev. It would be entirely reasonable to skip that line if /dev/fuse doesn't exist.

**Comment by paulproteus** [comment]
/usr/bin/yes​
