### ISSUE TITLE
Change "Save this link" text (not yet logged in)

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#862]
Currently "Save this link" has proven to be 14minutes worth of confusing for users attempting to Sign in. Any suggestions here @paulproteus? Maybe we can go back to "Sign in to....[valuable thing]"

![image](https://cloud.githubusercontent.com/assets/855341/9778281/282f5bb4-5723-11e5-986c-9950c6935974.png)

**Comment by paulproteus** [comment]
Maybe

Save this link now. Sign up (down arrow)


or


Save this link now. Sign in (down arrow)


or

Save this to your account. Sign up (down arrow)



all in the same purple background with white text.


I could also live with going back to "Sign in (down arrow)"

**Comment by neynah** [comment]
I could live with any of the above suggestions.
Some other options:
"Save this grain to your account. Sign up"
"Sign up for Free"
"Sign up to save this grain."

**Comment by kentonv** [comment]
This is fixed now (it just says "Sign In").
