### ISSUE TITLE
App Market should be more visible/accessible in Oasis

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#864]
We should make discovering the App Market easier from the shell - new users especially are going to be visiting this often, and experienced users may want to browse for apps.

It's possible that the current styling can confuse "Install" as an app itself.

Possibilities:
- separate the install app from app market icon from the App List
- add a tab in the side bar that links directly to the App Market
- style the install icon differently and use the app market icon
...

![image](https://cloud.githubusercontent.com/assets/855341/9796603/f5742f40-57ab-11e5-9411-4b7e6c752e0b.png)

**Comment by paulproteus** [comment]
One possibly-interesting thing is that on my Android device, the App Market
is indeed an app within my phone, whereas on Sandstorm, the App Market is a
separate website entirely.

**Comment by neynah** [comment]
Good point. Drew and I discussed yesterday that we think there's an issue with flow between sandstorm.io, oasis, and the app market. I don't see any obvious fixes for that but perhaps if the App Market will stay as a separate website, we should style the "Install" differently than an app. If for example we had the App Market within Oasis itself then maybe it makes sense to have it appear as an app.

**Comment by bytristanthomas** [comment]
I think @paulproteus has hit the nail on the head - IMO the app market should be available within Sandstorm (Oasis/self-hosted) and an app market link be added to the new sidebar design, possibly above the Apps button. The more people use the app market and find apps they like, the more likely they are to a) continue using Sandstorm and b) port/encourage others to port more apps to Sandstorm.

**Comment by neynah** [comment]
For now, user testing indicates that our revised design of highlighting the "Install from App Market" button improves discoverability for now. I will re-open this in the future if we continue to have issues.
