### ISSUE TITLE
WordPress: Error when trying to upload a theme

### ISSUE THREAD

**Issue by alisalaah** [sandstorm-io/sandstorm#866]
After uploading a theme I get the page "Are you sure you want to do this?" but with nothing to click.

When navigating back to the Add Theme page to try again I get a blank page that says "No such grain for public ID: ... [404]" only on the page where you would upload a theme.

If I restart the grain and go back then I can attempt to upload again but with same result.  I tried a new grain and got the same behavior.

**Comment by dwrensha** [comment]
Hi. I've opened this issue on the wordpress-sandstorm repo:
https://github.com/dwrensha/wordpress-sandstorm/issues/9
