### ISSUE TITLE
Proposal for new sidebar design

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#872]
The 3rd sidebar is my choice for the expanded version. The 4th sidebar is a compact version which displays by clicking the arrow.

![shelldoc-sidebar-toggle1](https://cloud.githubusercontent.com/assets/855341/10890685/40403912-814e-11e5-8357-25946db0d5d6.png)

**Comment by paulproteus** [comment]
I'm +1​ fwiw

**Comment by ocdtrekkie** [comment]
I am totally +1 on having a thinner sidebar for those of us who already know what we want to click on.

**Comment by kentonv** [comment]
Agreed with everything.

(Nitpick: Presumably we'll remove the down-triangle under the sandstorm logo since it will no longer control the sidebar.)

**Comment by ocdtrekkie** [comment]
Isn't it still practical to completely hide the sidebar for some applications? I guess if someone is going to stream video we need more of a straight full-screen option. 

Though this bar is thin enough I can probably be cool with it being there all the time.

**Comment by neynah** [comment]
Awh I was just about to make a correction. Oops. Yes the triangle under the Sandstorm logo should be removed. :)

**Comment by zarvox** [comment]
@ocdtrekkie In our user testing, we found that many folks have a very strong reflex to click the logo at the top left to attempt to go "back" or "home".  Having that toggle the navbar was nonintuitive (and hard for users to discover), so we plan to instead make the logo/text send you to wherever you'd go automatically immediately after logging in.  But then we need something else to toggle navbar visibility.

None of the places in the topbar are good at cluing that they toggle the navbar's visibility, and overlaying a button over the grain means that those are pixels the app can't use, which is also undesireable.  So instead we'll steal a narrow column of pixels from the side to put the navbar-toggling button there, and we'll increase the utility of that space by making the nav buttons still operable at the narrow width.

**Comment by jadeqwang** [comment]
@neynah The 3rd one is my fave too.

**Comment by zarvox** [comment]
Oh, this design also makes it theoretically possible to animate the show/hide of the navbar now.

**Comment by zarvox** [comment]
Looking at this again: it might be kinda weird/difficult for people to find the collapse/expand arrow in the middle of the sidebar.  Perhaps it makes more sense for us to put it all the way at the top or bottom?  Those tend to be where controls are more commonly found.

(This should be super easy to play with once the rest is implemented, so I'm not going to worry about it for now)

**Comment by neynah** [comment]
I think the only downside to that is we wouldn't have that middle grey section as a divider. (Unless we leave it anyway and just not have anything there). If it's top or bottom, I'd say top because if it's below the grains and its location is dependent on the number of grains above it, its placement will change(which is inconsistent) and if it's consistently at the very bottom left then it's possible people won't see it.

**Comment by kentonv** [comment]
I think visual users won't have any trouble finding it where it is. Not sure about non-visual users.

**Comment by kentonv** [comment]
Durr, non-visual users won't care about collapsing the sidebar anyway.

**Comment by zarvox** [comment]
Something to be aware of: non-visual users may still care about the lost pixels if we (or apps!) show/hide page components based on responsive snap points depending on frame width.  Nolan hit this specifically with GitLab, which doesn't show the clone instructions if the frame width is less than ~750px.

**Comment by paulproteus** [comment]
BTW, I wonder if "information scent" suggests that we should write "Grains" and "Apps" in the top navbar itself.

**Comment by shamrin** [comment]
Looks nice! I also prefer the third sidebar, with triangle under Sandstorm logo removed. (But I'm not longer a fresh user, so be careful.) By the way, what will the battery icon do?

(Totally missed this issue when I was submitting #1104.)

**Comment by ocdtrekkie** [comment]
@shamrin Battery icon refers to GBrhs (Gigabye-RAM-Hours). From the Indiegogo campaign:

What is GBrh?

Gigabyte RAM hours. This is how Sandstorm shared hosts parcel out compute resources. A shared host only charges you for time that an app is actually running, which usually means only the time during which you have the app open in your browser. If an app uses 1GB of RAM (on the server) for one hour, then it expends 1 GBrh. If it uses 1GB for two hours, or 2GB for one hour, then it expends 2GBrh, and so on.

A typical Sandstorm subscription comes with 200 GBrh per month. Meanwhile, a typical app server in our experience uses around 100MB of RAM. At such a rate, you would need to keep three apps open for the entire month to go over your limit. Only the most demanding users are likely to hit this limit. The Sandstorm UI will feature a battery indicator to warn you when you are running low.

Sandstorm does not meter CPU time but may dynamically adjust scheduling priorities to keep things fair. Users whose monthly GBrh limit is higher will also tend to get higher CPU priority, but users who hog excessive CPU time will get lower priority.

Of course, if you choose to run your own Sandstorm instance on your own machine, none of this applies.
