### ISSUE TITLE
Porting ownCloud

### ISSUE THREAD

**Issue by jancborchardt** [sandstorm-io/sandstorm#89]
I’m trying to port ownCloud to Sandstorm at the moment but have some problems/questions regarding the [porting guide](https://github.com/sandstorm-io/sandstorm/wiki/Porting-Guide):
- The demo command `spk init -p 10000 -- node main.js` isn’t really applicable since the default port is just 80 and the app runs by default (simple LAMP). Do we have to define a specific port and a launch command – if so, how?
- dependencies (and submodules) aren’t mentioned anywhere – how are they handled?
- permissions neither
- setting up a user account and choosing/configuring the database

To answer these questions I had a look at the Wordpress port: https://github.com/dwrensha/wordpress-sandstorm/commits/master – but it’s very specific and a lot of customization, so is there any general documentation on this?

I do have a script to handle dependencies, permissions and pulling of apps: https://github.com/jancborchardt/owncloud-scripts/blob/master/owncloud-setup.sh could that be used?

(Also cc @DeepDiver1975 @PVince81 from ownCloud for info.)

**Comment by JamborJan** [comment]
Hi @jancborchardt,

What is your status of porting ownCloud? I'm planning to look into this also but if you have already a usable status somehow it would be good to share your findings instead of starting from zero again. 

Thanks!

**Comment by jancborchardt** [comment]
@JamborJan I didn’t look further into it yet. If you want to take it over please go ahead. :) For any questions about ownCloud, come join #owncloud-dev on IRC.

**Comment by JamborJan** [comment]
Ok I start working on that. I assume it will take some time but let's see.

@kentonv I'm not sure what you need to do here but from my point of view the issue can be closed. Unless you want to track the status of the ownCloud port with it.

**Comment by jancborchardt** [comment]
@JamborJan great stuff, thanks a bunch!

**Comment by paulproteus** [comment]
Hi JJ!​

Are you willing to test out using "vagrant-spk" for this?

https://github.com/zarvox/vagrant-spk +
https://github.com/sandstorm-io/sandstorm/wiki/Porting-an-app-with-vagrant-spk


Drew did some work on the tool recently, and I'd be very grateful if you
can try it and let us know how you like it.

It should resolve a lot of the issues that made your last package hard to
create, so I'm very hopeful that you can test it out and see if it actually
makes things easier.

Cheers!

**Comment by JamborJan** [comment]
Hi @paulproteus,

I plan to package the app sandstorm friendly and maybe will try to use sqlite as database to save ressources.

The vagrant-spk tool sounds good. I will check it out and hope that the mentioned focus on php and mysql is not limiting me now and I can use sqlite.

The process via Docker worked for me pretty well at the end with my last port. It was a normal learning process which delayed the whole thing.

**Comment by zarvox** [comment]
Hi!  Just to let you know, due to technical limitations, I had to make some changes to how the tool works, which makes the wiki page instructions slightly out of date.  I'll try adding a README to vagrant-spk and updating the wiki soon.

**Comment by JamborJan** [comment]
@paulproteus vagrant-spk setup was pretty easy so far. Will continue with that and report my experience and findings.

@zarvox it would be awesome to be able to select somehow which database engine to use and other options. I will fork your repo and try to figure something out and make some suggestions.

**Comment by ChrislS** [comment]
Thumbs up for the project, I hope you succeed! :)

Just a note on the database engine: I see the advantage of sqlite, especially concerning data locality and portability. There are some Owncloud plugins, however, that _only_ work with a MySQL backend. So it would be great to have the option to choose the MySQL backend, even it it's then necessary to do some additional steps and get the server configured...

**Comment by JamborJan** [comment]
@ChrislS do you know which plugins for example? I'm not done with the decision yet and if there are good reasons to not use sqlite then I don't see why not sticking to mysql.

**Comment by jancborchardt** [comment]
@JamborJan for performance reasons we recommend using MySQL for any setups with multiple users or syncing with multiple clients. SQLite is ok for single-user setups or dev setups, but when it’s on Sandstorm it’s best to just use MySQL.

**Comment by ChrislS** [comment]
I am certainly no owncloud poweruser, so I don't have a good overview over the general requirements of plugins. I happen to know, though, that the Passman app (https://apps.owncloud.com/content/show.php/Passman?content=166285) only works with the MySQL backend.

**Comment by JamborJan** [comment]
OK, makes at least some steps easier as https://github.com/zarvox/vagrant-spk has mysql already by default.

**Comment by JamborJan** [comment]
Status: 
https://github.com/JamborJan/vagrant-spk
https://github.com/JamborJan/owncloud-sandstorm

Nothing is working so far. When you build the app it actually wants to download the index php and the database is not up and running, I think I screwed up my vagrant-spk fork. I will check this in more detail later. Everybody who is interested can have a look.

**Comment by ocdtrekkie** [comment]
As a cool thing, Davros being compatible with the ownCloud client means we have a clear working pattern to ensure ownCloud's clients will work with ownCloud on Sandstorm as well. :)

**Comment by JamborJan** [comment]
I'm happy that Davros has been released as I'm not able to do further development / investigation at the moment. Maybe someone else (or I later) can pick up the work from here to ensure that there is more than one solution.

**Comment by paulproteus** [comment]
Hi all! I'm going to remove the documentation tag here, since with the existence of `vagrant-spk` and a PHP-specific packaging stack, I think that docs are not the main issue, or at least, if they are, I want someone to tell me how the docs didn't work for them.

Details on PHP packaging with `vagrant-spk`: https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/

**Comment by KuenzelIT** [comment]
Is there any progress for the owncloud app? Is there still someone trying to port it?

**Comment by ocdtrekkie** [comment]
Nobody I know of is working on it.

**Comment by jancborchardt** [comment]
If someone picks it up, note that Owncloud was forked by the majority of the core developers and community into [Nextcloud](https://nextcloud.com). :) Our code is at https://github.com/nextcloud and if there's any questions, we hang out in #nextcloud-dev on freenode IRC.

**Comment by ocdtrekkie** [comment]
I think I am going to close these. I gave Nextcloud a try recently, and it's very, very much more than ideally should run inside a Sandstorm container, to the extent that it's largely an app platform of it's own at this point. I know it's a popular request, so if someone was to successfully package it, I think it'd be sensible to allow it in the market, but I don't think we want to consider it an issue that it's not present or dedicate the Sandstorm community's limited resources to packaging it.
