### ISSUE TITLE
Remember "currently open" grains somehow

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#894]
Sometimes, when I mean to restart a grain, I accidentally hit refresh on the browser. This closes all the grains I had open, and it takes me a while to get my state back.

Suggestion: maybe we can find a way to remember the list of currently open grains so that if I hit refresh, it will automatically start loading the grains I already open (kinda like Chrome's way of restoring pinned tabs). Maybe this can be a session variable?

**Comment by neynah** [comment]
Refresh the browser and your grains will still be listed in the sidebar now! https://github.com/sandstorm-io/sandstorm/pull/1646
