### ISSUE TITLE
Wildcard DNS configuration breaks application under certain conditions

### ISSUE THREAD

**Issue by find-evil** [sandstorm-io/sandstorm#899]
I sometimes need to isolate systems completely from the internet. In this particular instance, wildcard DNS is breaking since I do not have DNS resolution on the network for this particular system. I am also unable to use a service such as xip.io that is hosted externally since the system will be isolated from the internet. I can hack something together to fix this problem, so I wouldn't call it a true issue or bug, just a configuration oddity.

It would be useful to have a docs page that explains how to configure the system/particular gotchas for a completely disconnected or "isolated" mode of operation.

**Comment by ocdtrekkie** [comment]
I would love some advice on this as well!

**Comment by ocdtrekkie** [comment]
https://docs.sandstorm.io/en/latest/administering/offline/ exists now, though we don't consider setting up a DNS server with wildcard DNS support to be within the scope of our documentation.
