### ISSUE TITLE
Frame restrictions prevent remoteStorage apps from being run

### ISSUE THREAD

**Issue by jancborchardt** [sandstorm-io/sandstorm#90]
I want to port [Litewrite](http://litewrite.net) to Sandstorm. When trying to connect to my [remoteStorage](http://remotestorage.io), I got the following error:

```
Refused to display 'https://5apps.com/users/sign_in' in a frame
because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

The remoteStorage library uses OAuth, so it redirects to the provider for log in and then redirects back. Is there a possibility for apps to say it’s ok to redirect? Or what do you recommend we do?

cc @michielbdejong @skddc @galfert for @remoteStorage

**Comment by ocdtrekkie** [comment]
I think I'm going to close this one, as it pertained to how to have an app on Sandstorm store it's data on some other server, when the preferred Sandstorm model would be to be the place your apps and data are securely stored.

Arguably, someone could make a remoteStorage app that stored it's data on Sandstorm using said spec, but then you'd risk losing the way to understand your data if the web app went away. It's also preferable in this case for your Sandstorm server to host your app as well.

Also, the Powerbox does exist now, and so allowing HTTP requests between apps and other servers is now possible. https://github.com/zenhack/hello-sandstorm-oauth is a great example app.
