### ISSUE TITLE
Oasis: When billing prompt first shows, clicking "free" causes error alert

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#912]
When a new user first reaches the billing prompt, if they click on the "free" plan (i.e. to keep the plan they already have), a window.alert tells them: "Error: User must have stripe data already." This is because choosing the "free" plan does not prompt for a credit card (it's free), but the server-side code to change plans prematurely expects a credit card on file.

Of course, since they're already on the free plan, they can get the same effect by closing the popup, but the error is confusing.

**Comment by paulproteus** [comment]
@jparyani do you know if this is fixed yet? Fine if not, just thought I'd ask.

**Comment by jparyani** [comment]
Yep, this was fixed a while ago.

**Comment by paulproteus** [comment]
Yay!
