### ISSUE TITLE
How to uninstall sandstorm from command line

### ISSUE THREAD

**Issue by shashank-k** [sandstorm-io/sandstorm#915]
Is there a way to uninstall sandstorm from command line? 

I am getting the below error message, checked [https://github.com/sandstorm-io/sandstorm/issues/659]  and thinking of a fresh install.

    connect(): Permission denied; toString() = unix:/var/sandstorm/socket/backend

Are there any other suggestions for this. Thanks!

**Comment by dwrensha** [comment]
Did you install on top of an existing install? If so, you maybe be running into #660. Sorry about that.

Getting your install to work might be as easy as changing the ownership of /var/sandstorm/socket to root:sandstorm.

If that doesn't work, you can uninstall with

```
sudo sandstorm stop
sudo rm -rf /opt/sandstorm
```

and then reinstall.

**Comment by dwrensha** [comment]
I should clarify: the directory that Sandstorm sees as /var/sandstorm/socket will be at /opt/sandstorm/var/sandstorm/socket on your system.

**Comment by shashank-k** [comment]
@dwrensha Yes you are right. I did an install on top of existing install. I will try your suggestions and then close this. Thanks!

**Comment by paulproteus** [comment]
Hi @shashank-k ,

I hope you were able to get your server issues resolved! For now I'll close this, since I think the double-install issue is what was biting you.

I hope you'll leave a comment saying if you got your issues resolved!
