### ISSUE TITLE
Where did task list applications dissapear from app store?

### ISSUE THREAD

**Issue by JakubBily** [sandstorm-io/sandstorm#916]
Hey there, few weeks ago, there were two task list apps (I dont remember the names :( ) which I quite liked and it was one of the reasons, I would install Sandstorm. I just installed sandstorm again yesterday and the apps are not there. What happened? Anyone any information? Will we have them back? Any replacement? Thanks

**Comment by paulproteus** [comment]
Hi Jakub! I maintained one of them ("Meteor Todos") and can put it back
shortly. In fact, let me work on that now. The other one might be
LibreBoard. It got renamed into WeKan, but it's the same underlying code.
So there's good news for you there.

What happened was that we had a new way to host information about Sandstorm
apps (some more information is here
https://blog.sandstorm.io/news/2015-08-31-oasis-beta-launch.html & here
https://docs.sandstorm.io/en/latest/developing/publishing-apps/ ).

Hope that helps! Let me know if you have more questions.

**Comment by JakubBily** [comment]
Great! The one I was looking for was Meteor Todos. Would love to have it back :)

**Comment by paulproteus** [comment]
As a temporary workaround, you can use Meteor Todos by visiting this page:

https://sandstorm.io/apps/index.html

and installing it via the old app install interface.

Don't rely on that for too long, though, as it might go away sometime.

**Comment by paulproteus** [comment]
@neynah says this is closed, so I am going to mark it as such!
