### ISSUE TITLE
Logging in with GitHub returns error

### ISSUE THREAD

**Issue by newswim** [sandstorm-io/sandstorm#921]
This is probably known and due to the default guest account I must've been automatically using. But just for posterity, right now if I'm not signed in with sandstorm, start a demo, sign in to github, the running demo instance bugs out:

`Internal server error [500]`

I can create a new one and works fine, just wanted to bring this to your attention. Awesome service!!

**Comment by kentonv** [comment]
Hi Dan,

This isn't known; thanks for reporting it!

To be clear, when you say "the running demo instance bugs out", do you mean the app view breaks, or Sandstorm itself breaks? If it's the app, which app were you using?

**Comment by newswim** [comment]
The app view breaks. Telescope demo. There have been several new releases of Telescope, might be something with the version used by Sandstorm? Cheers!

**Comment by kentonv** [comment]
Oh my, indeed, it is broken. It turns out this is another symptom of the same bug that is causing the "download backup" button not to work. We have a fix ready (2ae0e3f0ef040b22bddc66a1c93e4f2bf2474e52) which will be pushed tonight. Sorry about that!

**Comment by kentonv** [comment]
Fixed now! Thanks.
