### ISSUE TITLE
Nginx config : invalid server name or wildcard "sandstorm-*

### ISSUE THREAD

**Issue by mrflos** [sandstorm-io/sandstorm#924]
Hi,
I try to run my own sandstorm server, so I adapted your github source example https://github.com/sandstorm-io/sandstorm/blob/master/nginx-example.conf#L25

```
server_name alpha.sandstorm.io alpha-*.sandstorm.io;
```

to 

```
server_name sandstorm.coop.tools sandstorm-*.coop.tools;
```

and I can't save :
```
nginx -t
nginx: [emerg] invalid server name or wildcard "sandstorm-*.coop.tools
```

So i changed to : 
```
server_name sandstorm.coop.tools *.sandstorm.coop.tools;
```

Now I can access all my sandstrom apps from http://sandstorm.coop.tools , but my dns entries for http://blog.coop.tools doesn't send me to the ghost blog declared here :

```
blog.coop.tools IN CNAME xql6hui0fqaguiazpnk3.sandstorm.coop.tools
sandstorm-www.blog.coop.tools IN TXT xql6hui0fqaguiazpnk3
```

Maybe it is 2 different problems, but I m not an expert, in any case the example brings me an nginx config error.
Tested with nginx 1.6.* and 1.9.3

**Comment by kentonv** [comment]
Urgh, it appears that our real config looks like tihs:

    server_name alpha.sandstorm.io ~^alpha-[^.]*\.sandstorm\.io$;

But somewhere along the way, the example ended up broken, and no one noticed.

**Comment by kentonv** [comment]
Fixed now. Sorry about that!

**Comment by mrflos** [comment]
I still had to add wildcards to nginx, in order to get, for example, the static content from sandstorm UI:

`server_name alpha.sandstorm.io ~^alpha-[^.]*\.sandstorm\.io$ *.alpha.sandstorm.io;`

Thanks @kentonv for making this right!
