### ISSUE TITLE
Get Sandstorm's built-in HTTPS to A or A+

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#941]
Filing this bug so I don't forget about it.

**Comment by kentonv** [comment]
It appears that Node 0.10.x does not support either DHE or ECDHE. Later versions support both, but Meteor is stuck on 0.10.x. This is sad. We need to convince them to update.

https://github.com/meteor/meteor/issues/3666

**Comment by ocdtrekkie** [comment]
I got an A when testing a Sandcats server. However, it states that "This server supports TLS 1.0 and TLS 1.1. Grade will be capped to B from January 2020." So we may wish to disallow TLS 1.0 and TLS 1.1. A lot of entities have done so this past year anyways, so people relying on it are going to have a bad time in a lot of places.

**Comment by ocdtrekkie** [comment]
As previously noted, I just tested again and got a B. So we should look at disabling TLS 1.0/1.1 support ASAP, and then close this issue.

**Comment by ocdtrekkie** [comment]
In 0.263, Sandstorm once again gets an A. This is a moving target, so we need not keep this open further without a specific action item.
