### ISSUE TITLE
Can't flush inside Tracker.autorun

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/sandstorm#944]
Seeing this error fairly regularly. It always happens for me after attempting an app install but now I'm seeing it elsewhere too. I recognize this log is unhelpful, but it's all I'm getting via the minified JS. It happens after I click Install from the app market for any app, but Gitweb in this case:

```

GET https://nolan.sandcats.io/sockjs/info?cb=d9vev0xyxm
	
200 OK
		202ms	
7f9a8b1...b2e6.js (line 68)
detailed error: Error: Can't flush inside Tracker.autorun
error source line:
	

...cker.flush while flushing");if(p)throw new Error("Can't flush inside Tracker.aut...

	
7f9a8b1...b2e6.js (line 7, col 3077)
```

Sometimes I see this when simply loading the shell. Sometimes a reload makes it go away, sometimes not. This particular instance happened after a Firefox restart so it should have been a fairly clean slate.

**Comment by ndarilek** [comment]
So apparently I was viewing Sandstorm in a mobile view because I do my work on an 11-inch tablet. When I maximized the window and reloaded the instance, this plus another issue went away.

Maybe this issue only appears on smaller screens for some reason? Code selectively loaded or a slightly different path triggered somewhere?

**Comment by ndarilek** [comment]
Still seeing this regularly. I almost always have to reload every Sandstorm instance 2-3 times before the page appears. Unfortunately, it now also happens after the screen is maximized. Maybe that was just a lucky coincidence before. :(

**Comment by paulproteus** [comment]
Yikes​. Can you reproduce on Oasis? What browser + version?

**Comment by ndarilek** [comment]
I was able to reproduce on Oasis before, on my sandcats server and on 
multiple dev accounts, so it isn't tied to a single set of 
circumstances. Firefox 41.0.2.

I pinged this issue because earlier it was reliably reproducible, as in, 
I'd have to reload my dev server 4-5 times before the interface would 
render. If this error happens, it never renders no matter how long I 
wait. I have to reload.

In the interim I restarted Firefox and Thunderbird because both were 
consuming large amounts of CPU. Since then, I can't reproduce it at all. 
In my eternal quest to find a factor, I wonder if there's a race 
condition in front-end startup or something, and high CPU load causes 
something to flush while a subscription is being processed by an 
over-burdened browser? Maybe there's a condition that triggers if the 
front-end starts more slowly?

**Comment by ndarilek** [comment]
OK, in my continuing efforts to pin down what may be causing this, I have another possible factor--Firebug.

Hasn't happened for a while, so I wanted to mark it closed, but only if it didn't happen again for another indefinite while. :) I opened my grains list, pulled up Piwik for some debugging, opened Firebug, then opened another static Sandstorm-hosted site. I then hit my Sandstorm server root in another tab and boom, error again, always reproducible.

I'll try this again later to see if there's something to it, but it seems like opening Firebug drastically increases the likelihood of causing this.

**Comment by zarvox** [comment]
Hey, I just wanted to add a comment here to let you know that this hasn't disappeared into the ether.  I'm struggling to reproduce this on Linux, with the same version of Firefox and Firebug. :(

I guess the next step would be to try the same under Windows with NVDA, in case that's introducing some strangeness?  Or maybe cause my system to be under higher load, to see if I can trigger some race condition more reliably?

**Comment by ndarilek** [comment]
I don't want to close this just yet, but it has mysteriously stopped happening. If it doesn't happen again in the next week or so, I'll come back and close it.

**Comment by ndarilek** [comment]
Haven't duplicated at all for over a week. Guess this one fixed itself. :)
