### ISSUE TITLE
Allow setting an instance title

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/sandstorm#945]
Lately I find myself moving between 3 separate Sandstorm instances:

 * Oasis
 * An instance run by my company
 * My personal instance

It would be nice if each individual Sandstorm instance could have its own title. At the moment they're all just "Sandstorm" so I have to look to my addressbar to figure out which one I'm working with.

**Comment by ndarilek** [comment]
I see there's now a server title in settings for emails. Any chance this could also be picked up and placed in the `<title/>` tag as well?

**Comment by kentonv** [comment]
Good idea! I made a PR.

**Comment by kentonv** [comment]
(#1445)
