### ISSUE TITLE
sandstorm & nginx

### ISSUE THREAD

**Issue by christianreiss** [sandstorm-io/sandstorm#950]
Hey folks,

I have been beating myself with this issue: I have a server running sandstorm (in LAN, 10.1.0.31) and a nginx server that does reverse proxy.

nginx config: https://haste.alpha-labs.net/eyisemalik.nginx
sandstorm config: https://haste.alpha-labs.net/abezalokoy.ini

Both services "boot up" and I can log in, but none of the apps work, no installations work and no icons are displayed: https://cloud.alpha-labs.net/index.php/s/NFXikvJ9dFCKb22

Installed application just keep loading: https://cloud.alpha-labs.net/index.php/s/JblzKbESdVLnHH6

I am totally at a loss. Any help would be pure awesomeness! \o/

-Chris.

**Comment by kentonv** [comment]
Hi Christian,

If the shell interface works but apps don't, that usually means something is wrong with the wildcard host.

It looks to me like your nginx config may be incorrect. To match the wildcard, you need to use regex syntax. So you need to replace `*.sandstorm.alpha-labs.net` with `~^[^.]*\.sandstorm\.alpha-labs\.net$`.

Let me know if that helps.

(Our `nginx-example.conf` actually had this same error until fairly recently. :( )

**Comment by christianreiss** [comment]
Hey,

thanks for your reply. I changed the server name to
server_name               ~^[^.]*\.sandstorm\.alpha-labs\.net$ sandstorm.alpha-labs.net;
I also tried
server_name               sandstorm.alpha-labs.net ~^alpha-[^.]*\.sandstorm\.alpha-labs\.net$;
All yielding the same result. :(

**Comment by christianreiss** [comment]
Well I whacked it with a hammer and now its working some more. I see icons and can Install grains. Opening grains yields in white pages; The access log says 200 all the way. 

I am assuming some sort of X-Frame-Options limitation maybe?

**Comment by christianreiss** [comment]
Yep, exactly that. Hah. I hid an add_header directive in the main config :)
Issue solved.

**Comment by kentonv** [comment]
Ah hah! Indeed, that would break it. Sandstorm automatically sets x-frame-options on the main interface, FWIW.
