### ISSUE TITLE
"see <install-location>/var/log/sandstorm.log for details" -> link to log tab instead

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#952]
When testing SMTP on the admin panel, we sometimes report: "For internal server errors, see <install-location>/var/log/sandstorm.log for details."

Instead, we should link directly to the log tab, since we have that now.

**Comment by paulproteus** [comment]
+1

**Comment by timmc** [comment]
This happens when misconfiguring an OAuth client as well.
