### ISSUE TITLE
Initial account setup should appear even if not invited

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#954]
When someone first logs in, we prompt them to fill in profile details. It seems, though, that this prompt does not appear if they log into a self-hosted server until they've been invited. It should appear even for uninvited users (who can't install apps / create grains, but can receive shares).

**Comment by dwrensha** [comment]
Heh, I had noticed this on my multiple-identities branch, and I assumed it was something I had broken within the branch.

**Comment by timmc** [comment]
While I did not observe this myself, it was reported by someone signing on to an instance I had stood up -- he was very surprised by the profile screen popping up while he was poking around (after he had signed in with OAuth but before he was marked as invited.)

**Comment by dwrensha** [comment]
The profile confirmation now appears upon first sign-in for all users, even guest users.
