### ISSUE TITLE
keep the 'send' button around to make it easy to send the next invite

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#961]
I was writing a document and shared it with @neynah and @paulproteus .

![image](https://cloud.githubusercontent.com/assets/1584904/10242775/2a587d76-68a8-11e5-9472-9348647a7ce9.png)

A very natural thing to do after sharing it with one person (and writing a customized message), is to revise the message slightly to send it to the next collaborator. 

It would be awesome if the "send" button stays there (maybe make "successfully sent" a light green dismissible thing) so you can immediately send another invite without having to copy/paste your personal message, click "send more invites" and hope you didn't forget and copy something else onto your clipboard over it. :)

**Comment by zarvox** [comment]
+1.

I would love for the success/error message to

1. be visually distinct from the rest of the form,
2. be dismissable, and
3. give context about who was successfully invited.  "Successfully invited `<email>`, `<email>`, and `<email>`" would be helpful to remind you (if you're going through a list) who all you're sharing with.

One thing that I *do* want to avoid is sending multiple invitations if users double-click the button (as less-technical users frequently do).  Perhaps we can clear the "invitees" field on submit, especially if the success message echoes the users that were successfully invited?

**Comment by jadeqwang** [comment]
:+1: on what @zarvox said.

re: double-sending. I think the best way to solve that is the combination of "Successfully invited <email>, <email>, and <email>" and clearing the "invitee" field.

@dwrensha ?

**Comment by paulproteus** [comment]
Here's what we do right now:

click send an invite and you see

![send-more-invites](https://cloud.githubusercontent.com/assets/25457/12727156/73655c36-c8d0-11e5-8b1a-90e21db9b807.png)

click "Send more invites" and you see

![after-send-more-invites](https://cloud.githubusercontent.com/assets/25457/12727161/7b21084e-c8d0-11e5-9b60-4316f1256630.png)

**Comment by paulproteus** [comment]
I think this is pretty OK now, and will happily close.

**Comment by paulproteus** [comment]
@jadeqwang If you'd reply +1 to this to indicate you agree it's closed properly, that'd be great. Similarly if you think the issue remains, given these screenshots, then please re-open!
