### ISSUE TITLE
New sharing links invalidate old ones

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/sandstorm#962]
I tried to create two different sharing links for an etherpad document earlier. Right as I created the second one, the person using the first one had their permission revoked.

This is either a UI bug or a sandstorm bug. If revocation on new URL creation is the intended behaviour, then it should be easier to get at existing URLs. If it's not, then it shouldn't happen. :-p

**Comment by dwrensha** [comment]
A sharing link should only get revoked when the sharer clicks on the "X" button next to it in the "Who Has Access" view. What you've described is not the intended behavior.

I just now tried to recreate reproduce your problem but was unable to. I followed these steps:
1) start a new Etherpad grain
2) create a shareable link
3) open the link in an incognito window
4) create a new shareable link

In my case, after these steps, the incognito window still has access.

Can you provide me with more information to help we reproduce the problem?

**Comment by mrdomino** [comment]
I can't reproduce this either now, actually. Must've done something weird without realizing it. I'll reopen if it happens again.
