### ISSUE TITLE
Group Grains

### ISSUE THREAD

**Issue by bubalazi** [sandstorm-io/sandstorm#969]
As a user, I would like to see my single project related grains of different nature (wekan board, draw.io drawing etc) all combined in a single project view (folder, link).

Stretch 1: Utilities for combining grains (drag'n drop or move-to falldown menu or ...)

**Comment by neynah** [comment]
I would personally like this feature. I have many grains myself (from different apps) that I would like grouped together in some meaningful way. We could also accomplish this with tags perhaps.

**Comment by ar-jan** [comment]
There's a feature request for tags here #581.

**Comment by devon** [comment]
App use fixed position in /grains page works for me. the grains sort by 'Last Activity', the position of each grains change every time. I have to search it. There should be a dashboard page or grains with fixed position.

**Comment by kentonv** [comment]
Once the powerbox is ready, it will be possible to write a "folder app", whose purpose is to contain a group of grains.

**Comment by scubaccs** [comment]
If tags are to be implemented, something to consider might be that tags can be shared like grains.  That way any new grain with an already shared tag will automatically be available to the user.  This would be a way to mimic a shared folder.

**Comment by dwrensha** [comment]
@scubaccs: I'm currently on a "collections" app for this purpose: https://github.com/dwrensha/sandstorm-collections-app

The big obstacle right now is that it depends on https://github.com/sandstorm-io/sandstorm/pull/2027 and there are some open questions there to be resolved.

**Comment by dwrensha** [comment]
Closing, because we have released the Collections app: https://sandstorm.io/news/2016-08-09-collections-app
