### ISSUE TITLE
"Confirm your profile" page doesn't give guidance on acceptable handle formats

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#976]
It just shows "please match the requested format" but doesn't say what that might include.

![screenshot](https://cloud.githubusercontent.com/assets/307325/10295300/a8e8fdd6-6b74-11e5-87e4-dd89dbd464d2.png)

**Comment by neynah** [comment]
I agree this should show.

Also, unrelatedly... does the dropdown button for "preferred pronoun" actually look like that?

**Comment by zarvox** [comment]
On my screen, it does!

I suspect the option fields are missing some relevant style, and my high-DPI screen is wreaking havoc.

Similarly, the button is using the default browser style - I would love for us to have some consistent, attractive text buttons to use in various places. :)

**Comment by kentonv** [comment]
wat, I specifically remember writing what was allowed in the text below the input box. :/

**Comment by zarvox** [comment]
Also the text "Please match the requested format" also doesn't appear in our codebase anywhere, as far as I can tell.  I'm guessing this is the browser enforcing the pattern="^[a-z_][a-z0-9_]*$" before you even try submitting the form.

Maybe we should remove the pattern validator, if it's producing a worse user experience and we're going to validate it in JS anyway and provide a more helpful message?

**Comment by kentonv** [comment]
Right, the browser enforces form validity. The nice part about that is that the browser has built-in support for highlighting the invalid field and asking the user to fix it. Building our own seems like a lot of work, unless we use alert(), which I don't think would be a better UX.

Also the browser supports CSS-selecting for invalid input, which is how the box outline turns red as soon as you type an invalid character (which IMO is really nice -- it even makes it reasonably easy to figure out what's allowed without actually being told).

I think we just need to update the description text under the field to be more specific.

**Comment by zarvox** [comment]
Description text appears to be more descriptive now, so I think we're in the clear to close this.
