### ISSUE TITLE
Cannot access admin setting page after install.

### ISSUE THREAD

**Issue by nhducit** [sandstorm-io/sandstorm#989]
I follow installation guide in home page. 
```
curl https://install.sandstorm.io | bash
```
But I can access to admin setting page after install.
```
mydomain.sandcats.io/admin/settings/xxxx
```

I figure out that when I don't use https:// in url, it shows my router login page.

![screenshot from 2015-10-08 22 09 38](https://cloud.githubusercontent.com/assets/4246176/10370486/4d363eda-6e09-11e5-9b3c-278ac46355e0.png)

**Comment by kentonv** [comment]
This is a common bug in routers. Some routers will always return their admin page for any request coming from inside the network, even if the request is addressed to the router's external IP address. In fact, my own router has this problem! (But I've also had many routers in the past that worked correctly.)

Unfortunately, there isn't an easy way to fix or work around this.
* If you have your own DNS server within your internal network, then you could instruct it to override your particular sandcats address to point directly at your internal server, bypassing the router.
* You could get a different router, or switch your router to bridge mode and use a Linux machine as your NAT.
* Maybe your router supports OpenWRT or some other replacement firmware that is less broken.
* You could run your server on DigitalOcean or something instead.

Sorry there aren't any good options here. :/

**Comment by nhducit** [comment]
Thank you @kentonv I'l try and report later.

**Comment by nhducit** [comment]
chrome display this when access to localhost:80
```
Error looking up DNS TXT records for host 'localhost': queryTxt ECONNREFUSED

This Sandstorm server's main interface is at: https://nhduc.sandcats.io

The DNS server refused the connection, which means either your DNS server is down/unreachable,
or the server has misconfigured their DNS.

If you are the server admin and want to use this address as the main interface,
edit /opt/sandstorm/sandstorm.conf, modify the BASE_URL setting, and restart.

If you got here after trying to log in via OAuth (e.g. through Github or Google),
the problem is probably that the OAuth callback URL was set wrong. You need to
update it through the respective login provider's management console.
```

**Comment by kentonv** [comment]
@nhducit That looks like exactly what I'd expect it to show -- you need to access Sandstorm via the sandcats hostname or change the configuration as it says. You could, for example, set:

    BASE_URL=http://localhost
    WILDCARD_HOST=*.localhost

in `/opt/sandstorm/sandstorm.conf`, then do `sudo sandstorm stop; sudo sandstorm start`.

Of course, then your server will only be accessible on your own machine, not through sandcats.

**Comment by nhducit** [comment]
@kentonv after change /opt/sandstorm/sandstorm.conf file I got redirect loop error.

```
This webpage has a redirect loop

ERR_TOO_MANY_REDIRECTS
```

**Comment by kentonv** [comment]
@nhducit Oops, I think you'll need to remove `HTTPS_PORT` from the config, since your `BASE_URL` is now HTTP.

@paulproteus You might find this failure mode interesting. Perhaps the redirect logic should be based on the protocol specified in `BASE_URL` rather than based on the presence of `HTTPS_PORT`?

**Comment by kentonv** [comment]
Haha, I also accidentally clicked "close and comment".

**Comment by paulproteus** [comment]
@kentonv I lol'd re: you accidentally closing and commenting.

I am curious to know if @nhducit manages to fix their issue!

And yeah -- if HTTPS_PORT and the BASE_URL don't agree, the _least_ we can
do is log something. I guess it's arguably true we should only do the
redirecting if HTTPS_PORT is set _and_ the BASE_URL is https. Otherwise,
we're probably setting people up for disaster. I just wonder if there's
some further complexity I'm not realizing.

**Comment by nhducit** [comment]
@kentonv @paulproteus I made it. Thank you very much.

**Comment by nhducit** [comment]
"Close and comment" on purpose

**Comment by nhducit** [comment]
Today I switch to new router but when connect to domain.sandscat.io, it still returns router admin page. :)

**Comment by kentonv** [comment]
@nhducit Sorry to hear that. Unfortunately this bug is pretty common. :( If you try to open domain.sandcats.io from outside your network (e.g. try on a phone with wifi turned off), what do you see?
