### ISSUE TITLE
odd wakeup behavior and unable to switch grains

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#997]
When I wake my laptop in the morning, usually, I have to reload frames in order to get my workspace back, but today, that didn't work. Instead, I have this odd behavior:

![image](https://cloud.githubusercontent.com/assets/1584904/10401114/a806b7e6-6e71-11e5-8333-4a3b3c145e4d.png)

https://www.youtube.com/watch?v=NeREww_zeME

The things I did right before that are:
- reload frame for the grain that you see being active
- close that grain from the sidebar as well as close another grain that had a 404 from being asleep

Not sure if:
- any edits I make on the open grain on the right are saved (as it's technically not an open grain in the sidebar)

**Comment by jadeqwang** [comment]
Ok, yep, the "closed" grain that's still open on the right is definitely still open (since my edits to it are saved and I can see that when I open it in a new browser tab).

**Comment by jparyani** [comment]
Closing, as we haven't seen this issue in a while.
